autotest/tp-qemu

qemu/tests/block_discard.py
qemu/tests/cfg/block_discard.cfg

Add a step to get partitions in during time continuously since
it will spend some time in syncing the operation of
creating partitions.
ID: 1695500

block_discard: Add a step for checking partitions

---

qemu/tests/cfg/expose_host_mtu.cfg
qemu/tests/expose_host_mtu.py

expose_host_mtu: Add windows guests support

---

qemu/tests/cfg/mq_enabled_chk.cfg
qemu/tests/mq_enabled_chk.py

id: 1662268
Check nic mq which should be determined by smp and queues with ethtool -l

mq_enabled_chk: Add a new test case

---

qemu/tests/nic_bonding.py

All devices will loss some packets during set_link loop, Since we are
testing the bonding function of the guest, we should send the "ip link
set dev {iface} up/down" command inside the guest instead of sending the
"set_link" via qemu.
ID: 1698838

nic_bonding: Use 'ip link' instead of 'set_link'

---

qemu/tests/cfg/multi_disk.cfg
qemu/tests/multi_disk.py

Do iozone stress on the random data disks.
ID: 1572520

multi_disk: Add iozone stress step on random disks

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

virtio_scsi_cdrom: Support 32 bit guest

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Check if fsfreeze/thaw works in windows guest
ID: 1508306, 1544188

qemu-guest-agent: Verify FS is frozen or thaw in windows guest

---

qemu/tests/cfg/ioeventfd.cfg
qemu/tests/ioeventfd.py

1. Add a case that checks the ioeventfd property.
2. Restructure ioeventfd case with stress.
ID: 1607682

ioeventfd: Update ioeventfd case

---

qemu/tests/boot_nic_with_intel_iommu.py
qemu/tests/cfg/boot_nic_with_intel_iommu.cfg

Boot guest with intel_iommu=on in guest kernel cmd line
id: 1691263

boot_nic_with_intel_iommu: Add test case

---

generic/tests/boot.py
generic/tests/cfg/boot.cfg
generic/tests/cfg/reboot.cfg

Add serial login support for boot test

Add serial login support for boot test

---

provider/storage_benchmark.py

storage_benchmark: Clean the env files if failed to install benchmark

---

qemu/tests/cfg/memory_leak_after_nichotplug.cfg
qemu/tests/memory_leak_after_nichotplug.py

id: 1666145, 1688093
1. Do memory leak check after nic hotplug/hotunplug for windows
2. Do memory leak check after add/del vlan for linux

memory_leak_after_nichotplug: Add new case

---

qemu/tests/slof_device_tree.py

Get the last line of output of get_info();
Create a new function compare_dev_tree() to reduce code redundancy;
Decode output of process.system_output() for host_system_id;
ID: 1704652

slof_device_tree: Refactoring code 

---

qemu/tests/balloon_memhp.py
qemu/tests/cfg/balloon_memhp.cfg

ID: 1373062
Depens on https://github.com/avocado-framework/avocado-vt/pull/1975

balloon_memhp: Add new case to test balloon with memory hotplug

---

qemu/tests/cfg/timerdevice.cfg
qemu/tests/timerdevice_host_time_back.py

Also need to remove network device for the guest.
bud id: 1694576

timerdevice_host_time_back: define different results for different RHELs

---

qemu/tests/balloon_check.py

balloon_check: increase the default "balloon_timeout" value

---

qemu/tests/cfg/resize_qemu_img.cfg
qemu/tests/resize_qemu_img.py

rename the case name for qcow2 supports.
id: 1715291

added qemu img qcow2 cases

---

qemu/tests/rng_hotplug.py

extend_interval: extend interval between hotunplug and hotplug

---

qemu/tests/boot_without_vectors.py
qemu/tests/cfg/boot_with_different_vectors.cfg

id: 1664982, 1664272
1. boot_with_different_vectors.with_vectors/without_vectors
2. boot_with_different_vectors.with_vhostforce/without_vhostforce

boot_with_different_vectors: add new test case

---

qemu/deps/linux_qinq/qinq.sh
qemu/tests/bridge_qinq.py
qemu/tests/cfg/bridge_qinq.cfg

bridge_qinq: Add basic QinQ test

---

qemu/tests/cfg/vsock.cfg
qemu/tests/vsock_negative_test.py
qemu/tests/vsock_test.py

vsock: Add negative test cases

---

qemu/tests/boot_with_multiqueue.py
qemu/tests/cfg/boot_with_max_queues.cfg
qemu/tests/cfg/mq_enabled_chk.cfg

Add windows support for mq_check script
id: 1566965

mq_enabled_chk: Add multi-queue check for virtio-net on windows guest

---

qemu/tests/cfg/vsock.cfg
qemu/tests/vsock_hotplug.py
qemu/tests/vsock_negative_test.py

Add new case for hotplug vsock device
id: 1671211

vsock_hotplug: Add new case for hotplug vsock device

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

1. Read file with a large number count
2. Add error information(reason string) to OpenFileFailed error
ID: 1663069, 1566808

qemu-guest-agent: add more check for gagent_file_read function

---

qemu/tests/live_backup_base.py

Enable force_share flag to avoid shared write lock issue. Pause VM tto ensure image meta not change by running VM. And, destory VM before do compare image step to ensure image not change by VM during the comparison process.
Signed-off-by: XuTian <xutian@redhat.com>
ID: 1628432

fix write lock error in live backup test

---

qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/nic_hotplug.py

1 Add cases about "guest shutdown/reboot after hotplug netkvm“
2 Add cases about "guest shutdown/reboot after hot-unplug netkvm“
3 Add case of "hotplug hot-unplug" in a loop
id: 1702532 1702534 1668247

nic_hotplug: Add 5 cases related hotplug and hot-unlpug

---

provider/storage_benchmark.py
qemu/tests/cfg/fio_windows.cfg

Update the version of fio to the latest one.
ID: 1706741

fio: Update the version of fio

---

qemu/tests/cfg/commit_snapshot_to_raw_backing.cfg
qemu/tests/cfg/qemu_disk_img.cfg
qemu/tests/commit_snapshot_to_raw_backing.py
qemu/tests/qemu_disk_img_commit.py

id:  1719107
disk-format: New checkpoint - check the snapshot whether emptied after commitment

disk-format:  New checkpoint for snapshot commitment

---

qemu/tests/cfg/netkvm_cpu_mapping.cfg
qemu/tests/netkvm_cpu_mapping.py

Check traceview log and get correct cpu mapping infomation
id:1718715

Add new case for netkvm_cpu_mapping

---

qemu/tests/boot_with_multiqueue.py
qemu/tests/netkvm_cpu_mapping.py

modified "boot_with_multiqueue.py" and "netkvm_cpu_mapping.py"
id:1722511

Modify function name to match the function in utils_net.py

---

provider/block_dirty_bitmap.py
qemu/tests/cfg/live_backup_add_bitmap.cfg
qemu/tests/live_backup_add_bitmap.py

Aims to test bitmap addition for qcow2/raw images with persistent
on/off.

add case live_backup_add_bitmap

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

1.refactor gagent_check_get_vcpus function.
2.support windows guest.
ID: 1481508

qemu_guest_agent: support get_vcpus in windows guest

---

qemu/tests/cfg/driver_load.cfg
qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/single_driver_install.cfg
qemu/tests/cfg/spice.cfg
qemu/tests/cfg/virtio_console.cfg
qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/cfg/virtio_port_login.cfg
qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/cfg/virtio_serial_stop_continue.cfg
qemu/tests/cfg/win_virtio_serial_data_transfer_reboot.cfg
qemu/tests/qemu_guest_agent.py
qemu/tests/qemu_guest_agent_hotplug.py
qemu/tests/win_virtio_serial_data_transfer_reboot.py

chardev: multiple backend support

---

qemu/tests/cfg/watchdog.cfg
qemu/tests/watchdog.py

watchdog: Add watchdog action - inject-nmi

---

qemu/tests/cfg/commit_with_backing.cfg
qemu/tests/commit_with_backing.py
qemu/tests/qemu_disk_img.py

test qemu-img commit with option '-b', which specifies the layer to
commit to.

Add test case 'commit_with_backing'

---

qemu/tests/cfg/win_serial_tool_test.cfg
qemu/tests/win_serial_tool_test.py

1. Virtio serial data transfer via vioser-test.exe
2. Transfer data using benchmarking tool
ID: 1566875, 1566879

Add two new serial cases for windows guests

---

qemu/tests/block_hotplug.py
qemu/tests/cfg/block_hotplug.cfg

Add a case that hotplug a max image size disk with qcow2 and raw.
ID: 1564836

block_hotplug: Add a case that hotplug a max size disk

---

qemu/tests/cfg/virtio_console.cfg

virtio_console: fix RegEx to check qemu version

virtio_console: fix RegEx to check qemu version

---

qemu/tests/virtio_mode.py

virtio_mode: Update cmd to make it work in rhel6 guest

---

generic/tests/avocado_guest.py

refactor the code to adopt changes with AvocadoGuest() in utils_test.

avocado_guest: adopt the changes for AvocadoGuest()

---

qemu/tests/balloon_hotplug.py
qemu/tests/cfg/balloon_hotplug.cfg

Also update error message for unplug.
ID: 1714394, 1710669
Depends on https://github.com/avocado-framework/avocado-vt/pull/2096

balloon_hotplug: Add timeout value for unplug

---

generic/tests/cfg/unattended_install.cfg
qemu/tests/cfg/rh_kernel_update.cfg
qemu/tests/cfg/virtio_scsi_cdrom.cfg

Use 'backup_image_after_testing_passed' to backup image

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg

timedrift_check_clock_offset: update virtio serial

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

New case to test "guest-get-fsinfo"
ID: 1557247

qemu_guest_agent: Add case to test "guest-get-fsinfo"

---

qemu/tests/cfg/uefi_secureboot.cfg
qemu/tests/uefi_secureboot.py

Add test case for uefi secureboot

---

provider/backup_utils.py
provider/block_dirty_bitmap.py
provider/job_utils.py
qemu/tests/cfg/differential_backup.cfg
qemu/tests/differential_backup.py

detials steps see case RHEL-149271

add differental backup with a diabled bitmap test

---

qemu/tests/cfg/virtio_serial_empty_line.cfg

fix cfg file parameters which have been changed.
id:1728934
Signed-off-by: Nana Liu nanliu@redhat.com

fix parameters which have been changed

---

qemu/tests/cfg/virtio_mode.cfg
qemu/tests/cfg/win_irq_check.cfg
qemu/tests/cfg/win_serial_tool_test.cfg
qemu/tests/cfg/win_sigverif.cfg

Need to update cfg files in order to attach serial devices to vm.
ID: 1733049

Update windows serial cases due to chardev framwork changed

---

generic/deps/stress
generic/tests/linux_stress.py

made linux stress test use local stress package

---

qemu/tests/cfg/x86_cpu_model.cfg
qemu/tests/x86_cpu_model.py

Add new case to test EPYC, Skylake-Server and Skylake-Client.
ID: 1733063, 1733065, 1733062

x86_cpu_model: add new case to test three cpu models

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

1.rewrite function of gagent_check_get_interfaces
2.support windows guest
ID: 1566798

qemu_guest_agent:support windows guest for gagent_check_get_interfaces

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

start guest agent inside windows guest with isa-serial port
ID: 1457067

qemu_guest_agent: support isa-serial method for windows guest

---

qemu/tests/cfg/virtio_serial_empty_line.cfg

fix cfg file parameters format.
id:1728934

virtio_serial_empty_line:fix error params format

---

qemu/tests/block_resize.py
qemu/tests/cfg/block_resize.cfg

1. Add resize linux file system and partition steps.
2. Add iozone test after disk resize.
3. Add resize test on windows system disk.
id: 1481111 1390485 1411207

block_resize: update block resize test cases

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/virtio_serial_file_transfer.py

1. Support tcp socket
2. Support Windows guest better
3. Make it modulized and multiplexible
Depends on https://github.com/avocado-framework/avocado-vt/pull/2135
id: 1724987, 1231039

virtio_serial_file_transfer: Optimize test case

---

qemu/tests/block_during_io.py
qemu/tests/cfg/block_during_io.cfg

The data disk letters will be changed after reboot in windows, 
so fetch the letters again.
ID： 1731895

block_during_io: Fetch the drive letters again after reboot

---

qemu/tests/virtio_console.py

virtio_console: Avoid redundent destroy

---

qemu/tests/virtio_console.py

virtio_console: Remove autotest related steps

---

qemu/tests/cfg/check_link_speed_duplex.cfg
qemu/tests/check_link_speed_duplex.py

Check both default and specific speed
id:1725563

check_link_speed_duplex.py: Add new case for checking link speed and duplex

---

generic/tests/cfg/unattended_install.cfg

unattended_install.large_image: add configuration for RHEL8

---

qemu/tests/block_scsi_device.py
qemu/tests/cfg/block_scsi_device.cfg

New a case to test scsi device by deleting and scanning.
ID: 1731608

block_scsi_device: New a case to test scsi device

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: negative test of a nonexistent agent cmd

---

generic/tests/cfg/iozone_windows.cfg
generic/tests/iozone_windows.py

Add a new case to do iozone test for gpt format disk.
id: 1566836

Add new case iozone_windows.with_gpt_disk

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/virtio_serial_file_transfer.py

virtio_serial_file_transfer: Support pty backend

---

qemu/tests/aio_test.py
qemu/tests/cfg/aio_test.cfg

id:1740971
aims to verify all aio tests are passed.

add new case aio test

---

qemu/tests/block_hotplug_in_pause.py
qemu/tests/cfg/block_hotplug_in_pause.cfg

New a case that hot plug a disk then unplug it under the status
of vm is stopping, resume vm at last.
ID: 1703871

block_hotplug_in_pause: New a case that hotplug then unplug in pause

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py
qemu/tests/qemu_guest_agent_snapshot.py

1. windows guest support for qemu_guest_agent_snapshot
2. delete redundant parameter for gagent snapshot
3. enlarge the transfer data size
ID: 1543267 1508302

qemu-guest-agent: windows guest support for gagent snapshot test case 

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/virtio_serial_large_file_transfer.py

virtio_serial: Add test case for large file transfer

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent_update.py

New case of update qemu-ga-win without vioser driver installed
ID: 1735577

qemu_guest_agent: update qemu-ga-win without vioser driver installed

---

qemu/tests/cfg/virtual_nic.cfg
qemu/tests/virtual_nic_stress.py

Ping host when running heavyload stress tool
id:1737714

Add windows support for virtual_nic.with_stress

---

qemu/tests/cfg/hotplug_mem.cfg
qemu/tests/cfg/migrate.cfg
qemu/tests/cfg/numa_memdev_options.cfg

Add pre_command for some memory cases to drop cache before test

---

qemu/tests/qemu_nobody.py

qemu_nobody:int object has no attribute strip 
Signed-off-by: yiqian <yiqian@localhost.localdomain>

qemu_nobody:int object has no attribute strip 

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_console.py
qemu/tests/virtio_serial_hotplug_port_pci.py

virtio_serial: Add test case for port and pci hotplug

---

qemu/tests/cfg/virtio_mode.cfg

virtio_mode: remove rhel6 guest from modern driver case

---

qemu/tests/cfg/block_during_io.cfg

block_during_io.iozone_stress, enlarge iozone_timeout to 7200 seconds

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: new case to test migrate with qga running

---

qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/migration_after_nichotplug.py

Add hotunplug migration for migration_after_nichotplug.py
id:1668250

Add new case of "Migrate guest after NIC hot-unplug"

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Sync guest time after stop/cont vm with guest-set-time cmd.
ID: 1738390

qemu_guest_agent: new case of sync guest time after stop/cont vm

---

qemu/tests/cfg/netkvm_in_use.cfg

Change sub_test from pci_hotplug to nic_hotplug
id:1652415

 Fix could not find suitable method for hotplug drive

---

qemu/tests/qemu_guest_agent.py

The behavior of linux vm and windows vm is different
when run guest-exec cmd with capture_output is true.
id: 1745887

qemu-guest-agent: fix guest-exec issue

---

qemu/tests/block_stream_drop_backingfile.py

destroy vm before remove snapshot files

---

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg

qemu_guest_agent: bug fix of duplicate serial device id

---

provider/storage_benchmark.py

Make sure that the environment of making iozone is clean.
ID: 1753139

storage_benchmark: Update the command of making iozone

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_serial_various_chardev_hotplug.py

Add new case to hotplug and hot-unplug
various chardevs
id:1588424

chardev:Add test case for various chardevs hotplug

---

qemu/tests/cfg/serial_no_listening.cfg
qemu/tests/serial_no_listening.py

serial_no_listening: writing to a virtio serial port while no listening side

---

deps/input_event/input_event_linux.py
deps/input_event/input_event_win.py
provider/input_event_proxy.py

Add 3 new files input_event_win/linux.py and input_event_proxy.py to simulate input event listening in guest.
id: 1734841

Add 3 new files input_event_win/linux.py and input_event_proxy.py

---

provider/qemu_img_utils.py
qemu/tests/cfg/commit_with_backing.cfg
qemu/tests/commit_with_backing.py

1. add support for luks as base image
2. refactor the code with functions provided in
provider/qemu_img_utils.py

commit_with_backing: support luks

---

qemu/tests/cfg/seabios_scsi_lun.cfg
qemu/tests/seabios_scsi_lun.py

Add new seabios case for virtio-scsi device with lun not 0
ID: 1734202

seabios_scsi_lun: add new case for lun not 0

---

qemu/tests/cfg/qemu_img_convert_with_copy_offloading.cfg
qemu/tests/qemu_img_convert_with_copy_offloading.py

Add new case for 'qemu-img convert' with copy_offloading

disk_format: New case qemu_img_convert_with_copy_offloading

---

provider/block_devices_plug.py

New a class provides interfaces about hot plugging and unplugging block
devices by serial or threaded.
ID: 1702102

block_devices_plug: New class provides plugging block devices

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: new case of test guest-fstrim for windows vm

---

qemu/tests/cfg/seabios_hotplug_unplug.cfg
qemu/tests/seabios_hotplug_unplug.py

1.Check seabios boot menu after hotplug devices
2.Check seabios boot menu after hotunplug devices
ID: 1685913, 1469056

seabios_hotplug: add new cases for seabios

---

qemu/tests/cfg/luks_convert.cfg
qemu/tests/luks_convert.py

Add support of different cache modes in conversion from luks to luks.

luks_convert: support specification of cache mode

---

provider/qemu_img_utils.py
qemu/tests/cfg/image_convert_bypass_host_cache.cfg
qemu/tests/image_convert_bypass_host_cache.py

check if `cache_mode` is `none`, `O_DIRECT` is on for system call `open`
or `openat`(RHEL8).

convert_bypass_host_cache: add new case

---

generic/tests/pxe_boot.py

pxe_boot: Make test exit once found TFTP packet

---

qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
qemu/tests/hotplug_unplug_during_io_repeat.py

New a case that repeated hotplug/hot-unplug while
the device is busy serving I/O.
ID: 1231139

hotplug_unplug_during_io_repeat: New a case for testing plug

---

qemu/tests/cfg/cgroup.cfg
qemu/tests/cgroup.py

decode from bytes to str for python3
id: 1745847
Signed-off-by: Xiangchun Fu xfu@redhat.com

cgroup: Fix python3 str type issue

---

qemu/tests/cfg/unplug_block_during_io_reboot.cfg
qemu/tests/unplug_block_during_io_reboot.py

New a case that reboot after hot unplug a disk with IO stress test
running on it.
ID: 1703632

unplug_block_during_io_reboot: New case to test unplug block during io

---

qemu/tests/uefi_secureboot.py

uefi_secureboot: add vm destroy in the end

---

qemu/tests/cfg/multi_nics_verify.cfg
qemu/tests/multi_nics_verify.py

multi_nics_verify: Make sure qemu process exits

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_serial_hotplug_port_pci.py
qemu/tests/virtio_serial_hotplug_port_pci_chardev.py

virtio_serial: Hotplug pci and chardev and port orderly

---

qemu/tests/boot_1_N_virtserialports.py
qemu/tests/cfg/virtio_serial_file_transfer.cfg

Boot a guest with one virtio-serial-pci with three serial ports
ID:1588426 

virtio_serial:boot guest with multiple serials

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/hotplug_port_chardev_pci_with_console.py

virtio_serial:Hotplug chardev and port with a virtconsole

---

qemu/tests/cfg/raw_image_create_and_check.cfg
qemu/tests/raw_image_create_and_check.py

1. Create and write data to a image
2. Check the virtual and actual size info of the image
ID: 1766421

 New case of raw_image_create_and_check

---

qemu/tests/cfg/qemu_img_convert_image_with_unaligned_size.cfg
qemu/tests/qemu_img_convert_image_with_unaligned_size.py

Add new case for 'qemu-img convert' image with unaligned size
ID: 1760292

disk_format: New case qemu_img_convert_image_with_unaligned_size

---

qemu/tests/cfg/boot_with_max_queues.cfg

Add "only virtio_net" parameters
Signed-off-by: yanglei-rh <leiyang@redhat.com>
ID:1764436

boot_with_max_queues:only test virtio-net

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

New case of umount fs when fs is frozen
ID: 1726941

qemu_guest_agent: Add case of umount fs while fsfrozen

---

qemu/tests/boot_nic_with_intel_iommu.py
qemu/tests/x86_cpu_model.py

boot_nic_with_intel_iommu/x86_cpu_model: Fix import error

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

check guest agent logs via -v and -l parameters.
ID:1749255

qemu_guest_agent: new case of guest agent log check

---

qemu/tests/cfg/netkvm_change_param_value_test.cfg
qemu/tests/netkvm_change_param_value_test.py

1 change values of NetKVM parameters-enable/disable
2 change values of NetKVM parameters-multi option
3 change values of NetKVM parameters-modify value directly
id: 1745890, 1745892, 1745893

Add new case related changing values of NetKVM parameters

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/virtio_serial_file_transfer_max_ports.py

virtio_serial:boot with max virtserialports on one virtio-serial-pci

---

qemu/tests/cfg/block_with_share_rw.cfg

Update the config file to support virtio_blk.
ID: 1745981

block_with_share_rw: Support virtio_blk

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: Set default cpu model to 'host'

---

qemu/tests/cfg/device_option_check.cfg

Modify the configure file to support checking wwn and serial options
in ppc.
ID: 1769669

Add wwn and serial checking for spapr_vscsi:

---

qemu/tests/cfg/win_virtio_driver_update_test.cfg

Add new case: with_vioinput.device_keyboard..uninstall_install/downgrade_upgrade
id: 1456178 1764447

Add new case install_uninstall/downgrade_upgrade driver for virtio keyboard device

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: new case of online/offline memory blocks

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

new case of cheing guest agent status when no user login,only
for windows guest.
ID: 1761658

qemu_guest_agent: check agent status when no user logged in

---

qemu/tests/virtio_serial_file_transfer.py
qemu/tests/virtio_serial_large_file_transfer.py

virtio_serial:fix large_file_transfer issue

---

qemu/tests/cfg/openflow_acl_test.cfg
qemu/tests/openflow_acl_test.py

There are some problem when running openflow_acl_test. Fix them and
improve code.
ID: 1769624

openflow_acl_test: Fix bugs and improve code

---

qemu/tests/ovs_quit.py

This test case does not work now, fix bugs and improve code
ID: 1768681

ovs_quit: Fix bugs and improve code

---

qemu/tests/cfg/usb.cfg

remove piix4-uhic usb controller from window

---

qemu/tests/virtio_serial_hotplug_port_pci.py

virtio_serial:hot-unplug relative ports before hot-unplugging pci

---

qemu/tests/cfg/boot_order_check.cfg

Remove ovmf from boot_order_check

---

qemu/tests/cfg/block_with_share_rw.cfg

New cases to test usb-storage with share-rw

---

qemu/tests/cfg/ppc_change_smt.cfg
qemu/tests/ppc_change_smt.py

Add case to test smt state on ppc platform
ID: 1774817

ppc_change_smt: Add case to test smt state on ppc platform

---

provider/qemu_img_utils.py
qemu/tests/cfg/image_rebase_bypass_host_cache.cfg
qemu/tests/image_commit_bypass_host_cache.py
qemu/tests/image_convert_bypass_host_cache.py
qemu/tests/image_rebase_bypass_host_cache.py

id:1774452
check if rebase with cache mode `none`, flag `O_DIRECT` is on for open
or openat.

image_rebase_bypass_host_cache: add new case

---

qemu/tests/cfg/usb.cfg
qemu/tests/usb_basic_check.py

check dwProtocol for usb-ccid in linux guest

---

qemu/tests/cgroup.py

1.Fix VMStress function missing parameter's issue.
2.Fix qemu process control CPU utilization's issue.
id: 1770058

cgroup:Fix CPU utilization of cfs_bandwidth's issues

---

qemu/tests/cfg/seabios_bootmenu_prompt.cfg
qemu/tests/seabios_bootmenu_prompt.py

Checking boot menu prompts with more than 10 available boot devices
ID: 1743551

seabios_bootmenu_prompt: Add new case for more than 10 boot devices

---

qemu/tests/cfg/hotplug_block_resize.cfg
qemu/tests/hotplug_block_resize.py

New 8 cases:
1. Hot plug a block device then enlarge it, shutdown guest by qmp.
2. Hot plug a block device then enlarge it, shutdown guest by shel.
3. Hot plug a block device then enlarge it, reboot guest by qmp.
4. Hot plug a block device then enlarge it, reboot guest by shell.
5. Hot plug a block device then shrink it, shutdown guest by qmp.
6. Hot plug a block device then shrink it, shutdown guest by shell.
7. Hot plug a block device then shrink it, reboot guest by qmp.
8. Hot plug a block device then shrink it, reboot guest by shell.
ID: 1703910

hotplug_block_reszie: New cases to test hot plug block device then resize

---

qemu/tests/cfg/rebase_onto_qcow2.cfg
qemu/tests/rebase_onto_qcow2.py

id:1775528
add case to cover that rebase could change the backing file from
luks/raw to a new qcow2 image.

rebase_onto_qcow2: add new case

---

provider/qemu_img_utils.py
qemu/tests/cfg/luks_compare.cfg
qemu/tests/cfg/luks_convert.cfg
qemu/tests/luks_convert.py

id: 1777186
add new test case to compare luks images with different cache modes.

luks_compare: add new case

---

qemu/tests/cfg/image_compare_bypass_host_cache.cfg
qemu/tests/image_compare_bypass_host_cache.py

id:1777242
add new case to test `O_DIRECT` is on for `open` when cache mode is
`none`.

image_compare_bypass_host_cache: add new case

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Only for linux guest,test guest file operation when selinux is enabled.
ID: 1759466

qemu_guest_agent: new case of read/write guest file with selinux enabled

---

qemu/tests/cfg/openflow_test.cfg
qemu/tests/openflow_test.py

Remove hard code and improve code, wait a few seconds and check if
tcpdump is alive, otherwise it will report "Timeout expired while
looking for pattern '^\\[.*\\][\\#\\$]\\s*$'"
ID: 1768691

openflow_test: remove hard code and improve code

---

qemu/tests/cfg/guest_iommu_test.cfg
qemu/tests/guest_iommu_test.py

guest_iommu_test: add new case for guest iommu test

---

qemu/tests/cfg/ovs_host_vlan.cfg
qemu/tests/ovs_host_vlan.py

Fix netperf issue and kill vm at the end of the test.
ID: 1770060

ovs_host_vlan: fix netperf issue and kill vm at the end of the test

---

qemu/tests/cgroup.py

Fix sockets * dies * cores * threads < smp or maxcpus
id: 1766938

cgroup: Fix maxcpus and smp's issues

---

provider/backup_utils.py
provider/blockdev_backup_base.py
provider/blockdev_backup_parallel.py
provider/blockdev_full_backup_base.py
provider/blockdev_full_backup_parallel.py
provider/job_utils.py
provider/virt_storage/backend/base.py
provider/virt_storage/backend/directory.py
provider/virt_storage/exception.py
provider/virt_storage/helper/fscli.py
provider/virt_storage/storage_admin.py
provider/virt_storage/storage_volume.py
provider/virt_storage/utils/state.py
provider/virt_storage/utils/storage_util.py
provider/virt_storage/virt_auth.py
provider/virt_storage/virt_device.py
provider/virt_storage/virt_encryption.py
provider/virt_storage/virt_secret.py
provider/virt_storage/virt_source.py
provider/virt_storage/virt_target.py
qemu/tests/blockdev_full_backup_reboot.py
qemu/tests/blockdev_full_backup_simple.py
qemu/tests/blockdev_full_backup_stress.py
qemu/tests/cfg/blockdev_full_backup.cfg
qemu/tests/cfg/blockdev_full_backup_multi_disks.cfg
qemu/tests/cfg/differential_backup.cfg
qemu/tests/differential_backup.py

ID: 1783860,  1783861, 1783845, 1783844, 1783843, 1783842, 1783866, 1783867,1784237

Add blockdev full backup test

---

qemu/tests/cfg/multi_vms_with_stress.cfg
qemu/tests/multi_vms_with_stress.py

New a case to test multiple VMs under running stress on host.
ID: 1731466

multi_vms_with_stress: New case to test multiple VMs with stressing

---

qemu/tests/cfg/image_rebase_bypass_host_cache.cfg

id:1783102
fix bug due to backup non-existent snapshot.

image_rebase_bypass_host_cache: fix backup

---

provider/blockdev_snapshot_base.py
qemu/tests/blockdev_snapshot.py
qemu/tests/cfg/blockdev_snapshot.cfg

add block device snapshot test

---

provider/backup_utils.py
provider/blockdev_stream_base.py
qemu/tests/blockdev_stream.py
qemu/tests/cfg/blockdev_stream.cfg

add case for block stream feature

---

provider/storage_benchmark.py

storage_benchmark: support compile iozone on aarch64

---

provider/block_dirty_bitmap.py
qemu/tests/bitmap_boundary_test.py
qemu/tests/cfg/bitmap_boundary_test.cfg

add case to test 65536 persistent bitmaps

---

provider/backup_utils.py
provider/blockdev_backup_base.py
provider/job_utils.py
qemu/tests/blockdev_full_mirror.py
qemu/tests/cfg/blockdev_full_mirror.cfg

add bockdev full mirror test

---

qemu/tests/cfg/nic_opt.cfg
qemu/tests/nic_opt.py

ID: 1585582 1624809 1624808 1631348
Signed-off-by: yanglei-rh <leiyang@redhat.com>,Sitong Liu siliu@redhat.com

Add four case for options test.

---

provider/backup_utils.py
qemu/tests/blockdev_commit.py
qemu/tests/cfg/blockdev_commit.cfg

add base block commit test

---

qemu/tests/cfg/seabios_order_once.cfg
qemu/tests/seabios_order_once.py

Add seabios new cases for boot option order/once
ID: 1734201

seabios_order_once: add boot option order/once cases

---

qemu/tests/cgroup.py

Fix python3 TypeError
id: 1768391, 1766953

cgroup: Fix python3 TypeError issue

---

qemu/tests/cfg/convert_to_virtual_disk.cfg
qemu/tests/convert_to_virtual_disk.py

1. Create input and output images.
2. Setup loop device with the output image.
3. Convert the input image to the loop device.
ID: 1788805

New case of convert_to_virtual_disk

---

qemu/tests/cfg/numa_opts.cfg
qemu/tests/numa_opts.py

numa_opts: Set maxcpus equal to smp

---

qemu/tests/block_with_write_threshold.py
qemu/tests/cfg/block_with_write_threshold.cfg

Add a case that test to change the write threshold for a block drive.
ID: 1731472

block_with_write_threshold: Add case to test the write threshold

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: verify the blacklist of guest agent

---

qemu/tests/cfg/rng_stress.cfg

rng_stress: add support for new backend 'rng-builtin'

---

qemu/tests/cfg/virtio_serial_basic.cfg

ID: 1746246
Depends on [avocado-framework/#2393](https://github.com/avocado-framework/avocado-vt/pull/2393)

virtio_serial:boot tcp_socket chardev with qmp monitor

---

qemu/deps/playbook.yml
qemu/deps/setup_bridge.sh
qemu/tests/cfg/nested_test.cfg
qemu/tests/nested_test.py

Add nested test cases.

---

qemu/tests/cfg/remote_block_resize.cfg
qemu/tests/remote_block_resize.py

1. Only ceph was supported
2. Extended and shrinked ceph image
ID: 1786240

Supported ceph image's extending and shrinking

---

qemu/tests/virtio_port_hotplug.py

virtio_serial: fix 'NoneType' issue while transferring data

---

qemu/tests/cfg/ioeventfd.cfg
qemu/tests/ioeventfd.py

ID: 1755682
Depends on [avocado-framework/avocado-vt#2376](https://github.com/avocado-framework/avocado-vt/pull/2376)

virtio_serial: test ioeventfd property with virtio_serial_pci

---

qemu/tests/cfg/x86_cpu_model.cfg
qemu/tests/x86_cpu_model.py

x86_cpu_model: Update approach to get supported cpu models

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_serial_unplug_port_chardev_pci.py

virtio_serial:Hot-unplug port and chardev and pci

---

qemu/tests/cfg/remote_image_convert.cfg
qemu/tests/remote_convert.py

1. Added cfg/remote_image_convert.cfg
2. The following testing scenarios are covered:
remote -> local -> remote
remote -> remote
ID: 1786234, 1786235

Supported iscsi and ceph images' convert

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: refactor case of check 'fsfreeze-hook' script's path

---

qemu/tests/cfg/vsock.cfg
qemu/tests/migration_with_vsock.py
qemu/tests/vsock_test.py

Add testcase for migration with vsock
ID: 1781088

Add testcase for migration with vsock

---

qemu/tests/blockdev_snapshot_reboot.py
qemu/tests/cfg/blockdev_snapshot_reboot.cfg

blockdev_snapshot_reboot:do snapshot during guest reboot
Signed-off-by: aliang123 <aliang@redhat.com>
id: 1798920

Snapshot during guest reboot for blockdev

---

qemu/tests/blockdev_snapshot_stop_cont.py
qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg

blockdev_snapshot_stop_cont: snapshot during guest stop_cont
id: 1800428

Snapshot during guest stop_cont

---

qemu/tests/cfg/image_create_with_large_size.cfg
qemu/tests/image_create_with_large_size.py

Test creating/resizing an image with large size.
ID: 1797850

New case of image_create_with_large_size

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/virtio_serial_file_transfer_offline_migrate.py

virtio_serial: offline_migration with virtio serial devices

---

qemu/tests/block_resize_unplug.py
qemu/tests/cfg/block_resize_unplug.cfg

New a case that resizes a disk then reboot VM and unplug this disk
at last.
ID: 1731614

block_resize_unplug: New case to resize disk then reboot VM and unplug

---

qemu/tests/block_stream_drop_backingfile.py

block_stream_drop_backingfile: fix encoding issue in re.search()
Signed-off-by: meet-lucky <qdong@redhat.com>
id:1640052

Fix the pattern format

---

provider/block_devices_plug.py
qemu/tests/block_hotplug_scsi_hba.py
qemu/tests/cfg/block_hotplug_scsi_hba.cfg

Add cases that test hotplug scsi hba with the options
"hotplug=on" and "hotplug=off".
ID: 1731615

block_hotplug_scsi_hba: Add cases to test options of hotplug scsi hba

---

qemu/tests/block_auto_detect_size_increased.py
qemu/tests/cfg/block_auto_detect_size_increased.cfg

New a case that checks the size fo disk increased could
be detected automatically.
ID: 1731617

New case to check disk size increased can be detected automatically

---

qemu/tests/block_check_event.py
qemu/tests/cfg/block_check_event.cfg

New a case to check whether the event id 158 is logged.
ID: 1777131

block_check_event: New case to check event id in windows log

---

generic/tests/guest_test.py

guest_test: using safe mode when execute cmd with serial session

---

qemu/tests/cfg/hugepage_mem_stress.cfg
qemu/tests/hugepage_mem_stress.py

New case to test qemu hugepage memory stress
ID: 1786687

hugepage_mem_stress: New case to test qemu hugepage memory stress

---

qemu/tests/nic_opt.py

Does not compile netperf package
ID:1792856

Remove the compilation options "--enable-demo=yes"

---

qemu/tests/cfg/create_large_raw_img.cfg
qemu/tests/create_large_raw_img.py

Test creating large raw images on different file systems.
ID: 1801538

New case of create_large_raw_img

---

qemu/tests/nested_test.py

Add vendor variant check in nested test case.
ID: 1804521

Add vendor variant check in nested test case

---

qemu/tests/cfg/trim_support_test.cfg
qemu/tests/trim_support_test.py

Test the disk size when boot with "discard=map"
id:1783896

New case of trim support test for windows guest

---

qemu/tests/cfg/multi_nics_reboot.cfg

1.Reboot guest multiple times with multiple NICs
ID: 1805551

Add one case of virtual network

---

generic/deps/iometer/iometer_multi_3disks.icf
generic/deps/iometer/iometer_multi_4disks.icf
generic/tests/cfg/iometer_windows.cfg
generic/tests/iometer_windows.py

New a case to test the multiple disks at the same time.
ID: 1566862

iometer_windows: New case to test multiple disks

---

provider/backup_utils.py
provider/blockdev_backup_base.py
provider/blockdev_base.py
qemu/tests/blockdev_inc_backup_test.py
qemu/tests/cfg/blockdev_inc_backup_test.cfg

ID: 1804177,  1804180,  1804184, 1804192, 1804199, 1804206

add blockdev incremental backup tests

---

qemu/tests/cfg/uefi_boot_from_device.cfg
qemu/tests/uefi_boot_from_device.py

1. boot from ide-hd/ide-cd
2. boot from scsi-hd/scsi-cd
3. boot from virtio-blk
4. boot from usb-storage
ID: 1805245, 1805246, 1805270, 1805273, 1805282

add new case "uefi_boot_from_device"

---

qemu/tests/qemu_guest_agent.py

Read guest file with large count, sometimes it success and
sometimes it will prompt reasonable error info,both of them
are acceptable
ID: 1752735

qemu_guest_agent: fix issue of read guest file with a large count

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
qemu/tests/qemu_guest_agent.py

1.support qga package(fast train) installation of rhel8 guest
2.install the latest package of rhel8
ID: 1776718

qemu_guest_agent: install qemu-guest-agent on rhel8 guest

---

qemu/tests/cfg/virtio_mode.cfg

rng_builtin: add 'rng-builtin' support for virtio_mode.with_viorng

---

provider/input_event_proxy.py
qemu/tests/cfg/vioinput_mice.cfg
qemu/tests/vioinput_mice.py

Two new case:
vioinput_mice.device_mouse
vioinput_mice.device_table
id: 1724060, 1724061

Add new case vioinput_mice.device_mouse/device_tablet

---

qemu/tests/cfg/blockdev_inc_backup_cluster_test.cfg

add cases to test backup image with different cluster_size

---

qemu/tests/watchdog.py

fix pci watchdog plug into pcie.0 issue

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

1. check network with ipv4
2. check network with ipv6
ID: 1807914

add new case: uefishell.check_network

---

qemu/tests/cfg/check_reports_end_offset.cfg
qemu/tests/check_reports_end_offset.py

1. Create a test qcow2 image.
2. Check there is image end offset with both
"json" and "human" output.
ID: 1786420

New case of check_reports_end_offset

---

qemu/tests/seabios.py

Until catching the second boot menu hint displaying after rebooting,
then send the boot menu key.
ID: 1802150

seabios_basic: optimize testing procedure

---

qemu/tests/cfg/vioinput_keyboard.cfg
qemu/tests/cfg/vioinput_mice.cfg

Check virtio-input driver functions well with iommu_platform=on
ID: 1783824

New case: Add iommu support for virtio input driver

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

add new case: uefishell.check_memory_map

---

qemu/tests/blockdev_snapshot_chains.py
qemu/tests/cfg/blockdev_snapshot_chains.cfg

blockdev_snapshot_chains:support maxium chain check
id:1811519

Live snapshot:Maximum snapshot chain check

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: correct flag name for Icelake cpu model

---

provider/backup_utils.py
provider/virt_storage/storage_volume.py
qemu/tests/blockdev_inc_backup_bitmap_mode_test.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_mode_test.cfg

New test case to test bitmap mode option for blockdev backup

---

qemu/tests/cfg/remote_image_snapshot.cfg
qemu/tests/qemu_disk_img.py
qemu/tests/qemu_disk_img_info.py

1. Added cfg/remote_image_snap.cfg
2. TC change for remote images
ID: 1778550 1778552

Supported snapshot for the remote iscsi and ceph images

---

qemu/tests/cfg/resize_short_overlay.cfg
qemu/tests/resize_short_overlay.py

Check the data after resizing short overlay over longer backing files.
ID: 1811588

New case of resize_short_overlay

---

qemu/tests/cfg/usb.cfg

usb_storage: add support for testing usb-storage under usb-hub

---

qemu/tests/cfg/uefi_check_debugcon.cfg
qemu/tests/uefi_check_debugcon.py

Verify the "-debugcon" parameter under the UEFI environment.
ID: 1813922

add new case: uefi_check_debugcon

---

qemu/tests/cfg/uefi_pkg.cfg
qemu/tests/uefi_pkg.py

Verify descriptor meta-files on the host.
ID: 1815447

add new case: uefi_check_descriptor_meta-files

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: new cast to test fsfreeze hook script

---

qemu/tests/cfg/virtio_serial_throttling.cfg
qemu/tests/virtio_serial_throttling.py

ID:  1798383
depend on : avocado-framework/avocado-vt#2430, https://github.com/avocado-framework/avocado-vt/pull/2477

induce throttling by opening chardev but not reading data from it

---

provider/backup_utils.py
provider/blockdev_base.py
qemu/tests/blockdev_inc_backup_bitmap_mode_test.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_mode_test.cfg

Signed-off-by: XuTian <xutian@redhat.com>
ID: 1816513

add blockdev backup sync top test

---

qemu/tests/cfg/x86_cpu_model.cfg
qemu/tests/x86_cpu_model.py

ID: 1817806, 1817323, 1817324, 1817807, 1817326

x86_cpu_model: Add some -noTSX cpu models

---

qemu/tests/cfg/nested_test.cfg
qemu/tests/nested_test.py

ID: 1816458
Add  l2_kar_options option for L2 guest

Add l2_kar_options option for L2 guest

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: Add '-cpu host' test case

---

qemu/deps/virtio-trace/Makefile
qemu/deps/virtio-trace/README
qemu/deps/virtio-trace/trace-agent-ctl.c
qemu/deps/virtio-trace/trace-agent-rw.c
qemu/deps/virtio-trace/trace-agent.c
qemu/deps/virtio-trace/trace-agent.h
qemu/tests/cfg/virtio_chardev_trace.cfg
qemu/tests/virtio_chardev_trace.py

add testcase for virtio-trace support testing
id: 1786555
@nanliu-r please help review
depends on: avocado-framework/avocado-vt#2430
signed-off-by: Micky Yun Chan <michan@redhat.com>

add testcase for virtio-trace support testing

---

qemu/tests/qemu_guest_agent.py

Fail to issue qga command after qga is started up.
ID: 1670248

qemu_guest_agent: fix issue of isa-serial backend

---

qemu/tests/block_hotplug_passthrough.py
qemu/tests/cfg/block_hotplug_passthrough.cfg

Hotplug/unplug passthrough disk test:
1) Create passthrough disk with scsi_debug tool.
2) Start the guest.
3) Hotplug this passthrough disk.
4) Create partition on this disk and format it.
5) Do iozone/dd test on this disk.
6) Reboot the guest.
7) Unplug this passthrough disk.
id: 1813212

Add new case block_hotplug_passthrough

---

qemu/tests/cfg/qemu_img_compare.cfg
qemu/tests/cfg/rebase_second_snapshot_to_base.cfg

Support some cases both for luks and luks-inside-qcow2.
ID:1818734

Delete the format limit for some cases

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_serial_hotplug_max_chardevs.py

virtio_serial:Hotplug max chardevs on one virtio serial pci

---

deps/key_keycode/key_to_keycode_win.json
provider/input_tests.py
qemu/tests/cfg/vioinput_hotplug.cfg
qemu/tests/vioinput_hotplug.py

new cases:
vioinput_hotplug.device_keyboard
vioinput_hotplug.device_mouse
vioinput_hotplug.device_tablet
Create new file input_tests.py in provider directory,
including functions of input related tests.
id: 1748160, 1748154, 1748163, 1748161, 1748155, 1748156

Add new case vioinput_hotplug of virtio keyboard/mouse/tablet device

---

qemu/tests/cfg/chardev_free_port.cfg
qemu/tests/chardev_free_port.py

ID: 1792851
depends on https://github.com/avocado-framework/avocado-vt/pull/2411

add testcase for chardev a free port value

---

qemu/tests/cfg/usb.cfg
qemu/tests/format_disk.py
qemu/tests/usb_storage.py

1.Add clean dmesg step before test in format_disk
2.Add clean partition step at the end of test in format_disk
3.Add hotplug/hotunplug support for usb-storage
ID: 1802011

usb_hotplug_unplug: add hotplug/hotunplug support for usb-storage

---

qemu/tests/cfg/usb.cfg

usb_storage: add rerror and werror options for usb-storage device

---

qemu/deps/playbook.yml

ID: 1814562
To avoid duplicated deployment of kar on L1 guest. 

Avoid duplicated deployment of kar on L1 guest

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_port_hotplug.py
qemu/tests/virtio_serial_file_transfer.py

virtio_serial:Hot-unplug port during data transferring

---

qemu/tests/blockdev_commit_query_named_block_nodes.py
qemu/tests/cfg/blockdev_commit_query_named_block_nodes.cfg

blockdev_commit_query_named_block_nodes: add support
for query_named_block_nodes during live commit
id: 1820429

Support query_named_block_nodes during live commit

---

qemu/tests/cfg/ept_test.cfg
qemu/tests/ept_test.py

ept_test: New case to test when ept is off

---

qemu/tests/cache_sizes_test.py
qemu/tests/cfg/cache_sizes_test.cfg

Test different cache sizes in a guest.
ID: 1814185

New case of cache_sizes_test

---

provider/blockdev_commit_base.py
qemu/tests/blockdev_commit_reboot.py
qemu/tests/cfg/blockdev_commit_reboot.cfg

blockdev_commit_reboot:commit during guest reboot
id: 1820491

Commit during guest reboot

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_port_hotplug.py

virtio-serial:Keep chardev open to re-use

---

qemu/tests/cfg/chardev_acpi.cfg
qemu/tests/chardev_acpi.py

add test for acpi description of serial and parallel ports correctness

---

qemu/tests/cfg/uefi_check_debugcon.cfg

disable windows guest for case uefi_check_debugcon

---

qemu/tests/cfg/thin_provision_check_mode.cfg
qemu/tests/thin_provision_check_mode.py

Add new case checking provisioning mode

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Get timezone,hostname and active users info via qga and check the result in guest.
ID: 1809416

qemu_guest_agent: new case to get basic info of vm

---

qemu/tests/cfg/qmp_command.cfg
qemu/tests/qmp_command.py

qmp_command:add command "query-target"
ID:1823311

qmp_command:add command "query-target"

---

qemu/tests/cfg/chardev_free_port.cfg
qemu/tests/chardev_free_port.py

chardev:remove the force drive parameter

---

qemu/tests/cfg/hv_check_cpu_utilization.cfg
qemu/tests/hv_check_cpu_utilization.py

Check host cpu utilization for each vcpu is less than 5% when
guest is idle with all hv flags
id: 1821603

check_cpu_utilization: cpu utilization check with all hv flags

---

qemu/tests/cfg/thin_provision_guest_fstrim.cfg
qemu/tests/thin_provision_guest_fstrim.py

Add new test case execute guest-fstrim to guest agent

---

qemu/tests/blockdev_commit_stop_cont.py
qemu/tests/cfg/blockdev_commit_stop_cont.cfg

blockdev_commit_stop_cont:commit during guest stop/cont
id: 1820515

Commit during guest stop/cont

---

qemu/tests/blockdev_commit_stress.py
qemu/tests/cfg/blockdev_commit_stress.cfg

Commit during guest's stress test
id:1823707

blockdev_commit_stress:commit during stress test

---

qemu/tests/cfg/hv_reset.cfg
qemu/tests/hv_reset.py

Reboot guest with hv_reset flag
id: 1825123

reboot_with_hv_reset: hv_reset function test for windows guest

---

qemu/tests/eject_media.py

Since the argument "id" in qmp command "blockdev-open-tray" is
different between virtio-scsi and virtio-blk for the non-removable
media, actually it depends on the "qdev" value from the command
"query-block".
ID: 1783872

eject_media: Fix blockdev open tray non cdrom with virtio-blk

---

qemu/tests/cfg/virtio_blk_with_discard_write_zeroes.cfg
qemu/tests/virtio_blk_with_discard_write_zeroes.py

New case to test the options discard and write_zeroes with
the boundary value by the positive and negative way.
ID: 1822043

New case to test discard and write_zeroes with boundary value

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Get operationg system info of vm via qga.
ID: 1813118

qemu_guest_agent: new case to get os info of vm

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

ID: 1826200
Depends on https://github.com/avocado-framework/avocado-vt/pull/2522.

nvdimm: add new case to test option pmem

---

provider/job_utils.py
qemu/tests/blockdev_commit_top.py
qemu/tests/cfg/blockdev_commit_top.cfg

blockdev_commit_top: commit with active overlay as top-node

---

qemu/tests/cfg/msi_change_flag.cfg
qemu/tests/msi_change_flag.py

1.Check vhost could be enabled when msi-x is disabled
ID: 1819088

Add an new case for netdev option

---

provider/cpu_utils.py

Sometimes when we kill a background process, will hit
'ShellStatusError', it's because the background process had been
launched with the same session and the pattern could not handle the
output, use 'setsid' can avoid this problem.
ID: 1826158

cpu_utils: Use "setsid" instead of "nohup" to run background command

---

qemu/deps/playbook.yml
qemu/tests/cfg/nested_test.cfg
qemu/tests/nested_test.py

ID: 1780520
Add nested verify CPU models test case

Add nested verify CPU models test case

---

qemu/tests/cfg/chardev_legacy_unplug.cfg
qemu/tests/chardev_legacy_unplug.py

hot unplug chardevs while guest attached with isa-serial (RHEL and x86 only)
id: 1818729

hot unplug chardevs while guest attached with isa-serial

---

qemu/tests/blockdev_commit_install.py
qemu/tests/cfg/blockdev_commit_install.cfg

Commit during guest installation
id:1828140

blockdev_commit_install:commit during guest installation

---

qemu/tests/cfg/remote_block_resize.cfg

Support resize for gluster storage backend

---

qemu/tests/cfg/migration_with_remote.cfg

Support migration for gluster storage backend(local)

---

qemu/tests/cfg/remote_image_convert.cfg

Support image convert for gluster storage backend

---

qemu/tests/cfg/remote_image_snapshot.cfg
qemu/tests/qemu_disk_img_info.py

gluster storage backend: support snapshot

---

qemu/tests/cfg/remote_negative.cfg
qemu/tests/remote_server_disconnected.py

guest backend pass to another active gluster server
when the first gluster server went down
ID: 1816134

gluster storage backend: gluster server disconnected

---

qemu/tests/cfg/remote_image_multiwrite.cfg
qemu/tests/remote_image_multiwrite.py

Storage backends: ceph/gluster/iscsi_direct
ID: 1820061, 1820062, 1820063

Support multiwrite to data disk for RHEL guests

---

qemu/tests/cfg/remote_block_hotplug.cfg

Support block hotplug for gluster storage backend

---

qemu/tests/cfg/hugepage_mem_stress.cfg
qemu/tests/hugepage_mem_stress.py

New case boot a guest with a non-existent mem-path.
ID: 1805568

with_non-existent_mem-path: New case boot a guest with a non-existent mem-path

---

qemu/tests/blockdev_snapshot_install.py
qemu/tests/cfg/blockdev_snapshot_install.cfg

Snapshot during guest installation
id:1831968

blockdev_snapshot_install:snapshot during guest installation

---

qemu/tests/cfg/mq_change_qnum.cfg
qemu/tests/cfg/pktgen.cfg
qemu/tests/pktgen.py

1.Modify "server_session" to let it raise Exception
ID:1829661 1710793

RHEL.8 is no longer test pktgen

---

qemu/tests/cfg/hv_time.cfg
qemu/tests/hv_time.py

Execute the gettime_cycles.exe to verify the flag "hv_time"
id: 1827459

hv_time: verify hv_time flag performance on windows guest

---

qemu/tests/cfg/vioser_in_use.cfg
qemu/tests/vioser_in_use.py

Vcpu hotplug test during data transfer via serial.
ID: 1566881

vioser_in_use: add case of vcpu hotplug

---

qemu/tests/cfg/hugepage_specify_node.cfg
qemu/tests/hugepage_specify_node.py

New case to test qemu allocate hugepage from node.
ID: 1804073

hugepage_specify_node: New case to test qemu allocate hugepage from node

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

set invalid dometime to vm via guest agent
ID: 1826629

qemu_guest_agent: set invalid dometime to vm

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg

virtio-serial:fix value of parameter serial_bus_*

---

qemu/tests/boot_N_M_virtserialports.py
qemu/tests/cfg/virtio_serial_file_transfer.cfg

ID: 1804138
Depends on [avocado-vt/#2514](https://github.com/avocado-framework/avocado-vt/pull/2514)

virtio-serial:boot guest with multiple virtio-serial-pcis

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg

timedrift_check_clock_offset: add guest agent link for rhel8 guest

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/virtio_serial_hotplug_existed_port_pci.py

 Add existed virtio serial port and serial bus

---

qemu/tests/cfg/hpt.cfg

Add new case for hpt guest with huge page backend
ID: 1839601,1839603
Signed-off-by: mdeng <mdeng@redhat.com>

power_hpt_mmu_test: add new case for hpt guest with huge page backend

---

qemu/tests/cfg/mmu_basic.cfg
qemu/tests/mmu_basic.py

New case to test disabling radix MMU mode on guest.
ID: 1835135, 1835141

mmu_basic: New case to test disabling radix MMU mode on guest

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/chardev_remove_pending_watches.py

virtio_serial:Remove pending watches after virtserialport unplug

---

qemu/tests/cfg/insert_media.cfg
qemu/tests/insert_media.py

New a case that inserts a media in the blockdev mode.
ID: 1822053

insert_media: New case that inserts media in blockdev mode

---

qemu/tests/cfg/hv_crash.cfg
qemu/tests/hv_crash.py

QEMU process will quit after nmi with hv_crash flag
id: 1836095

hv_crash: function test with hv_crash

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_mapsync.py

nvdimm_mapsync: add new case to test MAP_SYNC

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: add case to test EPYC-Rome cpu model

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Get virtio device of windows guest.
ID: 1824430

qemu_guest_agent: new case to get virtio device of vm

---

qemu/tests/cfg/hv_reset.cfg
qemu/tests/cfg/hv_time.cfg
qemu/tests/hv_reset.py
qemu/tests/hv_time.py

change hv_time and hv_reset case to this format.
id:1840970

hyper_v: Change hv flags to 'all features' against 'all but one'

---

provider/block_devices_plug.py

block_devices_plug: Support plug secret object

---

qemu/tests/cfg/slof_user_interface.cfg

1.slof could scan scsi id from 0 to 63 for vscsi adaptor
2.slof could scan channel id from 0 to 7 for vscsi adaptor
ID: 1837184, 1837188

slof_user_interface: Add two cases for slof

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_mode.py

ID: 1843844
Depends on https://github.com/avocado-framework/avocado-vt/pull/2585

nvdimm_mode: Add new case to test change nvdimm mode inside guest

---

qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/virtio_fs_readonly.py

New case to test virtio-fs with mounting by read-only options.
ID: 1809584

virtio_fs_readonly: New case to test virtio-fs with read-only

---

qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/virtio_fs_multi_vms.py

New cases to test virtio-fs with the multolple VMs and virtiofsd
daemons.
ID: 1809595, 1809596

virtio_fs_multi_vms: New cases to test virtio-fs with VMs and daemons

---

qemu/tests/aio_test.py
qemu/tests/boot_nic_with_intel_iommu.py
qemu/tests/cpu_device_hotplug_maximum.py
qemu/tests/guest_iommu_test.py
qemu/tests/kernbench.py
qemu/tests/multi_vms_nics.py
qemu/tests/nested_test.py
qemu/tests/nic_opt.py
qemu/tests/softlockup.py
qemu/tests/timedrift.py
qemu/tests/timedrift_with_multi_vms.py
qemu/tests/tsc_drift.py
qemu/tests/x86_cpu_model.py

Cpu library is getting refactored through this
PR https://github.com/avocado-framework/avocado/pull/3350,
This PR modified respective test code to reflect the same.

Adopt Avocado cpu library changes

---

qemu/tests/cfg/cdrom_block_size_check.cfg

Fix data plane on scsi_cd issue

---

qemu/tests/cfg/queues_number_test.cfg
qemu/tests/queues_number_test.py

Add one case for enable/disable multi queues repeatedly

---

qemu/tests/cfg/hotplug_mem_negative.cfg
qemu/tests/hotplug_mem_negative.py

hotplug_mem_negative: Fix 'no valid keyword' issue

---

qemu/tests/qemu_guest_agent.py

Sometimes the latest module comes out,
but qemu-guest-agent pkg is not ready, so it will
induce test fail.
ID: 1846192

qemu_guest_agent: fix bug of qga pkg installation

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

nvdimm_hotplug: add new case to test hotplug nvdimm device

---

qemu/tests/win_virtio_driver_update_test.py

1. after driver downgrade test, vm is rebooted twice.
2. add enable driver verifier step.
ID: 1842760

win_virtio_driver_update: fix issue of reboot twice after downgrade driver

---

qemu/tests/pci_bridge.py

pci_bridge: update list devices returned by disk_hotplug for BLOCKDEV compatibility

---

qemu/tests/cfg/usb.cfg

usb_multi_disk: add "msdos" labeltype for Windows guest

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add guest-fsfreeze-freeze-list function and reorganise
the function related to fsfreeze.
ID: 1817348

qemu_guest_agent: new case of guest-fsfreeze-freeze-list

---

qemu/tests/ioeventfd.py

Disable data plane for ioeventfd is off

---

qemu/deps/performance/start_testpmd.py
qemu/tests/cfg/virtio_net_dpdk.cfg
qemu/tests/virtio_net_dpdk.py

performance: add case "Virio with qemu vhost Back end in DPDK"

---

qemu/tests/boot_e1000e_with_cpu_flag.py
qemu/tests/cfg/boot_e1000e_with_cpu_flag.cfg

Add one case for Windows cpu model flag

---

qemu/tests/cfg/qmp_command.cfg
qemu/tests/qmp_command.py

qmp_command:add command "query-machines"
ID: 1824495

qmp_command:add command "query-machines"

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: Update model_pattern for some cpu models

---

qemu/tests/cfg/virtio_trace_pipenb.cfg
qemu/tests/virtio_trace_pipenb.py

id: 1848293
depends on: [avocado-framework/avocado-vt#2400](https://github.com/avocado-framework/avocado-vt/pull/2400)

virtio-serial:Under named-pipe non-blocking testing

---

qemu/tests/cfg/win_nics_teaming.cfg
qemu/tests/win_nics_teaming.py

Windows nic teaming test

---

qemu/tests/cfg/hv_cpu_hotplug.cfg

Do cpu hotplug with all the default flags
id: 1849520

hv_cpu_hotplug: CPU hotplug with all flags

---

qemu/tests/cfg/timedrift_adjust_time.cfg

timedrift_adjust_time: update time difference for windows guest

---

qemu/tests/cfg/chardev_pci_serial_login.cfg
qemu/tests/chardev_pci_serial_login.py

id: 1848285
depends on: [avocado-framework/avocado-vt#2566](https://github.com/avocado-framework/avocado-vt/pull/2566)

virtio-serial:verify login functions of pci-serial

---

qemu/tests/cfg/smbios_default_check.cfg
qemu/tests/smbios_default_check.py

Add test case to test default smbios strings in qemu
id:1846227

Add test case to test default smbios strings in qemu

---

qemu/tests/cfg/hv_vapic_test.cfg
qemu/tests/hv_vapic_test.py

Test disk io with fio tool in windows guest
id:1849519

hv_vapic_test: evaluate storage performance when adding "hv_vapic"

---

qemu/tests/cfg/remote_image_snapshot.cfg
qemu/tests/qemu_disk_img_info.py

snapshot test on nbd

---

qemu/tests/cfg/remote_block_hotplug.cfg

block_hotplug_with_remote_storage: support nbd storage

---

qemu/tests/cfg/migration_with_remote.cfg

migration_with_remote_storage: support nbd

---

qemu/tests/cfg/remote_image_convert.cfg
qemu/tests/remote_convert.py

Convert remote image to local image
Convert local image to remote image
Convert remote image to remote image
ID: 1845050, 1845053

remote_image_convert: support nbd storage backend

---

qemu/tests/block_hotplug.py
qemu/tests/block_multifunction.py
qemu/tests/cfg/block_multifunction.cfg

block_multifunction: New test for block device with multifunction

---

qemu/tests/qemu_img.py

Support nvme storage backend for creating test.
ID: 1850608

qemu_img: Support nvme storage backend for creating test

---

provider/nbd_image_export.py

Support nbd image export with internal server and qemu-nbd

---

provider/backup_utils.py
provider/blockdev_base.py
qemu/tests/blockdev_inc_backup_pull_mode_test.py
qemu/tests/cfg/blockdev_inc_backup_pull_mode_test.cfg

Do incremental live backup via pull mode

---

qemu/tests/blockdev_commit_server_down.py
qemu/tests/cfg/blockdev_commit_server_down.cfg

remote storage server down/up when doing live commit

---

qemu/tests/virtio_serial_hotplug_port_pci.py

chardev:fix unclear error message

---

qemu/tests/block_hotplug_in_pause.py

Add a step to verify the deleted event after unplug block device.
ID: 1846976

block_hotplug_in_pause: Add step to verify the deleted event

---

qemu/tests/block_multifunction.py
qemu/tests/block_multifunction_scale.py
qemu/tests/cfg/block_multifunction.cfg

block_multifunction: New test for hotplug block with multifunction

---

qemu/tests/cfg/hv_check_cpu_utilization.cfg
qemu/tests/hv_check_cpu_utilization.py

check cpu utilization after migration
id: 1849523

hv_check_cpu_utilization: migration windows guest with all flags

---

generic/tests/pxe_boot.py
qemu/tests/pxe_query_cpus.py

1.debug.log is too big to load
ID: 1850346

Add test parameters to reduce debug.log output

---

qemu/tests/cfg/fio_linux.cfg
qemu/tests/cfg/fio_windows.cfg
qemu/tests/fio_linux.py
qemu/tests/fio_windows.py

Support nvme storage backend。
ID: 1850390

fio: Support nvme storage backend

---

qemu/tests/cfg/remote_image_snapshot.cfg
qemu/tests/qemu_disk_img_info.py

remote_image_snapshot: Support curl storage backend

---

qemu/tests/cfg/hv_tlbflush.cfg
qemu/tests/hv_tlbflush.py

Using hv_tlbflush_code.exe tool to evaluate time.
id: 1851687

hv_tlbflush.py: Evaluate the execution time with flags "hv_tlbflush"

---

qemu/tests/cfg/nvme_plug.cfg
qemu/tests/nvme_plug.py

New a case that hot plug and unplug with an NVMe device.
ID:  1851284

nvme_plug: New case to test hot plug and unplug NVMe device

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg

timedrift_check_clock_offset: add gagent_restart_cmd

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flags.py
qemu/tests/x86_cpu_model.py

new case: Support memory protection key

---

generic/tests/pktgen_perf.py

the kernel modules move to package kernel-modules-internal instead
for rhel8
id: 1854702

pktgen_perf: add kernel-modules-internal install for rhel8

---

generic/tests/pktgen_perf.py

pktgen_perf: fix duplicate code

---

qemu/tests/eject_media.py

The filename is json format if the image format is luks.
ID: 1842846

eject_media: Support luks format

---

qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg

The name is changed in avocado,also should change here.

virtio-fs: update memory backend config

---

qemu/tests/cfg/balloon_memhp.cfg
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cfg/hotplug_mem.cfg
qemu/tests/cfg/hotplug_mem_negative.cfg
qemu/tests/cfg/numa_opts.cfg
qemu/tests/numa_opts.py

Also remove some cases which can't triggered by libvirt
ID: 1854713
Depends on https://github.com/avocado-framework/avocado-vt/pull/2649.

Update some numa related case to use memdev option

---

qemu/tests/cfg/uefi_check_resolution.cfg
qemu/tests/uefi_check_resolution.py

new case :Verify UEFI config setting in the GUI screen
id:1857610

new case : Verify UEFI config setting in the GUI screen

---

qemu/tests/cfg/mq_change_qnum.cfg

1.Delete parameters "image_snapshot = yes"
2.Add other parameters to clone the guest
ID:1860733

Change the clone guest method

---

generic/tests/cfg/unattended_install.cfg

Reduce the number of disks in unattended installation

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

Reduce the number of disks in virtio_scsi_cdrom installation

---

qemu/tests/cfg/remote_image_snapshot.cfg
qemu/tests/qemu_disk_img_info.py

remote_image_snapshot: support ssh storage backend

---

qemu/tests/cfg/hotplug_mem_negative.cfg

hotplug_mem_negative: Update match keywords

---

qemu/tests/cfg/memhp_threads.cfg
qemu/tests/memhp_threads.py

ID: 1859801
Depends on https://github.com/avocado-framework/avocado-vt/pull/2664.

memhp_threads: Add case to test prealloc_threads

---

qemu/tests/virtio_net_dpdk.py

virtio_net_dpdk: remove usless linefeed

---

qemu/tests/cfg/numa.cfg
qemu/tests/numa_consistency.py

numa_consistency: Update the threshold on ppc

---

qemu/tests/block_with_write_threshold.py

The filename is json format if the image format is luks, so
need to parse them and to get block device node name by filename
item instead of file item.
ID: 1838898

block_with_write_threshold: Support luks format

---

qemu/tests/cfg/device_option_check.cfg
qemu/tests/device_option_check.py

Add step to check serial number length with sg_vpd.exe tool.
ID: 1822908

Add serial number length check with sg_vpd.exe tool for blk device

---

qemu/tests/cfg/spapr_vty_console_login.cfg

New case to test spapr-vty device to login and hot-unplug.
id:1865726,1865795

spapr_vty: New case to test spapr-vty device to login and hot-unplug

---

qemu/tests/cfg/uefi_check_boot_option.cfg
qemu/tests/uefi_check_boot_option.py

new case:Verify Boot Option Support under UEFI environment
id:1861574

new case:Verify Boot Option Support under UEFI environment

---

qemu/tests/boot_with_remote_readonly_image.py
qemu/tests/cfg/remote_readonly_storage.cfg
qemu/tests/curl_cookie_with_secret.py
qemu/tests/remote_image_qemu_info_access.py

ID: 1851658, 1851659, 1851660, 1851657

Curl image access test

---

qemu/tests/cfg/slof_hugepage.cfg

correct the params' key values which includes 'mem1'
ID:1862900

Update cfg info for slof_hugepage

---

qemu/tests/cfg/x86_cpu_flags.cfg

x86_cpu_flags:new case to test amd flags

---

qemu/tests/blockdev_inc_backup_inc_success.py
qemu/tests/cfg/blockdev_inc_backup_inc_success.cfg

Incremental backup with sync:incremental,bitmap-mode:on-success

---

provider/blockdev_base.py
qemu/tests/blockdev_inc_backup_non_persistent_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_non_persistent_bitmap.cfg

Incremental backup with none-persistent bitmap

---

qemu/tests/cgroup.py

Fix sockets * dies * cores * threads < smp_cpus
id: 1245899

cgroup:Fix cpu topology issue

---

qemu/tests/blockdev_inc_backup_xpt_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_xpt_bitmap.cfg

Expose data image with persistent bitmap via qemu-nbd

---

qemu/tests/cfg/hpt_max_page_size.cfg
qemu/tests/hpt_max_page_size.py

1. Update hpt guest verification timeout
2. Update re search criteria
ID: 1843286

hpt_max_page_size: Update hpt guest verification timeout

---

qemu/tests/blockdev_inc_backup_with_guest_agent.py
qemu/tests/cfg/blockdev_inc_backup_with_guest_agent.cfg

Do incremental backup with guest-agent

---

qemu/tests/blockdev_inc_backup_resize.py
qemu/tests/cfg/blockdev_inc_backup_resize.cfg

block_resize a qcow2 image with persistent bitmap stored on it

---

qemu/tests/cfg/tpm_verify_device.cfg
qemu/tests/tpm_verify_device.py

ID: 1861265, 1861271, 1861273, 1861274

tpm_verify_device: New cases to verify TPM devices

---

qemu/tests/blockdev_inc_backup_with_migration.py
qemu/tests/cfg/blockdev_inc_backup_with_migration.cfg

Do incremental live backup with bitmap after migrated on shared storage

---

qemu/tests/cfg/balloon_check.cfg
qemu/tests/cfg/block_with_iommu.cfg
qemu/tests/cfg/boot_nic_with_intel_iommu.cfg
qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cfg/guest_iommu_test.cfg
qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/vioinput_keyboard.cfg
qemu/tests/cfg/vioinput_mice.cfg
qemu/tests/cfg/virtio_net_dpdk.cfg
qemu/tests/cfg/virtio_serial_file_transfer.cfg

Depends on https://github.com/avocado-framework/avocado-vt/pull/2726
id: 1866233

iommu: Add device intel-iommu before all virtio devices

---

qemu/tests/cfg/tpm_unattended_install.cfg
qemu/tests/tpm_unattended_install.py

tpm_unattended_install: New case to test unattended install with tpm

---

provider/block_dirty_bitmap.py
qemu/tests/blockdev_inc_backup_pull_mode_diff.py
qemu/tests/cfg/blockdev_inc_backup_pull_mode_diff.cfg

Do differential live backup via pull mode

---

qemu/tests/cgroup.py

Fix limits broken issue
id: 1872090

cgroup.cpu_share: increase the limits to fix limits broken issue

---

qemu/tests/virtio_net_dpdk.py

virtio_net_dpdk: gather the result from the next to last line

---

qemu/tests/cfg/tpm_with_bitlocker.cfg
qemu/tests/tpm_with_bitlocker.py

New case to test virtual TPM device by BitLocker inside window guest.
ID: 1861614

tpm_with_bitlocker: New case to test virtual TPM device by BitLocker

---

provider/block_devices_plug.py

Improve throttle support on hotplug-unplug

---

provider/throttle_utils.py

Add throttle utils and test

---

qemu/tests/ept_test.py

ept_test: Fix CmdError

---

qemu/tests/cfg/chardev_acpi.cfg
qemu/tests/chardev_acpi.py

chardev_acpi:change the method of checkpoint

---

provider/backup_utils.py
provider/blockdev_mirror_base.py
provider/blockdev_mirror_nowait.py
provider/blockdev_mirror_parallel.py
provider/blockdev_mirror_wait.py
qemu/tests/blockdev_mirror_multiple_blocks.py
qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg

Multiple blocks mirror simultaneously

---

qemu/tests/cfg/numa_opts.cfg
qemu/tests/numa_opts.py

depends on:  https://github.com/avocado-framework/avocado-vt/pull/2699
id: 1859028

numa_opts: check numa info in guest os

---

qemu/tests/cfg/numa_cpu.cfg
qemu/tests/numa_cpu.py

id: 1859025
depends on: 
https://github.com/avocado-framework/avocado-vt/pull/2699
https://github.com/avocado-framework/avocado-vt/pull/2725

numa_cpu: Assign cpu to numa node with '-numa cpu' in cmdline

---

qemu/tests/cfg/cpu_info_check.cfg
qemu/tests/cpu_info_check.py

Add test cases to check cpu related information

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add steps to setting new hostname and check it in guest.
ID: 1853556
Signed-off-by: Dehan Meng \<demeng@redhat.com\>

qemu_guest_agent: Get hostname after change it in guest

---

qemu/tests/blockdev_mirror_stress.py
qemu/tests/cfg/blockdev_mirror_stress.cfg

Basic block mirror test with stress -- only system disk

---

qemu/tests/blockdev_mirror_sync_none.py
qemu/tests/cfg/blockdev_mirror_sync_none.cfg

Block mirror with sync mode:none

---

provider/backup_utils.py
qemu/tests/blockdev_mirror_error.py
qemu/tests/cfg/blockdev_mirror_error.cfg

Block mirror with '"on-source-error": "stop", "on-target-error": "stop"'

---

qemu/tests/blockdev_mirror_simple.py
qemu/tests/cfg/blockdev_mirror_simple.cfg

1. granularity
2. buf-size
ID: 1877988, 1877990

Block mirror simple test with options

---

provider/cpu_utils.py
qemu/tests/x86_cpu_flags.py
qemu/tests/x86_cpu_model.py

provider/cpu_utils:move function to provider.cpu_utils

---

qemu/tests/cfg/ple_test.cfg
qemu/tests/ple_test.py

ple_test: Add new case to test ple

---

qemu/tests/blockdev_mirror_vm_reboot.py
qemu/tests/cfg/blockdev_mirror_vm_reboot.cfg

Basic block mirror during vm reboot -- only system disk

---

qemu/tests/blockdev_mirror_vm_stop_cont.py
qemu/tests/cfg/blockdev_mirror_vm_stop_cont.cfg

Basic block mirror during vm stop_cont -- only system disk

---

qemu/tests/cfg/remote_image_convert.cfg

Add nbd compression convert cases, remote to remote and remote to local

---

qemu/tests/chardev_hotplug.py

chardev_hotplug: Disable it on ppc since pci-serial is not supported

---

qemu/tests/cfg/x86_cpu_flags.cfg

cpu_flag:new cases to test cpu flags

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flag_disable.py

x86_cpu_flags:test flag disabled

---

qemu/tests/cfg/numa_dist.cfg
qemu/tests/numa_dist.py

1.Config guest with symmetric numa distance,check if it is in effect
2.Config guest with asymmetric numa distance,check if it is in effect
depends on: https://github.com/avocado-framework/avocado-vt/pull/2755
id: 1877259, 1877262

numa_dist: new case to config guest with different numa distance

---

qemu/tests/cfg/cpu_model_inter_generation.cfg
qemu/tests/cpu_model_inter_generation.py

cpu_model_inter_generation: New test case added

---

qemu/tests/cfg/qemu_img_check_fragmentation.cfg
qemu/tests/qemu_img_check_fragmentation.py

qemu_img_check_fragmentation: new case to check file fragmentation

---

qemu/tests/cfg/mq_change_qnum.cfg
qemu/tests/cfg/queues_number_test.cfg

Change the iteration number of multi queues

---

qemu/tests/blockdev_mirror_sync_top.py
qemu/tests/cfg/blockdev_mirror_sync_top.cfg

Blockdev mirror test with sync mode top

---

qemu/tests/blockdev_inc_backup_after_commit.py
qemu/tests/cfg/blockdev_inc_backup_after_commit.cfg

blockdev_inc_backup_after_commit: add block incremental backup test after block commit

---

qemu/tests/blockdev_mirror_install.py
qemu/tests/cfg/blockdev_mirror_install.cfg

Block-mirror test with VM installation

---

provider/backup_utils.py
provider/blockdev_stream_nowait.py
qemu/tests/blockdev_stream_install.py
qemu/tests/cfg/blockdev_stream_install.cfg

Block stream test with vm installation

---

qemu/tests/cfg/blockdev_inc_backup_with_throttling.cfg

blockdev_inc_backup_with_throttling: Add incremental backup test with throttling

---

provider/throttle_utils.py
qemu/tests/cfg/throttle_parameter_test.cfg
qemu/tests/throttle_parameter_test.py

ID:1883065,1883066,1883067,1883068,1883069,1883070,1883071,1883072,1883073

Add throttle general parameters test

---

provider/blockdev_stream_base.py
provider/blockdev_stream_parallel.py
qemu/tests/blockdev_stream_vm_reboot.py
qemu/tests/cfg/blockdev_stream_vm_reboot.cfg

block stream test with vm reboot

---

qemu/tests/blockdev_stream_stress.py
qemu/tests/cfg/blockdev_stream_stress.cfg

blockdev_stream_stress: add stream test with stress

---

qemu/tests/blockdev_stream_vm_stop_cont.py
qemu/tests/cfg/blockdev_stream_vm_stop_cont.cfg

blockdev_stream_vm_stop_cont: add stream test with vm stop/cont

---

qemu/tests/blockdev_stream_subchain.py
qemu/tests/cfg/blockdev_stream_subchain.cfg

data -> sn1 -> sn2 -> sn3
block-stream: {device: sn3, base-node: sn1}
ID: 1882960

blockdev_stream_sub_chain: Add stream test with sub snapshot chain

---

qemu/tests/blockdev_stream_multiple_blocks.py
qemu/tests/cfg/blockdev_stream_multiple_blocks.cfg

Do block-stream for at least two images in parallel
ID: 1882251

blockdev_stream_multiple_blocks: add stream test with several blocks

---

qemu/tests/cfg/macvtap_guest_communicate.cfg
qemu/tests/macvtap_guest_communicate.py

Guests communicate with vepa mode macvtap

---

qemu/tests/cfg/image_create_with_preallocation.cfg
qemu/tests/image_create_with_preallocation.py

image_create_with_preallocation: new case to check preallocation mode

---

qemu/tests/cfg/unattended_install_reboot_driftfix.cfg
qemu/tests/unattended_install_reboot_driftfix.py

check guest boot status w/o driftfix=slew (only windows)
ID: 1874708

adding new timer device case

---

qemu/tests/apicv_test.py
qemu/tests/cfg/apicv_test.cfg

apicv_test: Add new case to test apicv

---

qemu/tests/cfg/migrate.cfg
qemu/tests/migration_with_netperf.py

migrate.with_netperf.tcp: LoginTimeoutError: Login timeout expired

---

qemu/tests/cfg/microcode_test.cfg
qemu/tests/microcode_test.py

microcode_test: Add case to test microcode version is passed to guest

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model: filter case by cpu vendor

---

qemu/tests/cfg/kvm_unit_test_nested.cfg
qemu/tests/kvm_unit_test_nested.py

Add kvm_unit_test on host for nested test
ID: 1882626

Run kvm_unit_test on host for nested test

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Changed a key word of filter for matching more accurate values
ID: 1746341

qemu_guest_agent: Changed a key word of filter

---

qemu/tests/cfg/x86_cpu_flags.cfg

x86_cpu_flags:add new case to test flag smap

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Support sharing data between host and guest for windows guest.
ID: 1878611, 1878613, 1878615, 1878617

virtio-fs: new case of share data between host and win guest

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Fio test on shared file system in windows guest.
ID: 1889557, 1889558, 1889559

virtio-fs: new case of fio test in win guest

---

qemu/tests/cfg/qemu_img_measure.cfg
qemu/tests/qemu_img_measure_convert_image.py

qemu_img_measure_convert_image: add support for luks format

---

qemu/tests/cfg/numa_cpu.cfg
qemu/tests/numa_cpu.py

numa_cpu: config cpu numa mapping at preconfig state

---

qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/virtio_fs_multi_vms.py
qemu/tests/virtio_fs_share_data.py

Support sharing data between windows vms.
ID: 1889560

virtio-fs: new case of share data between vms

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_test_dies.py

x86_cpu_flags:new case to test dies topology

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flags.py

x86_cpu_flags:new case test flag arch-capabilities

---

qemu/tests/blockdev_mirror_readonly.py
qemu/tests/cfg/blockdev_mirror_readonly.cfg

blockdev_mirror_readonly: block mirror on readonly device

---

qemu/tests/ansible_test.py
qemu/tests/cfg/ansible_test.cfg

Add multi guests support in ansible_test
ID: 1891434

Add multi guests support in ansible_test

---

qemu/tests/cfg/chardev_pci_serial_login.cfg
qemu/tests/cfg/spapr_vty_console_login.cfg
qemu/tests/chardev_serial_login.py

New case to test guest with '-vga none' and spapr-vty device
ID:1865729

spapr_vty_console_login: New case to test '-vga none' device

---

qemu/tests/block_discard_hotplug.py
qemu/tests/cfg/block_discard_hotplug.cfg

Add hotpluging testing with discard disk

---

provider/cpu_utils.py
qemu/tests/cfg/smt_test.cfg
qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/cfg/x86_cpu_model.cfg
qemu/tests/smt_test.py

smt_test: add case to test smt

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flags.py

x86_cpu_flags:add parameter 'HostCpuVendor'

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add checkpoint 'file system usage statistics' and check it.
ID: 1857505

qemu_guest_agent: Add new checkpoint for 'fsinfo'

---

qemu/tests/cfg/cpu_model_negative.cfg
qemu/tests/cpu_model_negative.py

cpu_model_negative: Add new test case

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add case that check qga.service status after remove it.

---

qemu/tests/cfg/numa_negative.cfg
qemu/tests/numa_negative.py

numa_negative: numa options negative test

---

provider/throttle_utils.py
qemu/tests/cfg/throttle_parameter_test.cfg

Improve sampling accuracy
ID:1895818,1895822,1895821,1895823,1895824,1895826

Add throttle mix parameter case

---

qemu/tests/cfg/balloon_check.cfg

balloon_check..iommu_enabled: Add guest restriction

---

qemu/tests/cfg/steal_time.cfg
qemu/tests/steal_time.py

steal_time: Add new case to test steal time

---

provider/blockdev_base.py
qemu/tests/blockdev_mirror_firewall.py
qemu/tests/cfg/blockdev_mirror_firewall.cfg

Break connection by inserting a rule by iptables when doing
blockdev-mirror, remove the rule, blockdev-mirror should succeed
Signed-off-by: zhencliu <zhencliu@redhat.com>
ID: 1893930

blockdev_mirror_firewall: block mirror with firewall test

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flag_nonstop_tsc.py

x86_cpu_flags:test flag nonstop_tsc

---

qemu/tests/cfg/x86_cpu_model.cfg
qemu/tests/x86_cpu_model.py

x86_cpu_model: support Cooperlake model

---

qemu/tests/virtio_fs_share_data.py

fix the md5 value cannot be updated
ID: 1897036

virtio_fs_share_data: fix the md5 value cannot be updated

---

qemu/tests/cfg/migration_with_numa.cfg
qemu/tests/migration_with_numa.py

migration_with_numa: bind guest node to host node and do migration

---

provider/blockdev_base.py
qemu/tests/blockdev_mirror_speed.py
qemu/tests/cfg/blockdev_mirror_speed.cfg

Set speed with block-job-set-speed:
for an invalid speed: check the proper error message
for a valid speed: check job is still running
ID: 1896589

blockdev_mirror_speed: mirror speed test

---

qemu/tests/cfg/x86_cpu_L3_cache.cfg
qemu/tests/x86_cpu_L3_cache.py

x86_cpu_L3_cache: Check L3 cache inside guest

---

qemu/tests/cfg/multi_nics_verify.cfg

Change the number of e1000e devices from multi_nics_verify.cfg

---

qemu/tests/cfg/cpu_device_hotplug_during_boot.cfg
qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cfg/hv_cpu_hotplug.cfg
qemu/tests/cfg/invalid_cpu_device_hotplug.cfg

Update ovmf restriction for cpu hotplug test cases

---

provider/backup_utils.py
qemu/tests/blockdev_mirror_filternode.py
qemu/tests/cfg/blockdev_mirror_filternode.cfg

blockdev_mirror_filternode: Add block mirror filter-node-name test
ID: 1898035

Mirror filter-node-name test

---

qemu/tests/cfg/x86_cpu_flags.cfg

x86_cpu_flags: fix incorrect dies topology issue

---

qemu/tests/cfg/qmp_command.cfg

list the pci,pcie and all devices
ID:1896275

qmp_command:add command qom-list-types

---

provider/backup_utils.py
provider/blockdev_base.py
provider/blockdev_stream_base.py
provider/job_utils.py
qemu/tests/blockdev_stream_no_space.py
qemu/tests/cfg/blockdev_stream_no_space.cfg

blockdev_stream_no_space: stream to an image without enough space
ID: 1898421

Stream to an image without enough space

---

qemu/tests/blockdev_stream_hotunplug.py
qemu/tests/cfg/blockdev_stream_hotunplug.cfg

hotunplug frontend device: Succeeded
hotunplug format node: CHeck the proper error message output
ID: 1902371

blockdev_stream_hotunplug: Add hotunplug test during stream

---

qemu/tests/cfg/hotplug_mem.cfg

hotplug_memory: Add option test for hotplug cases

---

qemu/tests/cfg/hpt.cfg
qemu/tests/hpt_miscellaneous.py

id:1900445
Signed-off-by: MiriramDeng <mdeng@redhat.com>

hpt_resize_migration:resize hpt and do migration on ppc

---

qemu/tests/blockdev_stream_general.py
qemu/tests/cfg/blockdev_stream_general.cfg

job-cancel/job-resume/job-pause/auto-finalize/auto-dismiss
ID: 1902534

blockdev_stream_general: Add general block stream test

---

qemu/tests/cfg/check_link_speed_duplex.cfg

e1000e do not include speed and duplex property

---

qemu/tests/cfg/dump_guest_core.cfg
qemu/tests/dump_guest_core.py

add the limitation of arch and fix related issue in dump_guest_core.py
ID:1888531

Fix arch related issue of dump_guest_core.py

---

qemu/tests/cfg/hotplug_mem_stress_ng.cfg
qemu/tests/hotplug_mem_stress_ng.py

hotplug_mem_stress_ng: Run stress-ng test after hotplug memory

---

qemu/tests/cfg/hotplug_mem_simple.cfg
qemu/tests/hotplug_mem_simple.py

hotplug_mem_simple: Add new case to test hotplug memory

---

qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/rng_maxbytes_period.py

rng_maxbytes_period: add max-bytes/period cases for virtio-rng device

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_negative.py

nvdimm_negative: Add case to test negative align option

---

qemu/tests/cfg/cpu_model_negative.cfg

cpu_model_negative:fix warning msg

---

qemu/tests/cfg/block_hotplug_check.cfg
qemu/tests/pci_hotplug_check.py

ID:1733761,1511800
1.Add blockdev support
2.Improve test efficiency
3.Remove redunant command check
4.Add q35 support

block_hotplug_check:Fix unknown version of qemu issue

---

qemu/tests/cfg/x86_cpu_flags.cfg

x86_cpu_flags:new case to test mce=off

---

qemu/tests/cfg/time_conv.cfg
qemu/tests/time_conv.py

qemu-img - measure qemu-img convert time
id: 1900458

adding case of time qemu-img convert

---

qemu/tests/boot_with_disable_ept.py
qemu/tests/cfg/boot_with_disable_ept.cfg

boot_with_disable_ept:boot guest after disable ept/npt
ID:1905332

new case development:boot guest after disable ept/npt

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

nvdimm_nvml: Add new case to do nvml test

---

qemu/tests/block_performance_test.py
qemu/tests/cfg/block_performance_test.cfg

block_performance_test:test disk performance with queue-size/num-queues
ID:1898864,1898862

block_performance_test: test disk performance with queue-size/num-queue

---

qemu/tests/blockdev_stream_on_error_ignore.py
qemu/tests/cfg/blockdev_stream_on_error_ignore.cfg

blockdev_stream_on_error_ignore: stream test with on-error:ignore

---

qemu/tests/cfg/qemu_img_check_data_integrity.cfg
qemu/tests/qemu_img_check_data_integrity.py

1. add case "kill_qemu_during_io"
2. add case "kill_qemu_after_io"
ID: 1906992, 1906993, 1906994, 1906995

qemu.test: qemu_img_check_data_integrity

---

generic/tests/cfg/nfs_corrupt.cfg
generic/tests/nfs_corrupt.py

ID: 1906319, 1906406, 1906408, 1906417

nfs_corrupt: add raw and luks format support

---

qemu/tests/uefi_check_debugcon.py

uefi_check_debugcon:fix the problem of lack of trace-cmd package
ID:1907713

Fix the problem of lack of trace-cmd package

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flags.py

x86_cpu_flags:test flag virt-ssbd

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flag_intel_pt.py

x86_cpu_flags:add new flag intel-pt

---

qemu/tests/balloon_uniqueness.py
qemu/tests/cfg/balloon_uniqueness.cfg

balloon_uniqueness: Verify qemu only support one balloon device

---

deps/hlk/hlk_studio.ps1
provider/win_hlk_suite.py
qemu/tests/cfg/tpm_with_hlk.cfg
qemu/tests/tpm_with_hlk.py

tpm_with_hlk: New case to test vTPM with HLK

---

qemu/tests/cfg/nic_bonding.cfg
qemu/tests/nic_bonding.py

nic_bonding: Change script code because of logic error

---

generic/tests/iozone_windows.py

For iozone_windows case will be called as a sub-case by other cases.
after system_reset during iozone test on the vioscsi/viostor data disk,
found the the disk letter of iozone tested disk changed.Before iozone
test, disk letter is "I", after system_reset disk letter changed to "E".
It is a product bug but closed as WONTFIX, so need to workaround it in
automation.If found the disk letter changed, drop the origin disk letter
then reset the disk letter to the target letter.
ID: 1829709

iozone_windows: Reset disk letter if disk letter change after iozone

---

qemu/tests/timerdevice_boot.py

timerdevice_boot: adding timeout parameter

---

qemu/tests/blockdev_stream_backing_file.py
qemu/tests/cfg/blockdev_stream_backing_file.cfg

blockdev_stream_backing_file: stream test with backing-file option

---

provider/blockdev_live_backup_base.py
qemu/tests/blockdev_inc_backup_rm_persistent_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_rm_persistent_bitmap.cfg

Persistent bitmaps removal test

---

qemu/tests/qemu_guest_agent.py

QGA version higher than 5.0 so that the count number need to
limited lower than 48M.
ID: 1843355

qemu-guest-agent: Changed 'guest-file-read' count parameter

---

provider/block_devices_plug.py
qemu/tests/cfg/multi_disk_random_hotplug.cfg
qemu/tests/multi_disk_random_hotplug.py

Need some interval time for unplugging parallel way in windows.
ID: 1866579

multi_disk_random_hotplug: Add interval time for unplugging parallel

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_redis.py

nvdimm_redis: Add new case to run redis test

---

qemu/tests/balloon_thp.py
qemu/tests/cfg/balloon_thp.cfg

balloon_thp: Memory balloon with thp

---

qemu/tests/blockdev_inc_backup_bitmap_with_granularity.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_with_granularity.cfg

blockdev_inc_backup_bitmap_with_granularity: bitmap granularity test

---

qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/rng_host_guest_read.cfg
qemu/tests/cfg/rng_hotplug.cfg
qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/cfg/rng_read_longtime.cfg
qemu/tests/cfg/rng_stress.cfg
qemu/tests/cfg/viorng_in_use.cfg
qemu/tests/rng_maxbytes_period.py

rngd: restrict the guest list to check rngd service

---

qemu/tests/cfg/throttle_operation_test.cfg
qemu/tests/throttle_operation_test.py

ID:1908619,1908620,1908621,1908622,1908623,1908625,1908626,1908627,1908628,1908629,1908630

Add throttle operation test

---

generic/tests/cfg/jumbo.cfg
generic/tests/cfg/vlan.cfg
qemu/tests/cfg/enable_scatter_windows.cfg
qemu/tests/cfg/offload_checksum_windows.cfg
qemu/tests/cfg/win_irq_check.cfg

Add test params "only virtio_net" for some cfg files

---

qemu/tests/cfg/hv_type.cfg
qemu/tests/hv_type.py

Check if hyper-v type is existed on linux guest
id: 1909620

hv_type.py: Check type on Linux guest with all hv flags

---

qemu/tests/cfg/qemu_img_convert_with_rate_limit.cfg
qemu/tests/qemu_img_convert_with_rate_limit.py

qemu_img_convert_with_rate_limit: convert image with parameter -r

---

qemu/tests/cfg/commit_with_backing.cfg

commit_with_backing: add rate_limit support to commit test

---

qemu/tests/cfg/nic_hotplug.cfg

nic_hotplug script to add variants: with_iommu

---

qemu/tests/cfg/rss_iperf_test.cfg
qemu/tests/iperf_test.py

1.Test only for multi queues
2.Add rss test for virtio-net driver
ID:1908377

virtio-net can works normally when rss=on,hash=on,vhost=off

---

qemu/tests/change_media.py
qemu/tests/eject_media.py

Fix device tray not open issue
ID:1898030,1898032

cdrom_media: Fix device tray not open issue

---

provider/backup_utils.py
qemu/tests/blockdev_inc_backup_add_disabled_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_add_disabled_bitmap.cfg

blockdev_inc_backup_add_disabled_bitmap: Add disabled bitmap test

---

provider/block_dirty_bitmap.py
qemu/tests/blockdev_inc_backup_enable_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_enable_bitmap.cfg

blockdev_inc_backup_enable_bitmap: Add test for enabling disabled bitmaps

---

qemu/tests/blockdev_inc_backup_remove_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_remove_bitmap.cfg

blockdev_inc_backup_remove_bitmap: Add test for removing bitmaps

---

qemu/tests/blockdev_inc_backup_clear_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_clear_bitmap.cfg

blockdev_inc_backup_clear_bitmap: Add test for clearing bitmap

---

qemu/tests/blockdev_inc_backup_add_bitmap_to_raw.py
qemu/tests/cfg/blockdev_inc_backup_add_bitmap_to_raw.cfg

blockdev_inc_backup_add_bitmap_to_raw: Add bitmap to raw image

---

qemu/tests/blockdev_inc_backup_disable_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_disable_bitmap.cfg

blockdev_inc_backup_disable_bitmap: Add test for disabling bitmap

---

qemu/tests/cfg/hugepage_reset.cfg
qemu/tests/hugepage_reset.py

hugepage_reset: Test nr_hugepages resetting

---

qemu/tests/cfg/x86_cpu_flags.cfg

x86_cpu_flags:test pcid flag

---

qemu/tests/blockdev_inc_backup_filternode.py
qemu/tests/cfg/blockdev_inc_backup_filternode.cfg

blockdev_inc_backup_filternode: Add backup filter-node-name test

---

qemu/tests/blockdev_inc_backup_convert_with_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_convert_with_bitmap.cfg

Convert an image with disabled/enabled bitmaps
ID: 1911167

blockdev_inc_backup_convert_with_bitmap: Convert image with bitmaps

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py
provider/netperf_base.py
qemu/tests/cfg/netperf_udp_perf.cfg
qemu/tests/netperf_udp_perf.py

performance: add case "netperf -rate limiting UDP_STREAM"

---

provider/chardev_utils.py
qemu/tests/cfg/chardev_tls_encryption.cfg
qemu/tests/chardev_tls_encryption.py

chardev:test native TLS encryption

---

qemu/tests/blockdev_inc_backup_merge_external_bitmaps.py
qemu/tests/cfg/blockdev_inc_backup_merge_external_bitmaps.cfg

Signed-off-by: zhencliu <zhencliu@redhat.com>
ID: 1911582

blockdev_inc_backup_merge_external_bitmaps: Merge external bitmaps

---

qemu/tests/cfg/ksm_ksmtuned.cfg
qemu/tests/ksm_ksmtuned.py

ksmtuned: New test case to check kSM works well

---

qemu/tests/cfg/block_discard_hotplug.cfg

Disable luks format for discard test

---

qemu/tests/blockdev_inc_backup_pull_mode_vm_down.py
qemu/tests/cfg/blockdev_inc_backup_pull_mode_vm_down.cfg

blockdev_inc_backup_pull_mode_vm_down: Poweroff vm when pulling data

---

qemu/tests/block_kill_reconnect_with_remote_storage.py
qemu/tests/cfg/block_kill_reconnect_with_remote_storage.cfg

block_kill_reconnect_with_remote_storage: support nbd backend

---

qemu/tests/block_lvm_read_only.py
qemu/tests/cfg/block_lvm_read_only.cfg

block_lvm_read_only:test of lvm with read-only
ID:1909932

block_lvm_read_only: Test of lvm with read-only

---

qemu/tests/cfg/enable_scatter_windows.cfg
qemu/tests/cfg/netkvm_change_param_value_test.cfg
qemu/tests/enable_scatter_windows.py
qemu/tests/netkvm_change_param_value_test.py

For product change, need change MTU to *JumboPacket
id:1898870

Change netkvm param name for jumbo in windows

---

qemu/deps/netuser/exp.c
qemu/tests/cfg/netuser_buffer_test.cfg
qemu/tests/netuser_buffer_test.py

1.Only test for Linux
2.Use net user model to do packet buffer stress test
ID:1910839

Packet buffer stress test for user

---

multi_host_migration/tests/migration_multi_host_downtime_and_speed.py
qemu/tests/cdrom.py
qemu/tests/cpuflags.py
qemu/tests/migration.py
qemu/tests/migration_with_speed_measurement.py
qemu/tests/qemu_guest_agent.py
qemu/tests/vioser_in_use.py
qemu/tests/virtio_serial_file_transfer_offline_migrate.py

migration: Update migration cases to support migration parameters

---

qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg

delete "no s390x" in these cfgs and modify numa related info to other
architecture
ID:1915754

Modify cfgs related to virtio-fs since s390x supported

---

qemu/tests/netkvm_change_param_value_test.py

Add judgement for param_names
id: 1918083

netkvm_change_param_value_test.py: ERROR: list.remove(x): x not in list

---

qemu/tests/cfg/msi_change_flag.cfg
qemu/tests/cfg/nic_bonding.cfg
qemu/tests/cfg/transfer_file_over_ipv6.cfg
qemu/tests/cfg/virtual_nic.cfg
qemu/tests/cfg/win_nics_teaming.cfg

Remove 'oflag=direct' to avoid create data under tmpfs failed

---

qemu/tests/blockdev_inc_backup_pull_mode_diff.py
qemu/tests/blockdev_inc_backup_pull_mode_test.py

Enhance the tests with new backup_utils.copyif

---

qemu/tests/cfg/blockdev_commit.cfg
qemu/tests/cfg/blockdev_snapshot.cfg
qemu/tests/cfg/blockdev_snapshot_chains.cfg
qemu/tests/cfg/blockdev_snapshot_reboot.cfg
qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg
qemu/tests/cfg/blockdev_snapshot_stress.cfg
qemu/tests/cfg/blockdev_stream.cfg

blockdev: To support the new version

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

New case to test virtio-fs xfstest
ID: 1906312 1907882

virtio-fs: New case to test virtio-fs xfstest

---

.travis.yml
generic/tests/ethtool.py
generic/tests/whql_client_install.py
generic/tests/whql_submission.py
provider/virt_storage/virt_secret.py
qemu/deps/softlockup/heartbeat_slu.py
qemu/tests/balloon_check.py
qemu/tests/sr_iov_sanity.py
qemu/tests/virtio_console.py
requirements-travis.txt

1. Update inspektor version to 0.5.2
2. Update travis CI setting, disable "allow_failures" and add python3.9
3. Fix pylint issues on py files.
ID: 1920312

Update travis setting and disable "allow_failures"

---

qemu/tests/cfg/smt_test.cfg

smt_test: remove "enforce" flag

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add new case that start qga container.

---

qemu/tests/cfg/multi_nics_hotplug.cfg
qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/cfg/qemu_option_check.cfg

Add test parameters "only Host_RHEL.m6, Host_RHEL.m7"

---

qemu/tests/cfg/throttle_multi_guests_parameter_test.cfg
qemu/tests/throttle_multi_guests_parameter_test.py

Throttle: Add multi-vms parameter test

---

qemu/tests/cfg/virtual_nic.cfg
qemu/tests/virtual_nic_private.py

Tcpdump process terminate exceptly

---

qemu/tests/cfg/throttle_cdrom_test.cfg
qemu/tests/throttle_cdrom_test.py

Add cdrom test under throttle

---

provider/backup_utils.py
qemu/tests/cfg/blockdev_commit_reboot.cfg
qemu/tests/cfg/blockdev_commit_stop_cont.cfg
qemu/tests/cfg/blockdev_commit_stress.cfg
qemu/tests/cfg/blockdev_stream_no_space.cfg

Fix the issue that dd to /tmp with oflag=direct

---

qemu/tests/cfg/driver_load.cfg
qemu/tests/cfg/rng_driver_load.cfg

rng_module: update the guest restriction for virtio_rng module cases

---

qemu/tests/cfg/balloon_memhp.cfg
qemu/tests/cfg/hotplug_mem_simple.cfg

Update threshold for some memory hotplug test cases

---

qemu/tests/cfg/blockdev_commit_install.cfg
qemu/tests/cfg/blockdev_mirror_install.cfg
qemu/tests/cfg/blockdev_snapshot_install.cfg
qemu/tests/cfg/blockdev_stream_install.cfg

Add new keywords check for RHEL installation

---

qemu/tests/blockdev_inc_backup_pull_mode_vm_down.py
qemu/tests/cfg/blockdev_inc_backup_pull_mode_vm_down.cfg

blockdev_inc_backup_pull_mode_vm_down: fix the issue when qemu quits after vm poweroff

---

qemu/tests/cfg/usb.cfg
qemu/tests/usb_redir.py

usbredir_tcp: add usb-redir via tcp testing case

---

qemu/tests/cfg/seabios_strict.cfg

seabios_strict: change /tmp to /var/tmp
ID:1925918

change /tmp path to /var/tmp

---

provider/nbd_image_export.py
qemu/tests/blockdev_inc_backup_pull_mode_diff.py
qemu/tests/blockdev_inc_backup_pull_mode_test.py
qemu/tests/blockdev_inc_backup_xpt_bitmap.py

nbd_image_export: Add common block export support

---

qemu/tests/cfg/qemu_disk_img.cfg

Fix no matching bus on aarch64
ID: 1931031

qemu_disk_img: Fix no matching bus on aarch64

---

qemu/tests/blockdev_inc_backup_xpt_multiple_bitmaps.py
qemu/tests/cfg/blockdev_inc_backup_xpt_multiple_bitmaps.cfg

Export image with multiple bitmaps from nbd server
ID: 1922941, 1922946

blockdev_inc_backup_xpt_multiple_bitmaps: Mutiple bitmaps export

---

qemu/tests/blockdev_mirror_no_space.py
qemu/tests/cfg/blockdev_mirror_no_space.cfg

blockdev_mirror_no_space: Mirror to an image without enough space

---

qemu/tests/cfg/timerdevice.cfg

timerdevice: add invtsc cpu flag for guest on AMD host

---

qemu/tests/smt_test.py

smt_test: Fix IndexError

---

qemu/tests/numa_consistency.py

numa_consistency: Fix cpu topology bug and add numa configuration

---

qemu/tests/blockdev_mirror_same_src_tgt.py
qemu/tests/cfg/blockdev_mirror_same_src_tgt.cfg

blockdev_mirror_same_src_tgt: Mirror to the same node

---

qemu/tests/cfg/multi_nics_hotplug.cfg

Change test parameters in multi_nics_hotplug.cfg

---

provider/nbd_image_export.py
qemu/tests/cfg/remote_image_access.cfg
qemu/tests/nbd_unix_connection.py

nbd: repeate connection with unix socket

---

qemu/tests/cfg/hotplug_mem.cfg

ID: 1932729
Depends on https://github.com/avocado-framework/avocado-vt/pull/2932.

hotplug_mem: Add case for memory-backend-memfd

---

qemu/tests/cfg/blockdev_mirror_readonly.cfg

blockdev_mirror_readonly: Add different error message check

---

qemu/tests/cfg/hpt_max_page_size.cfg
qemu/tests/hpt_huge_page_negative.py

hpt:checking if P8 guest's negative test on power9 host pass or not

---

qemu/tests/cfg/hpt_max_page_size.cfg
qemu/tests/hpt_max_page_size.py

huge_page: boot up p8 guest with 16M page size on power9

---

qemu/tests/blockdev_mirror_src_no_space.py
qemu/tests/cfg/blockdev_mirror_src_no_space.cfg

blockdev_mirror_src_no_space: Mirror source without enough space

---

qemu/tests/blockdev_mirror_forbidden_actions.py
qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg

commit/resize/mirror/snapshot/stream should fail during mirroring,
proper error message should output
ID: 1933929

blockdev_mirror_forbidden_actions: do qmp cmds while mirroring

---

qemu/tests/blockdev_mirror_complete_running_job.py
qemu/tests/cfg/blockdev_mirror_complete_running_job.cfg

blockdev_mirror_complete_running_job: Complete a running mirror job

---

qemu/tests/blockdev_mirror_cancel_ready_job_with_io.py
qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_io.cfg

blockdev_mirror_cancel_ready_job_with_io: Cancel ready job when doing io

---

qemu/tests/cfg/timerdevice.cfg
qemu/tests/timerdevice_time_jump_check.py

timerdevice:modify host cpu checking way

---

qemu/tests/cfg/power_htm.cfg
qemu/tests/power_htm.py

1.support unit test for htm
2.check the test app can pass in the guest
ID:1929953, 1929954

power_htm:verify htm basic funciton works well on ppc

---

generic/tests/cfg/boot_vm_in_hugepage.cfg

add 1M hugepage supported and host hugepage set for supporting s390x
ID:1936832

Add support for hugepage on s390x

---

qemu/tests/cfg/nic_opt.cfg
qemu/tests/nic_opt.py

Change test parameters in nic_opt.cfg

---

generic/tests/cfg/boot_vm_in_hugepage.cfg
qemu/tests/cfg/hugepage_mem_stress.cfg
qemu/tests/cfg/hugepage_reset.cfg
qemu/tests/cfg/hugepage_specify_node.cfg
qemu/tests/hugepage_mem_stress.py

Update hugepage cases to use memdev

---

qemu/tests/cfg/uefi_boot_from_device.cfg
qemu/tests/cfg/uefi_check_log_info.cfg

uefi: change /tmp to /var/tmp
ID:1937571,1937573

change /tmp to /var/tmp

---

generic/tests/netperf.py

netperf: fix SyntaxError error

---

generic/tests/pktgen_perf.py

pktgen_perf: add check kernel version

---

qemu/tests/cfg/throttle_operation_test.cfg
qemu/tests/throttle_operation_test.py

1. Add throttle on the snapshot
2. Fix windows support in configure_data_disk
ID:1937622

Add throttle on snapshot test

---

qemu/tests/blockdev_inc_backup_bitmap_max_len_name.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_max_len_name.cfg

blockdev_inc_backup_bitmap_max_len_name: Add bitmap with maxlen name

---

qemu/tests/cfg/boot_nic_with_iommu.cfg

Virtual_network:Add iommu addaption on s390x and modify params
BZ:1939397

Add "iommu"  adaption on s390x

---

qemu/tests/blockdev_inc_backup_expose_active_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_expose_active_bitmap.cfg

blockdev_inc_backup_expose_active_bitmap: Expose an active bitmap

---

qemu/tests/cfg/same_mac_address.cfg
qemu/tests/same_mac_address.py

Boot guest with 2 virtio-net devices with the same mac address.
id: 1927120

Add new case: boot guest with the same mac address

---

qemu/tests/blockdev_inc_backup_migrate_without_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_migrate_without_bitmap.cfg

blockdev_inc_backup_migrate_without_bitmap: Migration without bitmap

---

qemu/tests/blockdev_inc_backup_no_space.py
qemu/tests/cfg/blockdev_inc_backup_no_space.cfg

Do full backup to an image without enough space
ID: 1938926

blockdev_inc_backup_no_space: Backup image without enough space

---

qemu/tests/blockdev_inc_backup_bitmap_inuse.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_inuse.cfg

blockdev_inc_backup_bitmap_inuse: Bitmap in-use cannot be used

---

qemu/tests/blockdev_mirror_after_block_error.py
qemu/tests/cfg/blockdev_mirror_after_block_error.cfg

blockdev_mirror_after_block_error: Block mirror after block error

---

qemu/tests/cfg/throttle_operation_test.cfg
qemu/tests/throttle_operation_test.py

Throttle: change snapshot node name

---

qemu/tests/cfg/trim_support_test.cfg
qemu/tests/trim_support_test.py

Add step to test trim 4k disk for blk.
ID:1894029

trim_support_test: Add step to test trim 4k disk for blk

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/timedrift_check_when_hotplug_vcpu.py

Add cpu hotplug support for ppc platform

---

qemu/tests/cfg/spapr_vty_multi_backends.cfg
qemu/tests/spapr_vty_multi_backends.py

spapr_vty: add spapr_vty's negative test case on power

---

qemu/tests/fio_perf.py

fio_perf: fix type error caused by commit45875435

---

qemu/tests/cfg/x86_cpu_model.cfg

x86_cpu_model:add new model EPYC-Milan

---

qemu/tests/cfg/power_nvram.cfg
qemu/tests/power_nvram.py

power_nvram: make sure qemu-kvm works well while raw strings are passed

---

qemu/tests/blockdev_commit_hotunplug.py
qemu/tests/cfg/blockdev_commit_hotunplug.cfg

blockdev_commit_hotunplug: hot-unplug block disk during live commit

---

qemu/tests/cfg/vsock.cfg
qemu/tests/vsock_hotplug.py

vsock:Add suporting for vsock on s390x,modify the device_pattern works
on s390x
ID:1937706

Add vsock supporting on s390x

---

qemu/tests/cfg/qemu_img_convert_with_target_is_zero.cfg
qemu/tests/qemu_img_convert_with_target_is_zero.py

convert image with parameter --target-is-zero -n
ID: 1942220, 1942222, 1942223

qemu.test: qemu_img_convert_with_target_is_zero

---

qemu/tests/cfg/qemu_guest_agent.cfg

qemu_guest_agent: test check_get_disks from RHEL8.4

---

qemu/tests/cfg/qemu_img_convert_with_backing_file.cfg
qemu/tests/qemu_img_convert_with_backing_file.py

convert image with parameters -B -n
ID: 1942225, 1942226, 1942227

qemu.test: qemu_img_convert_with_backing_file

---

qemu/tests/cfg/pcie_hotplug_opt.cfg

pcie_hotplug_opt add support for aarch64 platform
ID:1940270

pcie_hotplug_opt: Add support for aarch64 platform

---

generic/tests/cfg/pxe_boot.cfg

Set parameter "qemu_stop = off"

---

qemu/deps/million/million-ppc64.s
qemu/deps/million/million-ppc64le.s
qemu/tests/cfg/vpmu_check.cfg
qemu/tests/vpmu_check_instructions.py

vpmu:cpu cycles checking between host and guest

---

qemu/tests/boot_with_different_vectors.py
qemu/tests/cfg/boot_with_different_vectors.cfg

Change the code usage of test case boot_with_different_vectors

---

generic/tests/cfg/guest_test.cfg

Disable unsupported feature isa_serial test case on power

---

qemu/tests/throttle_cdrom_test.py

Throttle: update throttle cdrom expected result

---

qemu/tests/cfg/virtio_chardev_trace.cfg

Disable virtio_chardev_trace test case on power

---

qemu/deps/guest_sg_luns.sh
qemu/tests/cfg/multi_disk_wild_hotplug.cfg
qemu/tests/multi_disk_wild_hotplug.py

Add wild hotplug/unplug case

---

qemu/tests/balloon_check.py
qemu/tests/cfg/balloon_check.cfg

Depends on https://github.com/avocado-framework/avocado-vt/pull/2978
ID: 1944030

balloon_check: Add new case to test option free-page-reporting

---

qemu/tests/cfg/fio_perf.cfg
qemu/tests/fio_perf.py

add virtiofs performance test case

---

provider/win_driver_utils.py
qemu/tests/cfg/win_virtio_driver_install_from_update.cfg
qemu/tests/win_virtio_driver_install_from_update.py

Install virtio-win drivers from windows update.
ID: 1920844

win_virtio_driver_install_from_update: Add new test case

---

qemu/tests/blockdev_commit_powerdown.py
qemu/tests/cfg/blockdev_commit_powerdown.cfg

blockdev_commit_powerdown: power down during live commit

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Rebooting vm when virtiofs file system is mounted.
ID: 1941942

virtio-fs: new case of reboot vm when virtio is mounted

---

qemu/tests/multi_disk_random_hotplug.py

Block:change usb controller to usb3 for pseries

---

qemu/tests/cfg/smt_test.cfg

smt_test: Remove case Opteron.with_topoext

---

qemu/tests/blockdev_mirror_error.py
qemu/tests/cfg/blockdev_mirror_error.cfg

blockdev_mirror_error: Create a mirror image without enough space

---

qemu/tests/cfg/qemu_img_luks_key_management.cfg
qemu/tests/qemu_img_luks_key_management.py

1. add a new passowrd to free keyslot
2. erase password from keyslot
ID: 1945872

qemu.test: qemu_img_luks_key_management

---

qemu/tests/cfg/qemu_img_luks_inside_qcow2_key_management.cfg

1. add a new passowrd to free keyslot
2. erase password from keyslot
ID: 1945876

qemu.test: qemu_img_luks_inside_qcow2_key_management

---

qemu/tests/cfg/max_lun.cfg
qemu/tests/max_channel_lun.py

…apr-vscsi controller
ID:1942400

scalability:Verify max 32 LUNs on one channel

---

qemu/tests/cfg/qemu_img_luks_inside_qcow2_key_management.cfg
qemu/tests/cfg/qemu_img_luks_key_management.cfg
qemu/tests/qemu_img_luks_key_management.py

change to amend_secret_id and amend_secret_data
ID: 1949108

correct parameters amnd_secret_id and amnd_secret_data

---

qemu/tests/cfg/cpu_device_hotplug_time_jump.cfg
qemu/tests/cpu_device_hotplug_time_jump.py

Add new case to test if cpu hotplug causes time jump

---

qemu/tests/cfg/usb.cfg

usb:remove some pci-ohci test cases due to won't fix issue on ppc
