qemu/tests/cfg/qemu_disk_img.cfg

1. To support pseries test, specify drive_format of the snapshot
image to be virtio_blk for the originally virtio_scsi image,
while specify it to be virtio_scsi for the originally virtio_blk
one
ID: 1692255

qemu_disk_img.info.change_block_interface: Add pseries support

---

qemu/tests/cfg/openflow_acl_test.cfg
qemu/tests/openflow_acl_test.py

1. Telnelserver is deprecated in Win10,Win2016,Win2019, remove it in
setup_cmd and tests when Win vm as telnetserver.
2. the default bridge name is atbr0
Signed-off-by: WenliQuan <wquan@redhat.com>
id: 1467827

openflow_acl_test.accessed_deny_all_target.telnet: telnelserver is deprecated in Win10,Win2016,Win2019

---

qemu/tests/cfg/multi_disk.cfg

1. Add spapr-vscsi support in the max_disk test case
2. Add new test cases to test the scsi passthrough of spapr-vscsi
ID: 1702628, 1703953

multi_disk: Add spapr-vscsi support for max disk and scsi passthrough test

---

qemu/tests/cfg/virtio_scsi_mq.cfg
qemu/tests/virtio_scsi_mq.py

Wrap sentences to functions as below:
1. get_mapping_interrupts2vcpus: Get the mapping of between virtio
interrupts and vcpus.
2. create_data_images: Creating date images.
3. check_irqbalance_status: Checking the status of irq balance server.
4. start_irqbalance_service: Start the irqbalance service.
5. pin_vcpus2host_cpus: Pinning the vcpus to host cpus.
6. verify_num_queues: Verifying the number of queues from qtree.
7. check_interrupts: Checking the info of interrupts.
8. check_interrupts2vcpus: Checking the status of interrupters to vcpus.
9. pin_interrupts2vcpus: Pinning the interrupts to vcpus.
10. check_io_status: Check the status of I/O.
11. load_io_data_disks: Loading io on data disks.
12. compare_interrupts: Comparing the info of interrupts after io testing.
Delete the setting …

virtio_scsi_mq: Refectoring virtio_scsi_mq

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/timedrift_check_when_crash.py
qemu/tests/timedrift_check_when_hotplug_vcpu.py

1. Need to add pattern for windows guest.
2. Need to specify ntp_cmd for host when running windows guest.
3. For some windows guests, e.g. Win2019, the service w32time is running by default. So need to judge it first when starting.
bug id: 1707732

Add windows guest support for some timer device cases

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Qemu Guest Agent VSS Provider service startup type should be Manual.
ID:1487507

qemu_guest_agent: New case to check Vss Provider service

---

qemu/tests/cfg/win_irq_check.cfg

Add disable MSI test case by vectors for vioscsi, viostor, netkvm drivers.
id: 1566853

win_irq_check: Add a case disable msi by setting vectors

---

qemu/tests/netperf_udp.py
qemu/tests/ovs_qos.py

As the suject, aims to replace previous dependence on `__del__` to do
cleanup with explict call of cleanup function.

call cleanup method of utils_netperf.Netperf explicitly

---

qemu/tests/cfg/qemu_img_lock.cfg
qemu/tests/qemu_img_lock_reject_boot.py

It supprts qcow2 and raw:
reject_boot_same_img_twice
reject_boot_base_img_and_snapshot.qcow2_format
reject_boot_base_img_and_snapshot.raw_format
id: 1627027

added qemu-img lock reject boot tests

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/timedrift_check_when_crash.py

When guest kernel panic occurs, keep the qemu process alive.
bug id: 1721813

timedrift_check_when_crash: add "-no-shutdown" for windows guest

---

qemu/tests/cfg/slof_device_tree.cfg
qemu/tests/slof_device_tree.py

Since some qemu build does not expose "host-serial",
so it can't be got then skip to compare "host-serial"
and "system-id".
ID:1719637

slof_device_tree: Update case to support different qemu build

---

qemu/tests/cfg/hpt.cfg
qemu/tests/hpt_miscellaneous.py

Add waiting time after mem_hotpug since there's time delay for HPT resizing in a compatible guest on P9.As it is not a really product problem,we need this patch to pass our test case.
ID:Bug 1709655
Signed-off-by:Miriam Deng mdeng@redhat.com

hpt_miscellaneous: add waiting time before HPT resizing 

---

qemu/tests/cfg/boot_with_max_queues.cfg
qemu/tests/cfg/mq_enabled_chk.cfg

Should use "del" on windows guests, add "clean_cmd = del" in cfg file
id:1723699

 boot_with_multiqueue.py: fix using "rm" on windows guests

---

qemu/tests/vsock_hotplug.py

1.As ‘lspci’ command can not find device immediately in guest
after hotplugging virtio_vsock.
2.Add sleep(10) to solve this issue after hotplugging.
Signed-off-by:Xiangchun Fu xfu@redhat.com
ID:1726492

vsock_hotplug: Fix the issue of vsock_hotplug

---

qemu/tests/qemu_img_lock_reject_boot.py

Added env_process to create the vm, so the test can run alone.
id: 1726951

qemu-img-lock bug fix

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py

1. fix virttest.virt_vm.VMIPAddressMissingError in macvtap env
2. add parameter server_private_ip since guest could not get ip from
dhcp server in macvtap env
3. add parameter client_public_ip to set network interface&apos;s ip on
external host
id: 1693600

netperf: some improvement for macvtap env

---

generic/tests/cfg/iozone_windows.cfg
generic/tests/iozone_windows.py

Add a case to test the stability of guest by running iozone
on multiple disks in a long time.
ID: 1715710

iozone_windows: Add a case to test the stability of guest

---

qemu/tests/cfg/smbios.cfg

When testing with q35 machine type, RHEL6 guest cannot run with default virtio-1.0 driver.
This case is not related with virtio, so use non-virtio device instead to support RHEL6.
ID: 1728570

smbios: avoid using virtio device in smbios_table.machine_type

---

qemu/tests/cfg/virtual_nic.cfg

virtual_nic: correct the path of 'tshark.exe' in 'tcpdump_cmd'

---

generic/tests/cfg/vlan.cfg
generic/tests/vlan.py
qemu/tests/cfg/ctrl_vlan.cfg
qemu/tests/ctrl_vlan.py

Win7 and win2008 cannot use "Set-NetAdapter" in powershell, so replace with "Netsh".
id:1657625

vlan:fix cannot use "Set-NetAdapter" in powershell on windows7 guest

---

generic/tests/cfg/multi_queues_test.cfg
generic/tests/multi_queues_test.py

max_queues:
1. Add "vt_ulimit_nofile" to fix "Too many  open files"
2. Modify the method to get "top_info" to fix "top: pid limit (20) exceeded"
cpu_affinity:
1. Modifiy the "cmd" to fix to get an empty "irq_statics" when irq_number > 99
2. Restart "irqbalance.service" finally
others:
1. Sleep 2min to make the results more accurate
2. Use "top -i" to get the correctly running pid.
ID: 1367010 1647284

Fix some multi_queues_test problems

---

qemu/tests/cfg/timerdevice.cfg

timerdevice: modify ntp_sync_cmd to support rhel6 guest

---

qemu/tests/cfg/multi_nics_verify.cfg

Add "vt_ulimit_nofile"
id:1716712

multi_nics_verify.with_multiqueue: fix "Too many open files" issue

---

qemu/tests/cfg/viorng_in_use.cfg
qemu/tests/driver_in_use.py

1. Check basic driver function after main_test executed 
2. Adjust viorng config to optimize rng cases.
ID: 1725565

Check basic driver function after main_test executed

---

qemu/tests/cfg/seabios.cfg

1.The latest SGABIOS output has changed. Update sgabios_info to be compatible.
2.Update the way to specify boot_menu_key for RHEL 8 compatibility.
ID: 1728997
Signed-off-by: ybduan yduan@redhat.com

 sgainfo_update: update sgabios_info 

---

qemu/tests/qemu_disk_img_commit.py

Qemu-img should support to empty the overlay after commitment
ID: 1730518

Call QemuImg.commit for commit function

---

qemu/tests/cfg/migrate.cfg

Drop unstable command "x-multifd", update it to formal
command "multifd".
ID:1720112

Migration:Update unstable command "x-multifd" to "multifd" 

---

generic/tests/cfg/timedrift.cfg
generic/tests/cfg/timerclock.cfg
qemu/tests/cfg/time_manage.cfg
qemu/tests/cfg/timedrift_adjust_time.cfg
qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/cfg/timedrift_no_net.cfg
qemu/tests/cfg/timerdevice.cfg

-S will cause the guest system time is different with host system
time when -rtc clock=vm.
bug id: 1694657

timer-device: add qemu_stop = off for timer device cases

---

qemu/tests/cfg/timedrift_adjust_time.cfg
qemu/tests/timedrift.py
qemu/tests/timedrift_adjust_time.py
qemu/tests/timedrift_check_when_crash.py
qemu/tests/timedrift_check_when_hotplug_vcpu.py
qemu/tests/timedrift_monotonicity.py
qemu/tests/timedrift_with_migration.py
qemu/tests/timedrift_with_stop.py

The windows guest's time zone needs to be the same as host
before test.
bug id: 1694959

Add sync_timezone_vm for timer device cases

---

qemu/tests/cfg/timerdevice.cfg
qemu/tests/timerdevice_change_guest_clksource.py

For rhel8 guest, directly edit grub2.cfg isn't supported.
And even if for rhel7 and rhel6, directly edit grub2.cfg
isn't recommend.
bug id: 1708540

timerdevice_change_guest_clksource: change kernel param via grubby

---

qemu/tests/cfg/timerdevice.cfg

With host 100% load, the serial login needs more time, 240s
isn't enough. For windows guest, the response is too slow,
so no need to support it.
bug id: 1722784

timerdevice: modify login_timeout for cases with host load

---

qemu/tests/cfg/virtio_console.cfg
qemu/tests/virtio_console.py
qemu/tests/virtio_port_hotplug.py

Use simple_hotplug() instead of device.hotplug() for q35 support,
'serials' instead of 'virtio_ports' to align new definition. And
remove get device id by name methods since not necessary now
id: 1726614, 1529434, 1724599

virtio_console: Fix q35 hotplug issues

---

qemu/tests/cfg/seabios_reboot_timeout.cfg

Latest qemu 4.x doesn't support boot option reboot-timeout larger than
65535, it only works with older qemu version.
ID: 1735665

boot: restrict qemu version to test case time65536

---

qemu/tests/cfg/qmp_basic.cfg
qemu/tests/cfg/qmp_basic_rhel6.cfg
qemu/tests/cgroup.py

Deprecate 'vcpu_thread_pattern'
Depends on: https://github.com/avocado-framework/avocado-vt/pull/2163
ID: 1731777

Deprecate 'vcpu_thread_pattern'

---

qemu/tests/virtio_console.py

Otherwise sometimes cause unexpected exceptions when case finished
id: 1735756

virtio_console: destroy vm at the end of the case

---

qemu/tests/cfg/timerdevice.cfg

10s is too short, sometimes no results. Need more time to get
output.
bug id: 1736835

timerdevice: modify test_run_timeout

---

qemu/tests/seabios_bin.py

Update bin_dict to add support for latest rhel8-related machine type.
ID: 1731138

bin_file: Add support for rhel8-related machine type

---

qemu/tests/cfg/block_hotplug.cfg

Due to new block_resize file no need disk_update_cmd params,
so delete them, and update a few new block_resize.py needed params.
id: 1734227

block_hotplug: Update with_block_resize cfg

---

generic/tests/cfg/iometer_windows.cfg
generic/tests/iometer_windows.py

Update the codes by following:
1. Modify the shutdown and reboot command.
2. New a function to check whether the iometer is alive.
3. Add checking the "SHUTDOWN" event in function change_vm_status.
ID: 1737761

iometer_windows: Update the codes

---

generic/tests/pktgen_perf.py

1. when guest with only one ifcfg-ethx, need to force to restart
network, otherwise the guest will not get ip address
2. decode process output to text
id: 1731064

pktgen_perf: add restart_network=True for multiple nics on vm

---

qemu/tests/cfg/block_commit.cfg
qemu/tests/cfg/block_stream.cfg
qemu/tests/cfg/block_stream_negative.cfg
qemu/tests/cfg/drive_mirror.cfg
qemu/tests/cfg/drive_mirror_negative_tests.cfg
qemu/tests/cfg/live_snapshot.cfg
qemu/tests/cfg/live_snapshot_chain.cfg

temporary fix to avoid blockdev updates

used '-device' option for block migration tests

---

qemu/tests/boot_order_check.py

Python3: old-style cmp function is discarded in list.sort(), using key function instead.
ID: 1731866

sort_cmp_key: use key function instead of cmp function in list.sort()

---

provider/cdrom.py
qemu/tests/block_hotplug.py
qemu/tests/block_hotplug_in_pause.py
qemu/tests/block_resize.py
qemu/tests/cdrom.py
qemu/tests/cdrom_block_size_check.py
qemu/tests/change_media.py
qemu/tests/eject_media.py
qemu/tests/multi_disk_random_hotplug.py

cdrom: Support blockdev
To support blockdev, device_id is repalced by qdev.
Update block cases: Update block cases to support blockdev options
Need to update the block cases to support blockdev options, since
qemu enable the blockdev options from the certain version.
Updated cases:
1. block_hotplug
2. block_resize
3. cdrom
4. cdrom_block_size_check
5. change_media
6. eject_media
7. block_hotplug_in_pause
8. multi_disk_random_hotplug
ID: 1707730

Update block cases: Update block cases to support blockdev

---

qemu/tests/cfg/image_locking_read_test.cfg
qemu/tests/image_locking_read_test.py

id:1739342 
Add a new testcase to test QEMU image locking should allow read
operation over the same base image. This case aims to verify that
snapshot in different snapshot chain could be used at the same time.

add case image_locking_read_test

---

qemu/tests/block_with_share_rw.py
qemu/tests/cfg/block_with_share_rw.cfg

New cases that boot up two VMs to test scsi block device
with "share-rw=on" and "share-rw=off" option.
ID: 1731610

block_with_share_rw: New cases to test block device with share-rw

---

generic/tests/cfg/unattended_install.cfg

Windows guest could not be installed successfully when using
the "blockdev" options, so workarund it with the "serial" option.
ID: 1740010

unattended_install: Workaround install windows guest with blockdev option

---

qemu/tests/virtio_port_hotplug.py

There is a unfriendly log when failed to
hotplug a port. It should give more specific
error info but no more like code error
ID:1741090

virtio_port_hotplug:fix unfriendly error info

---

qemu/tests/cfg/offload_checksum_windows.cfg
qemu/tests/offload_checksum_windows.py

Add case of Offload Tx/Rx checksum for windows guests
id:1566941

offload_checksum_windows.py: add windows support for Offload Tx/Rx checksum

---

qemu/tests/cfg/numa_memdev_options.cfg
qemu/tests/numa_memdev_mlock.py
qemu/tests/numa_memdev_options.py

1.Update function "check_host_numa_node_amount" to
"get_host_numa_node" to check host numa node
whose node size is non-zero
2.Assign host numa nodes whose node size is non-zero to
"host-nodes" and "target_num"
ID:1716737
ID:1722351

Numa_memdev_options: Assign proper host numa node automatically

---

qemu/tests/cfg/driver_load.cfg

Since ppc doesn't suppurt ide interface, so replace it
with scsi-hd.
ID: 1741400
Signed-off-by: zhenyu zhang <zhenyzha@redhat.com>

driver_load: Support ppc for loading driver

---

qemu/tests/cfg/x86_cpu_model.cfg

Add more cpu models, including Opteron_G5, Opteron_G4, Opteron_G3,
Icelake-Server, Icelake-Client, Cascadelake-Server, Broadwell,
Broadwell-noTSX, Haswell, Haswell-noTSX, IvyBridge, and SandyBridge.
ID: 1737687, 1737688, 1737689, 1737691,1737692,1737693,1737694, 1737695, 1737697, 1737696

x86_cpu_model: add cases to test more cpu models

---

qemu/tests/cfg/physical_resources_check.cfg
qemu/tests/cfg/win_sigverif.cfg
qemu/tests/physical_resources_check.py
qemu/tests/win_msft_sign_check.py

Move driver microsoft signature check part from physical_resources_check to win_sigverif case as prewhql drivers are not msft signed. It's better to move it from regular cases.
ID: 1569925

Move driver microsoft signature check to win_sigverif case

---

qemu/tests/cfg/timedrift_adjust_time.cfg

The expected results for rhel6 and rhel8 are different.
Need to add results check for rhel6.
bug id: 1693232, 1693242

timedrift_adjust_time: add test results for rhel6

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/vioser_in_use.cfg
qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/driver_in_use.py
qemu/tests/vioser_in_use.py
qemu/tests/virtio_serial_file_transfer.py

1. Clean generated files in guest and host in virtio_serial_file_transfer case;
2. Move check_bg_running out of run to make other cases call it;
3. Add following new cases:
- reboot/shutdown/system_reset/stop/cont/migration vm during
virtio serial driver in use;
- install/uninstall, downgrade/upgrade in usevirtio driver;
- disable/enbale in use virtio driver
ID:1231046, 1231042, 1230682, 1231023, 1231003, 1231657, 1483440

Add several virtio serial new cases

---

generic/tests/cfg/syzkaller.cfg
generic/tests/syzkaller.py

This adds a syzkaller fuzzing testcase for powerpc
and it does the below steps
1. Install/Setup syzkaller in host
2. Setup Guest for passwordless ssh from host
3. Prepare and compile Guest kernel
4. Prepare syzkaller config with qemu params and guest params
5. Start sykaller with above config and run for specified time(test_timeout)
6. Test fails out incase of any host issues
More details about syzkaller can be found here https://github.com/google/syzkaller

Add syzkaller testcase

---

qemu/tests/cfg/vsock.cfg

1.For Q35 machine type,Hotplugged vsock device ID is change
2.Remove hard code vsock device ID from vsock.cfg
id: 1744932
Signed-off-by:Xiangchun Fu xfu@redhat.com

vsock:Fix the issue of vsock_hotplug

---

qemu/tests/cfg/virtio_scsi_mq.cfg

When the device has large queue number,
get the queues state need more time,
original 5 sec is not enough.
id: 1748275

virtio_scsi_mq: Change the timeout for wmi_facility_check

---

qemu/tests/cfg/nic_hotplug.cfg

Assign the correct nic_model for nic_model_nic1
id:1751000

Fix it can only run with virtio-net when migration after nic hotunplug

---

qemu/tests/qemu_img.py

ID: 1744394
And compatible unit 'GiB' for image_size in qemu_img.py

Fix 'qemu-img.info' case failure

---

qemu/tests/block_hotplug.py
qemu/tests/cfg/block_hotplug.cfg

Update the order of importing modules by PEP8.
Wrap the codes to function:
1. Update function find_disk and rename it.
2. Update function run_sub_test.
3. Wrap the part of waiting plugging disks completely to
function wait_plug_disks.
4. Wrap the part of creating block devices to function
create_block_devices.
5. Wrap the part of getting block devices to function
get_block_devices.
6. Wrap the part of hotplug or unplug block devices to
function plug_block_devices.
7. Wrap the part of format windows disk to function format_disk_win.
8. Wrap the part of doing io testing on disk to function
run_io_test.
9. Update function get_disk_size.
ID: 1550800, 1617971, 1624674

block_hotplug: Refectoring block_hotplug

---

qemu/tests/qemu_disk_img.py
qemu/tests/qemu_disk_img_info.py

ID: 1752701
1. modify qemu_disk_img.check_backingfile that it will use json to
compare backing file if backing is in luks format.
2. add qemu_disk_img_info.InfoTest.start_vm to keep base params that
will be used to retrieve backing image's secret to start VM.

qemu_disk_img.info: support luks

---

qemu/tests/qemu_guest_agent.py

For guest-get-vcpus cmd,when logical-id is 0,can-offline value
should be false.
ID: 1752706

qemu_guest_agent: offline should be false for the first vcpu in linux guest

---

qemu/tests/cfg/qemu_img_negative.cfg

Limit required_qemu version for
qemu_img_negative.rebase.nonexist_old_backing_file

Rebase with nonexist_old_backing_file can work since qemu-4.1

---

qemu/tests/uefi_secureboot.py

Since ovmf does not support boot order, it needs boot index instead
id: 1750195

uefi_secureboot: make sure guest boot from image

---

qemu/tests/cfg/convert_after_resize_snapshot.cfg
qemu/tests/cfg/convert_image_from_raw_to_qcow2.cfg
qemu/tests/cfg/qemu_disk_img.cfg
qemu/tests/cfg/qemu_img_create_snapshot_on_qcow2_target_from_raw_source.cfg
qemu/tests/cfg/qemu_img_measure.cfg
qemu/tests/convert_after_resize_snapshot.py
qemu/tests/convert_image_from_raw_to_qcow2.py
qemu/tests/qemu_disk_img.py
qemu/tests/qemu_disk_img_convert.py
qemu/tests/qemu_img_create_snapshot_on_qcow2_target_from_raw_source.py
qemu/tests/qemu_img_measure_convert_image.py

change the way to specify convert target image to use the following
format:
```
images += convert
convert_target_image1 = convert
image_name_convert = images/convert
image_format_convert = qcow2
```
and adapt to parameter changes:
`compat` to `qcow2_compatible`
`cluster_size` to `image_cluster_size`

use convert_target to specify convert target image 

---

provider/qemu_img_utils.py
qemu/tests/cfg/luks_convert.cfg
qemu/tests/luks_convert.py

1. add three cases:
convert from luks to qcow2
convert from luks to raw
convert from luks to luks
2. introduce new provider module `qemu_img_utils`, which includes
common funtions needed by QEMU image related testcases.

luks_convert: introduces cases to support convert from luks

---

qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/vioser_in_use.py
qemu/tests/virtio_port_hotplug.py
qemu/tests/virtio_serial_hotplug_port_pci.py

1. Move run_bg_test() out of run function in vioser_in_use.py;
2. Add windows serial hotplug and unplug related cases.
- serial port/pci unplug and plug;
- reboot/shutdown/system_reset/migartion after plug/unplug;
- repeat plug/unplug serial port/pci 100 times
ID: 1456080, 1456078, 1456081, 1231116, 1231115, 1745382, 1483431, 1575477, 1575481, 1575478

Add serial hotplug/unplug related cases

---

qemu/tests/cfg/convert_after_resize_snapshot.cfg
qemu/tests/cfg/convert_image_from_raw_to_qcow2.cfg
qemu/tests/cfg/qemu_disk_img.cfg
qemu/tests/cfg/qemu_disk_img_compare.cfg

1. use `convert_target` to specify convert target.
2. remove deprecated param `image_convert`.

Correct convert params

---

qemu/tests/cfg/unsafe_rebase_to_none_existing_backing_file.cfg
qemu/tests/unsafe_rebase_to_none_existing_backing_file.py

Update `rebase` to adjust the way to specify rebase target.

unsafe_rebase_to_none_existing_backing_file: fix rebase

---

provider/qemu_img_utils.py
qemu/tests/cfg/rebase_second_snapshot_to_base.cfg
qemu/tests/rebase_second_snapshot_to_base.py

1. support luks as the base image
2. replace functions from `qemu_disk_img` with those in
`provider/qemu_img_utils`.

rebase_second_snapshot_to_base: support luks

---

qemu/tests/vioser_in_use.py

Import driver_in_use in run_bg_test function to avoid python2 circular imports.
ID: 1761342

vioser_in_use: resolve circular imports issue

---

qemu/tests/cfg/qemu_img_lock.cfg

Add support for luks in case: `qemu_img_lock.reject_boot_same_img_twice`

qemu_img_lock: support luks

---

qemu/tests/cfg/seabios_scsi_lun.cfg

1. correct it in order to avoid removing system image
ID: 1762276

seabioa_scsi_lun: correct data image name

---

qemu/tests/cfg/check_block_size.cfg

ID : 1743608
Signed-off-by: Qing Wang <qinwang@redhat.com>

Enable physical and logical block size 4096 on ovmf installation

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/rng_host_guest_read.cfg
qemu/tests/cfg/rng_hotplug.cfg
qemu/tests/cfg/rng_read_longtime.cfg
qemu/tests/cfg/rng_stress.cfg
qemu/tests/cfg/viorng_in_use.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/rng_bat.py

Run random.exe from cdrom sometimes make windows BSOD, copy it to vm harddisk to workaround bsod issue.
ID: 1748683

rng_bat: Run random.exe from hard disk instead of cdrom to avoid windows bsod

---

qemu/tests/cfg/create_snapshot_on_running_base.cfg
qemu/tests/create_snapshot_on_running_base.py

As the subject, add support for luks for
`create_snapshot_on_running_base`, which tests the creation of snapshot
over a in-use base image.

create_snapshot_on_running_base: support luks

---

qemu/tests/cfg/qemu_guest_agent.cfg

The command to get the mount point info is different
between rhel7 and rhel8
ID: 1752748

qemu-guest-agent: bug fix of get fsinfo in rhel7 guest

---

qemu/tests/cfg/timedrift_with_multi_vms.cfg
qemu/tests/timedrift_with_multi_vms.py

Case 1: check the timedrift on all the guests when attached all
guests to different CPUs
Case 2: check the timedrift on all the guests when attached all
guests to the same CPU
bug id: 1748724, 1748726

timedrift_with_multi_vms: add two timer device cases

---

qemu/tests/cfg/disk_extension.cfg
qemu/tests/disk_extension.py

Add test for disk extension
There is insufficient disk space result in guest in io-error status.
This test doing disk extension until it meet real disk size and
guest may back to running status.

Add test for disk extension

---

qemu/tests/mq_change_qnum.py

Update the function name as the refactor in utilt_net.py in avocado-vt.
Refer to avocado-vt PR#1877. Refactor the function name of
get_host_default_gateway() to be get_default_gateway().
Signed-off-by: yalzhang <yalzhang@redhat.com>

Update the function name as the refactor

---

qemu/tests/cfg/qemu_disk_img.cfg

Update config file for targets from convertion to support luks format

qemu_disk_img: Support target files with luks format

---

qemu/tests/iperf_test.py

iperf_test.py: remove guest_iperf_file for guest_iperf__bin
id:1766418

Fix cannot recognize 'c:\/iperf-3.1.3.exeiperf-3.1.3.exe'

---

qemu/tests/boot_order_check.py
qemu/tests/cfg/boot_order_check.cfg

1. The original implementation only support pc machine type,
add pci address resolution support for q35 machine type.
2. Remove the restriction for "only Linux".
ID: 1730964

boot_order_check: add support for q35 machine type

---

qemu/tests/cfg/seabios_reboot_timeout.cfg

1. Can't set timeout to 65536 from rhel8.1 and later versions,
so disable reboot-timeout=65536 testing on them.
2. If set reboot-timeout=65536, qemu will force it to 65535 on rhel6,
rhel7 and rhel8.0, so continue reboot-timeout=65536 testing on them.
ID: 1764509

seabios_reboot_timeout: disable reboot-timeout=65536 testing from rhel8.1

---

qemu/tests/cfg/multi_nics_verify.cfg
qemu/tests/multi_nics_verify.py

Increase the timeout for getting ip and boot time.
id:1709328

multi_nics_verify: fix cannot get enough ip of nics for windows guest

---

provider/qemu_img_utils.py
qemu/tests/image_convert_bypass_host_cache.py

the use of mock in strace implementation leads to the following
problems:
1. mock.patch is not thread-safe.
2. mock dependency issue in Python2.
So refactor strace and modify relevant cases.

qemu_img_utils: refactor strace

---

qemu/tests/qemu_img.py

Setting shorter sleep time for sending signal function,
or 'qemu-img rebase' can not recieve the signal before exit.
ID: 1754381

qemu_img: setting shorter sleep time for send signal function

---

qemu/tests/cfg/qemu_img_lock.cfg
qemu/tests/qemu_img_lock_reject_boot.py

id: 1771289
As the subject, add support to test if boot base and snapshot images
simultaneously.

qemu_img_lock.reject_boot_base_img_and_snapshot: support luks

---

qemu/tests/cfg/plug_cdrom.cfg
qemu/tests/plug_cdrom.py

New 2 cases:
1. Unplug a existing virtio-scsi local emulated CD-ROM, reboot
then shutdown guest.
2. Hot plug a virtio-scsi CD-ROM, reboot then shutdown guest.
ID: 1704814

plug_cdrom: New cases that test to hot plug or unplug cdrom device

---

qemu/tests/block_resize.py
qemu/tests/cfg/block_resize.cfg

1.Add md5 checking for disk resize
2.Add enlarging disk size testing
on partition type gpt_ext4/xfs and msdos_xfs
ID: 1430204

Add md5 checking for disk resize

---

provider/qemu_img_utils.py
qemu/tests/cfg/discard_for_raw_block_target.cfg
qemu/tests/discard_for_raw_block_target.py

1. Create source image via 'dd'.
2. Modprobe 1G scsi disk with writesame_16 mode.
3. Convert source to scsi disk, then check whether
'fallocate' system call works
ID: 1768354

New case of discard_for_raw_block_target

---

qemu/tests/cfg/commit_snapshot_to_backing_image.cfg
qemu/tests/commit_snapshot_to_backing_image.py

id:1772803
1. add new case `commit_snapshot_to_backing_image` to support image commit
for all formats: qcow2, luks, raw.
2. support the specification of different cache mode.

commit_snapshot_to_backing_image: support luks commit

---

qemu/tests/cfg/rebase_onto_no_backing_file.cfg
qemu/tests/rebase_onto_no_backing_file.py

id: 1773930
replace functions from `qemu_disk_image` to `provider/qemu_img_utils`
in order to support luks.

rebase_onto_no_backing_file: support luks

---

qemu/tests/cfg/vioinput_enable.cfg
qemu/tests/driver_in_use.py
qemu/tests/vioinput_keyboard.py

Add new cases that do reboot/shutdown/system_rest/migrate when
vioinput device enabled.
id: 1775504, 1775503, 1775505

vioinput_enable: Add new cases when vioinput device enabled

---

qemu/tests/cfg/cluster_size_check.cfg

Extend the values of cluster_size to cover all of the supported
values - A power of two between 512 and 2048k.
ID: 1776140

cluster_size_check: Extend the values of cluster_size

---

qemu/tests/cfg/rebase_second_snapshot_to_base.cfg
qemu/tests/rebase_second_snapshot_to_base.py

id:1775507
1. use `qcow2_compatible` to specify `compat` version for qcow2.
2. add `unsafe` mode support for rebase.
3. modify that tmp files will be created in base and active layers.

rebase_second_snapshot_to_base: add support of unsafe rebase

---

qemu/tests/qemu_guest_agent.py

The first vcpu's "can-offline" field differs between amd and intel cpu
model according to them in linux os.
ID: 1766458

qemu_guest_agent: the first vcpu's info differs for different cpu model

---

provider/cpu_utils.py
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_device_hotpluggable_with_numa.py
qemu/tests/cpu_device_hotpluggable_with_stress.py

Add some test cases to test vcpu device hot plug and unplug. And after
that, do some sub test, verify guest work well and the number of vcpu is
the same as expected.
Depends on: [Add vcpu device support [V2]](https://github.com/avocado-framework/avocado-vt/pull/2293)
ID: 1777153,1777161,1777163,1777164,1777165,1777167,1777171,1777172,1777169,1777181,1777182,1777183,1777184,1777185,1777187,1777190,1777192,1777194,1778561

Add cases to test vcpu device hot plug/unplug

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

Set installed OS image file to specified file name
1. Specify image file for the OS installation
2. Remove backup action to save disk space
ID:1776570

Set installed OS image file to specified file name

---

qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/driver_in_use.py

1. Assign empty value to target_process;
2. Add "set_bg_stress_flag" in cfg file in order to check balloon backgroud test.
ID: 1772832

win_virtio_driver_update_test: check balloon background test status

---

qemu/tests/block_with_iommu.py
qemu/tests/cfg/block_with_iommu.cfg

New cases:
1. verify_enabled: Verify whether IOMMU is enabled in a guest
with virtio_scsi block device.
2. with_installation: Check virtio driver can be installed
successfully with iommu_platform=on during guest installation.
ID: 1716793, 1705625

block_with_iommu: Add new cases to test iommu with block device

---

qemu/tests/cfg/qemu_disk_img.cfg
qemu/tests/cfg/qemu_img.cfg
qemu/tests/qemu_disk_img_convert.py

qemu_img: Delete the dup cases with the ones in qemu_disk_img
1. Add the remain supported cluster_size values - A power of two between 512 and 2048k.
2. Delete the duplicate case with the ones in qemu_disk_img cfg file.
ID: 1781474

qemu_disk_img: Complete the supported cluster_size values

---

qemu/tests/win_heavyload.py

win_heavyload: Use vm.cpuinfo.smp instead of params["smp"]

---

generic/tests/cfg/guest_test.cfg
generic/tests/guest_test.py

1. guest_test.isa_serial_operations: don't need to reboot before test
2. Remove existing "dst_rsc_path" for both linux and windows
3. Use 'dhclient -r' instead of kill and restart on old version
4. For RHEL8 and later, use nmcli to control network
id: 1781468

guest_test: Use nmcli to control network on rhel8

---

qemu/tests/cfg/larger_buffer_with_none_cache_mode.cfg
qemu/tests/larger_buffer_with_none_cache_mode.py

1. Create 100M source image via 'dd'.
2. Convert the source image and check whether the maxim
result of pwrite/pwrite64 system call is 2M.
ID: 1784696

New case of larger_buffer_with_none_cache_mode

---

qemu/tests/cfg/image_creation_lock_release.cfg
qemu/tests/image_creation_lock_release.py

1. Create raw image and close it after 0.5 sec.
2. Check there is no error of the CML.
ID: 1785120

New case of image_creation_lock_release

---

qemu/tests/cfg/block_with_iommu.cfg

Add "image_verify_bootable = no" in config file
to disable to verify the image whether is bootable.
ID: 1786545

block_with_iommu: Disable to verify bootable

---

qemu/tests/cfg/hpt_max_page_size.cfg
qemu/tests/hpt_max_page_size.py

3 new cases:
1.Set cap-hpt-max-page-size=64k with hugepage
to check hugepage value.
2.Set cap-hpt-max-page-size=64k without hugepage
to check hugepage value.
3.Set cap-hpt-max-page-size=16m without hugepage
and with TCG to check hugepage value.
ID: 1780874, 1783878, 1784328 

hpt_max_page_size: New cases to test maximum page size for hpt guests

---

qemu/tests/cfg/virtio_blk_with_discard_write_zeroes.cfg
qemu/tests/virtio_blk_with_discard_write_zeroes.py

Add cases to test virtio_blk with the options discard and
wirte_zeores by checking their attributes and status.
ID: 1731471

Add cases to test virtio_blk with discard and write_zeroes

---

qemu/tests/cfg/image_creation_lock_release.cfg

Change the name from defaul to the test image name.
ID: 1788817

image_creation_lock_release: Fix the wrong image name

---

qemu/tests/cfg/device_option_check.cfg

scsi-disk is deprecated,
Change scsi-disk to scsi-hd or scsi-cd in device_option_check testing
ID:1787535 , 1782155

Change scsi-disk to scsi-hd or scsi-cd

---

provider/blockdev_snapshot_base.py
qemu/tests/cfg/blockdev_snapshot.cfg

blockdev_snapshot:add cfg to support snapshot to
non-default cluster-size target, and add rebase
mode "unsafe".
blockdev_snapshot_base:remove redundant code
id:1790384,1790385

Snapshot to target with non-default cluster-size

---

provider/block_devices_plug.py

Failed to hotplug the format node since need to hotplug a protocol
node before it, so modify the order of hotplugging blockdev nodes.
ID: 1788350

block_devices_plug: Fix the order of hotplugging blockdev nodes

---

qemu/tests/boot_from_device.py
qemu/tests/cfg/boot_from_device.cfg

No need to login and verify guest up, also mixed usage of bootable
and unbootable devices looks messy. Change all test cases to use
new created unbootable image.
Booting from iscsi is not so related with seabios and it needs extra
preparation steps. So remove boot_from_iscsi_device.
Categorize booting from cdroms:
ide-cd/scsi-cd
Categorize booting from disks:
ide-hd/virtio-blk/scsi-hd/usb-storage
ID: 1656723

boot_from_device: re-factor boot_from_device

---

qemu/tests/cfg/qemu_img_info_while_running.cfg
qemu/tests/qemu_img_info_while_vm_running.py

boot_and_info_same_img case
`qemu-img info` should support to get the info of a
running luks image.
ID: 1790784

qemu_img_info_while_vm_running: Support luks image

---

provider/blockdev_snapshot_base.py
qemu/tests/blockdev_snapshot_stress.py
qemu/tests/cfg/blockdev_snapshot_stress.cfg

blockdev_snapshot_stress:do snapshot under stress,
and rebase_mode=unsafe to avoid a product bug.
blockdev_snapshot_base:add scenario for snapshot on
system disk.
id:1793258

Snapshot on guest under stress

---

qemu/tests/cfg/remote_negative.cfg
qemu/tests/negative_create.py

negative_create.py is a negative test case that makes sure VM cannot be started, so we can use it for this test scenario;
Also, enhanced it with error message check, so that tc can check the expected error message from qemu.
ID: 1786495

Added configuration for 'boot from a readonly iscsi image'

---

qemu/tests/cfg/migration_with_remote.cfg

1. iscsi&ceph images are used for OS images
2. The following testing scenarios are covered:
migrate VM on the same host
migrate VM with postcopy on the same host
Signed-off-by: zhencliu <zhencliu@redhat.com>
ID: 1786232, 1786233

Added configuration for VM migration

---

qemu/tests/cfg/remote_block_hotplug.cfg

1. Added cfg/remote_block_hotplug.cfg
2. ceph and iscsi were supported
ID: 1786237, 1786238

Added configuration for remote image hotplug/hotunplug

---

generic/tests/cfg/multi_queues_test.cfg
generic/tests/cfg/ntttcp.cfg
qemu/tests/cfg/iperf_test.cfg
qemu/tests/cfg/mq_enabled_chk.cfg
qemu/tests/cfg/multi_nics_verify.cfg
qemu/tests/cfg/netkvm_cpu_mapping.cfg

avocado-vt can use vcpu_maxcpus to define smp without using smp, this
will make some cases fail, such as 'queues = ${smp}', fix it to check both
smp and vcpu_maxcpus
ID: 1782698

Fix '${smp}' issue since vt can use vcpu_maxcpus to define smp

---

qemu/tests/block_check_fds.py
qemu/tests/cfg/block_check_fds.cfg

New a case that checks file descriptors when attaching
and detaching virtio-scsi block devices.
ID: 1797872

block_check_fds: New case to check file descriptors

---

qemu/tests/hotplug_block_resize.py

The original codes just support to resize block device in
the drive mode, so adds support blockdev device.
ID: 1789204

hotplug_block_resize: Fix support to resize blockdev device

---

qemu/tests/cfg/boot_from_device.cfg
qemu/tests/cfg/seabios_strict.cfg

Disable image_boot to prevent interference with bootindex.
ID: 1781445

image_boot: disable image_boot

---

qemu/tests/cfg/multi_disk.cfg

Add cache options "writethrough" and "writeback" for
testing scsi-generic.
ID: 1731613

multi_disk: Add cache option for testing scsi-generic

---

qemu/tests/balloon_check.py
qemu/tests/cfg/balloon_check.cfg
qemu/tests/cfg/balloon_memhp.cfg
qemu/tests/cfg/balloon_minimum.cfg
qemu/tests/cfg/balloon_service.cfg

1. 64 bit windows guest free mem is larger than 150M when balloon vm mem to boundary value;
2. Guest mem stats value got from qmp compare threshold 150M is not big enough for big mem windows guests, use a compare ratio instead
3. After each balloon operation, 300M is not big enough for large mem vm,  use a compare ratio instead.
ID: 1775459, 1772845, 1774850

balloon_check: Extend compare threshold for guest mem change

---

qemu/tests/cfg/balloon_check.cfg
qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/virtio_serial_file_transfer.cfg

Add 3 three new cases:
1. rng works when iommu_platform=on;
2. balloon function works when iommu_platform=on;
3. boot virtio-serial-pci with iommu_platform=on.
BZ: 1783820, 1783821, 1783822

New case: Add iommu support for virtio balloon/rng/serial devices

---

qemu/tests/block_hotplug.py

Fix compatible with python2 & 3:
There is no attribute clear() for list type in
python2, so replace it with del.
Fix fail to hotplug device:
Judge whether the return of simple_hotplug is
False, since the return value is the string ""
when sending qmp command "__com.redhat_drive_add"
successfully.
ID: 1771278, 1771281

block_hotplug: Fix fail to hotplug device

---

qemu/tests/cfg/cpu_device_hotplug_during_boot.cfg
qemu/tests/cpu_device_hotplug_during_boot.py

Add new cases to hotplug vCPU device during boot stage, check the number
of CPU in guest after log into guest successfully.
ID: 1787974, 1787976

Add new cases to hotplug vCPU device during boot

---

qemu/tests/cfg/check_link_speed_duplex.cfg
qemu/tests/check_link_speed_duplex.py

1 Change default speed for windows according to product change
2 Delete default speed check for linux guest
id:1789673

check_link_speed_duplex: change/delete default speed for guests

---

qemu/tests/netkvm_change_param_value_test.py

The command of ping is not correct, it using "-i" params, should
be deleted.
id:1801492

netkvm_change_param_value_test:change ping prams for host to guest

---

qemu/deps/playbook.yml
qemu/tests/cfg/nested_test.cfg
qemu/tests/nested_test.py

ID: 1802927
Add options for Bootstrap.sh and enable nested test cases to use avocado and tp-qemu stable build in gating. 

Add options to Bootstrap.sh

---

qemu/tests/cfg/device_option_check.cfg

Modify the cfg file to support checking the wwn option of cdrom
under s390x platform
ID: 1800455

device_option_check: Support checking cdrom wwn option under s390x

---

qemu/tests/nested_test.py

use vm.wait_for_get_address replace vm.get_address, and
set timeout value to 240s
id: 1804737

nested_test: Fix get L1 guest ip address failed issue

---

qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
qemu/tests/invalid_cpu_device_hotplug.py

Add 4 new test cases to test hotplug cpu device with invalid properties.
Bugzilla ID: 1782030, 1782031, 1782032, 1782033, 1787264

4 new cases to test hotplug invalid cpu device

---

qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cpu_device_hotplug_maximum.py

Add test cases to test hotplug maximum number of vCPU devices and then hotunplug them.
Bug ID: 1786501

Add test cases to test hotplug maximum number of vCPU devices

---

qemu/tests/cfg/qemu_guest_agent.cfg

python bin should be python2.7 in windows guest.
ID: 1805552

qemu-guest-agent: bug fix of python bin in windows guest

---

qemu/tests/qemu_guest_agent.py

The interface of class 'Monitor' have changed, update the call
id: 1806375

qemu_guest_agent: Fix connect monitor failed issue

---

qemu/tests/cfg/cluster_size_check.cfg

Creating with preallocation mode metadata and different cluster sizes.
ID: 1804556

New case of cluster_size_check with preallocation mode metadata

---

qemu/tests/block_resize.py
qemu/tests/cfg/block_hotplug.cfg
qemu/tests/cfg/block_resize.cfg

Cancel the testing when resizing to 2T or 16T on the windows bios guest
and 16T on the windows ovmf guest since they don't support to do it.
ID:1785990
Signed-off-by: Menghuan Li <menli@redhat.com>

block_resize: Cancel testing when resizing to 2T or 16T

---

qemu/tests/cfg/numa_opts.cfg

Without extra parameters,the default numa node is 1 on ppc
ID:1805617
Signed-off-by: mdeng@redhat.com <mdeng@redhat.com>

numa_opts: Update default numa node on ppc

---

qemu/tests/cfg/vioinput_enable.cfg

new case that do reboot/shutdown/system_rest/migrate
when virtio-mouse/tablet device attached.
id: 1786304, 1786302, 1786289, 1456182, 1456176, 1456177

vioinput_enable: add new case for virtio-mouse/tablet device attached.

---

qemu/tests/cfg/win_virtio_driver_update_test.cfg

Add 4 new cases:
win_virtio_driver_update_test..device_mouse..uninstall_install/downgrade_upgrade
win_virtio_driver_update_test..device_tablet..uninstall_install/downgrade_upgrade
id: 1786405, 1786406, 1786407, 1786408

Add new case install_uninstall/downgrade_upgrade driver for virtio mouse/tablet device

---

qemu/tests/cfg/system_reset_during_boot.cfg
qemu/tests/system_reset_bootable.py

some vm can't bootup when the wait_time is 0, add this params to
make this test more easier to control.
id: 1808203

system_reset_during_boot: add minimal waiting time before reset vm

---

qemu/tests/qemu_guest_agent.py

Failed to get "target_release" on non-x86, update pattern to fix it.
- x86-64: rhel810-64
- ppc64le: rhel810-ppc64le
- aarch64: rhel810-aarch64
ID: 1811384

qemu_guest_agent: Update pattern to get "target_release"

---

provider/input_event_proxy.py

sometimes python_bin = 'python' does not work on windows os,
changed python_bin = 'python2'
id: 1811535

input_event_proxy: change python_bin = 'python2' for windows

---

qemu/tests/win_sigverif.py

Add command to ensure guest on desktop and wait 60s to make
all popups pop up to eliminate the impact of popups on autoit.
ID:1797847

win_sigverif: Fix 'sigverif logs are not created' error 

---

qemu/tests/cfg/block_hotplug.cfg
qemu/tests/cfg/block_hotplug_in_pause.cfg
qemu/tests/cfg/block_hotplug_negative.cfg
qemu/tests/cfg/block_resize.cfg
qemu/tests/cfg/disk_extension.cfg

id: 1808277
Related tests:
1. block_hotplug
2. block_hotplug_negative
3. block_hotplug_in_pause
4. block_resize
5. disk_extension

Remove configs with deprecated data plane

---

qemu/tests/block_iscsi_lvm.py
qemu/tests/cfg/block_iscsi_lvm.cfg

New a case that installs the guest OS on the lvm device which is
created on an iSCSI target.
ID: 1731616

block_iscsi_lvm: New case to install on lvm device with iSCSI target

---

qemu/tests/ksm_base.py
qemu/tests/numa_memdev_options.py
qemu/tests/smbios_table.py
qemu/tests/timedrift.py
qemu/tests/timerdevice_host_time_back.py
qemu/tests/timerdevice_time_jump_check.py
qemu/tests/x86_cpu_model.py

Drop the usage of 52lts compatibility layer to follow VT's roadmap.

Remove usage of 52lts compatiblity layer

---

qemu/tests/cfg/format_disk.cfg
qemu/tests/cfg/usb.cfg
qemu/tests/format_disk.py
qemu/tests/usb_storage.py

Add umount and wipefs steps before formatting in case the hard drive
contains a mounted filesystem.
ID: 1815053

umount_wipefs: add umount and wipefs steps

---

qemu/tests/cfg/commit_snapshot_to_raw_backing.cfg
qemu/tests/commit_snapshot_to_raw_backing.py

id: 1816522
if image is a block device, the size check will fail the case because
QEMU fails to get correct size info from block device. So add a switch
to enable tester to turn off the snapshot size check.

commit_snapshot_to_raw_backing: add switch for size check 

---

provider/storage_benchmark.py
qemu/tests/cfg/fio_linux.cfg

1. storage_benchmark: Add code to transfer fio installation timeout value from cfg file
2. fio_linux: Add fio installation timeout value for s390x in the cfg file
ID: 1815458
Signed-off by: Nini Gu <ngu@redhat.com>

fio_linux: Add fio installation timeout value to make it work on s390x

---

qemu/tests/cfg/trim_support_test.cfg

virtio-scsi does support trim natively at qemu level.
ID:1814176

Add trim test on virtio_scsi

---

qemu/tests/virtio_scsi_mq.py

Fix bug cpu topology: value of sockets * dies * cores * threads less than smp_cpus
ID:1793766

Set smp to vcpu_maxcpus

---

qemu/tests/cfg/savevm_loadvm.cfg
qemu/tests/savevm_loadvm.py

After launch a VM, save the VM and load it while VM is running, verify
guest kernel and dmesg, qemu does not crash.
ID: 1807416

savevm_loadvm: save VM and then load it while VM is running

---

qemu/tests/cfg/blockdev_commit.cfg
qemu/tests/cfg/blockdev_full_backup.cfg
qemu/tests/cfg/blockdev_full_backup_multi_disks.cfg
qemu/tests/cfg/blockdev_full_mirror.cfg
qemu/tests/cfg/blockdev_snapshot.cfg
qemu/tests/cfg/blockdev_stream.cfg

blockdev_snapshot:set rebase_mode unsafe
blockdev_commit:set rebase_mode unsafe
blockdev_stream:set rebase_mode unsafe
blockdev_full_mirror:set rebase_mode unsafe
blockdev_full_backup_multi_disks:set rebase mode unsafe
id:1817908

Set rebase_mode unsafe for some storage_vm_migration cases

---

qemu/tests/cfg/interrupt_check.cfg
qemu/tests/interrupt_check.py

Get interrupt info on guest, execute test and check again, to verify
that the interruption has increased.
ID: 1809450 1809452 1809454 1809456 1809459

Check number of interrupts on guest after execute some tests

---

qemu/tests/plug_cdrom.py

There just using sendline but not wait guest to shutdown.
It makes the connection reset.
ID:1816066,1816021,1777166

Fix async reboot to sync reboot

---

qemu/tests/cfg/cdrom_test.cfg
qemu/tests/cfg/change_media.cfg
qemu/tests/cfg/check_block_size.cfg
qemu/tests/cfg/device_option_check.cfg
qemu/tests/cfg/eject_media.cfg
qemu/tests/cfg/ioeventfd.cfg
qemu/tests/cfg/migration_with_block.cfg
qemu/tests/cfg/plug_cdrom.cfg
qemu/tests/cfg/virtio_scsi_cdrom.cfg

id: 1813792
Since scsi-cd is incompatible with iothread, adding configs to disable
iothread for scsi-cd related cases explicitly.

Disable iothread explicitly for scsi-cd cases

---

qemu/tests/vioinput_hotplug.py

Due to there has a unused module on vioinpu_hotplug.py file,
many patch hit ci check failed issue, here delete it.
id:1820138

vioinput_hotplug: delete import module line to fix ci check failed issue

---

qemu/tests/cfg/migrate.cfg

The with_reboot migration is not reliable when using QMP RESET event as
check for reset, because the VM object is constantly changing.
This is related to: https://github.com/avocado-framework/avocado-vt/pull/2289 which implements the "force_reset_go_down_check" parameter.

qemu..migrate: Override force_reset_go_down_check on with_reboot

---

qemu/tests/migration.py
qemu/tests/migration_with_speed_measurement.py

With multiple ping_pong iterations I noticed the mig_set_speed does not actually work properly. It's because the migrate_set_speed needs to be issued before each iteration and not just once. I checked the currently existing pre_migrate functions and it looks like having them executed before each iteration makes sense so I'd like to propose doing that.
While testing this I noticed the "migration_with_speed_measurement" test is a bit broken, so added a few fixes.

qemu..migration: Run pre_migrate before each iteration and set_speed fixes

---

provider/cpu_utils.py
qemu/tests/cfg/cpu_device_hotplug_during_boot.cfg
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_device_hotpluggable_with_stress.py

1. update pattern in `get_guest_cpu_ids` to make it work on s390
2. update to make some existing cpu hotplug cases work on s390
3. make a simple change so that some windows versions do not check cpu topology
Bug ID: 1817863, 1792104

Make cpu hotplug cases work on s390

---

qemu/tests/cfg/blockdev_snapshot.cfg
qemu/tests/cfg/blockdev_snapshot_multi_disks.cfg
qemu/tests/cfg/blockdev_snapshot_reboot.cfg
qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg
qemu/tests/cfg/blockdev_snapshot_stress.cfg
qemu/tests/cfg/blockdev_stream.cfg
qemu/tests/cfg/live_backup_add_bitmap.cfg

Add support for linux only on snapshot and stream cases
id: 1825076

blockdev_snapshot: add support for linux only

---

qemu/tests/boot_order_check.py
qemu/tests/cfg/boot_order_check.cfg

Wait a time interval until get the device pci address
It needs more time to get the complete 'info pci' information, so wait a time interval to get the device pci address.
ID:1820473

Fixed bug about boot_order_check when run it with q35

---

qemu/tests/change_media.py

Since the argument "id" in qmp command "blockdev-change-medium" is
different between virtio-scsi and virtio-blk for the non-removable
media, actually it depends on the "qdev" value from the command
"query-block".
ID: 1783870

change_media: Fix blockdev change non cdrom with virtio-blk

---

qemu/tests/block_scsi_generic_inquiry.py
qemu/tests/cfg/block_scsi_generic_inquiry.cfg

New a case that uses sg_inq command to inquiry the virtio devices
when the underlying host devices have failed in the guest.
ID: 1822055

block_scsi_generic_inquiry: New case that sg_inq virtio devices

---

qemu/tests/cfg/boot_order_check.cfg

cd_bootindex: remove cdroms to avoid bootindex conflict

---

qemu/tests/boot_from_remote.py
qemu/tests/cfg/remote_boot.cfg

1. use one glfs instance per volume
2. Boot from glusterfs with attach device in local filesystem
3. Controll libgfapi logging level
ID: 1814483, 1814493, 1814492

Add 3 new cases

---

qemu/tests/cfg/hotplug_mem_negative.cfg
qemu/tests/hotplug_mem_negative.py

6 new cases to test hotplug mem negative options:
1.hotplug memory whose size overcommit host memory size
2.hotplug Min memory size=0
3.add memory device with no wrong numa node id
4.add memory backend with wrong size
5.memory backend ram option negtive test
6.memory device addr option negtive test
ID: 1813746, 1813747, 1813748, 1813750, 1813754, 1813755

hotplug_mem_negative: New cases to test hotplug mem negative options

---

qemu/tests/cfg/cpu_device_hotplug_maximum.cfg

1. Disable windows guest for case 'max_socket'
2. Only enable case 'max_thread' on ppc platform
ID: 1834564, 1834570

cpu_device_hotplug_maximum: update case 'max_socket' and 'max_thread'

---

qemu/tests/cfg/seabios_order_once.cfg

set "image_boot = no" to prevent bootindex option from appearing
ID：1836802

set "image_boot = no" to prevent bootindex option from appearing

---

qemu/tests/cfg/hotplug_mem.cfg

1. Shorten pause_time so guest resume in time to respond to unplug
2. Disable cases to test unplug during guest reboot/reset
3. Reduce case number by adding some limits
ID: 1829659

hotplug_mem: Refine test cases about memory unplug

---

qemu/tests/block_with_iommu.py
qemu/tests/cfg/block_with_iommu.cfg

New a case to use command kexec to reload kernel under
the IOMMU mode.
ID: 1822052

block_with_iommu: New case to reload kernel with iommu

---

qemu/tests/cdrom_block_size_check.py
qemu/tests/cfg/cdrom_block_size_check.cfg

Improve codes by following:
1. Add checking "DEVICE_TRAY_MOVED" event after eject cdrom
and change cdrom.
2. Add checking whether the cdrom's tray opened after change
cdrom.
ID: 1778666, 1645000

cdrom_block_size_check: Improve codes

---

qemu/tests/cfg/ppc_check_cpu_and_mmu.cfg
qemu/tests/ppc_check_cpu_and_mmu.py

Add a new case to check the CPU model and MMU mode of host and guest are
matched.
ID: 1837804

ppc_check_cpu_and_mmu: New case to check CPU and MMU of host and guest

---

qemu/tests/block_hotplug_in_pause.py
qemu/tests/cfg/block_hotplug_in_pause.cfg

The device will still in qtree if the vm is paused after unplug
the frontend device in the blockdev mode and can not unplug the
backend blockdev nodes, so check qtree after resume the vm and
unplug the backend devices.
ID: 1749697

block_hotplug_in_pause: Fix failed to unplug device

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

For fs info test, there is no need to
check cdrom's info, check the normal disk's
serial number is enough.
ID: 1808951

qemu_guest_agent: bug fix of keyerror

---

qemu/tests/rh_kernel_update.py

The output returned by "brew buildinfo xxx" has a "Signatures" field,
update the "pkg_pattern" to handle this issue.
ID: 1842845

rh_kernel_update: update pkg_pattern to handle brew "Signatures"

---

qemu/tests/remote_server_disconnected.py

gluster_peers now is defined as 
gluster_peers = '[{"host": "dell-per415-03.lab.eng.pek2.redhat.com"},{"host":"hp-z420-01.qe.lab.eng.nay.redhat.com"}]'
instead of
gluster_peers = dell-per415-03.lab.eng.pek2.redhat.com hp-z420-01.qe.lab.eng.nay.redhat.com
ID: 1842766

gluster_peers is a string in json

---

qemu/tests/rng_bat.py

Now and then it takes a short time interval for rngd status becomes
'active (running)' after booting up when using rng-egd backend.
Wait for a reasonable time to get correct rngd status.
ID: 1842854

rngd_status: wait for a reasonable time to get correct rngd status

---

qemu/tests/cfg/usb.cfg

1.restrict uhci/ehci controllers only cover boot/reboot cases
2.correct usb_type_usbtest for qemu-xhci
ID: 1845007

usb_controller: restrict uhci/ehci controllers only cover boot/reboot cases

---

generic/tests/cfg/unattended_install.cfg

The reason is scsi-cd can not attatched scsi bus which enabled
data plane.
ID:1844920

Fix unattend install issue for cd-rom installtion

---

qemu/tests/hugepage_specify_node.py

hp_config is an example of HugePageConfig().setup() method,
so there is no cleanup() object.
Change hp_config to an instance of HugePageConfig(),
so that hp_config contains both .setup() and .cleanup().
ID: 1839632

hugepage_specify_node: fix 'NoneType' object has no attribute 'cleanup'

---

qemu/tests/cfg/disk_extension.cfg
qemu/tests/disk_extension.py

Fix using  static /dev/loop6 issue.
ID:1846226

Find unused loop device as image device

---

provider/block_devices_plug.py

Support the pci bus specified on creating block devices.
ID: 1846973

block_devices_plug: Fix support pci bus specified

---

qemu/tests/cfg/nested_test.cfg
qemu/tests/nested_test.py

Fix two timing related bugs:
Bug 1847824 - [KVM_AUTOTEST] When L1 guest starts up slow will get SCP error 
Bug 1822117 - [KVM_AUTOTEST] No test log for L1 guest when ansible cmd terminated as timeout.
ID: 1847824, 1822117

When L1 guest starts up slow will get SCP error

---

qemu/tests/cfg/timedrift_adjust_time.cfg
qemu/tests/timedrift_adjust_time.py

Case 1:resume a paused VM with "-rtc base=localtime,clock=vm" (only windows)
Case 2:resume a paused VM with "-rtc base=localtime,clock=host" (only windows)
Case 3:resume a paused VM with "-rtc base=utc,clock=vm" (only linux)
Case 4:resume a paused VM with "-rtc base=utc,clock=host" (only linux)
bug id: 1825738, 1828028, 1828029, 1828030

timedrift_adjust_time: add four timer device cases

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

Pseries supports nvdimm device since qemu-5.0, add the basic test case for it.
ID: 1829139

Support nvdimm.nvdimm_basic on pseries

---

qemu/tests/cfg/driver_load.cfg

This testing will break windows OS image.
It result in other test case failed on BSOD.
ID:1848937

Adding backup/restore image action for driver_load testing

---

qemu/tests/cfg/usb.cfg
qemu/tests/usb_host.py

1.remove the semicolon at the end of usb_reply_msg.
usb_negative_test becomes invalid with this semicolon.
2.update usb_reply_msg with latest info.
3.remove the reboot step at the end of usb_negative_test.
ID: 1849539

usb_negative: correct usb_reply_msg to validate usb_negative_test

---

qemu/tests/ansible_test.py
qemu/tests/cfg/ansible_test.cfg

Add an Ansible Playbook test case. The playbook will be cloned from the
git repository. You can write the required "play/role/task". In this
case, all the tasks you defined in the playbook will be executed from
the host via "ansible-playbook". You can do anything in the guest with
your playbook :)
ID: 1841419

ansible_test: Add a basic ansible playbook test

---

qemu/tests/cfg/rng_bat.cfg

1.Not support RHEL 7 host.
2.Cover 3 iommu scenarios.
ID: 1853798

rng_iommu: update rng_bat.iommu_enabled

---

provider/block_devices_plug.py
qemu/tests/cfg/multi_disk_random_hotplug.cfg
qemu/tests/multi_disk_random_hotplug.py

Summary:
1. Add a step that checks whether vioscsi.sys verifier
enabled in guest.
2. Add a step that does iozone and dd test on the new disks
after check hotplug status.
3. Fix support the machine type q35.
4. Call the BlockDevicesPlug's methods instead of the parts
of hotplug and unplug.
5. Define a configure_images_params that configures images
by params instead of the original parts.
ID: 1542350, 1566866, 1608253

multi_disk_random_hotplug: Refactoring the codes

---

qemu/tests/boot_from_nbd_image.py
qemu/tests/cfg/remote_boot.cfg
qemu/tests/cfg/remote_image_access.cfg
qemu/tests/cfg/remote_negative.cfg
qemu/tests/nbd_long_export_name.py
qemu/tests/remote_image_guestfish_access.py
qemu/tests/remote_image_ncat_access.py
qemu/tests/remote_image_nmap_access.py
qemu/tests/remote_image_qemu_io_access.py
qemu/tests/remote_image_unix_socket_access.py

Add the nbd image export/access test cases
1. access system image with guestfish without vm bootup
2. access exported image with qemu-io
2.1 drop sync testing
2.2 drop connection testing
3. scan the port of exported image with nmap
4. access image with unix domain socket
5. export image in nbd internal server, access it with ncat
5.1 export it with unix socket
5.2 export it with inet
6. boot from nbd image in raw/qcow2/luks format
6.1 export raw image as raw image, access it as raw image
6.2 export qcow2(full/falloc) image as raw image, access it as qcow2 image
6.3 export luks image as raw image, access it as luks image
6.4 export qcow2 image as qcow2 image, access it as raw image
6.5 export luks image as luks image, access it as raw image
7. Export image with max length of export name …

Add the nbd image export/access test cases

---

provider/block_devices_plug.py

1. block_devices_plug: Only assign bus for pci device when hotplug
There are 2 issues:
1. Only pci device should be assigned a bus when been hot plugged,
-dirve/-blockdev should not have a bus.
2. It should make sure that the device is a QDevice before check
if it is pci device. -object for luks should be skipped.
2. block_devices_plug: Fix variable referenced before assignment
id: 1852685, 1852690

block_devices_plug: Fix 2 hotplug issues

---

qemu/tests/cfg/multi_disk.cfg
qemu/tests/multi_disk.py

1.Increase vm monitor login timeout
2.Decrease disk number for virtio_scsi_variants
ID:1838891

Improve virtio_scsi_variants test cases efficiency

---

qemu/tests/cfg/block_iscsi_lvm.cfg

Assign unattended delivery method to cdrom explicitly in the
scenarios where unatteneded install guest OS form extra cdrom.
ID: 1838501

block_iscsi_lvm: Assign unattended delivery method explicitly

---

qemu/tests/block_hotplug.py
qemu/tests/cfg/block_hotplug.cfg

Failed to insert the SCSI device into the specified HBA controller
because that setting the params "drive_bus" is to specify the HBA
the controller then call method list_missing_named_buses of 
DevContainer to search HBA is used by iterating DevContainer.__buses 
list. But the __buses list didn't change after hotplugging since calling
images_define_by_params and calling simple_hotplug are not used by
matching way, so the __buses list is still using the same.
ID: 1771912

block_hotplug: Fix failed to insert scsi device into specified HBA

---

qemu/tests/qemu_img.py

specify parameter name img_fmt when calling function _get_image_filename
ID: 1858314

qemu_img.rebase: correct the parameter

---

generic/tests/ping.py

`process.run` cannot pass empty command line and will raise IndexError,
only execute the ext_host_get_cmd if it is not empty.
ID: 1858213

ping.ext_host: Only execute ext_host_get_cmd when it is not empty

---

qemu/tests/cfg/timerdevice.cfg
qemu/tests/timerdevice_boot.py

boot the guest with "-rtc base=utc,clock=host" when host 100% load (only linux)
boot the guest with "-rtc base=localtime,clock=host" when host 100% load (only windows)
reboot a guest with "-rtc base=localtime,clock=host" when host 100% load (only windows)
bug id: 1827016, 1836202, 1846824

add timer device case

---

qemu/tests/ansible_test.py

Sometimes, guest can return its IP address before it is available, and
the ansible-playbook command failed to execute through ssh connection.
So log into the guest at first.
ID: 1858245

ansible_test: Log into the guest at first to ensure it is available

---

provider/nbd_image_export.py

QemuImg.create should take the image specified params as its argument

---

qemu/tests/cfg/pcie_hotplug_opt.cfg
qemu/tests/pcie_hotplug_opt.py

Hot-unplug/plug virtio-blk-pci, virtio-scsi-pci, virtio-net-pci
while the parent pci-root-port use 'hotplug=off'
depends on: https://github.com/avocado-framework/avocado-vt/pull/2661
id: 1856690

Add case to test 'hotplug=off' option for pcie-root-port

---

qemu/tests/cfg/win_irq_check.cfg

Setting "vectors=0" for vioscsi driver since qemu product doesn't
support it, so we need to avoid trigger it.
ID: 1858148

win_irq_check: Remove vectors=0 scenarion in vioscsi driver

---

qemu/tests/cache_sizes_test.py

Since winutils iso will be added directly when testing it
with windows guest. And cache-size is a qcow2 option,
it cannot be given to any imgfmt but qcow2.
To avoid it, just set this parameter to system image.
ID: 1862315

cache_sizes_test: set parameter cache-size for system image

---

provider/blockdev_base.py
qemu/tests/blockdev_inc_backup_bitmap_mode_test.py
qemu/tests/blockdev_inc_backup_test.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_mode_test.cfg
qemu/tests/cfg/blockdev_inc_backup_cluster_test.cfg
qemu/tests/cfg/blockdev_inc_backup_test.cfg

image_chain is used for showing the backing info between images
ID: 1861951

Change image_chain to image_backup_chain for backup use

---

qemu/tests/qmp_command.py

The disk device qemu command line has two configurations:
1). blockdev config, eg:
-blockdev node-name=file_image1,driver=file,filename=/var/**.qcow2
-blockdev node-name=drive_image1,driver=qcow2,file=file_image1
2). disk drive config, eg:
-drive id=drive_image1,if=none,format=qcow2,file=/var/***.qcow2
If disk drive config, the expect value should be:
{'device': 'drive_image1', 'qdev': 'image1', 'format': 'qcow2'}
If blockdev config, the expect value should be:
{'node-name': 'drive_image1', 'qdev': 'image1', 'format': 'qcow2'}
Signed-off-by: Chen Qun <kuhn.chenqun@huawei.com>

qmp_command: add qmp 'node-name' expect value for blockdev

---

qemu/tests/cfg/watchdog.cfg

The check cmd is "qemu-kvm  -M virt -watchdog '?'" for aarch64.
Signed-off-by: Chen Qun <kuhn.chenqun@huawei.com>

watchdog: check watchdog device need machine for aarch64

---

qemu/tests/cfg/create_large_raw_img.cfg
qemu/tests/create_large_raw_img.py

The following error messages should all work well.
1. Image size must be less than 8 EiB!
2. Invalid image size specified.
Must be between 0 and 9223372036854775807.
ID: 1862381

add new error message when creating large image over xfs filesystem

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 1861283
depends on [avocado-framework/avocado-vt#2672](https://github.com/avocado-framework/avocado-vt/pull/2672)

x86_cpu_flags: new case to test flag avx512_bf16

---

qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cpu_device_hotplug_maximum.py

1. Update unplug verification timeout
2. Set "allow_pcpu_overcommit = no" since overcommit on a single guest is not a positive scenario.
ID: 1867003

cpu_device_hotplug_maximum: Update unplug verification timeout

---

qemu/tests/cfg/valgrind_memalign.cfg

valgrind does not support sandbox options,refer bz 1800495
ID:1869981

valgrind_memalign: delete sandbox options

---

qemu/tests/cfg/ppc_ic_mode_check.cfg
qemu/tests/ppc_ic_mode_check.py

Launch a guest with "kernel-irqchip=on/off" and "ic-mode=xics/xive" and
then check them from human monitor and guest's interrupts information.
ID: 1870448, 1870450, 1870451, 1870452

ppc_ic_mode_check: Add test cases to check ic-mode and kernel-irqchip

---

qemu/tests/cfg/qemu_img_negative.cfg
qemu/tests/image_creation_luks_with_non_utf8_secret.py

1. It should be failed to create the image.
2. The error information should be corret.
e.g. Data from secret sec0 is not valid UTF-8
ID: 1867037

Add a new case, create luks format image with non utf8 secret

---

qemu/tests/cfg/block_with_iommu.cfg

Default not send key when run case block_with_iommu with ovmf that
cause the guest can not boot from CD.
ID: 1838944

Fix windows guest installation issue with ovmf in case block_with_iommu

---

qemu/tests/cfg/usb.cfg
qemu/tests/usb_host.py

1.add I/O operation for passthrough usb stick
2.add hostbus and hostaddr options test for usb-host device
3.change to use QMP instead of HMP
4.boot up guest with a passthroughed usb device
ID: 1847777, 1847778, 1861177

usb_host: add I/O operation for passthrough usb stick

---

qemu/tests/cfg/qmp_event_notification.cfg

S3/S4 (suspend/hybernate) of guests is not supported 
for rhel7 and rhel8,remove it
ID: 1870003

qmp_event_notification: remove suspend and disk_suspend case

---

qemu/tests/cfg/nested_libguestfs_unittest.cfg
qemu/tests/nested_libguestfs_unittest.py

Add a test case, it invokes libguest-test-tool to run a unittest in
guest, analyze the test result and then check the nested file status.
ID: 1836116, 1836123

Add a case of using libguestfs-test-tool to check guest nested flag

---

qemu/tests/cfg/timerdevice_tsc_enable.cfg
qemu/tests/timerdevice_tsc_enable.py

enable TSC clocksource if invariant TSC is available (only linux
after rhel8.1)
ID: 1868209

timerdevice_tsc_enable: add one timer device case

---

qemu/tests/cfg/cpu_topology_test.cfg
qemu/tests/cpu_topology_test.py

cpu_topology_test: Add test case to test cpu topology

---

qemu/tests/cfg/single_driver_install.cfg

Install viofs driver in a preinstalled windows guest.
ID: 1877701 

virtio-fs: install viofs driver in Windows vm

---

qemu/tests/cgroup.py

get correct vcpus for vm.
id: 1875669

cgroup.freezer:get correct vcpus for vm

---

qemu/tests/cfg/qmp_command.cfg

In qemu-kvm-5.1 version, didn't find 'command_serr_enable',so remove it
ID: 1869992

qmp_command: update the return value of device list propeties

---

qemu/tests/blockdev_commit_install.py
qemu/tests/blockdev_snapshot_install.py
qemu/tests/cfg/block_with_share_rw.cfg
qemu/tests/cfg/driver_load.cfg
qemu/tests/cfg/multi_nics_hotplug.cfg
qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/qemu_option_check.cfg
qemu/tests/cfg/qmp_command.cfg
qemu/tests/cfg/qmp_event_notification.cfg
qemu/tests/cfg/usb.cfg
qemu/tests/cfg/usb_device_check.cfg
qemu/tests/cfg/watchdog.cfg
qemu/tests/nic_hotplug.py
qemu/tests/qemu_guest_agent.py
qemu/tests/qmp_command.py

1. Update cfg files to drop some network-related test cases.
2. Fix "nic_hotplug.used_netdev.nic_virtio.default" failed on pcie bridge.
3. qmp_command: Update "qmp_device-list-properties" and "qmp_query-machines" to let them work on aarch64.
4. qmp_event_notification: Drop "qmp_watchdog" for aarch64 rhel guest
5. Pattern of "cmd_get_disk" cannot handle multiple '/' like '/boot/efi', update to fix this problem.
6. qemu-kvm provided by RHEL does not yet support watchdog on aarch64, drop these cases.
7. aarch64 does not support IDE bus, modify the drive format to use a supported bus.
8. blockdev_snapshot_install & blockdev_commit_install: session.get_output will return "None" if it excepts OSError, check "serial_output" at first to ensure it is not None.
9. Update cfg files to drop some …

Update some filters to let some earlier test cases can work on aarch64

---

qemu/tests/multi_vms_nics.py

According to the case, sometimes we allocated the cpu number more than
the maxcpu supported in guest, so we add param['vcpu_maxcpus'] to set 
the value same.
ID:1872662

Change the vcpu_maxcpus to be the same with smp number

---

qemu/tests/cfg/numa.cfg
qemu/tests/numa_stress.py

tmpfs_size could set by cfg files now and it will be equal with 
node_Memtotal only with default number 0
ID:1870570

Make "tmpfs_size" able to set by cfg files to avoid lack of disk space

---

qemu/tests/cfg/tpm_unattended_install.cfg
qemu/tests/cfg/tpm_verify_device.cfg

Support running tpm_verify_device and tpm_unattended_install on aarch64.
ID: 1882580

Support running vtpm test cases on aarch64

---

qemu/tests/blockdev_mirror_install.py

serial_console.get_output can return None on PPC
when installing VM
ID: 1882969

blockdev_mirror_install: Fix None string issue

---

qemu/tests/cfg/resize_qemu_img.cfg
qemu/tests/resize_qemu_img.py

1. for increase size, add off, full and falloc
2. for shrink size, add off
ID: 1883026

resize_qemu_img: add preallocation support to resize image

---

qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/cfg/win_sigverif.cfg

Support viofs driver in win_sigverify and virtio_driver_sign_check
test cases.
ID: 1883424, 1883427

virtio-fs: support viofs driver for win driver case

---

qemu/tests/cfg/usb.cfg
qemu/tests/usb_redir.py

Add usb-redir device cases:
1. Basic functionality of USB redirection.
2. filter option of usb-redir device.
3. bootindex option of usb-redir device.
4. Host USB device negative configuration.
ID: 1876507, 1826129, 1876509, 1876510

usb_redir: add usb-redir cases

---

qemu/tests/cfg/dump_guest_memory.cfg
qemu/tests/dump_guest_memory.py

dump_guest_memory.py:dump new cases development
Before you run this case,Please make sure your host and guest installed the same version kernel.
1.check dump-guest-memory command exists in qemu side
2.Verify dump guest memory to file and process the file with crash.
ID:1878061,1882604

dump new cases development

---

qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cpu_device_hotplug_maximum.py

1. Offline all hotplugged vCPUs before hotunplug them.
2. Hotunplug operations only in Linux guests.
ID: 1879456, 1881271

Add cases to offline hotplugged vCPUs before hotunplug them

---

qemu/tests/cfg/cpu_offline_online.cfg
qemu/tests/cpu_offline_online.py

Launch a guest, take CPUs offline, and bring them online after
verification.
ID: 1882562

cpu_offline_online: New case to test offline vCPUs and then online

---

qemu/tests/cfg/cpu_device_hotplug_during_boot.cfg
qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
qemu/tests/cpu_device_hotplug_during_boot.py

1. cpu_device_hotplug_during_boot: Modify boot_patterns
2. Update required qemu version of CPU hotplug related test case for PPC
ID: 1834569

Modify boot_patterns and restrict qemu for cpu hotplug related cases

---

provider/job_utils.py
qemu/tests/blockdev_inc_backup_pull_mode_diff.py
qemu/tests/blockdev_inc_backup_pull_mode_test.py

The old block-job-* interfaces will be deprecated, use
the latest ones "job-*", still keep "block-job-set-speed"
as an exception
ID: 1882633

block jobs: replace all block-job-* interfaces with job-*

---

qemu/tests/blockdev_commit_install.py
qemu/tests/blockdev_mirror_install.py
qemu/tests/blockdev_snapshot_install.py
qemu/tests/blockdev_stream_install.py
qemu/tests/cfg/blockdev_commit_install.cfg
qemu/tests/cfg/blockdev_mirror_install.cfg
qemu/tests/cfg/blockdev_snapshot_install.cfg
qemu/tests/cfg/blockdev_stream_install.cfg

blockdev_commit_install/blockdev_mirror_install
blockdev_snapshot_install/blockdev_stream_install
updated, please be noted that we have to add more
keywords if the installation console logs changed
ID: 1888498

block job with install: Add one keyword to detect install start

---

qemu/tests/cfg/block_hotplug.cfg
qemu/tests/cfg/block_hotplug_in_pause.cfg
qemu/tests/cfg/block_hotplug_negative.cfg
qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
qemu/tests/cfg/multi_disk_random_hotplug.cfg

Cause spapr_vscsi devices not support to hotplug/hot-unplug, add
"no spapr_vscsi" in cfgs to avoid running those cases while doing hotplug
/hot-unplug
ID:1877658

Modify cfgs to avoid hotplug/hot-unplug with spapr_vscsi devices

---

qemu/tests/cfg/usb.cfg

add usb_boot and usb_reboot test cases of pci_ohci on  power
ID:1883774
Signed-off-by: MiriramDeng <mdeng@redhat.com>
It depends on https://github.com/avocado-framework/avocado-vt/pull/2784

usb_pci_ohci:add pci_ohci test cases for power

---

qemu/tests/cfg/spapr_vty_multi_backends.cfg
qemu/tests/spapr_vty_multi_backends.py

spapr_vty_multi_backends: New case to test guest with multi backends of spapr-vty
1) Boot guest with multi pci-serial with backend
2) Modify the kernel cfg file to specify the backend
3) for pty and file backend:
3.1) open and close chardev
4) for unix_socket and tcp_socket
4.1) Login guest.
4.2) move, create files inside guest
ID: 1865727, 1865728, 1865731, 1889203

spapr_vty_multi_backends: New case to test multi backends of spapr-vty

---

qemu/tests/cfg/cgroup.cfg
qemu/tests/cgroup.py

Ensure that different kernel use the correct cpu time
1.RHEL8.3 will use cpu system time.
2.Prior to RHEL8.3 will use cpu user time.
id: 1875683

cgroup.cpuset_cpus:ensure that different kernel use the correct cpu time

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Set selinux boolean `virt_qemu_ga_read_nonsecurity_files`
as on for accessing successfully and recover env back.
ID: 1870447

qemu_guest_agent: Add steps to set selinux boolean

---

qemu/tests/cfg/blockdev_commit_install.cfg
qemu/tests/cfg/blockdev_mirror_install.cfg
qemu/tests/cfg/blockdev_snapshot_install.cfg
qemu/tests/cfg/blockdev_stream_install.cfg
qemu/tests/cfg/check_block_size.cfg
qemu/tests/cfg/tpm_unattended_install.cfg

When the bootable disk has been recreated or the boot partition
is changed, better to recreate the aavmf vars as well.
ID: 1883407
Depends on: https://github.com/avocado-framework/avocado-vt/pull/2777

Restore aavmf vars if needed

---

qemu/tests/virtio_console.py

On Python 3.7 and later, async is a reserved word.  Let's swap that
for the complete word.
This is the matching change for the Avocado-VT change.
Reference: https://github.com/avocado-framework/avocado-vt/pull/2808
Signed-off-by: Cleber Rosa <crosa@redhat.com>

qemu/tests/virtio_console.py: remove reserved word

---

qemu/tests/blockdev_mirror_hotunplug.py
qemu/tests/cfg/blockdev_mirror_hotunplug.cfg

When doing blockdev-mirror, hotunplug the source image's
frontend device with device-del, the mirror job should
succeed without any error
ID: 1894885

blockdev_mirror_hotunplug: hotunplug device when doing mirror

---

qemu/tests/blockdev_mirror_ready_vm_down.py
qemu/tests/cfg/blockdev_mirror_ready_vm_down.cfg

The job should complete automatically after vm poweroff
ID: 1896238

blockdev_mirror_ready_vm_down: vm poweroff when mirror job is ready

---

provider/virt_storage/storage_volume.py

1. protocol node: set "auto-read-only":true,"discard":"unmap"
2. format node: set "read-only=false"
3. The change should not take effect on all hotplug cases, but
only on cases use storage_volume module, e.g. most storage
vm migration cases, for the settings are not required, we
should cover testing scenario without setting 1&2
ID: 1882628

storage_volume: Keep the same setting with libvirt when blockdev-add

---

qemu/tests/qemu_guest_agent.py

since guest-agent fail to set/check guest freeze status through guest-agent
socket, add "restorecon -Rv /" to avoid this issue
ID:1876731,1889312

add "restorecon -Rv /" before guest-agent run fsfreeze

---

qemu/tests/cfg/virtio_fs_share_data.cfg

Libvirt test virtiofsd daemon adds extra parameters.
So the qemu layer synchronizes these parameters.
ID: 1896214

virtio_fs_share_data: Add virtiofsd daemon extra parameters

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_flags.py

ID: 1887656
Intel 5-level paging, it extends the size of
virtual addresses from 48 bits to 57 bits.

x86_cpu_flags: test 5-level paging

---

qemu/tests/cfg/dump_guest_core.cfg
qemu/tests/dump_guest_core.py

dump_guest_core.py:qemu dump new cases development
1.Use gdb check core dump file
2.Use crash check vmcore file
ID:1888531, 1888532

qemu dump new cases development

---

provider/backup_utils.py
qemu/tests/blockdev_mirror_simple.py
qemu/tests/cfg/blockdev_mirror_simple.cfg

blockdev_mirror_simple: Add mirror job general operation test
We cover the test by setting the following explicitly
auto-finalize: true or false
auto-dismiss: true or false
ID: 1897993

Add mirror job general operation test

---

provider/blockdev_mirror_base.py
qemu/tests/blockdev_mirror_hotunplug.py
qemu/tests/blockdev_stream_subchain.py

Different outputs of query-block command will show with different
drive format(e.g. virtio-blk, scsi-hd):
qdev: /machine/peripheral/data1/virtio-backend
qdev: data1
we have to apply the check code for all outputs
ID: 1898011

blockdev_mirror_base: fix node attached check after mirror job

---

qemu/tests/cfg/verify_panic_status_with_pvpanic.cfg
qemu/tests/verify_panic_status_with_pvpanic.py

verify_panic_status_with_pvpanic:new case to verify vm status when trigger crash
Verify the QMP even with -device pvpanic when trigger crash.
ID:1894818

new case to verify vm status when trigger crash

---

qemu/tests/cfg/numa_negative.cfg

Some windows guests have minimum memory restriction, which is 4G.
If memory size < 4G, tests will cancel. So update it.
ID: 1902164

numa_negative: Update memory size to avoid test cancel

---

qemu/tests/blockdev_stream_none_existed_overlay.py
qemu/tests/cfg/blockdev_stream_none_existed_overlay.cfg

Do block-stream to a non-existed snapshot image
ID: 1900975

blockdev_stream_none_existed_overlay: Stream to a non-existed snapshot

---

qemu/tests/blockdev_stream_no_backing.py
qemu/tests/cfg/blockdev_stream_no_backing.cfg

{'execute': 'block-stream', 'arguments': { 'device': 'drive_image1'}}
in which drive_image1 is the VM system image without a backing file
ID: 1901403

blockdev_stream_no_backing: block-stream on an image without backing

---

qemu/tests/multi_disk.py

Set timeout for getting multiple disks in windows.
ID: 1699204

multi_disk: Set timeout for getting windows disk index

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

1. Support install/uninstall virtio-fs driver(windows guest only)
2. Support upgrade/downgrade virtio-fs driver(windows guest only)
3. Support disable/Enable virtio-fs driver (windows guest only)
ID:1899833,1899834,1902160

virtio-fs: new case about viofs driver

---

qemu/tests/qemu_guest_agent.py

Because of bz-1738820, add soft link '/etc/qemu-kvm/fsfreeze-hook'
as new relation output that generated by the command
line 'rpm -ql qemu-guest-agent |grep fsfreeze-hook'.
ID: 1898836

qemu_guest_agent: Add quantity related to fsfreeze-hook

---

provider/cpu_utils.py
qemu/tests/cpu_device_hotpluggable_with_stress.py

When smp and maxcpus are defined at the same time, use smp/vcpu_maxcpus
as the check number to detect that the number of vcpu does not meet the
actual situation.
ID: 1904310

Modify the logic of checking vcpu before and after plug/unplug [BATCH1]

---

qemu/tests/blockdev_stream_forbidden_actions.py
qemu/tests/cfg/blockdev_stream_forbidden_actions.cfg

mirror/commit/resize/live snapshot/stream action should be forbidden
when doing block-stream
ID: 1904988

blockdev_stream_forbidden_actions: Add qmp cmd test during stream

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

uefishell:fix the problem of incorrect file name of ovmf vars.
ID:1903088

fix the problem of incorrect file name of ovmf vars

---

qemu/tests/blockdev_stream_speed.py
qemu/tests/cfg/blockdev_stream_speed.cfg

Set an invalid speed, qemu should output the proper error message,
set a valid speed, stream job can continue without any error
ID: 1901840

Block stream speed boundary test

---

qemu/tests/cfg/slof_next_entry.cfg
qemu/tests/slof_next_entry.py

Next_entry will be cleared after reboot, grub-reboot sets the default
boot menu entry for the next boot, but not further boots after that.
ID: 1907294

slof_next_entry: Add a case to check the next_entry on guest

---

qemu/tests/blockdev_inc_backup_disabled_persistent_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_disabled_persistent_bitmap.cfg

Disabled bitmap keeps disabled after reload
ID: 1907291

blockdev_inc_backup_disabled_persistent_bitmap: Disabled bitmap testing

---

qemu/tests/blockdev_inc_backup_mod_readonly_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_mod_readonly_bitmap.cfg

Remove/clear a bitmap on a readonly image
ID: 1910292

blockdev_inc_backup_mod_readonly_bitmap: Modify a readonly bitmap

---

qemu/tests/blockdev_inc_backup_add_persistent_bitmap_when_paused.py
qemu/tests/cfg/blockdev_inc_backup_add_persistent_bitmap_when_paused.cfg

Add persistent bitmap when VM is paused, bitmap should exist no
matter VM is restarted or paused again
ID: 1910480

blockdev_inc_backup_add_persistent_bitmap_when_paused: Add bitmap test

---

provider/backup_utils.py
qemu/tests/blockdev_inc_backup_pull_mode_vm_reboot.py
qemu/tests/cfg/blockdev_inc_backup_pull_mode_vm_reboot.cfg

Backup image in pull mode(sync: none), reboot vm while pulling
data from exported fleecing image(exported by internal nbd)
ID: 1909636

blockdev_inc_backup_pull_mode_vm_reboot: vm reboot test for pull

---

qemu/tests/blockdev_inc_backup_merge_bitmaps_with_diff_granularity.py
qemu/tests/cfg/blockdev_inc_backup_merge_bitmaps_with_diff_granularity.cfg

Merge two bitmaps with different granularities
ID: 1909076

blockdev_inc_backup_merge_bitmaps_with_diff_granularity: Add bitmaps merge test

---

qemu/tests/blockdev_inc_backup_bitmap_vm_crash_reboot.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_vm_crash_reboot.cfg

Add a non-persistent bitmap, then trigger vm crash,
check bitmap still existed after vm reboot
ID: 1910337

blockdev_inc_backup_bitmap_vm_crash_reboot: bitmap exists after crash

---

qemu/tests/blockdev_inc_backup_bitmap_with_hotplug.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_with_hotplug.cfg

Add bitmap to a hot-plugged image, then unplug the image,
bitmap should be gone.
ID: 1911275

blockdev_inc_backup_bitmap_with_hotplug: bitmap with hotplug

---

provider/cpu_utils.py
qemu/tests/cpu_device_hotplug_during_boot.py
qemu/tests/cpu_device_hotplug_maximum.py
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_device_hotpluggable_with_numa.py
qemu/tests/cpu_device_hotpluggable_with_stress.py
qemu/tests/invalid_cpu_device_hotplug.py

When smp and maxcpus are defined at the same time, use smp/vcpu_maxcpus
as the check number to detect that the number of vcpu does not meet the
actual situation.
ID: 1904310

Modify the logic of checking vcpu before and after plug/unplug [BATCH2]

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add command 'guest-get-disk' for checking disk_name,
disk_dependencies, disk_partition, disk_alias(lvm only).
ID: 1906654

qemu-guest-agent: Add command 'guest-get-disk' for checking disks info

---

qemu/tests/cfg/block_discard_hotplug.cfg
qemu/tests/cfg/virtio_blk_with_discard_write_zeroes.cfg

Due to fstrim and blkdiscard command is not support
in RHEL.7 for the discard disk.
ID:1915189,1875212

Disable rhel 7 in discard test

---

generic/tests/nic_promisc.py
generic/tests/nicdriver_unload.py
generic/tests/ntttcp.py
multi_host_migration/tests/migration_multi_host_with_file_transfer.py
qemu/tests/block_copy.py
qemu/tests/live_snapshot_runtime.py
qemu/tests/migration_with_file_transfer.py
qemu/tests/migration_with_reboot.py
qemu/tests/nic_bonding.py
qemu/tests/qemu_guest_agent_snapshot.py
qemu/tests/sr_iov_irqbalance.py
qemu/tests/virtio_console.py
qemu/tests/win_nics_teaming.py

threading.Thread.isAlive() has been removed in python 3.9,
and is_alive() has been supported since python 2.6
id: 1916085

Replace 'isAlive' with 'is_alive' for threading.Thread

---

qemu/tests/cfg/vsock.cfg

Fix lspci output change issue for vsock device when machine_type=q35.
ID: 1916620

Fix lspci output change issue for vsock device

---

provider/win_wora.py
qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
qemu/tests/cfg/cpu_device_hotpluggable.cfg
qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
qemu/tests/cpu_device_hotplug_maximum.py
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_device_hotpluggable_with_numa.py
qemu/tests/cpu_device_hotpluggable_with_stress.py
qemu/tests/invalid_cpu_device_hotplug.py

For win2016 guest, there is a exist microsoft issue:
https://support.huawei.com/enterprise/zh/doc/EDOC1100034211/5ba99a60
In order to workaround the known issue, add install driver of
"HID Button over Interrupt Driver" steps before cpu hotplugged.
id: 1822451

cpu_device_hotpluggable: Add a workaround for win2016 guest

---

qemu/tests/cfg/qemu_guest_agent.cfg

qemu_guest_agent: Use 'mkdir -p' to avoid file exists issue

---

qemu/tests/cfg/x86_cpu_model.cfg

ID: 1912198
'Icelake-Client' CPU Models are deprecated since 5.2.0

x86_cpu_model: delete Icelake-Client since qemu 5.2.0

---

qemu/tests/cfg/commit_with_backing.cfg
qemu/tests/cfg/rebase_second_snapshot_to_base.cfg

For some os, '/tmp' is wiped whenever the system reboots where as
'/var/tmp' gets preserved across reboot
id: 1914129

commit_with_backing: save file under '/var/tmp' instead of '/tmp'

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent_snapshot.py

Cause we use "blockdev-snapshot" rather than "blockdev-snapshot-sync" from rhel8
Switch cmd command of creating snapshot to the new method
ID:1891927,1806380 

Change the way of create snapshot to new method, also add cfg info

---

qemu/tests/cfg/multi_vms_with_stress.cfg

multi_vms_with_stress: Fix the issue of VM can not start
Since on some machines with poor performance, the CPU resources
are not allocated enough, which causes the VM to fail to start.
Therefore, set the 'smp' value to 1
ID:1869517,1874383

Fix the issue of VM can not start

---

qemu/tests/cfg/qemu_output.cfg
qemu/tests/qemu_output.py

Verify qemu has no error outputs at different stages in the guest life
cycle.
ID: 1916546

qemu_output: New case to check qemu outputs at different stages

---

qemu/tests/cfg/qemu_guest_agent.cfg

qemu_guest_agent: Hotfix case "guest-get-disks"
ID: 1919091

qemu_guest_agent: Hotfix case "guest-get-disks"

---

qemu/tests/cfg/throttle_operation_test.cfg

It need to apply enough pcie_extra_root_port for the
hotplug operation under q35.
ID:1920799

throttle_operation_test:fix no free root port issue

---

qemu/tests/cfg/ppc_nested_compat.cfg
qemu/tests/ppc_nested_compat.py

Launch a qemu instance with power8 compat mode and cap-nested-hv=on,
qemu will terminate and prompt that it does not support.
ID: 1918598

ppc_nested_compat: negative test that launch a compat mode nested guest

---

provider/message_queuing.py
qemu/tests/cfg/nested_interactive_agent.cfg
qemu/tests/nested_interactive_agent.py

After launching a guest, send the specified message to notify the remote
nc server and then waiting for the nc server to enter the specific message
to continue the test.
ID: 1912622

New case of controlling life cycle of guest via the chat of MQ server

---

provider/ansible.py
qemu/tests/ansible_test.py
qemu/tests/ansible_with_responsive_migration.py
qemu/tests/cfg/ansible_test.cfg

Add a new scenario. After ansible-playbook runs, the test case will
launch an nc server and capture a specific message (regardless of
whether the message is written to the server through the playbook or
other forms). When the message is received, migrate guests and wait for
the execution of ansible-playbook to complete.
ID: 1912622
Depends on: #2591

ansible_test: Support receiving message to migrate guests

---

generic/tests/shutdown.py
generic/tests/whql_hck_client_install.py
provider/cpu_utils.py
qemu/tests/balloon_check.py
qemu/tests/block_hotplug_in_pause.py
qemu/tests/block_resize.py
qemu/tests/dump_guest_memory.py
qemu/tests/fio_perf.py
qemu/tests/mlock_basic.py
qemu/tests/qemu_guest_agent.py
qemu/tests/qemu_guest_agent_hotplug.py
qemu/tests/qemu_img_map_unaligned_image.py
qemu/tests/remote_block_resize.py
qemu/tests/usb_device_check_negative.py
qemu/tests/usb_redir.py
qemu/tests/vioser_in_use.py
qemu/tests/win_sigverif.py
requirements-travis.txt

Inspektor has the ability to use autopep8 transparently (if installed),
add autopep8 in requirements-travis.txt to enable this ability.
Refer to: avocado-framework/avocado#4394
ID: 1921754

Enable autopep8 style check in travis CI

---

qemu/tests/cfg/boot_nic_with_iommu.cfg

1. In order to avoid the impact of enabling iommu on other devices, only enable iommu capability for the virtual network device.
2. Add the machine type extra params for aarch64.
ID: 1925875

boot_nic_with_iommu: Only enable iommu capability on network device

---

qemu/tests/blockdev_commit_non_existed_base.py
qemu/tests/cfg/blockdev_commit_non_existed_base.cfg

blockdev_commit_non_existed_base: Block commit with base is an non-existed snapshot
ID:1923961

Block commit with base is an non-existed snapshot

---

qemu/tests/blockdev_inc_backup_xpt_allocation_depth.py
qemu/tests/cfg/blockdev_inc_backup_xpt_allocation_depth.cfg

Export allocation depth with qemu-nbd and block-export-add
ID: 1922947, 1922948

blockdev_inc_backup_xpt_allocation_depth: Allocation export test

---

qemu/tests/cfg/nvdimm.cfg

1. The reflink and dax options are mutually exclusive which causes the mount to fail. Force "reflink=0" when formatting XFS system.
2. Move aarch64 out of the unsupported list and remove some duplicate versions on non-x86 platforms on L12.
ID: 1931442

nvdimm: Enable "reflink=0 with non-RHEL.7 guests

---

qemu/tests/boot_order_check.py

Some device representation has no 'desc' element.
Change to use get() to obtain it.
ID: 1931792

boot_order_check: use get() to obtain 'desc' element.

---

qemu/tests/blockdev_commit_non_existed_node.py
qemu/tests/cfg/blockdev_commit_non_existed_node.cfg

blockdev_commit_non_existed_node: Block commit test
Block commit with base is an non-existed snapshot in snapshot
chain. When do live commit, specify an non-existed snapshot
in snapshot chain as top, qemu-kvm should prompt error.
ID:1931265

Block commit with top is an non-existed snapshot

---

qemu/tests/cfg/dump_guest_memory.cfg

Adjust the value of dump_file_timeout to wait dump file
generated completed.
ID:1925951

dump_guest_memory: adjust the value of dump_file_timeout.

---

provider/backup_utils.py
provider/blockdev_backup_base.py
provider/blockdev_base.py
provider/blockdev_snapshot_base.py
provider/blockdev_stream_base.py
qemu/tests/blockdev_inc_backup_test.py
qemu/tests/blockdev_mirror_multiple_blocks.py
qemu/tests/blockdev_snapshot_multi_disks.py
qemu/tests/blockdev_stream_multiple_blocks.py
qemu/tests/blockdev_stream_subchain.py
qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg
qemu/tests/cfg/blockdev_stream_multiple_blocks.cfg

When starting vm with target images(such as:
mirror/backup/snapshot images) as its data images on RHEL9,
device node name may change, e.g.
data1 -> /dev/sdb in VM (start VM with data1)
data1 -> mirror1 (do block-mirror)
mirror1 -> /dev/sda in VM (restart VM with mirror1)
ID: 1918878

Mount correct device when restarting vm with target images

---

qemu/tests/win_sigverif.py

Send 'meta_l-d' to ensure system stay on desktop and
wait 60s to make all popups pop up to ensure autoit
run normally.
ID:1797847

win_sigverif: Fix 'sigverif logs are not created' error

---

generic/tests/cfg/timerclock.cfg
qemu/tests/cfg/timedrift_adjust_time.cfg
qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/cfg/timerdevice_tsc_enable.cfg

aarch64 only supports `arch_sys_counter` clock and some timer device test cases have platform limitations, drop them on aarch64.
ID: 1919843, 1932762

Drop some timer device test cases on aarch64

---

qemu/tests/cfg/dump_guest_memory.cfg

Fix no vmcoreinfo device on aarch64
ID: 1933921

dump_guest_memory: Fix no vmcoreinfo device on aarch64

---

provider/cpu_utils.py
qemu/tests/cpu_device_hotplug_maximum.py
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_topology_test.py

The function name "check_guest_cpu_topology" is easy to confuse, rename
it to "is_guest_cpu_topology_matched" and correct all calls to it.
ID: 1934429

cpu_utils: rename check_guest_cpu_topology to make it clear

---

generic/tests/cfg/multi_queues_test.cfg
qemu/tests/cfg/boot_with_different_vectors.cfg
qemu/tests/cfg/bridge_vlan.cfg
qemu/tests/cfg/flow_caches_stress_test.cfg
qemu/tests/cfg/mq_change_qnum.cfg
qemu/tests/cfg/netkvm_in_use.cfg
qemu/tests/cfg/netperf_stress_test.cfg
qemu/tests/cfg/nic_opt.cfg
qemu/tests/cfg/ovs_qos.cfg
qemu/tests/cfg/virtual_nic.cfg
qemu/tests/flow_caches_stress_test.py

Change the netperf test version and source patch

---

qemu/tests/blockdev_commit_specify_node.py
qemu/tests/cfg/blockdev_commit_specify_node.cfg

1.Block commit with based and top is the same.
2.Block commit with parent as top and child as base.
ID:1934957,1934955

blockdev_commit_specify_node: block commit with specify node

---

provider/nbd_image_export.py
qemu/tests/blockdev_mirror_remote_server_down.py
qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg

Stop nfs service while mirroring, then start nfs service to resume
mirroring
ID: 1934985

blockdev_mirror_remote_server_down: Stop remote server while mirroring

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

operation includes guest-ssh-add-authorized-keys, 
*-remove-*, *-get-*, and reset ssh keys" for host can 
login guest via ssh without passwd.
ID: 1906644

qemu-guest-agent: Add new case for operate ssh-pub-keys into guest.

---

qemu/tests/virtio_fs_multi_vms.py
qemu/tests/virtio_fs_readonly.py
qemu/tests/virtio_fs_share_data.py

The mount virtiofs target failed due to a new product issue, so a special test
point was added. When the mount fails, subsequent tests will not be performed.
ID: 1937607

virtio-fs: Add a checkpoint of the mount virtiofs target

---

qemu/tests/blockdev_inc_backup_inconsistent_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_inconsistent_bitmap.cfg

Clearing/Enabling/Disabling an inconsistent bitmap should fail,
removing an inconsistent bitmap should succeed.
ID: 1937172, 1937281, 1937283

blockdev_inc_backup_inconsistent_bitmap: Inconsistent bitmap test

---

qemu/tests/blockdev_inc_backup_without_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_without_bitmap.cfg

Do incremental backup without a bitmap in a transaction
ID: 1936354

blockdev_inc_backup_without_bitmap: Incbk without a bitmap

---

qemu/tests/blockdev_inc_backup_bitmap_not_exist.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_not_exist.cfg

Do incremental backup with a non-existed bitmap
ID: 1936303

blockdev_inc_backup_bitmap_not_exist: Incbk with non-existed bitmap

---

provider/block_dirty_bitmap.py
qemu/tests/blockdev_inc_backup_bitmap_size.py
qemu/tests/cfg/blockdev_inc_backup_bitmap_size.cfg

Add bitmap with the default granularity
Add bitmap with different granularities
Estimate space utilization for bitmaps
ID: 1939307, 1939308

blockdev_inc_backup_bitmap_size: Estimate bitmap size

---

qemu/tests/blockdev_inc_backup_target_not_exist.py
qemu/tests/cfg/blockdev_inc_backup_target_not_exist.cfg

Do incremental backup with a non-existed target node
ID: 1936317

blockdev_inc_backup_target_not_exist: Incbk with non-existed target

---

qemu/tests/cfg/qemu_img_negative.cfg
qemu/tests/snapshot_negative_test.py

1. add case "qemu_img_negative.snapshot.with_incorrect_format"
2. add case "qemu_img_negative.snapshot.with_non_existing_backing_file"
3. add case "qemu_img_negative.snapshot.with_empty_string_for_backing_file"
ID: 1941355

qemu.test: qemu_img_negative.snapshot

---

qemu/tests/cfg/virtio_fs_share_data.cfg

In the latest version of rhel, tmp is a tmpfs and
cannot be used as a mount dir. So modify it to the /mnt dir.
ID: 1940744

virtio-fs: fix nfs mount failed

---

qemu/tests/blockdev_inc_backup_nospace_with_bitmap_mode.py
qemu/tests/cfg/blockdev_inc_backup_nospace_with_bitmap_mode.cfg

Do incremental backup to an image without enough space,
bitmap-mode=always, count of bitmap should be less then before
bitmap-mode=on-success, count of bitmap should be the same
ID: 1940019, 1940020

blockdev_inc_backup_nospace_with_bitmap_mode: Bimap mode test

---

requirements-travis.txt

The latest pylint version(2.7.3) is mismatch to inspekt-1.5.2, the CI
check will fail with "got an error: 'E1002'".
ID: 1944502

HOTFIX: Fix the latest pylint version causing the CI check to fail

---

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
qemu/tests/qemu_guest_agent_hotplug.py

Increase the interval between operations "device_del"
and "chardev-remove", original interval is too short to
execute "chardev-remove" successfully.
ID: 1899363

qemu_guest_agent_hotplug: Increase interval between operations

---

qemu/tests/cfg/ioeventfd.cfg
qemu/tests/ioeventfd.py

Virtual_block: modify the way of getting dev_id so that it could adapt
on s390x
ID:1940320

Add adaption for ioeventfd on s390x

---

qemu/tests/blockdev_stream_remote_server_down.py
qemu/tests/cfg/blockdev_stream_remote_server_down.cfg

Remote server down when doing block stream, job paused;
Resume remote storage, job should complete.
ID: 1945100

blockdev_stream_remote_server_down: Remote server down when streaming

---

qemu/tests/qemu_guest_agent.py

qemu-guest-agent.py: There is not only one user under '/home' dir
There is an exist user(or a simple file) under dir' home' on RHEL9
so the code logic should be changed as 'if xxx not in /home/*'
instead of original 'if xxx != /home/*'.
ID: 1943792 

qemu-guest-agent: There is not only one user under '/home' dir on rhel9

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent: Add situation for windows to get disks info
1. qemu_guest_agent.py: Add conditions to filter windows.
2. qemu_guest_agent.cfg: Add cmd to get disks info in windows.
ID: 1937188

qemu_guest_agent: Add situation for windows to get disks info.

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add steps to check and install vioser during setup phase for qga
on windows guest.
1. qemu_guest_agent.py: add method to check/install vioser
2. qemu_guest_agent.cfg: add some params.
ID: 1737332

qemu_guest_agent: check and install vioser during Setup for windows

---

generic/tests/cfg/kdump.cfg
qemu/tests/kdump_with_stress.py

Since stress's package download link is unavailable, so rewrited
the function of install_stress_app() to install stress app in VM.
ID:1931484

kdump with stress: fix stress package download failed issue.

---

qemu/tests/cfg/chardev_tls_encryption.cfg
qemu/tests/usb_redir.py

From qemu6.0, short-form boolean options are deprecated, options
such as "server" or "nowait", correct them to "server=on" and
"wait=off"
id: 1945036

chardev: correct short-form usage for some options

---

qemu/deps/performance/start_testpmd.py
qemu/tests/cfg/virtio_net_dpdk.cfg
qemu/tests/virtio_net_dpdk.py

1. "/usr/bin/testpmd" is replaced with "/usr/bin/dpdk-testpmd"
2. -w is deprecated, use -a instead
3. "dpdk-devbind" is replaced with "dpdk-devbind.py"
4. update virtio_net_dpdk.cfg since hardware was changed
id:1941440

virtio_net_dpdk: update case for new rhel product

---

qemu/tests/cfg/qemu_img_convert_with_target_is_zero.cfg
qemu/tests/qemu_img_convert_with_target_is_zero.py

the target image can't be luks format, it causes the image corruption
ID: 1949373

correct the usage of parameter --target-is-zero for luks image

---

provider/block_dirty_bitmap.py
qemu/tests/blockdev_inc_backup_add_disabled_bitmap.py
qemu/tests/blockdev_inc_backup_bitmap_vm_crash_reboot.py
qemu/tests/blockdev_inc_backup_disable_bitmap.py
qemu/tests/blockdev_inc_backup_disabled_persistent_bitmap.py
qemu/tests/blockdev_inc_backup_inconsistent_bitmap.py
qemu/tests/blockdev_inc_backup_rm_persistent_bitmap.py
qemu/tests/blockdev_inc_backup_with_migration.py

On qemu6.0, 'status' field under qmp 'query-block' command output is
deprecated, so use the 'recording' field instead to get the bitmap
status.
ID: 1944940

dirty-bitmaps: Replace to use the 'recording' field to get bitmap status

---

qemu/tests/cfg/block_during_io.cfg

No enough system space after installation for win10 to
run iozone on system disk with '-g 10G' option.
ID: 1925926

block_during_io.cfg: fix iozone error issue for win10

---

qemu/tests/qemu_guest_agent.py

Update error message "Command guest-fsfreeze-freeze has been disabled: "
"the agent is in frozen state" instead of original "The command "
"guest-fsfreeze-freeze has been disabled for this instance" to tell user
more clearly.
ID: 1949784

qemu_guest_agent.py: Improve error messages for freezing a frozen fs.

---

qemu/tests/plug_cdrom.py

Add repeat steps to get new added CD-ROM DeviceID.
Sometimes, new added cdrom cannot shown in windows os  immediately .
ID: 1841491

plug_cdrom: fix issue "No available CD-ROM devices: No Instance(s) Available"

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add new case to check whether resource leak caused via qga-cmds
1. Add method 'gagent_check_resource_leak' in qemu_guest_agent.py.
2. Add some params in qemu_guest_agent.cfg
ID: 1933545

qemu_guest_agent: Add new case to check whether resource leak caused via qga-cmds

---

qemu/tests/cfg/block_hotplug_check.cfg
qemu/tests/cfg/block_resize.cfg
qemu/tests/cfg/device_option_check.cfg
qemu/tests/cfg/eject_media.cfg
qemu/tests/cfg/multi_disk.cfg
qemu/tests/cfg/plug_cdrom.cfg

The files in /tmp dir will be removed after reboot on rhel9
but the files still useful after reboot so change the path
to /var/tmp to let the files preserved.
ID: 1925456

fix 'Could not open '/tmp/*' issue on rhel9

---

qemu/tests/cfg/netkvm_protocol_binding.cfg
qemu/tests/netkvm_protocol_binding.py

Binding of netkvm protocol to netkvm adapter and enabled manually without VF.
id: 1927119

SRIOV: add new case for netkvm protocal binding on windows

---

qemu/tests/cfg/migration_with_block.cfg
qemu/tests/migration_with_block.py

Update the device_name of new changed cdrom,
it will change to a random string '#block*' after cdrom changed.
Adjust the code to get the device_name first,
then to check_items one by one in qmp info block.
ID: 1806418

migration_with_block: Fix KeyError:'drive_orig' issue

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Before this commit
guest crash
```
04:23:06 DEBUG| Sending command: ./check -virtiofs -E blacklist
05:00:35 INFO | [qemu output] error: kvm run failed Bad address
05:00:35 INFO | [qemu output]  PC=ffff5eedb65cb5b0 X00=ffffa072a22c0000 X01=0000ffff909a0040
05:00:35 INFO | [qemu output] X02=000000000000ff80 X03=0000ffff909a0000 X04=0000000000000000
05:00:35 INFO | [qemu output] X05=ffffa072a22d0000 X06=ffffa072a22c0000 X07=cdcdcdcdcdcdcdcd
05:00:35 INFO | [qemu output] X08=cdcdcdcdcdcdcdcd X09=cdcdcdcdcdcdcdcd X10=cdcdcdcdcdcdcdcd
05:00:35 INFO | [qemu output] X11=cdcdcdcdcdcdcdcd X12=cdcdcdcdcdcdcdcd X13=cdcdcdcdcdcdcdcd
05:00:35 INFO | [qemu output] X14=cdcdcdcdcdcdcdcd X15=00007889c9852732 X16=ffff5eedb60cae20
05:00:35 INFO | [qemu output] X17=0000ffff91a81c60 X18=0000000000000001 …
```

Fix virtiofs xfstests

---

requirements-travis.txt

Update pylint to the fixed version 2.8.0, seems the 2.7.2 has an issue
that could not generate the "checkall" subcommand.
ID: 1953289

travis-ci: Update pylint version

---

qemu/tests/cfg/boot_from_device.cfg
qemu/tests/cfg/seabios_order_once.cfg

tmpfs filesystem does not support O_DIRECT.
ID: 1953265

seabios: use directory /var/tmp instead of /tmp

---

qemu/tests/qemu_guest_agent.py

qemu_guest_agent.py: add filer condition to filter out the windows
system does not execute command "restorecon-Rv".
ID: 1926218

qemu_guest_agent: fix "restorecon-Rv" wasn't recognized in windows

---

qemu/tests/cfg/rh_kernel_update.cfg

rh_kernel_update: verify virtio only for RHEL.6 and RHEL.7 guest

---

qemu/tests/blockdev_inc_backup_test.py
qemu/tests/cfg/blockdev_inc_backup_test.cfg

'Source and target image have different sizes' will output no
matter completion-mode is individual or grouped
ID: 1954371

blockdev_inc_backup_test: Error msg changed when size is different

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qemu_guest_agent.cfg: change 'tmp' to '/home' because '/tmp' is
tmpfs that not support ioctl(FSFREEZE)
ID: 1928609

qemu_guest_agent: Change '/tmp' for checking fsfreeze on rhel9

---

qemu/tests/cfg/balloon_check.cfg

balloon_check: restrict iommu testing only for Intel platform

---

qemu/tests/cfg/ioeventfd.cfg
qemu/tests/ioeventfd.py

virtual_block:add virtio_serial_ccw0 to adapt s390x
ID:1951608

Add supported for ioeventfd.virtio_serial for s390x

---

qemu/tests/qemu_guest_agent.py

Abolish code logic through system variant to determine whether
to query 'os_variant' value, but is directly determined whether
there is a target value.
ID: 1946410

qemu_guest_agent: Directly determine whether there is 'variant'

---

qemu/tests/cfg/driver_load.cfg

Virtual_block: add adaption for driver_load.with_block and driver_load
.with_vioscsi on s390x
ID: 1953997

Add adaption for driver_load on s390x

---

generic/tests/cfg/kdump.cfg
generic/tests/kdump.py

This issue root case is missing variable and can not
execute 'kdumpctl propagate' successfully.
ID:1910846

kdump: fix the issue of kdump ssh case

---

qemu/tests/cfg/chardev_tls_encryption.cfg

fix 'isa-serial' isn't a valid device on aarch64
id:1958727

chardev_tls_encryption: fix 'isa' isn't a valid device on aarch64

---

qemu/tests/cfg/qemu_disk_img.cfg

disk_format: add qemu_disk_img.info.change_block_interface for s390x
ID: 1959818

Add support for qemu_disk_img on s390x

---

qemu/tests/cfg/multi_nics_hotplug.cfg

virtual-network: add pci_model "virtio-net-ccw" for s390x
ID:1942866

 Add virtio-net-ccw support for s390x

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

xfstests-dev is an upstream tool, so it's updated frequently.
After this update, you will use the 'git clone' method to
get the latest code every time.
id: 1960086

virtio_fs_share_data:update the acquisition way of xfstest tool

---

qemu/tests/cfg/smbios.cfg

smbios should only be tested on x86, because -smbios does not support on
non-x86 platforms IIUC.
ID: 1962242

smbios: only test smbios on x86 platforms

---

qemu/tests/queues_number_test.py

Collect all command outputs by the serial session will cause the command
got the incorrect output when 2 commands return at the same time.
ID: 1963004

queues_number_test: Add a ssh session to handle execution of commands

---

generic/tests/cfg/file_transfer.cfg

'disable_pci_msi = yes' will change the kernel command line, so we
should apply a temporary image to avoid dirty change of the kernel
command line.
ID: 1964007

file_transfer: clone_master should be used to avoid changing kernel CML

---

qemu/tests/virtio_fs_multi_vms.py
qemu/tests/virtio_fs_set_capability.py
qemu/tests/virtio_fs_share_data.py

Should start virtiofs service at first register and fail test if not
get virtio-fs mounted volume letter.
ID: 1958446

virtio-fs: start virtiofs service at first register for windows vm

---

qemu/tests/cfg/qemu_img_negative.cfg

1. It should be failed to create the image.
2. The error information should be corret.
e.g. Data from secret sec0 is not valid UTF-8
ID: 1966713

Add a new case, create luks-inside-qcow2 image with non utf8 secret

---

qemu/tests/boot_with_different_vectors.py
qemu/tests/cfg/boot_with_different_vectors.cfg

aarch64 uses GICv2/3 interrupt controller, adds support in the
boot_with_different_vectors.py
ID: 1964001

boot_with_different_vectors: Support GIC interrupt of aarch64

---

qemu/tests/migration_with_block.py

Virtual_block: add timeout time from 30s to 60s, add 30s wait time to
wait qmp return 'status'
ID:1957823

Modify timeout time to support s390x

---

qemu/tests/boot_without_vectors.py

1.'disable_pci_msi = yes' will change the kernel command line,
but falied to clone image, so change the code to avoid dirty
change of the kernel command line.
ID:1966855

boot_without_vectors: Failed to clone image

---

qemu/tests/cfg/uefi_pkg.cfg
qemu/tests/uefi_pkg.py

1. if it supports sev-es, the number is 3
2. add support for rhel9
ID: 1960484

uefi_pkg: update the number of descriptor meta files

---

qemu/tests/bridge_mirror.py
qemu/tests/memory_leak_after_nichotplug.py

1.From the session.cmd mode change to serial_session.cmd_out_safe
mode to avoid dirty output due to other serial information.
2.From console session change to ssh session
ID:1966864

Change the session mode to avoid dirty output

---

qemu/tests/blockdev_inc_backup_migrate_without_bitmap.py

In order to be compatible with both qemu6.0 and former qemu
versions, change to use 'recording' field in qmp 'query-block'
ouput to get the bitmap status.
ID: 1964824

blockdev_inc_backup_migrate_without_bitmap: Change to use 'recording' field to check the bitmap status

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

Using service method to start virtiofs exd for driver
load stress test case and driver update test case.
ID: 1958471

virtio-fs: use virtiofs service method for driver test

---

qemu/tests/cfg/nmi_bsod_catch.cfg

Win2022 guest min memory has to be 4096.
ID: 1968512

nmi_bsod_catch.cfg: Win2022 guest min memory has to be 4096

---

qemu/tests/blockdev_commit_non_existed_node.py
qemu/tests/blockdev_inc_backup_target_not_exist.py
qemu/tests/blockdev_stream_none_existed_overlay.py
qemu/tests/cfg/blockdev_commit_non_existed_node.cfg
qemu/tests/cfg/blockdev_inc_backup_target_not_exist.cfg
qemu/tests/cfg/blockdev_stream_none_existed_overlay.cfg

Since qemu6.0, the node name related error message changed to
use 'node-name' instead of the original 'node_name' and with ''
surrounded, so update the related cases to make them work on
both qemu6.0 and former qemu versions.
ID: 1967875

blockdev_*_no*_exist*: Update error message to adapt qemu6.0 change

---

qemu/tests/cfg/hv_check_cpu_utilization.cfg

The cpu usage of thread X should less than 5% in manual and
less than 10% in auto is reasonable when guest is idle. For
there may start some scripts in the background on host to
occupy some cpu.
ID: 1867849

hv_check_cpu_utilization: The cpu usage < 10% is reasonable in auto

---

qemu/tests/cfg/virtio_fs_set_capability.cfg

Cmd of 'capsh print' result is changed on rhel8 later host.
Change code to support rhel8 and later host.
ID: 1970220

virtio-fs: capsh print support on rhel8 later host

---

qemu/tests/cfg/device_bit_check.cfg
qemu/tests/device_bit_check.py

Virtual_block: Add id_pattern works on s390x and modify the checking
command to adapt the test on s390x
ID:1969638

Modify pattern for device bit check on s390x

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 1965165
Cover the test scenario to test default cpu model,
Now the default cpu model is 'qemu64'

x86_cpu_flags:test default cpu model

---

qemu/tests/cfg/virtio_fs_share_data.cfg

Add vcpu_maxcpus to qemu command line in case test failed with big smp but small vcpu
on host.
ID: 1973577

virtio-fs: add vcpu_maxcpus parametor

---

qemu/tests/cfg/timedrift_check_clock_offset.cfg
qemu/tests/timedrift_check_when_crash.py
qemu/tests/timedrift_check_when_hotplug_vcpu.py

timedrift_check_clock_offset: enable w32time before starting it

---

qemu/tests/cfg/numa_memdev_options.cfg
qemu/tests/numa_memdev_options.py

Also add compact memory cmd to pre_command to avoid no enough
hugepage error.
ID: 1975051

numa_memdev_options: Add filter to fix CmdError

---

qemu/tests/cfg/boot_with_disable_ept.cfg

AMD host also use "Y/N" to enable/disable npt from RHEL-8.5
ID: 1977204

boot_with_disable_ept: update the status of npt parameter

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Command 'rm -rf ${mountpoint_def}/foo' not recognized as internal
or external command in Windows, so change this operation to
windows cmd "def".
ID: 1970167

qemu_guest_agent.py: Change operation 'rm' to 'def' on windows

---

qemu/tests/cfg/multi_disk.cfg

Change the cfg file to let it support s390x.
ID: 1973923

multi_disk.all_drive_format_types: Support s390x

---

generic/tests/cfg/kdump.cfg
generic/tests/kdump.py

1.Fix the problems of parameter 'auth_key_path' is missing
2.Fix the problem that the "chkconfig" command cannot be found on rhel9
3.Fix the problem of vmocre file not found
ID:1972457,1975606

kdump: fix problems related to kdump cases

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

The output of checking disks info is json format, and it is
is pretty print with new product, cause the old logic can't
work, so change the logic to make it work with both.
id:1975052

qemu_guest_agent: change the logic to obtain disks info

---

qemu/tests/cfg/hv_cpu_hotplug.cfg

We should set a workaround 'install 'HID Button over Interrupt Driver'
in win2016 guest when test cpu hotplug for a windows issue.
ID: 1975638

hv_cpu_hotplug: Set a workaround for win2016 guest

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_mapsync.py

Due to smaps file structure change, the output of cmd 'grep -A21'
no longer contains the expected 'VmFlags' line. Fix it by adding
more matching lines.
ID: 1978092

nvdimm_mapsync: Fix IndexError

---

qemu/tests/cfg/qmp_command.cfg
qemu/tests/qmp_command.py

'change vnc target' command removed in qemu-kvm-6.0,
so remove it
id: 1973535

fix 'query-vnc' command

---

qemu/tests/balloon_check.py

The original value is 0,qmp will reture error with 0.
ID: 1977566

balloon_check: modify illegal_value to 1 if do evict test

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add new case "guest-info" to check qemu version/build of
linux/windows guests.
ID: 1967386

qemu_guest_agent.py: Add new case to check qemu version/build

---

qemu/tests/cfg/insert_media.cfg

The /tmp folder is tmpfs in RHEL9 result in vm creation failed.
So change the iso folder from /tmp to /var/tmp.
ID:1968389

Change tmp folder to /var/tmp for case insert_media

---

qemu/tests/cfg/commit_snapshot_to_backing_image.cfg
qemu/tests/cfg/image_commit_bypass_host_cache.cfg
qemu/tests/cfg/image_locking_read_test.cfg
qemu/tests/cfg/image_rebase_bypass_host_cache.cfg
qemu/tests/cfg/qemu_img_convert_with_backing_file.cfg
qemu/tests/cfg/qemu_img_convert_with_rate_limit.cfg
qemu/tests/cfg/qemu_img_convert_with_target_is_zero.cfg
qemu/tests/cfg/rebase_onto_no_backing_file.cfg
qemu/tests/cfg/rebase_onto_qcow2.cfg

for some os, '/tmp' is wiped whenever the system reboots where as
'/var/tmp' gets preserved across reboot
ID: 1982488

save file under '/var/tmp' instead of '/tmp'

---

qemu/tests/boot_with_disable_ept.py
qemu/tests/cfg/boot_with_disable_ept.cfg

windows guest need more time to login with ept disabled,
so extend timeout value.
ID: 1977181

boot_with_disable_ept: extend timeout value with ept disabled

---

qemu/tests/cfg/tpm_verify_device.cfg

TPM passthrough is removed on rhel 9.
ID: 1983507

Remove tpm passthrough test case for rhel 9

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

1. Add auto send key action of ovmf windows installation
2. Reduce disks number of multi disks windows installation
ID:1874693

Fix virtio_scsi_cdrom windows installation issue

---

qemu/tests/blockdev_inc_backup_without_bitmapmode.py
qemu/tests/cfg/blockdev_inc_backup_without_bitmapmode.cfg

sync:bitmap, but no bitmap-mode
id:1983605

blockdev_inc_backup_without_bitmapmode:Do incremental live backup with     sync:bitmap, but no bitmap-mode

---

qemu/tests/blockdev_full_backup_with_bitmap.py

Remove re which is never used.
Signed-off-by: zhencliu <zhencliu@redhat.com>

blockdev_full_backup_with_bitmap: fix ci error

---

qemu/deps/trigger_panic_drive/Makefile
qemu/deps/trigger_panic_drive/force_panic.c
qemu/tests/cfg/verify_panic_status_with_pvpanic.cfg
qemu/tests/verify_panic_status_with_pvpanic.py

qemu_vm: Add pvpanic device support for aarch64
Update pvpanic device for aarch64
id: 1979465

Update pvpanic device for aarch64

---

qemu/tests/cfg/virtio_fs_share_data.cfg

1.distinguish fs_binary_extra_options's and '-o cache'
2.delete with_no_writeback variant as the default is no_writeback in product.
ID: 1983004

virtio-fs: correct fixe fs_binary_extra_options's setting

---

qemu/tests/blockdev_inc_backup_sync_bitmap_nobitmap.py
qemu/tests/cfg/blockdev_inc_backup_sync_bitmap_nobitmap.cfg

backup with sync:bitmap, but no bitmap
id:1983623

blockdev_inc_backup_sync_bitmap_nobitmap:Do incremental live     backup with sync:bitmap, but no bitmap

---

qemu/tests/cfg/blockdev_inc_backup_always.cfg

Do incremental live backup with bitmap-mode:always
id:1983911

blockdev_inc_backup_always:Do incremental live backup with bitmap-mode:always

---

qemu/tests/blockdev_inc_backup_never_always.py
qemu/tests/cfg/blockdev_inc_backup_never.cfg

Do incremental live backup with sync:incremental and
bitmap-mode:never
id:1983902

blockdev_inc_backup_never: Do incremental live backup with bitmap-mode:never

---

qemu/tests/blockdev_inc_backup_merge_to_nonexist_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_merge_to_nonexist_bitmap.cfg

Merge bitmaps to a non-existed target
id:1984294

blockdev_inc_backup_merge_to_nonexist_bitmap:Merge bitmaps to a non-existed target

---

qemu/tests/blockdev_inc_backup_xpt_nonexist_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_xpt_nonexist_bitmap.cfg

Expose non-existed bitmap via qemu-nbd
id:1985277

blockdev_inc_backup_xpt_nonexist_bitmap:Expose non-existed bitmap via qemu-nbd

---

qemu/tests/blockdev_inc_backup_xpt_incon_bitmap.py
qemu/tests/cfg/blockdev_inc_backup_xpt_incon_bitmap.cfg

Expose an inconsistent bitmap via qemu-nbd
id:1984815

blockdev_inc_backup_xpt_incon_bitmap: Expose an inconsistent bitmap via qemu-nbd

---

qemu/tests/bridge_qinq.py
qemu/tests/cfg/bridge_qinq.cfg

1. Failed to set netmask on s390x using socket, so replace with "ip
link" command.
2. Only stop NetworkManager on RHEL7 since it will conflict with
network.service.
3. Use "ip" command to configure network instead of "ifconfig"
4. Delete the private bridge in the final stage regardless of whether
the test passes or not.
ID: 1985163

bridge_qinq: Support s390x and fix some problems

---

qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/nic_hotplug.py

s390x does not use pci.0 bus, it uses virtual-css as the parent bus,
update this part to support s390x.
ID: 1986298

nic_hotplug.used_netdev: Support s390x

---

provider/virt_storage/storage_volume.py

For raw format, it does not need the 2nd blockdev-create
command to create the format, so delete it.
ID: 1989785

storage_volume: Fix hotplug raw image issue

---

qemu/tests/cfg/virtio_mode.cfg
qemu/tests/virtio_mode.py

In virtio_mode test case, other drivers lack driver_verifier parameter except netkvm.
So for other drivers, use driver_name to replace driver_verifier.
ID: 1989893

virtio_mode: fix driver_verifier missing issue

---

qemu/tests/cfg/pcie_hotplug_opt.cfg
qemu/tests/pcie_hotplug_opt.py

From QEMU6.1, the error message be changed to: "Bus '***' does not
support hotplugging", update the expected error message pattern
to make it work for all version.
id: 1988734

pcie_hotplug_opt: update the expected hotplug error message

---

generic/tests/vlan.py

Virtual-network: add support for vlan with "driver_verifier" on s390x
ID: 1987282

Add support for vlan on s390x

---

qemu/tests/block_during_io.py

Any errors and hangs (or an infinite loop) in a daemon process
will not affect the main process, and it will only be terminated
once the main process exits.The entire Python program exits when
no alive non-daemon threads are left, so we could set all threads
as daemon mode in background.
Signed-off-by: Yongxue Hong <yhong@redhat.com
ID: 1925927

block_during_io: Set sub-thread as daemon mode in background

---

provider/storage_benchmark.py

Add s390x support in the __init__() function of the
IozoneLinuxCfg class.
ID: 1989333

storage_benchmark: Add s390x support when make iozone

---

qemu/tests/mq_change_qnum.py

Sometimes guest will be launched with a private bridge, the bridge is a
NAT network so it cannot connect to the host's gateway. The gateway of
the guest should be the correct one as the ext_host because we are
testing the network connection of the guest.
ID: 1990518

mq_change_qnum: Set ext_host as the guest's gateway instead of host's

---

qemu/tests/vioser_in_use.py
qemu/tests/virtio_serial_file_transfer.py
qemu/tests/win_virtio_serial_data_transfer_reboot.py

Change the following files for this update:
1. vioser_in_use.py
2. virtio_serial_file_transfer.py
3. win_virtio_serial_data_transfer_reboot.py
ID: 1926582

virtio_serial: Set sub-thread as daemon mode in background

---

generic/tests/cfg/file_transfer.cfg

For some dirtos, "/tmp" is a tmpfs file system, its size is half of the
memory, so if the memory is too small, there is no space to copy the
temporary file.
ID: 1987211

file_transfer: Change the tmp directory to "/var/tmp"

---

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
qemu/tests/qemu_guest_agent.py

1. Change the code logic that get attribute 'qga_v' for RHEL9
2. Add parameter 'cmd_check_qgaservice' to qemu_guest_agent_hotplug.cfg
ID: 1990794

qemu-guest-agent: Getting 'qga_v' for rhel9 and fix a minor issue

---

qemu/tests/blockdev_mirror_cancel_ready_job_with_io.py
qemu/tests/blockdev_mirror_cancel_running_job.py

Replace job-cancel by block-job-cancel for mirror job
according to the usage change of upper layer
id:1992514

blockdev_mirror_*: replace job-cancel by block-job-cancel for mirror job

---

qemu/tests/cfg/tcpreplay.cfg

tcpreplay: Fix the tcpreplay execution command using a fixed bridge name

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 1986694
Steps:
1. boot guest '-cpu $cpu_model,avx_vnni'
on supported host.
2. check cpu flag inside guest.

x86_cpu_flags:add new case to test avx_vnni

---

qemu/tests/cfg/numa_opts.cfg

Memory: Since s390x only have one numa node, remove test case requires
more
ID: 1995036

Remove numa test cases require more than one node on s390x

---

qemu/tests/blockdev_stream_on_error_ignore.py
qemu/tests/cfg/blockdev_stream_on_error_ignore.cfg

Check stream complete with no space left after lvm extend
id:1965216

blockdev_stream_on_error_ignore:update job event check after extend lvm

---

provider/ansible.py
qemu/tests/ansible_test.py
qemu/tests/ansible_with_responsive_migration.py
qemu/tests/cfg/ansible_test.cfg

1. Check ansible exists or not before test start
2. Install ansible use the method that defined by ansible_install_policy
3. If install ansible with pip, install sshpass separately as it can't be
installed automatically. Install specified sshpass if failed to install
it from distro and there is a specified sshpass pkg.
id: 1993730

ansible: check ansible exists or not before test start

---

provider/storage_benchmark.py

Use fio_resources to define the priority of different resources, and
get 'fio_path' according to it.
id: 1992963

storage_benchmark: get fio path from the fio resources defination

---

qemu/tests/blockdev_commit_forbidden_actions.py
qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg

Snapshot related action should be forbidden after live commit starts
id:1995912

blockdev_commit_forbidden_actions:Forbide block job ops during commit

---

qemu/tests/discard_for_raw_block_target.py

Update the output check function to match the read size with the imag size.
ID: 1998022

discard_for_raw_block_target: update according to the behavior changes of 'fallocate'

---

qemu/tests/blockdev_commit_auto_readonly.py
qemu/tests/cfg/blockdev_commit_auto_readonly.cfg

Support auto-read-only=on for various backends:filesystem at present
id:2000429

blockdev_commit_auto_readonly:Support auto-read-only=on for filesystem backend

---

qemu/tests/cfg/virtio_fs_share_data.cfg

fix memory-backend-file option configuration is invalid on S390
id:1996927

virtio_fs:fix memory-backend-file option cfg is invalid on S390

---

qemu/tests/virtio_fs_share_data.py

PR adds error messages for pjdfstest and xfstest in virtio_fs_share_data test case.
ID: 1999727

virtio_fs_share_data: add error messages for pjdfstest and xfstest

---

qemu/tests/cfg/fio_perf.cfg
qemu/tests/fio_perf.py

fio package is setup in Linux guests installation processs by default,
so remove the setup steps of fio in the case.
ID: 2000378

fio_perf: remove the setup steps of fio for Linux guests

---

qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Avoid the whole virtio_fs_share_data.cfg being too long,the multi backend
part is seperated to be one new cfg file.
ID: 1997512

virtio-fs: create a new multi_backend config file

---

qemu/tests/hv_check_cpu_utilization.py

Guest not get idle status with current sleep time,
so the test result will be wrong.
ID: 1998977

hv_check_cpu_utilization: extend time to let guest chill

---

qemu/tests/cfg/vioinput_enable.cfg
qemu/tests/driver_in_use.py

Some codes changed impact the vioinput_enable case.
Change the driver running check codes to match vioinput device.
id: 2000844

driver_in_use: update driver running verify for vioinput

---

qemu/tests/cfg/blockdev_commit_standby.cfg

Limit case support version to "larger than RHEL8.3"
id:2004365

blockdev_commit_standby: limit support version

---

qemu/tests/cfg/blockdev_inc_backup_inconsistent_bitmap.cfg

…u_img
Remove repair_bitmap_with_qemu_img from
blockdev_inc_backup_inconsistent_bitmap.cfg
id:2007525

blockdev_inc_backup_inconsistent_bitmap:remove repair_bitmap_with_qemu_img

---

qemu/tests/cfg/x86_cpu_asyncpf.cfg
qemu/tests/x86_cpu_asyncpf.py

ID: 1986692
1. boot a guest with "-machine pc-q35-rhel8.5.0" or newer.
2. check guest's dmesg, should see Async PF enabled
3. check 'Hypervisor callback interrupts' inside guest,
should have at least 1 for each CPU.

x86_cpu_asyncpf: Async PF enabled

---

qemu/tests/boot_from_device.py
qemu/tests/boot_order_check.py
qemu/tests/cfg/boot_from_device.cfg
qemu/tests/cfg/boot_order_check.cfg
qemu/tests/cfg/seabios.cfg
qemu/tests/cfg/seabios_hotplug_unplug.cfg
qemu/tests/cfg/seabios_order_once.cfg
qemu/tests/cfg/seabios_strict.cfg
qemu/tests/seabios.py
qemu/tests/seabios_hotplug_unplug.py
qemu/tests/seabios_order_once.py
qemu/tests/seabios_strict.py

seabios: disable sga device in rhel9

---

provider/win_dump_utils.py
qemu/tests/cfg/fwcfg.cfg
qemu/tests/fwcfg.py

Fwcfg64 basic function test:
1) Boot guest with -device vmcoreinfo.
2) Check the fwcfgg64 driver has been installed.
3) Run "dump-guest-memory -w memory.dmp" in qemu monitor.
4) Check the memory.dmp can be saved and the size is larger then 0Kb.
5) Check the dump file can be open with windb tools.
id: 1992917

Add new case for fwcfg64 basic testing

---

qemu/tests/virtio_fs_share_data.py

In case fuser -km command timeout, should go to a dir outside that fuser called.
ID: 2017629

virtio_fs: resolve fuser -km timeout issue

---

qemu/tests/usb_redir.py

Set default argument shell=True to guarantee the repository creation on host.
ID: 1965742

usbredir_server: set default argument shell=True

---

qemu/tests/disk_extension_lvm.py

When writing data is almost complete, Sometimes the VM
will not step in pause statue.
ID:2018076

Fix check vm status timeout issue

---

qemu/tests/blockdev_stream_to_invalid_node.py
qemu/tests/cfg/blockdev_stream_to_invalid_node.cfg

Error msg is changed after qemu6.1, add support for it
id:2004327

blockdev_stream_to_invalid_node:support new error msg in qemu6.1

---

qemu/tests/blockdev_inc_backup_mod_readonly_bitmap.py

if bitmap can't saved
Make sure bitmap saved to image after vm shutdown,
if not, fail the case.
id:2007543

blockdev_inc_backup_mod_readonly_bitmap:fail case     if bitmap can't saved

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
ID: 2020157

driver_load_stress: join() argument must be str, bytes not 'NoneType'

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

No need to use stress testing for the background test during do
driver update/downgrade/install/uninstall/load/unload test
ID: 2020996

Change fio parameter for viofs driver test

---

qemu/tests/cfg/timedrift_with_multi_vms.cfg

aarch64 architecture only supports 'arch_sys_counter' clocksource, so
change it accordingly.
ID: 2021712

timedrift_with_multi_vms: Change clocksource on aarch64

---

generic/tests/netstress_kill_guest.py

Virtual_network: Since this case has an abnormal activity for killing
guests, change the way of starting netperf_stress
ID: 2015540

Modify the way of starting netperf_stress in netstress_kill_guest

---

qemu/tests/balloon_hotplug.py
qemu/tests/cfg/balloon_hotplug.cfg

Memory: add parent_bus to support ballon device on s390x
ID: 2022207

add ballon device support on s390x

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent_update.py

1. qemu_guest_agent.cfg: add 'gagent_download_cmd' to avoid case
get skip in test loop.
2. qemu_guest_agent_update.py: "add 'rpm_install' situation and
process code in another way that use the same logic with
self.gagent_src_type == 'virtio-win'."
ID: 2024030

qemu_guest_agent: Hotfix for adding 'gagent_download_cmd'

---

qemu/tests/qemu_guest_agent.py

qemu_guest_agent.py: Remove '/etc/qemu-kvm/fsfreeze-hook' check
point, because /etc/qemu-kvm/fsfreeze-hook was wrong
location used in RHEL 8. We have to keep it for backward
compatibility within RHEL 8. 
ID: 1999401

qemu-guest-agent: Remove previous workaround for RHEL8

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py

If driver verifier is enabled, the %errorlevel% is 2 when
"verifier /reset"
id: 2014962

netperf: stop driver verifier for performance testing

---

generic/tests/cfg/kdump.cfg

s390 could not find any nmi file under /proc/sys/kernel, so should 
skip testing nmi scenarios.
ID: 2026191

kdump: Disable nmi test cases on s390 platform

---

qemu/tests/cfg/valgrind_memalign.cfg
qemu/tests/valgrind_memalign.py

In this case, s390x guest will enter the "guest-panicked" status
instead of "running", so vm.resume() cannot verify the correct status.
ID: 2024601

valgrind_memalign: Pause VM and continue it to verify status on s390

---

qemu/tests/cfg/blockdev_mirror_after_block_error.cfg

Set BLOCK_IO_ERROR event timeout
id:1966879

blockdev_mirror_after_block_error: add event timeout

---

qemu/tests/cfg/blockdev_mirror_cancel_running_job.cfg

Add param "speed" for mirror job to make it can be
cancelled before reach ready status
id:2004360

blockdev_mirror_cancel_running_job: add option speed

---

qemu/tests/cpu_device_hotplug_during_boot.py

In the newer version of kernel, the output of udev device
initialization has a little change, so the current pattern could not
capture the output, so update the "boot_patterns" accordingly.
ID: 2001530

cpu_device_hotplug_during_boot: Update boot pattern

---

qemu/tests/cfg/multi_nics_stress.cfg
qemu/tests/multi_nics_stress.py

Currently, memory overcommit has not yet been officially supported.
But avocado will give each guest half of the host's memory, which will cause oom.
ID:2025824

multi_nics_stress:Set guest memory based on host resource

---

qemu/tests/cfg/virtio_fs_multi_vms.cfg

If using a normal file as the memory backend, should delete it
at the end,otherwise, next time the vm system will fail to boot up.
Also libvirt will delete the file after shutdown vm.
ID: 1978177

virtio_fs: clear memory backend file after vm is shutdown

---

qemu/tests/cfg/fio_perf.cfg

change the fio cmd to fio options to match the current framework
ID: 2029259

fio_perf: fix TypeError of the raw disk

---

.github/workflows/ci.yml

Disable the CI check on Python 2.7 as we no longer support such the
use case.

CI: disable the check on Python 2.7

---

qemu/tests/expose_host_mtu.py

Since configure_network.py has been deleted,So some changes
were made to solve the issue.
ID:2030091

expose_host_mtu:fix the issue of module not found

---

qemu/tests/block_resize.py

Since we recently updated the windows image size, some windows versions
have an image size of 32G, which will cause the block size to be not a
multiple of 512.
ID:2031569

block_resize: update block_size calculation algorithm

---

qemu/tests/cfg/fio_perf.cfg

The output file of fio cmd isn't the same with it in scp cmd,
fix this issue.
ID: 2031500

fio_perf: fix scp failed issue on virtiofs perf test

---

qemu/tests/balloon_check.py

Memory_balloon: check if vm.monitor is None before get balloon info
since vm.monitor would be none sometimes
ID: 2024564

balloon_check: Check vm.monitor before get balloon info

---

qemu/tests/migration_with_dst_problem.py

The cause of the raised error has been fixed. Also a related unwanted magnitude conversion has been removed.
ID: 2030589
Signed-off-by: bgartzia <bgartzia@redhat.com>

migrate.after_extensive_io: Fix ValueError

---

qemu/tests/cfg/sve_basic.cfg

The new qemu version update the error message when launch a guest with
unsupported sve length, the error messages are similar but not the
same, so update the pattern accordingly.
ID: 2034464

sve_basic: Update error_msg for unsupported vector length

---

qemu/tests/block_iscsi_with_specical_max_sectors.py
qemu/tests/cfg/block_iscsi_with_specical_max_sectors.cfg

Add case for specific max sector of disk

---

qemu/tests/cfg/watchdog.cfg

Device 'ib700' can't go on PCIE bus, so remove it
ID: 2035734

Remove ib700 test cases for q35

---

qemu/tests/balloon_memhp.py

After hotplug memdev, need to wait a while before check memory in windows guest.
ID: 1874694

balloon_memhp: wait a while before check guest memory for windows vm

---

qemu/tests/qemu_guest_agent.py

qemu_guest_agent.py: Get the penultimate value from a list instead
of the positive second value.
ID: 2035626

qemu_guest_agent: Change the logic that get value from a list

---

provider/win_dump_utils.py
qemu/tests/cfg/fwcfg.cfg
qemu/tests/cfg/fwcfg_enable.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/fwcfg.py

1. Add disable security alert step
2. Change the way for finding memory dump file path
3. Adjust win2012-64/r2 extracted and dump id check cmds
4. optimize the dump extracted timeout issues
id: 2019273, 2024074

Update settings for fwcfg related cases

---

qemu/tests/qemu_guest_agent.py

qemu_guest_agent.py: clean timeout parameters for some commands.
ID: 2031084

qemu-guest-agent: Erase some invalid timeout settings

---

qemu/tests/cfg/vsock.cfg
qemu/tests/migration_with_vsock.py
qemu/tests/vsock_hotplug.py
qemu/tests/vsock_negative_test.py
qemu/tests/vsock_test.py

Replace nc-vsock with ncat for vsock test on rhel9
ID: 2034163

Replace nc-vsock with ncat for vsock test

---

qemu/tests/cfg/qmp_event_notification.cfg

The commit https://github.com/qemu/qemu/commit/1adf528ec3bdf62ea3b580b7ad562534a3676ff5
enables the current PL031 to report the guest's RTC changes to the QMP
monitor, so after this(qemu-6.2) on the aarch64 platform can also
enable qmp_rtc_change.
ID: 2037580

qmp_rtc_change: Add aarch64 support

---

qemu/tests/memory_leak_after_nichotplug.py

The ssh session will take a few memory for use when we connect using
ssh and execute a lot of commands, there has confusion that the memory
is used by ssh or "ip link add", so use the serial session to avoid it.
ID: 2039155

memory_leak_after_nichotplug: Use serial session for Linux

---

qemu/tests/blockdev_commit_fio.py

Add timeout values for fio.run() function and the
wait_until_block_job_completed() function to make
the test on ppc PASS.
ID: 2036019

blockdev_commit_fio: Add timeout value

---

qemu/tests/cfg/block_during_io.cfg

Sometimes, iozone test with -g 10G will write full the system disk, cause the system not bootable normally, will block all other jobs behind this job.
id: 1774814

block_during_io: update the iozone -g parameter to 4G

---

qemu/tests/virtio_serial_hotplug_port_pci.py

Make sure the guest boot successfully before hotplug otherwise the guest
may crash.
Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
Before
```
[snip]
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.arm64-pci: ERROR: VM is dead due to a kernel crash, see debug/serial log for details (295.34 s)
```
After
```
[snip]
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.virtio_port_hotplug.hotplug_port_pci.arm64-pci: PASS (85.32 s)
```

virtio_serial_hotplug_port_pci: Fix guest crash caused by hotplug

---

qemu/tests/cfg/seabios.cfg
qemu/tests/seabios_bin.py

bios.bin is used for rhel6 machine type, it has been remove
from the seabios build in rhel9. So skip checking it.
ID: 2040348

seabios_bin: skip bios.bin checking for rhel9

---

qemu/tests/cfg/seabios.cfg

bios.bin has been remove from the seabios build in rhel9.
ID: 2040348

seabios_bin: only check bios.bin in rhel6, rhel7 and rhel8

---

qemu/tests/memhp_threads.py

memhp_threads: fix \_\_atributes\_\_ error
\_\_atributes\_\_ was deleted from Memory class in
virttest/qemu_devices/qdevices.py on avocado-vt,
but since three lines block was added in \_\_init\_\_
that assings the value to params, no call to the
Memory.\_\_atributes\_\_  is longer needed nor the
following line, just the call to the constructor.
ID: 2035697

memhp_threads: fix attribute error

---

generic/tests/netperf.py

When test failover case in loop, it's failed since the external device
was set down in last test. in such case, the deivce on host is
NO-CARRIER, then the guest could not get ip through dhclient.
id: 2041356

Netperf: remove "ifconfig down"

---

qemu/tests/cfg/virtio_fs_set_capability.cfg

Output of 'capsh print'  is changed on rhel9 and rhel860,
so to make the output check works on the old one and the latest one, redesign it.
Now just check 'Bounding set' line works on both.
ID: 2052775

virtio-fs: capsh print result check change

---

qemu/tests/block_hotplug_in_pause.py

Applying small changes over the block_hotplug_in_pause testcase.
A bug was reported since the script was waiting for QMP to generate a `<type>_DELETED` event after deleting a stg0_encrypted object by QMP, using the `object-del` command.
Since the scope of the test is just limited to hotplugging and unpluging block devices, checking if the just-unplugged thing is a QObject or a QDevice and awaiting for the event in case of the latter should do the work.
ID: 1990759

block_hotplug_in_pause: stg0_encrypted not deleted

---

qemu/tests/block_resize.py
qemu/tests/cfg/block_resize.cfg

Since sometimes windows command cannot get response in 1s,
update the wait_for function steps to 3 here.
id: 1970334

block_resize: update wait_for function steps

---

qemu/tests/cfg/multi_disk_random_hotplug.cfg

The change in the configuration fixes the issue when trying to plug a 6th device during the test mentioned in the PR title.
I think that the issue should be fixed in the base.cfg. However that
could be risky since it wouldn't be affecting only to tests from this
provider. I opened another issue in the avocado-vt repo to discuss
about the usb_bus config. https://github.com/avocado-framework/avocado-vt/issues/3351
Meanwhile, I provide this patch, which fixes the issue for this test, while the more general fix is discussed.
Signed-off-by: Beñat Gartzia <bgartzia@redhat.com>
ID: 2034503

multi_disk_random_hotplug: cant insert ehci device

---

qemu/tests/cfg/virtio_fs_share_data.cfg

Default is no_writeback, so add test scenario with writeback.
ID: 2035203

virtio_fs: support writeback option on virtiofsd

---

qemu/tests/cfg/openflow_acl_test.cfg

1.The main connection tools on rhel9 are ssh and nc
ID:2052853

openflow_acl_test: Disable telnet test on rhel9

---

qemu/tests/cfg/usb.cfg

1. Disable usb-ccid device tests since ARM does not support it
2. Re-enable usb-storage tests starting with qemu-6.0
ID: 2057305

usb: Disable usb-ccid and re-enable usb-storage on ARM

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

1. on rhel900,we use virtiofsd-rust version which it doesn't support -o posix_lock and -o flock
2. Also add writeback test for multi backend test.
ID:  2052843

virtio_fs: virtiofsd config update for some options

---

qemu/tests/cfg/transfer_file_over_ipv6.cfg
qemu/tests/transfer_file_over_ipv6.py

Link-local IPv6 address is a local unicast address with prefix fe80,
for general IPv6 testing, we should use the public/remote IPv6 address
instead of link-local address, this should be a more general scenario.
But we should also test local IPv6, to make it as configurable.
ID: 2039110

transfer_file_over_ipv6: Configurable IPv6 address type

---

qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
qemu/tests/cfg/multi_disk_random_hotplug.cfg

After some research about the vt_ulimit_nofile key usage in configurations, I catched a test case using the parameter as a workaround. I also catched (in multi_disk_random_hotplug) a redundant value assignment.
It looks like the rest of test cases using the vt_ulimit_nofile are doing it with other goals in mind rather than avoiding getting an error for the fd-leak when opening/closing sessions.
ID: 2051875

vt_ulimit_nofile: workarounds deletion

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

qga has two methods to run in windows:
1. The default method is to run as a service after installing
qemu-ga,msi. most users/customers are using that way.
2. Stop the default qemu-ga.service and run qemu-ga.exe as a
program.
Both of them are avaliable to work.
ID: 2054028
Signed-off-by: 6-dehan <demeng@redhat.com>

qemu_guest_agent: Add new case that run qga as a program

---

qemu/tests/blockdev_snapshot_chains.py
qemu/tests/blockdev_snapshot_merge.py
qemu/tests/cfg/blockdev_snapshot.cfg
qemu/tests/cfg/blockdev_snapshot_chains.cfg
qemu/tests/cfg/blockdev_snapshot_data_file.cfg
qemu/tests/cfg/blockdev_snapshot_guest_agent.cfg
qemu/tests/cfg/blockdev_snapshot_install.cfg
qemu/tests/cfg/blockdev_snapshot_merge.cfg
qemu/tests/cfg/blockdev_snapshot_multi_disks.cfg
qemu/tests/cfg/blockdev_snapshot_readonly.cfg
qemu/tests/cfg/blockdev_snapshot_reboot.cfg
qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg
qemu/tests/cfg/blockdev_snapshot_stress.cfg

Add ceph support for live snapshot
id:2045982

blockdev_snapshot: support backend ceph support for live snapshot

---

qemu/tests/transfer_file_over_ipv6.py

Fix typo: from `params.getboolean` to `params.get_boolean`
ID: 2062680

transfer_file_over_ipv6: Fix a typo `params.getboolean`

---

qemu/tests/cfg/virtio_fs_set_capability.cfg

Virtio_fs:correct capability parameter for virtiofs due to product changes
ID:2060219

Virtio_fs:correct capability parameter for virtiofs due to product's changing

---

provider/win_dump_utils.py

Customized params["mem"] type is float, correct it to str.
id: 2062669

Fix issue: unsupported operand type(s) for +: 'float' and 'str'

---

qemu/tests/cfg/tpm_verify_device.cfg
qemu/tests/tpm_with_check_aavmf.py

Check if the TPM message is correct in the edk2 output.
ID: 2062956

tpm_with_check_aavmf: Add new case to check TPM contents in edk2 on ARM

---

qemu/tests/cfg/tpm_with_tss.cfg
qemu/tests/tpm_with_tss.py

Clone the tpm2-tss repo and configure with tpm device, execute the unit
test and check the test result.
ID: 2060235

tpm_with_tss: Add a new case to test tpm2-tss unit test inside guest

---

qemu/tests/cfg/tpm_bind_luks.cfg
qemu/tests/tpm_bind_luks.py

Add the new case to format the extra disk to LUKs format, bind it with
TPM2 policy via clevis, and reboot the guest to check if the operating
system can unlock it automatically.
ID: 2060234

tpm_bind_luks: New case to bind luks disk with TPM2 policy via clevis

---

generic/tests/trans_hugepage_swapping.py

1. fix several TypeError
2. Use utils_memory to handle meminfo, and normalize the data size
3. Correct the incorrect unit conversion in dd cmd
4. For ppc, vm mem must align to 256M
5. Disable the swap in the guest before allocate the memory of guest
depends on: https://github.com/avocado-framework/avocado-vt/pull/3335
id: 2032449

trans_hugepage_swapping: fix several Error

---

qemu/tests/cfg/qmp_command.cfg

From cmd_return_value for aarch64 was deleted
{'name':'e1000e'} and {'name':'rtl8139'}.
ID: 2062912

qmp_command: changed cmd_return_value for aarch64

---

qemu/tests/blockdev_mirror_hotunplug.py

blockdev_mirror_hotunplug: change the critical condition on check device deleted.
ID: 2035988

blockdev_mirror_hotunplug.py: change the critical condition on check device deleted.

---

qemu/tests/cfg/hotplug_mem_reserve.cfg

In avocado-vt framework, the correct param name be used in env_process to
check required qemu is 'required_qemu'.
id:2070384

hotplug_mem_reserve: correct 'required_qemu_version' to 'required_qemu'

---

qemu/tests/blockdev_commit_fio.py
qemu/tests/cfg/blockdev_commit_fio.cfg

To verify the commit job can be completed after heavy IO finishes
id:2066993

blockdev_commit_fio: to verify commit can finish after fio done

---

generic/tests/cfg/ksm_services.cfg
qemu/tests/cfg/ksm_base.cfg
qemu/tests/cfg/ksm_ksmtuned.cfg
qemu/tests/cfg/ksm_overcommit.cfg

ksm: adds ksmtuned in cmds_installed_host cfg option
for ksm_base, ksm_services, ksm_overcommit and ksm_ksmtuned
cfg files
depends on: https://github.com/avocado-framework/avocado-vt/pull/3353
ID: 2034135

ksm_base: adds ksmtuned in cmds_installed_host cfg option

---

qemu/tests/cfg/block_with_share_rw.cfg
qemu/tests/cfg/interrupt_check.cfg
qemu/tests/cfg/multi_disk_random_hotplug.cfg
qemu/tests/cfg/pvpanic_basic.cfg
qemu/tests/cfg/slof_memory.cfg
qemu/tests/cfg/slof_open_bios.cfg
qemu/tests/cfg/slof_order.cfg
qemu/tests/cfg/slof_user_interface.cfg
qemu/tests/cfg/systemtap_tracing.cfg
qemu/tests/cfg/usb.cfg
qemu/tests/cfg/usb_device_check.cfg
qemu/tests/usb_common.py
qemu/tests/usb_hotplug.py
qemu/tests/usb_redir.py

Several usb device configuration parameters were not being read during device generation in virttest. That implied introducing changes that also affected the name of the keys used to configure those device parameters (please refer to https://github.com/avocado-framework/avocado-vt/pull/3361)
This changes updates the cfg files so the parameters will be taken into account once the mentioned PR gets merged.
It also reverts 75f26e28ae21e4e49b6dfbd1858994cf28362ff1 since the added configuration in that commit will be implied in the base configuration if the already mentioned pr gets merged.
ID: 2059254

usb: port and bus param parsing

---

qemu/tests/cfg/chardev_tls_encryption.cfg

Add code to support s390x test for the chardev tls encryption
scnearios.
ID: 2070005

chardev_tls_encryption: Add s390x support

---

qemu/tests/cfg/smbios_default_check.cfg

For baseboard-product-name, either RHEL-AV or RHEL is right.
ID: 2038054

smbios_default_check: the RHEL-AV / RHEL split is gone in rhel9

---

qemu/tests/cfg/boot_order_check.cfg

3. rhel8 will continue to support sgabios, but starting with 8.6
libvirt uses "-machine graphics=off" so rhel-8 testing
should be switched over too.
ID: 2036174

seabios: disable sga device from rhel8.6 and the later version

---

provider/storage_benchmark.py
qemu/tests/blockdev_commit_fio.py
qemu/tests/blockdev_snapshot_reboot.py

Need ensure all backgroupd threads exit before the main thread exits,
otherwise, will hit error "Test reported status but did not finish"
id: 2072801

blockdev_commit_fio: fix background thread can't exit preperly

---

qemu/tests/cfg/virtio_console.cfg

Since there is a product bug on s390x virtio console, will only
test virtio serial devices for this case.
ID: 2074794

virtio_console..restart.stressed: Only test virtio serial devices

---

provider/ansible.py

1. For python_install on s390x and ppc64le, it would fail on s390x
and ppc64le for ansible's dependency module cryptography which
needs Rust >=1.41.0; while it can only be installed through
'yum install'. So add code to support it.
2. Merge the code of package 'sshpass' installation.
ID: 2056492

Ansible: Add s390x/ppc64le support for python_install

---

qemu/tests/cfg/win_irq_check.cfg

1.Boot the guest with multiple queues nic with guest msi disabled
inside guest, should support windows guest
ID:1485223

win_irq_check: Add multi queues test scenario

---

qemu/tests/cfg/slof_boot.cfg
qemu/tests/slof_boot.py

While running slof test cases we'd better record the slof version.
ID:2073261

slof: add checking slof version step for slof_boot test cases

---

qemu/tests/cfg/fio_perf.cfg

Signed-off-by: Liu Yiding <liuyd.fnst@fujitsu.com>
```
(1/1) Host_RHEL.m8.u6.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.6.0.aarch64.io-github-autotest-qemu.fio_perf.shared_fs.virtio_fs_perf.always.arm64-pci
```

fio_perf: Enable virtio_fs_perf for aarch64

---

generic/tests/cfg/kdump.cfg

Since crashkernel=auto is not supported on latest rhel9,
so remove the setting from our scripts.
ID:2075732

kdump:remove crashkernel=auto setting

---

qemu/tests/bridge_qinq.py
qemu/tests/cfg/bridge_qinq.cfg

1. Move some static parameters to the top to avoid UnboundLocalError
2. The guest contains many vlan interfaces, when destroying the VM,
"ifconfig -a" will time out, so set gracefully to "False" to avoid the
issue.
3. This is only a basic test to check extertypes, however tcpdump will 
capture all packages and this makes the log size too huge. So reduce the 
ping count to reduce the log size, also use "setsid" command to run 
tcpdump in the background, to avoid dirty output when issuing "pkill 
tcpdump".
ID: 2078050

bridge_qinq: Fix unexpected errors and reduce log size 
