qemu/tests/cfg/virtual_nic_send_buffer.cfg, qemu/tests/virtual_nic_send_buffer.py
=> Virtual nic send buffer

qemu/tests/boot_with_different_vectors.py, qemu/tests/cfg/boot_with_different_vectors.cfg
=> qemu.tests: Add boot_with_different_vectors test case and script.

qemu/tests/cfg/macvtap_event_notification.cfg, qemu/tests/macvtap_event_notification.py
=> qemu.tests: Add macvtap_event_notification new test case

generic/tests/netperf.py
Add _netserver_started to judge if need setup netserver during test.
Signed-off-by: Yiqiao Pu <ypu@redhat.com>
=> generic.tests: Add global variable _netserver_started in netperf

qemu/cfg/host-kernel/Host_RHEL/5/10.cfg, qemu/cfg/host-kernel/Host_RHEL/5/11.cfg, qemu/cfg/host-kernel/Host_RHEL/6/6.cfg, qemu/cfg/host-kernel/host-kernel-check.cfg
Add the released host version to host-kernel-check.cfg
Signed-off-by: Yang Xue <yaxue@redhat.com>
=> Add the released host version to host-kernel-check.cfg

generic/tests/cfg/kdump.cfg, generic/tests/cfg/multi_queues_test.cfg, qemu/tests/cfg/device_assignment_netperf_test.cfg, qemu/tests/cfg/ext_host_netperf_stress.cfg, qemu/tests/cfg/flow_caches_stress_test.cfg, qemu/tests/cfg/mq_change_qnum.cfg, qemu/tests/cfg/multi_vms_netperf_stress.cfg, qemu/tests/cfg/netperf_stress_test.cfg, qemu/tests/cfg/sr_iov_netperf_test.cfg, qemu/tests/cfg/suspend_under_netperf.cfg, qemu/tests/netperf_stress.py
=> Test protocols

generic/tests/shutdown.py
Current shutdown case can not works well with the guest when we
add -no-shutdown in the command line. Update it fit it. Also add
a detail check with the status monitor output after shutdown.
=> generic.tests: Make shutdown can work with -no-shutdown

generic/tests/cfg/multi_queues_test.cfg
=> multi_queues_test.cfg: multi queues only support virtio_net.

generic/tests/cfg/guest_test.cfg, generic/tests/guest_test.py
=> generic.guest_test: new case to test isa_serial port

qemu/tests/cfg/sr_iov.cfg, qemu/tests/sr_iov_hotplug.py, qemu/tests/sr_iov_hotplug_negative.py
=> Sr iov related case update

qemu/tests/cfg/file_copy_stress.cfg, qemu/tests/cfg/mq_change_qnum.cfg, qemu/tests/cfg/mq_max_queues.cfg, qemu/tests/file_copy_stress.py, qemu/tests/mq_change_qnum.py
Redhat ID:  1010800 1010794  1010798  1010796
=> Update mq_change_qnum test case.

generic/tests/module_probe.py
Update the module list in the beginning of the test. This will helpful
to restore the test env when this test is finished.
Need support of:
https://github.com/autotest/autotest/pull/900
=> generic.tests: Improve module_probe

generic/tests/cfg/multi_queues_test.cfg
=> generic.cfg: Fix smp to 1 for multi_queues_test.with_netperf.smp1

qemu/tests/enospc.py
=> enospc.py: fix the typo of the arg

generic/tests/cfg/guest_suspend.cfg, qemu/tests/cfg/suspend_under_netperf.cfg, qemu/tests/netperf_stress.py
=> Update Suspend under netperf

qemu/tests/cfg/pktgen.cfg, qemu/tests/pktgen.py
1). add step to check host/guest dmesg
2). add step to check guest network via ping command
3). fix some typo error
=> Add missed steps

qemu/tests/cfg/openflow_acl_test.cfg, qemu/tests/openflow_acl_test.py
Add openflow access control test. Set up openflow rules for deny
access from of to guest. Choice website, ftp, ssh and telnet to
test the rules actually work.
=> qemu.tests: Add openflow access control test

qemu/tests/cfg/migrate.cfg, qemu/tests/migration_with_netperf.py
=> qemu.tests: Update migration_with_netperf.

qemu/tests/nic_bonding.py
=> qemu.tests: Update nic_bonding to cover more test point.

generic/tests/cfg/timedrift.cfg
=> generic.tests.cfg: Update incorrect configure in timedrift.cfg

qemu/tests/nic_hotplug.py
1. add steps reboot vm after nic hotplug and hotunplug
2. check vm status after pause & resume
3. add debug info when raise VMAddressVerificationError and VMIPAddressMissingError
=> qemu.tests.nic_hotplug: add missed reboot step

qemu/tests/cfg/file_copy_stress.cfg
=> qemu.cfg: Update clean_cmd to del /q /f for file_copy_stress

qemu/tests/migration_multi_host.py
1. Add check guest doesn't reboot during multi-host migration
2. Clear unused imports
=> qemu.tests: Improve migration_multi_host

qemu/deps/win_serial/VirtIoChannel_guest_recieve.py, qemu/tests/balloon_stress.py, qemu/tests/boot_from_device.py, qemu/tests/boot_order_check.py, qemu/tests/cdrom.py, qemu/tests/change_media.py, qemu/tests/cpuid.py, qemu/tests/migration_with_dst_problem.py, qemu/tests/multi_disk_random_hotplug.py, qemu/tests/ovs_mirror.py, qemu/tests/seabios.py, qemu/tests/usb_storage.py
Fixes for the new problems that the latest pylint and PEP8 checks started finding in our codebase.
=> Fix pep8 new problems

qemu/tests/cfg/invalid_parameter.cfg, qemu/tests/invalid_parameter.py
=> Invalid parameter

qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot.py
=> qemu.tests: Add reboot_timeout parameter for live_snapshot

generic/tests/cfg/guest_test.cfg, generic/tests/cfg/iometer_windows.cfg, qemu/cfg/host-kernel/Host_RHEL/5.cfg, qemu/cfg/tests-spice.cfg, qemu/tests/cfg/nic_bonding_host.cfg, qemu/tests/cfg/openflow_acl_test.cfg, qemu/tests/cfg/watchdog.cfg
As the get() of params changed, some of the cfgs need update.
=> qemu: Update the useage for params in cfg

qemu/tests/cfg/virtio_serial_stop_continue.cfg
=> qemu.cfg: Add virtio_serial_stop_continue test case.

generic/tests/cfg/file_transfer.cfg, generic/tests/cfg/nic_promisc.cfg, qemu/tests/cfg/device_assignment.cfg, qemu/tests/cfg/driver_load.cfg, qemu/tests/cfg/live_snapshot.cfg, qemu/tests/cfg/mq_change_qnum.cfg, qemu/tests/cfg/mq_max_queues.cfg, qemu/tests/cfg/nic_bonding.cfg, qemu/tests/cfg/nic_bonding_host.cfg, qemu/tests/cfg/openflow_test.cfg, qemu/tests/cfg/set_link.cfg, qemu/tests/cfg/virtual_nic_send_buffer.cfg
=> qemu: Delete transfer_type parameter

qemu/tests/nic_bonding_host.py
Make two update in nic bonding host test:
- Make the bonding mode can be set by cfg file
- Remove the iface that already used from our iface list for bonding test.
=> qemu.test: Update for nic_bonding_host

qemu/tests/migration_after_nichotplug.py
=> qemu.tests: add step to check hotpug nic works after reboot

qemu/control_files/control.kernel-version
=> qemu: Support dryrun parameter in control.kernel-version

qemu/cfg/host-kernel/Host_RHEL/7/1.cfg, qemu/cfg/host-kernel/host-kernel-check.cfg
=> qemu.cfg: Add RHEL.7.1 into host-kernel-check.cfg

qemu/tests/balloon_stress.py
=> fix typo in balloon_stress test case

qemu/tests/cdrom.py
Update a mistake made in gluster support. And add one line for debug.
=> qemu.tests: Update the cleanup_cdrom in cdrom test

qemu/tests/cfg/drive_mirror.cfg
=> tp-qemu: start iptables before job cancel negative test

qemu/tests/rv_video.py
Sometimes, totem crashes and doesn't start and causes test to
fail. Restart totem if you can't find PID of totem after 10 seconds.
Also, use gsettings instead of dconf for RHEL7.
=> spice.rv_video: Restart totem if it crashes

qemu/tests/cfg/spice.cfg
=> qemu.tests.cfg.spice: Add RHEL7 to spice testing

qemu/tests/balloon_disable.py
Update the check string as the output from monitor is changed.
=> qemu.tests: Update the balloon disable check string

qemu/tests/cgroup.py
Disks might not be enumerated by kernel in the same order as added on
command line. This patch uses device serial number instead.
=> qemu.tests.cgroup: Use disk serial number instead of name

qemu/tests/ovs_qos.py
=> tp-qemu: ovs_qos: Improve the error info when test failed

generic/tests/mac_change.py
Update it as the output of monitor command line have changed.
=> generic.tests: Update the nic device id confirm method

qemu/tests/cfg/drive_mirror.cfg, qemu/tests/drive_mirror_simple.py
=> qemu.tests: fix cfg typo in drive_mirror

qemu/tests/cfg/qemu_img.cfg
=> qemu.cfg.qemu_img: Config update

qemu/tests/cfg/pci_hotplug.cfg
Update the block size check command for some spicial combination of
different device hotplug in the system.
=> qemu.tests.cfg: Update the block size check command in pci_hotplug

qemu/tests/cfg/virtio_serial_file_transfer.cfg, qemu/tests/virtio_serial_file_transfer.py
=> Add virtio serial file transfer basic test.

qemu/tests/rv_logging.py
spice_vdagent.log file is not available in RHEL7 anymore
and journalctl is used to look at spice-vdagent logs.
=> Updating rv_logging test for RHEL7

generic/tests/cfg/timedrift.cfg
=> generic.tests.cfg: Small fix for timedrift.cfg

qemu/tests/watchdog.py
=> qemu.tests.watchdog: Typo fix

qemu/tests/cfg/multi_macvtap_devices.cfg, qemu/tests/multi_macvtap_devices.py
=> qemu.tests: Add multi_macvtap_devices test case.

generic/tests/cfg/block_hotplug.cfg
=> tp-qemu: block_hotplug: disable ide for block hotplug.

qemu/tests/cfg/ovs_mirror.cfg, qemu/tests/ovs_mirror.py
make ovs mirror related case works on private ovs birdge to avoid complex network environment impact test result.
ID: 1189025
=> Make ovs mirror works on private ovs bridge

qemu/tests/multi_disk.py
Add check the disk number after get the disk list
for windows guest.
ID: 1207489
=> qemu.tests: Small fix for multi_disk

.travis.yml
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
=> Updating the autotest used in the Travis environment

qemu/tests/cfg/virtio_port_login.cfg, qemu/tests/virtio_port_login.py
=> qemu.tests: add virtio port login test rhel-only

qemu/tests/device_bit_check.py
In old version qemu, qtree use on/off for bool type property,
Now it use true./false instead. Update code to make this case
support both old and new version qemu output.
=> qemu.tests: make device property support both old and new qemu

qemu/tests/cfg/seabios.cfg, qemu/tests/seabios.py
=> Seabios bug fix

qemu/tests/rv_build_install.py
Adding a build_install_spiceprotocol function to build spice-protocol
before building any of the other packages. Also, other minor changes.
=> spice: Adding building of spice protocol function and minor updates

generic/tests/cfg/guest_test.cfg, qemu/cfg/unittests.cfg, qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/cfg/valgrind_memalign.cfg
Related pullreq: 
https://github.com/autotest/virt-test/pull/2184
=> qemu: Update isa_serials to serials in cfg files

qemu/tests/boot_from_device.py
=> tp-qemu: make iscsi image setup/cleanup via qemu_storage module

qemu/tests/ovs_qos.py
=> tp-qemu: only care peak value of throughput

qemu/deps/spice/build_install.py
Created a function to run the subprocess command as the code was
getting repeated multiple times.
=> qemu.spice: Refactoring for easier understanding of code

qemu/tests/pci_hotplug.py
Seems we only insert the device to vm.devices but forget to remove it
after the device is hot-unplug from vm.
=> qemu.tests: Remove the device from vm device container after hot-unplug

qemu/tests/usb_basic_check.py
=> qemu.tests: wait for device ready when check inside guest

qemu/tests/qmp_event_notification.py
=> tp-qemu: get target monitor by protocol

qemu/tests/cfg/seabios.cfg
=> qemu.tests.cfg: Update boot_device config for seabios

qemu/tests/set_link.py
=> qemu.tests: Catch the multiple exceptions

qemu/tests/cfg/usb.cfg
=> tp-qemu: usb.cfg: add some usb types.

qemu/tests/rv_build_install.py
Updating from spice-gtk 0.28 to spice-gtk 0.29.
=> qemu.spice: Modifying tarball version to use newer released version

qemu/tests/rv_video.py
=> qemu.spice: Update rv_video to use display 0

qemu/tests/cfg/rh_kernel_update.cfg, qemu/tests/rh_kernel_update.py
=> tp-qemu: add rh_kernel_update test

generic/tests/cfg/mac_change.cfg
=> generic.tests.cfg: Disable the guests which are not supported mac_change

qemu/deps/cpuid/README, qemu/tests/cfg/qemu_cpu.cfg
Add README to cpuid test, update the cfg format to make it the same with other cfg files and fix config issue
=> tp-qemu: Add README to cpuid test, and fix cfg file issue

qemu/tests/cfg/nic_teaming.cfg, qemu/tests/nic_teaming.py
Signed-off-by: Qian Guo <qiguo@redhat.com>
=> Add team driver failover test for RHEL7.x guests

qemu/tests/cdrom.py, qemu/tests/floppy.py, qemu/tests/migration_multi_host.py, qemu/tests/migration_multi_host_cancel.py, qemu/tests/migration_multi_host_downtime_and_speed.py, qemu/tests/migration_multi_host_firewall_block.py, qemu/tests/migration_multi_host_ping_pong.py, qemu/tests/migration_multi_host_timedrift.py, qemu/tests/migration_multi_host_with_file_transfer.py, qemu/tests/migration_multi_host_with_speed_measurement.py
=> qemu.tests: Add rdma protocol support for migration_multi_host

qemu/tests/cfg/rh_kernel_update.cfg
=> qemu.test.rh_kernel_update: support powerpc

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/qemu_disk_img_info.py
This PR depends on autotest/virt-test#2241
=> qemu.tests: Add qemu_disk_img_info test case

qemu/tests/cfg/qemu_io_blkdebug.cfg
=> tp-qemu: qemu_io_blkdebug: no need to start vm for the case.

qemu/tests/virtual_nic_private.py
=> tp-qemu: fix get vm mac address failed issue

qemu/cfg/host-kernel/Host_RHEL/6/7.cfg, qemu/cfg/host-kernel/host-kernel-check.cfg
=> tp-qemu: host-kernel: Add RHEL.6.7 host kernel config.

qemu/tests/cfg/numa.cfg, qemu/tests/numa_consistency.py
=> tp-qemu: numa_consistency: add numa hardware info to debug log when test failed

qemu/tests/cfg/qemu_cpu.cfg
=> tp-qemu: Disable hv_vapnic on RHEL6 ,enable hv_relaxed on RHEL6

qemu/tests/qemu_img.py
=> tp-qemu: backup image chain when boot guest failed

qemu/tests/cfg/qemu_disk_img.cfg
test cache mode for qemu-img commit
=> qemu.tests: Add qemu_disk_img_commit test case

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/qemu_disk_img_rebase.py
test "-b """ for qemu-img rebase.
This PR depends on autotest/virt-test#2231
=> qemu.tests: Add qemu_disk_img_rebase test case

generic/tests/cfg/mac_change.cfg
=> tp-qemu: mac_change: disable SLES.11.4 guest for up_change.

qemu/tests/cfg/balloon_check_qmp.cfg
=> tp-qemu: balloon_check_qmp.cfg: fix a typo.

qemu/tests/cfg/qmp_event_notification.cfg
Add some scenarios to get event "RESET" and "SHUTDOWN" when
send command in guest.
=> qemu.tests.cfg: Add some scenarios to cover more command in guest

.travis.yml
We have updated the distro version for the autotest
package. This changes the apt setup command accordingly.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
=> .travis.yml: Update ubuntu distro

qemu/tests/physical_resources_check.py
=> qemu.tests: Add more debug log to check

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/qemu_disk_img_snapshot.py
This PR depends on autotest/virt-test#2249
=> qemu.tests: Add qemu_disk_img_snapshot test case

qemu/tests/system_reset_bootable.py
=> small update to made test loop more readable

qemu/tests/cfg/boot_cpu_model.cfg
=> tp-qemu: fix boot_cpu_model.check_flag.add_flag failed issue

qemu/tests/qemu_disk_img.py, qemu/tests/qemu_disk_img_commit.py, qemu/tests/qemu_disk_img_convert.py, qemu/tests/qemu_disk_img_rebase.py
=> qemu.test.qemu_disk_img: code clean up to make it more readable

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host.py, qemu/tests/migration_multi_host_with_reboot.py
Add do live migration during vm boot with random time and
reboot vm with system_reset.
=> qemu.tests: Add boot/reboot cases for migration_multi_host

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host_cancel.py, qemu/tests/migration_multi_host_with_file_transfer.py
Update cases migration_multi_host_cancel and
migration_multi_host_with_file_transfer.
id: 1256111 1256113
=> qemu.tests: Update some cases of migration_multi_host

qemu/deps/spice/key_event_form.py, qemu/deps/win_serial/serial-host-send.py, qemu/tests/balloon_stress.py, qemu/tests/chardev_hotplug.py, qemu/tests/disable_win_update.py, qemu/tests/drive_mirror_simple.py, qemu/tests/multicast_iperf.py, qemu/tests/qemu_disk_img.py, qemu/tests/rv_smartcard.py, requirements-travis.txt
Now we're going to start being picky about unused imports. Brace yourselves.
=> Update to inspektor 0.2.0

.travis.yml
Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>
=> .travis.yml: Add python 2.6 to the test matrix

qemu/tests/pci_hotplug.py
1. Do not print some unimportant monitor logs in debug file, as there will be
a lot of logs in debug file if repeat hotplug devices, which is hard to read.
But we can still check the logs in montior log.
2. add is_supported_cmd().
id: 1233048
=> tp-qemu: pci_hotplug.py: some updates for the case.

qemu/tests/driver_in_use.py
=> tp-qemu: Add a framework for whql related cases when driver in use.

CODING_STYLE, README.rst
s/describle/describe
s/Readbility/Readability
s/indepentently/independently
=> Fix typos in CODING_STYLE and README

qemu/tests/cfg/hotplug_mem.cfg, qemu/tests/hotplug_mem.py
=> tp-qemu: add memory hotplug/unplug tests

qemu/tests/cfg/driver_load.cfg, qemu/tests/driver_load.py
Update driver_load and add more scenerio
Signed-off-by: Suqin Huang
=> Update driver_load and add more scenerio

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host_with_stress.py
=> qemu.tests: Add new case migration_multi_host_with_stress

qemu/tests/cfg/multi_host.cfg
Do nic driver unload/load for migration.
ID: 1266315 1266316
=> qemu/tests/cfg: Add new scenario for multi_host

qemu/tests/win_virtio_update.py
after nic driver installed default route maybe change, so
try to login guest via all nic to avoid login timeout issue.
=> try to login guest via all nics after driver installed

qemu/tests/cfg/qmp_command.cfg
=> qemu.test.cfg.pmemsave:change it to correct command

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host.py
1. Update some variants
2. Remove the duplicated config
=> qemu/tests/cfg: Update multi_host.cfg

qemu/tests/cfg/set_link.cfg
=> set test_timeout from 1000 to 2000

qemu/tests/balloon_check.py
=> balloon_check: fix syntax issue

qemu/tests/migration_with_dst_problem.py, qemu/tests/sr_iov_irqbalance.py
=> Use API function to get service status in VM

qemu/tests/cfg/cluster_size_check.cfg
=> cluster_size_check: no need start vm for this case.

qemu/tests/cfg/device_bit_check.cfg
=> device_bit_check: no need add cdrom for this case.

qemu/tests/format_disk.py
=> qemu.tests.format_disk: make parameters safer for windows guests

qemu/cfg/host-kernel/Host_RHEL/5/7.cfg, qemu/cfg/host-kernel/Host_RHEL/5/8.cfg, qemu/cfg/host-kernel/Host_RHEL/5/9.cfg, qemu/cfg/host-kernel/Host_RHEL/7/2.cfg, qemu/cfg/host-kernel/host-kernel-check.cfg
need to update host-kernel in tp-qemu, which is useful when test with autotest framework
=> Update cfg in host-kernel

qemu/tests/rh_kernel_update.py
Because not all RHEL distro use grub as its bootloader, those grub
related params no longer made sense, so change their name to boot_xxx.
ID: 1246408
=> qemu.tests.rh_kernel_update: rename 'grub' related params

qemu/tests/floppy.py
=> qemu/tests: Update multi host part for floppy.py

qemu/tests/cfg/driver_load_stress.cfg, qemu/tests/driver_in_use.py
=> Add scenerio to disable/enable viostor/vioscsi driver

generic/tests/cfg/iozone_windows.cfg, generic/tests/iozone_windows.py
iozone can be run in system disk currently,
add disk support as well, need to create the partition first.
ID: 1303003
=> Improve iozone_windows to support disk test

qemu/tests/cfg/cluster_size_check.cfg, qemu/tests/cluster_size_check.py
1. test some invalid cluster_size
2. fix AttributeError: 'QemuImg' object has no attribute 'params'
=> qemu.tests: Add negative test case for cluster_size_check

qemu/tests/cfg/qmp_command.cfg
=> qemu.test.cfg: add powerpc parameter for device mouse

qemu/tests/qemu_disk_img.py
=> tp-qemu: quick fix miss import data_dir module error

qemu/tests/cfg/balloon_in_use.cfg, qemu/tests/driver_in_use.py
Based on: autotest/tp-qemu#463
id: 1230672 1231010 1231013 1231655
=> tp-qemu: Add some subtests when balloon driver in use.

qemu/tests/balloon_hotplug.py, qemu/tests/cfg/balloon_hotplug.cfg
=> tp-qemu: Add case for balloon hotplug.

qemu/tests/balloon_stress.py, qemu/tests/cfg/balloon_in_use.cfg
=> tp-qemu: some updates about balloon_stress.

qemu/tests/cfg/driver_load_stress.cfg
=> tp-qemu: driver_load_stress: Add scenario for netkvm and balloon.

qemu/tests/cfg/fio_windows.cfg, qemu/tests/cfg/multi_host.cfg, qemu/tests/fio_windows.py
=> qemu/test: Add fio test for multi host migration

qemu/deps/spice/build_install.py
Adding support for building spice-server to the build_install.py
script.
=> qemu.spice: Adding spice-server to build_install.py

generic/tests/mac_change.py
=> tp-qemu: Fix serial session ShellTimeout issue

generic/tests/cfg/netperf.cfg
=> generic.test: update netperf download link and configuration

qemu/tests/cfg/multi_disk_random_hotplug.cfg, qemu/tests/multi_disk_random_hotplug.py
=> tp-qemu: update unplug disk test steps

qemu/tests/cfg/qmp_basic.cfg, qemu/tests/cfg/qmp_basic_rhel6.cfg
=> tp-qemu: qmp_basic: set host filter for the case.

qemu/tests/cdrom.py, qemu/tests/cfg/multi_host.cfg
Update serial number for Multihost()
=> qemu/tests/cdrom.py: Update some codes for multi host migration

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host_downtime_and_speed.py
1. Add new scenario that set_downtime before migration
2. Add check downtime steps after migration
3. Remove the duplicate methods
ID: 1266330 1266331 1266332
=> qemu/tests: Update migration_multi_host_downtime_and_speed.py

qemu/tests/cfg/hotplug_mem.cfg
=> hotplug_memory: update sub-test name

generic/tests/netperf.py
ID: 1315548 1315167
Signed-off-by: Maosheng Zhang <mazhang@redhat.com>
=> tp-qemu: fix ppc platform no io_exits and irq_injections issue

qemu/tests/cfg/readonly_disk.cfg
1. Add werror/rerror to readonly data disk
ID:1321735
=> Add werror/rerror to block drive

qemu/tests/balloon_service.py, qemu/tests/cfg/balloon_service.cfg
=> tp-qemu: Add a new case for balloon service testing.

qemu/tests/cfg/driver_load_stress.cfg
=> Update iozone_cmd of driver_load_stress

qemu/deps/win_driver_install/dpinst.xml, qemu/deps/win_driver_install/win_driver_install.py
=> tp-qemu: Add driver_install script for windows guest.

qemu/tests/balloon_check.py
=> tp-qemu: update balloon test boundary value

generic/tests/netperf.py
ID: 1321717
Signed-off-by: Maosheng Zhang <mazhang@redhat.com>
=> tp-qemu: Update netperf.py to support avocado

generic/tests/cfg/module_probe.cfg, generic/tests/module_probe.py
=> module_probe: fix moudle kvm_intel/kvm_amd cannot be unloaded

generic/tests/cfg/block_hotplug.cfg, qemu/tests/block_hotplug.py
=> qemu/tests/: Add new case for block hotplug

qemu/tests/set_link.py
Check the guest connective through ping host from guest instead of ping guest from host.
=> set_link: Check the guest connective via ping host from guest

qemu/tests/cfg/multi_disk.cfg
=> qemu/tests/cfg/: Add lost config of ppc64le in multi_disk.cfg

qemu/tests/cfg/multi_nics_hotplug.cfg
=> qemu/tests/cfg: Some nics model not support for power

generic/tests/module_probe.py
=> tp-qemu: module_probe.py: Update module name under avocado.

generic/tests/cfg/netperf.cfg
ID: 1326204
Signed-off-by: Maosheng Zhang <mazhang@redhat.com>
=> tp-qemu: update netperf test configuration

qemu/tests/block_stream_reboot.py
Add random sleep time to wait for sub-test begin to preform
ID: 1329490
=> block_stream_reboot: add random sleep time

qemu/tests/cfg/disable_win_update.cfg, qemu/tests/disable_win_update.py
1. add step to check windows service status.
2. update the way to disable windows service.
id: 1328698
=> tp-qemu: disable_win_update.py: some updates for this case.

qemu/tests/cfg/check_block_size.cfg, qemu/tests/check_block_size.py
=> qemu/tests/check_block_size: change the mothod of disk identification

qemu/tests/cfg/single_driver_install.cfg, qemu/tests/single_driver_install.py
1. Install driver (Install / Upgrade / Downgrade).
2. Uninstall driver.
=> tp-qemu: Add case for windows single driver install.

qemu/tests/device_option_check.py
Depends on: https://github.com/avocado-framework/avocado-vt/pull/479
ID: 1327925
=> qemu.tests.device_option_check: fix the issue of finding property from qtree

qemu/tests/cfg/single_driver_install.cfg
=> small syntax error in the config file

qemu/tests/pktgen.py
=> qemu.tests.pktgen: fix syntax issue

qemu/tests/cfg/multi_disk_random_hotplug.cfg
remove 'spapr_vscsi' since it does not support hotplugging
ID: 1327926
=> qemu.tests.multi_disk_random_hotplug: remove spapr_vscsi

qemu/tests/balloon_stress.py
=> tp-qemu: balloon_stress.py: fix a syntax error.

qemu/tests/migration_after_nichotplug.py
1. re-get session after re-enabling the primary link.
2. fix a typo of session.
id: 1128017
=> tp-qemu: migration_after_nichotplug: some updates about session.

qemu/tests/balloon_stress.py
=> balloon_stress: fix syntax error

qemu/tests/cfg/driver_load.cfg, qemu/tests/driver_load.py
=>  driver_load: fix loading and unloading wrong modules

qemu/tests/cfg/watchdog.cfg, qemu/tests/watchdog.py
=> watchdog: don't boot up VM for 'check_watchdog_support'

qemu/tests/block_resize.py, qemu/tests/cfg/block_resize.cfg
1. add step description
2. add driver verifiver
3. update disk format
=> Update block_resize test

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
depend on https://github.com/avocado-framework/avocado-vt/pull/496
id:1328001 1327995 1327990
=> add sync-delimited set-user-password get-vcpus set-vcpus cmd support

qemu/tests/cfg/balloon_in_use.cfg, qemu/tests/cfg/driver_load_stress.cfg, qemu/tests/cfg/netkvm_in_use.cfg, qemu/tests/driver_in_use.py
suppress_exception always be True currently
=> Fix error of suppress_exception value

qemu/tests/cfg/single_driver_install.cfg, qemu/tests/single_driver_install.py
1. Remove scenarios "downgrade" and "uninstall".
This case won't upgrade / install driver after
downgrade / uninstall, which is not acceptable.
Will write new case to cover those scenarios.
2. rename variant "uninstall".
3. remove some unreasonable cfg.
=> tp-qemu: single_driver_install: remove scenarios "downgrade" and "uninstall"

generic/tests/ethtool.py
When set offload status via ethtool, the operation may takes effect for more than one option, like:
```
$ ethtool -k eth0
Offload parameters for eth0:
...
scatter-gather: off
tcp-segmentation-offload: off
udp-fragmentation-offload: off
generic-segmentation-offload: off
...
$ ethtool -K eth0 sg on
$ ethtool -k eth0
Offload parameters for eth0:
..
scatter-gather: on
tcp-segmentation-offload: on
udp-fragmentation-offload: on
generic-segmentation-offload: on
...
```
hence, if want to both set `gso: off` and `sg: on`, it is better to preform this through the same command, like:
```
$ ethtool -k eth0
Offload parameters for eth0:
...
scatter-gather: off
tcp-segmentation-offload: off
udp-fragmentation-offload: off
generic-segmentation-offload: off
...
$ ethtool -K eth0 gso off sg on
$ ethtool -k …
```
=> generic.tests.ethtool: set offload status atomically

qemu/tests/cfg/driver_load.cfg
Signed-off-by: Lin Ma <lma@suse.com>
=> fix modprobe typo of virtio-scsi in in driver_load

qemu/tests/win_virtio_update.py
=> win_virtio_update: fix typo which affects test result

qemu/deps/win_driver_install/win_driver_install.py, qemu/tests/cfg/single_driver_install.cfg, qemu/tests/single_driver_install.py
output is blank line if the driver uninstalled when
get current driver version.
id: 1335030
=> Some updates for windows driver installation.

qemu/tests/cfg/live_snapshot_basic.cfg, qemu/tests/live_snapshot_basic.py
id: 1321820 1321830
Based on:
https://github.com/avocado-framework/avocado-vt/pull/448
=> Add new case for basic live snapshot tests.

qemu/tests/cfg/virtio_storage_in_use.cfg
Add scenerios for virstor/vioscsi test
e.g run iozone in system disk/data disk before/during/after sub tests (shutdown, reboot)
=> Add more scenerios for viostor/vioscsi test

qemu/tests/live_snapshot.py
=> live_snapshot: live_snapshot() interface is changed in qemu_monitor.py, update cases to match it.

qemu/tests/change_media.py
=> Add error message when "change" is first executed

generic/tests/shutdown.py, qemu/tests/client_guest_shutdown.py, qemu/tests/qemu_no_shutdown.py
id: 1342991
Based on: https://github.com/avocado-framework/avocado-vt/pull/570
=> system_powerdown: Using interface in framework to cover event check.

qemu/tests/balloon_service.py
=> balloon_service: fix a logical error of blnsvr.exe status.

qemu/tests/cfg/drive_mirror.cfg, qemu/tests/cfg/drive_mirror_negtive_tests.cfg, qemu/tests/drive_mirror.py, qemu/tests/drive_mirror_cancel.py, qemu/tests/drive_mirror_complete.py
Update drive_mirror test cases
Signed-off-by: QianqianZhu qizhu@redhat.com
Based on:
avocado-framework/avocado-vt#535
=> Update drive_mirror test cases

qemu/tests/cfg/qmp_command.cfg
=> qmp_command: add command "query-pci".

qemu/tests/cfg/qmp_command.cfg
=> qmp_command: add command "query-events", "device-list-properties" and "query-command-line-options".

qemu/tests/cfg/hotplug_mem_repeat.cfg, qemu/tests/hotplug_mem_repeat.py
This case can't be test with latest rhel guest, it block by kernel bug 1314306
=> Add hotplug/unplug memory in loop test

qemu/tests/hotplug_mem_repeat.py
There's no attribute TestFailed.
=> hotplug_mem_repeat: fix error.TestFailed

qemu/tests/cfg/rh_kernel_update.cfg
=> resolve latest kernel installation dependency problems of RHEL7.3

qemu/tests/cfg/drive_mirror_negtive_tests.cfg
Remove the duplicate variant and modified commands.
ID: 1263067
=> drive_mirror_negtive_tests: remove the duplicate variant and modified commands

qemu/tests/cfg/nic_hotplug.cfg
Modified param `find_pci_cmd` in order to get the right list.
ID: 1330848
=> nic_hotplug: modified param find_pci_cmd in order to get the right list

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent_snapshot.py
1. Update case steps.
2. add windows support.
id: 1321832
Based on: https://github.com/autotest/tp-qemu/pull/592
https://github.com/avocado-framework/avocado-vt/pull/448
=> tp-qemu: qemu_guest_agent_snapshot.py: Update case steps.

qemu/tests/cfg/win_virtio_driver_update_test.cfg, qemu/tests/win_virtio_driver_update_test.py
Include:
1. uninstall and install driver.
2. downgrade and upgrade driver.
id: 1231103 1231073 1231066 1231047
=> tp-qemu: Add new case for windows virtio driver basic testing.

qemu/tests/cgroup.py
=> cgroup: close the session in finally 

qemu/tests/cfg/qmp_event_notification.cfg
=> qmp_event_notification: add event check for ram and disk suspend.

qemu/tests/cfg/hotplug_mem.cfg
=> add hugepage test for ppc which default hugepage size is 16M

generic/tests/cfg/iozone_windows.cfg, generic/tests/iozone_windows.py, qemu/tests/balloon_service.py, qemu/tests/balloon_stress.py, qemu/tests/block_resize.py, qemu/tests/cfg/balloon_service.cfg, qemu/tests/cfg/balloon_stress.cfg, qemu/tests/cfg/block_resize.cfg, qemu/tests/driver_in_use.py
It has been descriped in framework
=> Remove verifier log.info from test

qemu/tests/cfg/hotplug_mem.cfg
=> qemu.tests.cfg: update memory hotplug with stress tests cfg

qemu/tests/cfg/viorng_in_use.cfg, qemu/tests/driver_in_use.py, qemu/tests/rng_bat.py
run random test before/during/after stop_contion/reboot/shutdown
=> Add viorng driver test scenerios

qemu/tests/qemu_guest_agent_snapshot.py
=>  qemu_guest_agent_snapshot: update class name which has been changed in live_snapshot_basic.

qemu/deps/win_driver_install/win_driver_install.py, qemu/tests/single_driver_install.py
1. single_driver_install.py: Improve exception handle.
2. win_driver_install.py: add "append" mode for driver_install.log.
id: 1360200 1358673
=> Update windows driver install related scripts.

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host_with_kdump.py
=> Ping-pong live migratioin until guest kdump completes

qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot_stress.py
id: 1321833 1321838
Based on:
https://github.com/autotest/tp-qemu/pull/701
https://github.com/avocado-framework/avocado-vt/pull/628
=> qemu.tests: Add new case of live snapshot under stress.

qemu/tests/cfg/virtio_port_hotplug.cfg, qemu/tests/virtio_port_hotplug.py
=> tp-qemu: add virtio port hotplug/unplug tests

qemu/tests/cfg/live_snapshot.cfg
=> qemu.tests: Add new case of live snapshot with stop_cont.

qemu/tests/pci_hotplug.py, qemu/tests/pci_hotplug_check.py, qemu/tests/pci_hotunplug.py, qemu/tests/sr_iov_hotplug.py, qemu/tests/sr_iov_hotplug_negative.py
=> qemu/tests: Fix typo in output

qemu/tests/cfg/rng_hotplug.cfg, qemu/tests/rng_hotplug.py
Add rng device hotplug/unplug test
=> Add rng device hotplug/unplug test

qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot_negative_test.py
=> qemu.tests: Add new negative case for live snapshot with non-existed path.

qemu/tests/cfg/qemu_img.cfg, qemu/tests/qemu_img.py
Add cases for upgrading and downgrading qcow2 version of image
=> Add cases for subcommand amend of qemu-img

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/cfg/qemu_img.cfg, qemu/tests/qemu_disk_img.py, qemu/tests/qemu_disk_img_convert.py, qemu/tests/qemu_img.py
1. Add cases for cluster size/sparse size/cache mode/show progress
2. Add function verify_info() to check result of convert operation
=> Add cases for subcommand convert of qemu-img

qemu/tests/rng_bat.py
=> rng_bat: Fix wrong doc and enhance error message

qemu/tests/cfg/qmp_event_notification.cfg, qemu/tests/qmp_event_notification.py
id: 1343300
Based on: https://github.com/avocado-framework/avocado-vt/pull/667
=> qemu.tests.qmp_event_notification: add "system_wakeup" event check.

qemu/tests/cfg/win_virtio_driver_update_test.cfg, qemu/tests/win_virtio_driver_update_test.py
1. Add test before/after/during driver update
2. Add viorng load/unload test
=> Add more scenerios to win virtio driver test

qemu/tests/win_virtio_update.py
=> win_virtio_update: cleanup

qemu/tests/cfg/pci_hotplug.cfg, qemu/tests/pci_hotplug.py
=> update pci_hotplug cfg to contain the serial opton when hotplug block

qemu/tests/block_copy.py, qemu/tests/cfg/drive_mirror.cfg
Add pause&resume block job test case for drive_mirror.
Signed-off-by: Qianqian Zhu qizhu@redhat.com
id: 1360154
=> Add pause&resume block job test case for drive_mirror.

qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot_transaction.py
id: 1321839
Based on: https://github.com/autotest/tp-qemu/pull/701
https://github.com/avocado-framework/avocado-vt/pull/633
=> qemu.tests: Add case for successful live snapshot transaction.

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
depends on https://github.com/avocado-framework/avocado-vt/pull/558
ID:1327985 1327988 1327992 1327998
=> update qga cmd: set-time, get-time, network-interface, fstrim

qemu/tests/cfg/block_stream.cfg
=> qemu.tests.block_stream_stress: Add scenario for data plane.

qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot.py
=> qemu.tests: Add new case of live snapshot during installation.

qemu/tests/block_copy.py, qemu/tests/cfg/block_stream.cfg
And add more speeds test scenarios for block_stream.
id: 1370974
=> qemu.tests.block_copy: Update set_speed() to make it support more speeds.

qemu/tests/cfg/block_stream.cfg, qemu/tests/cfg/multi_host.cfg, qemu/tests/cfg/slof_dataplane_boot.cfg
=> qemu.tests: Add data-plane support for virtio-scsi since RHEL.7.3.

qemu/tests/block_copy.py, qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_snapshot.py, qemu/tests/live_snapshot_runtime.py
And remove duplicated code.
id: 1321835
=> qemu.tests: Re-write live snapshot reboot case with existing class and func.

qemu/tests/virtio_console.py
=> virtio_console: Use the API class of avocado-vt

qemu/tests/win_heavyload.py
1. Make it work under both autotest-framework and avocado-framework
2. in migration test, does not stop heavyload on src host
=> qemu.test: win_heavyload

generic/tests/multi_queues_test.py
=> multi_queues_test.with_netperf.cpu_affinity: modify the method of irq static to support  ppc64

qemu/tests/single_driver_install.py
=> qemu.tests: small fix for log file path in host

qemu/tests/pktgen.py
=> Fix the problem that can't get return value from echo %OS% cmd in pktgen test case

qemu/tests/cfg/rh_kernel_update.cfg, qemu/tests/rh_kernel_update.py
=> qemu.tests.rh_kernel_update: upgrade package qemu-guest-agent

qemu/tests/cfg/single_driver_install.cfg
=> qemu.tests.single_driver_install: Update virtio serial device name for different hosts.

generic/tests/cfg/fillup_disk.cfg
=> generic.tests.fillup_disk: update dir path with single slash.

qemu/tests/cfg/single_driver_install.cfg
id: 1231045 1231013 1231010 1230672 1231655
=> qemu.tests.single_driver_install: fix a typo of guest name for win8-32.1 .

qemu/tests/cfg/driver_load.cfg, qemu/tests/cfg/driver_load_stress.cfg, qemu/tests/cfg/single_driver_install.cfg
=> tests.cfg: add q35 support for windows driver related tests

qemu/tests/cfg/live_snapshot_chain.cfg, qemu/tests/live_snapshot_chain.py
1. Add snapshots to 64 for scalability test.
2. Verify sn64 works fine.
3. Add step "system_reset" after snapshot creation finish.
id: 1108413
=> qemu.tests.live_snapshot_chain: Update long_chain scenario.

qemu/tests/cfg/multi_disk.cfg
=> multi_disk.all_drive_format_types: modified drives type for pseries variant

qemu/tests/cfg/rng_hotplug.cfg, qemu/tests/rng_hotplug.py
hotplug/unplug rng devices 500 times
and run random.exe before/after hotplug 
=> hotplug rng devices in loop

qemu/tests/cfg/win_virtio_driver_update_test.cfg
=> qemu.tests.win_virtio_driver_update_test: add missing param "target_process".

qemu/tests/cfg/win_virtio_driver_update_test.cfg
=> qemu.tests.win_virtio_driver_update_test: fix a typo of guest name for win8-32.1 .

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> qemu.test: check_memory_leak on windows guest after run command "guest-info" many times.

qemu/tests/cfg/migrate.cfg, qemu/tests/migration_after_vm_paused.py
=> tp-qemu: add migration_after_vm_paused test

qemu/tests/cdrom.py, qemu/tests/cpuflags.py, qemu/tests/floppy.py, qemu/tests/migration_multi_host.py, qemu/tests/migration_multi_host_cancel.py, qemu/tests/migration_multi_host_downtime_and_speed.py, qemu/tests/migration_multi_host_firewall_block.py, qemu/tests/migration_multi_host_ping_pong.py, qemu/tests/migration_multi_host_timedrift.py, qemu/tests/migration_multi_host_with_file_transfer.py, qemu/tests/migration_multi_host_with_reboot.py, qemu/tests/migration_multi_host_with_speed_measurement.py, qemu/tests/migration_multi_host_with_stress.py, qemu/tests/virtio_console.py
=> qemu.test: migration codes updated in framework, so update import statement

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/qemu_disk_img.py
Support to sync data in windows guest.
ID: 1390069
=> qemu_disk_img: Add sync in windows

qemu/tests/cfg/driver_load_stress.cfg
block contain viostor and vioscsi
update with_block to with_viostor is more reasonable
=> Update with_block to with_viostor

qemu/tests/rng_bat.py
=> Update X to winutils_letter of driver_check_cmd

generic/tests/cfg/downgrade_qcow2_version.cfg, generic/tests/downgrade_qcow2_version.py
qemu.tests: Downgrade the image version when it is QCOW v3 
ID: 1388721
=> qemu.tests: Downgrade the image version when it is QCOW v3 

qemu/tests/cfg/multi_host.cfg, qemu/tests/migration_multi_host_with_xbzrle.py
=> qemu.test: multihost migration with xbzrle

generic/tests/cfg/jumbo.cfg, generic/tests/jumbo.py
generic.tests.jumbo: update test steps.
1.  update test steps.
2. delete windows guest test for e1000 Nic.
ID:1361026
Signed-off-by: Wei Liao weliao@redhat.com
=> generic.tests.jumbo: update test steps.

qemu/tests/cfg/netkvm_in_use.cfg
=> qemu.tests.netkvm_in_use: Update some commands for checking pci.

qemu/tests/cfg/rh_kernel_update.cfg
Signed-off-by: Meng Yang meyang@redhat.com
ID: 1379203
=> need higher version package kmod to update kernel

qemu/tests/multi_disk_random_hotplug.py
ID: 1389155
Signed-off-by: Xu Tian xutian@redhat.com
=> qemu.tests.multi_disk_random_hotplug: fix syntax

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/cfg/qemu_img.cfg, qemu/tests/qemu_img.py
Add cases for cache mode and show progress
ID: 1361861, 1362614
=> Add cases for subcommand rebase of qemu-img

qemu/tests/migration_multi_host_with_kdump.py
1. add function "start_worker_guest_kdump"
2. add function "check_worker_kdump"
=> qemu.test: migration_multi_host_with_kdump

qemu/deps/windows_ga_install/get_package.py, qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> add windows guest agent installation method

qemu/tests/cfg/rng_stress.cfg
Signed-off-by: Suqin Huang shuang@redhat.com
=> Add rng-egd backend to rng1

qemu/tests/balloon_check.py, qemu/tests/balloon_service.py, qemu/tests/cfg/balloon_illegal.cfg, qemu/tests/cfg/balloon_service.cfg
qemu.tests.balloon_check:
1.remove illegal balloon value setting limitation.
2.adjust code for balloon illegal test.
qemu.tests.cfg.balloon_check:
1.add variants "balloon_illegal" for balloon illegal test.
2.add balloon_illegal test for enlarge operation
=> Add balloon_illegal test in balloon_check

qemu/tests/balloon_stress.py
qemu.tests.balloon_stress:
1.set default maximum balloon value--vm maximum mem
2.set memory balloon randomly, not constant value.
Signed-off-by: Aihua Liang<aliang@redhat.com>
=> balloon_stress:default maximum balloon value correct and test logic optmize

qemu/tests/cfg/rng_bat.cfg, qemu/tests/rng_bat.py
it has been supported upstream
=> Remove set_winutils_letter from rng_bat

qemu/tests/balloon_stress.py
balloon_stress:
1.import random
2.define object balloon_test
Signed-off-by:Aihua Liang<aliang@redhat.com>
ID:1388321
=> qemu.tests.balloon_stress:add code import and object define

qemu/tests/cfg/driver_load_stress.cfg, qemu/tests/driver_in_use.py, qemu/tests/driver_load.py
Load/unload viorng driver befor/during/after rng_bat test
Signed-off-by: Suqin Huang shuang@redhat.com
=> Add virtio-win viorng driver load/unload test

qemu/tests/cfg/single_driver_install.cfg, qemu/tests/cfg/win_virtio_driver_update_test.cfg
1. Win2008r2 is missing of param "guest_alias".
2. Fix the error of Win2008 guest_name.
3. Add Win2016 guest.
id: 1397835
=> qemu.tests: Update param "guest_alias" in configurations.

qemu/tests/live_snapshot_runtime.py
Do live snapshot during the pre-action, and need wait for pre-action complete when snapshot finished.
id: 1391925
=> qemu/tests/live_snapshot_runtime.py: over-write action_when_start().

qemu/tests/rh_kernel_update.py
Fix typos and remove the unused variable
=> rh_kernel_update: clean up

qemu/tests/cfg/hotplug_mem.cfg, qemu/tests/hotplug_mem.py, qemu/tests/stop_continue.py
cleanup code execute logical and made a small update to ensure VM is paused status when execute test case "hotplug_memory.during.pause_vm.hotplug.backend_file.2M_hugepage.policy_bind.two".
=> Update test case to make memory hotplug/unplug when VM is paused

generic/tests/cfg/boot_vm_in_hugepage.cfg
=> generic.tests: add case boot vm memory in hugepage

qemu/tests/block_stream_drop_backingfile.py
Fix a typo, verfiy -> verify; add a preposition 'with'.
=> Fix a typo and a syntax error

generic/tests/cfg/boot_savevm.cfg, generic/tests/cfg/unattended_install.cfg, multi_host_migration/tests/cfg/multi_host.cfg, qemu/tests/cfg/floppy_test.cfg, qemu/tests/cfg/readonly_floppy.cfg
=> floppy: disable floppy test for q35 and pseries machine

generic/tests/yum_update.py, qemu/tests/cfg/live_snapshot_chain.cfg
=> Disable gpgcheck when execute "yum" cmd.

qemu/tests/single_driver_install.py
"Denying new connections due to the limit on number of connections" error
if don't close the session
=> Close un-used session

qemu/cfg/host-kernel/Host_RHEL/6/8.cfg
=> qemu.cfg.host-kernel: Add 6.8 host kernel.

qemu/tests/cfg/multi_disk.cfg
ID:1400385
Signed-off-by: Jing Zhao <jinzhao@redhat.com>
=> Added q35 machine type on multi_disk config file

qemu/tests/cfg/drive_mirror.cfg
=> drive_mirror: setup iscsi target on localhost

qemu/cfg/host-kernel/host-kernel-check.cfg
=> host-kernel-check.cfg: Add RHEL.6.8 host kernel check

multi_host_migration/tests/cfg/multi_host.cfg, multi_host_migration/tests/migration_multi_host_auto_converge.py
=> qemu.test: add test "migration_multi_host_auto_converge"

qemu/tests/cfg/qemu_disk_img_compare.cfg, qemu/tests/qemu_disk_img_convert.py
Compare images after convert qcow2 format to raw format
ID: 1395550
=> qemu.tests: Add case for qemu-img compare

qemu/tests/cfg/rh_kernel_update.cfg, qemu/tests/rh_kernel_update.py
Make kernel build name configurable.
ID: 1402347
=> rh_kernel_update: make kernel build name configurable

qemu/tests/balloon_service.py, qemu/tests/cfg/balloon_service.cfg
1. Add linux guest into the guest-stats-polling-interval test.
2. Add large polling interval test
ID: 1373066
=> balloon_service: Add linux guest into the test

qemu/tests/cfg/nvdimm.cfg, qemu/tests/nvdimm.py
qemu.tests: add case for nvdimm basic test
ID: 1400770
Depends on: https://github.com/avocado-framework/avocado-vt/pull/813
=> qemu.tests: add case for nvdimm

qemu/tests/cfg/slof_device_tree.cfg, qemu/tests/slof_device_tree.py
Add new test case for SLOF feature, check guest device tree information, compare them with the expected value.
ID: 1324342
Signed-off-by: Qunfang Zhang qzhang@redhat.com
=> tp-qemu: Add new test case "slof_device_tree" for SLOF feature (ppc only)

qemu/tests/cfg/enforce_quit.cfg
=> qemu.test: enforce_quit.unknow_flag: disable this case on RHEL.6 host

qemu/tests/balloon_check.py
=> balloon_check: close session in the end of test

qemu/tests/numa_stress.py
Get the speed of "dd if=/dev/urandom of=tmpfs" on host, in order to get appropriate timeout.
ID: 1404125
=> numa.numa_stress: Get tmpfs_write_speed of the host before test

qemu/tests/cfg/nvdimm.cfg, qemu/tests/nvdimm.py
Add case for nvdimm backed by host emulated device
ID: 1400771
=> qemu.tests: Add case for nvdimm backed by host emulated device

qemu/tests/cfg/rng_driver_load.cfg, qemu/tests/rng_driver_negative.py
1. repeat load/unload 10 times
2. unload during random read
Signed-off-by: Suqin Huang shuang@redhat.com
=> Add rng driver load test

qemu/tests/cfg/rng_read_longtime.cfg, qemu/tests/rng_bat.py
Read data from /dev/random 10 hours
id: 1377564
=> Read from guest long time

multi_host_migration/tests/migration_multi_host_with_reboot.py
=> qemu.test: fix random time issue in migration_multi_host_with_reboot

qemu/tests/balloon_boot_in_pause.py, qemu/tests/cfg/balloon_boot_in_pause.cfg
Add case balloon_boot_in_pause with corresponding code to make ballooning memory when guest start with pause status come true
ID: 1373058
=> Add code to balloon guest memory when guest start with paused status

qemu/tests/numa_consistency.py
Signed-off-by: Miriam Deng mdeng@redhat.com
ID: 1404109
=> update wrong page size of test case numa_consistency 

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/qemu_disk_img.py
Update the letter of winutils to WIN_UTILS in cmd
ID: 1395550
=> qemu_disk_img: Update the letter of winutils to WIN_UTILS in cmd

qemu/tests/cfg/numa_opts.cfg
Signed-off-by: Miriam Deng mdeng@redhat.com
ID: 1395524
=> update numa configration for multiple node tests on ppc64le platform 

qemu/cfg/host-kernel/Host_RHEL/7/3.cfg, qemu/cfg/host-kernel/host-kernel-check.cfg
=> host-kernel: Add RHEL.7.3 host kernel.

qemu/tests/floppy.py
=> for "aexpect", make it work under both autotest-framework and avocado-framework

qemu/tests/cfg/drive_mirror_negative_tests.cfg
=> drive_mirror_negative_tests: fix typo

qemu/tests/cfg/win_video_play.cfg, qemu/tests/win_video_play.py
Play video with wmplayer if it's installed default,
else install kmplayer and run video
id:1403637
=> Add video play for windows guest

qemu/tests/balloon_check.py, qemu/tests/balloon_stress.py, qemu/tests/cfg/balloon_stress.cfg
video play is created as a separate case,
run it background in balloon stress test
ID:1130458
=> Update video play code in balloon_stress

generic/tests/iozone_windows.py, qemu/tests/cfg/ioeventfd.cfg
generic.tests.iozone_windows:
1.set a default value for "disk_letter"
2.modify iozone_cmd for ioeventfd test
ID:1412895
=> iozone_windows:update iozone_cmd for ioeventfd test

qemu/tests/balloon_check.py
=> Add env params

qemu/tests/hotplug_mem.py
=> hotplug_mem: Fix undefined name 'exceptions'

qemu/tests/win_video_play.py
=> float is requested for time.sleep

qemu/tests/cfg/win_heavyload.cfg
=> Remove config_cmd from win_heavyload test

qemu/tests/blk_stream.py, qemu/tests/block_copy.py, qemu/tests/drive_mirror.py
Add wait for and after job finished function, which are common part for all block job types.
=> block_copy: Add wait for and after job finished function.

qemu/tests/rh_qemu_iotests.py
Skip to run configure in source code when test with qemu-kvm
ID: 1426893
=> rh_qemu_iotests: update case steps when test  with qemu-kvm

qemu/tests/qemu_disk_img_snapshot.py
No matter change_md5 or change_md5 == md5 will raise error.
So in my opinion, there should be "or" instead of "and".
=> fix qemu_disk_img_snapshot

qemu/tests/qmp_command.py
Hmp command return the PC value in hexadecimal.
Qmp command return the PC value in complement.
This patch transform the value from it's hexadecimal to it's complement.
=> fix qmp_command.qmp_query-cpus

qemu/tests/cfg/cpu_device_hotplug.cfg, qemu/tests/cpu_device_hotplug.py
Add vcpu device baed hotplug/unplug tests with different
configurations.
Signed-off-by: Nageswara R Sastry rnsastry@linux.vnet.ibm.com
=> Add vCPU device based hotplug/unplug test cases

qemu/tests/stop_continue.py
Excpetion raise in finally block overwrite exception occur
in key steps. Make it raise root-cause if test is failed.
ID: 1426510
=> qemu.stop_continue: raise root-cause if test is failed

qemu/tests/cgroup.py
In qemu1.5,we get the information like "idTestR2: removable=1 locked=0..."
In new version,we get the information like "idTestR2 (#block303): /dev/sda"
The most important thing is weather "idTestR2" in the information.
The expression ("%s: " % name) won't work for the new version.
This modify is compitable for old version.
=> fix cgroup.devices_access

qemu/tests/block_copy.py, qemu/tests/cfg/live_backup.cfg, qemu/tests/live_backup.py, qemu/tests/live_backup_base.py
1. Incremental live backup data consistency
2. Incremental live backup granularity
ID: 1398559, 1398557
Depends on: https://github.com/avocado-framework/avocado-vt/pull/800
=> live_backup.py: Add live backup test cases.

generic/tests/cfg/pxe_boot.cfg
Signe-off-by: Yanan Fu <yfu@redhat.com>
=> qemu.test.pxe_boot: extend pxe_timeout to 360s

multi_host_migration/tests/cfg/multi_host.cfg, multi_host_migration/tests/migration_multi_host_with_stress.py
login guest with "nic_index=1" when run sub test "driver_load"
ID: 1428306
=> qemu.test: Fix login timeout in migration_multi_host_with_module_reload

qemu/tests/balloon_check.py
qemu.tests.balloon_memory:
1.re-get guest memory after system's up
ID:1372564
=> balloon_check: get guest memory after system up

multi_host_migration/tests/cfg/multi_host.cfg
=> tp-qemu.test: migrate_multi_host.virtio_blk_data_plane

qemu/tests/set_link.py
Before send 'set link down command' into VM monitor, VM has a IP address. And, when pinging a host on your own subnet the sender will first send an ARP request for the MAC address of the associated IP address, so update acceptable packet loss ratio to 80%.
And, update test step to check connection between from host side to ensure test works stably.
ID: 1397690
=> qemu.tests: recorrect expect results of ping

qemu/tests/boot_from_device.py
=> qemu.tests.boot_from_device: fix value error

qemu/tests/win_video_play.py
del cmd doesn't work sometime, update to taskkill
=> Update video kill cmd

qemu/tests/balloon_check.py
After do balloon, wait until guest memory don't change anymore
ID: 1433192
=> qemu.tests.balloon_check: Wait until guest memory don't change after do balloon

qemu/tests/cfg/qemu_disk_img.cfg
restore image after testing instead of before testing
=> Restore image after testing

generic/tests/cfg/iozone_windows.cfg
=> generic.tests: iozone_windows, change timeout value from 7200 to 10800

qemu/tests/block_copy.py
=> block_copy: is_paused, check busy or not before count offset.

qemu/tests/timerdevice_clock_drift_with_ntp.py, qemu/tests/timerdevice_tscsync_longtime.py
=> Update and correct the path referred to time-warp-test.c

qemu/tests/cfg/drive_mirror.cfg, qemu/tests/cfg/drive_mirror_negative_tests.cfg, qemu/tests/cfg/physical_resources_check.cfg
=> Configuration Updates

qemu/tests/cfg/balloon_check.cfg, qemu/tests/cfg/ipi_x2apic.cfg, qemu/tests/cfg/seabios.cfg
The (3) patches are fixes to enable tp-qemu support for aarch64. More to come...
Thanks,
-Wei
=> tp-qemu fixes for aarch64

qemu/tests/balloon_stress.py, qemu/tests/cfg/balloon_stress.cfg, qemu/tests/win_video_play.py
=> Make sure video is running during memory balloon

qemu/tests/blk_stream.py, qemu/tests/block_stream_check_backingfile.py, qemu/tests/cfg/block_stream.cfg
Add test case for backing-file option, with either absolute or relative path.
id: 1368005
=> block_stream: Add test case for backing-file option.

qemu/tests/block_copy.py, qemu/tests/cfg/live_backup.cfg, qemu/tests/live_backup_base.py
1. Add data-plane scenario for live backup test.
2. Add time and space efficiency check for live backup.
id: 1400760, 1412532, 1412533
Signed-off-by: Qianqian Zhu qizhu@redhat.com
=> live_backup: Add test case for live backup.

qemu/tests/cfg/balloon_in_use.cfg
=> Update cfg of balloon_in_use

qemu/tests/cfg/qmp_command.cfg
update test case steps, add check the size of pmemsave
ID: 1346625 
Signed-off-by: jingzhao84 <jinzhao@redhat.com>
=> qmp_pmemsave: update test case steps, add check the size of pmemsave

qemu/tests/cfg/balloon_hotplug.cfg
change balloon hotplug/unplug repeat time from 5 to 100
ID:1479122
=> balloon_hotplug.cfg:change hotplug/unplug repeat time to 100

qemu/tests/cfg/nic_hotplug.cfg, qemu/tests/nic_hotplug.py
=> nic_hotplug: add a new case for hot plug a netdev with the id already in use

qemu/tests/cfg/rh_kernel_update.cfg
=> qemu.tests.rh_kernel_update: Add support for ARM

qemu/tests/virtio_console.py
Expect "None" value returned. A negative test.
id: 1468465
=> virtio_console: fix statement error in test_rw_host_offline_big_data()

qemu/tests/cfg/qmp_command.cfg, qemu/tests/qmp_command.py
=> qemu.tests.qmp_command:updated qmp_cpu test steps

qemu/tests/cfg/openflow_acl_test.cfg
=> openflow_acl_test: replace lynx with curl for checking website status 

generic/tests/cfg/boot_vm_in_hugepage.cfg
boot_vm_in_hugepage.1G_hugepage:
Update previous scenario configurations and move it in variant "2M_hugepage"
Add new case for 1G hugepage, boot, reboot, shutdown
ID: 1467177
=> boot_vm_in_hugepage.1G_hugepage: add new case for 1G hugepage, boot, reboot, shutdown

qemu/tests/flow_caches_stress_test.py
=> qemu.tests.flow_caches_stress_test: fixed escape character issue

.travis.yml, generic/tests/netperf.py, multi_host_migration/tests/migration_multi_host_auto_converge.py, multi_host_migration/tests/migration_multi_host_with_kdump.py, multi_host_migration/tests/migration_multi_host_with_xbzrle.py, qemu/deps/softlockup/heartbeat_slu.py, qemu/deps/spice/build_install.py, qemu/deps/spice/key_event_form.py, qemu/deps/win_driver_install/win_driver_install.py, qemu/deps/win_serial/VirtIoChannel_guest_recieve.py, qemu/deps/win_serial/serial-host-send.py, qemu/deps/win_serial/windows_support.py, qemu/tests/balloon_boot_in_pause.py, qemu/tests/balloon_service.py, qemu/tests/block_resize.py, qemu/tests/cpuid.py, qemu/tests/nvdimm.py, qemu/tests/pci_bridge_block_stress.py, qemu/tests/performance.py, qemu/tests/qemu_guest_agent.py, qemu/tests/qemu_guest_agent_snapshot.py, qemu/tests/qmp_command.py, qemu/tests/usb_storage.py, requirements-travis.txt
Update the CI scripts to use the latest inspektor 0.4.5.
=> Inspektor 0.4.5

README.rst
I forgot to make the change in the previous MR that
updated inspektor to 0.4.5, so let's make the
change now.
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
=> README.rst: Update inspekt command run by CI

qemu/tests/cfg/viorng_in_use.cfg, qemu/tests/driver_in_use.py
viorng_in_use was windows only case,add support for linux guests
ID：1475677
=> viorng_in_use: add support for linux guests

qemu/tests/multi_nics_verify.py
Add a missing param for echo command.
=> multi_nics_verify: fix bug

qemu/tests/virtio_port_login.py
=> virtio_port_login: hot fix

generic/tests/cfg/avocado_guest.cfg
Added tests from avocado-misc-tests repository to run inside guest
=> Added tests from avocado-misc-tests repository

generic/tests/cfg/avocado_guest.cfg
=> avocado_guest: Fix typo

qemu/tests/cfg/multi_nics_stress.cfg
change ${main_vm} to vm1
id: 1488074
=> multi_nics_stress:match vm name and netperf_client vm name

qemu/tests/blk_commit.py, qemu/tests/block_commit_stress.py, qemu/tests/block_stream_stress.py, qemu/tests/cfg/block_commit.cfg, qemu/tests/cfg/block_stream.cfg, qemu/tests/cfg/drive_mirror.cfg, qemu/tests/drive_mirror_stress.py
id: 1380234
Signed-off-by: Xiyue Wang xiywang@redhat.com
=> block_commit: Add test case 'Basic block commit test' to block commit

qemu/tests/cfg/openflow_acl_test.cfg
=> openflow_acl_test.xxx.telnet: Update main-vm name and passwd in cfg file

generic/tests/cfg/unattended_install.cfg
=> generic.tests: unattended_install.large_image: add config for RHEL7 and Windows

qemu/tests/win_heavyload.py
1. correct the test_timeout value. 
2. improve stop heavyload strategy
id: 1436547
=> qemu.tests.win_heavyload: Improve stop heavyload strategy

qemu/tests/cfg/qmp_command.cfg, qemu/tests/qmp_command.py
qmp_command: update check method of "query-name","query-uuid"and "human-monitor-command"
ID: 1346721
=> qmp_command: update check method of "query-name","query-uuid"and "human-monitor-command"

qemu/tests/nic_hotplug.py
ID: 1489717
Conflict will happen if we try to open a new serial console instance
while there is already a activated instance existed from the same console
object. Updated the serial console operation here to get rid of this kind
of conflicts.
=> nic_hotplug.py: fix serial console conflict

qemu/tests/cfg/nvdimm.cfg, qemu/tests/nvdimm.py
add new case: check nvdimm in guest backed by /dev/dax0.0
ID: 1467191
=> nvdimm.nvdimm_dax: add new case: check nvdimm in guest backed by /dev/dax0.0

qemu/tests/block_resize.py, qemu/tests/cfg/block_resize.cfg
block_resize: add support for data plane
Signed-off-by:Aihua Liang<aliang@redhat.com>
Bug id:1434266
=> block_resize: add support for data plane

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
It's not necessary for every qemu-ga case to run copy/install/query/start-service steps.
ID: 1487483
=> qemu_guest_agent: modify the qemu_guest_agent code structure for qemu-ga installation.

qemu/tests/cfg/rng_read_longtime.cfg
=> Update cmd of read_rng_cmd

generic/tests/netperf.py
1.Remove irq_injs and rpkt_per_irq since it's not supported any
more in kvm state
2.Since powerpc doest not support io_exits in kvm state, uses exits
for all platform.
3.Fail to control last numa node by numactl tool in some ppc machine,
so switch to node 0 instead.
id : 1472058
=> Keep consistent report with x86 for ppc platform.

qemu/tests/cfg/rng_host_guest_read.cfg, qemu/tests/rng_host_guest_read.py
Add a new case to support host and guest read random numbers at
the same time.
ID:1496724
=> rng_host_guest_read:Host and guest read data at the same time

qemu/tests/cfg/multi_nics_stress.cfg, qemu/tests/multi_nics_stress.py
add a pre_cmd to dhclient ip before netperf
id: 1489738
=> multi_nics_stress: add dhclient to get new added nics ip

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
1.add case for install/uninstall qemu-ga-xx.msi repeatly.
2.fix unreferenced params issue.
ID: 1487506
=> qemu_guest_agent: add case about install/uninstall qemu-ga package for windows guest.

qemu/tests/cfg/numa_opts.cfg
=> numa_opts: Update default memory size for 3 nodes test

generic/tests/cfg/lvm.cfg, generic/tests/ioquit.py, generic/tests/lvm.py
=> generic.tests: for test lvm, remount lv for sub test "fillup_disk" and "ioquit" after guest reboot/shutdown

generic/tests/cfg/ping.cfg, generic/tests/ping.py
improve ping from host to guest, add ping exceed/flood for guest to host, and fix some bugs in this patch.
id: 1479695 1479696
=> fix some bugs and add steps for ping.py 

qemu/tests/block_hotplug.py, qemu/tests/cfg/block_hotplug.cfg
Run iozone test on firstly and lastly time hotpluged data disk on windows guests.
Add test case reboot and shutdown guest after hotplug a data disk.
id: 1483853, 1488351，1488353
=> Add iozone/reboot/shutdown test after hotplug a data disk

qemu/tests/balloon_stress.py, qemu/tests/cfg/balloon_in_use.cfg, qemu/tests/cfg/balloon_stress.cfg, qemu/tests/cfg/driver_load_stress.cfg
balloon_stress: add support for Linux guest
ID: 1467183
=> balloon_stress: add support for Linux guest

qemu/tests/cfg/rng_driver_load.cfg, qemu/tests/driver_load.py
=> Stop service before load/unload rng driver

generic/deps/clock_getres/clock_getres.c, generic/tests/cfg/autotest_control.cfg, qemu/tests/cfg/nic_hotplug.cfg, qemu/tests/cfg/qmp_command.cfg, qemu/tests/cfg/smbios.cfg, qemu/tests/qmp_command.py
This addresses some issues related to s390x. I used RHEL.7.devel defined in https://github.com/avocado-framework/avocado-vt/pull/1200
=> Some s390x related tweaks and one bugfix

qemu/tests/cfg/sr_iov.cfg, qemu/tests/sr_iov_hotplug.py
- sriov hotplug to guest with hugepage and without hugepage backed
guest.
- guest reboot after hotplug and verify hotplugged device persist
after reboot
- stop the vm monitor and perform hotplug, resume guest and verify
hotplugged device
=> sr_iov.cfg: Added sriov hotplug testcases

qemu/tests/cfg/fio_windows.cfg, qemu/tests/fio_windows.py
1. Boot a guest with a data disk
2. Format new added data disk
3. Change the fio command to make sure it run on system disk or data disk
id: 1456172
=> Add fio test on data disk

qemu/tests/block_hotplug_negative.py, qemu/tests/cfg/block_hotplug_negative.cfg
drive release check after failed to add device with data plane enable
Bug id:1467486
=> New case: block_hotplug_negative

qemu/tests/balloon_check.py
=> balloon_check: Fix bug when utils_misc.wait_for() timeout

qemu/tests/block_hotplug.py, qemu/tests/cfg/block_hotplug.cfg
data plane support for case "with_plug.with_system_reset.one_pci"
Bug id:1434263
=> block_hotplug: add support for data plane

qemu/tests/cfg/rng_hotplug.cfg, qemu/tests/rng_hotplug.py
#add optional steps to support reboot/shutdown guest after hotplug
or hot-unplug rng devices
ID:1455809 1455808 1455807 1455806
=> rng_hotplug:reboot/shutdown guest after plug/unplug rng device

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py, qemu/tests/qemu_guest_agent_suspend.py
1.add gagent-stop function.
2.add case to repeat stop/restart qemu-ga service for 100 times.
ID: 1503420
=> qemu_guest_agent: new case about stop/restart qemu-ga service in guest.

qemu/tests/cfg/block_hotplug.cfg
=> block_hotplug.cfg: add device type support for s390x

qemu/tests/enospc.py
1. Should report error when leaked clusters are founded
2. As image locking is enabled, must use force shared option to
check a stopped image.
3. Update the function to print the debug info
ID: 1517728
=> enospc: Use force shared option to check the stopped image

qemu/tests/block_copy.py
=>  block_copy: Use QemuImg instead of generating qemu-img cmd

qemu/tests/cpuflags.py
Some small bugfixes and adjustments of cpuflags tests... @ehabkost @KarMez-Redhat
=> Couple of cpuflags fixes

qemu/tests/cfg/boot_order_check.cfg, qemu/tests/cfg/ioeventfd.cfg, qemu/tests/cfg/live_snapshot_chain.cfg, qemu/tests/cfg/spice.cfg, qemu/tests/live_snapshot_chain.py
Hello guys, those are fixes found while running full set of tests on s390s. It's not addressing all issues, but the most pressing ones.
=> Bunch of (not only) s390x fixes

qemu/tests/cfg/watchdog.cfg, qemu/tests/watchdog.py
=> s390x: add the watchdog type diag288 for s390x

qemu/tests/cfg/readonly_floppy.cfg, qemu/tests/readonly_floppy.py
=> qemu.test: readyonly_floppy, get virt_data_dir dynamically

qemu/tests/cfg/migrate.cfg
=> migrate.cfg: droped automem in cfg

qemu/tests/cfg/usb_device_check.cfg, qemu/tests/usb_common.py
1. added error checking in dmesg for linux guest
2. reduced timeout for usb check tests
id: 1523014
=> usb_device_check: added error checking in dmesg for linux guest

qemu/tests/block_copy.py, qemu/tests/cfg/live_backup.cfg, qemu/tests/cfg/live_snapshot.cfg, qemu/tests/live_backup_base.py, qemu/tests/live_snapshot_basic.py, qemu/tests/live_snapshot_integrity.py, qemu/tests/live_snapshot_stress.py
live_snapshot_integrity: Add integrity check test case for live snapshot.
id: 1366135
=> live_snapshot_integrity: Add integrity check test case for live snapshot.

qemu/tests/migration.py
test errors out if tcpdump is not installed in guest, handle it by
checking and installing it.
remove few autotest dependencies
=> migration: check and install tcpdump package

qemu/tests/numa_basic.py
Check numa node free memory before running test
ID: 1503402
=> numa_basic: Check node free memory before test

qemu/tests/driver_in_use.py
When sub_test is a cmd instead of a case in avocado, use session.cmd() function to run it, rather than utils_test.run_virt_sub_test()
ID:1516594
=> driver_load_stress: Shouldn't call run_virt_sub_test() if sub_test is command lines

qemu/tests/cfg/boot_from_device.cfg, qemu/tests/cfg/drive_mirror.cfg, qemu/tests/cfg/drive_mirror_negative_tests.cfg, qemu/tests/cfg/qemu_img_negative.cfg, qemu/tests/cgroup.py, qemu/tests/live_snapshot_chain.py, qemu/tests/multi_disk.py
This is a collection of fixes and small improvements found while reviewing @ldoktor PR #1170 .
Changes from v1 (#1173):
- Based, and rebased, on v3
- Remove comments from iscsi target configuration
- Added missing `astring` import
=> S390x 2.3 trivial fixes [v2]

qemu/tests/cfg/hotplug_mem.cfg
=> hotplug_mem: Update migration related params for Windows guest

qemu/tests/cfg/pktgen.cfg
=> pkt.host_guest: extend timeout value and comment password_pktgen_server

qemu/tests/nvdimm.py
=> nvdimm_dax: Fix ValueError for ndctl_ver

qemu/tests/cpuflags.py
This PR fixes (at least) the `cpuflags..qemu_test_migration_with_additional_flags` test and adds some little cleanups.
=> cpuflags: Batch of little fixes

qemu/tests/cfg/single_driver_install.cfg
Add driver install case with pvpanic device
id:1457073
=> single_driver_install.cfg: add install pvpanic device

generic/tests/mac_change.py
get one mac is enough for the same device_id
id:1528169
=> mac_change: Get correct mac when boot with multi-queue

generic/tests/cfg/avocado_guest.cfg
Updated new avocado-misc tests for guest
=> Updated new avocado-misc tests for guest

qemu/tests/cfg/win_virtio_driver_update_test.cfg
add install/uninstall and upgrade/downgrade driver cases for pvpanic
id:1533751 1533752
=> win_virtio_driver_update_test.cfg: add two cases for pvpanic

qemu/tests/cfg/cluster_size_check.cfg, qemu/tests/cfg/qemu_img.cfg
Make test cases to run in certain version of qemu
ID: 1531441, 1531445
=> disk format: Add required qemu version to cases

qemu/tests/migration_with_reboot.py
This test did not pass the "migration_cmd*" to the `vm.migrate`,
therefor the `exec.default_exec` and `exec.gzip_exec` were the same.
=> qemu.migration_with_reboot: Respect migration_cmd

qemu/tests/block_hotplug.py
block_hotplug:add code to unplug virtio-scsi-pci.
bug id: 1507185
=> fix virtio-scsi-pci plug/unplug with repitition fail issue

qemu/tests/balloon_check.py, qemu/tests/balloon_sc_interrogate.py, qemu/tests/cfg/balloon_service.cfg
balloon service should be in running status after send INTERROGATE
signal via windows cmd.
ID:1456105
=> balloon_sc_interrogate:send INTERROGATE signal to balloon service

qemu/tests/block_hotplug.py, qemu/tests/cfg/block_hotplug.cfg
Add subtest "block_resize" after hotplug.
bug id:1466231
=> block_resize: add subtest "block_resize" after hotplug

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
bug id: 1468532
Signed-off-by: yama yama@redhat.com
=> qemu_guest_agent.py: add thaw the unfrozen FS case

qemu/tests/cfg/mlock_basic.cfg, qemu/tests/cfg/numa_memdev_options.cfg, qemu/tests/mlock_basic.py, qemu/tests/numa_memdev_mlock.py, qemu/tests/numa_memdev_options.py
Numa memdev options test:
1. Add new cases for testing numa memdev options(with mlock, policy, host-nodes)
2. Update mlock_basic for easy reusing
ID: 1467178, 1467180, 1467181, 1467179
=> Numa memdev options test

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg, qemu/tests/qemu_guest_agent.py, qemu/tests/qemu_guest_agent_hotplug.py
=> qemu_guest_agent.py: add hotplug/unplug guest agent device case

qemu/tests/qemu_guest_agent.py
1.add check step after thaw fs in guest.
2.fix bug about 'thread._local' object has no attribute 'contexts'
id: 1543259 , 1508356
Signed-off-by: Xiaoling Gao xiagao@redhat.com
=> qemu_guest_agent:Add check step after thaw FS in guest

qemu/tests/balloon_hotplug.py, qemu/tests/cfg/balloon_hotplug.cfg
balloon_hotplug.with-migrate: Add migration test after hotplugging/unplugging balloon device
ID: 1467186
Signed-off-by: yduan yduan@redhat.com
=> balloon_hotplug.with-migrate

generic/tests/cfg/pktgen_perf.cfg, generic/tests/pktgen_perf.py
Gather guest tx/rx mpps through pktgen kernel module.
ID: 1470602
=> Pktgen_perf: Add performance test case pktgen_perf

generic/tests/iozone_windows.py, qemu/tests/balloon_sc_interrogate.py, qemu/tests/balloon_service.py, qemu/tests/balloon_stress.py, qemu/tests/block_resize.py, qemu/tests/cfg/balloon_stress.cfg, qemu/tests/driver_in_use.py, qemu/tests/pvpanic.py, qemu/tests/rng_bat.py, qemu/tests/win_irq_check.py
Add a session login if no session exists
based on:https://github.com/avocado-framework/avocado-vt/pull/1451/
id: 1557143
=> Update the function 'utils_test.qemu.windrv_check_running_verifier'

qemu/tests/cfg/qmp_event_notification.cfg
Add new case for checking "GUEST_PANICKED" event
ID: 1550843
=> Add new qmp test case "GUEST_PANICKED' event"

qemu/tests/block_copy.py, qemu/tests/block_stream_installation.py, qemu/tests/block_stream_simple.py, qemu/tests/cfg/block_stream.cfg
1. Block stream data integrity.
2. Block stream with various payload: when installation and stop_cont.
3. Hot-unplug block disk during block stream.
id: 1368009, 1368011, 1370975
=> block_stream: Add test cases for stress, integrety and hotplug.

generic/tests/nic_promisc.py
Signed-off-by: Mallesh Koti <mallesh@linux.vnet.ibm.com>
=> nic_promisc.py: removing autotest dependency.

qemu/tests/seabios.py
1.As sendkey "esc" is later,So boot_menu_list is NULL
2.Get boot_menu_list via sendkey "esc" during booting.
id:1509197
=> testcase:boot_menu_list is NULL 

openvswitch/tests/load_module.py, openvswitch/tests/ovs_basic.py
=> [openvswitch]Replace autotest modules - lo

qemu/tests/9p.py, qemu/tests/audio.py, qemu/tests/balloon_disable.py, qemu/tests/balloon_stop_continue.py, qemu/tests/blk_stream.py, qemu/tests/block_copy.py, qemu/tests/block_discard.py, qemu/tests/block_resize.py, qemu/tests/block_stream_drop_backingfile.py, qemu/tests/block_stream_negative.py, qemu/tests/block_stream_simple.py, qemu/tests/boot_cpu_model.py, qemu/tests/boot_from_device.py, qemu/tests/boot_order_check.py, qemu/tests/boot_time.py, qemu/tests/boot_with_different_vectors.py
=> [qemu] Replace autotest modules - #ab

generic/tests/boot.py, generic/tests/boot_savevm.py, generic/tests/build.py, generic/tests/clock_getres.py, generic/tests/dd_test.py, generic/tests/downgrade_qcow2_version.py, generic/tests/dropin.py, generic/tests/ethtool.py, generic/tests/fail.py, generic/tests/fillup_disk.py
=> [generic] Replace autotest modules - bcdef

qemu/tests/device_bit_check.py, qemu/tests/disable_win_update.py, qemu/tests/drive_mirror.py, qemu/tests/drive_mirror_cancel.py, qemu/tests/drive_mirror_complete.py, qemu/tests/drive_mirror_powerdown.py, qemu/tests/drive_mirror_simple.py, qemu/tests/driver_in_use.py, qemu/tests/eject_media.py, qemu/tests/enforce_quit.py
=> [qemu] Replace autotest modules - de

generic/tests/netperf.py, generic/tests/netstress_kill_guest.py, generic/tests/nfs_corrupt.py, generic/tests/nicdriver_unload.py, generic/tests/ntpd.py, generic/tests/ntttcp.py, generic/tests/ping.py, generic/tests/pxe_boot.py
=> [generic] Replace autotest modules - np

qemu/tests/hdparm.py, qemu/tests/hello_world.py, qemu/tests/hotplug_mem.py, qemu/tests/hotplug_mem_repeat.py, qemu/tests/hypervisor_flag.py, qemu/tests/invalid_parameter.py, qemu/tests/ipi_x2apic.py
=> [qemu] Replace autotest modules - hi

qemu/tests/netperf_stress.py, qemu/tests/netperf_udp.py, qemu/tests/nfs_perf.py, qemu/tests/nic_bonding.py, qemu/tests/nic_bonding_host.py, qemu/tests/nic_hotplug.py, qemu/tests/nic_teaming.py, qemu/tests/nmi_bsod_catch.py, qemu/tests/nmi_watchdog.py, qemu/tests/nonexist_vcpu_hotplug.py, qemu/tests/numa_consistency.py, qemu/tests/numa_opts.py, qemu/tests/numa_stress.py, qemu/tests/nx.py
=> [qemu] Replace autotest modules - n

qemu/tests/kdump_with_stress.py, qemu/tests/kernbench.py, qemu/tests/kernel_install.py, qemu/tests/kexec.py, qemu/tests/kill_app.py, qemu/tests/ksm_base.py, qemu/tests/ksm_overcommit.py, qemu/tests/live_snapshot.py, qemu/tests/live_snapshot_base.py, qemu/tests/live_snapshot_chain.py, qemu/tests/live_snapshot_runtime.py, qemu/tests/live_snapshot_transaction.py
=> [qemu] Replace autotest modules - kl

generic/tests/save_restore.py, generic/tests/shutdown.py, generic/tests/skip.py, generic/tests/stress_boot.py, generic/tests/trans_hugepage.py, generic/tests/trans_hugepage_defrag.py, generic/tests/trans_hugepage_memory_stress.py, generic/tests/trans_hugepage_relocated.py, generic/tests/trans_hugepage_swapping.py, generic/tests/vlan.py, generic/tests/warning.py, generic/tests/whql_client_install.py, generic/tests/whql_env_setup.py, generic/tests/whql_hck_client_install.py, generic/tests/whql_submission.py
=> [generic] Replace autotest modules - stvw

qemu/tests/cfg/fio_perf.cfg
=> fio_perf: Don't remove NVMe and fusion ssd after test

qemu/tests/unittest.py, qemu/tests/unittest_kvmctl.py, qemu/tests/usb_basic_check.py, qemu/tests/usb_host.py, qemu/tests/usb_hotplug.py, qemu/tests/usb_storage.py, qemu/tests/watchdog.py, qemu/tests/win_disk_write.py, qemu/tests/win_heavyload.py, qemu/tests/win_virtio_serial_data_transfer_reboot.py, qemu/tests/win_virtio_update.py, qemu/tests/windows_info.py, qemu/tests/yonit_bitmap.py, qemu/tests/zero_copy.py
=> [qemu] Replace autotest modules - uwyz

qemu/tests/openflow_acl_test.py, qemu/tests/openflow_test.py, qemu/tests/ovs_mirror.py, qemu/tests/ovs_qos.py, qemu/tests/ovs_quit.py, qemu/tests/pci_bridge_block_stress.py, qemu/tests/pci_devices.py, qemu/tests/pci_hotplug.py, qemu/tests/pci_hotplug_check.py, qemu/tests/pci_hotunplug.py, qemu/tests/perf_kvm.py, qemu/tests/performance.py, qemu/tests/physical_resources_check.py, qemu/tests/ping_kill_test.py, qemu/tests/pktgen.py, qemu/tests/pxe_query_cpus.py
=> [qemu] Replace autotest modules - op

qemu/tests/readonly_floppy.py, qemu/tests/reboot_time.py, qemu/tests/remove_interface_from_host.py, qemu/tests/rh_kernel_update.py, qemu/tests/rng_stress.py, qemu/tests/rv_audio.py, qemu/tests/rv_build_install.py, qemu/tests/rv_connect.py, qemu/tests/rv_copyandpaste.py, qemu/tests/rv_fullscreen.py, qemu/tests/rv_input.py, qemu/tests/rv_logging.py, qemu/tests/rv_smartcard.py, qemu/tests/rv_vdagent.py, qemu/tests/rv_video.py, qemu/tests/rv_vmshutdown.py
=> [qemu] Replace autotest modules - r

qemu/tests/qcow2perf.py, qemu/tests/qemu_disk_img.py, qemu/tests/qemu_disk_img_commit.py, qemu/tests/qemu_disk_img_convert.py, qemu/tests/qemu_disk_img_info.py, qemu/tests/qemu_disk_img_rebase.py, qemu/tests/qemu_guest_agent_snapshot.py, qemu/tests/qemu_guest_agent_suspend.py, qemu/tests/qemu_img.py, qemu/tests/qemu_io.py, qemu/tests/qemu_io_blkdebug.py, qemu/tests/qemu_iotests.py, qemu/tests/qemu_killer_report.py, qemu/tests/qemu_no_shutdown.py, qemu/tests/qemu_nobody.py, qemu/tests/qemu_option_check.py, qemu/tests/qmp_basic.py, qemu/tests/qmp_basic_rhel6.py, qemu/tests/qmp_command.py, qemu/tests/qmp_event_notification.py
=> [qemu] Replace autotest modules - q

generic/tests/guest_suspend.py, generic/tests/guest_test.py, generic/tests/invalid_para_mq.py, generic/tests/iofuzz.py, generic/tests/iozone_windows.py, generic/tests/jumbo.py, generic/tests/kdump.py, generic/tests/ksm_services.py, generic/tests/module_probe.py, generic/tests/multi_queues_test.py, generic/tests/multicast.py
=> [generic] Replace autotest modules - gijkm

qemu/tests/save_restore_vm.py, qemu/tests/set_link.py, qemu/tests/smartcard_setup.py, qemu/tests/smbios_table.py, qemu/tests/softlockup.py, qemu/tests/sr_iov_boot_negative.py, qemu/tests/sr_iov_hotplug_negative.py, qemu/tests/sr_iov_irqbalance.py, qemu/tests/steps.py, qemu/tests/stop_continue.py, qemu/tests/stress_kernel_compile.py, qemu/tests/suspend_under_stress.py, qemu/tests/sysprep.py, qemu/tests/system_reset_bootable.py, qemu/tests/systemtap_tracing.py
=> [qemu] Replace autotest modules - s

qemu/tests/file_copy_stress.py, qemu/tests/fio_perf.py, qemu/tests/flag_check.py, qemu/tests/floppy.py, qemu/tests/flow_caches_stress_test.py, qemu/tests/format_disk.py, qemu/tests/fullscreen_setup.py, qemu/tests/getfd.py, qemu/tests/gluster_boot_snap_boot.py, qemu/tests/gluster_create_images.py, qemu/tests/guest_memory_dump_analysis.py
=> [qemu] Replace autotest modules - fg

qemu/tests/cdrom.py, qemu/tests/cdrom_block_size_check.py, qemu/tests/cgroup.py, qemu/tests/change_media.py, qemu/tests/chardev_hotplug.py, qemu/tests/check_block_size.py, qemu/tests/check_coredump.py, qemu/tests/check_roms.py, qemu/tests/check_unhalt_vcpu.py, qemu/tests/client_guest_shutdown.py, qemu/tests/cluster_size_check.py, qemu/tests/cpu_add.py, qemu/tests/cpu_device_hotplug.py, qemu/tests/cpu_hotplug.py, qemu/tests/cpuflags.py, qemu/tests/cpuid.py, qemu/tests/cpuinfo_query.py, qemu/tests/create_macvtap_device.py, qemu/tests/cyginstall.py
=> [qemu] Replace autotest modules - c

openvswitch/tests/load_module.py
=> Python 3: [openvswitch] a raise fixer

qemu/tests/valgrind_memalign.py, qemu/tests/vhost_with_cgroup.py, qemu/tests/virt_subtest_combine.py, qemu/tests/virtio_console.py, qemu/tests/virtio_driver_sign_check.py, qemu/tests/virtio_port_hotplug.py, qemu/tests/virtio_port_login.py, qemu/tests/virtio_scsi_mq.py, qemu/tests/virtual_nic_private.py, qemu/tests/virtual_nic_send_buffer.py, qemu/tests/vmstop.py, qemu/tests/vnc.py
=> [qemu] Replace autotest modules - v

qemu/tests/macvtap_event_notification.py, qemu/tests/migration_after_nichotplug.py, qemu/tests/migration_after_vm_paused.py, qemu/tests/migration_with_dst_problem.py, qemu/tests/migration_with_file_transfer.py, qemu/tests/migration_with_netperf.py, qemu/tests/migration_with_reboot.py, qemu/tests/migration_with_speed_measurement.py, qemu/tests/monitor_cmds_check.py, qemu/tests/mq_change_qnum.py, qemu/tests/multi_disk.py, qemu/tests/multi_disk_random_hotplug.py, qemu/tests/multi_macvtap_devices.py, qemu/tests/multi_nics_stress.py, qemu/tests/multi_nics_verify.py, qemu/tests/multi_vms_file_transfer.py, qemu/tests/multi_vms_nics.py, qemu/tests/multicast_iperf.py
=> [qemu] Replace autotest modules - m

generic/tests/ethtool.py, generic/tests/nicdriver_unload.py, qemu/tests/live_snapshot_base.py
=> Fixup function hash_file

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/cfg/usb.cfg, qemu/tests/cfg/win_virtio_update.cfg, qemu/tests/rv_audio.py, qemu/tests/rv_connect.py, qemu/tests/rv_copyandpaste.py, qemu/tests/rv_vdagent.py
=> [qemu] Python 3: Update print

generic/tests/autotest_control.py, generic/tests/autotest_regression.py, generic/tests/dd_test.py, generic/tests/ethtool.py, generic/tests/guest_test.py, generic/tests/invalid_para_mq.py, generic/tests/iofuzz.py, generic/tests/ksm_services.py, generic/tests/multicast.py, generic/tests/ntpd.py, generic/tests/stress_boot.py, generic/tests/trans_hugepage_defrag.py, generic/tests/vlan.py, generic/tests/whql_env_setup.py, generic/tests/whql_submission.py
=> Python 3: [generic] exception fixer

qemu/tests/9p.py, qemu/tests/cdrom.py, qemu/tests/ipi_x2apic.py, qemu/tests/macvtap_event_notification.py, qemu/tests/multi_nics_verify.py, qemu/tests/nmi_watchdog.py, qemu/tests/qemu_img.py, qemu/tests/qmp_command.py, qemu/tests/readonly_floppy.py, qemu/tests/timedrift_check_with_syscall.py, qemu/tests/tsc_drift.py, qemu/tests/yonit_bitmap.py
| get_command_output          -> cmd_output
| get_command_status          -> cmd_status
| get_command_status_output   -> cmd_status_output
=> Update session calls

qemu/tests/cdrom.py, qemu/tests/floppy.py, qemu/tests/migration_with_dst_problem.py
=> [qemu] Python 3: Update raise

generic/tests/multi_queues_test.py, generic/tests/shutdown.py
=> Python 3: [generic] range() and map() fixer

qemu/tests/qmp_command.py
=> [qemu] Python 3: Update long()

qemu/tests/device_option_check.py, qemu/tests/kill_app.py, qemu/tests/multi_disk.py, qemu/tests/multi_disk_random_hotplug.py, qemu/tests/pci_devices.py, qemu/tests/usb_common.py, qemu/tests/usb_storage.py
=> [qemu] Python 3: Update dict calls

qemu/tests/cgroup.py, qemu/tests/sr_iov_hotplug.py
=> [qemu] Python 3: Update custom class calls

qemu/tests/performance.py, qemu/tests/qemu_io_blkdebug.py, qemu/tests/unittest.py
=> [qemu] Python 3: Update module name

qemu/tests/block_stream_drop_backingfile.py, qemu/tests/cdrom.py, qemu/tests/cpuflags.py, qemu/tests/live_backup_base.py, qemu/tests/migration_with_dst_problem.py, qemu/tests/multi_disk.py, qemu/tests/nfs_perf.py, qemu/tests/ovs_qos.py, qemu/tests/pxe_query_cpus.py, qemu/tests/qemu_disk_img_rebase.py, qemu/tests/qemu_io.py, qemu/tests/qmp_event_notification.py, qemu/tests/rh_kernel_update.py, qemu/tests/steps.py, qemu/tests/timedrift_adjust_time.py, qemu/tests/timerdevice_clock_drift_with_ntp.py, qemu/tests/timerdevice_clock_drift_with_sleep.py
=> [qemu] Python 3: Update map(), filter() and zip()

generic/tests/jumbo.py, generic/tests/netperf.py, generic/tests/ntttcp.py, generic/tests/trans_hugepage_relocated.py
=> Python 3: [generic] replaced commands

generic/tests/trans_hugepage_defrag.py, generic/tests/trans_hugepage_swapping.py
=> Python 3: [generic] replaced file() with open()

openvswitch/tests/ovs_basic.py
=> Python 3: [openvswitch] a range fixer

qemu/tests/cpuid.py, qemu/tests/guest_memory_dump_analysis.py, qemu/tests/multi_disk.py, qemu/tests/pci_hotplug.py, qemu/tests/pci_hotplug_check.py, qemu/tests/physical_resources_check.py, qemu/tests/virtio_scsi_mq.py
=> [qemu] Python 3: Replace string

qemu/deps/cdrom/tray_open.py, qemu/deps/softlockup/heartbeat_slu.py, qemu/deps/spice/build_install.py, qemu/deps/win_driver_install/win_driver_install.py, qemu/deps/win_serial/VirtIoChannel_guest_recieve.py, qemu/deps/win_serial/windows_support.py, qemu/deps/windows_ga_install/get_package.py
=> Python 3: Miscellaneous fixes

qemu/tests/rv_connect.py
=> rv_connect: Fix typo

qemu/tests/qmp_basic.py, qemu/tests/qmp_basic_rhel6.py
=> [qemu] Python 3: Update unicode()

qemu/tests/watchdog.py
=> watchdog: remove unexpected argument 'retain_output' of system_output()

qemu/tests/nic_hotplug.py
ID: 1569417
Signed-off-by: Sitong liu <siliu@redhat.com>
=> nic_hotplug: fix syntax error

qemu/tests/timedrift.py
=> timedrift: Fix the issue of set_cpu_affinity

qemu/tests/multicast_iperf.py, qemu/tests/qemu_img.py
=> Fix issues of using avocado.utils.process.CmdError

.travis.yml, requirements-travis.txt, requirements.txt
=> Enable python36 check

qemu/tests/cfg/virtio_storage_in_use.cfg
=> qemu.test: virtio_storage_in_use, the drive format should be same between system disk and data disk.

qemu/tests/qemu_nobody.py
=> qemu.tests.qemu_nobody: Fix typo

qemu/tests/cfg/fio_windows.cfg
=> qemu.test: fio_windows, add scenario for aio=threads and aio=native

generic/tests/cfg/lvm.cfg, generic/tests/lvm.py, qemu/tests/cfg/cdrom_test.cfg, qemu/tests/cfg/format_disk.cfg
=> mkfs: update old fs to new one

qemu/tests/flow_caches_stress_test.py, qemu/tests/migration_with_netperf.py, qemu/tests/multi_nics_stress.py, qemu/tests/netperf_stress.py, qemu/tests/netperf_udp.py, qemu/tests/ovs_qos.py
=> Python 3: Replace string_escape with unicode_escape for decode()

qemu/tests/qemu_img.py, qemu/tests/rh_kernel_update.py
=> Python3 : decode process output to text

qemu/tests/win_virtio_driver_update_test.py
replace shutdown original guest and  boot up it with new iso  process with changing cdrom way
ID: 1556772
=> win_virtio_driver_update_test.py:optimize changing cdrom process

qemu/tests/balloon_hotplug.py, qemu/tests/cfg/balloon_hotplug.cfg
hot-unplug balloon device while balloon service is enabled.
ID:1456109
=> balloon_hotplug: hot-unplug balloon device when balloon service is running

.travis.yml
=> Drop python 2.6 ci check

requirements-travis.txt
=> drop simplejson CI check

qemu/tests/cfg/qmp_command.cfg
=> qmp_command: fix issue of query block status while using q35 machine type 

qemu/tests/cfg/qmp_event_notification.cfg
=> qmp_command: Update command line about s3/s4 for q35 machine type

qemu/tests/cfg/timedrift_adjust_time.cfg, qemu/tests/cfg/timedrift_no_net.cfg, qemu/tests/cfg/timerdevice.cfg, qemu/tests/timedrift_adjust_time.py, qemu/tests/timedrift_no_net.py, qemu/tests/timedrift_no_net_win.py
=> timerdevice: fix error to get hardware time

qemu/tests/qemu_img.py
using os.kill to send `SIGUSR1` to qemu-img process
id: 1582037
=> qemu_img: fixed a process sginal sending issue

multi_host_migration/tests/migration_multi_host_with_kdump.py, qemu/tests/kdump_with_stress.py
Updated kdump function calls with correct params
=> Updated kdump function calls with correct params

qemu/tests/cfg/fio_perf.cfg, qemu/tests/fio_perf.py
=> fio_perf: fix qemu version output error

qemu/tests/cfg/rh_kernel_update.cfg, qemu/tests/rh_kernel_update.py
1. clean up deprecated installation method
2. to support installing kernel related rpms
ID: 1575802, 1598732
=> rh_kernel_update: Improve the test

qemu/tests/cfg/fio_perf.cfg
=> fio_perf: fix errors about virtio_win version output

.travis.yml
=> bypass ci check errors

qemu/tests/pvpanic.py
notmyfault_app triggers BSOD of the guest, and it terminates qemu
process, so sometimes, it can not get the status of the cmd.
This fix catches ShellStatusError, to allow later check of the
panic event.
id: 1601304
=> pvpanic: catch ShellStatusError

qemu/tests/rng_bat.py
Add decode operation before re.search for python3 compatible
ID：1603035
=> Add decode operation before re.search for python3 compatible

generic/tests/ping.py
Add additional explicit decode from bytes to str for python3
ID: 1609656
=> ping.ext_host: Add compatibility for python3

qemu/tests/cfg/qemu_guest_agent.cfg
=> qemu_guest_agent: Adopt guest 'python' command to python3

generic/tests/cfg/timedrift.cfg, qemu/tests/timedrift_with_reboot.py
=> timedrift_with_reboot: sync guest's timezone before testing.

qemu/tests/chardev_hotplug.py, qemu/tests/qemu_guest_agent.py
=> virtio_serial test loop: To decode process.system_output() to string

qemu/tests/cfg/block_hotplug.cfg
=> block_hotplug.data_plane: add iothread to existing virtio-scsi-pci

qemu/tests/cfg/usb.cfg
=> usb: Minor fixes for RHEL8 test failure

qemu/tests/eject_media.py
=> eject_media: use eject_cdrom and change_media

qemu/tests/virtio_console.py
=> [python 3]virtio_console: decode data received from sock

qemu/tests/cfg/migrate.cfg, qemu/tests/migration.py
Add migration test scenarios to test the recent Multifd feature
with migration parameters configuring non default values.
Qemu commit: 14 commits from 35374cbdff
=> migration: Add multifd migration scenario

qemu/tests/cfg/qmp_event_notification.cfg
=> qmp_event_notification: Disable verify_guest_dmesg for certain tests

qemu/tests/migration.py
=> migration: Fix IndexError

qemu/tests/cfg/qemu_guest_agent.cfg
=> qemu_guest_agent: revert to python command for Windows guest

qemu/tests/cfg/multi_nics_hotplug.cfg
ID: 1625798
Sign-off-by: Sitong Liu <siliu@redhat.com>
=> RHEL8: Exclude testing with RHEL8 guest/host in some cases

generic/tests/cfg/timedrift.cfg
=> Drop ntp variant

qemu/tests/cfg/cgroup.cfg, qemu/tests/cgroup.py
=> cgroup: add case of CFS bandwidth limit

qemu/tests/rng_hotplug.py
modify hotplug and hot-unplug method to support rng device plug and unplug under pcie bus.
ID:1570472
=> rng_hotplug: Modify plug and unplug method to adjust to pcie bus

qemu/tests/cfg/transfer_file_over_ipv6.cfg, qemu/tests/transfer_file_over_ipv6.py
1. Add get windows ipv6 locallink address
2. Enable upload/download big data between host and windows guest
ID: 1566963
=> Add windows guest support for upload/download data via ipv6

generic/tests/cfg/timedrift.cfg, qemu/tests/timedrift.py
=> timedrift: delete redundant command for adding host load

qemu/tests/cfg/seabios_reboot_timeout.cfg, qemu/tests/seabios_reboot_timeout.py
Add reboot-timeout option test case for seabios
ID: 1469050
=> seabios_reboot_timeout: Add seabios new case

generic/tests/cfg/vlan.cfg, generic/tests/vlan.py
=> vlan: enable ping test with vlan tag on windows guest

qemu/tests/cfg/ovmf_check_efi.cfg, qemu/tests/ovmf_check_efi.py
=> ovmf_check_efi: Check if guest boots from UEFI

qemu/tests/cfg/multicast_iperf.cfg, qemu/tests/multicast_iperf.py
=> multicast_iperf: install gcc-c++ to compile iperf for multicast

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> qemu_guest_gagent.py: check guest agent status after running init 3

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> qemu_guest_agent: Add case of hotplugging disk with frozen fs

qemu/tests/cfg/set_link.cfg, qemu/tests/set_link.py
Add ip check for windows guest and extend the timeout.
id:1510750
=>  set_link: fix problem of packets lost during ping on windows guest

qemu/tests/cfg/check_block_size.cfg
Otherwise the installation can not proceed in ovmf interface
id: 1611536
=> check_block_size: send key and restore var file for ovmf

qemu/tests/cfg/multi_nics_verify.cfg, qemu/tests/multi_nics_verify.py
=> multi_nics_verify: Boot 27 NICs and all the NICs can get IPs

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> qemu_guest_agent.py: check the default path of fsfreeze-hook

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
=> qemu_guest_agent.py: add case of checking guest agent status via qmp

qemu/tests/virtio_console.py
Virtserialport device must be added to an existed chardev, so when there is
a virtioserialport, there is always a chardev. When hot-unplug a port, the 
relevant chardev still in vm. In original test_interrupted_transfer function, 
the code tries to hotplug the port to a non-existed chardev after hot-unplug this 
port. This can be fixed by getting the chardev of this port before hotplug it.
Besides, the default 'interrupted_transfer' test did data transferring between 
one virtioconsole and one virtioserialport. This failed everytime in my test, so
I made two changes to implement this test. 
1) Update the vm object with devices one virtioconsole and one virtioserialport
to with devices two "virtioserialport".
2) Update the data transferring between console and port to between ports. …
=> virtio_console.py: correct error - replug port with non-existed chardev.

qemu/deps/watchdog/watchdog-test-framework/.gitignore, qemu/deps/watchdog/watchdog-test-framework/COPYING, qemu/deps/watchdog/watchdog-test-framework/Makefile, qemu/deps/watchdog/watchdog-test-framework/README, qemu/deps/watchdog/watchdog-test-framework/watchdog-test.c, qemu/tests/cfg/watchdog.cfg, qemu/tests/watchdog.py
=> watchdog: Test watchdog device with a simple framework

qemu/tests/cfg/flow_caches_stress_test.cfg, qemu/tests/flow_caches_stress_test.py
flow_caches_stress_test: fix subcase no_multi_queues on RHEL guest
id: 1317759
=> flow_caches_stress_test: fix subcase no_multi_queues on RHEL guest

qemu/tests/cfg/uefishell.cfg, qemu/tests/uefishell.py
=> uefishell: add case of executing main uefi cmd

qemu/tests/cfg/watchdog.cfg, qemu/tests/watchdog.py
=> watchdog: Heartbeat test for i6300esb

generic/tests/cfg/trans_hugepage.cfg, generic/tests/trans_hugepage_memory_stress.py, qemu/tests/cfg/numa.cfg, qemu/tests/numa_stress.py
=> numa_stress/trans_hugepage: remove dependency of autotest

qemu/tests/cfg/rng_bat.cfg, qemu/tests/cfg/rng_driver_load.cfg, qemu/tests/cfg/rng_host_guest_read.cfg, qemu/tests/cfg/rng_hotplug.cfg, qemu/tests/cfg/rng_read_longtime.cfg, qemu/tests/cfg/rng_stress.cfg, qemu/tests/cfg/viorng_in_use.cfg, qemu/tests/rng_bat.py
=> rng_bat: check and start rngd service in guest before getting random numbers

qemu/tests/balloon_check.py, qemu/tests/cfg/balloon_check.cfg
id: 1572866
Depends on https://github.com/avocado-framework/avocado-vt/pull/1542
=> balloon_check: add case with option "deflate-on-oom" is on

qemu/tests/cfg/hotplug_mem.cfg
ID: 1559278, 1559279
Depends on https://github.com/avocado-framework/avocado-vt/pull/1448
=> hotplug_mem: add option test for memory backend

qemu/tests/cfg/hotplug_mem.cfg, qemu/tests/cfg/hotplug_mem_repeat.cfg
=> hotplug_mem: Update to support run rhel6 guest

qemu/tests/balloon_service.py, qemu/tests/cfg/balloon_service.cfg
ID: 1573806
Depends on https://github.com/avocado-framework/avocado-vt/pull/1542
=> balloon_service: add some negative test for guest-stats-polling-interval

generic/tests/linux_stress.py
Stress app should not be killed without stress_duration defined
id: 1641772
=> linux_stress: stress app should not be killed

qemu/tests/cfg/numa_memdev_options.cfg, qemu/tests/numa_memdev_options.py
ID: 1574834
Depends on https://github.com/avocado-framework/avocado-vt/pull/1554
=> numa_memdev_options: add case to test two nodes with different backend

qemu/tests/cfg/cpu_add.cfg, qemu/tests/cfg/timedrift_adjust_time.cfg, qemu/tests/cfg/timedrift_check_clock_offset.cfg, qemu/tests/cfg/timedrift_no_net.cfg, qemu/tests/cfg/timerdevice.cfg, qemu/tests/cpu_add.py, qemu/tests/timedrift_adjust_time.py, qemu/tests/timedrift_check_when_crash.py, qemu/tests/timedrift_no_net.py, qemu/tests/timedrift_no_net_win.py, qemu/tests/timerdevice_boot.py, qemu/tests/timerdevice_clock_drift_with_ntp.py, qemu/tests/timerdevice_clock_drift_with_sleep.py
=> Replace ntpdate use in cases

qemu/tests/cfg/hotplug_mem.cfg, qemu/tests/hotplug_mem.py
ID: 1578607
Depends on https://github.com/avocado-framework/avocado-vt/pull/1570
=> hotplug_mem: add new case to hotplug memory to different nodes

qemu/tests/chardev_hotplug.py, qemu/tests/virtio_console.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/1773
id: 1625835
=> virtio_console: python3 issue fix

qemu/tests/cfg/resize_raw_img.cfg, qemu/tests/resize_raw_img.py
1. Verify qemu-img resize increase on raw format.
2. Verify qemu-img resize shrink on raw format
id: 1641950
=> added two qemu-img resize tests

qemu/tests/multi_nics_verify.py
=> multi_nics_verify: fix no file of lock-server-running

qemu/tests/cfg/timerdevice.cfg, qemu/tests/timerdevice_boot.py
=> timerdevice_boot: update test steps

qemu/tests/cfg/uefishell.cfg
add case of check smbios, and check "lasterror" value to judge if cmd is run successfully
id: 1581071
=> uefi: check smbios info in uefi env

qemu/tests/balloon_hotplug.py, qemu/tests/cfg/balloon_hotplug.cfg
=> balloon_hotplug: invoke simple_hotplug() to set bus under q35

qemu/tests/multi_vms_nics.py
=> mutl_vms_nics: fix TypeError for python3

qemu/tests/cfg/seabios.cfg, qemu/tests/seabios_bin.py
Add bin file check for seabios
ID: 1482399
=> seabios.bin_file: Add new case for seabios

generic/tests/cfg/multi_queues_test.cfg, generic/tests/multi_queues_test.py
=> multi_queues_test: fix TypeError for python3

qemu/tests/cfg/qemu_option_check.cfg, qemu/tests/qemu_option_check.py
=> qemu_option_check: python3 compatible, add e1000e, remove e1000

qemu/tests/pci_devices.py
QEMU "info qtree" output depends on information generated by guest
firmware. One example is the bus number in PCI device address. QEMU
retrieves it from the PCI configuration space of the bridge which
creates the bus that a PCI device is attached to. So if test runs
"info qtree" before firmware finishes initializing pci devices, its
output can be incorrect.
The current code works around this timing issue by sleeping 5 seconds.
That is not reliable and doesn't work on my aarch64 system. So I'd
suggest to change the test to not start until it verifies the guest
has booted up. This will make the test execution time slightly longer
but is reliable.
Signed-off-by: Huan Xiong <huan.xiong@hxt-semitech.com>
=> pci_devices: run "info qtree" after the guest boots up

qemu/tests/cfg/convert_after_resize_snapshot.cfg, qemu/tests/convert_after_resize_snapshot.py
Verify it can successfully convert a enlarged snapshot.
id: 1645376
=> added a qemu-img convert test

qemu/tests/cfg/single_driver_install.cfg
=> single_driver_install: Add tests for virtio input devices

qemu/tests/cfg/seabios_strict.cfg, qemu/tests/seabios_strict.py
Check boot result when strict is on/off
ID: 1469040
=> seabios_strict: add strict option on/off test

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
Test guest agent commands of guest-file-open/write/flush/seek/read/close
ID：1468931 1468524 1468933  1468932 1552417 1552418 1585559
=> qemu_guest_agent: add test case for guest-file qga command

qemu/tests/multi_vms_nics.py
=> multi_queues_test: Add params for sub_test 'multi_vms_nics'

qemu/tests/cfg/balloon_service.cfg
=> balloon_service: add param guest_compare_threshold

qemu/tests/cfg/hotplug_mem.cfg
ID: 1644496，1456123
Depends on https://github.com/avocado-framework/avocado-vt/pull/1809
=> hotplug_mem: fix hugepage issue for migration case

qemu/tests/netperf_stress.py
=> netperf_stress: enable netperf test with vlan ip

qemu/tests/cfg/multi_disk.cfg, qemu/tests/multi_disk.py
(1) add case with_virtio_scsi_TMF
(2) add windows support for case multi_lun
(3) add windows support for case multi_scsiid_lun
(4) add windows support for case multi_bus_scsiid_lun
ID: 1572480 1321731
=> qemu.test: Update multi_disk related cases

qemu/tests/cfg/thin_write_in_qemu_img_commit.cfg, qemu/tests/thin_write_in_qemu_img_commit.py
=> added a test checks thin write in qemu-img commit

qemu/tests/cfg/ctrl_vlan.cfg, qemu/tests/ctrl_vlan.py
=> ctrl_vlan: add case to test 'ctrl_vlan' on linux and windows guest

qemu/tests/ovs_qos.py
=> ovs_qos: decode process.system_output()

qemu/tests/bridge_vlan.py, qemu/tests/cfg/bridge_vlan.cfg
=> Vlan: enable vlan ping between guest and host

qemu/tests/bridge_mirror.py, qemu/tests/cfg/bridge_mirror.cfg
=> Add enabling port mirror with bridge backend

qemu/tests/cfg/viorng_in_use.cfg
=> viorng_in_use: correct re pattern

qemu/tests/cfg/expose_host_mtu.cfg, qemu/tests/expose_host_mtu.py
=> expose_host_mtu: add test case of expose host mtu to guest

qemu/tests/cfg/set_link.cfg, qemu/tests/set_link.py
=> set_link: Drop cases "status_off" as it has been deprecated

generic/tests/cfg/vlan.cfg, generic/tests/vlan.py
and replace "iptables -F" with stopping "firewalld.service"
ID: 1646793
=> vlan: update error message pattern for new guest

generic/tests/cfg/lvm.cfg
=> generic.test: skip cluster leak warning for lvm

qemu/tests/cfg/qemu_img_map_unaligned_image.cfg, qemu/tests/qemu_img_map_unaligned_image.py
=> added a qemu-img map an unaligned image case

qemu/tests/cfg/pci_devices.cfg
Signed-off-by: Huan Xiong <huan.xiong@hxt-semitech.com>
=> pci_devices: fix test name

qemu/tests/vhost_with_cgroup.py
=> vhost_with_cgroup: Modify the method to get vhost pid

qemu/tests/win_virtio_driver_update_test.py
Correct the logic to avoid installing driver twice.
ID: 1656668
=> win_virtio_driver_update: Correct the logic

qemu/tests/ksm_base.py, qemu/tests/ksm_overcommit.py
=> ksm_base/ksm_overcommit: Fix python3 issue

qemu/tests/cfg/virtio_serial_empty_line.cfg, qemu/tests/virtio_serial_empty_line.py
=> virtio_serial: Add test case for empty line transfer

qemu/tests/cfg/ovs_host_vlan.cfg, qemu/tests/ovs_host_vlan.py
=> ovs_host_vlan: add ovs simple vlan test case in one host

qemu/tests/cfg/readonly_disk.cfg, qemu/tests/readonly_disk.py
=> qemu.test: Update case "readonly_disk"

qemu/tests/cfg/balloon_boot_in_pause.cfg, qemu/tests/cfg/balloon_check.cfg, qemu/tests/cfg/balloon_hotplug.cfg, qemu/tests/cfg/block_hotplug.cfg, qemu/tests/cfg/boot_time.cfg, qemu/tests/cfg/cpu_add.cfg, qemu/tests/cfg/pci_hotplug.cfg, qemu/tests/cfg/rng_hotplug.cfg
paramter name 'check_img' is not correct, it should be 'check_image'
id: 1661205
=> Correct 'check_img' to 'check_image'

qemu/tests/openflow_test.py
and replace "iptables -F" with "systemctl stop firewalld" to stop
firewall.
=> [python3]openflow_test: decode stdout for utils_net.openflow_manager()

qemu/tests/cfg/win_sigverif.cfg, qemu/tests/win_sigverif.py
Add a new case for "sigverif" utility. It checks whether all drivers are digtally signed.
ID:1455812
=> win_sigverif: case for windows "sigverif" utility testing

qemu/tests/cfg/rebase_onto_no_backing_file.cfg, qemu/tests/rebase_onto_no_backing_file.py
=> added a rebase a qcow2 snapshot to remove the raw backing case

qemu/tests/cfg/rebase_second_snapshot_to_base.cfg, qemu/tests/rebase_second_snapshot_to_base.py
1. rebase with different compat modes
2. rebase with various cache modes
id: 1657723
=> added rebase second qcow2 snapshot to a raw base cases

qemu/tests/ksm_base.py
=> ksm_base: Fix python3 bytes issue

qemu/tests/balloon_check.py, qemu/tests/balloon_service.py, qemu/tests/cfg/balloon_service.cfg
balloon_service: Add two balloon service related cases
Add three new cases related to balloon service:
1. install/uninstall balloon service;
2. disable/enable balloon service;
ID: 1456110,1456106
=> balloon_service: Add two balloon service related cases

qemu/tests/qemu_guest_agent.py
The check_guest_file test case only cover basic guest file write test,
need to do more test for it.
ID:1468524
=> qemu_guest_agent: update guest file write test with count parameter

generic/tests/mac_change.py
guest mac need not to change when ctrl_mac_addr_off
id:1612763
=> mac_change:fix error "Guest mac change failed" in windows guests

qemu/tests/cfg/commit_snapshot_to_raw_backing.cfg, qemu/tests/commit_snapshot_to_raw_backing.py, qemu/tests/qemu_disk_img.py
1. rebase with different compat modes
2. rebase with various cache modes
id: 1656252
=> added commit qcow2 snapshot to raw backing image cases

qemu/tests/cfg/create_snapshot_on_running_base.cfg, qemu/tests/create_snapshot_on_running_base.py
qemu-img create a snapshot on a running base image
id: 1652448
=> add a test case create a snapshot on a running base

qemu/tests/qemu_guest_agent.py
gagent_install/uninstall_cmd can't get correct value if qga pkg is installed.
ID:1658889
=> qemu_guest_agent:fix qemu-ga uninstall failed issue

qemu/deps/openflow_acl_test/applicationHost.config, qemu/tests/cfg/openflow_acl_test.cfg, qemu/tests/openflow_acl_test.py
id: 1475696
Pkgmgr is deprecated, instead use dism. and Create a New FTP Site
by Editing the IIS Configuration Files
=> Openflow_acl_test.xxx.ftp: Create a New FTP Site by Editing the IIS Configuration Files

provider/win_dev.py, qemu/tests/cfg/rng_bat.cfg, qemu/tests/cfg/win_irq_check.cfg, qemu/tests/rng_bat.py, qemu/tests/win_irq_check.py
msinfo32 has performance issues, windrv_check_running_verifier() is re-worked with devcon tool. So update related code in cases.
ID：1598291
=> windows drivers' cases: Update windows driver status check function

qemu/tests/cfg/balloon_in_use.cfg
=> balloon_in_use: update stress to avoid migration timeout

qemu/tests/cfg/qemu_disk_img.cfg, qemu/tests/cfg/qemu_img.cfg, qemu/tests/cfg/qemu_iotests.cfg
=> tp-qemu: remove vdi/qed format from disk format test

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
Freeze fs and issue guest-file qga command.
ID: 1663096
Signed-off-by: Xiaoling Gao xiagao@redhat.com
=> qemu_guest_agent:Add case of trying to operate guest file on a freeze fs

qemu/tests/cfg/numa_opts.cfg, qemu/tests/numa_maxnodes.py
=> numa_opts: add new case to test 128 numa nodes

qemu/tests/block_hotplug_in_pause.py, qemu/tests/cfg/block_hotplug_in_pause.cfg
New case "hotplug block device when vm paused" is needed,
add block_hotplug_in_pause.py and block_hotplug_in_pause.cfg
bug id:1550795
=> New test case "block_hotplug_in_pause"

provider/slof.py, qemu/tests/cfg/slof_boot.cfg, qemu/tests/slof_boot.py
Add slof_boot case for testing SLOF
1.Add slof_boot case.
2.Add common functions for testing SLOF.
ID: 1645002
=> slof_boot: Add slof_boot case for testing SLOF

qemu/tests/cfg/virtio_mode.cfg, qemu/tests/virtio_mode.py
Check device mode are set as expected and device works normally in each mode.
ID: 1598381
=> virtio_mode: Add new cases for three virtio mode: modern, transitional and legacy

qemu/tests/cfg/slof_hugepage.cfg, qemu/tests/slof_hugepage.py
slof_hugepage case is that verify SLOF info with hugepage.
ID: 1645009
=> slof_hugepage: Add slof_hugepage case for testing SLOF

provider/slof.py
=> slof: Get multiple SOLF's contents

qemu/tests/cfg/slof_greater_lun_id.cfg, qemu/tests/slof_greater_lun_id.py
slof_greater_lun_id case is that verify SLOF info
when LUN ID greater than 255.
ID: 1645020
=> slof_greater_lun_id: Add slof_greater_lun_id case for testing SLOF

qemu/tests/expose_host_mtu.py
=> expose_host_mtu: get interface of netdst when multiple bridge is used on host

qemu/tests/cfg/slof_multi_devices.cfg, qemu/tests/slof_multi_devices.py
slof_multi_devices case is that verify SLOF info
with multi-devices.
ID: 1645019
=> slof_multi_devices: Add slof_multi_devices case for testing SLOF

qemu/tests/cfg/slof_memory.cfg, qemu/tests/slof_memory.py
slof_memory case is that verify SLOF info
with large maxmem.
ID:1645055
=> slof_memory: Add slof_memory case for testing SLOF

qemu/tests/boot_with_different_vectors.py, qemu/tests/cfg/boot_with_different_vectors.cfg
Add windows support to boot with diifferent vectors
id:1485220
=> boot_with_different_vectors.py: add windows support

deps/nc_vsock/nc-vsock.c, qemu/tests/cfg/vsock.cfg, qemu/tests/vsock_test.py
General steps:
1. Compile nc-vsock binary and use it transfer data between guest
and host
2. Listening port from guest side, connection from host and input
character, check if guest receive it
3. Transfer large file from guest to host via nc-vsock
id: 1671209
=> vsock: Add vsock basic test

qemu/tests/cfg/slof_user_interface.cfg, qemu/tests/slof_user_interface.py
slof_user_interface is that verify SLOF info by user interface.
ID: 1646846
=> slof_user_interface: Add slof_user_interface case for SLOF

qemu/tests/cfg/slof_user_interface.cfg
Rename cases since they are duplicated by others.
ID: 1693613
=> slof_user_interface: Rename cases

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
Execute a command in the guest via guest-exec cmd,
and check status of this process.
ID: 1564829
=> qemu_guest_agent: add case of gagent_check_guest_exec

qemu/tests/cfg/slof_open_bios.cfg, qemu/tests/slof_open_bios.py
slof_open_bios case is that verify open bios info.
ID: 1645060
=> slof_open_bios: Add slof_open_bios case for SLOF

qemu/tests/cfg/slof_balloon.cfg, qemu/tests/slof_balloon.py
slof_balloon case is that verify SLOF info with balloon.
ID: 1645063
=> slof_balloon: Add slof_balloon case for SLOF

qemu/tests/cfg/hotplug_mem_repeat.cfg, qemu/tests/hotplug_mem_repeat.py
=> hotplug_mem_repeat: Add new case to test hotplug/unplug 256 times

qemu/tests/cfg/qemu_img_supports_convert_coroutines_complete.cfg, qemu/tests/qemu_img_supports_convert_coroutines_complete.py
=> qemu-img supports coroutines complete

qemu/tests/cfg/slof_order.cfg, qemu/tests/slof_order.py
slof_order case is that verify info of boot order.
ID: 1645056
=> slof_order: Add slof_order case for testing SLOF

qemu/tests/cfg/qemu_guest_agent.cfg, qemu/tests/qemu_guest_agent.py
add a new test case to test freeze/thaw fs during IO test
ID：1543252
=> qemu_guest_agent: add case of freeze/thaw fs during IO test

provider/storage_benchmark.py
1. Add iozone class which providing interfaces to
test block devices.
2. Add fio class which providing interfaces to
test block devices.
ID: 1579750, 1668969 
=> storage_benchmark: Add a storage benchmark class

generic/tests/cfg/ntttcp.cfg, generic/tests/ntttcp.py
1 cannot excute NTttcp command before
2 change session num according to queues
3 add windows driver verified
id:1566966
=> ntttcp.py: fix cannot run this case issue

generic/tests/dd_test.py
To get partitions in during time continuously since
it will spend some time in syncing the operation of
creating partitions.
ID: 1695549
=> dd_test: Update the method of getting partitions
