autotest/tp-qemu

- qemu/tests/cfg/pktgen.cfg
No need to add vhost variants,remove it from qemu/tests/cfg/pktgen.cfg
> qemu.tests.cfg: Remove vhost variants form pktgen

- qemu/tests/cfg/qemu_io_blkdebug.cfg
As error 11 means EAGAIN in Linux will cause qemu_io process keep
re-try the operatoin. This makes the test will timeout instead of
raise an error. So remove it from the list.
> qemu.tests.cfg: Remove 11 from error number list

- qemu/tests/set_link.py
The guest OS need some time to update the status. So add sleep after
we set set_link from monitor.
> qemu.tests: Add sleep after set_link

- generic/tests/cfg/file_transfer.cfg
- generic/tests/cfg/macvtap_mac_change.cfg
- qemu/tests/cfg/flow_caches_stress_test.cfg
- qemu/tests/cfg/remove_interface_from_host.cfg
vhost is 'on' or 'off' should be a parts of matrix, should be convert in
test plan or in special test, so remove it from case cfg.
> remove vhost variants from cfg

- qemu/tests/cfg/multi_vms_nic.cfg
- qemu/tests/multi_vms_nics.py
We do not use guest mac address. So no need filter out it from guest.
> qemu.tests.multi_vms_nics: Do not filter mac address from guest anymore.

- generic/tests/shutdown.py
Sometimes we login into guest in a very short time before all services are
fully start in guest os. This will cause runlevel command return a non-zero
status. Add wait_for there to check the runlevel until we get it.
> generic.tests: Add wait_for when check guest run level

- generic/tests/cfg/stop_continue.cfg
Just modify the variants "with_file_copy.prepare_op" from "dd if=/dev/urandom of=/tmp/origin bs=1M  count=1024" to "dd if=/dev/zero of=/tmp/origin bs=1M count=1024"
> Change the variants with_file_copy.prepare_op in stop_continue.cfg

- qemu/tests/cfg/spice.cfg
Now we will append migrate_vms to vms if it not vms.
migrate_vms set to virt-tests-vm1, so we'd better use virt-tests-vm1 in vms. Or one more VM named virt-tests-vm1 will be created.
> qemu.cfg.spice: Use virt-tests-vm1 as first VM name.

- qemu/tests/cfg/ext_host_netperf_stress.cfg
- qemu/tests/cfg/multi_nics_stress.cfg
- qemu/tests/cfg/netperf_stress_test.cfg
> qemu.cfg: Do not test netperf TCP_SENDFILE test in windows guest.

- qemu/tests/cfg/ioeventfd.cfg
Update the cfg file to set up ioeventfd only for image1 and correct the parameter
set up mistakes.
> qemu.test: Update the ioeventfd cfg file

- qemu/tests/cfg/multi_disk.cfg
- qemu/tests/cgroup.py
Hi guys,
the multi_disk test worked almost out of the box, it only doesn't support some of the drive formats.
The cgroup test is a bit trickier as it's more often to see sparse cpu/mem layouts on PPC. I used a class to map sparse definition to list (and back) to support various layouts and tested it on PPC64 and it works fine.
Additionally I tweaked the test to decrease the number of false-negatives (while avoiding false-positives) so now it should work better on x86 too.
__Beware: On x86_64 F20 the `blkio_throttle` test causes kernel panic (reported) and you might want to set `migrate_vms = ""` as this test uses custom `vms` setup and you might end-up with unused VMS running in the background.__
> Adjust multi_disk test and cgroup tests to work on PPC64

- qemu/tests/live_snapshot.py
To avoid to raise exception TypeError if not set it.
ID: 1088129
> qemu.test.live_snapshot: Add the default value for reboot_timeout

- qemu/tests/blk_stream.py
- qemu/tests/block_copy.py
- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/drive_mirror.py
- qemu/tests/drive_mirror_complete.py
- qemu/tests/drive_mirror_continuous_backup.py
- qemu/tests/drive_mirror_powerdown.py
- qemu/tests/drive_mirror_simple.py
1. update  parser_test_args in drive_mirror class to make test  use default naming conventions
2. update cleanup in drive_mirror to make it use right way to cleanup a iscsi target image
3. add step for flush page cache before compare image in  drive_mirrir_complete test
4. fix coding style issue.
> fix bug in  block_copy releated cases

- qemu/cfg/tests-spice.cfg
- qemu/deps/spice/build_install.py
- qemu/tests/rv_build_install.py
Building spice-gtk and virt-viewer on RHEL7 requires
extra packages and different build options.
> spice.build_install: Add RHEL7 support for building spice pkgs

- generic/tests/cfg/kdump.cfg
Update the check_cmd config because running netperf client in guest.
> generic.tests.cfg: Small fix for kdump_with_stress

- qemu/tests/mq_change_qnum.py
Some parameters in be init at the top of the script, otherwise
it will cause variable referenced before assignment error.
> qemu.tests: Mave some parameters to the top of scripts

- qemu/tests/balloon_stress.py
- qemu/tests/cdrom.py
- qemu/tests/nic_hotplug.py
- qemu/tests/win_heavyload.py
Most  of our test case use wait_for function in utils_misc module and only a little use same function in under autotest.client.shared.utils module.  this fix unify all case in tp-qemu repo to use wait_for function in virttest.utils_misc module.
> qemu.tests: instead utils.wait_for with utils_misc.wait_for

- qemu/tests/ovs_qos.py
sleep 3 second to wait netperf server ready to connect and print netperf
output when expction catched.
ID: 1198475
> tp-qemu.tests.ovs_qos: add sleep second in test step

- qemu/tests/cfg/multi_disk.cfg
- qemu/tests/cfg/usb.cfg
- qemu/tests/multi_disk.py
1. Add new function to get the disk index for windows guest.
2. Update the related config.
> qemu.tests: Add new function to get the disk index for windows guest

- qemu/tests/virtio_scsi_mq.py
Sometime the vcpu number may smaller than host cpu number in this case.
So add a judgement when try to bond vcpu thread to host cpus.
> qemu.test: Bond vcpu according the vcpu number

- qemu/tests/cfg/boot_with_different_vectors.cfg
- qemu/tests/cfg/flow_caches_stress_test.cfg
- qemu/tests/cfg/invalid_parameter.cfg
- qemu/tests/cfg/mq_change_qnum.cfg
- qemu/tests/cfg/pktgen.cfg
as RHEL.6 host does not support multi queue.
> tp-qemu: disable multi queue test on RHEL.6 host.

- qemu/tests/boot_with_different_vectors.py
qemu abort with error is expect when vm boot with a non-uint32
values, catch VMError and check exception message it reasonable.
> qemu.tests: catch except in negative test

- qemu/tests/rv_video.py
Removing some leftover debugging commands to verify
that the repeat totem value was set.
Reviewed by: Swapna Krishnan <skrishna@redhat.com>
> qemu.tests: Removing debugging commands from rv_video.py

- generic/tests/shutdown.py
Fix a typo when last patch is made. It will lead to a wrong result
for monitor status check.
> generic.tests: Fix a typo in shutdown

- qemu/tests/pci_hotplug.py
This method is more stable when we have more than one type of monitor in
our test.
> qemu.tests: Use monitor.protocol to judge the monitor type

- qemu/tests/rv_logging.py
Due to additional logging statements coming from spice-vdagent, the
number of lines which are being searched needs to be updated.
> qemu.tests.rv_logging: Changing the amount of log to grep

- qemu/tests/cgroup.py
In blkio_throttle* tests the command "dd" often finishes after > 360s
with latest kernel. This patch changes the deadline to 600s which
usually works fine (the long deadline is fine as we use very slow
speeds - 1024B/s - for testing).
> qemu.tests.cgroup: Increase the check command timeout

- generic/tests/cfg/fillup_disk.cfg
- generic/tests/fillup_disk.py
1. Add "killall -9 dd" before the cleaning in case the dd
process is not finished.
2. Print the files in /tmp no matter whether the clean_cmd
is executed successfully or failed. As sometimes the cmd
return is successful, but actually it's failed.
> tp-qemu: fillup_disk: Improve the debug log when test failed.

- qemu/tests/virtio_console.py
When qemu_virtio_port is waiting for reconnection and exception occurs
we need to set the EXIT_EVENT otherwise the test hangs for infinity.
> qemu.tests.virtio_console: Avoid hang on exception

- qemu/cfg/tests-spice.cfg
- qemu/deps/spice/build_install.py
While building virt-viewer, enable smartcard option to be able to run
smartcard tests. Also, building smartcard functionality requires
libcacard-devel package. Adding path to libcacard-devel rpm to
config file.
> qemu.spice: Add smartcard option while building and add dependencies

- qemu/tests/cfg/mq_max_queues.cfg
> tp-qemu: mq_max_queues: RHEL.6 host does not support multi host.

- generic/tests/cfg/lvm.cfg
case 'lvm.lvm_fill' needs case 'fillup_disk' as a subcase,
need add the config from fillup_disk.cfg to lvm.cfg.
> tp-qemu: lvm.lvm_fill: update some config.

- qemu/tests/cfg/format_disk.cfg
/media dir not exist in some mini install os(eg, SLES), so
create /media before mount disk to it;
ID: 1176735
> tp-qemu: fix mount-point not exist issue

- qemu/tests/pci_hotplug.py
- qemu/tests/pci_hotplug_check.py
this patch only replaces 'ppc64' checks for 'ppc64' and 'ppc64le' checks.
> qemu.tests: Adjust tests to ppc64le

- qemu/deps/spice/build_install.py
On RHEL7, "--disable-kms" option should not be passed. But it's needed
for RHEL6.
> deps.spice: Updating build options to build qxl on rhel7

- qemu/tests/cfg/systemtap_tracing.cfg
Some testcase need to boot virtio_blk disk, so update
related config.
> qemu.tests.cfg: Fix systemtap_tracing config

- qemu/tests/cfg/migrate.cfg
Response test owner's request to update netperf clinets numbers
to make test more reasonable.
ID: 993578
> qemu.tests: make migrate..with_netperf case more reasonable

- qemu/tests/cfg/virtio_console.cfg
- qemu/tests/virtio_console.py
Hello guys,
this pull request adjusts the default configuration. First patch disables some of the virtconsole subtest variants as they don't reflect real-world usage and related issues might never be fixed. The second and third patch adjusts the configuration to work on aarch64 out of the box.
Regards,
Lukáš
> qemu.tests.virtio_console: Mostly config tweaks

- qemu/tests/softlockup.py
Autotest test structure already changed, so update the code to fit it.
> qemu.tests: Update the monitor_dir in softlockup

- qemu/deps/spice/build_install.py
Due to changes in xrandr, some CFLAGS need to be modified
in Makefile.am before building spice-vdagent. This has been
recommended by SPICE developers.
> spice: Temporary workaround for building spice-vdagent

- qemu/tests/nic_bonding_host.py
As pkill will failed in our test sometime. So use dhclient -r to
exit the dhclient process in system.
> qemu.tests: Use dhclient -r to release the current lease

- generic/tests/cfg/kdump.cfg
- generic/tests/kdump.py
We met some test failed without enough debug information for kdump.
So will store the kdump.cfg to debug dir and record the kdump service
status before we run this case. Also update the command to use the
suitable commands for different version of guests.
> generic.tests: Add some debug information for kdump

- qemu/tests/rv_build_install.py
Forcing use of EPEL repo for perl-Text-CSV and disabling all other
repos.
> spice: Modifying the way perl-Text-CSV is installed

- qemu/tests/cfg/openflow_test.cfg
- qemu/tests/openflow_test.py
dd copy_file=1G will spend more time in guest, default timeout=60
is not enough for it, so update it.
> qemu.tests: Add timeout for prepare_cmd in openflow_test

- generic/tests/cfg/netstress_kill_guest.cfg
We have not implemented the windows support yet, disable the
test for windows, will make windows support in the future.
> tp-qemu: netstress_kill_guest.driver: disable windows test.

- generic/tests/cfg/mac_change.cfg
mac_change..up_change sub case is not suitable for SLES guest,
should be down the ethernet then change the mac.
> generic.tests.cfg: Disable up_change sub case for SLES guest

- qemu/tests/boot_from_device.py
- qemu/tests/cfg/boot_from_device.cfg
For RHEL6 host, boot menu hint message changed.
ID: 1224039
> qemu.tests.cfg: Update the boot_menu_hint config

- qemu/tests/cfg/systemtap_tracing.cfg
- qemu/tests/systemtap_tracing.py
default unit of qmp monitor for balloon value is byte, so
update value to avoid guest reboot when balloon memory to
a incorrect vaule.
> qemu.tests: correct balloon values for qmp command

- qemu/cfg/tests-spice.cfg
Removing some options not required for spice testing. ovmf,
rng_randomn, rng_egd are not required.
> qemu.spice: Removing some options not required for spice testing

- qemu/deps/spice/build_install.py
- qemu/tests/rv_build_install.py
For virt-viewer in RHEL6, there's dependency on spice-gtk version 0.28
which is not what RHEL6 comes with. Hence, we build spice-gtk from
upstream 0.28 tarball on RHEL6 before building virt-viewer from
upstream.
build_install.py: add tarball support for spice-gtk
rv_build_install.py: build spice-gtk before building virt-viewer
> qemu.spice: Add support for building spice-gtk from tarball

- generic/tests/cfg/pxe_boot.cfg
pxe_boot does not work for macvtap backend, as pxe can't
capture the packet from the macvtap tap port, disable it
for macvtap temporarily, will fix it in the furture.
> tp-qemu: pxe_boot: disable pxe_boot for macvtap.

- qemu/tests/block_stream_simple.py
Correct block_stream_simple doc string for speed related instruction.
Signed-off-by: Shaolong Hu <shu@redhat.com>
> tp-qemu: correct block_stream_simple doc string

- qemu/cfg/tests-spice.cfg
Only bridge option is required for spice testing. Removing user, network and macvtap options.
> qemu.spice: Removing options not needed for spice testing

- generic/tests/cfg/mac_change.cfg
- generic/tests/mac_change.py
1. Register has been changed after mac change, and delete
the register may fail, then set "image_snapshot=yes" to
save the original image. 
2. Init the serial again after guest reboot.
> tp-qemu: mac_change: Init the serial again after guest reboot and set "image_snapshot=yes".

- qemu/tests/cfg/qemu_cpu.cfg
> tp-qemu: disable hyperv and hv_relaxed for host os older than rhel7

- qemu/tests/rv_connect.py
If there's no brackets to enclose the two exception,
The second is regarded as a variable and can't be catched.
> qemu.tests.rv_connect: fix catching exception

- qemu/tests/cfg/nic_bonding.cfg
for macvtap temporarily, will fix it in the furture.
id: 1241390
> nic_bonding does not work for macvtap backend, disable it

- qemu/tests/virtio_console.py
There might be unread previously signaled signals before the test.
This patch reads them out to not spoil the expected results.
> qemu.tests.virtio_console: Read-out signals before test

- qemu/tests/pktgen.py
Change log "packet lost ratio is '%100'" to '100%'.
> qemu.tests.pktgen: Small fix for log format

- qemu/tests/cdrom.py
- qemu/tests/cfg/cdrom_test.cfg
tp-qemu: do no use fixed cdrom letter for windows
this patch fixed 2 things:
1. not using fixed cdrom letter for windows
2. if the letter of winutil is bigger than the letter of testing
cdrom ,testing will fail ,this patch is changing to make sure not
using winutil cdrom for testing
ID: 1240903
Signed-off-by: Mike Cao \<bcao@redhat.com\>
> tp-qemu: no need to umount cdrom for windows

- qemu/cfg/tests-spice.cfg
- qemu/tests/fullscreen_setup.py
Changing resolution of guest in RHEL7 causes some weird behavior. So
changing the resolution of the client instead to see if fullscreen
remote-viewer causes the guest resolution to change to match client.
Also, shutdown both client and guest after test to reset to previous
configurations and to go to clean slate
> spice: Modifying fullscreen test to change resolution of client

- qemu/tests/multi_disk_random_hotplug.py
- qemu/tests/rv_copyandpaste.py
- qemu/tests/rv_logging.py
- qemu/tests/transfer_file_over_ipv6.py
In order to display message to users correctly,
The exception message has to use interpolation.
This PR refers to the commit beacb9d.
Signed-off-by: Wei,Jiangang <weijg.fnst@cn.fujitsu.com>
> Fix skip message for TestFail()

- qemu/tests/cfg/qemu_disk_img.cfg
test cache mode and "-o options" for qemu-img convert.
This PR depends on autotest/virt-test#2230
> qemu.tests: Add qemu_disk_img_convert test case

- qemu/tests/cfg/rh_kernel_update.cfg
Because of the wrong regex, it will fetch a ppc64le kernel for ppc64
guest. Now have corrected it.
> qemu.cfg.rh_kernel_update: correct regex for ppc64

- qemu/tests/cfg/rh_kernel_update.cfg
- qemu/tests/rh_kernel_update.py
For installing the latest rhel kernel package, failed with
dracut dependencies, so add "--nodeps" to skip it.
> qemu.tests: Install the kernel dependencies packages

- qemu/tests/cfg/nic_hotplug.cfg
Currently, spapr-vio bus doesn't support hot pluging.
So variant spapr-vlan shouldn't be added to this case
This patch is to remove it
ID: 1214221
> disable nic_hotplug/unplug for spapr-vlan bus

- qemu/tests/macvtap_event_notification.py
The variable 'action_check' is assigned to but never used.
And No 'action_check' is defined in macvtap_event_notification.cfg.
so remove it.
> macvtap_event_notification: remove ununesed variable

- qemu/tests/rv_build_install.py
pyparsing is now required for building spice-protocol. Hence moving
epel creation and pyparsing install to build_install_spiceprotocol
> spice: Updating to install pyparsing as part of spice-protocol build

- qemu/cfg/tests-spice.cfg
- qemu/tests/rv_build_install.py
Building qxl from upstream has new dependecies on packages
"libfontenc-devel" and "libXfont-devel". Adding these packages
to the list of packages to be installed before building qxl.
> spice: Building qxl has new dependencies, adding dependencies

- generic/tests/cfg/fillup_disk.cfg
- generic/tests/fillup_disk.py
1. backup image before testing and restore image after testing.
2. ignore the errors in post processing, which will cover the
main error reason.
id: 1172016
> tp-qemu: fillup_disk: ignore the errors in post processing.

- qemu/tests/mq_change_qnum.py
Use get_host_default_gateway() to get ext_host
ID: 1242739
> qemu.tests.mq_change_qnum: Improve the method for getting ext_host

- qemu/tests/cfg/watchdog.cfg
- qemu/tests/watchdog.py
Check vm paused during migration.
> tp-qemu: fix logical issue in watchdog.migration_when_wdt_timeout.pause

- qemu/tests/cdrom.py
- qemu/tests/cfg/cdrom_test.cfg
1. The way in cdrom.py (cdrom_dev_list[-1]) to get cdrom is not
suitable, especially for multiple cdrom, update the way to
get the cdrom in guest according to the serial number.
2. The guest <= RHEl.5 does not support subcase "cdrom_not_insert",
then disable it.
id: 1209727 1185789
> tp-qemu: cdrom.py: update the way to get the cdrom in guest.

- qemu/tests/pci_hotplug_check.py
The return of utils_misc.find_substring() should be checked,
not the output of monitor.info() or monitor.human_monitor_cmd().
> qemu/tests/pci_hotplug_check: fix wrong check condition

- qemu/tests/cfg/usb.cfg
There is the default bus which is added in base.cfg,
for usb test only, not add the default bus for testing.
id: 1183906
> tp-qemu: usb: test the usb bus alone.

- qemu/tests/numa_consistency.py
Get the numa node index instead of the number of the numa node,
as there are some non-contiguous numa nodes host.
id: 1189441
> tp-qemu: numa_consistency: update the type when get numa node list.

- qemu/tests/rv_build_install.py
In RHEL6, moving to aexpect from virttest.aexpect causes 
ShellCmdError to not work anymore. Hence removing 
ShellCmdError exception and keeping a general except 
statement instead. 
> qemu.spice: Removing ShellCmdError

- generic/tests/shutdown.py
Based on: avocado-framework/avocado-vt#122
> tp-qemu: shutdown.py: Call the setup_runlevel() in utils_test.py directly.

- qemu/tests/rv_smartcard.py
On RHEL6, using aexpect directly causes 
ShellCmdError & ShellCmdTimeout exceptions 
to not work anymore. 
> qemu.spice: Removing aexpect exceptions

- qemu/tests/rv_build_install.py
Changing the spice-gtk tar package to be the latest upstream 
release from 0.29. 
> qemu.spice: Changing spice-gtk tar pkg to latest

- qemu/tests/win_virtio_update.py
It is introduced in 288ce897
module autotest.client.shaed is typo
change back to shared
> tp-qemu: fix typo

- qemu/tests/rh_kernel_update.py
200s is not enough to update initrd sometime, need enlarge it.
id: 1271908
> rh_kernel_update: Enlarge timeout when update initrd.

- qemu/tests/rv_build_install.py
Changing name of spice-gtk tar package to version 0.30
> qemu.spice: Changing spice-gtk tar pkg to 0.30

- qemu/tests/cfg/qemu_disk_img.cfg
RHEL5 and RHEL6 host do not support option "compat"
for qemu_disk_img.convert.
id: 1270632
> tp-qemu: qemu_disk_img.convert: disable option "compat" for RHEL5 and RHEL6 host.

- qemu/tests/sr_iov_irqbalance.py
Maybe the variable 'service_status_filter is intended to
be the pattern param for re.search(),
But re.search() adopts character string directly.
So It becomes meaningless.
> sr_iov_irqbalance: remove unused pattern string

- qemu/tests/cfg/nmi_bsod_catch.cfg
The default setting of mem page file is 4096
According to https://support.microsoft.com/en-us/kb/889654
the traditional model of the page file should be
at least the size of physical ram plus 1 MB, or 1.5 times
So test will fail  if the mem in qemu-kvm larger than 4096
This patch is to use fixed mem size for this case
id: 1165933
> tp-qemu: fixed mem for nmi crashdump case

- qemu/tests/cfg/cpuinfo_query.cfg
Some commands it not supported on RHLL7 host ,this patch is to delete
them and add some new config on RHEL7
As qemu-kvm ?dump is not supported in RHEL7 ,
modify config file to make it RHEL6 only.
Add new test case in cfg for RHEL7 cpuinfo query
ID: 1044928
> tp-qemu: fix cfg for cpuinfo_query

- qemu/tests/cfg/device_bit_check.cfg
The latest RHEL.7 has updated the qtree info, the
properties "event_idx" and "indirect_desc" is under
"virtio-blk-device" instead of "virtio-blk-pci".
id: 1265888
> tp-qemu: device_bit_check.cfg: Update the dev_type.

- qemu/tests/balloon_stress.py
- qemu/tests/cfg/balloon_stress.cfg
1. using the existing func() to enable and clear driver
verifier for windows guest.
2. set flag to enable and clear driver verifier, which can makes
the case more flexible, and the case can be a background case.
3. add a flag env["balloon_test"], which makes the case balloon_stress
be a background case.
id: 1274571
> tp-qemu: balloon_stress: some updates for balloon_stress.

- qemu/tests/cfg/watchdog.cfg
- qemu/tests/watchdog.py
Based on: avocado-framework/avocado-vt#122
id: 1261771
> tp-qemu: watchdog: Setup the runlevel for "shutdown" scenario before test.

- qemu/tests/cfg/boot_from_device.cfg
- qemu/tests/cfg/seabios.cfg
For latest RHEL.7, boot_menu_hint changed from "F12" to
"ESC".
ID: 1224039
> qemu/tests/cfg/: Update boot_menu_hint for seabios log

- qemu/tests/qmp_command.py
In RHEL7 ,(qemu)info block will reply 2 or 3 lines for one block device
This patch combile all the lines to single line
ID: 1263527
> tp-qemu: combile output of query block to one line

- qemu/tests/rv_build_install.py
Making sure that remote-viewer is recognized to be from
/usr/local/bin/ instead of /usr/bin/
> qemu.spice: Combining 2 commands into one

- qemu/tests/migration_with_netperf.py
The unused variable 'g_client_install' isn't completely removed
by 78ea6aa.
> migration_with_netperf: cleanup

- qemu/tests/cfg/rng_bat.cfg
latest virtio-rng device driver register dll into system
after install driver, so disabled this step.
> disable rng dll register command

- qemu/tests/cfg/floppy_test.cfg
- qemu/tests/cfg/readonly_floppy.cfg
As pseries does not support floppy, so need to disable related tests.
ID: 1279716
> qemu.test.floppy_test/readonly_floppy: disable for pseries

- qemu/cfg/host-kernel/Host_RHEL/7.cfg
qemu-kvm support up to 256 queues now.
> qemu/cfg/host-kernel: Update the max queues number

- qemu/tests/rng_bat.py
The way session_cmds is created is evaluated by pylint as dangerous.
Let's make it more visible by using generator.
> qemu.tests.rng_bat: Clean pylint error

- .travis.yml
- README.rst
- qemu/tests/openflow_test.py
- requirements-travis.txt
Move to the faster, container-based travis tesing infrastructure.
In order to do this, add a new requirements-travis.txt file that
concentrates the requirements of the testing job, plus cleanup
of .travis.yml and addition of sudo: false to that file.
> Move new travis infra

- qemu/tests/cfg/qemu_disk_img.cfg
> tp-qemu: qemu_disk_img: disable those not supported versions for preallocation mode "full" and "falloc".

- qemu/tests/cfg/hdparm.cfg
Disable spapr_vscsi variant for hdparm test as it is not supported.
ID: 1276304
> qemu.tests.hdparm: disable spapr_vscsi

- qemu/tests/cdrom.py
1. update the serial number length to "10~20",
which is more reliable for comparation.
2. add qtree info when test failed.
id: 1276289
> tp-qemu: cdrom.py: some small updates.

- qemu/tests/pci_hotplug.py
> pci_hotplug: replace virttest.aexpect with aexpect

- generic/tests/cfg/dd_test.cfg
- generic/tests/cfg/lvm.cfg
- generic/tests/dd_test.py
- generic/tests/lvm.py
- qemu/tests/block_resize.py
- qemu/tests/cfg/block_resize.cfg
- qemu/tests/cfg/format_disk.cfg
- qemu/tests/format_disk.py
qemu.test: format_disk, block_resize
generic.test: lvm, dd_test
These above cases assumed the target drive path is "/dev/*db". However,
it would not be true in rhel ppc guest with using virtio-blk interface.
The fix will make these cases to get the target drive by serial or wwn.
ID: 1279721 1279719 1272397
> Replace the method of getting target drive path

- qemu/tests/qemu_img.py
vm paused after send shutdown command, so it will
caused check vm shutdown error in below.
> qemu_img: fix logical issue

- qemu/cfg/tests-example.cfg
And not "sanity", which is intended to be a much shorter test set.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> qemu/cfg/tests-example.cfg: longer test set should be named stable

- qemu/tests/cfg/qmp_event_notification.cfg
- qemu/tests/qmp_event_notification.py
Running guest cmd "shutdown -h now" would cause a termination of shell
session, this would raise an exception that can fail the test. So add
the ability for passing "ignore_all_errors=True" to call-back function
which runs in guest.
ID: 1272378
> qemu.tests.qmp_event_notification: allow passing options to call-back function

- qemu/tests/netperf_stress.py
When netperf_stress as a background case, need sleep a while
before set flag "env[netperf_run] = False", to avoid the other
cases have not got the flag "env[netperf_run]" changed.
id: 1292688
> tp-qemu: netperf_stress.py: sleep a while before set flag "env[netperf_run] = False"

- qemu/tests/cfg/netkvm_in_use.cfg
id: 1231015, 1230674, 1231007
Based on: autotest/tp-qemu#463
> tp-qemu: Add some subtests when netkvm driver in use.

- qemu/tests/cfg/hotplug_mem.cfg
To avoid test name confilt with basic system_reset,
and reboot tests.
> qemu.tests.cfg: update sub-tests name

- qemu/tests/qemu_disk_img_commit.py
Add sync on host after execute commit about qemu_disk_img_commit case.
bug id: 1283687
Signed-off-by:Xiaoling Gao xiagao@redhat.com
> Fix qemu_disk_img_commit,add sync step on host after commit.

- qemu/tests/cfg/multi_host.cfg
- qemu/tests/migration_multi_host_timedrift.py
1. Add step for checking clocksource in guest.
2. Add new case without_kvmclock.
ID: 1298771
> qemu/tests: Add new case without_kvmclock for multi host migration

- generic/tests/kdump.py
kdump config file should be /etc/kdump.conf
> generic/tests: Small fix for kdump.py

- generic/tests/cfg/autotest_control.cfg
Add autotest-client-tests url for download zip source and add
network_proxies configuration to support download source code via
proxy server.
> tp-qemu: add configuration in autotest.control_test

- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/drive_mirror_complete.py
1. Remove useless sync and wait steps
2. pause vm before reopen operation
3. compare source image and target image after reopen operation
> drive_mirror: test step update

- qemu/cfg/host-kernel/Host_RHEL/7.cfg
Create the new thread when do migration only support
from Host_RHEL.7.0.
ID: 1321505
> qemu.cfg.host-kernel: Add option enable_check_mig_thread for Host_RHEL.7

- qemu/tests/rh_kernel_update.py
In some linux guest (eg. rhel7.2) cp command has alias
like: alias cp='cp -i'
command execution will block by wait for alternation.
> fix command execute timeout issue

- qemu/deps/win_driver_install/win_driver_install.py
For some guests, inf file name is upper case letters,
as endswith() is case letter sensitive, need transfor
them to lower case letters.
> tp-qemu: win_driver_install.py: fix a letter case problem.

- qemu/tests/cfg/disable_win_update.cfg
- qemu/tests/disable_win_update.py
The default cmd timeout is 60s, it is not enough
for some guests sometimes, like Win10.
id: 1311434
> tp-qemu: disable_win_update: add cmd timeout.

- qemu/cfg/tests-spice.cfg
- qemu/tests/rv_build_install.py
Building spice-gtk from upstream on RHEL 7.2 requires a new package
libepoxy-devel to be installed on the machine.
> qemu.spice: Adding libepoxy-devel rpm install for building spice-gtk

- qemu/tests/change_media.py
Sometimes Line#121 will report "local variable 'msg'
referenced before assignment", so define msg at begin.
ID: 1327383
> qemu/tests/: Small fixed for change_media.py

- qemu/tests/invalid_parameter.py
Have no attribute 'reason' in class VMCreateError().
ID: 1218500
> qemu.tests: Small fix in invalid_parameter.py

- qemu/tests/multi_disk.py
1) remove unused variable
2) fix double calls for session.close(),
note that _do_post_cmd() has already call it.
> multi_disk: cleanup

- qemu/tests/cfg/pci_hotplug.cfg
The commit f83f336 change the method of getting target drive path,
which leads cases related block_resize fail for x86_64.
such as pci_hotplug.hotplug_block.blk_virtio_blk.with_block_resize
Error Message:
ParamNotFound: Mandatory parameter 'blk_extra_params_stg' is missing.
Check your cfg files for typos/mistakes
> block_resize: fix ParamNotFound

- generic/tests/netperf.py
Instead of get_download_dir(), which is really used to hold download
definition files, AKA as assets, the ".ini" files that define locations
and hashes such as the JeOS image files.
This is related to https://github.com/avocado-framework/avocado-vt/pull/439, more specifically https://github.com/avocado-framework/avocado-vt/pull/439/commits/d253d4b6e614f66520240b6117ab95d60d11851d
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> generic/tests/netperf.py: use datadir.get_tmp_dir()

- qemu/tests/timedrift_no_net.py
- qemu/tests/timedrift_no_net_win.py
virttest.utils_misc.find_command is deprecated and
avocado.utils.path.find_command is recommended.
taking compatibility into account,
so use autotest.client.utils.find_command instead.
> Fix usages of virttest.utils_misc.find_command

- qemu/tests/cfg/pci_hotplug.cfg
When we hotplug a NIC, there's no block device added.
so It's unreasonable to resize block device.
> pci_hotplug: remove hotplug_nic..with_block_resize cases

- qemu/tests/watchdog.py
logging.info() is behind error.TestFail(),
which leads to logging.info will never be executed.
> watchdog: trivial fix for logging

- qemu/tests/migration_multi_host_firewall_block.py
Enclose multiple exception(in one line) in parentheses.
> migration_multi_host_firewall_block: fix multiple exception

- qemu/tests/cfg/hotplug_mem.cfg
If memory file in hugepage, both build-in memory and hotpluged
memory allocate from hugepages, so page number should be double.
> hotplug_mem: increase hugepage number

- qemu/tests/balloon_check.py
No need to call get_ballooned_memory() again after
utils_misc.wait_for(lambda: compare_mem ==
self.get_ballooned_memory(),...)
> balloon_check: Fix meaningless code

- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/single_driver_install.py
1. fix a syntax error.
The end double quote of variant "guest_alias" will be
analyzed as a string \" in raw string.
2. Update the path of driver virtio serial.
id: 1334077
> tp-qemu: single_driver_install: some corrections of code.

- qemu/tests/cfg/qemu_guest_agent.cfg
The previous filter will filter out the other os versions which we may not want to.
ID: 1334584
> fix the os version filter which cause problems

- qemu/tests/cdrom.py
The dbd7086 introduces (2. add qtree info when test failed)
But, No vm passed to get_match_cdrom(),
The order of (qtree_info, serial_num) is wrong.
> cdrom: revert: add qtree info when test failed

- qemu/tests/performance.py
utils_test.wait_for_login had been replaced with vm.wait_for_login
You can refer to virt-test/feea4fd.
> performance: Fix no attribute 'wait_for_login'

- qemu/tests/cfg/driver_load_stress.cfg
- qemu/tests/cfg/netkvm_in_use.cfg
> tp-qemu: add missing param in cfgs who call case "driver_in_use".

- qemu/tests/cfg/slof_dataplane_boot.cfg
Test this case on ppc64le host, passed. 
03:39:23 INFO | PASS 1-smp_8.8192m.repeat1.run_test.Host_RHEL.m7.u2.qcow2.virtio_blk.up.virtio_net.RHEL.7.2.ppc64le.io-github-autotest-qemu.slof_dataplane_boot
> Add cfg file for a slof case to boot guest with dataplane

- qemu/tests/qemu_img.py
For example,
'session.sendline(params.get("shutdown_command"))' was discarded,
"Shutdown command is sent, ..." is inapproprivate.
> qemu_img: improvements for the output

- qemu/tests/mq_change_qnum.py
In serial sessions, frequently the kernel might print debug or
error messages that make read_up_to_prompt to timeout. Let's try
to be a little more robust and send a carriage return, to see if
we can get to the prompt when safe=True.
Based: https://github.com/autotest/aexpect/pull/6
id: 1330906
> mq_change_qnum.py: Using safe mode when execute cmd in guest via serial.

- qemu/tests/qemu_io_blkdebug.py
Correct the CmdError exception to get stderr, which is usefull for the caller
> qemu_io_blkdebug: fix catcing exception for process.CmdError

- qemu/tests/qemu_io.py
"/tmp/test.qcow2" is extremely common and used by many cases.
In order to avoid the risk of destroying old image file,
It's better to rename the image.
In regard of QemuIOConfig.__init__ had used test.tmpdir,
we adopt the form "test.tmpdir" + "test.qcow2".
besides above,
remove unused variable and adjust the position of logging.info.
> qemu-io: Name the image path by means of test.tmpdir

- qemu/tests/live_snapshot_basic.py
replace '%' with '%s'  and remove unused variable.
> live_snapshot_basic: fix wrong format specifiers

- qemu/tests/qemu_io_blkdebug.py
As upstream commit 5be5b7764f83cf9a535a22ecbd33710daf1fe210 has been
merged in the release qemu-kvm-rhev-2.6.0-1.el7, BlkdebugEvent are named 
with an underscore instead of a period. Update the related events according 
to new naming rules.
> qemu_io_blkdebug: update BlkdebugEvent for upstream change

- qemu/tests/eject_media.py
- qemu/tests/macvtap_event_notification.py
- qemu/tests/pci_hotunplug.py
- qemu/tests/qmp_event_notification.py
commit 7ef4e5077731a9aba8853042ccbadf9370d24496
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Thu Jun 16 09:40:12 2016 +0800
pci_hotunplug: improve the way to distinguish monitor type
create_monitor() has chosen the proper monitor,
We can use vm.monitor.protocol to distinguish between qmp and hmp.
Not need to call qemu_has_option any more.
commit 4ca787d74d375b611dd00e32b9b15ee6d0e18fd5
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Thu Jun 16 08:58:00 2016 +0800
Fix wrong usage for qemu_has_option
If the param 'qemu_path' is default,
The utils_misc.qemu_has_option() takes qemu-kvm as test object,
Not the qemu specified by user. It's definition as follow,
def qemu_has_option(option, …
> fix wrong usage for qemu_has_option

- qemu/tests/cgroup.py
- qemu/tests/migration_multi_host_with_speed_measurement.py
- qemu/tests/migration_with_speed_measurement.py
commit 74886e9c789073ce5306b0ba1fbcf5e63e59dd4d
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Tue Jun 21 11:24:45 2016 +0800
cgroup: delete the percent sign
The variable is decimal, not percentage
No need to be followed by percent sign,
commit 62c2b6d2984b738a01d3023f4ad3c045bea5827b
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Tue Jun 21 10:18:29 2016 +0800
Fix format output for the ratio of migration speed
delete spaces between number and "%"
> Trivial fix for the usage of percentage

- qemu/tests/cfg/cpu_add.cfg
- qemu/tests/cpu_add.py
1. vcpu_need_hotplug for max_cpu scenario can not be a fixed num,
should be vcpu_need_hotplug = vcpu_maxcpus - vm.cpuinfo.smp
2. Rename param "id" to "cpuid", as there is same param in the object.
3. Enlarge waiting time after hotplug cpus, 60s is not enough for
max cpu hotplug.
id: 1348826
> cpu_add: some updates of code.

- qemu/tests/cfg/readonly_floppy.cfg
First, The original relative path of floppy images are not exist. There is no
'data/images/' folders under 'shared' folder by default, It causes 'dd' command
failures.
If adding code into 'pre_command' of readonly_floppy.cfg to check/create
'shared/data/images/', Then the second issue jumps out:
Because 'process_command' function in env_process.py will perform
... "cd %s; %s" % (test.bindir, pre_command) ...
The test.bindir's value is assigned to '/usr/share/avocado-plugins-vt',
So we got 2 fl images under /usr/share/avocado-plugins-vt/shared/data/images/.
But in the final qemu command line parameters which generating by avocado,
The path of floppy image is /usr/share/avocado/data/avocado-vt/images/...
So I think that we insert 'cd /usr/share/avocado' to pre_command for ignoring
the …
> Change the path of floppy images

- generic/tests/netstress_kill_guest.py
- qemu/tests/trace_cmd_boot.py
1. netstress_kill_guest: cleanup
1) use wait_until_dead() instead of os.kill()
2) remove setup_cmd/clean_cmd discarded by 0f39772
3) round is reserved by python. so s/round/i/
4) s/r_times/times/
2. trace_cmd_boot: trivial fix for wait time
Log shows it wait for 120s, actually it cost 180s.
> Netstress kill guest

- qemu/tests/cfg/qemu_io_blkdebug.cfg
As differnt errno are usually treated as the same code branch, test
one errno is good enough.
> qemu_io_blkdebug: fix qemu-io cases timeout issue

- qemu/tests/cfg/drive_mirror.cfg
Remove node-name and granularity in drive-mirror related test for RHEL6.
id: 1351903
Signed-off-by: Qianqian Zhu qizhu@redhat.com
> Remove node-name and granularity in drive-mirror related test for RHEL6

- qemu/tests/sr_iov_sanity.py
There are scenarios where the SR-IOV VF devices would not be created on host due to some issues related to SR-IOV setup on Host. Currently we do not check if we have VFs loaded after test_setup.PciAssignable. This commit would introduce this check on qemu test side. There is another commit on avocado-vt/virttest which would print ERROR message to users when VF device are not created.
> check SR-IOV VF device on host before proceeding with test

- qemu/tests/cfg/virtio_driver_sign_check.cfg
Dispose of '/usr/share/virtio-win/',
Use 'isos/windows/' for cdrom_virtio,
Use 'images/win7-64/' for floppy_name.
> virtio_driver_sign_check: Use the recommended and unified path

- qemu/tests/cfg/multi_disk.cfg
Signed-off-by: Nini Gu ngu@redhat.com
ID: 1348499
> multi_disk.cfg: Force to use aio=threads for scsi-generic disks created by scsi_debug

- qemu/tests/cfg/multi_vms_nic.cfg
- qemu/tests/multi_vms_nics.py
Current guest ip finding mechanism could not work if guest contains
multi nics. Use avocado api to get guest interface name and ip address.
> multi_vms_nic: fix get wrong ip address for linux guest

- qemu/tests/stop_continue.py
Close the sessions which were opened in stop_continue subtest to save the file descriptor in the process.
ID: 1340667
> pci_hotplug: close the session opened in sub_test 'stop_continue'

- qemu/tests/qemu_disk_img_snapshot.py
1. Image tag is defined in parameter images, so read the correct params.
2. Drop the useless class SnapshotTest.
> qemu_disk_img_snapshot: Fix incorrect params

- qemu/tests/block_stream.py
- qemu/tests/block_stream_check_backingfile.py
- qemu/tests/block_stream_reboot.py
- qemu/tests/block_stream_simple.py
- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/cfg/drive_mirror_negtive_tests.cfg
- qemu/tests/drive_mirror_cancel.py
- qemu/tests/drive_mirror_complete.py
- qemu/tests/drive_mirror_powerdown.py
- qemu/tests/drive_mirror_reboot.py
- qemu/tests/drive_mirror_simple.py
> qemu.tests: Unify usage of "source_image" in block_stream and drive_mirror related cases.

- qemu/tests/timedrift_no_net.py
- qemu/tests/timedrift_no_net_win.py
The error message has to use interpolation.
> timedrift: Fix wrong message for TestError

- qemu/tests/win_virtio_serial_data_transfer_reboot.py
fix assigned but never used local variable 'ports' and 'd_file'.
> win_virtio_serial_data_transfer_reboot: cleanup

- qemu/tests/cfg/rng_bat.cfg
- qemu/tests/rng_bat.py
1. use function in framework to enable driver verifier
2. no need to enable driver in linux guest
3. update code base on avocado framework
> Use function in framework to enable driver verifier

- qemu/tests/cluster_size_check.py
* s/Finall/Finally
* The logging begins with the timestamp,
calling logging.error continuously for one error will cause
multiple messages with different timestamp.
> cluster-size_check: Fix typo and update the error message

- generic/tests/ethtool.py
In python, variables that are only referenced inside a function
are implicitly global. And if a variable is assigned a new value
anywhere within the function's body, it's assumed to be a local.
so ethtool_save_params() doesn't truely store the ethtool status
into global variable 'pretest_status'. we can simply make use of
by 'global' to fix the problem, but it's not a good method.
> ethtool: fix wrong assignment for global variable

- qemu/tests/cfg/usb.cfg
- qemu/tests/format_disk.py
- qemu/tests/usb_storage.py
The usb_storage tests report couple of errors, says:
* missing blk_extra_params_stg
* Expected: '520fa169-32f8-431f-9f1e-70992671d2e5', Actual: 'TARGET_DISK0'
('520fa169-..' is generated dynamically, 'TARGET_..' is my blk_extra_params_stg)
* Can not get drive path by id 'NO_EQUAL_STRING
* Can not get drive path by id 'EMPTY_STRING'
This patch fixes above issues.
Signed-off-by: Lin Ma <lma@suse.com>
> qemu.tests.usb_storage: Fix serial params errors

- qemu/tests/cfg/multi_vms_nic.cfg
- qemu/tests/multi_vms_nics.py
To avoid the packet lose, need to make sure the vcpus + vhosts <= pcpus
and pin vcpus/vhosts into different cpu.
> multi_vms_nic: fix packet lose during command ping.

- qemu/tests/cfg/viorng_in_use.cfg
It will take long time in with some guest on some hw, set the loop in during_bg_test only
> Set random test in loop on during_bg_test only

- qemu/tests/cfg/qemu_cpu.cfg
Update CPUID test case config files to properly account for RHEL-7.2 known CPUID changes.
> qemu_cpu.cfg updates for RHEL-7

- qemu/tests/virtio_console.py
When the first check in sigio test fails, the exception does not log the
information from guest, which are essential in order to know why it went
wrong. Let's log it as well.
PS: I checked all other `guest_worker._cmd` uses and they already log
the data on failure.
> virtio_console: Log guest output on sigio failure

- qemu/tests/cfg/live_snapshot.cfg
> live_snapshot: parameter "node-name" does not support on RHEL.5 and RHEL.6 QMP.

- qemu/tests/virtio_console.py
The removed functions are suppose to clean previously set signals, which
is not really needed as the `set_poll_want_return` itself cleans the
signals. The only exception is when we close the port so let's add a
0.5s delay in order to make sure the signal was already emitted and wont
corrupt the testing.
> qemu: Remove unnecessary cleanup in virtio_console test

- qemu/tests/cfg/migrate.cfg
Fix $image to ${image} in migration.cfg
ID: 1365768
Signed-off-by: Huiqing Ding huding@redhat.com
> fix typo in migration.cfg

- qemu/tests/cfg/mq_change_qnum.cfg
1.reduce the filesize to 512
2.reduce the scp_para_sessions to 4
3.reduce the stress_timeout to 360
id: 1010795
Signed-off-by: weliao <weliao@redhat.com>
> Reduce stress and run time, too big stress caused case run ERROR.

- qemu/tests/cfg/migrate.cfg
- qemu/tests/migration_with_dst_problem.py
Change the path of image2 from tmp dir to "/usr/share/avocado/data/avocado-vt/".
ID: 1208357 
Signed-off-by: Huiqing Ding huding@redhat.com
> migration_with_dst_problem: fix the path of image2

- qemu/tests/block_stream_stress.py
- qemu/tests/cfg/block_stream.cfg
Steps should be: load_stress -> block_stream -> pause -> reset_speed ->
resume -> cancel -> block_stream -> reboot.
id: 1368013
> qemu.tests.block_stream: Add new test scenario for general block stream test.

- qemu/tests/cfg/rng_bat.cfg
- qemu/tests/rng_bat.py
random read sometimes failed because the driver status is "disabled"
check the status before read will make the failure more clear
> Add driver status check in rng_bat

- qemu/tests/cfg/rng_stress.cfg
- qemu/tests/rng_stress.py
1. Fetch data from /dev/random in guest and host at the same time
2. Switch rng device and fetch data
> Add more scenerios to rng device test

- qemu/tests/cfg/block_stream.cfg
> qemu.tests.block_stream: Enlarge timeout when reset speed to minimal.

- qemu/tests/qemu_disk_img.py
add sync operation on guest after create file on it.
ID: 1379522
> qemu_disk_img_commit: add sync operation on guest after create file.

- qemu/tests/cfg/ovs_qos.cfg
Delete option 100,10 for rate_brust_pairs.
There is no such option in Polarion test case, this is unnecessary to test since it will generate zero throughput.
id: 1386070
sign-off-by: Wei Liao weliao@redhat.com
> ovs_qos.cfg: delete option 100,10 for rate_brust_pairs

- qemu/tests/drive_mirror.py
image file will changing during block job complete, ignore
error then check again is necessary step.
ID: 1388326
> qemu.tests: ignore error in check target image is opened

- qemu/tests/cfg/netkvm_in_use.cfg
- qemu/tests/pci_hotplug.py
- qemu/tests/pci_hotplug_check.py
Signed-off-by: Cong Li coli@redhat.com
id: 1231126
> qemu.tests.pci_hotplug: Add default value of "wait_secs_for_hook_up".

- qemu/tests/live_snapshot_chain.py
Previous "snapshot_num = 20" does not work for other cases except "long_chain".
id: 1108413
> qemu.tests.live_snapshot_chain: update default value for "snapshot_num".

- qemu/cfg/host-kernel/Host_RHEL/6.cfg
- qemu/cfg/host-kernel/Host_RHEL/7.cfg
Simulated hardware configuration include in guest-hw.cfg.
Drop extra configuration for virtio_net because it block
macvtap related tests.
ID: 1388817
> tp-qemu: remove useless config in host-kernel.cfg

- qemu/tests/numa_stress.py
Remove the memoryfile generated in last round to release memory.
ID: 1167596
> numa.numa_stress: remove memoryfile to release memory

- generic/tests/cfg/multi_queues_test.cfg
- generic/tests/multi_queues_test.py
used postfix '_fixed' for params vcpu threads,
cores and sockets to avoid these params overwrite
in other configuration file.
ID: 1393237, 1241435
> tp-qemu.multi_queues_test: fix vcpus count

- qemu/tests/cfg/win_virtio_driver_update_test.cfg
Force ide drive_format  make create VM failed if VM is Q35 machine,
fix it by overwrite dirve_format to ahci if machine type is q35.
ID: 1593598
> qemu.tests.win_virtio_driver_update_test: fix dirve_format issue

- qemu/tests/cfg/block_stream.cfg
Need wait for block stream finished when streaming.
id: 1368013
> qemu.tests.block_stream.with_stress.cancel_async: Update case steps.

- qemu/tests/cfg/rh_kernel_update.cfg
- qemu/tests/rh_kernel_update.py
enable snapshot for disk image, and commit changes when OS updated.
so that we can skip logical about backup and restore OS.
ID: 1394120
> qemu.tests: use snapshot to avoid backup and retore steps

- qemu/tests/cfg/qemu_img_negative.cfg
- qemu/tests/rebase_negative_test_on_iscsi.py
Rebase an image to the other image to check whether cause core dump.
All the images are created on the iscsi lvm.
ID: 1368643
> Add negative case for subcommand rebase of qemu-img

- qemu/tests/balloon_stress.py
Using framework function get_guest_cmd_status_output() to execute cmd in guest,
in case session is unavailable sometimes.
id: 1231013 1231041
> qemu.tests.balloon_stress: fix session unavailable problem.

- qemu/tests/balloon_stress.py
commit 9c93182b6f7e3f44df454206247e6b794085c73b
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Wed Nov 23 15:56:33 2016 +0800
balloon_stress: Remove the check for guest os type
'only Windows' has been declared in balloon_in_use.cfg,
and it's parent tests also declared the same filter in
driver_load_stress.cfg and balloon_stress.cfg.
so the check for os type is redundant.
commit 61c80e531ae30ad229dce9adc93185634d257136
Author: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
Date:   Wed Nov 23 15:54:24 2016 +0800
balloon_stress: clean up
The method used to set memory balloon had been changed
in 6a9d829, The 'unit' never be used.
> Two commits about balloon stress test

- qemu/tests/cfg/qemu_disk_img.cfg
- qemu/tests/qemu_disk_img.py
- qemu/tests/qemu_disk_img_info.py
- qemu/tests/qemu_disk_img_rebase.py
1. move function to parent class fo reducing repetitive code.
2. correct the snapshot tag to get the right guest_file_name
for windows guest.
3. add case to change block interface for snapshot
ID: 1374196, 1374199
> qemu.tests: add case for external snapshot

- qemu/tests/cfg/hotplug_mem.cfg
Filter out 1G_hugepage tests for pseries because it does
not support that huge page size.
ID: 1393231
> hotplug_mem: filter out 1G_hugepage tests for pseries

- qemu/tests/cfg/driver_load_stress.cfg
Size of temporary file for iozone must be less than the disk size
ID: 1397635
> driver_load_stress: Update parameter for iozone

- qemu/tests/block_stream_drop_backingfile.py
I think it is 'expect_backingfile' not 'except_backingfile'
>  Fix a typo

- qemu/tests/cfg/boot_order_check.cfg
- qemu/tests/cfg/single_driver_install.cfg
1. fix typo in single_driver_install.cfg.
2. add q35 configurations in boot_order_check.cfg.
id: 1400456
> qemu.tests: Update q35 configurations for some cases.

- qemu/tests/cfg/drive_mirror.cfg
1. Disable host rhel6 support for pause_resume_job.
2. Reboot guest after mirroring with node name. 
id: 1330404, 1330410, 1360154
> drive_mirror.cfg: Disable host rhel6 support for pause_resume_job.

- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
> single_driver_install.cfg: param "kill_after_test" is invalid now, using "kill_vm" instead

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_check.cfg
qemu.tests.balloon_check: sleep 90s for guest reboot
balloon_check:
1.Set time sleep 90s before get guest's used memory after sub-test:reboot
ID:1396878
> Balloon_check: sleep before subtest check

- qemu/tests/multi_vms_nics.py
1.Test no need ping itself ip.
2.When ping itself ip with -I eth0, will ping failed.
ID: 1375446
Signed-off-by: Wei Liao weliao@redhat.com
> qemu.tests.multi_vms_nic:no need ping itself ip

- qemu/tests/cfg/drive_mirror.cfg
Extend gruanularity512 wait_timeout, and reopen after mirroring
id: 1330414, 1342425
> drive_mirror.cfg: Extend gruanularity512 wait_timeout

- qemu/tests/cfg/rng_bat.cfg
- qemu/tests/cfg/rng_hotplug.cfg
- qemu/tests/cfg/rng_stress.cfg
- qemu/tests/cfg/viorng_in_use.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
the default letter of winutils.iso is WIN_UTILS
> Update the letter of winutils to WIN_UTILS in cmd

- qemu/tests/cfg/block_stream.cfg
- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/cfg/live_snapshot.cfg
- qemu/tests/cfg/live_snapshot_chain.cfg
block job test will eat a lots of caches in testing,
free caches  after test to avoid VM hang memory.
ID: 1267186
> qemu.tests: free caches in block copy test

- qemu/tests/cfg/rng_bat.cfg
- qemu/tests/cfg/rng_hotplug.cfg
Need to use /dev/random instead of /dev/hwrng
/dev/random is the place from where we should always read.
/dev/hwrng will be available to read if there is a hardware rng device
id:1403651
> Update /dev/hwrng to /dev/random for rng random read

- qemu/tests/cfg/drive_mirror.cfg
Remove mirroring to qcow2 on iscsi.
When drive mirroring with qcow2 image on iscsi, it will cause mismatch issue, which is caused by iscsi instead of qemu,
so only test raw image on iscsi, qcow2 matrix will be covered with local and nfs storage.
id: 1353787
Sign-off-by: Qianqian Zhu <qizhu@redhat.com>
> drive_mirror: Remove mirroring  to qcow2 on iscsi.

- qemu/tests/cfg/pci_devices.cfg
xhci is not supported on RHEL.6 host.
id: 1408899
> disable xhci on RHEL.6 host.

- qemu/tests/cfg/block_stream.cfg
block job pause and resume for storage migration are not supported on RHEL.6 host.
id: 1409046
> disable block job pause and resume for storage migration on RHEL.6 host.

- qemu/tests/block_hotplug.py
- qemu/tests/cfg/block_hotplug.cfg
- qemu/tests/stop_continue.py
1. block_hotplug.cfg: add separate scenario for repeated plug/unplug, no need repeat 300 times for each scenario when one pci.
2. block_hotplug.py: get and close a separate session when using it to fix file descriptor out of range problem.
3. stop_continue.py: close session when test finished.
id: 1332870
> qemu.tests.block_hotplug: some improvements for the code.

- qemu/tests/flow_caches_stress_test.py
- qemu/tests/migration_with_netperf.py
- qemu/tests/multi_nics_stress.py
- qemu/tests/netperf_stress.py
- qemu/tests/netperf_udp.py
- qemu/tests/ovs_qos.py
tests.netperf_stress:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient"
tests.netperf_udp:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient"
tests.flow_caches_stress_test:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient"
tests.migration_with_netperf:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient"
tests.multi_nics_stress:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient"
tests.ovs_qos:
1.add params of "prompt,linesep, status_test_command"
2.pass these params to "NetperfServer/NetperfClient" …
> qemu.tests:get "prompt,linesep,status_test_command" from OS's config file

- qemu/tests/cfg/single_driver_install.cfg
According to new policy, all RHEL host will use the latest virtio-win drivers.
And latest virtio-win serial driver use "VirtIO Serial Driver".
id: 1408629
> qemu.tests.single_driver_install:update virtio serial device name to keep same with the latest virtio-win version

- qemu/tests/cfg/live_snapshot.cfg
- qemu/tests/cfg/live_snapshot_negative.cfg
- qemu/tests/live_snapshot_negative.py
1. separate live snapshot negative tests from live_snapshot.cfg to a new configuration.
2. rename live_snapshot_negative_test.py to live_snapshot_negative.py for a uniform format.
And also rename the class name in it.
3. update error match string for RHEL.6 host.
id: 1409054
> qemu.tests: some updates for live_snapshot negative tests.

- generic/tests/cfg/pxe_boot.cfg
Avoid to set bootindex to disk.
ID: 1377165
> pxe_boot: avoid to set bootindex to disk

- generic/tests/iometer_windows.py
ID: 1270217 
1. replace cmd to cmd_status_output,when iometer failed
print the iometer error info
Signed-off-by: Meng Yang meyang@redhat.com
> Print error info when iometer_windows test failed

- qemu/tests/cfg/rh_qemu_iotests.cfg
- qemu/tests/rh_qemu_iotests.py
1. Update cases for qcow2/raw/vmdk image format
2. Add case for vhdx image format
ID: 1395551, 1395552
> qemu.tests: add case to run qemu_iotests

- qemu/tests/numa_stress.py
Add -p option for mkdir to avoid error if directory exists, and remove it in finally.
ID: 1412083
> numa.numa_stress: Add -p option for mkdir to avoid error if directory exists

- qemu/tests/cfg/block_hotplug.cfg
In some enterprises, the default bootindex is -1 for system disk,
which means cancel the boot index.
If hotplug a data disk then reboot guest, qemu may set the data
disk with higher bootindex, which depends on different enterprises'
policies.
As above, need set bootindex=0 for system disk.
id: 1412718
> qemu.tests.block_hotplug: set bootindex=0 for system disk.

- qemu/tests/cfg/readonly_disk.cfg
- qemu/tests/readonly_disk.py
ID: 1162412
1. replace the vols using function set_winutils_letter.
2. print the output of the cmd executed in guest.
(1/2) smp_16.16384m.repeat1.run_test.Host_RHEL.m6.u9.qcow2.virtio_scsi.up.virtio_net.Win7.x86_64.sp1.io-github-autotest-qemu.readonly_disk: PASS (433.68 s)
(2/2) smp_16.16384m.repeat1.run_test.Host_RHEL.m6.u9.qcow2.virtio_scsi.up.virtio_net.Win7.x86_64.sp1.io-github-autotest-qemu.readonly_disk.with_wrerror: PASS (433.83 s)
Signed-off-by: Meng Yang meyang@redhat.com
> improve the script of readonly_disk

- multi_host_migration/tests/migration_multi_host_timedrift.py
1. Delete redundant characters in return value
ID: 1411686
> qemu.test: fix guest didn't use kvm-clock in migration_multi_host_timedrift

- qemu/tests/cfg/drive_mirror.cfg
ID:1263071
linux-2.6 doesn't support ppc64le compiling , update it to linux-4.8 version.
> Switch the kernel source code version to support ppc arch kernel compiling

- qemu/tests/cfg/drive_mirror.cfg
Redistribute boot_target_image to meet cases description.
id: 1146789, 1330404
> drive_mirror: Redistribute boot_target_image to meet cases description.

- qemu/cfg/host-kernel/Host_RHEL/6/4.cfg
- qemu/cfg/host-kernel/Host_RHEL/6/5.cfg
- qemu/cfg/host-kernel/Host_RHEL/6/6.cfg
- qemu/cfg/host-kernel/Host_RHEL/6/7.cfg
- qemu/cfg/host-kernel/Host_RHEL/6/8.cfg
As bug 1063124: Fail to boot windows 2012/win8.1/win8 x86_64 guest with '-cpu SandyBridge/Opteron_G4' with hv_relaxed flag, remove this flag ans add note.
> host-kernel: remove cpu flag "hv_relaxed" as some win guest failed to boot with it

- qemu/tests/flow_caches_stress_test.py
The commit 2687b22 "qemu.tests:modify netperf related script"
assigns shell prompt to variable 'shell_prompt',
but pass 'prompt' to utils_netperf.NetperfServer().
> flow_caches_stress_test: Fix undefined name 'prompt'

- qemu/tests/nic_bonding_host.py
As recommended in bonding module document, set miimon
value to 100 when insert bonding module.
ID: 1081151
> qemu.tests: set miimon param for bonding module

- qemu/tests/cfg/fio_windows.cfg
- qemu/tests/fio_windows.py
1. fix typo error and improve finally, which will cover the key error
2. update test_timeout to cmd_timeout as the name is the same as job timeout in framework
id:1412887
> Fix typo and cfg of fio_windows

- qemu/tests/usb_host.py
usb.usb_host: fixs a string formatting error for communicating with HMP
ID:1422746
> usb.usb_host: fixs a string formatting error for communicating with HMP

- qemu/tests/cgroup.py
When test cgroup.memory_memsw_limit, the qemu process will be
killed because of exceeding limit. So sending command "true"
will lead to ShellTimeOut error. When test cgroup.memory_limit,
although exceeding limit, the qemu process won't be killed.
So sending command is ok.
> check virtual mechine is alive or not before sending command

- qemu/tests/cfg/multi_disk_random_hotplug.cfg
- qemu/tests/multi_disk_random_hotplug.py
1. Add codes to handle unplug error caused by cmd '__com.redhat_drive_del'
2. Change all monitors to QMP ones
3. Add sleep time between/after hotplugs/unplugs
ID: 1303513
> multi_disk_random_hotplug: Add codes to handle the hot_unplug error caused by cmd '__com.redhat_drive_del'

- qemu/tests/cfg/qcow2perf.cfg
Drop the variants summary_qcow2perf as there is no requirement to track.
ID: 1408924
> qcow2perf: drop the outdate variants

- qemu/tests/cfg/multi_disk_random_hotplug.cfg
usb-echi controller could not be used to attach usb-tablet in RHEL.6 host, so update to use the ich9-usb-ehci1 one
ID: 1426498
> multi_disk_random_hotplug: Update the usb controller for RHEL.6 host

- qemu/tests/cfg/rh_qemu_iotests.cfg
Drop the parameter "--force", rpmbuild will apply all
patches to source code.
ID: 1431319
> rh_qemu_iotests: drop parameter --force

- qemu/tests/cfg/qemu_io_blkdebug.cfg
- qemu/tests/qemu_io_blkdebug.py
As command perror is not installed in some hosts, replace
perror with os.strerror
ID: 1409205
> qemu_io_blkdebug: replace perror with  os.strerror

- qemu/tests/cfg/multi_nics_hotplug.cfg
- qemu/tests/cfg/multi_nics_stress.cfg
- qemu/tests/cfg/multi_nics_verify.cfg
- qemu/tests/cfg/single_driver_install.cfg
when boot vm with multi nics, sometimes wrong nic index will cause
login guest failed,flexible_nic_index=yes can help avoid this issue
> Add "flexible_nic_index = yes" for multi nics related cases

- qemu/tests/cfg/migrate.cfg
Enable automem maybe cause source VM command line different
with destination VM command line. This case, migration test
maybe failed, so disable it to avoid unexpected test fail.
> qemu.migration: disable automem to avoid migration failed

- generic/tests/iometer_windows.py
Param 'run_timeout' define in test configuration but not used
it cause iometer commands run timeout in lower performance
machines.
ID: 1437841
> generic.tests: fix iometer command timeout issue

- qemu/tests/pxe_query_cpus.py
There is an issue that the tftp packages has already arrived before the
script starting to snoop them, so stop VM until subtest began.
ID: 1439569
> qemu.test.pxe_query_cpus: stop VM until subtest began

- qemu/tests/cfg/drive_mirror_negative_tests.cfg
Setup iscsi target on localhost for negative tests.
id: 1415588
> drive_mirror_negative_tests: Setup iscsi target on localhost.

- qemu/tests/cfg/usb.cfg
added 'no usb-ehci' into usb-hub and usb-ccid related variants to drop
these cases.
ID: 1441539
> qemu.tests.cfg.usb.cfg: fix usb controller speed mismatch problem

- qemu/tests/ksm_overcommit.py
Correct the path of the script 'ksm_overcommit_guest.py'.
ID: 1438134
> ksm_overcommit: Correct ksm_overcommit_guest.py path

- qemu/tests/cfg/pci_bridge.cfg
- qemu/tests/pci_bridge_block_stress.py
Limit the number of block devices to 10 temporarily until
Bug 1410315 - [KVM_AUTOTEST] RFE: Failed to insert more than 19 block devices under pci-bridge resolved.
ID: 1405362
> New case to attach 31 virtio-block devices to a pci-bridge

- qemu/tests/cfg/virtio_port_login.cfg
udev in latest rhel linux can generate serivce file for new
vport and vconsole, skip generate if the file exist in guest
os to avoid unexpect exception.
ID: 1157474
> qemu.tests: skip generate serivce file if it exist

- qemu/tests/cfg/boot_from_device.cfg
add "usb-ehci" and "nec-xhci" variants into boot_from_usb_stg，
so that it will test both controllers.
ID: 1369672
> qemu.tests.cfg.boot_from_device.cfg:add nec-usb-xhci support

- qemu/tests/balloon_check.py
balloon_check:set windows evict balloon_illegal_value to "0"
qemu.tests.balloon_check:
1.set windows evict balloon_illegal_value to "0"
Signed-off-by:Aihua Liang<aliang@redhat.com>
ID: 1372561
> balloon_check:set windows evict balloon_illegal_value to "0"

- qemu/tests/nic_hotplug.py
Instead nic name with nic index when get IP address of the nic.
ID: 1442685
> qemu.tests: fix syntax in nic_hotplug test

- qemu/tests/cfg/qemu_option_check.cfg
ID: 1443887
On power platform , rtl8139 and e1000 nic device are not supported. 
This patch disabled these two device and enabled spapr-vlan device which is specific for power
> ppc64le: qemu_option_check, Add spapr-vlan device support and disable rtl8139&e1000 for power platform

- qemu/tests/balloon_boot_in_pause.py
- qemu/tests/balloon_check.py
100s is a little short for some host, update the default value to 300,
otherwise need to update lots cfg file
id: 1446042
> Update balloon_time default value

- qemu/tests/cfg/boot_order_check.cfg
Del the unmatched sentences for status checking, update to matched ones. 
ID: 1447594
> qemu.tests.boot_order_check: Update boot_order_check config

- qemu/tests/rv_logging.py
The typo has been fixed in the product code. 
Signed-off-by: Swapna Krishnan <skrishna@redhat.com>
> qemu.tests.rv_logging.py: Use "quitting" instead of quiting

- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/drive_mirror.py
Remove granularity check since qemu2.9 disable the guranularity display in block job info. Only make sure block mirror success also fit test case requirement.
id: 1443419
> drive_mirror: remove granularity check since qemu2.9 disable the guranularity display in block job info.

- qemu/tests/cfg/migrate.cfg
There is no need to disable this test on JeOS, it does not require any
extra programs on guest, nor features unavailable there. The only issue
might be using too big file, but the default setting works well.
> Enable migrate.with_file_transfer on JeOS

- .travis.yml
Sphinx 1.4.9 is the last version that supports Python 2.6.
Signed-off-by: Yanbing Du <ydu@redhat.com>
> travis: lockdown Sphinx version for python2.6

- qemu/tests/virtio_console.py
A reference error which affects the rmmod() function in virtio_console.py.
id: 1451239
> qemu.tests.virtio_console: fix reference error

- qemu/tests/cfg/check_block_size.cfg
- qemu/tests/check_block_size.py
qemu.tests.check_block_size: add support for windows guest
qemu.tests.check_block_size:
1.add block check cmd for windows
qemu.tests.cfg.check_block_size:
1.add test guest--windows
2.disable win7,win2008 and win2008r2 temporarily for no suitable disk_check_cmd
3.divided cases to base and installation(avoid vfd installation)
Signed-off-by:Aihua Liang<aliang@redhat.com>
ID:1134252
> check_block_size: Add test for windows guest

- qemu/tests/rv_connect.py
Sometimes, the tests fail since it takes longer to startup and the
test doesn't wait for remote-viewer to completely start up
> qemu.tests: Increasing waittime from 5 to 15 seconds

- qemu/cfg/tests-spice.cfg
Updating the tests-spice.cfg file for RHEL 7 and also removing
the need to restart the VM for every test as only some tests need
it.
> qemu.cfg: Updating for RHEL 7

- qemu/tests/cfg/fio_perf.cfg
- qemu/tests/fio_perf.py
add fio performance test for block
The scripts should support:
1) platform: only x86_64 now
2) data disks: only single disk
3) backends: localfs, nfs, fusion-io
4) guests: windows and linux guest
id: 1434695
> fio_perf: add fio performance test for block

- generic/tests/netperf.py
netperf : Use grep command to ignore the command line itself was added into ouput
Signed-off-by : Wenli Quan  <wquan@redhat.com>
Bug id: 1435584
> Use grep command to ignore the command line itself was added into ouput

- qemu/tests/cfg/fio_perf.cfg
Add support for ppc64 and ppc64le in fio block performance test. Because we usually don't test dataplane nether x86_64 nor ppc, I remove dataplane configuration.
bug id: 1460906
> fio_perf: add support for ppc64 and ppc64le and remove localfs dataplane in fio block performance test

- qemu/tests/cfg/viorng_in_use.cfg
viorng_in_use: add missing parameter
viorng_in_use call subtest rng_bat, but param 'driver_id_pattern' is
not defined in the configuration file of viorng_in_use, so need to
add it accordingly.
ID:1466218
> viorng_in_use: add missing parameter

- qemu/tests/cfg/usb.cfg
- qemu/tests/usb_storage.py
The guest will auto mount usb disk after reboot when the usb disk
was made file system. Since removable usb disk will not available,
unmount the usb disk before running subsequent tests.
Bug id: 1452071
> usb_storage: unmount usb disk before running subsequent tests

- qemu/tests/cfg/multi_disk_random_hotplug.cfg
Need more time to wait between unplugs on ppc64le and ppc64.
bug id : 1443474
> multi_disk_random_hotplug.cfg: add ppc64le and ppc64 wait time

- generic/tests/netperf.py
Ideally, guest needs to boot up with two nics, one is for connection,
the other is for testing. but in mostly guest, only one ONBOOT=yes
in configuration ifcfg-ethx, need to force to restart_network on vm.
id :1464915
> Netperf: add restart_network=True for multiple nics on vm

- generic/tests/netperf.py
Rhel 7.4 uses systemctl to control services instead of service command
id : 1463560
> Netperf: add stop firewall service for rhel7.4 guest

- qemu/tests/cfg/fio_perf.cfg
- qemu/tests/fio_perf.py
NVMe backend is new test requirement.
bug id: 1467831
> fio_perf: add NVMe backend for block performance test

- qemu/tests/cfg/mlock_basic.cfg
- qemu/tests/mlock_basic.py
New case: mlock_basic: Get nr_mlock and nr_unevictable in host before and after VM start, check with VM memory when mlock is on/off.
ID: 1467174
> mlock_basic: Get nr_mlock and nr_unevictable in host before and after VM start, check with VM memory when mlock is on/off.

- qemu/tests/cfg/sr_iov.cfg
- qemu/tests/sr_iov_hotplug.py
1. After hotplugging the sriov vf interfaces, test might fail due to unavailibilty of
ip address and interface remains inactive. param assign_static_ip can be set if static
ip configuration is required.
2. Removed autotest dependencies.
> sr_iov_hotplug: Enabled static ip configuration for hotplugged interface

- qemu/tests/rh_kernel_update.py
Maxinum 15 mins spend in my 5 tests, set double redundancy for extreme network.
id : 1469028
> Rh_kernel_update: enlarge timeout of install_rpm to 30mins to avoid case failed in bad network traffic.

- qemu/tests/cfg/data_plane_snapshot.cfg
New case: boot guest with data plane enable and snapshot=on
Bug id:1434267
> New case: boot guest with snapshot=on and data plane enable

- qemu/tests/set_link.py
ID: 1479658  1477801
Once a time, patches updated the method to check the network connection b/w guest and host. But the interface name was not updated meanwhile, this will cause problems if the interface name of guest and host is different.
> set_link: Update the method of getting IP of guest and correct the parameter value of network connection checking function

- qemu/tests/cfg/multi_nics_stress.cfg
change vm name to vm1 in order to boot 4 nics on vm1 as before
id:1479121
> change nics_virt-tests-vm1 to vm1 in multi_nics_stress.cfg

- qemu/tests/cfg/qemu_img.cfg
Make qemu_img.amend compatible with new host version
id:1480461
> qemu.tests.qemu_img: correct the configuration

- generic/deps/clock_getres/clock_getres.c
Arm uses "arch_sys_counter" and not "kvm-clock". Let's adjust the
sources to cope with that.
> clock_getres: Add support for arm

- qemu/tests/zero_copy.py
In current qemu, user networking (i.e. "-netdev user") doesn't
support "vhost" option. This patch checks the nettype in
configuration. If nettype="user", it will give a warning and
cancel zero_copy test instead of flaging it as an error.
Signed-off-by: Wei Huang <wei@redhat.com>
> zero_copy: Check nettype for zero_copy test

- qemu/tests/multi_nics_verify.py
> qemu.tests.multi_nics_verify: fix the escape character issue to let the second one work

- qemu/tests/win_virtio_serial_data_transfer_reboot.py
According the following msdn doc, the return code 2 of a verifier
command can be ignored since it is harmless.
https://msdn.microsoft.com/en-us/windows/hardware/drivers/devtest/verifier-command-line
ID: 1438140
> win_virtio_serial_data_transfer_reboot: fix the bug of verifier

- qemu/tests/cfg/driver_load_stress.cfg
1. Update the cfg base on the update of balloon_stress cfg file
2. Set the balloon_test flag in the get_memory_boundary,
as the balloon operation is executed, and becasue the boundary balloon time
is different for different mem, which will make the wait_time different.
id: 1426039
> Update driver load stress cfg file

- qemu/tests/smbios_table.py
The smbios_table test sets machine type, but arm is a bit different and
it requires the `arm64*` prefix to correctly detect the machine. Let's
allow that by inheriting the prefix from the original `machine_type`.
> smbios_table: Support for arm

- generic/tests/cfg/boot_vm_in_hugepage.cfg
Only 2M and 1G can not cover all the hugepage size, add 16M and 512M too.
id:1488303
> generic.tests.boot_vm_in_hugepage: Add multi variants to test with different hugepage size

- qemu/tests/cfg/virtio_port_login.cfg
- qemu/tests/virtio_port_login.py
id: 1468452
Serial-getty@hvc0.service failed to be enabled because hvc0.service has been masked and linked to /dev/null.
> virtio_port_login.virtio_console : correct the port login timeout error

- generic/tests/avocado_guest.py
- generic/tests/cfg/avocado_guest.cfg
Added test to support avocado tests run inside guest
Single or multiple avocado tests can be run by single
invocation of this test.
Changes from previous version:
Added support for multiple tests
> RFC: Added support to run avocado tests inside guest

- qemu/tests/cfg/usb_device_check.cfg
- qemu/tests/usb_common.py
- qemu/tests/usb_device_check.py
add usb_device_check.cfg for define params of each usb check cases.
add usb_common to handle usb device common behaviors for all usb tests.
add usb_device_check to run usb check cases.
id: 1324310
> Add usb device check cases

- qemu/tests/cfg/usb_device_check.cfg
add case add multi_hubs_in_parallel, it attachs eight hubs on one hub
id: 1491103
> cfg.usb_device_check:add multi_hubs_in_parallel

- qemu/tests/cfg/usb_device_check.cfg
Add two cases for input devices:
input_devices_under_one_hub,
it attachs usb mouse kbd and tablet on one hub.
input_devices_under_two_tier_hub,
it attachs usb mouse kbd and tablet on a two-tier hub.
id: 1491551 1491547
> usb_device_check: add check input devices under hub

- qemu/tests/boot_with_machine_types.py
- qemu/tests/cfg/data_plane_boot.cfg
New case: boot guest under different machine type with data plane enable
Merge data_plane_snapshot.cfg to data_plane_boot.cfg
Bug id:1467485
> New case: boot guest under different machine type with data plane enable

- qemu/tests/cfg/usb_device_check.cfg
- qemu/tests/usb_device_check.py
- qemu/tests/usb_device_check_negative.py
Add multi_hubs_in_series negative and hub_speed_mismatch in
usb_device_check_negative.py.
Add a new usb_device_check_negative.py to run the negative test.
Fix typos.
id: 1492615 1492970
> Add usb hub negative tests

- generic/tests/cfg/unattended_install.cfg
Add two parameters for comfirming the system disk
ID: 1489761
> multi_disk_install: add parameters for system disk

- qemu/tests/nvdimm.py
This issue only exist in case nvdimm.nvdimm_basic. This case does not use "start_vm = no", but "nvdimm_dax" be assigned only when "start_vm = no", so this case will failed as "local variable 'nvdimm_dax' referenced before assignment" in "finally".
id: 1496302
> qemu.tests.nvdimm: Avoid "nvdimm_dax" be referenced before assignment

- qemu/tests/cfg/usb_device_check.cfg
- qemu/tests/usb_common.py
Add max_devices_under_one_hub, to check 8 usb mouse attatced to one usb hub.
Add usb_mouse, to check a usb mouse attached without usb hub.
usb_mouse_and_tablet checks a usb mouse and tablet without usb hub.
usb_kbd checks a usb keyboard without usb hub.
usb_common: modified imported modules to make it compatible with both python 2.6 and 2.7
id: 1493404 1493413 1493420 1493423 1494469
Signed-off-by: Haotong Chen hachen@redhat.com
> usb_device_check: add check max_devices_under_one_hub and mouse/tablet/kbd cases

- qemu/tests/cfg/rh_kernel_update.cfg
Make kernel_re and knl_dbginfo_re more strict to avoide updating
guest kernel to unstable versions.
id: 1500249
> rh_kernel_update: updated kernel_re and knl_dbginfo_re

- qemu/tests/cfg/migrate.cfg
delete "only Host_RHEL.m6" in cfg file
id: 1491527
> migrate.cfg: fix migrate.between_vhost_novhost cannot run on RHEL7 host

- qemu/tests/cfg/viorng_in_use.cfg
- qemu/tests/driver_in_use.py
Add with_live_migration variant to support live migraion during
virtio rng is in use.
ID:1231659
> viorng_in_use: Live migration while rng device in use

- qemu/tests/cfg/virtio_console.cfg
- qemu/tests/virtio_console.py
(1) update and extend test for boot_to_much_ports
Port number has been extended from 32 to 512 for 2.x.x version, so update test case.
(2) disable loopback test between consoles
Data transfer test for console is invalid according the former test result.
(3) update error module with error_context
(4) remove try.. except in run() that covers every function
Without it step, exceptions can also be correctly raised in separate function, so delete this step to avoid importing avocado.core in this script.
id: 1472105, 1468463, 1468458
> virtio_console.py: update and extend test for boot_to_much_ports

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
Ksm uses a lot of processing power, we need to disable it. it takes
30% cpu usage (16cpus) in my tests.
ID: 502942
> Netperf: disable ksm for performance issue

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
1.Qemu-ga cmd "guest-set-user-password" support windows guest without encryption.
2.Change new password to a complex one for windows requirment.
ID: 1490227 
> qemu_guest_agent: Support "guest-set-user-password"  for windows guest

- qemu/tests/blk_stream.py
- qemu/tests/block_stream_check_backingfile.py
base image option: only sectors above this image are streamed.(optional)
So if there is only one snapshot, base->sn1, the stream will start from sn1
to sn1, that means no data streamed, so it will complete immediately and
still have base as it backing file, which cause backing file check failed.
Fix:
1. By default set base option to None. Currently only case
block_stream.backingfile_option need to set this option.
2. Set base to guest image_file only when call set_backingfile() function.
3. If base is none, then check_backingfile_exist() should not be called,
it will report error.
id: 1496671
> block_stream: Set default base to None.

- qemu/tests/sr_iov_hotplug.py
- qemu/tests/sr_iov_sanity.py
qemu.tests: Update invoking of test_setup.PciAssignable accordingly.
Depends on https://github.com/avocado-framework/avocado-vt/pull/1152.
> qemu.tests: Update invoking of test_setup.PciAssignable

- qemu/tests/cfg/qemu_disk_img.cfg
The temproray image new.qcow2 is used to test the scenario qemu-img
rebase, Should not be booted up. Since qemu 2.10, image locking is
enabled which make multiple QEMU processes cannot write to the same
image, even if boot snapshot and backing file at the same time are
not allowed.
ID: 1509832
> qemu_disk_img: Drop the temporary image from boot list

- generic/tests/cfg/netperf.cfg
Enabled that two params bring a slightly cpu enlarge in test, so diable
them for performance issue.
ID: 1501049
> Netperf: disable params take_regular_screendumps and store_vm_register

- qemu/tests/cfg/openflow_acl_test.cfg
openflow_acl_test: remove two telnet sub-cases for Windows guests because telnet server is no longer supported
1. access_deny_all_target.telnet
2. access_deny_special_target.telnet
ID: 1475103
> openflow_acl_test: remove two telnet sub-cases for Windows guests

- qemu/tests/cfg/usb_device_check.cfg
- qemu/tests/usb_common.py
- qemu/tests/usb_device_check.py
Make all current usb device check cases support for Windows.
id: 1504516
> usb_device_check: add windows test support

- generic/tests/cfg/unattended_install.cfg
The 'timeout' variable that was set had no effect, 'install_timeout' is
the one that should be used.
> Reduce unattended import install to 3 minutes

- qemu/tests/cfg/usb.cfg
- qemu/tests/cfg/usb_device_check.cfg
- qemu/tests/usb_common.py
Added qemu-xhci on usb.cfg and usb_device_check.cfg.
Fixed a logging bug.
id: 1509825
> usb.cfg: Add qemu-xhci support

- qemu/tests/cfg/check_block_size.cfg
check_block_size.4096_4096:disable ide in this case,
for ide's logical_block_size must be 512.
bug id:1509097
> Disable ide in case "check_block_size.4096_4096"

- qemu/tests/cfg/multi_nics_stress.cfg
ID: 1512404
In the previous shell command, the "dhclient process" will not be run
successfully, because there is already a active dhclient process. The
updated shell command will terminate the previous one before runing
next.
> multi_nics_stress.cfg: terminate the dhclient processs before runing next one

- qemu/tests/balloon_hotplug.py
- qemu/tests/cfg/balloon_hotplug.cfg
add optional steps to support reboot/shutdown guest after hotplug
or hot-unplug balloon devices
ID:1456107,1456149,1456150,1456108
> balloon_hotplug:reboot/shutdown guest after plug/unplug balloon device

- multi_host_migration/tests/cfg/multi_host.cfg
- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/cfg/live_snapshot.cfg
- qemu/tests/cfg/win_heavyload.cfg
- qemu/tests/win_heavyload.py
1. To avoid heavyload process damage guest image which will effect other
testing, backup the image before testing and restore it after test finished.
2. After heavyload test finished, keep guest running for a while to make sure
it work well.
id: 1437304
> qemu.tests.win_heavyload: backup image before test and restore it after test

- qemu/tests/block_stream.py
qemu2.10 starts to prevent qemu-img access an operating image,
therefore it will prompt CmdError when check image size by qemu-img.
So check size via qmp monitor if catch such error.
id: 1510732
> block_stream: Add monitor method check size for qemu2.10

- qemu/tests/drive_mirror_complete.py
To enable "-U" option for "qemu-img compare", avoid access error.
Depends on https://github.com/avocado-framework/avocado-vt/pull/1228
id: 1513863
> drive_mirror: Add "force_share=True" for "qemu_img.compare_images"

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
When netdst is switch, set specified mtu on host/client/guest
(linux/windows) before netperf start tests.
ID: 1485855
> Netperf: add jumbo test scenario

- qemu/tests/boot_with_machine_types.py
- qemu/tests/smbios_table.py
1. The return value of utils_misc.get_support_machine_type has changed,update
function call to match it.
2. Add "remove_alias = True" for smbios_table.
Depends on: https://github.com/avocado-framework/avocado-vt/pull/1218
id: 1510766
> smbios_table: Update function call as the definition be changed

- qemu/tests/cfg/device_option_check.cfg
- qemu/tests/device_option_check.py
When the winutils disk letter happen to change in guest,
the "cmd = D:\hddsn.exe C:"  cannot be executed successfully.
Here changed it to "cmd = WIN_UTILS:\hddsn.exe C:",
and used the set_winutils_letter() to set the correct disk letter.
id:1511391
> device_option_check.blk_serial_check: change the disk letter of winutils disk

- qemu/tests/pci_devices.py
Mostly spelling wording changes to make it update with the
Avocado-VT/VirtTest terms.  And the shebang which can safely
go.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> qemu/tests/pci_devices.py: trivial fixes

- qemu/tests/cdrom.py
utils_misc.find_substring will logged every mismatch info. When
we call it in "get_match_cdrom", the mismatched info will be logged
until the matched cdrom found. This will cause misleading. So replace
it directly by re.
bug id:1511747
> Optimize function "get_match_cdrom" not to log mislead info

- qemu/tests/cfg/sr_iov_sanity.cfg
- qemu/tests/sr_iov_sanity.py
1. User can opt for dhcp IP or a static IP configuration for probed interfaces inside guest. 
Added option for static IP configuration in this commit.
2. Not all test environments would have a dhcp server to serve IP for
random mac addresses. So configure_on_host param has been
introduced to choose whether configure VFs with dhcp IP on host or not
Signed-off-by: Santwana Samantray <santwana@linux.vnet.ibm.com>
> Modify SRIOV sanity test to include VF static IP configuration scenario

- qemu/tests/balloon_hotplug.py
- qemu/tests/block_copy.py
- qemu/tests/cfg/balloon_check.cfg
- qemu/tests/cfg/balloon_hotplug.cfg
- qemu/tests/cfg/floppy_test.cfg
- qemu/tests/cfg/live_backup.cfg
- qemu/tests/cfg/live_snapshot_chain.cfg
- qemu/tests/cfg/multi_disk.cfg
- qemu/tests/cfg/nic_hotplug.cfg
- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/cfg/seabios.cfg
- qemu/tests/cfg/spice.cfg
- qemu/tests/cfg/unittest_kvmctl.cfg
- qemu/tests/cfg/virtio_scsi_mq.cfg
- qemu/tests/cgroup.py
- qemu/tests/ksm_overcommit.py
- qemu/tests/time_manage.py
- qemu/tests/virtio_scsi_mq.py
This is a follow-up of the https://github.com/autotest/tp-qemu/pull/1163 which got some acks and some nacks.
Changes:
* block_copy: Improve block regexp to work with recent qemu -> improved regexp to support spaces in filename
* Make sure images are removed in live_snapshot_chain -> reworked to not hide exceptions from test execution
* Turn the iscsi target into example only -> instead of commenting-out keep it and change the values to obviously dummy ones along with note to change it downstream
* Adjust config of nic_hotplug to work properly on s390x -> removed the double-fix
All but the changed commits were already acked by @luckyh so waiting for 2nd ack there and full 2 acks are required for the 4 patches mentioned above.
> Bunch of (not only) s390x fixes [v2]

- qemu/tests/balloon_service.py
Move related code out of try block, so when it fails the finally block won't execute which could lead error "local variable 'drive_letter' referenced before assignment"
ID: 1491184
> balloon_service: Fix bug when error happens in try block 

- qemu/tests/cfg/qemu_option_check.cfg
ID: 1524251
disable the unsupported devices and add the supported for s390x platform
> qemu_option_check: add devices supported on s390x platform

- qemu/tests/cfg/rh_kernel_update.cfg
- qemu/tests/rh_kernel_update.py
ID: 1523604
The kernel update test case was not enabled on s390x platform. this patch enabled it on s390x
> s390x: add kernel update test case support

- qemu/tests/cfg/valgrind_memalign.cfg
- qemu/tests/valgrind_memalign.py
This test depends on broken environment, where "vm.process" was not closed on "vm.shutdown". Let's fix that and tweak it to work properly on s390x.
> Couple of fixes to make "valgrind_memalign" work

- qemu/tests/drive_mirror_stress.py
The "drive_mirror_stress" uses "error_context" without setting
"context_aware" which leads to error. Let's set it.
> Set context_aware in drive_mirror_stress

- qemu/tests/cfg/virtio_scsi_mq.cfg
- qemu/tests/virtio_scsi_mq.py
Add a scsi-hd device for system disk on ppc and modify the strategy of checking interrupts.
ID : 1406975
> virtio_scsi_mq: check the info of interrupts by interrupt name

- qemu/tests/cfg/balloon_stress.cfg
Current 1800s is not long enough to run 1000 times balloon on some hosts. Remove the config to use the default value in base.cfg.
ID: 1527381
> balloon_stress: Update test_timeout to use default value

- qemu/tests/cfg/balloon_stress.cfg
get_memory_boundary function will calculate a min_size for balloon operation.
Default ratio value(0.1) is too small which lead to small min_size.Actuall
windows minimal mem increases if guest stress increase, sometimes it makes
balloon operation fail. Set ratio = 0.5 in the cfg file to avoid this issue.
ID:1529225
> balloon_stress.cfg: Add ratio paramter in cfg file

- qemu/tests/cfg/block_commit.cfg
- qemu/tests/cfg/block_stream.cfg
- qemu/tests/cfg/block_stream_negative.cfg
- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/cfg/drive_mirror_negative_tests.cfg
- qemu/tests/cfg/live_backup.cfg
- qemu/tests/cfg/live_snapshot.cfg
- qemu/tests/cfg/live_snapshot_chain.cfg
- qemu/tests/cfg/live_snapshot_negative.cfg
According to the test plan changed, add data-plane as a default matrix for all storage vm migration feature test.
id:  1516182
> Add data-plane as a matrix for all block jobs

- qemu/tests/cfg/virtio_console.cfg
- qemu/tests/virtio_console.py
The mmio-based arm requires virtio-serial-device and s390x machine
requires virtio-serial-ccw device.
This test also requires https://github.com/avocado-framework/avocado-vt/pull/1258 to properly define `virtio-serial-ccw` devices on the `avocado-vt` side.
> virtio_console: Treat virtio-serial-* 

- qemu/tests/cfg/device_option_check.cfg
"cmd = WINUTILS:\hddsn.exe C:" is not match the lable name
in def set_winutils_letter, change it to WIN_UTILS.
id: 1527826
> Correct the volume label name to WIN_UTILS

- qemu/tests/cfg/boot_from_device.cfg
- qemu/tests/cgroup.py
- qemu/tests/live_snapshot_chain.py
The rest of the fixes from the big https://github.com/autotest/tp-qemu/pull/1170. The changes are:
* `Make sure images are removed in live_snapshot_chain` - reworked, 2 acks needed
* `Fix the usage of process in cgroup test` - separated the unrelated fixes, 2 acks needed
* `Improve "dd" regexp to cope with newer versions in cgroup test` - the separated part of the previous commit, 2 acks needed
* `Turn the iscsi target into example only` - Added missing `"`, acked by @clebergnu
> Bunch of (not only) s390x fixes [v3]

- qemu/tests/boot_from_device.py
- qemu/tests/cfg/boot_from_device.cfg
In boot_from_device.check_boot_result(), although console output
boot_fail msg, the test result will be set to pass. The logic is
not reasonable, correct it.
bug id:1506101
> Correct logic for device's boot_fail

- qemu/tests/cfg/win_irq_check.cfg
- qemu/tests/win_irq_check.py
Add new case to check balloon and rng's irq value in windows guest.
based on: https://github.com/avocado-framework/avocado-vt/pull/1201
ID: 1455810
> win_irq_check: check balloon and rng's irq value in windows guest

- generic/tests/cfg/pxe_boot.cfg
ID: 1532193
For s390x platform, If there is no bootindex set for the nic device, the
guest won't try to boot with it, and if there is no bootable device
found while booting, the qemu process will terminated if "-no-shutdown"
was not set
> s390x: add additional params for s390x plaform for pxe_boot testing

- qemu/tests/cfg/pvpanic.cfg
- qemu/tests/cfg/pvpanic_basic.cfg
- qemu/tests/pvpanic.py
new cases related pvpanic:
1. check pvpanic event after trigger crash by nmi
2. do nmi crash after system_reset/reboot/shutdown/stop_cont
3. do nmi crash after migration
Signed-off-by: Yu Wang wyu@redhat.com
based on: avocado-framework/avocado-vt#1236
id:1457076  1508736 1509834 1508737
> pvpanic: add new cases related pvpanic

- generic/tests/cfg/ioquit.cfg
- generic/tests/ioquit.py
Replace "vm.process.close()" by "vm.destroy()"
bug id:1522616
> generic.ioquit: fix cluster leak issue

- qemu/tests/multi_disk_random_hotplug.py
qemu_tree.check_guests_proc_scsi() only compares scsi infos
for qtree/guest, so when there's an ide/virtio_blk device,
call this function is useless.
And it can't distigush a scsi device and a usb device, so
this function call for scsi/usb is also meaningless.
bug id:1533797
> Remove check_guests_proc_scsi() from verify_qtree()

- qemu/tests/cfg/pci_devices.cfg
- qemu/tests/pci_devices.py
The pci controllers handling changed significantly and the pci_devices test does not work anymore. This PR addresses all the issues needed for this test to run properly on Fedora.
Note: This test requires https://github.com/avocado-framework/avocado-vt/pull/1221 to work properly (it works without it, but one issue is not addressed)
> Make the pci_devices test to work again

- qemu/tests/boot_order_check.py
- qemu/tests/cfg/boot_order_check.cfg
In some hosts, guest got a key event from `wait_for_serial_login`, which cause grub process
waits for another key event to continue, and timeout will occur. It is redundant to login
serial console again, so use original `vm.serial_console` to fix this bug.
ID: 1481151
> boot_order_check: fix bug

- generic/tests/cfg/unattended_install.cfg
Move machine.cfg prior to subtests.cfg. Therefore remove
unattended_install..cdrom, unattended_install..extra_cdrom_ks
configuration from machine.cfg, it will not take effect after above
modification. Actually it is not proper to define such parameters
in machine.cfg, it should be defined here for itself.
id: 1537394
> uttended_install.cfg: Specify cd_format here instead of in machine.cfg

- qemu/tests/balloon_check.py
original sleep time(90s) is too small, balloon_check get guest used
memory at the very early stage. The value is not correct as it will
increase after all guest application up.
ID:1529212
> balloon_check: Extend sleep time to wait guest reach ready status

- qemu/tests/block_resize.py
Only virtio driver needs to be checked in windows, no need
to do it with ide driver.
bug id:1541271
> block_resize: only virtio driver needs to be verified in windows

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_check.cfg
- qemu/tests/cfg/balloon_hotplug.cfg
- qemu/tests/cfg/balloon_illegal.cfg
- qemu/tests/cfg/balloon_in_use.cfg
- qemu/tests/cfg/balloon_service.cfg
- qemu/tests/cfg/balloon_stress.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
1. When windows guest mem is small(e.g.1024M), calculated mem min_size will be larger than ori_mem if ratio=0.5, which will lead balloon cases fail.
2. When do balloon operation in linux guest, we should consider crashkernel value as well,leaving enough memory for guest to avoid guest OOM.
So modify the formula and leave a balloon buffer(300M in default) for guest min_sz.
ID:1529221,1538489
> Balloon check:Modify ballon min_size calculation formula

- qemu/tests/cfg/fio_windows.cfg
- qemu/tests/fio_windows.py
Fio has multiple device function, it allows fio running
on multiple disks at the same time. Here use this way to catch
run fio on system and data disks at the same time.
id:1520254
> Use the fio multiple device function to replace multiple thread

- qemu/tests/cfg/block_hotplug.cfg
block_resize.py only support extend/shrink on one data disk.
To keep consistency, set "only one_pci" in block_hotplug.cfg
for with_block_resize.
bug id:1549976
> block_hotplug: set "only one_pci" for with_block_resize

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
Qemu-ga-win pkg is not the latest one at present,need to get it from virtio-win iso.
BTW,optimize qemu-ga-instlall/uninstall function.
id: 1514340 
> qemu_guest_agent: Changing the way to download qemu-ga-win package from virtio-win iso

- qemu/tests/cfg/balloon_in_use.cfg
1).balloon_in_use only support windows guest before, add linux guest as well.
2).set mig_speed to 512M to avoid migration timeout issue.
ID:1483484,1517074
> balloon_in_use: Add linux guest support and fix migration timeout issue

- generic/tests/cfg/lvm.cfg
> generic.tests.lvm: don't remove image_stg1 and image_stg2 before lvm clean

- generic/tests/cfg/unattended_install.cfg
- qemu/tests/cfg/check_block_size.cfg
For windows guest, virtio driver is needed if drive format is blk and scsi.
To aviod vm can not identify cdrom as no driver, specify cd_format to ide.
This issue is introduced by avocado-vt commit 164dc1ff7fd39f30a7fb3ec54ad14858614ce907.
id: 1542520
> unattended_install: Specify cd_format when install Windows guest

- qemu/tests/nic_hotplug.py
Under avocado-vt latest commit 2aafd99, serial console has been
changed to allow multiple serial console connection.
This reverts commit bc44b6e625926af3d56396a7e98179f5ca1b8d5b.
Signed-off-by: Haotong Chen hachen@redhat.com
id: 1551512
> Revert "nic_hotplug.py: fix serial console conflict"

- qemu/tests/block_hotplug.py
If the vm is truly crash/dead, original code will return directly, which is not expected. Only for screnaio 'shutdown' could return directly, others should prompt guest dead error info which is already added in the framework.
id: 1511837
> qemu.tests.block_hotplug: make the condition detection of vm.is_dead() more robust.

- qemu/tests/block_stream_reboot.py
1. Block stream job should be performed directly after system_reset
command sent, no need a backgroud thread for reboot.
2. Shorten the sleep time after reboot, A reboot process wont take
such long time.
id: 1530844
> block_stream_reboot: Correct reboot process

- qemu/tests/set_link.py
Change to serial login for vm.reboot, since there is not network then
id:1551433
> set_link.py: fix shell reboot not effect in windows guests

- generic/tests/cfg/kdump.cfg
- qemu/tests/kdump_with_stress.py
kdump.cfg variable name check_cmd conflict with guest-os/Linux.cfg line 140
ID: 1543768
Signed-off-by: Chunyu Liao cliao@redhat.com
> kdump: Change Kdump variable name

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_in_use.cfg
- qemu/tests/cfg/driver_load_stress.cfg
- qemu/tests/driver_in_use.py
It will takes 90/180 seconds for guests getting to stable state in balloon_check, it should send signal when it's ready so that other operation can start after that.
driver_in_use should start background test only when guest memory get to stable state to avoid bg_test check failure.
ID:1550805
> balloon_check: Send stable signal when guest memory reach stable state

- generic/tests/nfs_corrupt.py
id: 1475777
Add check for NFS to ensure that its exported size should be large enough to hold the data image created, which will be used as destination for dd test in NFS corrupt. Also change the timeout of NFS soft mount to increase the wait time.
> nfs_corrupt: add space check for nfs and change timeo for mount

- qemu/tests/cfg/drive_mirror.cfg
- qemu/tests/drive_mirror_installation.py
drive_mirror_installation: add test case for mirroring during installation.
1. drive_mirror.cfg: Simplify stress part.
2. drive_mirror.py: get image name from params directly, fix path error when get from storage.
id: 1330412
> drive_mirror_installation: add test case for mirroring during installation.

- generic/deps/monotonic_time/Makefile
- generic/deps/monotonic_time/cpuset.c
- generic/deps/monotonic_time/cpuset.h
- generic/deps/monotonic_time/logging.c
- generic/deps/monotonic_time/logging.h
- generic/deps/monotonic_time/spinlock.h
- generic/deps/monotonic_time/threads.c
- generic/deps/monotonic_time/threads.h
- generic/deps/monotonic_time/time_test.c
- generic/deps/rtc/Makefile
- generic/deps/rtc/rtctest.c
- generic/deps/tsc/Makefile
- generic/deps/tsc/README
- generic/deps/tsc/checktsc.c
- generic/deps/tsc/sched.h
- generic/tests/cfg/timerclock.cfg
- generic/tests/hwclock.py
- generic/tests/monotonic_time.py
- generic/tests/rtc.py
- generic/tests/tsc.py
Since these four cases are still used in our test, rewrite them to avocado.
ID: 1556861
Signed-off-by: Sitong Liu siliu@redhat.com
> Rewrite clock test in autotest

- qemu/tests/balloon_check.py
- qemu/tests/driver_in_use.py
env["balloon_test_setup_ready"] value will keep available between cases which lead to following two cases fail if run them together with other balloon cases:
- balloon_in_use..during_bg_test
- driver_load_stress.with_balloon.during_bg_test
ID:1558323
> balloon_check: Use params instead of env to save balloon ready event

- qemu/tests/cfg/hotplug_mem.cfg
ID: 1558339
As power guest's crashkernel size is much bigger than x86's,which makes some memory_hotplug test cases fail just because of an improper one.It's necessary for us to change a proper one.I've already confirmed threshold with ppc developer and I've been told it was reasonable on ppc.Thanks
Signed-off-by: mdeng@redhat.com <mdeng@redhat.com>
> Update threshold of memory_hotplug tests on ppc

- generic/tests/netperf.py
1 Add jumbo setting for macvtap devices
2 Use second ethernet for login guest since host could not
communicate guest through first one which is attached from macvtap
3 fix no attribute 'stop_tcpdump' error
ID: 1528209 1528203 1538502
> Netperf: add support with macvtap device.

- generic/tests/mac_change.py
macvtap_mac_change: Adjust test steps according to test plan
1. in RHEL guest with virtio1.0, when set ctrl_mac_addr=off, mac can be changed to new one in guest but display the old one while 'info network'
2. in RHEL guest with virtio1.0, when set ctrl_mac_addr=on, mac can be changed to new ones both in guest and 'info network'
id: 1486119
> macvtap_mac_change: Adjust test steps according to test plan

- qemu/tests/cfg/pci_devices.cfg
The default usb-controller breaks the pci_device..max_devices variants
because it occupies the 1d.0 slot. We don't really need any additional
usb devices so let's just remove them for this test.
> qemu.pci_devices: Remove default usb devices and controllers

- qemu/tests/cfg/migrate.cfg
The path in gzip command might contain spaces or "weird" characters.
Migrate command already uses double-quotes so let's use the single
quotes to avoid the need to escape characters in the src/dst path.
Tested with:
exec:gzip -c > '/var/tmp/avocado_u8sHJg/avocado_job_OHWFL5/1-\
functional_rpm_dvd type_specific.io-github-autotest-qemu.migrate\
.with_reboot.exec.gzip_exec;-e630/migrateE8PDpZ/migrate_file'
> qemu.migrate: Quote the paths in gzip command

- qemu/tests/cfg/balloon_in_use.cfg
Correct balloon driver's name from "balloon.sys" to "balloon" which is used in windrv_check_running_verifier() function.
ID:1562739
> balloon_in_use: Correct balloon driver name

- qemu/tests/cfg/qemu_disk_img.cfg
1. Skip commit test with unsafe mode on RHEL-6 host.
2. Backup image and restore image for commit test to avoid
interference in later cases.
ID: 1565424
> qemu_disk_img.commmit: Update configurations for the case

- generic/tests/ethtool.py
Python 3 dese not support `foo.fucn_name`,
using `foo.__name__` instead.
> Python 3: [generic] replaced foo.func_name

- qemu/tests/balloon_check.py
To support both Python 3 and 2, use `next(iter)` or `iter.__next__()`
> Python 3: drop usage of iter.next()

- qemu/tests/qcow2perf.py
Add missing argument `shell=True` to function `process.run`.
> qcow2perf: Fix bug

- generic/tests/cfg/netperf.cfg
variants jumbo is duplicated with jumbo.py, so replace it with
with_jumbo.
ID: 1528148
> Netperf: variants jumbo is duplicated with jumbo.py case

- qemu/tests/cfg/hotplug_mem.cfg
ID: 1563481
It is because 2M size is default hugepage size on Power9 and we need to adjust it accordingly
Signed-off-by: mdeng@redhat.com <mdeng@redhat.com>
> Add 2M hugepage size tests for P9 

- qemu/tests/cfg/block_hotplug.cfg
1. Modify the repeat time from 300 to 100 about with_repetition test.
Repeat 300 times takes too long time.
2. Modify the repeat time from 3 to 1 about not repetition test.
Repeat hotplug and unplug can be covered by with_repetition test.
3. Limited the with_shutdown.after_plug only with_plug,
When test without_plug, this case is no needed.
id: 1572160
> block_hotplug: Modify the repeat time and add limited condition for with_shutdown case

- qemu/tests/cfg/usb.cfg
1. Replace parameter 'usb_max_port*' to the correct one 'max_ports*'.
2. Add 'no ppc64 ppc64le' in 'ich9-ehci' part.
3. Delete usb_boot test for usb_kbd, usb_mouse and usb_tablet part
since it's covered by cases in usb_device_check.cfg.
4. Correct usb controllers to be 'only usb-ehci, ich9-ehci' in
usb_hotplug..usb_negative_test part.
5. Delete usb_hotplug.usb_multi_times.usb_negative_test and
usb_host.usb_multi_times.usb_negative_test cases, since they are
meaningless.
6. Add/delete lines to make usb_multi_disk part work.
ID: 1411609, 1560843
> usb: Refine test cases in the config file

- qemu/tests/cfg/nmi_bsod_catch.cfg
nmi_bsod_catch.cfg: disable pvpanic
this case needs system reboot after panic.
open pvpanic system will shutdown after panic.
bug id: 1560457
Signed-off-by: Chunyu Liao  cliao@redhat.com
> nmi_bsod_catch: disable pvpanic

- generic/tests/build.py
- openvswitch/tests/ovs_basic.py
- qemu/tests/qemu_iotests.py
- qemu/tests/unittest_kvmctl.py
The test's "srcdir" property is deprecated and is planned to be
removed no later than May 11 2018. So replaced test.srcdir with
test.workdir.
Also changed variable name accordingly.
Please refer to:
https://github.com/avocado-framework/avocado/pull/2509
id: 1568659
> Replace test.srcdir with test.workdir

- qemu/tests/timedrift.py
When restoring the configurations of cpu affinity, some threads
would be no long existed, so need to ignore the errors emitted
by this operation.
> timedrift: Fix the CmdError of restore_cpu_affinity()

- qemu/tests/physical_resources_check.py
ovmf fd file uses image name as prefix, so it will be counted wrongly when check device by image_name. Fix it by excluding the fd file when count.
id: 1399929
> physical_resources_check: exclude ovmf fd file when count device

- generic/tests/cfg/linux_stress.cfg
- generic/tests/linux_stress.py
- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/cfg/live_snapshot.cfg
Depends on https://github.com/avocado-framework/avocado-vt/pull/1467
id: 1552382
> linux_stress: To replace stress test in autotest_control

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_check.cfg
Windows guest used memory changes after each boot/reboot, so when check memory value after guest reboot, the compared threshold should be larger.
ID:1281244
> balloon_check: Increase balloon compare threshold after guest reboot

- qemu/tests/system_reset_bootable.py
system_reset_bootable picks random times to sleep for between
reboot iterations.
Prior to this patch it used integers, and so always waited for
whole numbers of seconds.  This causes a problem where there's
a sub-second failure window during which a reboot would fail.
Depending on the system, qemu version and luck, the window could
completely miss the failure (reliably), and a small change
(such as a slightly different qemu build or host system) could
move the failure window within a second-boundary that would be caught.
This results in blaming the change rather than the original
fault.
Solve this by moving to random fractional values, at millisecond
resolution; there's probably more than a ms slop in the system
anyway.
Signed-off-by: Dr. David Alan Gilbert <dgilbert@redhat.com>
> system_reset_bootable: Use fractional random sleeps

- qemu/tests/cfg/pvpanic_basic.cfg
- qemu/tests/pvpanic.py
Add ps2_keyboard, usb_keyboard and notmyfault_app method to trigger
a crash.
id: 1542783 1542785  1542786
> pvpanic.py: add trigger crash cases for pvpanic

- qemu/tests/block_hotplug.py
- qemu/tests/cfg/block_hotplug.cfg
block_hotplug:
1.replace hotplug device definations by qcontainer.images_define_
by_params()
2.extract controller_device_dict setting as an individual function
"con_devs_dict()"
3.remove useless options in block_hotplug.cfg
bug id:1583472
> Replace hotplug device defination by qcontainer.images_define_ by_params()

- qemu/tests/cfg/block_hotplug.cfg
The 'blk_extra_params' uses ',' as separator and not ' '. Using ' '
leads to ' serial' instead of 'serial' being passed as an argument.
Theoretically I could just use '=' without any separator, but in order
to keep '+=' I decided to simply add the separator here. Empty inputs
are automatically skipped on parsing.
> block_hotplug: Use the correct 'blk_extra_params' separator

- qemu/tests/qemu_guest_agent.py
ID：1585547
Modify the reference to the parameter in the function find_interface_by_name
Signed-off-by: micai <micai@redhat.com>
> Modify the file qemu_guest_agent.py

- qemu/tests/smbios_table.py
When `uuid = random`, avocado-vt will generate a uuid through
`/proc/sys/kernel/random/uuid`. This uuid contains digits and
lower letters. It will be passed to qemu cmdline as a option.
eg: -smbios type=1,manufacturer='Dell Inc.',product='PowerEdge R430',
uuid='4c4c4544-0050-4610-804c-b9c04f584d32',serial='9PFLXM2',
version='Not Specified',family='VIRT',sku='KVM' \
However, the guest uuid obtained from
`dmidecode -t 1 | grep UUID | sed 's/^.*://g'` contains digits
and capital letters, which causes mismatch for the verification.
id: 1585588
> smbios_table: make uuid check case insensitive

- generic/tests/linux_stress.py
- qemu/tests/balloon_stress.py
Due to recent change in utils_test relating to VMStress, couple of qemu tests
were failing. This patch fixes up 2 qemu testcases.
> Fixup: Update test cases to reflect recent lib changes

- qemu/tests/vhost_with_cgroup.py
porcess.system_output needs to set ignore_status=True
and decode the return value for later usage.
> Python 3: fix a process issue

- qemu/tests/cfg/usb.cfg
Fix below issue:
```
13:02:16 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-qemu/qemu/tests/multi_disk.py", line 227, in run
13:02:16 ERROR|     file_system = [_.strip() for _ in params.get("file_system").split()]
13:02:16 ERROR| AttributeError: 'NoneType' object has no attribute 'split'
```
id: 1588919
> usb.usb_multi_disk: fix the absent of param file_system

- qemu/tests/rh_qemu_iotests.py
Since qemu-2.12, qemu-iotests requires tester to specify the path
for qemu, qemu-img, qemu-io, and qemu-nbd. Or the test suit will
show a warning message and terminate the tests.
ID: 1582035
> rh_qemu_iotests: Specify the path for binary QEMU_NBD_PROG

- qemu/tests/qemu_img.py
Data type of exit_status is int, which should not be decoded.
Only decode text output.
ID: 1598956
> qemu_img: fix the issue that cannot get CmdResult.exit_status

- qemu/tests/cfg/migrate.cfg
The migrate jobs usually define 1 vms, but during the migration 2 vms
might be live, which might affect the number of required memory for
hugepages. Let's use the "max_vms" parameter, which is considered on
hugepage setup, to reflect the reality.
> migrate: Set "max_vms" to allow "hugepage" testing

- qemu/tests/balloon_check.py
Can not compare "int" with "str".
id: 1602224
> balloon_check: Set "gcompare_threshold" to int type

- qemu/tests/block_hotplug.py
Fix up the filedescriptor out of range in select()
by reducing to call the wait_for_login.
ID: 1598700
> block_hotplug: Reduce calling of wait_for_login method.

- qemu/tests/driver_in_use.py
qemu.windrv_check_running_verifier() functions is introduced in balloon_stress case, it takes at most another 360 seconds. So need to extend timeout value for check_setup_events.
ID:1605051
> balloon_in_use: extend timeout value for checking "check_setup_events"

- qemu/tests/enospc.py
- qemu/tests/qemu_img.py
- qemu/tests/rebase_negative_test.py
In Python 2, the str type was used for two different kinds of values:
text and bytes, whereas in Python 3, these are separate and incompatible
types.
e.g.
TypeError: a bytes-like object is required, not 'str'
\>>> 'abc' in b'abcd'
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
\>>> type(b'abcd')
<class 'bytes'>
More background on this can be seen in
https://www.redhat.com/archives/avocado-devel/2018-April/msg00002.html
This patch helps to decode the binary data into a text string.
ID: 1610167
> Decode Binary data to Text

- qemu/tests/disable_win_update.py
On some occasions `sesssion.sendline()` takes longer to finish,
thus massing up the output of the session.
So,change it to `cmd()`.
id: 1567708
> disable_win_update.py: session bug fix

- qemu/tests/cfg/rng_stress.cfg
- qemu/tests/rng_stress.py
1. avoid getting stuck when pre_cmd is running in background
2. correct the value of param `ignore_status` for post_cmd
ID: 1588412
> rng_stress: Fix bugs of pre_cmd and post_cmd

- qemu/tests/rng_bat.py
Delete useless `vm.wait_for_login()` to avoid fd leak.
> rng_hotplug: Fix the issue of fd leak

- generic/tests/netperf.py
- generic/tests/pktgen_perf.py
- multi_host_migration/tests/migration_multi_host_firewall_block.py
- multi_host_migration/tests/migration_multi_host_with_speed_measurement.py
- qemu/tests/block_copy.py
- qemu/tests/cdrom.py
- qemu/tests/cdrom_block_size_check.py
- qemu/tests/change_media.py
- qemu/tests/fio_perf.py
- qemu/tests/migration_with_speed_measurement.py
- qemu/tests/pci_devices.py
- qemu/tests/performance.py
With the py3k changes some returns are not strings, but decoded
unicodes. Currently this mainly breaks monitor returns, where human
monitor gets recognized as qmp one. Let's use "six.string_types" that
provides the right string types for given python version.
> Use "six.string_types" instead of "str"

- qemu/tests/stepmaker.py
This is the minimum needed for Python 3 compatibility and update
of the GTK API from 2 to 3 is the minimal needed for the GObject
introspection compatibility layer.
> Update pygtk requirement to GTK3 compatibility layer

- qemu/lib/cdrom.py
id: 1347198
1. add function "get_device_tray_status" for checking if device tray is opened or not.
2. add context manager classes to support event checking of cdrom-related functions.
> qemu.lib: add cdrom checking classes of 'DEVICE_TRAY_MOVED'

- qemu/tests/sr_iov_irqbalance.py
Since legacy python (2.4-2.6) is no longer supported by avocado-vt,
now it is the time to drop the package `virttest.staging.backports`
as it is used for backward compatibility.
ID: 1607758
> Drop the package virttest.staging.backports

- generic/tests/hwclock.py
hwclock test fails on JeOS, Fedora etc with default pattern,
make an ability to define custom date pattern for other OSes
> hwclock: make an ability to define custom pattern

- generic/tests/cfg/linux_stress.cfg
- generic/tests/linux_stress.py
Existing linux stress was supporting single vm with single stress
tool. This commit extends that testcase to now support multiple
guests running same/different stress tools inside for given duration
> Extend linux stress to support multivm with multi stress tools

- qemu/tests/cfg/virtio_console.cfg
- qemu/tests/virtio_console.py
This test used a wrong assumption that this symlink must always
exists, but it doesn't have to be there when other virtio device
is present. Let's just rely only on the "_get_port_status" test
which makes sure the number of symlinks correspondent to number
of devices.
Relates to: https://github.com/avocado-framework/avocado-vt/issues/1736
> Remove "virtio_console..check_zero_sym"

- generic/tests/kdump.py
By default kdump test sets crashkernel reserve memory with offset of 16M. In powerpc, offest is auto calculated, setting explicit offset will result in crash kernel failing to reserve memory leading to kdump service start failure. We need to make def_kernel_param_cmd generic by omitting offset (kdump will offset the reserved memory automatically) which works across archs.
> Make def_kernel_param_cmd generic

- generic/tests/cfg/pxe_boot.cfg
- qemu/tests/pxe_query_cpus.py
The test would call `pxe_boot` and run parallelly, and that would
result in error which was caused by race conditions. The patch
attends to fix this issue by making the script indenpendent.
ID: 1548954
> pxe_query_cpus: An enhancement to the test

- qemu/tests/watchdog.py
As python3 only use unicode string. This patch covert bytes string
to unicode string.
ID:1630779
> watchdog: fix python3 encoding issue

- qemu/tests/cfg/rh_kernel_update.cfg
Fix a param assignment bug that would lead a failure of virtio
module check on s390x.
ID: 1632994
> rh_kernel_update: Fix a param assignment bug

- qemu/tests/cfg/uefishell.cfg
- qemu/tests/uefishell.py
To add uefishell common test, with two general cases: "key enrollment" and "check oprom in uefi env"
id: 1558458, 1558459
> ovmf: add uefishell common test

- qemu/tests/cfg/multi_nics_stress.cfg
- qemu/tests/multi_nics_stress.py
1.Since need launch 5 vms and half of system cpus was launched by
default, there is about 2.5 cpu over commit. in such situation, tests
need more time on login.
2.Disable windows firewall
id: 1400391
> multi_nic_stress: enlarge login_timeout and disable windows firewall

- qemu/tests/cfg/single_driver_install.cfg
Since now we use different name for system disk between virtio-scsi
and virtio-blk, it has less chance to trigger the BSOD error, so we
can remove the previous workaround.
ID: 1608673
> single_driver_install: Remove workaround

- qemu/tests/cfg/single_driver_install.cfg
When install vioscsi and viostor drivers, switching system to ide then install another driver, then switch it back will cause windows crash.
ID:1638181
> single_driver_install: No need to switch system to ide when install storage drivers

- qemu/tests/cfg/qemu_img_info_while_running.cfg
- qemu/tests/qemu_disk_img.py
- qemu/tests/qemu_img_info_while_vm_running.py
Added three `qemu-img` lock tests.
To verify it supports to get information of a running image.
id: 1638310
> added qemu_img_info_while_vm_running cases

- qemu/tests/balloon_boot_in_pause.py
- qemu/tests/balloon_check.py
Guest boot in pause status in this case, super(BallooningTestPause, self).__init__ () will always fail since it will try to get guest ip address and login.
ID: 1517601
> balloon_boot_in_pause: Fix login error since vm boot in pause status

- qemu/tests/boot_with_different_vectors.py
- qemu/tests/cfg/boot_with_different_vectors.cfg
1. MQ will be set automatically according to cmd line configuration
in qemu. This behavior is introduced by an RFE bug.
2. virtio[x]-interrupt match string modified
id: 1576643
> boot_with_different_vectors: remove set mq operation in test steps

- qemu/tests/cfg/reject_qemu_img_info.cfg
- qemu/tests/reject_qemu_img_info.py
Added two `qemu-img` lock tests.
To verify it rejects to get information due to image lock.
id: 1639992
> added reject_qemu_img_info cases

- qemu/tests/cfg/multicast_iperf.cfg
- qemu/tests/multicast_iperf.py
ID: 1638723
- Update iperf2 version to iperf-2.0.12
- Add parameter "timeout" into `t.join()`
Additional info:
**Add parameter "timeout"  to fix another bug.**
When interrupting iperf, if the client task in the guest is not 
completed, the host iperf server will wait threads to complete. So add 
it to avoid unexpected situations, otherwise the job will always hang.
> Update iperf2 version and fix bug

- qemu/tests/block_hotplug_negative.py
- qemu/tests/cfg/block_hotplug_negative.cfg
block_hotplug_negative: replace hotplug process defination by
images_define_by_params()
bug id:1550397
> optmize block_hotplug_negative to support raw disk's hotplug

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
1. virtual-host tuned profile on server and client
2. virtual-guest tuned profile on vm
3. disable watchdog
4. hyper-v enlightenment for windows guest with  -cpu ,hv_time,
hv_relaxed,hv_vapic,hv_spinlocks=0x1fff
Netperf: add support for rhel8
1. add support for python3.6
2. update linux netperf to latest 2.7.1
3. re-design the logic for getting server_ip/server_ctl/server_ctl_ip
ID: 1501046, 1642875
> Netperf: tweak configuration according whitepaper

- generic/tests/netperf.py
Add ethernet check to see if support jumbo setting, if not, will skip
the test.
ID:1529426
> Jumbo: add ethernet check to see if support jumbo setting

- qemu/tests/mq_change_qnum.py
- qemu/tests/pktgen.py
1. Deprecate 'status' as a result condition for mq change function
2. Fix an function parameter error with using decode()
ID: 1626881
> Re-write code logic of checking results of network mq change

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
1.frozen guest FS
2.send shutdown agent cmd to guest
3.send reboot agent cmd to guest
4.send fsthaw cmd to guest
id: 1468530, 1476648
> qemu_guest_agent: add new guest agent case

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_minimum.cfg
1. Set very small value(10M) to windows guest, guest memory will keep still at a minimal working value.
2. Set a minimal boudary memory value to guests, guests can work normally even after reboot.
ID:1542296
> balloon_small:Reset memory size to very small during runtime

- generic/tests/cfg/iozone_windows.cfg
iozone_windows cfg set mem=2048 before, but when the guest
min memory large then 2G, like win2016 need min memory 4G,
the job will be canceled.
It's better that let the guest use automatic allocation mem value.
id: 1633895
> iozone_windows: Delete "mem=2048" from iozone_windows.cfg

- qemu/tests/cfg/live_snapshot_chain.cfg
- qemu/tests/live_snapshot_chain.py
QMP command 'system_reset' is issued after creating files in the guest. The
command has an effect similar to the physical reset button on a PC. But
filesystems may be left in an unclean state which causes the loss of data. Run
the command "sync" to flush the data to disk.
ID: 1642032
> live_snapshot_chain: Flush data to disk before running system_reset

- qemu/tests/cfg/virtio_driver_sign_check.cfg
- qemu/tests/virtio_driver_sign_check.py
1. Boot a guest with latest virtio-win.iso and virtio-win.vfd.
2. Run signtool.exe to verify each driver '.sys', '.inf' and 'Wdf'file.
id: 1375853
> virtio-win driver signtool check Test

- qemu/tests/cgroup.py
Two little tweaks to cgroup test to avoid false-negatives. Discussion here: https://bugzilla.redhat.com/show_bug.cgi?id=1621903
@KarMez-Redhat you might be interested in this.
> Cgroups limits in bytes

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
1. add ovs support
2. add firewall disable for windows guest
3. set jumbo's back when occurs test.error or test.fail with
netperf.jumbo.host_guest test
ID: 1538527 1538534 1538539
> Netperf: fix some issues

- generic/tests/dd_test.py
1. vm.destroy is not a mandatory step when dd_test is executed directly.
2. If dd_test is called as subtest in some other tests,
caller's following steps may be interrupted
for vm has been destroyed.
ID: 1650421
> dd_test: remove destroy vm operation

- qemu/tests/boot_with_different_vectors.py
should use findall to find a str in the output of session.cmd_output
id: 1646772
> boot_with_different_vectors: cannot find a str in session.cmd_output

- generic/tests/cfg/ethtool.cfg
- generic/tests/ethtool.py
id: 1630351, 1626894
1. add support of e1000e
2. remove support of e1000 on RHEL8 guest
3. fix bug of decode
> offload_txrx_chksum: fix bug

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
1. sometimes since vm performance issue or processors could not handle
at same time with mis-config sessions number, it may not all clients
up at same times, we can modify tries  parameters to repeat sub tests
to increase the successful probalility.
2.add function stop_netperf_clients() to use correct kill command
according to linux or windows system
ID: 1315167 1408744
> Netperf: add tries parameter to repeat sub tests

- generic/tests/cfg/guest_test.cfg
dhclient is not started by default on new system, so 'killall x' will fail and cause the script fails, so replace '&&' with ';' to allow it not processed and execute later command directly
id: 1645453
> guest_test: Allow 'killall x' failed per it sometimes not processed

- qemu/tests/cfg/balloon_disable.cfg
- qemu/tests/cfg/balloon_stop_continue.cfg
Since -balloon is no longer supported by qemu3.1, update cases accordingly.
ID: 1655410
> balloon_disable/balloon_stop_continue: remove -balloon usage

- qemu/tests/cfg/smbios.cfg
- qemu/tests/smbios_table.py
This contains some config tweaks to allow running this test under q35 profile, then some py3 fixes and adjustment to avoid booting unwanted upstream targets.
@KarMez-Redhat, @wainersm, @yashkmankad: this should help you with your CI.
> qemu..smbios: q35 and py3 fixes

- qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
The existed parameter only support pc machine type,should support q35 as well.
id: 1653167
> qemu_guest_agent:q35 support for qemu_guest_agent_hotplug

- qemu/tests/cfg/unsafe_rebase_to_none_existing_backing_file.cfg
- qemu/tests/unsafe_rebase_to_none_existing_backing_file.py
Unsafe rebase a qcow2 snapshot to a none exist the raw backing file.
id: 1657145
> added an unsafe rebase snapshot

- qemu/tests/cfg/block_discard.cfg
> block_discard: correct scsi-hd to scsi-block for pass-through scsi disk

- generic/tests/ioquit.py
The first commit fixes py2/py3 compatibility issue and the second one uses https://github.com/avocado-framework/avocado/pull/2924 to avoid write-lock issues on recent qemu. The problem is that `aexpect.close()` kills the `sh` underneath, which is suppose to destroy the `qemu` process as well. And it does, but especially after extensive io usage it takes time resulting in failed tests due to `qemu-img` being unable to obtain write lock.
> generic..ioquit: Adjust reading Exception to py3

- qemu/tests/boot_with_different_vectors.py
- qemu/tests/cfg/boot_with_different_vectors.cfg
Add support for "XICS" and "XIVE" interrupt controller type.
ID: 1646772
> boot_with_different_vectors: Support Power8/9

- qemu/tests/qemu_guest_agent.py
Clear readonly for disks and online them in windows guest before format them.
ID: 1658948
> qemu_guest_agent:clear readonly bit for windows disk and online them

- qemu/tests/cfg/timedrift_check_clock_offset.cfg
- qemu/tests/timedrift_check_after_load_vm.py
Add case for checking time drift after savevm and loadvm
ID: 1468147
P.S. This patch is from closed patch #1095 , reopen it.
> timedrift_check_after_load_vm: add case

- qemu/tests/cfg/rh_kernel_update.cfg
- qemu/tests/rh_kernel_update.py
* remove the default cmdline args for configuring new kernels
* make the command run only if there is additional args
ID: 1661969
> rh_kernel_update: Modify the step of updating kernel cmdline

- generic/tests/cfg/vlan.cfg
- generic/tests/vlan.py
1. update corresponding pattern for ALT7 guest
2. fix "set_vlan_cmd" typo
ID: 1646793
> Update error message pattern for ALT7 guest

- qemu/tests/single_driver_install.py
`findstr` cannot handle unicode well and that cause the problem to
get the version of the given driver, so let's call `type` to solve
it.
ID: 1663071
> single_driver_install: Fix the unicode issue

- qemu/tests/cfg/ctrl_vlan.cfg
only virtio-net supports ctrl_vlan parameter. Avoid running this case with other devices.
ID: 1663094
> Avoid running ctrl_vlan cases with other devices except virtio-net

- generic/tests/hwclock.py
The generic hwclock test may fail as false-positive in reason
of a pattern output mismatch, but not exactly because it failed
to set the clock. In that case, printing the expected output pattern
on the fail message is useful to quickly spot the problem.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> generic/hwclock: print expected output pattern on fail

- qemu/tests/cfg/smbios.cfg
The filter is suppose to be Host.RHEL and not Host_RHEL.
> qemu..smbios: Fix typo in Host.RHEL filter

- qemu/tests/cfg/virtio_scsi_mq.cfg
- qemu/tests/virtio_scsi_mq.py
step1: boot guest vm up with num_queues
step2: enable vioscsi.sys verifier in guest
step3: run wmi check command
step4: check instance.QueuesCount value as expected
id: 1564837
> tp-qemu: Add case WMI_facility_test for windows guests

- qemu/tests/reject_qemu_img_info.py
Due to qemu-img write lock err msg changes,
updated the write lock err msg checker to fit all
the cases.
id: 1664935
> updated write lock err msg checker

- qemu/tests/cfg/watchdog.cfg
The bug caused all rdma and x-rdma tests used the default tcp protocol.
> watchdog: fix migration_protocol parameter name

- qemu/tests/cfg/qemu_img_measure.cfg
'qemu-img measure' function exists since qemu-2.10.0.
ID: 1668167
> Disk_Format: Limit qemu version for 'qemu-img measure' related cases

- qemu/tests/cfg/multi_disk.cfg
- qemu/tests/multi_disk.py
1. change drive_format from scsi-disk to scsi-hd.
scsi-disk is legacy, use scsi-hd instead of scsi-disk.
2. add umount partition step for passthrough scsi_debug disk test.
when multiple SCSI disks are simulated by scsi_debug, they
could be viewed as multiple paths to the same storage device.
So need umount partition before operate next disk, in order
to avoid corrupting the filesystem(xfs integrity checks error).
ID: 1669025
> qemu.test: update case multi_disk related steps

- qemu/tests/cfg/block_hotplug.cfg
- qemu/tests/cfg/nic_hotplug.cfg
- qemu/tests/cfg/rng_hotplug.cfg
- qemu/tests/cfg/virtio_console.cfg
Need provide sufficient extra root port when there are more than 1
devices to be hotplugged, since the default pcie_extra_root_port
is 1
id: 1661084
> Q35: Provide more pcie_extra_root_port for hotplug cases

- qemu/tests/single_driver_install.py
In some drivers' inf files, there are some spaces between 'DriverVer'
and '=', somes have no, so modify the search to be more tolerant.
ID: 1676722
> single_driver_install: Make driver version search be more tolerant

- qemu/tests/fio_perf.py
The result file isn't closed.
bug id: 1676768
> fio_perf: close the opened result file in the end

- qemu/tests/cfg/fio_perf.cfg
e.g. kvm-userspace-ver : b'package qemu-kvm-rhev is not installed
\nqemu-kvm-2.12.0-41.el8+2104+3e32e6f8.x86_64'
It should be 'qemu-kvm-2.12.0-41.el8+2104+3e32e6f8.x86_64'
bug id: 1677467
> fio_perf: removing useless info when getting qemu-kvm version

- qemu/tests/cfg/qmp_event_notification.cfg
The test works on i440fx and q35 machines because MC146818 (the RTC
device on them) emulation code generates RTC_CHANGE event when its time
is set. For aarch64 virt machine, however, its RTC device is PL031,
whose emulation code doesn't generate that event. So skip the test on
aarch64.
Signed-off-by: Huan Xiong <huan.xiong@hxt-semitech.com>
> qmp_event_notification: skip qmp_rtc_change test on aarch64

- qemu/tests/cfg/nmi_bsod_catch.cfg
- qemu/tests/nmi_bsod_catch.py
1. Add step to check whether driver verifier enabled in guest.
2. Add mem_fix for Win2016, Win2019 guest, due to 2G is less than their vm_mem_min(4G).
id: 1456099, 1566839
> Update nmi_bsod_catch case to match virtio-win scsi/blk crash dump check case

- qemu/tests/live_snapshot.py
- qemu/tests/live_snapshot_base.py
For case live_snapshot.with_file_transfer:
1. change the path of live_snapshot_img to images/*
2. remove live_snapshot_img after test finished
For case live_snapshot.base:
The correct parameter name should be 'snapshot_file' instead of 'snapshot_name'.
id: 1679011
> live_snapshot: change the path of snapshot and remove it at the end 

- qemu/tests/cfg/multi_nics_hotplug.cfg
- qemu/tests/nic_hotplug.py
1. Get free root port and assign it as bus for hotplugging nic device.
2. The second commit removing unused variants in this script. For the 'status, output' in ping_hotplug_nic(), the return value of ping() is covered by the return value by cmd_output_safe(), I suppose what we want to return to the user is from ping(), so remove the second ones.
id: 1658131
> Nic hotplug: Add pcie support

- generic/tests/cfg/jumbo.cfg
- generic/tests/ethtool.py
- generic/tests/jumbo.py
- qemu/tests/ovs_host_vlan.py
id: 1571613
1. some case does not clean ovs ports after finished, this case
will error because of trying to set mtu to all the ports in ovs
bridge but some of the ports are invalid.
2. fix python3 compatibale issue
> jumbo: remove redundant ports in ovs bridge and fix python3 issue

- qemu/tests/cfg/expose_host_mtu.cfg
- qemu/tests/expose_host_mtu.py
1. Use `utils_net.Bridge().list_iface()` to get the `netdst` bridge interface
2. Replace `ifconfig` with `ip link`
ID: 1683012
> expose_host_mtu: Modify method to get the bridge source interface

- qemu/tests/cfg/rh_kernel_update.cfg
Our framwork support different methods to backup image:
1. backup_image_before_testing: will skip if there is a same backup
2. backup_image: will backup image by force.
Our test order in a loop can be:
1. Installation test backup image by force when install finished.
2. rh_kernel_update
3. some case use "backup_image_before_testing", it will skip backup
when there is a same existing backup image
4. At the end of that case, it will restore(restore_image_after_testing)
the backup image which be saved at step 1, without the change of
rh_kernel_update in step 2.
So, use 'backup_image' in rh_kernel_update to backup image by force.
id: 1683557
> rh_kernel_update: backup image at the end of the test

- qemu/tests/balloon_check.py
- qemu/tests/cfg/balloon_in_use.cfg
- qemu/tests/cfg/balloon_stress.cfg
- qemu/tests/driver_in_use.py
1. Cancel timeout in stress_thread.join() to wait whole bg_test finish, else two balloon operation conflict and lead to error: "Failed to balloon memory to expect value during 240.0s";
2. Change repeat time from 200 to 100 to reduce testing time.
3. Increase balloon_buffer from 300 to 600 to avoid too smalle balloon value.
ID: 1658894
> driver_in_use..during_bg_test: Fix balloon memory error

- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/hotplug_mem.py
1. add wait_for_login at the beginning to wait guest boot up before
doing test
2. for guest_reboot and vm_system_reset cases, wait a few seconds
to make sure sub test run in correct order and avoid timeout issue
ID: 1649970
> hotplug_mem: Fix timeout issue for some cases 

- qemu/tests/cfg/timerdevice.cfg
Timerdevice tests were designed assuming at least one of the following:
- tsc clocksource is available in host
- kvmclock, tsc, or pit clocksources are available in guest
- msr-tools is available in guest
All of these are x86 specific features. So skip them on aarch64.
Signed-off-by: Huan Xiong <huan.xiong@hxt-semitech.com>
> timerdevice: skip all tests on aarch64

- qemu/tests/live_snapshot_basic.py
In python2, json.loads(str) return a unicode value, but in python3,
it just returns a string value.
Correct the match pattern for snapshot_node_name for compatibility
between python2 and python3.
bug id:1640055
> live_snapshot_basic: correct match pattern for snapshot_node_name

- qemu/tests/block_copy.py
Sometimes, 'query-block-jobs' get 'len'= 0 at the first few seaconds
after 'drive-mirror' start. In this condition, 'len' =='offset' == 0.
It is not really block job steady, will cause 'job-complete' hit error
id: 1684439
> block_copy: change the method of checking block job is steady

- generic/tests/cfg/timedrift.cfg
- qemu/tests/cfg/timerdevice.cfg
The command "timedatectl" isn't supported before RHEL7, update cfg files to drop two test cases.
ID: 1686706
> timedrift&timerdevice: Skip running two test cases before RHEL7 OS

- qemu/tests/balloon_check.py
- qemu/tests/balloon_minimum.py
- qemu/tests/cfg/balloon_minimum.cfg
Original free memory compare value is 50M which is too small, especially for latest windows guests. So enlarge it to 150M.
ID: 1669959
> balloon_minimum.negative: Enlarge free memory compare value

- qemu/tests/balloon_hotplug.py
- qemu/tests/cfg/balloon_hotplug.cfg
Original code calls BallooningTest() at least twice in each plug time, it takes more than 16 hours to finish this case. Optimize the code to reduce the running time.
ID: 1679846
> balloon_hotplug: Optimize code to reduce case running time

- generic/tests/cfg/iometer_windows.cfg
- generic/tests/iometer_windows.py
Rescan first when running windows diskpart.
Diskpart requires windows volume INF file and volume setup
events ready, add 10s to wait events done.
id: 1618586
> Fix a diskpart timeout issue

- qemu/tests/cfg/nic_bonding.cfg
- qemu/tests/nic_bonding_host.py
Force set 'max_bonds' parameter when loading 'bonding' module to control the number of bonding interfaces.
ID: 1686313
> Force set 'max_bonds' parameter when loading 'bonding' module

- qemu/tests/cfg/virtio_scsi_cdrom.cfg
Add a new case that guest could install os from
scsi-cd device for x86_64.
ID: 1628043
> virtio_scsi_cdrom: Add an installation case

- generic/tests/jumbo.py
- qemu/tests/expose_host_mtu.py
id: 1690216
There might be txx-xxxxxx (more than 1 number after 't') in the
port list, modify the regular expression to fit the situation
> expose_host_mtu and jumbo: delete redundant ovs ports

- qemu/tests/hotplug_mem.py
Memory hot-unplug only works after adding 'movable_node' to guest
kernel line. This patch will check if the option is there and add
it if not.
ID: 1689802
> hotplug_mem: Update guest kernel line to make unplug work

- generic/tests/ioquit.py
The commit 58633a7b7e56 added a call to kill_process_tree on
ioquit test. It passes 'wait' parameter that actually does not
exist on kill_process_tree, and instead it should use 'timeout'.
Signed-off-by: Wainer dos Santos Moschetta <wainersm@redhat.com>
> Fix ioquit call to kill_process_tree

- qemu/tests/cfg/rng_bat.cfg
- qemu/tests/cfg/rng_host_guest_read.cfg
- qemu/tests/cfg/rng_hotplug.cfg
- qemu/tests/cfg/rng_read_longtime.cfg
- qemu/tests/cfg/rng_stress.cfg
- qemu/tests/cfg/viorng_in_use.cfg
- qemu/tests/rng_stress.py
For rhel 6 guest including virtio-rng device(s), there will be only
'virtio' in files 'rng_available' and 'rng_current', not 'virtio_rng.x'
like in rhel 7 guest. Also as a result, it is impossible to switch rng
device in rhel 6 guest with multiple virtio-rng devices.
1.Add rhel 6 specific virtio-rng driver name 'virtio'
2.Disable rng_stress.two_device for rhel 6 guest
ID: 1617286
> virtio_rng_rhel6_driver: update rng cases to support rhel 6 guest

- qemu/tests/balloon_hotplug.py
Unplug balloon device while device in using state are not allowed, windows will prompt a warning for that. So wait a while to make device in idle state then unplug it.
ID:1607208
> balloon_hotplug: wait 10 senconds before unplug balloon devices.

- qemu/tests/cfg/ovs_quit.cfg
- qemu/tests/ovs_enslave_port.py
> ovs_enslave_port: Add test case of enslave a port which is already in another ovs bridge

- qemu/tests/cfg/balloon_in_use.cfg
- qemu/tests/driver_in_use.py
virtio_storage_in_use background test takes 2 hours, better to set timeout value in stress_thread.join() to avoid wating that long time.
But two simultaneous balloon operation conflicts so set a flag for balloon cases.
ID:1696073
> driver_in_use: set timeout value in stress_thread.join() to save testing time

- qemu/tests/qemu_guest_agent.py
There is no need check "exited" keyword, if it doesn't exist the
following code can cover it.
ID: 1698318
> qemu_guest_agent: fix issue of 'guest-exec-status' failed

- qemu/tests/balloon_check.py
When the expected value is small, it's not appropriate to only compare by
the ratio. E.g. If expected value is 1000M, default ratio is 10%, then the
tolerate difference is only 100M, which might not be suitable for windows
guest.
ID: 1697801
> balloon_check: add comparing abosolute difference when check memory

- qemu/tests/cfg/fio_linux.cfg
- qemu/tests/fio_linux.py
Boot guest with "aio=native" or "aio=threads" CLI option
and run fio tools.
ID: 1630819
> fio_linux: Add a case run fio for Linux

- qemu/tests/cfg/nvdimm.cfg
From RHEL8, according to product bz 1620330: "To test or use dax on
xfs, reflink must be turned off". So update the format command, add
"-m reflink=0"
id: 1699968
> nvdimm: update the format nvdimm command

- qemu/tests/timerdevice_boot.py
> timerdevice_boot: Session is closed in advance

- generic/tests/cfg/unattended_install.cfg
- generic/tests/unattended_install.py
perform multiVM installation/import parallely or one by one with specfic
trigger time or by random trigger based on the param `install_trigger_time`
and `ramdom_trigger` respectively. This patch doesn't change the default way
for single VM.
Suggested-by: Xu Han <xuhan@redhat.com>
Suggested-by: Satheesh Rajendran <sathnaga@linux.vnet.ibm.com>
> unattended_install: perform multivm unattended_install

- qemu/tests/cfg/timedrift_check_clock_offset.cfg
- qemu/tests/timedrift_check_when_crash.py
When guest kernel panic occurs, keep the qemu process alive.
bug id: 1549005
> timedrift_check_when_crash: add "-no-shutdown" for linux guest

- qemu/tests/cfg/flow_caches_stress_test.cfg
- qemu/tests/cfg/mq_change_qnum.cfg
- qemu/tests/cfg/mq_max_queues.cfg
Multi queues test cases are not meaningful for other virtual network
device except virtio-net-pci, add limitation (only virtio_net) for these
cases.
ID: 1700180
> Add limitation for some multi queues test cases

- qemu/tests/cfg/set_link.cfg
spapr-vlan doesn't advertise the link state, drop these cases for it.
ID: 1698838
> set_link: drop 'set_link' test cases for spapr-vlan

- generic/tests/cfg/iometer_windows.cfg
- generic/tests/iometer_windows.py
Add 4 cases:
1. Reboot guest after  Iometer running.
2. Shutdown guest after Iometer running.
3. Reboot guest when running iometer.
4. Shutdown guest when running iometer.
Wrap sentences to functions as below:
1. install_iometer
2. register_iometer
3. prepare_ifc_file
4. _run_backgroud
5. run_iometer
6. change_vm_status
7. check_vm_status
ID: 1566870
> iometer_windows: Add new cases

- generic/tests/cfg/netperf.cfg
nic_model 'e1000' is only supported by x86, for other arch
use 'virtio' instead
id: 1702216
> netperf: update nic_model_nic2 for different arch

- qemu/tests/cfg/timedrift_check_clock_offset.cfg
Because the output of "hwclock -u" in rhel6 is different.
bug id: 1695462
> timedrift_check_non_event: add pattern for rhel6 guest

- provider/storage_benchmark.py
1. The command of checking the running process in windows
should be "TASKLIST /FI "IMAGENAME eq $process_name.EXE".
2. No clean the env files if there are not env files.
ID: 1703339
> storage_benchmark: Correct the clean method in windows

- qemu/tests/cfg/iozone_linux.cfg
- qemu/tests/cfg/virtio_storage_in_use.cfg
- qemu/tests/driver_in_use.py
- qemu/tests/iozone_linux.py
1. Support check the backgroud test for linux.
2. Add linux scenario support in virtio_storage_in_use cfg.
3. Add a new case iozone_linux called from virtio_storage_in_use.
ID: 1611971
> virtio_storage_in_use: Add linux support for virtio_storage_in_use

- qemu/tests/timerdevice_clock_drift_with_ntp.py
- qemu/tests/timerdevice_tscsync_change_host_clksource.py
- qemu/tests/timerdevice_tscsync_longtime.py
- qemu/tests/timerdevice_tscwrite.py
a bytes-like object is required, not 'str'
bug id: 1693995
> timerdevice: fix python3 issue

- qemu/tests/cfg/timerdevice.cfg
Timer device cases need variant up.
bug id: 1701138
> timerdevice: remove "no up"

- qemu/tests/migration.py
- qemu/tests/migration_with_reboot.py
Currently the "pre_migrate" and "post_migrate" is only supported in the
stock "migrate.py" test. This patch puts the related functions on top of
the module, adds the needed variables as arguments and uses those
methods from the migrate.with_reboot test.
Note it'd be much nicer to implement this in framework, but that would
take a lot of backward-compatible code, therefor this looks like a
bearable compromise.
> qemu.migration: Add support for pre/post-migrate for reboot mig

- qemu/tests/cfg/timerdevice.cfg
> timerdevice: add "only Linux" for some cases

- qemu/tests/migration_with_reboot.py
tp-qemu will not be installed to global if we using virtual env. So import `migration` from `qemu.tests`
ID: 1708019
> migration_with_reboot: fix ImportError when using virtual env

- qemu/tests/bridge_mirror.py
- qemu/tests/bridge_vlan.py
- qemu/tests/cfg/bridge_mirror.cfg
- qemu/tests/cfg/bridge_vlan.cfg
1. Skip bridge testcases if host bridge backend is OVS
These two testcases only supported linux bridge, skip test them if 
using ovs. Determine whether br_backend is equal to Bridge()
2. Use other methods to create bridge and set promiscuous mode
Use the methods in the framework to create bridge and modify 
promiscuous mode
3. Upgrade the codes of 'bridge_vlan'
Since "only linux" has been defined in cfg, make a small code upgrade
ID: 1663076
> Skip bridge testcases if host bridge backend is OVS

- generic/tests/cfg/avocado_guest.cfg
include new testcases from avocado-misc-tests in
`avocado_guest` to test inside guest.
> avocado_guest: add memory, numa and stress testcases

- qemu/tests/timerdevice_clock_drift_with_ntp.py
If running cmd fails, we need to raise exception instead of
ignoring its status and output.
bug id: 1710282
> timerdevice_clock_drift_with_ntp: replace session.sendline

- qemu/tests/timerdevice_clock_drift_with_sleep.py
Usleep is deprecated, and will be removed in near future.
Previous timeout is short if guest there are many cpus.
bug id: 1707343
> timerdevice_clock_drift_with_sleep: modify sleep and timeout

- qemu/tests/cfg/win_irq_check.cfg
- qemu/tests/win_irq_check.py
1. Add default irq check for vioscsi, viostor, vioserial, vioinput, netkvm drivers.
2. Add disable MSI from guest test case for vioscsi, viostor, vioserial, vioinput, netkvm drivers.
id: 1566855 1566852
> win_irq_check: Add irq check for all other supported driver

- qemu/tests/balloon_check.py
Need check the return value of "wait_for", otherwise the following
test steps will be affected.
id: 1697287
> balloon_check: check if guest memory turn to stable status

- qemu/tests/cfg/virtual_nic.cfg
set params 'wait_bg_time' equal to 'netperf_test_duration'
ID: 1711120
> virtual_nic.send_buffer: set params 'wait_bg_time'

- qemu/tests/cfg/qmp_command.cfg
For q35, hotplug device should specidy bus, add device to "pcie-root-port".
without "bus",it will use bus "pcie.0" which does not suppot hotplug.
id: 1709814
> qmp_command: Specify bus when execute 'device_add' with q35

- qemu/tests/cfg/openflow_acl_test.cfg
- qemu/tests/openflow_acl_test.py
lftp is removed from RHEL8 repo. Use wget to replace lftpget.
id: 1665445
> openflow_acl_test: use wget as a replacement of lftp

- generic/tests/cfg/ntttcp.cfg
delete "numa_node = -1"
id:1709635
> ntttcp.cfg: need not use numa_node for this case

- qemu/tests/cfg/multi_nics_verify.cfg
Add multique variant and limit 8 mq for windows 32 bit
id: 1688109
> multi_nics_verify: boot with 8 nics with mq on windows 32bit guest

- generic/tests/cfg/timerclock.cfg
> timerclock: define different patterns for different RHELs

- qemu/tests/transfer_file_over_ipv6.py
The old design match wrong md5 value if execute md5sum command failed
id: 1713595
> transfer_file_over_ipv6: To catch correct error info

- qemu/tests/qemu_guest_agent.py
Add exception of 'fsfreeze is limited up to 10 seconds' in check_hotplug_frozen function.
ID: 1714423
> qemu_guest_agent: fix fsthaw failed issue in check_hotplug_frozen func

- qemu/tests/boot_with_max_queues.py
- qemu/tests/cfg/boot_with_max_queues.cfg
1. boot guest with "queues=256,vectors=514", check the guest status.
2. do scp test with max queues.
id:1485225
> boot_with_max_queues.py: boot guest with max queues

- qemu/tests/migration.py
When the test is executed via "run_virt_sub_test" (imported) it will not
contain the top-level functions in locals() and the use of globals() is
needed.
Reported-by: Li Jin <lijin@redhat.com>
> qemu.migration: Use globals instead of locals for get_functions
