autotest/tp-qemu

- qemu/tests/cfg/balloon_uniqueness.cfg
> balloon_uniqueness: Fix NoneType error

- qemu/tests/cfg/rh_kernel_update.cfg
> rh_kernel_update: Update params for RHEL.8 guest

- qemu/tests/cfg/boot_with_different_vectors.cfg
> Delete the Windows guest as a parameter of the netperf server

- qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
qemu_guest_agent_hotplug.py: Add params for checking vioser setup
Add some parameters for checking whether virtio-serial is installed
ID: 1950194
> qemu_guest_agent_hotplug.py: Add params for checking vioser setup

- qemu/tests/cfg/virtio_serial_file_transfer.cfg
> virtio_serial:set iommu and legacy options as default config while transferring data

- qemu/tests/cfg/virtual_nic.cfg
> Limit guest startup memory size

- qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
1. qemu_guest_agent_hotplug.cfg: delete unwanted character
ID: 1950888
> qemu_guest_agent: Hotfix for deleting unwanted character.

- qemu/tests/cfg/mq_change_qnum.cfg
- qemu/tests/mq_change_qnum.py
> Change the test parameters of the mq_change_qnum file

- qemu/tests/cfg/vioinput_enable.cfg
- qemu/tests/cfg/vioinput_keyboard.cfg
- qemu/tests/cfg/vioinput_mice.cfg
- qemu/tests/driver_in_use.py
- qemu/tests/vioinput_keyboard.py
- qemu/tests/vioinput_mice.py
For all called setup_win_driver_verifier() cases,
do updates to match with adjusts.
ID: 1919753
> Update all cases that called setup_win_driver_verifier()

- qemu/tests/cfg/rng_bat.cfg
> rng_iommu: restrict iommu testing only for Intel platform

- qemu/tests/blockdev_commit_backing_file.py
- qemu/tests/cfg/blockdev_commit_backing_file.cfg
> blockdev_commit_backing_file: Block commit "backing-file" option test

- qemu/tests/balloon_check.py
- qemu/tests/balloon_service.py
- qemu/tests/cfg/balloon_service.cfg
Get memory cache from guest and qmp,check if they
are the same.
ID: 1946456
> balloon_check: check memory cache from guest and qmp

- qemu/tests/cfg/verify_panic_status_with_pvpanic.cfg
Restrict this case only for Linux guest
ID: 1951410
> verify_panic_status_with_pvpanic: Restrict to linux

- qemu/tests/cfg/chardev_tls_encryption.cfg
- qemu/tests/chardev_tls_encryption.py
> chardev:fix tls_encryption command issue and wrong device type on ppc

- qemu/tests/cfg/fio_perf.cfg
> fio_perf: add image_aio = native

- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/virtio_fs_set_capability.py
New case set capability and then run virtiofsd
ID: 1912231,1934910
> virtio-fs: New case set capability

- qemu/tests/cfg/usb.cfg
- qemu/tests/cfg/usb_device_check.cfg
> usb_ehci:disable usb_ehci test cases on power

- qemu/tests/cfg/x86_cpu_model.cfg
> x86_cpu_model: add new model Snowridge

- qemu/tests/qemu_guest_agent.py
qemu_guest_agent.py: Changes for 'get_devices' on qemu5.2 rebase
1. Use common time encoding for guest-get-devices 'driver-date'
2. Rename guest-get-devices return member 'address' to 'id'
ID: 1936295
> qemu_guest_agent.py: Changes for 'get_devices' on qemu5.2 rebase

- qemu/tests/cfg/x86_cpu_flags.cfg
> x86_cpu_flags: new flag 'pku' supported on Milan

- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_mirror_install.cfg
- qemu/tests/cfg/blockdev_snapshot_install.cfg
- qemu/tests/cfg/blockdev_stream_install.cfg
> block installation test: Disable data plane when using virtio-scsi

- qemu/tests/cfg/virtual_nic.cfg
- qemu/tests/virtual_nic_stress.py
> Change the test contant in virtual_nic_stress file

- qemu/tests/cfg/seabios_reboot_timeout.cfg
> seabios_reboot_timeout: detail the host restriction for case time65536

- generic/tests/cfg/netstress_kill_guest.cfg
- generic/tests/netstress_kill_guest.py
- provider/netperf_test.py
> Change the test logic of case netstress_kill_guest

- qemu/tests/netperf_udp_perf.py
> netperf_udp_perf: remove nic_index=1 in vm.copy_files_to

- qemu/tests/cfg/usb_device_check.cfg
> usb_device_check: update chk_usb_info_cmd for latest RHEL guest

- qemu/tests/queues_number_test.py
> Solve the problem of broken pipe caused by lack of session

- qemu/tests/timerdevice_clock_drift_with_sleep.py
> timerdevice_clock_drift_with_sleep: adjust the results threshold

- qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
> cpu_device_hotplug_maximum: Skip test with iommu on AMD platform

- qemu/tests/blockdev_commit_filter_node_name.py
- qemu/tests/cfg/blockdev_commit_filter_node_name.cfg
> blockdev_commit_filter_node_name:block commit with filter-node-name

- qemu/tests/cfg/virtio_fs_multi_vms.cfg
- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_multi_vms.py
- qemu/tests/virtio_fs_set_capability.py
- qemu/tests/virtio_fs_share_data.py
Register a virtiofs service to start a shared directory in windows guest and record viriofs log in it.
ID: 1946429, 1946423
> virtio-fs: new case of record virtiofs log in windows guest

- qemu/tests/ksm_ksmtuned.py
> ksm_ksmtuned: Fix issues with windows guest

- qemu/tests/blockdev_inc_backup_with_complete_mode.py
- qemu/tests/cfg/blockdev_inc_backup_with_complete_mode.cfg
grouped: the first job should be cancelled
default: the first job should complete without any error
The second job will always get the 'No space left' error
ID: 1945878
> blockdev_inc_backup_with_complete_mode: completion-mode negative test

- qemu/tests/cfg/multi_nics_hotplug.cfg
- qemu/tests/cfg/netkvm_in_use.cfg
- qemu/tests/cfg/nic_hotplug.cfg
> Add image backup parameters

- qemu/tests/nic_bonding.py
> Change the method of setup bond0

- qemu/tests/virtio_fs_multi_vms.py
Need to send vm object to every vm.
ID: 1906677
> virtio_fs_multi_vms: fix 'str' object has no attribute 'params' error

- qemu/tests/numa_consistency.py
> numa:increase initial memory size since the old is boundary value on power

- qemu/tests/virtio_net_dpdk.py
> virtio_net_dpdk: add function unbind_dpdk_nic

- provider/message_queuing.py
- qemu/tests/cfg/nested_block_resize.cfg
- qemu/tests/cfg/nested_block_resize_l1.cfg
- qemu/tests/nested_block_resize.py
- qemu/tests/nested_block_resize_l1.py
> Add block resize test in nested ENV

- qemu/tests/cfg/pvpanic.cfg
- qemu/tests/cfg/pvpanic_basic.cfg
- qemu/tests/pvpanic.py
Add new test cases related CRASHLOADED for pvpanic device
id: 1947751 1947715
> pvpanic.py: Add new feature for pvpanic device

- qemu/tests/cfg/multi_nics_hotplug.cfg
Virtual_network: modify the annotation of cfg file
ID: 1942866
> Modify multi_nic_hotplug for s390x

- qemu/tests/cfg/passthrough_with_multipath_device.cfg
- qemu/tests/passthrough_with_multipath_device.py
> block:passthrough with multipath device

- qemu/tests/blockdev_commit_general_operation.py
- qemu/tests/cfg/blockdev_commit_general_operation.cfg
> blockdev_commit_general_operation:block commit general operation

- qemu/tests/cfg/multi_nics_hotplug.cfg
- qemu/tests/cfg/nic_hotplug.cfg
- qemu/tests/nic_hotplug.py
> Change the text content of nic_hotplug

- qemu/tests/cfg/watchdog.cfg
> watchdog:remove rdma migration test for watchdog on ppc

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Create and delete folder and copy file to it in shared directory.
ID: 1900964
> virtio_fs: Add folder test in shared directory

- qemu/tests/cfg/vsock.cfg
Add iommu test for vsock
ID: 1961987
> vsock: Add iommu test for vsock

- qemu/tests/cfg/create_large_img.cfg
> create_large_img: add filter to image format

- qemu/tests/cfg/tpm_verify_device.cfg
Fix tpm information in ovmf log change issue on rhel9
ID: 1967501
> Fix tpm information in ovmf log change issue on rhel9

- qemu/tests/cfg/check_link_speed_duplex.cfg
> Add "no RHEL.7" to file check_link_speed_duplex.cfg

- generic/tests/cfg/boot_vm_in_hugepage.cfg
- qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
- qemu/tests/cfg/hpt.cfg
- qemu/tests/cfg/hpt_max_page_size.cfg
- qemu/tests/cfg/hugepage_mem_stress.cfg
- qemu/tests/cfg/hugepage_reset.cfg
- qemu/tests/cfg/hugepage_specify_node.cfg
- qemu/tests/cfg/slof_hugepage.cfg
- qemu/tests/hugepage_mem_stress.py
- qemu/tests/hugepage_reset.py
- qemu/tests/hugepage_specify_node.py
- qemu/tests/slof_hugepage.py
Signed-off-by: Yumei Huang yuhuang@redhat.com
ID: 1926689
Depends on https://github.com/avocado-framework/avocado-vt/pull/3073.
> Update hugepage related test cases to avoid extra_params

- qemu/tests/numa_cpu.py
> numa_cpu: Fix issue with 32bit guests

- qemu/tests/cfg/usb.cfg
> usb:remove usb_smartcard and usb_redir test cases on ppc

- qemu/tests/cfg/boot_nic_with_iommu.cfg
- qemu/tests/cfg/nic_hotplug.cfg
> Add "caching-mode=on" option for iommu device

- qemu/tests/cfg/balloon_memhp.cfg
- qemu/tests/cfg/cpu_device_hotpluggable.cfg
- qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
> Update windows guest restriction for some cases

- provider/win_driver_installer_test.py
- provider/win_driver_utils.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_install_by_installer.py
- qemu/tests/win_virtio_driver_installer_repair.py
- qemu/tests/win_virtio_driver_installer_uninstall.py
- qemu/tests/win_virtio_driver_update_by_installer.py
Support install virtio-win drivers via virtio-win-guest-tools.exe
for windows guest.
ID: 1893692, 1898762, 1898763
> win_driver_install_by_installer: Add new test case

- qemu/tests/cfg/qmp_command.cfg
> qmp_command: remove query-cpu case

- qemu/tests/cfg/x86_cpu_flags.cfg
> x86_cpu_flags:test SPR new flags

- qemu/tests/cfg/nvdimm.cfg
ID: 1972595
Depends on https://github.com/avocado-framework/avocado-vt/pull/3103.
> nvdimm_readonly: Add new case to test readonly option

- qemu/tests/cfg/hv_cpu_hotplug.cfg
> hv_cpu_hotplug: Add new support win2022 guest

- qemu/tests/cfg/disk_extension_lvm.cfg
- qemu/tests/disk_extension_lvm.py
> Add case of disk extension on lvm backend

- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/virtio_fs_set_capability.py
qcontainer: Add virtiofsd user config method
Update this method in tp-qemu case
ID: 1969269
> virtio_fs_set_capability: update virtiofsd user config method

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
- qemu/tests/qemu_guest_agent.py
Move qga installation code logic to internal file,
and change some parameter name.
ID: 1890839, 1886685
> qemu_guest_agent.py: Move qga installation code logic away

- qemu/tests/cfg/x86_cpu_model.cfg
> x86_cpu_model: add new model 'max'

- qemu/tests/cfg/x86_cpu_flags.cfg
- qemu/tests/x86_cpu_flags.py
> x86_cpu_flags: update case's step

- qemu/tests/cfg/uefishell.cfg
- qemu/tests/uefishell.py
> uefishell.check_smbios: add support for type=2

- qemu/tests/blockdev_commit_standby.py
- qemu/tests/cfg/blockdev_commit_standby.cfg
blockdev_commit_standby:complete a standby commit job
id: 1975687
> New case: complete a standby commit job

- qemu/tests/cfg/sve_basic.cfg
- qemu/tests/sve_basic.py
- qemu/tests/sve_invalid.py
ID: 1970784, 1970785, 1970786
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3094
> Add some basic test cases of SVE

- qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
- qemu/tests/cpu_device_hotplug_maximum.py
> cpu_device_hotplug_maximum: disable topology check for some guests

- qemu/tests/cfg/usb.cfg
> pci_ohci:remove the test case from usb_boot test on ppc

- qemu/tests/cfg/nic_hotplug.cfg
- qemu/tests/nic_hotplug.py
> The default nic is changed after hotplug,causing login failure

- qemu/tests/cfg/hugepage_reset.cfg
- qemu/tests/hugepage_reset.py
> hugepage_reset: Add stress for windows guest

- qemu/tests/cfg/qmp_command.cfg
> replaced 'query-events' with 'query-qmp-schema'

- qemu/deps/thin-provision/sg_write_same.sh
- qemu/tests/block_discard_write_same.py
- qemu/tests/cfg/block_discard_write_same.cfg
> Add new case write same support on discard disk

- qemu/tests/cfg/sve_suite.cfg
- qemu/tests/sve_guest_suite.py
- qemu/tests/sve_host_suite.py
Add 3 test cases to use test suites to test SVE on host and guest.
ID: 1979211, 1979213, 1979214
> Add test cases using test suites to test SVE

- qemu/tests/cfg/change_media.cfg
Virtual_block: switch directory of saving iso from /tmp to /var/tmp
ID: 1969231
> Change directory of saving iso

- qemu/tests/cfg/ksm_ksmtuned.cfg
- qemu/tests/ksm_ksmtuned.py
> ksm_ksmtuned: Stress guest to increase qemu memory usage

- qemu/tests/balloon_boot_in_pause.py
- qemu/tests/balloon_check.py
- qemu/tests/balloon_minimum.py
- qemu/tests/cfg/balloon_illegal.cfg
Before checking balloon changed value is to compared with the original value
which is not accurate.
So modify it to compare with memory value before balloon action.
ID: 1828754
> Balloon_check: check balloon changed value with the previous value

- qemu/tests/blockdev_snapshot_nonexist_target.py
- qemu/tests/cfg/blockdev_snapshot_nonexist_target.cfg
> New case:RHEL-177340 - Snapshot to a non-exist target

- qemu/tests/blockdev_snapshot_guest_agent.py
- qemu/tests/cfg/blockdev_snapshot_guest_agent.cfg
> New case:RHEL-177342 - Snapshot with guest agent

- qemu/tests/blockdev_snapshot_readonly.py
- qemu/tests/cfg/blockdev_snapshot_readonly.cfg
> New case:RHEL-187695 - Snapshot on read-only drive

- qemu/tests/cfg/cpu_device_hotplug_time_jump.cfg
> cpu_device_hotplug_time_jump: Update expected_gap

- qemu/tests/blockdev_commit_fio.py
- qemu/tests/cfg/blockdev_commit_fio.cfg
> blockdev_commit_fio:Block commit under stress with fio

- qemu/tests/blockdev_full_backup_nonexist_target.py
- qemu/tests/cfg/blockdev_full_backup_nonexist_target.cfg
> blockdev_full_backup_nonexist_target: Full backup to a non-existed target

- qemu/tests/blockdev_full_backup_invalid_sync_mode.py
- qemu/tests/cfg/blockdev_full_backup_invalid_sync_mode.cfg
> blockdev_full_backup_invalid_sync_mode: Full backup with invalid sync mode

- qemu/tests/blockdev_snapshot_merge.py
- qemu/tests/cfg/blockdev_snapshot_merge.cfg
> blockdev_snapshot_merge: Merge the snapshot chain

- qemu/tests/blockdev_full_backup_with_bitmap.py
- qemu/tests/cfg/blockdev_full_backup_with_bitmap.cfg
> blockdev_full_backup_with_bitmap: Full backup with bitmap

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Get file's st_dev of different device.
ID: 1978153
> virtio-fs: new case to check file's stdev

- generic/tests/cfg/unattended_install.cfg
1. Support ovmf install
2. Reduce disk number for windows virtio-blk installation
ID:1714485
> Fix unattended_install issue

- qemu/tests/cfg/x86_cpu_model.cfg
> x86_cpu_model: update some cases' steps

- qemu/tests/cfg/cpu_pm.cfg
ID: 1982951
Depends on https://github.com/avocado-framework/avocado-vt/pull/3144.
> Add new case to test option 'cpu_pm'

- qemu/tests/blockdev_inc_backup_no_bitmap.py
- qemu/tests/cfg/blockdev_inc_backup_no_bitmap.cfg
Do incremental live backup without bitmap
id:1983923
> blockdev_inc_backup_no_bitmap: Do incremental live backup without bitmap

- qemu/tests/blockdev_inc_backup_merge_with_nonexist_bitmap.py
- qemu/tests/cfg/blockdev_inc_backup_merge_with_nonexist_bitmap.cfg
Merge with a non-existed bitmap
id:1984268
> blockdev_inc_backup_merge_with_nonexist_bitmap:Merge with a non-existed bitmap

- qemu/tests/cfg/nic_opt.cfg
> nic_opt: Remove architecture restrictions

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
Add steps to check qga.service running log in rhel guest,
in case miss the error/failed/warning message.
ID: 1974778
> qemu_guest_agent: Add steps to check qga.service running log

- qemu/tests/x86_cpu_L3_cache.py
> x86_cpu_L3_cache:update the checkpoint

- qemu/tests/expose_host_mtu.py
Unfortunately, s390 will always return 0 when get_mtu on utils_net, this
should be a problem of s390 via using socket connection. Change methods
of then to support s390.
ID: 1982918
> expose_host_mtu: Change get_mtu/set_mtu methods to support s390

- qemu/tests/qemu_guest_agent.py
1. change the parameter name 'qga_ver_guest' for windows
2. add condition 'main_qga_ver >= 102' for windows
ID: 1988830
> qemu_guest_agent.py: Fix some minor issues

- qemu/tests/cfg/nvdimm.cfg
> nvdimm:remove nvdimm_redis test on power

- qemu/tests/blockdev_mirror_cancel_running_job.py
- qemu/tests/cfg/blockdev_mirror_cancel_running_job.cfg
Cancel a running mirror job
id:1985937
> blockdev_mirror_cancel_running_job:Cancel a running mirror job

- qemu/tests/blockdev_mirror_qemuio_ready_job.py
- qemu/tests/cfg/blockdev_mirror_qemuio_ready_job.cfg
Qemu-io source image when commit job reach ready status
id:1986300
> blockdev_mirror_qemuio_ready_job:Qemu-io source image when commit job reach ready status

- qemu/tests/blockdev_stream_to_invalid_node.py
- qemu/tests/cfg/blockdev_stream_to_invalid_node.cfg
Stream to an invalid node of the chain
id:1989000
> blockdev_stream_to_invalid_node:Stream to an invalid node of the chain

- qemu/tests/block_resize.py
On s390x virtio-blk test, the disk letter might change after
guest reboot, so add code to get it again after guest reboot
and make the code be suitable to all archs
ID: 1986668
> block_resize: Get new disk label after guest reboot

- provider/backup_utils.py
- qemu/tests/blockdev_stream_filter_nodename.py
- qemu/tests/cfg/blockdev_stream_filter_nodename.cfg
> blockdev_stream_filter_nodename:Block stream with filter-node-name set

- qemu/tests/physical_resources_check.py
Skip memory checking on vm_mem_limit setting
ID:1908606
> Fix memory checking issue

- qemu/tests/cfg/virtio_fsd_check_info.cfg
- qemu/tests/virtio_fsd_check_info.py
Check virtiofsd version an copyright
ID: 1988943
> virtio-fs: new case to check virtiofsd info

- qemu/tests/virtio_port_hotplug.py
> virtio_port_hotplug: split host_proc_pid to fix the error

- qemu/tests/cfg/timedrift_adjust_time.cfg
- qemu/tests/cfg/timedrift_with_multi_vms.cfg
> timedrift:Add timebase clock source

- qemu/tests/blockdev_stream_base_itself.py
- qemu/tests/cfg/blockdev_stream_base_itself.cfg
Block stream based on itself
id:1989793
> blockdev_stream_base_itself:Block stream based on itself

- qemu/tests/blockdev_stream_powerdown.py
- qemu/tests/cfg/blockdev_stream_powerdown.cfg
Power down during block stream
id:1989828
> blockdev_stream_powerdown:Power down during block stream

- qemu/tests/cfg/spapr_vty_multi_backends.cfg
- qemu/tests/spapr_vty_multi_backends.py
> spapr_vty:add migration test for feature spapr_vty on ppc

- provider/netperf_test.py
- qemu/tests/boot_with_different_vectors.py
- qemu/tests/cfg/boot_with_different_vectors.cfg
- qemu/tests/cfg/flow_caches_stress_test.cfg
- qemu/tests/cfg/migrate.cfg
- qemu/tests/cfg/multi_nics_stress.cfg
- qemu/tests/cfg/netperf_stress_test.cfg
- qemu/tests/cfg/nic_opt.cfg
- qemu/tests/cfg/queues_number_test.cfg
- qemu/tests/flow_caches_stress_test.py
- qemu/tests/migration_with_netperf.py
- qemu/tests/multi_nics_stress.py
- qemu/tests/netperf_stress.py
- qemu/tests/nic_opt.py
> Change the code execution logic to capture error messages

- qemu/tests/seabios_bin.py
> seabios.bin_file: add support for pc-i440fx-4.2 and pc-i440fx-2.11

- qemu/tests/ctrl_vlan.py
According to product changes,adjust automation script.
ID:1994456
> ctrl_vlan: ajust vlan table expected value

- qemu/tests/usb_redir.py
- qemu/tests/usb_smartcard_sharing.py
usb smartcard sharing works only with spice.
ID: 1964826
> usb_smartcard_sharing: Add check for spice connection

- qemu/tests/cfg/blockdev_stream_to_invalid_node.cfg
Update error msg for virtio_blk
id:1995397
> blockdev_stream_to_invalid_node.cfg:update error msg

- qemu/tests/blockdev_stream_with_ioerror.py
- qemu/tests/cfg/blockdev_stream_with_ioerror.cfg
Do block stream after block error(read/write/no space)
id:1994868
> blockdev_stream_with_ioerror:stream after block error

- qemu/tests/blockdev_commit_with_ioerror.py
- qemu/tests/cfg/blockdev_commit_with_ioerror.cfg
Do live commit after block error(read/write/no space)
id:1994948
> blockdev_commit_with_ioerror: commit after io error

- qemu/tests/blockdev_commit_to_nospace.py
- qemu/tests/cfg/blockdev_commit_to_nospace.cfg
Live commit to non-enough space storage
id:1995410
> blockdev_commit_to_nospace:commit to non-enough space

- provider/backup_utils.py
- qemu/tests/blockdev_commit_with_ignore.py
- qemu/tests/cfg/blockdev_commit_with_ignore.cfg
Live commit with on-error "ignore"
id:1995494
> blockdev_commit_with_ignore:commit with io-error:ignore

- qemu/tests/cfg/balloon_memhp.cfg
- qemu/tests/cfg/cpu_device_hotpluggable.cfg
- qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
> Remove Win11 guest support for some hotplug cases

- qemu/tests/cfg/virtio_aer_opt.cfg
- qemu/tests/virtio_aer_opt.py
> virtio_aer_opt: new case to check aer and ats capabilties in guest os

- qemu/tests/cfg/block_check_event.cfg
Add support for win11 and win2022 for this case
ID: 2000377
> block_check_event：Add support for win11 and win2022

- qemu/tests/cfg/x86_cpu_flags.cfg
- qemu/tests/x86_cpu_flags.py
> x86_cpu_flags:update test policy for one case

- qemu/tests/cfg/x86_cpu_model.cfg
> x86_cpu_model: add new cpu model -v*

- qemu/tests/cfg/passthrough_fc_with_lun_device.cfg
- qemu/tests/passthrough_fc_with_lun_device.py
> Add io testing on the FC passthrough with lun device

- qemu/tests/cfg/timedrift_check_clock_offset.cfg
> update qga installation configuration in timer device case

- qemu/tests/cfg/virtio_driver_sign_check.cfg
Add fwcfg signtool check support on virtio_driver_sign_check
id: 1992923
> virtio_driver_sign_check: Add fwcfg signtool check support

- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
Add qemu version limit on with_stdev_check
ID: 2005562
> virtio_fs:Add qemu version limit on with_stdev_check

- qemu/tests/bridge_qinq.py
Due to no left space, changed the file path. The root cause of
no left space is because "/tmp" is a tmpfs file system, its size
is half of the memory, so if the memory is too small, there is
no space to copy temporary files
ID:2005571
> bridge_qinq:Change the path of the transferred file

- qemu/tests/qemu_img.py
add base image format for the command of snapshot creation
ID: 2002513
> qemu_img: fix sub case of commit

- qemu/tests/blockdev_commit_throttle.py
- qemu/tests/cfg/blockdev_commit_throttle.cfg
Commit to throttle node
id:2003941
> blockdev_commit_throttle:commit to throttle node

- qemu/tests/blockdev_mirror_with_ignore.py
- qemu/tests/cfg/blockdev_mirror_with_ignore.cfg
Mirror with on-target-error "ignore"
id:2002566
>  blockdev_mirror_with_ignore:mirror with target error ignore

- qemu/tests/blockdev_inc_backup_with_ignore.py
- qemu/tests/cfg/blockdev_inc_backup_with_ignore.cfg
Do incremental live backup with on-target-error "ignore"
id:2003542
> blockdev_inc_backup_with_ignore:do incremental backup with ignore

- qemu/tests/cfg/nic_acpi_index.cfg
- qemu/tests/nic_acpi_index.py
- qemu/tests/nic_acpi_index_boot.py
1.When "acpi-index=N" is enabled, NIC name should always be ethN
ID:1996492
> Add a new case of virtual network option

- generic/tests/cfg/kdump.cfg
- qemu/tests/cfg/pvpanic.cfg
- qemu/tests/cfg/pvpanic_basic.cfg
- qemu/tests/cfg/verify_panic_status_with_pvpanic.cfg
Update pvpanic configuration steps on aarch64
id: 2007081 
> dump:Update pvpanic configuration steps on aarch64

- qemu/tests/block_iscsi_4kdisk.py
- qemu/tests/cfg/block_iscsi_4kdisk.cfg
> Add windows installation with blk+raw+iothread on 4k disk

- qemu/tests/cfg/hv_tlbflush.cfg
- qemu/tests/cfg/trim_support_test.cfg
> hv_tlbflush/trim_support_test:use qemu version to limit the cases

- qemu/tests/cfg/uefishell.cfg
> uefishell.check_network: extend time interval to get ip address

- qemu/tests/block_check_serial.py
- qemu/tests/cfg/block_check_serial.cfg
> Add check serial length test

- qemu/tests/cfg/discard_for_raw_block_target.cfg
> discard_for_raw_block_target: add 4k sector size support

- qemu/tests/cfg/virtio_fs_multi_vms.cfg
- qemu/tests/cfg/virtio_fs_readonly.cfg
- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
- qemu/tests/cfg/virtio_fsd_check_info.cfg
Update virtio-fs configuration steps on S390
ID:2008086 
> virtio_fs:Update virtio-fs configuration steps on S390

- qemu/tests/watchdog.py
> watchdog: correct format of console output for some test case

- qemu/tests/virtio_fs_share_data.py
Update code to umount nfs finally.
ID: 1974163
> virtio_fs: need to umount nfs finally

- qemu/tests/cfg/virtio_fs_multi_vms.cfg
- qemu/tests/cfg/virtio_fs_readonly.cfg
- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
- qemu/tests/cfg/virtio_fsd_check_info.cfg
Update mem share option configuration on S390
ID:2018111
> virtio_fs:Update mem share option configuration on S390

- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_mirror_install.cfg
- qemu/tests/cfg/blockdev_snapshot_install.cfg
- qemu/tests/cfg/blockdev_stream_install.cfg
Add new install tag for blockdev_stream_install,
blockdev_snapshot_install, blockdev_mirror_install,
blockdev_commit_install
id:2007553
> blockdev_stream_install:new install tag added for rhel9

- qemu/tests/cfg/rng_maxbytes_period.cfg
- qemu/tests/cfg/virtio_mode.cfg
aarch64:update virtio-rng limits
ID:2018907
> aarch64:update virtio-rng limits

- qemu/tests/cfg/cgroup.cfg
> cgroup:disable blkio_bandwidth test case on ppc

- qemu/tests/cfg/watchdog.cfg
> watchdog: correct the trigger command for heartbeat_test

- qemu/tests/blockdev_commit_firewall.py
- qemu/tests/cfg/blockdev_commit_firewall.cfg
Using firewall to stop live commit
id:2018118
> blockdev_commit_firewall:live commit with firewall

- qemu/tests/blockdev_commit_cor.py
- qemu/tests/cfg/blockdev_commit_cor.cfg
Commit with copy-on-read filter on top
id:2014969
> blockdev_commit_cor:add support for cor filter

- qemu/tests/blockdev_stream_cor_base.py
- qemu/tests/cfg/blockdev_stream_cor_base.cfg
Block stream with base: copy-on-read node
id:2017292
> blockdev_stream_cor_base: stream with cor filter as base

- qemu/tests/cfg/blockdev_stream_cor.cfg
Block stream on copy-on-read filter
id:2017282
> blockdev_stream_cor:block stream on cor filter

- qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
- qemu/tests/virtio_fs_share_data.py
Add memory-backend-file with hugepage and numa.
ID: 2016895
> virtio_fs: add hugepage memory backend

- qemu/tests/cfg/chardev_tls_encryption.cfg
- qemu/tests/cfg/serial_no_listening.cfg
- qemu/tests/virtio_serial_hotplug_max_chardevs.py
aarch64:update checkdev judging
ID: 2020550
> aarch64:update checkdev judging

- qemu/tests/cfg/pvpanic.cfg
- qemu/tests/cfg/pvpanic_basic.cfg
> pvpanic:update path of nmi in the guest on ppc

- generic/tests/cfg/multi_queues_test.cfg
- generic/tests/multi_queues_test.py
- provider/netperf_test.py
- qemu/tests/cfg/boot_with_different_vectors.cfg
- qemu/tests/cfg/bridge_vlan.cfg
- qemu/tests/cfg/flow_caches_stress_test.cfg
- qemu/tests/cfg/mq_change_qnum.cfg
- qemu/tests/cfg/multi_nics_stress.cfg
- qemu/tests/cfg/netperf_stress_test.cfg
- qemu/tests/cfg/nic_opt.cfg
- qemu/tests/cfg/queues_number_test.cfg
- qemu/tests/flow_caches_stress_test.py
- qemu/tests/mq_change_qnum.py
- qemu/tests/multi_nics_stress.py
- qemu/tests/netperf_stress.py
- qemu/tests/nic_opt.py
- qemu/tests/queues_number_test.py
> Change the running logic of netperf and shorten the startup time

- generic/tests/cfg/kdump.cfg
- generic/tests/kdump.py
> kdump:update nmi path in the guest for kdump scenario

- qemu/tests/nic_opt.py
> nic_opt: Change to ping guest from host

- qemu/tests/cfg/qemu_img.cfg
- qemu/tests/qemu_img.py
Due to the process completion time being too fast, 
Reduce the cycle interval time and add dd step.
ID:2023601
> qemu_img:Reduce the cycle interval time and add dd step

- provider/throttle_utils.py
- qemu/tests/cfg/throttle_parameter_test.cfg
Add throttle_runtime interface
ID:2026574
> io-throttling:Add throttle_runtime interface

- qemu/tests/cgroup.py
> cgroup:adjust the vm's maxcpus when it's set to an half of host's

- qemu/tests/blockdev_inc_backup_modify_backing_bitmaps.py
Add support to raw driver
id:2024070
> blockdev_inc_backup_modify_backing_bitmaps:add support to raw driver

- qemu/tests/cfg/unattended_install_reboot_driftfix.cfg
> unattended_install_reboot_driftfix: update ovmf related cfg

- qemu/tests/cfg/qemu_guest_agent.cfg
Delete virtio_blk test for check_hotplug_frozen on ppc64le.
ID: 2023230
> qemu_guest_agent: Delete virtio_blk test for check_hotplug_frozen

- qemu/tests/cfg/throttle_multi_guests_parameter_test.cfg
- qemu/tests/cfg/throttle_operation_test.cfg
- qemu/tests/cfg/throttle_parameter_test.cfg
Update io-throttling configuration on PPC
ID:2027895
> io-throttling:Update io-throttling configuration on PPC

- qemu/tests/cfg/passthrough_fc_with_lun_device.cfg
> passthrough_fc_with_lun_device: Fix cache mode error

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
This reverts commit 08b5a4150546a59172d990c696816cecc912d15f.
ID: 2024789
Signed-off-by: demeng demeng@redhat.com
> Revert "Add new case that start qga container"

- provider/backup_utils.py
- provider/virt_storage/storage_volume.py
- qemu/tests/blockdev_snapshot_data_file.py
- qemu/tests/cfg/blockdev_snapshot_data_file.cfg
> blockdev_snapshot_data_file: snapshot to target created with data_file

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
Remove dump from distribution on the specified version
ID:2029702
> virtio-fs:Remove dump from distribution on specified version

- qemu/tests/cfg/cpu_info_check.cfg
> cpu_info_check:use default autotest policy

- qemu/tests/cfg/x86_cpu_flags.cfg
> x86_cpu_flags: update step for 'tsc'

- qemu/tests/cfg/block_iscsi_4kdisk.cfg
- qemu/tests/cfg/block_iscsi_lvm.cfg
> block_iscsi_4kdisk:block_iscsi_lvm:add ovmf installation support

- qemu/tests/block_iscsi_fault_disk.py
- qemu/tests/cfg/block_iscsi_fault_disk.cfg
> Add kill VM with fault disk case

- qemu/tests/qemu_guest_agent.py
change the way that check logoff operation whether executed well.
ID: 1808959
> qemu_guest_agent: Fix logoff issue for windows only case

- qemu/tests/luks_convert.py
- qemu/tests/qemu_img_convert_with_rate_limit.py
For luks_convert_to_raw/qcow2/luks, remove the target images.
ID: 2006683
Signed-off-by: chdong <chdong@redhat.com>
> Remove converted images after testing

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Add new case to test --socket-group.
ID: 2016893
> virtio_fs: new case to test socket-group

- qemu/tests/usb_host.py
Build new filesystem on USB stick step before getting the mount
point.
ID: 2027235
> usb_host: add building filesystem on USB stick step

- qemu/tests/cfg/virtio_aer_opt.cfg
- qemu/tests/virtio_aer_opt.py
> virtio_aer_opt:Add ats_aer options for block device

- qemu/tests/cfg/libvirt_host_model_test.cfg
- qemu/tests/libvirt_host_model_test.py
> x86_cpu_model_boot: check cpuinfo between libvirt and qemu

- qemu/tests/cfg/block_hotplug_check.cfg
- qemu/tests/pci_hotplug_check.py
Add aarch64 bus designation
ID: 2033170
> pci_hotplug_check:Add aarch64 bus designation

- provider/virt_storage/backend/rbd.py
- provider/virt_storage/helper/rbdcli.py
- provider/virt_storage/storage_admin.py
- provider/virt_storage/storage_volume.py
- provider/virt_storage/virt_source.py
- qemu/tests/blockdev_mirror_to_rbd.py
- qemu/tests/cfg/blockdev_mirror_to_rbd.cfg
> blockdev_mirror_to_rbd: do mirror to a rbd node

- qemu/tests/bridge_vlan.py
- qemu/tests/cfg/bridge_vlan.cfg
> bridge_vlan:Add NM management to support setting private ip

- qemu/tests/blockdev_full_backup_invalid_max_workers.py
- qemu/tests/cfg/blockdev_full_backup_invalid_max_workers.cfg
Backup with invalid max-workers
id:2034470
> blockdev_full_backup_invalid_max_workers:backup with invalid max-workers

- qemu/tests/cfg/qemu_guest_agent_hotplug.cfg
hot fix for this last file.
ID: 2029676
> qemu_guest_agent: Add paramters to 'qemu_guest_agent_hotplug.cfg'

- qemu/tests/cfg/hv_check_cpu_utilization.cfg
- qemu/tests/hv_check_cpu_utilization.py
Win11 can not execute 'reg' related command as permission issue.
ID: 1999008
> hv_check_cpu_utilization: Fix 'Access is denied' error for Win11

- qemu/tests/cfg/hv_check_cpu_utilization.cfg
- qemu/tests/hv_check_cpu_utilization.py
Sorry for reverting this commit since clicked the merge button by mistake.
> Revert "hv_check_cpu_utilization: Fix 'Access is denied' error for Win11"

- qemu/tests/blockdev_full_backup_invalid_sync_mode.py
- qemu/tests/cfg/blockdev_full_backup_invalid_sync_mode.cfg
Update error msg since qemu6.2
id:2034080
> blockdev_full_backup_invalid_sync_mode:update error msg

- qemu/tests/blockdev_snapshot_chains.py
Support for case "blockdev_snapshot_chains"
id:2023659
> blockdev_snapshot_chains:support raw

- qemu/tests/ksm_overcommit.py
1. Remove pid file from qemu cli
2. Fix if condition about 32 bit guests
ID: 1876448
> ksm_overcommit: Fix some issues

- qemu/tests/cfg/usb.cfg
> usb_host_negative: update usb_reply_msg with latest info

- qemu/tests/cfg/hotplug_mem_reserve.cfg
- qemu/tests/hotplug_mem_reserve.py
ID: 2012092
Depends on https://github.com/avocado-framework/avocado-vt/pull/3285.
> hotplug_mem_reserve: add new case to test reserve option

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_with_unknown_group_name.py
Support virtiofsd test with unknow socket group.
ID: 2016910
> virtio_fs: negative test of unknow socket group

- generic/tests/cfg/netperf.cfg
- generic/tests/netperf.py
Add support for failover
Signed-off-by: Wenli Quan<wquan@redhat.com>
id: 2026566
> Netperf: add support for failover

- generic/tests/cfg/pktgen_perf.cfg
- generic/tests/pktgen_perf.py
pktgen_perf: update result format
id: 2037227
> pktgen_perf: update result format

- qemu/tests/cfg/tpm_with_bitlocker.cfg
Add Win2022 guest for tpm_bitlocker test case
ID: 2039601
> Add Win2022 guest for tpm_bitlocker test case

- generic/tests/syzkaller.py
- qemu/tests/nested_test.py
PR alignes tp-qemu with software_manager changes in avocado
See: https://github.com/avocado-framework/avocado/pull/5225
id: 2040126
> software_manager: align tp-qemu with changes in avocado

- provider/throttle_utils.py
> throttle_utils:support blockdev_reopen function

- qemu/tests/blockdev_commit_fio.py
- qemu/tests/cfg/blockdev_commit_fio.cfg
Update timeout for fio.run and commit job
id:2039134
> blockdev_commit_fio: update timeout for fio run and commit job

- qemu/tests/cfg/cpu_topology_test.cfg
- qemu/tests/cpu_topology_test.py
Add aarch64 PPTT table check
ID:2041697
> cpu_topology_test:Add aarch64 PPTT table check

- qemu/tests/cfg/boot_from_device.cfg
- qemu/tests/cfg/seabios.cfg
- qemu/tests/cfg/seabios_bootmenu_prompt.cfg
- qemu/tests/cfg/seabios_hotplug_unplug.cfg
- qemu/tests/cfg/seabios_order_once.cfg
- qemu/tests/cfg/seabios_reboot_timeout.cfg
- qemu/tests/cfg/seabios_scsi_lun.cfg
- qemu/tests/cfg/seabios_strict.cfg
- qemu/tests/cfg/smbios.cfg
- qemu/tests/cfg/smbios_default_check.cfg
> seabios: add restriction for seabios-related cases

- generic/tests/boot.py
- generic/tests/boot_savevm.py
- generic/tests/clock_getres.py
- generic/tests/dd_test.py
- generic/tests/downgrade_qcow2_version.py
- generic/tests/ethtool.py
- generic/tests/fillup_disk.py
- generic/tests/guest_test.py
- generic/tests/hwclock.py
- generic/tests/invalid_para_mq.py
- generic/tests/iofuzz.py
- generic/tests/iometer_windows.py
- generic/tests/ioquit.py
- generic/tests/iozone_windows.py
- generic/tests/jumbo.py
- generic/tests/kdump.py
- generic/tests/ksm_services.py
- generic/tests/linux_stress.py
- generic/tests/lvm.py
- generic/tests/mac_change.py
- generic/tests/module_probe.py
- generic/tests/monotonic_time.py
- generic/tests/multi_queues_test.py
- generic/tests/multicast.py
Skipped:
* autotest_control.py
* autotest_distro_detect.py
* autotest_regression.py
> Update the logging namespace - generic (a-m)

- qemu/tests/uefi_boot_from_device.py
- qemu/tests/uefi_check_debugcon.py
- qemu/tests/uefi_check_log_info.py
- qemu/tests/uefi_check_secure_mor.py
- qemu/tests/uefi_pkg.py
- qemu/tests/uefi_secureboot.py
- qemu/tests/uefishell.py
- qemu/tests/unplug_block_during_io_reboot.py
- qemu/tests/unsafe_rebase_to_none_existing_backing_file.py
- qemu/tests/usb_basic_check.py
- qemu/tests/usb_common.py
- qemu/tests/usb_device_check.py
- qemu/tests/usb_device_check_negative.py
- qemu/tests/usb_host.py
- qemu/tests/usb_hotplug.py
- qemu/tests/usb_redir.py
- qemu/tests/usb_smartcard_sharing.py
- qemu/tests/usb_storage.py
> Update the logging namespace - qemu (u)

- qemu/tests/plug_cdrom.py
This commit expands the "wait until the device is detected in guest then mount" that was being followed in tests involving windows guests. That way, it fixes the some tests with linux guests were having.
ID: 2032983
> plug_cdrom: special device /dev/sr0 does not exist

- qemu/tests/cfg/hv_info_check.cfg
- qemu/tests/hv_info_check.py
Interface for querying supported HyperV Enlightenments
by the current host.
ID: 2028388
> hv_info_check: Add new test case

- qemu/tests/cfg/virtio_port_hotplug.cfg
- qemu/tests/virtio_serial_hotplug_max_chardevs.py
ID: 2048027
Change:
old msg: Duplicate ID 'port1' for device
new msg: Duplicate device ID 'port1'
> virtio_serial_hotplug_max_chardevs: fix error msg

- openvswitch/tests/load_module.py
- openvswitch/tests/ovs_basic.py
> Update the logging namespace - openvswitch

- qemu/tests/cfg/virtio_serial_file_transfer.cfg
> virtio_serial_file_transfer:disable intel-iommu on AMD

- qemu/tests/seabios_bin.py
> seabios.bin_file: add support for 9.0 machine types

- qemu/tests/cfg/numa_opts.cfg
Update numa max nodes test on aarch64
ID:2044696
> numa_opts:Update numa max nodes test on aarch64

- qemu/deps/block_device/guest_fio_on_disks.sh
- qemu/tests/block_check_memory_leak.py
- qemu/tests/cfg/block_check_memory_leak.cfg
> Add block device memory leak test

- qemu/tests/balloon_boot_in_pause.py
- qemu/tests/balloon_check.py
- qemu/tests/balloon_hotplug.py
- qemu/tests/balloon_memhp.py
- qemu/tests/balloon_minimum.py
- qemu/tests/balloon_sc_interrogate.py
- qemu/tests/balloon_service.py
- qemu/tests/balloon_stop_continue.py
- qemu/tests/balloon_stress.py
- qemu/tests/balloon_thp.py
- qemu/tests/bitmap_boundary_test.py
- qemu/tests/blk_commit.py
- qemu/tests/blk_stream.py
- qemu/tests/block_auto_detect_size_increased.py
- qemu/tests/block_check_event.py
- qemu/tests/block_check_fds.py
- qemu/tests/block_check_serial.py
- qemu/tests/block_commit_reboot.py
- qemu/tests/block_commit_stress.py
- qemu/tests/block_copy.py
- qemu/tests/blockdev_commit_backing_file.py
- qemu/tests/blockdev_commit_fio.py
- qemu/tests/blockdev_commit_general_operation.py
- qemu/tests/blockdev_commit_install.py
- qemu/tests/blockdev_commit_non_existed_node.py
- qemu/tests/blockdev_commit_specify_node.py
- qemu/tests/blockdev_commit_speed_limit.py
- qemu/tests/blockdev_full_backup_stress.py
> Update the logging namespace - qemu (b part 1)

- qemu/tests/cfg/trim_support_test.cfg
- qemu/tests/trim_support_test.py
> trim_support_test:disable luks format for trim feature

- generic/tests/netperf.py
- generic/tests/netstress_kill_guest.py
- generic/tests/nfs_corrupt.py
- generic/tests/nic_promisc.py
- generic/tests/nicdriver_unload.py
- generic/tests/ntpd.py
- generic/tests/ntttcp.py
- generic/tests/os_update.py
- generic/tests/ping.py
- generic/tests/pktgen_perf.py
- generic/tests/pxe_boot.py
- generic/tests/save_restore.py
- generic/tests/shutdown.py
- generic/tests/stress_boot.py
- generic/tests/trans_hugepage.py
- generic/tests/trans_hugepage_defrag.py
- generic/tests/trans_hugepage_memory_stress.py
- generic/tests/trans_hugepage_relocated.py
- generic/tests/trans_hugepage_swapping.py
- generic/tests/tsc.py
- generic/tests/unattended_install.py
- generic/tests/vlan.py
- generic/tests/whql_client_install.py
- generic/tests/whql_env_setup.py
- generic/tests/whql_hck_client_install.py
- generic/tests/whql_submission.py
> Update the logging namespace - generic (n-w)

- qemu/tests/virtio_fsd_check_info.py
> virtio_fs:remove one check point from test case

- qemu/tests/blockdev_snapshot_chains.py
- qemu/tests/blockdev_snapshot_merge.py
- qemu/tests/cfg/blockdev_snapshot.cfg
- qemu/tests/cfg/blockdev_snapshot_chains.cfg
- qemu/tests/cfg/blockdev_snapshot_data_file.cfg
- qemu/tests/cfg/blockdev_snapshot_guest_agent.cfg
- qemu/tests/cfg/blockdev_snapshot_install.cfg
- qemu/tests/cfg/blockdev_snapshot_merge.cfg
- qemu/tests/cfg/blockdev_snapshot_multi_disks.cfg
- qemu/tests/cfg/blockdev_snapshot_nonexist_target.cfg
- qemu/tests/cfg/blockdev_snapshot_readonly.cfg
- qemu/tests/cfg/blockdev_snapshot_reboot.cfg
- qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg
- qemu/tests/cfg/blockdev_snapshot_stress.cfg
Add iscsi_direct support for live snapshot
id:2052903
> live_snapshot:add iscsi_direct backend support

- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/cfg/hotplug_mem_negative.cfg
- qemu/tests/cfg/hotplug_mem_repeat.cfg
- qemu/tests/cfg/hotplug_mem_reserve.cfg
- qemu/tests/cfg/hotplug_mem_simple.cfg
- qemu/tests/cfg/hotplug_mem_stress_ng.cfg
Update threshold due to arm display mem less than other platforms
ID: 2057780
> hotplug_mem: Update threshold on arm

- qemu/tests/block_kill_reconnect_with_remote_storage.py
- qemu/tests/block_multifunction.py
- qemu/tests/block_performance_test.py
- qemu/tests/block_resize.py
- qemu/tests/block_resize_unplug.py
- qemu/tests/block_scsi_device.py
- qemu/tests/block_scsi_generic_inquiry.py
- qemu/tests/block_stream.py
- qemu/tests/block_stream_check_backingfile.py
- qemu/tests/block_stream_drop_backingfile.py
- qemu/tests/block_stream_negative.py
- qemu/tests/block_stream_simple.py
- qemu/tests/block_stream_stress.py
- qemu/tests/block_with_iommu.py
- qemu/tests/block_with_share_rw.py
- qemu/tests/block_with_write_threshold.py
- qemu/tests/boot_N_M_virtserialports.py
- qemu/tests/boot_cpu_model.py
- qemu/tests/boot_from_device.py
- qemu/tests/boot_from_remote.py
- qemu/tests/boot_order_check.py
- qemu/tests/boot_time.py
- qemu/tests/boot_with_different_vectors.py
- qemu/tests/boot_with_machine_types.py
- qemu/tests/boot_with_multiqueue.py
- qemu/tests/boot_without_vectors.py
- qemu/tests/bridge_mirror.py
- qemu/tests/bridge_qinq.py
- qemu/tests/bridge_vlan.py
> Update the logging namespace - qemu (b part 3)

- qemu/tests/cfg/blockdev_commit.cfg
- qemu/tests/cfg/blockdev_commit_auto_readonly.cfg
- qemu/tests/cfg/blockdev_commit_backing_file.cfg
- qemu/tests/cfg/blockdev_commit_cor.cfg
- qemu/tests/cfg/blockdev_commit_filter_node_name.cfg
- qemu/tests/cfg/blockdev_commit_fio.cfg
- qemu/tests/cfg/blockdev_commit_firewall.cfg
- qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_commit_general_operation.cfg
- qemu/tests/cfg/blockdev_commit_hotunplug.cfg
- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_commit_non_existed_node.cfg
- qemu/tests/cfg/blockdev_commit_powerdown.cfg
- qemu/tests/cfg/blockdev_commit_query_named_block_nodes.cfg
- qemu/tests/cfg/blockdev_commit_reboot.cfg
- qemu/tests/cfg/blockdev_commit_specify_node.cfg
- qemu/tests/cfg/blockdev_commit_speed_limit.cfg
- qemu/tests/cfg/blockdev_commit_standby.cfg
- qemu/tests/cfg/blockdev_commit_stop_cont.cfg
- qemu/tests/cfg/blockdev_commit_stress.cfg
- qemu/tests/cfg/blockdev_commit_throttle.cfg
- qemu/tests/cfg/blockdev_commit_to_nospace.cfg
- qemu/tests/cfg/blockdev_commit_top.cfg
- qemu/tests/cfg/blockdev_commit_with_ignore.cfg
- qemu/tests/cfg/blockdev_commit_with_ioerror.cfg
Add backend iscsi_direct support for live commit
id:2054030
> blockdev_commit: add iscsi_direct support for live commit

- qemu/tests/cfg/blockdev_full_mirror.cfg
- qemu/tests/cfg/blockdev_mirror_cancel_running_job.cfg
- qemu/tests/cfg/blockdev_mirror_install.cfg
- qemu/tests/cfg/blockdev_mirror_qemuio_ready_job.cfg
- qemu/tests/cfg/blockdev_mirror_with_ignore.cfg
Support iscsi_direct backend for block mirror
id:2054483
> blockdev_mirror: add iscsi_direct support

- provider/ansible.py
- provider/block_devices_plug.py
- provider/block_dirty_bitmap.py
- provider/blockdev_backup_base.py
- provider/blockdev_base.py
- provider/blockdev_commit_base.py
- provider/blockdev_snapshot_base.py
- provider/cdrom.py
- provider/cpu_utils.py
- provider/input_event_proxy.py
- provider/input_tests.py
- provider/job_utils.py
- provider/message_queuing.py
- provider/nbd_image_export.py
- provider/netperf_base.py
- provider/netperf_test.py
- provider/qemu_img_utils.py
- provider/slof.py
- provider/storage_benchmark.py
- provider/throttle_utils.py
- provider/virt_storage/storage_admin.py
- provider/virt_storage/utils/storage_util.py
- provider/win_driver_installer_test.py
- provider/win_driver_utils.py
- provider/win_dump_utils.py
- provider/win_hlk_suite.py
- provider/win_wora.py
Please note that the current approach could be considered as a
workaround to the issue below. In the future, we may replace it
with some interface provided by VT.
> Update the logging namespace - provider

- qemu/tests/blockdev_stream_cor_base.py
- qemu/tests/cfg/blockdev_stream.cfg
- qemu/tests/cfg/blockdev_stream_base_itself.cfg
- qemu/tests/cfg/blockdev_stream_cor.cfg
- qemu/tests/cfg/blockdev_stream_cor_base.cfg
- qemu/tests/cfg/blockdev_stream_dirty_bitmap.cfg
- qemu/tests/cfg/blockdev_stream_filter_nodename.cfg
- qemu/tests/cfg/blockdev_stream_powerdown.cfg
- qemu/tests/cfg/blockdev_stream_stress.cfg
- qemu/tests/cfg/blockdev_stream_to_invalid_node.cfg
- qemu/tests/cfg/blockdev_stream_with_ioerror.cfg
Add support iscsi_direct for block stream
id:2054026
> blockdev_stream: add backend iscsi_direct support for block stream

- qemu/tests/cfg/qemu_img_bitmap.cfg
- qemu/tests/qemu_img_bitmap.py
cover all the sub commands of bitmap
ID: 2018122
> qemu_img_bitmap: new case of qemu-img bitmap

- qemu/tests/cfg/cpu_model_negative.cfg
- qemu/tests/cpu_model_negative.py
> cpu_model_negative:fix error msg change

- qemu/tests/convert_image_from_raw.py
- qemu/tests/qemu_img_measure_convert_image.py
> Remove images after testing to avoid space occupation

- provider/block_dirty_bitmap.py
- qemu/tests/cfg/blockdev_full_backup.cfg
- qemu/tests/cfg/blockdev_full_backup_invalid_max_workers.cfg
- qemu/tests/cfg/blockdev_full_backup_invalid_sync_mode.cfg
- qemu/tests/cfg/blockdev_full_backup_multi_disks.cfg
- qemu/tests/cfg/blockdev_full_backup_nonexist_target.cfg
- qemu/tests/cfg/blockdev_full_backup_with_bitmap.cfg
- qemu/tests/cfg/blockdev_full_backup_x_perf.cfg
- qemu/tests/cfg/blockdev_inc_backup_always.cfg
- qemu/tests/cfg/blockdev_inc_backup_bitmap_mode_test.cfg
- qemu/tests/cfg/blockdev_inc_backup_bitmap_size.cfg
- qemu/tests/cfg/blockdev_inc_backup_cluster_test.cfg
- qemu/tests/cfg/blockdev_inc_backup_merge_to_nonexist_bitmap.cfg
- qemu/tests/cfg/blockdev_inc_backup_merge_with_nonexist_bitmap.cfg
- qemu/tests/cfg/blockdev_inc_backup_never.cfg
- qemu/tests/cfg/blockdev_inc_backup_no_bitmap.cfg
- qemu/tests/cfg/blockdev_inc_backup_sync_bitmap_nobitmap.cfg
- qemu/tests/cfg/blockdev_inc_backup_test.cfg
- qemu/tests/cfg/blockdev_inc_backup_with_complete_mode.cfg
- qemu/tests/cfg/blockdev_inc_backup_with_ignore.cfg
- qemu/tests/cfg/blockdev_inc_backup_without_bitmapmode.cfg
- qemu/tests/cfg/differential_backup.cfg
- qemu/tests/cfg/live_backup_add_bitmap.cfg
- qemu/tests/cfg/qemu_img_convert_with_inconsistent_bitmap.cfg
Add backend iscsi_direct support for incremental live backup
id:2054963
> incremental_live_backup:add iscsi_direct support

- qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
> cpu_device_hotplug_maximum:limit windows guests

- qemu/deps/block_device/speed.sh
- qemu/tests/block_boot_under_low_speed.py
- qemu/tests/cfg/block_boot_under_low_speed.cfg
> Add boot under low speed case

- qemu/tests/cfg/hv_avic.cfg
- qemu/tests/hv_avic.py
Check corresponding CPUID entries with hv-avic flag.
ID: 2051842
> hv_avic: Add new test case

- generic/tests/trans_hugepage_memory_stress.py
trans_hugepage_memory_stress:fix Invalid argument
ID:2061631
> trans_hugepage_memory_stress:fix Invalid argument

- qemu/tests/cfg/blockdev_full_mirror.cfg
- qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_io.cfg
- qemu/tests/cfg/blockdev_mirror_complete_running_job.cfg
- qemu/tests/cfg/blockdev_mirror_error.cfg
- qemu/tests/cfg/blockdev_mirror_filternode.cfg
- qemu/tests/cfg/blockdev_mirror_firewall.cfg
- qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_mirror_hotunplug.cfg
- qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg
- qemu/tests/cfg/blockdev_mirror_readonly.cfg
- qemu/tests/cfg/blockdev_mirror_ready_vm_down.cfg
- qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg
- qemu/tests/cfg/blockdev_mirror_simple.cfg
- qemu/tests/cfg/blockdev_mirror_speed.cfg
- qemu/tests/cfg/blockdev_mirror_sync_none.cfg
- qemu/tests/cfg/blockdev_mirror_sync_top.cfg
- qemu/tests/cfg/blockdev_mirror_to_rbd.cfg
- qemu/tests/cfg/blockdev_mirror_with_ignore.cfg
Add ceph backend for block mirror
id:2046047
> blockdev_mirror: support ceph backend

- qemu/tests/cfg/balloon_memhp.cfg
- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/cfg/migration_with_numa.cfg
- qemu/tests/cfg/numa_memdev_options.cfg
Explicit CPU-NUMA association workaround on arm
ID: 2060258
> numa:explicit CPU-NUMA association workaround on arm

- qemu/tests/cfg/blockdev_stream.cfg
- qemu/tests/cfg/blockdev_stream_base_itself.cfg
- qemu/tests/cfg/blockdev_stream_cor.cfg
- qemu/tests/cfg/blockdev_stream_cor_base.cfg
- qemu/tests/cfg/blockdev_stream_dirty_bitmap.cfg
- qemu/tests/cfg/blockdev_stream_filter_nodename.cfg
- qemu/tests/cfg/blockdev_stream_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_stream_general.cfg
- qemu/tests/cfg/blockdev_stream_hotunplug.cfg
- qemu/tests/cfg/blockdev_stream_multiple_blocks.cfg
- qemu/tests/cfg/blockdev_stream_on_error_ignore.cfg
- qemu/tests/cfg/blockdev_stream_powerdown.cfg
- qemu/tests/cfg/blockdev_stream_speed.cfg
Add backend ceph support for block stream
id:2046003
> blockdev_stream: support backend ceph

- qemu/tests/cfg/blockdev_commit.cfg
- qemu/tests/cfg/blockdev_commit_backing_file.cfg
- qemu/tests/cfg/blockdev_commit_cor.cfg
- qemu/tests/cfg/blockdev_commit_filter_node_name.cfg
- qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_commit_general_operation.cfg
- qemu/tests/cfg/blockdev_commit_hotunplug.cfg
- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_commit_non_existed_node.cfg
- qemu/tests/cfg/blockdev_commit_powerdown.cfg
- qemu/tests/cfg/blockdev_commit_query_named_block_nodes.cfg
- qemu/tests/cfg/blockdev_commit_specify_node.cfg
- qemu/tests/cfg/blockdev_commit_speed_limit.cfg
- qemu/tests/cfg/blockdev_commit_throttle.cfg
- qemu/tests/cfg/blockdev_commit_top.cfg
- qemu/tests/cfg/blockdev_commit_with_ioerror.cfg
Add backend ceph support for live commit
id:2046004
> blockdev_commit: add ceph support

- qemu/tests/block_resize.py
block_resize: create the mount point before mount.
ID: 1994450  
> block_resize: create the mount point before mount.

- qemu/tests/cfg/hv_enforce_cpuid_smoke.cfg
- qemu/tests/hv_enforce_cpuid_smoke.py
hv_enforce_cpuid_smoke: add new testcase.
ID: 2057341
> hv_enforce_cpuid_smoke: add new testcase.

- qemu/tests/cfg/hv_enforce_cpuid_msr_check.cfg
- qemu/tests/hv_enforce_cpuid_msr_check.py
hv_enforce_cpuid_msr_check: add new testcase
ID: 2051845
> hv_enforce_cpuid_msr_check: add new testcase

- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
Make folder test to a single case to make it more flexible.
ID: 2013071
> virtio_fs: separate folder test to a single one

- qemu/tests/cfg/check_basepage_size.cfg
- qemu/tests/check_basepage_size.py
Check base page size on aarch64
ID: 2065528
> check_basepage_size: Check base page size on aarch64

- qemu/tests/cfg/virtio_fs_share_data.cfg
> virtio_fs:remove pjdfstest test cases on power

- qemu/tests/block_iscsi_format_large_size_disk.py
- qemu/tests/cfg/block_iscsi_format_large_size_disk.cfg
> Add case format large size disk based on pass-through block device

- qemu/tests/block_auto_detect_size_increased.py
block_auto_detect_size_increased: support the 'luks' image format.
ID: 1993837
> block_auto_detect_size_increased: support the 'luks' image format.

- qemu/tests/cfg/vdi_image_create.cfg
- qemu/tests/vdi_image_create.py
1. Create a image with vdi format
ID: 2064158
> vdi_image_create: new case of vdi_image_create

- qemu/tests/blockdev_snapshot_chains.py
- qemu/tests/blockdev_snapshot_merge.py
- qemu/tests/blockdev_snapshot_multi_disks.py
- qemu/tests/cfg/blockdev_snapshot.cfg
- qemu/tests/cfg/blockdev_snapshot_chains.cfg
- qemu/tests/cfg/blockdev_snapshot_data_file.cfg
- qemu/tests/cfg/blockdev_snapshot_guest_agent.cfg
- qemu/tests/cfg/blockdev_snapshot_install.cfg
- qemu/tests/cfg/blockdev_snapshot_merge.cfg
- qemu/tests/cfg/blockdev_snapshot_multi_disks.cfg
- qemu/tests/cfg/blockdev_snapshot_nonexist_target.cfg
- qemu/tests/cfg/blockdev_snapshot_readonly.cfg
- qemu/tests/cfg/blockdev_snapshot_reboot.cfg
- qemu/tests/cfg/blockdev_snapshot_stop_cont.cfg
- qemu/tests/cfg/blockdev_snapshot_stress.cfg
Add backend:nbd support for live snapshot
id:2066584
> blockdev_snapshot: add nbd support for live snapshot

- qemu/tests/cfg/blockdev_full_mirror.cfg
- qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_io.cfg
- qemu/tests/cfg/blockdev_mirror_cancel_running_job.cfg
- qemu/tests/cfg/blockdev_mirror_complete_running_job.cfg
- qemu/tests/cfg/blockdev_mirror_error.cfg
- qemu/tests/cfg/blockdev_mirror_filternode.cfg
- qemu/tests/cfg/blockdev_mirror_firewall.cfg
- qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_mirror_hotunplug.cfg
- qemu/tests/cfg/blockdev_mirror_install.cfg
- qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg
- qemu/tests/cfg/blockdev_mirror_readonly.cfg
- qemu/tests/cfg/blockdev_mirror_ready_vm_down.cfg
- qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg
- qemu/tests/cfg/blockdev_mirror_simple.cfg
- qemu/tests/cfg/blockdev_mirror_speed.cfg
- qemu/tests/cfg/blockdev_mirror_sync_none.cfg
- qemu/tests/cfg/blockdev_mirror_sync_top.cfg
- qemu/tests/cfg/blockdev_mirror_with_ignore.cfg
Add backend:nbd support for block mirror
id:2068982
> blockdev_mirror:add nbd support for block mirror

- qemu/tests/cfg/blockdev_stream.cfg
- qemu/tests/cfg/blockdev_stream_base_itself.cfg
- qemu/tests/cfg/blockdev_stream_cor.cfg
- qemu/tests/cfg/blockdev_stream_cor_base.cfg
- qemu/tests/cfg/blockdev_stream_dirty_bitmap.cfg
- qemu/tests/cfg/blockdev_stream_filter_nodename.cfg
- qemu/tests/cfg/blockdev_stream_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_stream_general.cfg
- qemu/tests/cfg/blockdev_stream_hotunplug.cfg
- qemu/tests/cfg/blockdev_stream_install.cfg
- qemu/tests/cfg/blockdev_stream_multiple_blocks.cfg
- qemu/tests/cfg/blockdev_stream_on_error_ignore.cfg
- qemu/tests/cfg/blockdev_stream_powerdown.cfg
- qemu/tests/cfg/blockdev_stream_speed.cfg
- qemu/tests/cfg/blockdev_stream_subchain.cfg
- qemu/tests/cfg/blockdev_stream_to_invalid_node.cfg
Backend:nbd support for block stream
id:2068003
> blockdev_stream:add nbd support for block stream

- qemu/tests/cfg/vdi_image_convert.cfg
- qemu/tests/vdi_image_convert.py
1. Convert images between raw and vdi
ID: 2072406
> vdi_image_convert: new case of vdi_image_convert

- provider/job_utils.py
- qemu/tests/blockdev_commit_firewall.py
- qemu/tests/cfg/blockdev_commit_firewall.cfg
Add arguements "speed" for commit job to make sure
that job in running status before/after iptables
set
id:2073358
> blockdev_commit_firewall: add speed for commit job

- qemu/tests/cfg/device_option_check.cfg
Add cd image for aarch64
ID:2073918
> device_option_check:add cd image for aarch64

- qemu/tests/cfg/throttle_multi_guests_parameter_test.cfg
Update io-throttling configuration on aarch64
ID:2072870
> io-throttling:Update io-throttling configuration on aarch64

- qemu/tests/blockdev_commit.py
- qemu/tests/cfg/blockdev_commit.cfg
- qemu/tests/cfg/blockdev_commit_auto_readonly.cfg
- qemu/tests/cfg/blockdev_commit_backing_file.cfg
- qemu/tests/cfg/blockdev_commit_cor.cfg
- qemu/tests/cfg/blockdev_commit_filter_node_name.cfg
- qemu/tests/cfg/blockdev_commit_fio.cfg
- qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_commit_general_operation.cfg
- qemu/tests/cfg/blockdev_commit_hotunplug.cfg
- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_commit_non_existed_node.cfg
- qemu/tests/cfg/blockdev_commit_powerdown.cfg
- qemu/tests/cfg/blockdev_commit_query_named_block_nodes.cfg
- qemu/tests/cfg/blockdev_commit_reboot.cfg
- qemu/tests/cfg/blockdev_commit_specify_node.cfg
- qemu/tests/cfg/blockdev_commit_speed_limit.cfg
- qemu/tests/cfg/blockdev_commit_standby.cfg
- qemu/tests/cfg/blockdev_commit_stop_cont.cfg
- qemu/tests/cfg/blockdev_commit_stress.cfg
- qemu/tests/cfg/blockdev_commit_throttle.cfg
- qemu/tests/cfg/blockdev_commit_top.cfg
- qemu/tests/cfg/blockdev_commit_with_ioerror.cfg
Add backend:nbd support for live commit
id:2068346
> blockdev_commit: add nbd support for live commit

- qemu/tests/block_performance_test.py
- qemu/tests/cfg/block_performance_test.cfg
ID:2047662,1930998
Improve sampling and add filter q35 for case
> block_performance_test: improve sampling

- provider/throttle_utils.py
- qemu/tests/throttle_operation_test.py
> throttle_operation_test:change warn message to info

- qemu/tests/cfg/passthrough_fc_with_lun_device.cfg
- qemu/tests/passthrough_fc_with_lun_device.py
1.Fix issue if host have no device included in multipath
2.Increase partition size
BZ:2070446,2070443
> passthrough_fc_with_lun_device:fix no children issue and improve test

- qemu/tests/cfg/virtio_fs_hotplug.cfg
- qemu/tests/cfg/virtio_fs_multi_vms.cfg
- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
- qemu/tests/virtio_fs_hotplug.py
- qemu/tests/virtio_fs_multi_vms.py
- qemu/tests/virtio_fs_set_capability.py
- qemu/tests/virtio_fs_share_data.py
Need to config virtiofs debug log in register instead.
ID: 2056741
> virtio_fs: enable virtiofs debug log in windows vm

- generic/tests/lvm.py
ID:2069578
Ensure guest lvm available before remove it.
> lvm_clean:fix lvm inexistent issue

- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
- qemu/tests/virtio_fs_share_data.py
virtio_fs_share_data_multi_backend.cfg: add new testcase.
ID: 2035201
> virtio_fs_share_data_multi_backend.cfg: add new testcase

- generic/tests/cfg/jumbo.cfg
- generic/tests/jumbo.py
1.Add min mtu value for test
ID:1571616
> jumbo: Add min mtu value for test

- qemu/tests/cfg/qemu_guest_agent.cfg
Added Reboot and Halt patterns for s390x. 
ID: 2073295
Signed-off-by: Bogdan Marcynkov bmarcynk@redhat.com
> qemu_guest_agent: Add reboot/halt support - s390x

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
> virtio_fs: add iozone test on shared directory

- qemu/tests/cfg/throttle_block_set_io_throttle.cfg
- qemu/tests/throttle_block_set_io_throttle.py
> Add new case throttle_block_set_io_throttle

- qemu/tests/cfg/dump_guest_core.cfg
- qemu/tests/dump_guest_core.py
> dump_guest_core:update gdb command based on gdb usage

- qemu/tests/virtio_fs_share_data.py
> virtio_fs: extend timeout when creating 5G file on host

- qemu/tests/cfg/x86_cpu_model.cfg
ID: 2083046
Only boot to check model basically
> x86_cpu_model:add new model 'Icelake-Server-v6'

- provider/job_utils.py
- qemu/tests/blockdev_mirror_speed.py
- qemu/tests/cfg/blockdev_mirror_speed.cfg
Skip job running check for low speed
id:2078395
> blockdev_mirror_speed:skip job running check for low speed

- qemu/tests/blockdev_stream_speed.py
- qemu/tests/cfg/blockdev_stream_speed.cfg
Skip stream job running check for low speed set
id:2078381
> blockdev_stream_speed:skip job running check for low speed set

- qemu/tests/cfg/kvm_unit_test_nested.cfg
Sync kvm_unit_test test parameters for nested test with upstream 
ID: 2087018
> Update kvm_unit_test_nested test parameters

- qemu/tests/cfg/nvdimm.cfg
> nvdimm:add dependent package for test case nvdimm_nvml

- qemu/tests/bridge_vlan.py
- qemu/tests/memory_leak_after_nichotplug.py
- qemu/tests/msi_change_flag.py
- qemu/tests/nic_teaming.py
1.Change session mode to resolve dirty output due to serial session
ID:2087909
> Change session mode to resolve dirty output due to serial session

- generic/tests/vlan.py
1. Add a function to get a free port on the dst guest
ID:2078435
> vlan: Add a function to get a free port

- qemu/tests/cfg/timedrift_check_clock_offset.cfg
> disable the unsupported ovmf for internal snapshot

- qemu/tests/cfg/x86_cpu_flags.cfg
- qemu/tests/x86_cpu_flag_disable.py
ID: 2065031
Check the disable function with random flag
> x86_cpu_flags: update script "flag_disable"

- qemu/tests/cfg/virtio_fs_share_data.cfg
> virtio_fs: enable packed for vhost-user-fs-pci device

- qemu/tests/virtio_fs_hotplug.py
> virtio_fs_hotplug: 'session' needs to be re-obtained after vm reboot

- qemu/tests/cfg/slof_hugepage.cfg
- qemu/tests/slof_hugepage.py
> SLOF:update wrong parameters for hotplug test case on ppc

- qemu/tests/cfg/cpu_device_hotplug_during_boot.cfg
- qemu/tests/cfg/cpu_device_hotplug_maximum.cfg
- qemu/tests/cfg/cpu_device_hotplug_time_jump.cfg
- qemu/tests/cfg/cpu_device_hotpluggable.cfg
- qemu/tests/cfg/invalid_cpu_device_hotplug.cfg
> cpu_hotplug: limit host and qemu version

- qemu/tests/cfg/multi_disk_wild_hotplug.cfg
The more loops, the greater the chance of finding a problem.
ID:2090962
> multi_disk_wild_hotplug:increase loop number

- qemu/tests/cfg/fwcfg.cfg
- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/cfg/virtio_driver_sign_check.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
> fwcfg: exclude some Windows from the test matrix

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
> virtio_fs: add git init test on shared dir

- qemu/tests/transfer_file_over_ipv6.py
> transfer_file_over_ipv6:cancel the test if remote ip is None

- generic/tests/boot.py
- qemu/tests/cfg/multi_nics_reboot.cfg
boot.py: add nic adaptability for each platform
BZ: 2032981
> boot.py: add nic adaptability for each platform

- qemu/tests/cfg/virtio_fs_set_capability.cfg
> virtio_fs: use "-o xattrmap" without "-o xattr"

- generic/tests/ioquit.py
> ioquit: Fix failed checking dd process due to sleep too long

- qemu/tests/cfg/cpu_model_inter_generation.cfg
ID: 2048049
Choose cpu model accoding to CPU_TYPES_RE and CPU_TYPES.
> cpu_model_inter_generation: change auto_cpu_policy

- qemu/tests/cpu_topology_test.py
> cpu_topology_test: fix wrong cpu topology

- qemu/tests/cfg/netkvm_protocol_binding.cfg
- qemu/tests/netkvm_protocol_binding.py
> netkvm_protocol_binding:workaround for some issues

- qemu/tests/cfg/blockdev_stream_forbidden_actions.cfg
- qemu/tests/cfg/blockdev_stream_general.cfg
- qemu/tests/cfg/blockdev_stream_hotunplug.cfg
- qemu/tests/cfg/blockdev_stream_install.cfg
- qemu/tests/cfg/blockdev_stream_multiple_blocks.cfg
- qemu/tests/cfg/blockdev_stream_no_backing.cfg
- qemu/tests/cfg/blockdev_stream_no_space.cfg
- qemu/tests/cfg/blockdev_stream_none_existed_overlay.cfg
- qemu/tests/cfg/blockdev_stream_on_error_ignore.cfg
- qemu/tests/cfg/blockdev_stream_speed.cfg
- qemu/tests/cfg/blockdev_stream_stress.cfg
- qemu/tests/cfg/blockdev_stream_subchain.cfg
- qemu/tests/cfg/blockdev_stream_vm_reboot.cfg
- qemu/tests/cfg/blockdev_stream_vm_stop_cont.cfg
Remove backend limitations on cases, exclude cases that
based on specific backend
id:2097601
> blockdev_stream: remove backend limitations on cases

- qemu/tests/cfg/fio_perf.cfg
- qemu/tests/fio_perf.py
> turn off driver verifier for windows block perf test

- qemu/tests/cfg/hpt.cfg
- qemu/tests/hpt_miscellaneous.py
> HPT:update parameter for hpt mem_hotplug test case on ppc

- qemu/tests/cfg/interrupt_check.cfg
Interrupt: add s390x specific pattern to check times of interrupt
ID: 2099610
>  Add interrupt supported on s390x

- qemu/tests/cfg/win_irq_check.cfg
Remove 'IRQ' cases for all drivers as no real value.
ID: 2095144
> win_irq_check: Remove 'IRQ' cases as no real value

- generic/tests/cfg/kdump.cfg
> kdump:adjust crashkernel size for test case on ppc64le

- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
- qemu/tests/single_driver_install.py
> single_driver_install: workaround for install driver without signture

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
1. change the previous method that judge whether the resouce leak
happen, the new logic is to collect the trend of value change for
further analysis.
2. hot fix a minor issue.
ID: 2056330
Signed-off-by: 6-dehan <demeng@redhat.com>
> qemu_guest_agent.py: Optimize the resource leak case

- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/single_driver_install.py
> single_driver_install: delete the original drivers

- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/virtio_win_installer_version_check.py
Check installer version with rpm and virtio-win ISO.
ID: 2100361
> virtio_win_installer: product version check of installer

- qemu/tests/ksm_overcommit.py
> ksm:update the memory size of the guest since it should be multiple of 256M on ppc

- qemu/tests/cfg/balloon_memhp.cfg
- qemu/tests/cfg/hotplug_mem.cfg
- qemu/tests/cfg/migration_with_numa.cfg
- qemu/tests/cfg/numa_memdev_options.cfg
Corrected CPU-NUMA association version restrictions on arm
ID: 2101650
> numa:Corrected CPU-NUMA association version restrictions

- qemu/tests/cfg/kvm_stat.cfg
- qemu/tests/kvm_stat.py
> Add kvm_stat case

- qemu/tests/block_check_max_tranfer_length.py
- qemu/tests/cfg/block_check_max_tranfer_length.cfg
Check the maximum transfer length if combination of
seg_max and queue_depth.
ID: 2092261
> block_check_max_tranfer_length: Add new test case

- qemu/tests/cfg/x86_cpu_asyncpf.cfg
- qemu/tests/x86_cpu_asyncpf.py
ID: 2106669
A number of prints in guest dmesg log were
demoted before, after kernel rebase, these
prints logs are removed. So remove the step
checking such log inside guest.
> x86_cpu_asyncpf:update test steps

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
increase the memory on writeback-cache mode
ID: 2108477
> virtio_fs: increase the memory on writeback-cache mode

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Add a new case to repeate stop/start virtiofs service for windows guest.
ID: 2092226
> virtio_fs: stop/start virtiofs service for windows guest

- qemu/tests/cfg/qemu_img_check_data_integrity_with_lazy_refcounts.cfg
- qemu/tests/qemu_img_check_data_integrity_with_lazy_refcounts.py
> qemu_disk_img: new case for data integrity check with cache=writethrough & lazy_refcounts=on

- qemu/tests/cfg/remote_image_snapshot.cfg
> add windows support for case remote_image_snapshot

- qemu/tests/cgroup.py
- qemu/tests/fullscreen_setup.py
- qemu/tests/qemu_nobody.py
- qemu/tests/rv_audio.py
- qemu/tests/rv_fullscreen.py
- qemu/tests/rv_logging.py
- qemu/tests/smartcard_setup.py
inspekt enables a new pylint style check, so some issues are reported,
and it causes the gh actions check to fail.
ID: 2114624
> Fix some style issues in python files

- qemu/tests/timerdevice_clock_drift_with_ntp.py
> update the threshold to 30 for clock freq offset test

- qemu/tests/cfg/qemu_img_convert_from_vdi.cfg
- qemu/tests/qemu_img_convert_from_vdi.py
1. Convert from vdi os image
2. Boot up from the target image
ID: 2112262
> qemu_img_convert_from_vdi: new case

- qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
- qemu/tests/cfg/multi_disk_random_hotplug.cfg
- qemu/tests/cfg/throttle_operation_test.cfg
It need to apply enough pcie_extra_root_port for the
hotplug operation under arm64.
ID:2117145
> multi_disk_random_hotplug:fix no free root port issue

- qemu/tests/blockdev_stream_speed.py
Remove dup code for speed check
id:2113796
>  blockdev_stream_speed:remove the dup code

- qemu/tests/cfg/migrate.cfg
Test migration compatibility with different CPU cluster
and Numa configurations.
ID:2096138
> migrate: Add CPU cluster and numa mixed test

- qemu/tests/cfg/numa_cpu.cfg
- qemu/tests/numa_cpu.py
Add support for aarch64
ID:2091858
> numa_cpu:Add support for aarch64

- qemu/tests/usb_redir.py
Update re pattern to get USB device info in host dmesg correctly
ID: 2118189
> usbredir_negative: update re pattern to get USB device info

- qemu/tests/timedrift.py
As https://bugs.python.org/issue30520 mentioned, Python < 3.7 has the
issue for picking the logger object, so here is a workaround to bypass
this issue.
ID: 2114619
> timedrift: Bypass the issue of pickle _thread.RLock with Python < 3.7

- qemu/tests/arm_cpu_test_clusters.py
- qemu/tests/cfg/arm_cpu_test_clusters.cfg
Check guest gets correct multiple vcpu clusters
ID:2093857
> arm_cpu_test_clusters:Check guest vcpu clusters

- qemu/tests/cfg/nested_vsock_con_sockets.cfg
- qemu/tests/cfg/nested_vsock_con_sockets_l1.cfg
- qemu/tests/nested_vsock_con_sockets.py
- qemu/tests/nested_vsock_con_sockets_l1.py
> Add vsock concatenate sockets test with nested vms

- qemu/tests/cfg/blockdev_snapshot_chains.cfg
Update snapshot chain length to 199
id:2121318
> blockdev_snapshot_chains: update snapshot num to 199

- qemu/tests/cfg/blockdev_full_backup.cfg
Set auto-finalize to true in manual_completed to cover libvirt scenario
id:2121351
> blockdev_full_backup:update auto-finalize to true in manual_completed

- provider/qsd.py
> Add QSD support

- qemu/tests/blockdev_commit_with_stop.py
- qemu/tests/cfg/blockdev_commit_with_stop.cfg
Commit with on-error:stop
id:2120241
>  blockdev_commit_with_stop:commit with on-error:stop

- qemu/tests/cfg/hotplug_mem.cfg
hotplug_mem: increase threshold value
ID: 2122569
> hotplug_mem: increase threshold value

- qemu/tests/cfg/block_multifunction.cfg
> block_multifunction:disable pcie-root-port device for ppc

- provider/win_driver_utils.py
- qemu/tests/cfg/fwcfg.cfg
- qemu/tests/cfg/fwcfg_enable.cfg
- qemu/tests/driver_in_use.py
- qemu/tests/fwcfg.py
Uninstall the driver and check if a memory leak occurs,
if no,re-install the driver.
ID:2113798
> Add a memory leak check to driver test.

- qemu/tests/blockdev_mirror_qemuio_target.py
- qemu/tests/cfg/blockdev_mirror_qemuio_target.cfg
qemu-io target image during mirror
id:2121264
> blockdev_mirror_qemuio_target:qemu-io target during mirror

- qemu/tests/virtio_fs_hotplug.py
virtio_fs_hotplug.py: keep the "session" variable up to date
ID: 2074459
> virtio_fs_hotplug.py: keep the "session" variable up to date

- qemu/tests/cfg/qsd_pidfile_check.cfg
- qemu/tests/qsd_pidfile_check.py
> Add QSD pidfile option test

- qemu/tests/cfg/pvpanic_event_check.cfg
- qemu/tests/pvpanic_event_check.py
Add a case to test crashloaded event when the VM crashes
ID:2120905
> Add a case to test crashloaded event when the VM crashes

- qemu/tests/block_multifunction.py
> block_multifunction:add time delay after boot

- provider/netperf.py
- qemu/tests/cfg/netkvm_in_use.cfg
- qemu/tests/netkvm_in_use.py
Currently,netkvm in use cases will run into some problems,
and the problem is hard to fix.So rewrite the code to fix the
problem.
ID:2024832
> netkvm_in_use:Rewrite netkvm in use cases

- qemu/tests/cfg/qsd_object_check.cfg
- qemu/tests/qsd_object_check.py
> Add QSD object option test

- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_installer_repair.py
- qemu/tests/win_virtio_driver_update_by_installer.py
Adjust data structure to fix the ill code.
ID: 2126711
> win_driver_install_by_installer: Optimize the code

- qemu/tests/cfg/nvdimm.cfg
- qemu/tests/nvdimm.py
> nvdimm:fix missed package for guest

- qemu/tests/cfg/migration_with_remote.cfg
> add windows support for migration_with_remote_storage

- qemu/tests/cfg/remote_block_hotplug.cfg
> add windows support for remote_block_hotplug

- qemu/tests/cfg/remote_block_resize.cfg
- qemu/tests/remote_block_resize.py
> add windows support for remote_block_resize

- qemu/tests/cfg/remote_image_convert.cfg
> add windows support for remote_image_convert

- qemu/tests/cfg/qemu_guest_agent.cfg
qga: add pattern to adapt qga command "halt" and "reboot" on s390x
ID: 2124750
> Add pattern to adapt qga on s390x

- qemu/tests/cfg/migrate.cfg
- qemu/tests/migration.py
- qemu/tests/migration_with_file_transfer.py
- qemu/tests/migration_with_netperf.py
1.Install ksmtuned package to support migrate test cases
ID:2126112
> migrate:Install ksmtuned package to support migrate test cases

- qemu/tests/cfg/fwcfg_enable.cfg
- qemu/tests/driver_in_use.py
Add an option "memory_leak_check" to enable or disable memory leak check step.
ID:2124807
> driver_in_use:add an option to fix the bz

- qemu/tests/blockdev_mirror_stress.py
- qemu/tests/cfg/blockdev_mirror_stress.cfg
Replace stress test by fio during mirror
id:2121670
> blockdev_mirror_stress:replace stress by fio

- qemu/tests/blockdev_commit_hotunplug.py
- qemu/tests/cfg/blockdev_commit_hotunplug.cfg
Update expected job status from running to running or ready
id:2127794
> blockdev_commit_hotunplug:update expected job status

- qemu/tests/cfg/timerdevice.cfg
> timerdevice: modify the pattern to match the correct process to kill 

- qemu/tests/block_multifunction.py
- qemu/tests/block_multifunction_scale.py
- qemu/tests/cfg/block_multifunction.cfg
Add block_multifunction test scene on arm
ID:2124148
> block_multifunction:Add this test scene on arm

- qemu/tests/cfg/rng_hotplug.cfg
- qemu/tests/cfg/rng_stress.cfg
- qemu/tests/rng_hotplug.py
- qemu/tests/rng_stress.py
> rng_driver: re-locate variable 'rng_driver' to add Windows guest support

- provider/in_place_upgrade_base.py
- qemu/tests/cfg/in_place_upgrade.cfg
- qemu/tests/in_place_upgrade.py
ID:2104728,2104731
Including no_rhsm and rhsm two test matrix
> In_place_upgrade:add in place upgrade test case in the vm for upgrade path from rhel8 to rhel9

- qemu/tests/cfg/qsd_export_vhub_check.cfg
- qemu/tests/qsd_export_vhub_check.py
> Add QSD export vhost-user-blk option test

- qemu/tests/cfg/virtio_fs_security_label.cfg
- qemu/tests/virtio_fs_share_data.py
Selinux-label option support for virtiofsd.
ID: 2102454
> virtio_fs: new case of selinux-label support

- qemu/tests/cfg/qsd_blockdev_check.cfg
- qemu/tests/qsd_blockdev_check.py
> Add QSD blockdev option testing

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_update_by_installer.py
win_virtio_driver_update_by_installer: add new testcase
ID: 2102455
> win_virtio_driver_update_by_installer: add new testcase

- qemu/tests/cfg/virt_firmware_basic_test.cfg
- qemu/tests/virt_firmware_basic_test.py
> add a new case virt_firmware_basic_test

- qemu/tests/cfg/in_place_upgrade_legacy.cfg
- qemu/tests/in_place_upgrade_legacy.py
ID:2106674, 2106676
Adding without rhsm and with rhsm test matrix
> In_place_upgrade: add in place upgrade test cases for RHEL7 to RHEL8

- qemu/tests/cfg/multi_nics_verify.cfg
Virtual_network: add nic adaptability for multi_nics_verify to avoid missing ip address
ID: 2129274
> Add nic adaptability for multi_nics_verify

- .github/workflows/ci.yml
- generic/tests/netperf.py
- generic/tests/syzkaller.py
- qemu/tests/in_place_upgrade_legacy.py
- requirements-ci.txt
- requirements-travis.txt
1. Rename requirements-travis.txt to requirements-ci.txt since we switch
to GitHub actions now.
2. Upgrade some pip packages to sync style/lint check update.
ID: 2135571
> gh actions: CI check improvement

- qemu/tests/cfg/nested_system_reset.cfg
- qemu/tests/nested_system_reset.py
> Add system_reset test in nested environment

- provider/win_driver_installer_test.py
- qemu/tests/cfg/driver_load_stress.cfg
- qemu/tests/cfg/virtio_fs_hotplug.cfg
- qemu/tests/cfg/virtio_fs_multi_vms.cfg
- qemu/tests/cfg/virtio_fs_set_capability.cfg
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
To make it easy to maintain, change the winfsp version to a stable one.
ID: 2136715
> virtio_fs: update winfsp version to a default one

- qemu/tests/cfg/nmi_bsod_catch.cfg
- qemu/tests/nmi_bsod_catch.py
Adjust the case step for dump file check, replace with windebug check.
ID: 2118634
> Add dump check via windbg for the case nmi_bsod_catch

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_update_by_installer.py
win_virtio_driver_update_by_installer: add new test case about balloon
ID: 2081921
Signed-off-by: Houqi (Nick) Zuo [hzuo@redhat.com](mailto:hzuo@redhat.com)
> win_virtio_driver_update_by_installer: add new test case about balloon

- provider/qsd.py
- qemu/tests/cfg/qsd_live_snapshot.cfg
- qemu/tests/qsd_live_snapshot.py
Do live snapshot under qsd
id:2131201
> qsd_live_snapshot:do live snapshot under qsd

- qemu/tests/cfg/qsd_block_commit.cfg
- qemu/tests/qsd_block_commit.py
Do commit under qsd
id:2136070
>  qsd_block_commit:do commit under qsd

- qemu/tests/cfg/qsd_block_stream.cfg
- qemu/tests/qsd_block_stream.py
Do stream under qsd
id:2133675
> qsd_block_stream:do stream under qsd

- qemu/tests/blockdev_inc_backup_test.py
- qemu/tests/cfg/qsd_backup_push.cfg
- qemu/tests/qsd_backup_push.py
Do incremental live backup test under qsd.
id:2137184
> qsd_backup_push:incremental backup under qsd

- qemu/tests/cfg/qsd_backup_pull.cfg
- qemu/tests/qsd_backup_pull.py
Do incremental backup(pull mode) under qsd.
id:2139304
> qsd_backup_pull:do pull incremental backup under qsd

- qemu/tests/cfg/qsd_block_mirror.cfg
- qemu/tests/qsd_block_mirror.py
Do block mirror under qsd
id:2138704
> qsd_block_mirror: do block mirror under qsd

- qemu/tests/cfg/win_irq_check.cfg
- qemu/tests/win_irq_check.py
Refer to the developer advice:
reduce some steps and re-tidied as a new case here.
id: 2096487
> Add new case vectors_check under win_irq_check

- qemu/tests/cfg/nested_block_resize.cfg
- qemu/tests/cfg/nested_block_resize_l1.cfg
> Fix nested_block_resize test case boot order issue

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_installer_repair.py
- qemu/tests/win_virtio_driver_installer_uninstall.py
- qemu/tests/win_virtio_driver_update_by_installer.py
Remove qemufwcfg related setting and replace it with fwcfg.
ID:2141877
> installer:remove qemufwcfg related setting

- qemu/tests/cfg/win_virtio_driver_install_from_update.cfg
> win_virtio_driver_install_from_update:add fwcfg test

- qemu/tests/cfg/virtio_fs_winfsp_test.cfg
- qemu/tests/virtio_fs_share_data.py
Add new case of winfsp-tests on shred directory for windows guest.
ID: 2130452
> virtio_fs: new case of winfsp-tests suit

- qemu/tests/cfg/luks_image_over_qsd.cfg
- qemu/tests/luks_image_over_qsd.py
> luks_image_over_qsd: new case

- qemu/tests/cfg/memhp_threads.cfg
- qemu/tests/memhp_threads.py
Add check for prealloc-threads default
ID: 2140499
> memhp_threads: Add check for prealloc-threads default

- qemu/tests/block_multifunction.py
Add separate 'in' item for both condition
ID：2141378
> block_multifunction:fix syntax error for 'or'

- qemu/tests/physical_resources_check.py
Disk serial should exclude special characters.
ID:2144439
> physical_resources_check:fix serial generator

- qemu/tests/cfg/secure_img.cfg
- qemu/tests/secure_img.py
Genaral_operation: secure image and check
ID: 2144412
> Add secure_image test case on s390x

- qemu/tests/cfg/qsd_install.cfg
- qemu/tests/qsd_install.py
> Add QSD installation test

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
Add options for xfstest.
ID: 2150189
> virtio_fs: add xattr and no_killpriv_v2 to xfstest

- qemu/tests/cfg/qmp_command.cfg
> qmp_command:add 'query-stats' and 'query-stats-schema' commands

- qemu/tests/cfg/blockdev_commit_install.cfg
- qemu/tests/cfg/blockdev_mirror_install.cfg
- qemu/tests/cfg/blockdev_snapshot_install.cfg
- qemu/tests/cfg/blockdev_stream_install.cfg
Remove installation image after test
id:2155142
> blockdev_*_install:remove image after installation test

- qemu/tests/cfg/dump_guest_core.cfg
- qemu/tests/cfg/dump_guest_memory.cfg
ID:2155404
Signed-off-by: Ke MA <mama@redhat.com>
> Dump: update from '-device vmcoreinfo' to 'vmcoreinfo = yes' 

- qemu/tests/cfg/migrate_nic_with_iommu.cfg
Migrate nic with iommu_platform=on and different memory size
ID:2148847
> migrate_nic_with_iommu:migrate nic with iommu_platform=on

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
> Add pvpanic function test after install driver via installer

- qemu/tests/cfg/hotplug_unplug_nic_with_viommu.cfg
Hotplug/unplug nic with iommu_platform=on based on virtio iommu device
ID:2148348
> hotplug_unplug_nic_with_viommu:Hotplug/unplug nic based on viommu device

- qemu/tests/cfg/pvpanic_memory_leak.cfg
- qemu/tests/pvpanic_memory_leak.py
Adding memory leak checking
ID: 2149195
Signed-off-by: Ke MA <mama@redhat.com>
> Pvpanic: Memory Leak check

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
> Add netkvm function test after install driver via installer

- qemu/tests/cfg/qsd_hotplug_vubp.cfg
- qemu/tests/qsd_hotplug_vubp.py
> Add QSD hotplug vhost-user-blk-pci device testing

- qemu/tests/cfg/qsd_vubp_options.cfg
- qemu/tests/qsd_vubp_options.py
> Add QSD vhost-user-blk-pci device options test

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
check qemu-ga.service function after installing via
virtio-win-guest-installer.
ID: 2101738
> qemu_guest_agent: Add new case for installing qga via installer

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
Add driver vioser function test if the driver installed by installer.
ID: 2102925
> Add function test after install vioser by installer

- qemu/tests/cfg/in_place_upgrade.cfg
- qemu/tests/in_place_upgrade.py
ID:2159931
The script supports installing leapp tool from compose or upstream.
> IPU:for rhel 8 to rhel 9, add function of installing leapp tool from compose or upstream

- qemu/tests/cfg/in_place_upgrade_legacy.cfg
- qemu/tests/in_place_upgrade_legacy.py
ID:2161657
The script supports installing leapp tool from compose.
> IPU:for rhel7 to rhel8 upgrade path, add the installation of leapp from compose

- provider/sgx.py
- qemu/tests/cfg/sgx_basic.cfg
- qemu/tests/sgx_basic.py
Add sgx boot option and sgx check capability functions
ID: 2135665
> Add sgx basic test

- generic/tests/cfg/iozone_windows.cfg
- generic/tests/iozone_windows.py
- provider/win_driver_utils.py
- qemu/tests/cfg/block_hotplug_scsi_hba.cfg
- qemu/tests/cfg/block_resize_unplug.cfg
- qemu/tests/cfg/fio_windows.cfg
Add interface to enable/disable driver for windows.
ID:2149494
> win_driver_utils: Add interface to enable/disable driver for windows

- qemu/tests/cfg/fwcfg_enable.cfg
> fwcfg:add a memory leak check at the end of function test

- qemu/tests/save_restore_vm.py
Issue: https://github.com/autotest/tp-qemu/issues/3523
> save_restore_vm: update test with new vm.restore_to_file behavior

- provider/win_driver_installer_test.py
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
- qemu/tests/win_virtio_driver_install_by_installer.py
- qemu/tests/win_virtio_driver_installer_repair.py
win_virtio_driver_install_by_installer: add new test case
add new test cases to win_virtio_driver_install_by_installer.py and win_virtio_driver_installer_repair
id: 2143143, 2143454
> win_virtio_driver_install_by_installer: add new test case

- qemu/tests/cfg/x86_cpu_asyncpf.cfg
ID: 2169086
Script only support RHEL8.4 kernel or newer
> x86_cpu_asyncpf:Limit guests kernel

- provider/win_driver_installer_test.py
- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Now windows vm also supports multi fs sources, add functions to start multi fs in windows vm.
ID:  2160299
> virtio_fs: support multi_fs_sources in one windows vm

- qemu/tests/tpm_bind_luks.py
It seems that a problem in the previous version, it causes the luks FS
sometimes not to mount after reboot, so correct the mount options in
crypttab and fstab. We should use UUID instead of disk path in crypttab 
to avoid the disk letter changes, also relabel the mount point is a must
to avoid another failure.
ID: 2168025
> tpm_bind_luks: Update FS options written to crypttab and fstab

- qemu/tests/cfg/in_place_upgrade.cfg
- qemu/tests/cfg/in_place_upgrade_legacy.cfg
- qemu/tests/in_place_upgrade.py
- qemu/tests/in_place_upgrade_legacy.py
> Add rename function for images after doing in place upgrade

- qemu/tests/numa_stress.py
numa_stress: updates case to avoid out of memory
Updates the case to avoid the out of memory, caused by a bad assignment of the memory to be filled for every numa node. Now takes the the free memory for each node avoiding this previous frequent action.
ID: 2161563
> numa_stress: updates case to avoid out of memory

- qemu/tests/cfg/numa.cfg
> Update a parameter for numa stress test on ppc64le

- qemu/tests/cfg/sgx_multi_vms.cfg
- qemu/tests/sgx_multi_vms.py
> Add sgx multi vms boot test

- provider/win_driver_utils.py
- provider/win_dump_utils.py
- qemu/tests/cfg/fwcfg.cfg
- qemu/tests/cfg/fwcfg_enable.cfg
- qemu/tests/cfg/single_driver_install.cfg
- qemu/tests/cfg/virtio_driver_sign_check.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
ID:2172829
Signed-off-by: Leidong Wang leidwang@redhat.com
> fwcfg:enable fwcfg test for 32 bits windows guest

- qemu/tests/boot_from_virtiofs.py
- qemu/tests/cfg/boot_from_virtiofs.cfg
> boot_from_virtio_fs:add a script to test virtiofs

- qemu/tests/cfg/s390x_cpu_model.cfg
CPU: add supported feature paie on s390x for 7.2.0 and newer qemu versions
reference: https://gitlab.com/qemu-project/qemu/-/commit/1d41de5f0524b00a3e1ac0a5b66958466f4332fa
ID: 2168130
> Add new feature for CPU model on s390x

- qemu/tests/qemu_img_lock_reject_boot.py
Method `create` from `qemu_vm.py` tries to connect to QMP monitor right after initial cheking of QEMU process to be alive. This can bring timing issue as sometimes QEMU process dies slowly (observed in case of luks image) after this initial check when connections to QMP monitors are being established. As a result `MonitorConnectError` exception can be triggered instead of `VMCreateError` anticipated by `qemu_img_lock_reject_boot` test case. 
This PR changes the logic of test case, so all exceptions are caught and expected error messages are checked differently.
**Context**
- This PR replaces https://github.com/avocado-framework/avocado-vt/pull/3616 and solves the issue on tp-qemu level. 
- Please see relevant discussion here: https://github.com/avocado-framework/avocado-vt/pull/3616#discus …
> qemu_img_lock_reject_boot: check output without using exceptions

- qemu/tests/cfg/virtio_fs_share_data.cfg
ID: 2175095
Add winfsp on i386 machine.
> virtio_fs: fix Config WinFsp.Launcher failed issue

- qemu/tests/cfg/format_disk.cfg
- qemu/tests/format_disk.py
> Format_disk: modify dmesg command for rhel610 guest on ppc

- qemu/tests/watchdog.py
> watchdog:add vm_destory to watchdog in case it affects subsequent test

- qemu/tests/cfg/qemu_img_extent_size_hint.cfg
- qemu/tests/qemu_img_extent_size_hint.py
Check extent_size_hint in qemu-img info
id:2176783
> qemu_img_extent_size_hint:extent_size_hint check

- qemu/tests/cfg/virtio_fs_share_data.cfg
> virtio_fs: new case of test posix-acl with xfstest

- qemu/tests/multi_disk.py
The disks driver are not always same after booting. 
It needs to regain the disks driver after booting.
ID:2158316
> multi_disk:fix regain disk driver after booting

- provider/vdpa_sim_blk_utils.py
> Add VDPA block device simulator utils

- qemu/tests/cfg/sgx_cpu.cfg
- qemu/tests/sgx_cpu.py
ID: 2172405
Signed-off-by: Zixi Chen zixchen@redhat.com
> sgx_cpu: Add sgx cpu test

- generic/tests/cfg/boot_vm_in_hugepage.cfg
Add set specify huge page size test
ID: 2170742
> boot_vm_in_hugepage:add set specify hugepage test

- qemu/tests/cfg/guest_iommu_group.cfg
- qemu/tests/guest_iommu_group.py
ID: 2168053
Signed-off-by: Jin Liu jinl@redhat.com
> iommu: add iommu group test case

- qemu/tests/block_io_with_unaligned_offset.py
- qemu/tests/cfg/block_io_with_unaligned_offset.cfg
> Add qemu-io with unaligned offset testing

- qemu/tests/cfg/commit_with_bitmaps_nospace.cfg
- qemu/tests/commit_with_bitmaps_nospace.py
Commit with too many bitmaps
ID:2181171
> commit_with_bitmaps_nospace:commit multi-bitmaps

- qemu/tests/cfg/numa_opts.cfg
Enable with_maxmem test on ARM platform
ID: 2185514
> Enable with_maxmem test on ARM platform

- qemu/tests/cfg/timer_rtc_sync.cfg
- qemu/tests/timer_rtc_sync.py
> add case of RTC sync in 11 mins mode

- generic/tests/arm_kvm_unit_tests.py
- generic/tests/cfg/arm_kvm_unit_tests.cfg
Clone the kvm-unit-tests and run specific subtests, then check the test results.
ID: 2176735, 2176734
> arm_kvm_unit_tests: Run kvm-unit-tests subtests and check results

- provider/ansible.py
In case ansible is installed via pip before avocado based ansible tests are executed, some key dependecies don't have to be satisfied - the most important `sshpass`. These dependecies must be installed from repository, which also may be custom one, so it is important to use `distro_install` which handles it.
ID: 2150279
> ansible: ensure ansible dependencies like `sshpass` are installed

- qemu/tests/cfg/spapr_vty_multi_backends.cfg
ID:2187127
Signed-off-by: Miriam Deng <mdeng@redhat.com>
> Spapr: remove image_snapshot from the cfg

- qemu/tests/cfg/watchdog.cfg
> watchdog:Disable Hot-plug/hot-unplug i6300esb test case in q35

- qemu/tests/cfg/boot_from_virtiofs.cfg
> boot_from_virtiofs: support linux guest only

- qemu/tests/cfg/guest_iommu_group.cfg
ID: 2190069
Signed-off-by: Jin Liu [jinl@redhat.com](mailto:jinl@redhat.com)
> restrict intel_iommu with intel cpu

- qemu/tests/cfg/tpm_check_buffer_size.cfg
- qemu/tests/tpm_check_buffer_size.py
Add tpm_check_buffer_size test case
ID: 2189100
Signed-off-by: qcheng-redhat <qcheng@redhat.com>
> Add tpm_check_buffer_size test case

- qemu/tests/cfg/block_hotplug.cfg
> block_hotplug:change max_size case disk size to 100T

- qemu/tests/cfg/block_discard_write_same.cfg
Adding loop device detach operation
ID:2183001
> block_discard_write_same_resource:fix resource clean issue

- qemu/tests/timerdevice_boot.py
> changing to safe mode for serial session

- qemu/tests/cfg/fio_perf.cfg
- qemu/tests/fio_perf.py
ID: 2182290
1. decode the byte string to string.
2. add virtiofsd version to report
> fio-perf: add virtiofsd version to report

- qemu/tests/cfg/check_basepage_size.cfg
- qemu/tests/check_basepage_size.py
1. Update basic page size to dynamic checking method
2. Add mapping hugepage check
ID:2185726
> check_basepage_size:Add mapping hugepage check

- .ci/cfg-lint-check.py
- .ci/commits-check.sh
- .github/workflows/ci.yml
1. Update version of actions
2. Add script to check commits style
3. Add script to check cfg lint
4. Add cartesian parser check
5. Add PR title length check
ID: 2183458
> Improve the GH CI workflow

- qemu/tests/qemu_guest_agent.py
Add @error_context.context_aware to the top of function.
ID: 2203033
Signed-off-by: demeng <demeng@ovpn-12-16.pek2.redhat.com>
> qemu_guest_agent: Hot fix for check_get_diskstats

- qemu/tests/cfg/multi_disk_wild_hotplug.cfg
- qemu/tests/multi_disk_wild_hotplug.py
> Add case:repeatedly hotplug-unplg disks wildly without delay

- qemu/tests/cfg/fwcfg.cfg
- qemu/tests/fwcfg.py
> Fwcfg: reboot the vm after install windbg

- qemu/tests/cfg/power_hpt_mmu_test.cfg
ID:2202992
Signed-off-by: Min Deng <mdeng@redhat.com>
> HPT:disable some guests in HPT test on pp64le

- qemu/tests/qemu_guest_agent.py
1. disable 'quick format' when format storage.qcow2 inside VM
2. change the times of loop of creating fragment to match  test logic and strategy.
3. delete a checkpoint that query original BLOCK data after formatting disk.
ID: 2209261
> qemu_guest_gent: change test logic for case 'guest-fstrim'

- qemu/tests/uefi_pkg.py
Because explicitly set mode = split in firmware json description files from rhel9.3, for amdsev and inteltdx json files, the 'mode' is 'stateless', for other json files, if it has 'mode' element, its value is 'split'.
ID: 2209852
> check the 'mode' is 'split' except for amdsev and inteltdx json files

- qemu/tests/cfg/blockdev_stream_install.cfg
Correct lun_image1 value from 1 to 3
id:2210625
> blockdev_stream_install: correct lun_image1

- generic/tests/cfg/pktgen_perf.cfg
- generic/tests/pktgen_perf.py
Need to disabled all rules for performance test as it affect the
performance.
ID:2196164
> pktgen_perf: disable iptables rules

- deps/virtio_fs/virtio_fs_mmap.py
- qemu/tests/cfg/virtio_fs_write_same_space.cfg
- qemu/tests/virtio_fs_write_same_space.py
ID: 217803
New case of testing writing to the same addr on shared directoy.
> virtio_fs: writing to the same space on shared dir test

- qemu/tests/cfg/in_place_upgrade_legacy.cfg
ID:2209619
Signed-off-by: Min Deng <mdeng@redhat.com>
> IPU:Fix the issue of yum update by following known document

- qemu/tests/chardev_serial_login.py
ID: 2212249
Add one parameter to avoid irrelevant messages.
> Chardev: fix UnicodeDecodeError issue

- qemu/tests/mq_change_qnum.py
1.After to check the debug this problem is caused by the serial session
instead of a product problem, so replace serial_session to session.
ID:2213377
> Changed to session mode to resolve dirty output due to serial session

- qemu/tests/virtio_fs_share_data.py
ID: 2203065
Win11 guest has different error msg for git.
> virtio_fs: add error msg for git on Win11

- qemu/deps/softlockup/heartbeat_slu.py
- qemu/tests/cfg/softlockup.cfg
- qemu/tests/softlockup.py
> stress: Fix softlockup case issues

- provider/win_driver_utils.py
ID: 2217225
For some drivers, need to reboot system after
disable them, after that the session should
be set/return again.
> win_driver_utils: return session after system reboot

- qemu/tests/block_detect_zeroes.py
- qemu/tests/cfg/block_detect_zeroes.cfg
1. Add boot with detect-zeroes option case
2. Add hotplug with detect-zeroes option case
ID: 2214140,2216365,2217720
> Add blockdev detect-zeroes option test case

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
ID: 2212610
Allow running xfstest with virtiofsd writeback option.
> virtio_fs: support more options for xfstest

- qemu/tests/cfg/virtio_fs_sandbox.cfg
- qemu/tests/virtio_fs_sandbox.py
Start virtiofsd with common user and set sandbox=none, trying to write on the shared dir inside guest.
ID: 2173819
> virtio_fs: new test case to run virtiofsd unprivileged

- provider/in_place_upgrade_base.py
- qemu/tests/cfg/in_place_upgrade.cfg
- qemu/tests/cfg/in_place_upgrade_legacy.cfg
ID: 2186172 
Signed-off-by: Min Deng <mdeng@redhat.com>
> IPU: dynamically set rhel version if test is with rhsm

- qemu/tests/in_place_upgrade.py
> In_place_upgrade_8to9:remove get data step for rhel8torhel9 upgrade path

- generic/tests/monotonic_time.py
> monotonic_time: change to tsc_lfence from tsc

- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
ID: 2211373
For balloon check during installer test, threshold should be set.
> win_virtio_driver_installer: add threashold for balloon function

- qemu/tests/cfg/numa_opts.cfg
Update arm cpu numa allocation
ID:2229033
> numa_opts:Update arm cpu numa allocation

- qemu/tests/cfg/hugepage_reset.cfg
Add support for arm huge pages
ID: 1326
> hugepage_reset:Add support for arm huge pages

- qemu/tests/cfg/x2avic_test.cfg
- qemu/tests/x2avic_test.py
ID: 1305
AMD support one feature x2AVIC on Genoa.
> x86: Support x2AVIC on AMD Genoa

- qemu/tests/cfg/qemu_guest_agent.cfg
ID:2230771
Signed-off-by: Miriam Deng <mdeng@redhat.com>
> PPC:update some parameter for guest_agent test cases

- provider/win_dump_utils.py
dump file analysis log need time to generate, so add this logic to make sure we can check the full log.
ID: 2235229
> fwcfg: loop to check dump analysis log

- qemu/tests/block_resize.py
- qemu/tests/cfg/block_resize.cfg
Add defrag event check steps after do system disk shrink.
ID: 1200
> Add defrag event check steps after do system disk shrink

- qemu/tests/cfg/virtio_fs_memory_backend.cfg
ID: 2193087
1. add memfd backend.
2. test hugepage on all backend.
3. test numa on all backend.
> virtio_fs: restruct virtiofs memory backend test

- provider/dpdk_utils.py
- qemu/tests/cfg/vdpa_dpdk.cfg
- qemu/tests/vdpa_dpdk.py
> dpdk: add performance test using dpdk tool

- qemu/tests/cfg/virt_firmware_check_phys_bits.cfg
- qemu/tests/virt_firmware_check_phys_bits.py
> virt_firmware_check_phys_bits: Add a new case

- qemu/tests/cfg/sev_basic_config.cfg
- qemu/tests/sev_basic_config.py
> Add sev basic config test case

- qemu/tests/cdrom_block_size_check.py
> cdrom_test:change checking condition to change media

- qemu/tests/cfg/hv_flag_cpuid_check.cfg
- qemu/tests/hv_flag_cpuid_check.py
1. cpuid check with hv-tlbflush-ext flag
2. cpuid check with hv-tlbflush-direct flag
ID: 1106, 1107
Signed-off: Peixiu Hou phou@redhat.com
> Add 2 new cases for hyper-v flags

- qemu/tests/cfg/sev_dhcert_boot.cfg
- qemu/tests/sev_dhcert_boot.py
> Add sev dhcert boot case

- qemu/tests/cfg/virtio_fs_host_owner_win.cfg
- qemu/tests/virtio_fs_host_owner_win.py
Adding UID:GID host owner to virtiofs service,
and check the uid and gid from host side.
ID:  2218426
> virtio_fs: add UID:GID test for Windows vm

- qemu/tests/cfg/sev_hotplug_mem.cfg
- qemu/tests/sev_hotplug_mem.py
> SEV: Add sev memory hotplug/unplug case

- qemu/tests/cfg/in_place_upgrade.cfg
- qemu/tests/cfg/in_place_upgrade_legacy.cfg
- qemu/tests/in_place_upgrade.py
- qemu/tests/in_place_upgrade_legacy.py
ID：1389
Update installation command of leapp from compose.
> IPU: update the installation command of leapp tool

- qemu/tests/cfg/test_vdpa_control_virtqueue.cfg
- qemu/tests/test_vdpa_control_virtqueue.py
Create new test case to support test control virtqueue with vDPA device.
ID: 1307
> Test vDPA control virtqueue

- qemu/tests/cfg/hv_check_cpu_utilization.cfg
Change service disable methods from sc to reg
ID: 1131
> hv_check_cpu_utilization: Change service disable methods on Win10-32

- qemu/tests/block_vhost_vdpa_test.py
- qemu/tests/cfg/block_vhost_vdpa_test.cfg
Adding vhost-vdpa test
1. Adding multi disks case
2. Adding hotplug/unplug case
ID:1392
> add vhost vdpa test

- qemu/tests/block_boot_multi_disks.py
- qemu/tests/cfg/block_boot_multi_disks.cfg
> Add booting multi disks case

- qemu/tests/virtio_fs_share_data.py
Add a checkpoint that doing io test after reboot guest os.
ID: 1310
> virtio_fs: add IO test after rebooting guest os

- qemu/tests/block_hotplug_with_cpu_hotplug.py
- qemu/tests/cfg/block_hotplug_with_cpu_hotplug.cfg
Add new case about scenario: hotplug storage device after hotplug a cpu device.
Add new case about scenario: hotplug storage device after
hotplug a cpu device.
ID: 1385, 1532
Signed-off-by: Menghuan Li <menli@redhat.com>
> block_hotplug_with_cpu_hotplug: Add new case

- qemu/tests/cfg/guest_iommu_test.cfg
Check virtio device function with iommu when disable ats
ID:1542
> guest_iommu_test: add a new scenario when ats=off

- qemu/tests/block_resize.py
- qemu/tests/cfg/block_resize.cfg
1. Event filter enhancement retrieves events in the last 3 minutes
2. Support wild search
3. Wrap check_shrink_completion
ID:1487,1576,1574
> block_resize:enhance event handle

- qemu/tests/cfg/nic_hotplug.cfg
For the igb device add hotplug/unplug scenarios.
ID:1546
> nic_hotplug: Add a new nic model igb

- qemu/tests/cfg/hv_flag_cpuid_check.cfg
Add cpuid_pkg name for hv_flag_cpuid_check
ID: 1568
> hv_flag_cpuid_check: add cpuid_pkg name

- qemu/tests/block_vhost_vdpa_test.py
- qemu/tests/cfg/block_vhost_vdpa_test.cfg
1. Add discard option test
2. Add cache option test
ID:1745,1746
> block_vhost_vdpa_test:add new case

- qemu/tests/block_aio_io_uring.py
- qemu/tests/cfg/block_aio_io_uring.cfg
1. Add case boot disk with aio=io_uring
2. Add case hotplug disk with aio=io_uring
ID:1720
> Add block_aio_io_uring test case

- qemu/tests/cfg/virtio_fs_share_data.cfg
virtiofs doesn't support it.
ID: 1744
> virtio_fs: remove generic/263 from xfstest

- qemu/tests/cfg/virtio_fs_share_data.cfg
- qemu/tests/virtio_fs_share_data.py
Compare symbolic link information in the Windows host and guest to check if they are consistent.
ID: 1690
> virtio_fs: compare symbolic link info in host and Windows guest

- generic/tests/netperf.py
> netperf: Add vDPA support to netperf

- qemu/tests/cfg/driver_load_stress.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
As the fio function was changed in virtio_fs_share_data, driver related test also need to be updated.
ID: 1754
> win_virtio_driver: update fio parameters

- qemu/tests/cfg/virtio_fs_queue_size.cfg
IO test on shared dir in different queue_size situation.
ID: 1569
> virtio_fs: add queue_size test case

- qemu/tests/virtio_fs_group_permission_access.py
Update script to detete user before add it.
ID: 1769
> virtio_fs: need to delete user before add it

- qemu/tests/cfg/multi_disk_wild_hotplug.cfg
> multi_disk_wild_hotplug:disable pcie-root-port device for ppc

- qemu/tests/cfg/hv_avic.cfg
- qemu/tests/cfg/hv_flag_cpuid_check.cfg
- qemu/tests/hv_avic.py
- qemu/tests/hv_flag_cpuid_check.py
cpuid package is included in epel repo, so prepare epel repo for these cases.
1] hv_avic
2] hv_flag_cpuid_check
ID: 1765
> hyper-v enlightenment: Install epel repo on RHEL guest

- qemu/tests/cfg/multi_disk_random_hotplug.cfg
> multi_disk_random_hotplug:Update stg_image_num for ppc

- qemu/tests/secure_img.py
SE: updaing boot_img_cmd since we have new certification
ID: 1700
> Updating boot_img_cmd for secure image on s390x

- qemu/tests/cfg/timerdevice.cfg
- qemu/tests/timerdevice_boot.py
> Reduce the host load for timer device case

- qemu/tests/cfg/virtio_fs_share_data.cfg
Remove some generic test cases from test suite of xfstest
ID: 1584
> PPC:disable some xfstests test cases from test suite

- qemu/tests/block_check_memory_leak.py
> Cancel memory leak test for ppc kvm interrupt type guest

- qemu/tests/qemu_img_convert_with_rate_limit.py
- qemu/tests/qemu_img_convert_with_target_is_zero.py
> qemu_img_convert:sync host data after convert

- qemu/tests/block_vhost_vdpa_test.py
- qemu/tests/cfg/block_vhost_vdpa_test.cfg
> Add  vhost-vdpa read-only and detect_zeroes options test

- qemu/tests/interrupt_check.py
> interrupt_check:add timeout for dd writing command

- qemu/tests/sve_invalid.py
1. Should use `len(sve_lengths)` to compare the length
2. Correct the parameter type in cpu.cpu_has_flags
ID: 1987
> fix(sve_invalid): minor fix for sve check

- provider/cpu_utils.py
- qemu/tests/cfg/cpu_topology_test.cfg
- qemu/tests/cpu_topology_test.py
CPU: updated sockets info, and enable exsisted test case on s390x
ID: 1925
> Enable cpu_topology on s390x

- qemu/tests/cfg/virtio_fs_supp_group_transfer.cfg
limit guest version for the case is supported sync rhel9.3
ID: 2020
> virtio_fs_supp_group_transfer: limit guest version

- qemu/tests/block_hotplug.py
- qemu/tests/block_resize.py
- qemu/tests/cfg/block_hotplug.cfg
- qemu/tests/cfg/block_resize.cfg
- qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
- qemu/tests/cfg/multi_disk_random_hotplug.cfg
- qemu/tests/cfg/multi_disk_wild_hotplug.cfg
- qemu/tests/hotplug_unplug_during_io_repeat.py
- qemu/tests/multi_disk_random_hotplug.py
- qemu/tests/multi_disk_wild_hotplug.py
Add gstack and strace log collection for cases:
block_hotplug,block_resize,hotplug_unplug_during_io_repeat, multi_disk_random_hotplug,multi_disk_wild_hotplug
ID:1956,1957,1958,1959,1960
> Add debug info collection for block device relevant cases

- qemu/tests/cfg/qemu_disk_img.cfg
Add new option of compression_type with zstd
ID: 1953
> qemu_disk_img: new case for image convert with zstd compressed

- qemu/tests/cfg/emulate_vf_reboot.cfg
- qemu/tests/emulate_vf_reboot.py
Automation a new case to support reboot guest after create VFs
ID:2012
> Reboot guest after create VFs

- generic/tests/cfg/emulate_vf_jumbo.cfg
- generic/tests/jumbo.py
Automation a new case to support igb vf jumbo tests
ID:2026
> igb vf jumbo tests

- qemu/tests/cfg/emulate_vf_shutdown.cfg
- qemu/tests/emulate_vf_shutdown.py
Automation a new case to support shutdown guest after create VFs
ID:2013
> shutdown guest after create VFs

- qemu/deps/block_device/libblkio_release_test.sh
It should use corresponding build code
instead of public repo.
ID：2100
> block_libblkio_release:change repo of source code

- qemu/tests/cfg/hotplug_unplug_during_io_repeat.cfg
- qemu/tests/hotplug_unplug_during_io_repeat.py
Add cleaning and umount operation for Linux guest
Reduce the number of loop to improve test efficiency.
ID:2052
> hotplug_unplug_during_io_repeat:improve test steps

- provider/win_driver_utils.py
- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
1.Fix the bug of incorrect au3 script name
2.Copy the msi au3 script and msi file to same path to
aviod missing file issue
3.add script to run the test case under 32bit OS
ID:2096,2107
> Update uninstall driver test's configuration

- qemu/tests/cfg/migration_with_sgx.cfg
- qemu/tests/cfg/sgx_basic.cfg
- qemu/tests/cfg/sgx_cpu.cfg
- qemu/tests/cfg/sgx_multi_vms.cfg
> sgx: Add thread_context object

- qemu/tests/cfg/cpu_topology_test.cfg
- qemu/tests/cpu_topology_details_test.py
CPU: Add details check of CPU topology for different sockets and cores
the scenario could also work on other platform
ID: 2001
> Add test scenario for CPU topology for all platform

- qemu/tests/cfg/nvdimm.cfg
> Disable nvdimm_nvml test case on ppc

- provider/pktgen_utils.py
1.fix attributeError
2.use process.system_output for the pkten command on host
id:2252
> pktgen_utils.py: two fixs

- qemu/tests/cfg/vsock_perf.cfg
- qemu/tests/vsock_perf.py
Add vsock_perf test case
ID: 2122
Signed-off-by: qcheng-redhat <qcheng@redhat.com>
> Add vsock_perf test case

- qemu/tests/cfg/hv_check_cpu_utilization.cfg
New guests need set administrator access for SecurityHealthService
ID:2342
> Add SecurityHealthService access for Win2025 and WinNext

- qemu/tests/cfg/qemu_guest_agent.cfg
file name doesn't match cause auto error.
ID: 2354
> qemu_guest_agent: hotfix for case gagent_debugview_VSS_DLL

- qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
Virtio_fs: Add several limination for virtiofs and remove numa related
cases on s390x
ID: 1500
> Add specific memory backend for virtiofs test case on s390x

- qemu/tests/cfg/qmp_command.cfg
> Remove 'singlestep' member of StatusInfo in rhel9.5

- qemu/tests/cfg/guest_iommu_test.cfg
- qemu/tests/guest_iommu_test.py
Set eim=on in x2apic mode.
ID: 2284
> Intel_iommu: add x2apic support

- qemu/tests/cfg/throttle_block_set_io_throttle.cfg
Change configuration to comply with the new iothread scheme.
ID:2340
> throttle_block_set_io_throttle:fix change iothread configuration

- qemu/tests/cfg/block_hotplug_check.cfg
fix pci_id_pattern is miss for windows
ID:1708
> block_hotplug_check:fix miss pci_id_pattern in cfg

- qemu/tests/balloon_uniqueness.py
Memory: update the bus to attach with s390x devices
ID: 2386
> Update the bus usage for s390x

- qemu/tests/cfg/block_kill_reconnect_with_remote_storage.cfg
Update the command for it filters more than one lines in latest RHEL
ID: 2418
> block_kill_reconnect_with_remote_storage: update find_system_disk_cmd

- qemu/tests/block_check_memory_leak.py
> Cancel memory leak test for ppc kvm xive interrupt type guest

- provider/virtio_mem_utils.py
- qemu/tests/cfg/virtio_mem_dynamic_memslots.cfg
- qemu/tests/virtio_mem_dynamic_memslots.py
virtio_mem_utils: refactors dynamic memslots functions
Refactors the dynamic memslots functions, including them
as part of the virtio_mem_utils provider to avoid code
duplication with future test cases.
ID: 2370
> virtio_mem_utils: refactors dynamic memslots functions

- provider/vdpa_sim_utils.py
id: 2450
Signed-off-by: Wenli Quan <wquan@redhat.com
> vdpa_sim_utils: corrected glob pattern to obtain the vdpa device name

- generic/tests/cfg/stress_boot.cfg
- generic/tests/stress_boot.py
1  Fix boot up with memory and vcpus
2. Set log into guest to 420s
ID: 2242
> stress_boot: fix boot up with mem and vcpus

- qemu/tests/block_performance_test.py
- qemu/tests/cfg/block_performance_test.cfg
1. Change dd to fio
2. Support choosing fastest disk
3. Support host IO performance checking
4. Support fio parameters data model
5. Support init/deinit operation on host and guest
ID:2397
> block_performance_test:improve test method

- qemu/tests/cpu_device_hotplug_time_jump.py
ID: 2513
regEx pattern error because of dmesg log changed.
> x86_cpu_hotplug: Fix regEx pattern error

- qemu/tests/cfg/virtio_fs_share_data.cfg
To compatible with python3, winapi cmd should be
updated.
ID: 2239
> create_dir_winapi: update winapi cmd

- generic/tests/cfg/pktgen_perf.cfg
- generic/tests/pktgen_perf.py
- provider/pktgen_utils.py
> pktgen: add support for one vp_vdpa test case in pktgen

- qemu/deps/timedrift/clktest.c
> add header files for test script clktest.c

- generic/tests/cfg/netperf.cfg
Signed-off-by: Wenli Quan [wquan@redhat.com]
id: 2529
> netperf: bypass compilation with -Wno-implicit-function-declaration

- qemu/tests/cfg/boot_from_virtiofs.cfg
Add bootindex 2 for stg image
ID: 2532
> boot_from_virtiofs: add bootindex for stg image

- qemu/tests/cfg/block_vhost_vdpa_test.cfg
1. Combinate options cache/discard/detect_zeroes
2. Change DummyCMD to dd command for windows test
3. Fix aio to threads when cache direct is off
ID:2270,2451,2452
> block_vhost_vdpa_test:improve test

- qemu/tests/block_iothread_test.py
- qemu/tests/cfg/block_iothread_test.cfg
> Add block iothread test cases

- qemu/tests/cfg/nested_vsock_con_sockets.cfg
- qemu/tests/cfg/nested_vsock_con_sockets_l1.cfg
- qemu/tests/cfg/vsock_test.cfg
Set default value for vsock_test_tool
Signed-off-by: qcheng-redhat <qcheng@redhat.com>
ID: 2500
> Set default value for vsock_test_tool

- qemu/tests/cfg/vfio_net_plug.cfg
- qemu/tests/vfio_net_plug.py
The new test case is to test hotplug or hotunplug vfio NICs into the guest, after that, reboot the guest to check if qemu process has any error.
> feat(vfio): Test hot plug/unplug vfio NIC into guest

- provider/win_driver_utils.py
Get windows os release build version, if version is bigger than 14393, the new pnputil flag will be used.
ID: 2511
> win_driver_utils: update cmd based on guest os version

- qemu/tests/cfg/vfio_net_lifecycle.cfg
- qemu/tests/vfio_net_lifecycle.py
Passthrough some NICs to the VM, during the VM lifecycle, check if NICs are working well.
ID: 2578
> feat(vfio): Test nics passthrough throughout the vm life cycle

- qemu/deps/block_device/libblkio_release_test.sh
The RHEL10 guest does not install wget default.
Adding wget package install into script.
ID:2591
> libblkio_release_test:fix miss wget

- qemu/tests/cfg/kvm_unit_test_nested.cfg
> kvmunittests: update to execute whole kvm-unit-tests suite

- provider/sgx.py
> Get sgx-epc size only from the current boot journal

- qemu/tests/cfg/multi_disk.cfg
Adjust image size to support the latest XFS
due to it requiring the size to be greater than 300M
ID:2593
> multi_disk:adjust image size

- qemu/tests/cfg/virtio_fs_host_owner_win.cfg
- qemu/tests/virtio_fs_host_owner_win.py
This issue is introduced by "Fix pylint check",
it can be fixed with setting a condition.
ID: 2515
> virtio_fs_host_owner: fix get shared dir issue

- provider/pktgen_utils.py
> Updated regex to correctly capture full version numbers

- qemu/tests/cfg/virtio_fs_support_win_fs.cfg
- qemu/tests/virtio_fs_support_win_fs.py
Adapt the win2025 GUI layout.
ID: 2259
> virtiofs_supp_for_fs.cfg: bug fixing

- provider/virt_storage/storage_volume.py
> storage_volume: Added the format node's child node

- qemu/tests/insert_media.py
Now blockdev raw format node can be eliminated upon conditions, so this patch modified the code to adapt with the change.
ID: 2408
> insert_media: adapt to blockdev raw format elimination

- generic/tests/cfg/netperf.cfg
- generic/tests/cfg/pktgen_perf.cfg
- qemu/tests/cfg/netperf_udp_perf.cfg
- qemu/tests/cfg/pktgen_burst_test.cfg
> perf cases: stop and flush firewalld, iptables and nftables

- qemu/tests/stress_kernel_compile.py
1.Install wget tool in guest
2.Set the progress parameter for wget
3.Set wget the download time to 40 mins
ID: 2501
> stress_kernel_compile: fix wget issues

- provider/backup_utils.py
- provider/blockdev_commit_base.py
- qemu/tests/blockdev_commit_auto_readonly.py
- qemu/tests/blockdev_commit_cor.py
- qemu/tests/blockdev_commit_filter_node_name.py
- qemu/tests/blockdev_commit_fio.py
- qemu/tests/blockdev_commit_firewall.py
- qemu/tests/blockdev_commit_forbidden_actions.py
- qemu/tests/blockdev_commit_general_operation.py
- qemu/tests/blockdev_commit_hotunplug.py
- qemu/tests/blockdev_commit_non_existed_node.py
- qemu/tests/blockdev_commit_powerdown.py
- qemu/tests/blockdev_commit_query_named_block_nodes.py
- qemu/tests/blockdev_commit_reboot.py
- qemu/tests/blockdev_commit_server_down.py
- qemu/tests/blockdev_commit_specify_node.py
- qemu/tests/blockdev_commit_speed_limit.py
- qemu/tests/blockdev_commit_standby.py
- qemu/tests/blockdev_commit_stop_cont.py
- qemu/tests/blockdev_commit_with_ignore.py
- qemu/tests/blockdev_commit_with_stop.py
- qemu/tests/blockdev_stream_base_itself.py
- qemu/tests/blockdev_stream_to_invalid_node.py
- qemu/tests/qsd_block_commit.py
> backup_utils: Added backing-mask-protocol support

- provider/virt_storage/storage_volume.py
> Removed raw format node after qemu/qsd 9.0.0

- qemu/tests/cfg/x86_cpu_model.cfg
ID: 2632
includes a small fix and adds some versioned CPU models
> x86_cpu_model:update cpu model category

- generic/tests/ping.py
Rewrite the code to support passt tests
ID:2619
> ping.ext_host: rewrite to support passt tests

- qemu/tests/cfg/edk2_basic.cfg
- qemu/tests/edk2_basic.py
Check whether the status of edk2
The boot process is normal.
ID: 2574
> edk2_basic:Add edk2 basic test

- qemu/tests/cfg/in_place_upgrade.cfg
ID:2567
Refined the commands when doing in place upgrade
> IPU: refine the commands when doing leapp test

- qemu/tests/cfg/virtio_mem_numa_basic.cfg
Add support on windows side to test viomem.
ID: 2496
> virtio_mem_numa_basic.cfg: Add support on windows side

- qemu/tests/cfg/tpm_verify_device.cfg
- qemu/tests/tpm_verify_device.py
Add two check points:
1. Check windows event log
2. Execute power shell command: tpmsupportedfeature
ID: 2676
> Add check points in tpm_verify_device test case

- qemu/tests/cfg/passthrough_fc_with_lun_device.cfg
> passthrough_fc_with_lun_device:add default max_sectors case

- qemu/tests/cfg/virt_firmware_check_phys_bits.cfg
> virt_firmware_check_phys_bits: update pattern for limitation_msg

- qemu/tests/cfg/block_resize.cfg
> block_resize:change sgdisk to parted

- qemu/tests/cfg/usb_device_check.cfg
> usb: Update chk_usb_info_cmd default value

- qemu/tests/edk2_basic.py
Add edk2 output information checkpoint due to product issue.
ID: 2866
> edk2_basic: Add edk2 output info checkpoint

- qemu/tests/usb_storage.py
> Cut down serial characters length

- generic/tests/pktgen_perf.py
- provider/pktgen_utils.py
For the arm platform, there are two pagesize package, 
Update the pagesize package acquisition method by the current 
guest base page size.
ID:2961
> pktgen_utils:Added support for 64k pagesize

- qemu/tests/seabios_bin.py
> seabios_bin: add bios bin file for the latest rhel guest

- qemu/tests/migration_with_vsock.py
- qemu/tests/vsock_hotplug.py
- qemu/tests/vsock_negative_test.py
- qemu/tests/vsock_test.py
Fix vsock tests random timing issue
ID: 3001
> Fix vsock tests random timing issue

- qemu/tests/cfg/hotplug_virtio_mem.cfg
Add support on windows side to test viomem hotplug.
ID: 3166
> hotplug_virtio_mem.cfg: Add support on windows side

- qemu/tests/cfg/qemu_guest_agent.cfg
- qemu/tests/qemu_guest_agent.py
add checkpoint and steps for case 'check_fsfreeze_hook_script', since customer case ask to check the logfile of hook_script
ID: 3120
> qemu_guest_agent: add steps for case 'check_fsfreeze_hook_script'

- qemu/tests/cfg/x86_cpu_flags.cfg
- qemu/tests/cfg/x86_cpu_model.cfg
ID: 3037
Remove the deprecated cpu models on different releases since they are not supported any more.
> x86: remove unsupported cpu models

- provider/virt_storage/storage_volume.py
- qemu/tests/blockdev_commit_cancel.py
- qemu/tests/cfg/blockdev_commit_cancel.cfg
New case:Cancel a commit job
id: 3151
> blockdev_commit_cancel:cancel a commit job

- provider/win_driver_utils.py
- qemu/tests/cfg/driver_load_stress.cfg
- qemu/tests/cfg/win_virtio_driver_update_test.cfg
1. Support install/uninstall viomem driver(windows guest only)
2. Support upgrade/downgrade viomem driver(windows guest only)
3. Support disable/Enable viomem driver (windows guest only)
ID:2485,2487,2488
> viomem: new case about viomem driver

- qemu/tests/cfg/in_place_upgrade.cfg
ID:3319
Add rmmod command for in place upgrade from RHEL 9 to RHEL 10
Signed-off-by: Miriam Deng <mdeng@redhat.com>
> Add rmmod command for in place upgrade from RHEL 9 to RHEL 10

- qemu/tests/remote_block_resize.py
Change the filter to find the target image for raw format.
ID: 2788
> remote_block_resize: adapt the raw images to be found for resizing

- qemu/tests/cfg/virtio_fs_daemon_readonly.cfg
- qemu/tests/virtio_fs_daemon_readonly.py
> virtio_fs_daemon_readonly: new case of virtiofsd readonly

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- .pylintrc
- commitlint.config.mjs
- requirements-ci.txt
1. Update checkout to v4
2. Update setup-python to v5
3. Update changed-files to v46
4. Update commitlint to v6
5. Add python3.12
6. Upgrade ubuntu runner
ID: 1901
> ci: Making CI more robust and rational

- qemu/deps/sev-snp/regular_attestation_workflow.sh
- qemu/tests/snp_basic_config.py
- qemu/tests/snp_multi_vm.py
According to snpguest command document, should
use host cpu model instead of guest cpu model.
> attestation: change to use host cpu model

- qemu/tests/cfg/snp_cpu_model.cfg
- qemu/tests/snp_cpu_model.py
> snp_cpu_model:Add cpu model test on snp guest

- qemu/tests/cfg/tpm_unattended_install.cfg
- qemu/tests/cfg/tpm_verify_device.cfg
Replace the wmic command with PowerShell commands in vTPM test cases
ID: 3800
> Remove the wmic command in vTPM test cases

- qemu/tests/cpu_device_hotplug_during_boot.py
ID: 3292
There are some changes in last rhel boot message, update
pattern	message	to match log.
> cpu_hotplug: fix mismatch boot message pattern

- qemu/tests/larger_buffer_with_none_cache_mode.py
Skip if none of the strace events are in the line
ID: 3855
> larger_buffer_with_none_cache_mode: enhance the output check

- qemu/tests/virtio_serial_file_transfer.py
Sometimes,it's not ready for first command in 1 second.
ID:3735
> virtio_serial_file_transfer:Change sleep time to 3

- qemu/tests/virtio_fs_share_data.py
avoid data loss when running system_reset
ID:4067
> virtio_fs_share_data:run sync command before reboot vm

- qemu/tests/openflow_acl_test.py
1.The old test method to check output is not reliable
2.Latest openssh changes the error output and causes failure
ID:4089
> Switch to socat to check whether the openflow acl rules are effective

- qemu/tests/cfg/dump_guest_core.cfg
dump_guest_core: change vmcore path to fix truncation warning
ID:  3869
> dump_guest_core: change vmcore path to fix truncation warning

- qemu/tests/cfg/qemu_img.cfg
change the commit_testfile from / to /home to be compatible for both package and image mode guests
ID: 4076
> qemu_img: change the directory for commit test file

- qemu/tests/balloon_uniqueness.py
balloon_uniqueness:Update right bus type for s390x device
ID:4196
> balloon_uniqueness:Update right bus type for s390x device
