qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

For nfs backend --no-killpriv-v2 option should be set to virtiofsd.
ID: 2069900

virtio_fs: add --no-killpriv-v2 for nfs backend

---

qemu/tests/cfg/tpm_verify_device.cfg

Deps on avocado-framework/avocado-vt/pull/3364, Update
global TPM parameters and set different TPM names in
different VMs.
ID: 2072812

tpm_verify_device: Update some TPM parameters

---

qemu/tests/cfg/balloon_memhp.cfg

balloon_memhp: increases threshold value to avoid memory size mismatch
ID: 2063976

balloon_memhp: increases threshold value to avoid memory size mismatch

---

qemu/tests/cfg/viorng_in_use.cfg

Relocate ‘winutils.iso’ part since it only for Windows.
ID: 2079223

Viorng_in_use: Changed ‘winutils.iso’ since it only for Windows

---

qemu/tests/cfg/rh_qemu_update.cfg
qemu/tests/rh_qemu_update.py

PR adds new test case, which uses guest for upgrade testing between two `qemu-kvm` versions provided by different RHEL `virt` modules (if module is used, otherwise it does upgrade between two different package versions).
ID: 2067729

rh_qemu_update: new test case for testing qemu-kvm upgrade

---

qemu/tests/cfg/transfer_file_over_ipv6.cfg
qemu/tests/transfer_file_over_ipv6.py

1.Add linklocal and remote IPv6 addr for windows and linux
ID:2074848

transfer_file_over_ipv6: Add IPv6 address type

---

provider/blockdev_base.py
qemu/tests/blockdev_mirror_readonly.py
qemu/tests/blockdev_mirror_sync_top.py
qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_io.cfg
qemu/tests/cfg/blockdev_mirror_complete_running_job.cfg
qemu/tests/cfg/blockdev_mirror_error.cfg
qemu/tests/cfg/blockdev_mirror_filternode.cfg
qemu/tests/cfg/blockdev_mirror_firewall.cfg
qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg
qemu/tests/cfg/blockdev_mirror_hotunplug.cfg
qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg
qemu/tests/cfg/blockdev_mirror_no_space.cfg
qemu/tests/cfg/blockdev_mirror_readonly.cfg
qemu/tests/cfg/blockdev_mirror_ready_vm_down.cfg
qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg
qemu/tests/cfg/blockdev_mirror_simple.cfg
qemu/tests/cfg/blockdev_mirror_speed.cfg
qemu/tests/cfg/blockdev_mirror_stress.cfg
qemu/tests/cfg/blockdev_mirror_sync_none.cfg
qemu/tests/cfg/blockdev_mirror_sync_top.cfg
qemu/tests/cfg/blockdev_mirror_vm_reboot.cfg
qemu/tests/cfg/blockdev_mirror_vm_stop_cont.cfg

Remove "image_create_support_*" from *.cfg 
id:2074479

blockdev_mirror:remove image_create_support_*

---

qemu/tests/cfg/hotplug_mem_repeat.cfg
qemu/tests/hotplug_mem_repeat.py

hotplug_mem_repeat: skips memory unplug process on all rhel7 guests
ID: 2054033

hotplug_mem_repeat: skips memory unplug process on all rhel7 guests

---

qemu/tests/cfg/s390x_cpu_model.cfg
qemu/tests/s390x_cpu_model_boot.py
qemu/tests/s390x_cpu_model_expansion.py

CPU model: add cases to check if the QMP command "query-cpu-model-expansion" works
expected and adaption test with different CPU models on s390x
ID: 2070199

Add cases for cpu-model-expansion and boot with different CPU-models

---

qemu/tests/cfg/tpm_unattended_install.cfg
qemu/tests/cfg/tpm_verify_device.cfg

Fix an issue on old rhel 8 releases caused by a product bz. 
ID: 2084051

Add restriction to tpm test cases for some old rhel 8 releases

---

qemu/tests/remote_server_disconnected.py
qemu/tests/sr_iov_sanity.py

Since Python 3.3+ provides `ipaddress` as the standard library for
IPv4/IPv6 manipulation, let's replace the third-party one (`netaddr`)
with it for a better maintainability.

replace netaddr with ipaddress

---

qemu/tests/numa_consistency.py

numa_consistency: include only numa nodes with memory and cpus
Changes the numa nodes list to include only the nodes with
memory and cpus assigned
ID: 2070405

numa_consistency: include only numa nodes with memory and cpus

---

qemu/tests/blockdev_commit_standby.py
qemu/tests/blockdev_stream_general.py

In case blockdev_stream_general and blockdev_commit_standby
we check job in paused/standby status by "job's offset not
changed", that is not precise. So now we check it's status
directly.
id:2078394

blockdev_stream_general:correct job paused check

---

qemu/tests/blockdev_inc_backup_with_ignore.py

In original design, when failed to prepare test env, like lvm setup,
case's step continue to run, which will cause "target dir not exist"
error.
Now, add test.fail in _create_inc_dir.except to make the case fail
if prepare test env failed
id:2073931

blockdev_inc_backup_with_ignore: Fail case when prepare test env failed

---

qemu/tests/cfg/multi_nics_verify.cfg

1.Windows guests will occupy more machine resources, so the login
time needs to be inceased
2.From the perspective of QE, in the case of multiple queues and
multiple network cards, more machine resources are required, and
it is not a good choice to limit the number of smps to be equal
to queues, so delete this line of configuration.
ID:2087640

multi_nics_verify: Increase login time and modify cli parameters

---

qemu/tests/blockdev_stream_with_ioerror.py
qemu/tests/cfg/blockdev_stream_with_ioerror.cfg

For rhel7.9, dd 80M file is too large for this test, so change
the dd file size to 60M
id:2079666

blockdev_stream_with_ioerror:80M file is too large for 100M backend space

---

qemu/tests/cfg/remote_image_compress.cfg
qemu/tests/remote_image_compress.py

This commit adds a test case that checks that the compress filter
works properly wrapping images when exported with the qemu-nbd command.
This commit depends on the commits from the https://github.com/avocado-framework/avocado-vt/pull/3360 PR from avocado-vt.
ID: 2047527

qemu-nbd: Develop convert over nbd with compress

---

qemu/tests/bridge_vlan.py

1.Since the guest network was disabled in the previous test step, then guest can not reobtain network,so add this test step.
ID:2082800

bridge_vlan:Add restart guest network test steps

---

qemu/tests/block_with_share_rw.py
qemu/tests/cfg/block_with_share_rw.cfg

Some arm servers only have nvme controller,
so add an environment check for arm.
ID:2073269

block_with_share_rw:add environment checks

---

qemu/tests/cfg/ple_test.cfg
qemu/tests/ple_test.py

ID: 1926088
UnixBench will raise error while runing without
the dependency packages.

ple_test: add dependency of UnixBench

---

qemu/tests/cfg/qemu_guest_agent.cfg

qemu_guest_agent: add reboot/halt support for RHEL 8
ID:2088394

qemu_guest_agent: Add reboot/halt support for RHEL 8

---

qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_io.cfg
qemu/tests/cfg/blockdev_mirror_complete_running_job.cfg
qemu/tests/cfg/blockdev_mirror_error.cfg
qemu/tests/cfg/blockdev_mirror_filternode.cfg
qemu/tests/cfg/blockdev_mirror_firewall.cfg
qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg
qemu/tests/cfg/blockdev_mirror_hotunplug.cfg
qemu/tests/cfg/blockdev_mirror_install.cfg
qemu/tests/cfg/blockdev_mirror_multiple_blocks.cfg
qemu/tests/cfg/blockdev_mirror_no_space.cfg
qemu/tests/cfg/blockdev_mirror_readonly.cfg
qemu/tests/cfg/blockdev_mirror_ready_vm_down.cfg
qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg
qemu/tests/cfg/blockdev_mirror_same_src_tgt.cfg
qemu/tests/cfg/blockdev_mirror_simple.cfg
qemu/tests/cfg/blockdev_mirror_speed.cfg
qemu/tests/cfg/blockdev_mirror_stress.cfg
qemu/tests/cfg/blockdev_mirror_sync_none.cfg
qemu/tests/cfg/blockdev_mirror_sync_top.cfg
qemu/tests/cfg/blockdev_mirror_vm_reboot.cfg
qemu/tests/cfg/blockdev_mirror_vm_stop_cont.cfg

Remove backend limitation for mirror cases, excluse
those defined under specific backend
id:2097610

blockdev_mirror:remove backend limitation

---

qemu/tests/block_hotplug_in_pause.py

Not all services are available even if automation login guest already.
It may result in unexpected result if send request to guest to do something.
It may consider to add some sleep time to ensure guest finish booting.
ID:2095166

block_hotplug_in_pause:add sleep time to wait guest finish booting

---

qemu/tests/cfg/x86_cpu_protection_key.cfg
qemu/tests/x86_cpu_protection_key.py

ID: 2094628
New case which support protection keys in an
AMD EPYC-Milan or newer models VM.

x86_cpu_protection_key: support protection keys

---

qemu/tests/tpm_bind_luks.py

Sometimes the guest will go to the DA lockout mode if the vTPM is not in
the right status, reset the DA lockout counter before binding to avoid
this issue.
ID: 2099993

tpm_bind_luks: Reset TPM DA lockout counter before binding

---

qemu/tests/cfg/numa_opts.cfg

The internal default allocation of the current sockets is 2,
but cores in the same socket cannot be assigned to different
numa nodes.
ID:2097641

numa_opts:fix incorrect cpu numa allocation

---

qemu/tests/cfg/migrate.cfg

Add ksm command check,throw a TestSkipError exception
if command requested by test is not installed.
ID:2101703

migrate:Add ksm command check

---

qemu/tests/cfg/cdrom_block_size_check.cfg
qemu/tests/cfg/change_media.cfg
qemu/tests/cfg/plug_cdrom.cfg

The provious product do not support iothread on scsi-cd.
The feature is supported from qemu version 7.0.0-4
Some typical cases are choosen to remove disable iothread limit.
ID:2097576

Change some cdrom relevant cases to set no limit on iothread

---

qemu/tests/ceph_image_mem_leak.py
qemu/tests/cfg/ceph_image_mem_leak.cfg

1. Start guest with 10 rbd data disks and system disk.
2. Check the block info for 2 hours
3. Check the used memory size is not increased
ID: 2101643

ceph_image_mem_leak: new case of ceph_image_mem_leak

---

qemu/tests/single_driver_install.py

Now after guest shutdown then boot again, the guest will not use
the cloned image as code issue which result in unexpected issue.
After the fix, we can confirm all steps run in the same image.
ID: 2106243

single_driver_install: use the cloned image for all steps

---

qemu/tests/virtio_fs_share_data.py

When using ext3/ext4 as the fs backend,sometimes creating
the big file(about 5G) will fail due to the performance.
Extend the timeout to make it successful on the most host.
ID: 2101340

virtio_fs: extend timeout of creating big file on host

---

qemu/tests/cfg/qemu_img_check_data_integrity.cfg
qemu/tests/qemu_img_check_data_integrity.py

1. Backup image before testing and restore after
2. Check the image and repair the leaked clusters after
data integrity testing
ID: 2103037

qemu_img_check_data_integrity: fix leaked clusters issue

---

qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/virtio_driver_sign_check.py

As the driver change, signature check steps need to change as well.
Updated details as follows:
For prewhql driver version:
SignTool.exe verify /v /pa /c vioscsi.cat vioscsi.sys
SignTool.exe verify /v /pa /c vioscsi.cat vioscsi.inf
For whqled driver version:
SignTool.exe verify /v /kp /c vioscsi.cat vioscsi.sys
SignTool.exe verify /v /kp /c vioscsi.cat vioscsi.inf
id: 2094221

Update driver signtool signature check steps

---

qemu/tests/migration_with_vsock.py
qemu/tests/vsock_hotplug.py
qemu/tests/vsock_negative_test.py
qemu/tests/vsock_test.py

1. Adjust some timeout values in vsock test cases to make them more stable on some old hosts.
2. Adjust big_file size to a more reasonable value.  
ID: 2071224

Adjust some timeout values in some vsock test cases.

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

New case about 'Create new directory with WinAPI's CreateDirectory', it is only for windows guest and virtiofsd-rs version.
1. Create directory on shared dir with Winapi command.
2. Check virtiofsd output to make sure there is no error.
ID: 2102452

virtio_fs: create dir with winapi in windows guest

---

generic/tests/ntttcp.py

Currently,VM's session will be lost deue to Ncat reset
So I would like to replace it with serial login to improve it
ID:2076210

ntttcp:use serial login instead of SSH/Netcat

---

qemu/tests/cfg/blockdev_stream.cfg
qemu/tests/cfg/blockdev_stream_remote_server_down.cfg
qemu/tests/cfg/blockdev_stream_with_ioerror.cfg

Set test data disk size to 2G, for image creation
for host_device test is not allowed. Set the test
disk size the same with other cases for convenience.
id:2108980

blockdev_stream:update test data disk size to 2G

---

qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/rng_maxbytes_period.py

'virtio-rng-pci' is one type of virtio rng devices, the real name is not
unique, we have "virtio-rng-pci", "virtio-rng-pci-non-transitional",
"virtio-rng-pci-transitional", etc. And the device name in some
platforms is not the same. So we should not use the params namespace
"xxx_virtio-rng-pci", otherwise we need to configure the same virtio-rng
device with different parameters in diff platforms.
ID: 2098066

Cut out '-pci' from the namespace of virtio-rng device params

---

qemu/tests/cfg/balloon_memhp.cfg

Due to product changes, the threshold value has been
increased for x86 platforms.
So synchronously adjust the SoC platform.
ID: 2106982

balloon_memhp: Increases threshold value for SoC platform

---

qemu/tests/memhp_threads.py

Based on avocado-vt [commit  e6228fd6fd3b18d098669f26789eefc143b2cbdc,](https://github.com/avocado-framework/avocado-vt/commit/e6228fd6fd3b18d098669f26789eefc143b2cbdc)
it is needed to include again the call to Memory
\_\_attributes\_\_ in order to get the proper params
when executing the hotplug.
ID: 2101305

memhp_threads: reverts fix attribute error

---

qemu/tests/cfg/blockdev_snapshot.cfg
qemu/tests/cfg/blockdev_snapshot_chains.cfg
qemu/tests/cfg/blockdev_snapshot_data_file.cfg
qemu/tests/cfg/blockdev_snapshot_multi_disks.cfg

Update data disk size to 2G for test convenience.
Image creation for nbd and host_device test is
not allowed, and all cases share the same backend
image, so we should make sure all test disks are
the same size, here we use 2G.
id:2108963

blockdev_snapshot: update data disk size to 2G

---

qemu/tests/cfg/blockdev_commit.cfg
qemu/tests/cfg/blockdev_commit_cor.cfg
qemu/tests/cfg/blockdev_commit_filter_node_name.cfg
qemu/tests/cfg/blockdev_commit_firewall.cfg
qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg
qemu/tests/cfg/blockdev_commit_general_operation.cfg
qemu/tests/cfg/blockdev_commit_hotunplug.cfg
qemu/tests/cfg/blockdev_commit_non_existed_node.cfg
qemu/tests/cfg/blockdev_commit_powerdown.cfg
qemu/tests/cfg/blockdev_commit_query_named_block_nodes.cfg
qemu/tests/cfg/blockdev_commit_server_down.cfg
qemu/tests/cfg/blockdev_commit_specify_node.cfg
qemu/tests/cfg/blockdev_commit_speed_limit.cfg
qemu/tests/cfg/blockdev_commit_throttle.cfg
qemu/tests/cfg/blockdev_commit_top.cfg

For host_device test, image creation is not allowed,
we should use the same size for test data disks, so
we set the size to 2G to make the same size with not
chaning cases.
id:2109332

blockdev_commit:set test data disk size to 2G

---

qemu/tests/cfg/blockdev_full_mirror.cfg
qemu/tests/cfg/blockdev_mirror_firewall.cfg
qemu/tests/cfg/blockdev_mirror_remote_server_down.cfg

For host_device test, image creation is not allowed,
so we set data disk size to the same 2G for all cases.
id:2109371

blockdev_mirror:set test data disk size to 2G

---

qemu/tests/cfg/blockdev_full_backup.cfg
qemu/tests/cfg/blockdev_full_backup_invalid_max_workers.cfg
qemu/tests/cfg/blockdev_full_backup_multi_disks.cfg
qemu/tests/cfg/blockdev_full_backup_nonexist_target.cfg
qemu/tests/cfg/blockdev_full_backup_x_perf.cfg
qemu/tests/cfg/blockdev_inc_backup_test.cfg

For host_device test, image creation is not allowed,
all test data disks size should keep the same,
so we set it to 2G.
id:2109814

blockdev_backup:set test data disk size to 2G

---

qemu/tests/cfg/fio_perf.cfg

To make the better comparison of virtiofs performance,
we are supposed to use the following two options:
--thread-pool-size and --allow-direct-io(rhel8 doesn't support).
ID: 2075728

fio_perf: add some options to virtiofsd

---

qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Generic/531 always fail due to produce bz and it will block
the latter test cases.So add it to blacklist until the product
bz is fixed.
ID: 2111391

virtio_fs: add generic/531 to blacklist for xfstest on nfs

---

qemu/tests/cfg/hotplug_mem_share_discard_data.cfg
qemu/tests/hotplug_mem_share_discard_data.py

hotplug_mem_share_discard_data: new memory auto case
hotplug with share and discard-data options
Creates a new auto case that setup hugeapages, boots a guest with a 
memory-backend-file object and one numa node, hotplugs backend-ram
or backend-file memory object with share: True option and the first one 
could be with discard-data on/off, then checks the plugged memory device,
unplugs it and check results for discard-data value
ID: 2095232

hotplug_mem_share_discard_data: new auto case for memory hotplug with share and discard-data options

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

1. virtio_fs: use session.cmd to instead of session.sendline
Using "cd /d c:\" to instead of "C:", because the previous one
has exit code. So can use session.cmd() directory which
is more usable than session.sendline().
2.  virtio_fs: some update of virtio_servic_stop_start
This viofs_sc_stop_cmd is only for viofs_service_stop_start test
case, we should limit it to it's work scope to avoid
other cases' error. And for stop/start steps, use a more resonable way to check
the service status.
ID: 2112744,  2112791

virtio_fs: some optimization and bug fix

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 2117101
Sapphire Rapids (SPR) supports AMX Instructions.
And also fix one little issue about one wrong flag parameter.

x86_cpu_flags:add new case to test AMX on Sapphire Rapids

---

qemu/tests/cfg/check_block_size.cfg

Virtual_block: add a variant with install guest into a 4096k size of
image with physical_block_size&logical_block_size both equal to 4096k
ID: 2112278

Add variants to check_block_size for more coverage

---

qemu/tests/cfg/multi_nics_verify.cfg
qemu/tests/cfg/nic_hotplug.cfg

1. nic_hotplug..with_repetition: it will repeat 100 times, this means it
will open more than 400 fds in the qemu process, so extend maximum
number of open file descriptors.
2. multi_nics_verify.with_multiqueue: the queues equal to smp, when the
smp is too large, this case will open thousands of fds, and maybe beyond
the support of qemu.
ID: 2115341

Tweak 2 multi queues network cases

---

qemu/tests/cfg/win_virtio_driver_update_test.cfg

For balloon driver update test,as it calls balloon_check
function and do memory check after balloon test, which need
to add guest_compare_threshold and guest_mem_ratio to make
windows guest works.
ID: 2116238

win_virtio_driver_update: add compare_threshold and mem_ratio for balloon

---

provider/job_utils.py

The function 'wait_until_block_job_completed' call 'block_job_complete'
while job is in 'ready' status, while 'block_job_complete' wait for
'ready' status again. Sometimes, job completed already before checking
status in 'block_job_complete' and cause timeout error.
id: 2111720

job_utils: avoid waiting for 'ready' status while job completed alredy

---

qemu/tests/cfg/openflow_acl_test.cfg

1.Change the windows ftp server settings cmd and modified the ftp
path and target server.To solve the problem that windows guests
cannot access the other party's ftp service
ID:2052847

openflow_acl_test..ftp:Change the windows ftp server settings cmd

---

qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/virtio_fs_hotplug.py
qemu/tests/virtio_fs_multi_vms.py
qemu/tests/virtio_fs_set_capability.py
qemu/tests/virtio_fs_share_data.py

Copy virtiofs.exe from virtio-win cdrom to c: in case
the virtio-win cdrom volume name is changed in a test loop.
ID: 2079196

virtio_fs: change virtiofs bin path for windows guest

---

qemu/tests/cfg/qemu_guest_agent.cfg

Qemu_guest_agent: add 'reboot' and 'halt' support for RHEL 7 on s390x platform.
ID:2111006
Signed-off-by: Bogdan Marcynkov [bmarcynk@redhat.com]

qemu_guest_agent: Add reboot/halt support for RHEL 7

---

qemu/tests/cdrom.py

The cdrom devices maybe not lock status after boot in linux.
It is better to unlock cdrom in advance.
ID:2114740

cdrom_test:add unlock cdrom operation for linux guest

---

qemu/tests/cfg/hotplug_mem_negative.cfg
qemu/tests/hotplug_mem_negative.py

Currently on the arm platform maxmem_mem needs to be
less than 1T, so update the configuration.
ID: 2107006

hotplug_mem_negative:Correct maxmem_mem value on arm platform

---

qemu/tests/cfg/check_block_size.cfg

Remove '4096_4096_cluster_install' on i386 platform of seabios.
As Seabios only supports logical_block_size = 512. It is a
regression issue introduced by another patch.
ID: 2119702

check_block_size: Remove '4096_4096_cluster_install' on i386 of seabios

---

generic/tests/cfg/nfs_corrupt.cfg

The warning in the host dmesg is not a test point
for this test, so turning it off has an effect
on the test results.
ID: 2120501

nfs_corrupt: Set host_dmesg_ignore to yes

---

qemu/tests/cfg/s390x_cpu_model.cfg
qemu/tests/s390x_cpu_model_baseline.py

The `query-cpu-model-baseline` is expected select
- the intersection of both model definitions' properties
- the older generation in a list of two.
Agreed with developers not to cover all cpu models.
Signed-off-by: Sebastian Mitterle <smitterl@redhat.com>
Suggested-by: Boqiao Fu <bfu@redhat.com>

s390x_cpu_model: Add baseline test cases

---

generic/tests/cfg/nfs_corrupt.cfg
generic/tests/nfs_corrupt.py

Virtual_blk: add label for stage disk to make sure right drive was tested while
dd testing
ID: 2119690

Add label for stage disk, delete the bootindex on s390x

---

qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/rng_maxbytes_period.py

Updates for 'rng_maxbytes_period' case on s390x platform  - fixed 'expect driver error' in cases.
Also, this patch fixed next 2 errors in this case:
1) "Read data rate is not as expected. data rate: 79.2 kB/s, max-bytes: 512, period: 1000",
2) "Unexpected dd result, status: 0, output: 1+0 records in"
ID: 2111454

rng_maxbytes_period: guest report driver is s390-trng , expect is 'virtio_rng'

---

provider/win_dump_utils.py

The case sometimes fails because the dump analysis log
cannot be found. So add a checkpoint to check if
chk_dump_cmd is executing as expected. Extend the timeout
to wait for the log to be generated.
ID:2120153

win_dump_utils:imporvement and bug fix

---

qemu/tests/cfg/watchdog.cfg
qemu/tests/watchdog.py

watchdog: remove s390x with rdma since it's not supported right now; and
according to the performance issue on z13, add 5 sec before checking the
VM status.
ID: 2121647

remove s390x with rdma and add wait time before check vm status

---

qemu/tests/cfg/hotplug_mem_reserve.cfg

hotplug_mem_reserve: increases threshold value
ID: 2122616

hotplug_mem_reserve: increases threshold value

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/cfg/x86_cpu_model.cfg

ID: 2084388
Disable deprecated many named CPU models which may
have some problems while booting a RHEL9 guest.

x86_cpu_model: disable some unsupported models

---

qemu/tests/eject_media.py

Not all guest have same behavior.
It makes cdrom tray is opened then execute the
blockdev-remove-medium/blockdev-change-medium opeation.
ID:2106985

eject_media:fix change media issue

---

qemu/tests/nested_block_resize.py

Change aligns test logic with `ansible_test` using the same approach.
ID: 2124295

nested_block_resize: cancel test if `ansible-playbook` is not available

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Add inode-file-handles parameters test for general file
system and nfs file system. Also compatible testing with
sandbox.
ID: 2090128

virtio_fs: add inode-file-handles for virtiofsd

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

The cmd to create dir by winpi has no exit code, so it's better
to use another cmd to check if the dir was created successfully.
ID: 2112799

virtio_fs: logic change of checking dir created by winapi

---

qemu/tests/cfg/blockdev_full_backup_multi_disks.cfg

Correct blk_extra_params setting for virtio_blk
id:2124464

blockdev_full_backup_multi_disks:correct blk_extra_param setting

---

qemu/tests/cfg/uefi_check_resolution.cfg
qemu/tests/uefi_check_resolution.py

1. the default value before rhel9.1: 640 x 480
2. the default value from rhel9.1: 1280 x 800
ID: 2125105

update the default resolution for rhel9.1 and higher version

---

qemu/tests/cfg/x86_cpu_protection_key.cfg

ID: 2126254
RHEL8 and RHEL9 have different microarchitecture supports, need to use them separately.

x86_cpu_protection_key: update microarchitecture level

---

qemu/tests/cfg/uefi_secureboot.cfg

The signer's common name is Red Hat Secure Boot Signing 501 from rhel9, so update the pattern in the config file.
ID: 2129120

uefi_secureboot: update sign_keyword for rhel9 and higher version

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

virtio_fs_share_data.py: ignore some errors which do NOT belong to pjdfstest
ID: 2076950

virtio_fs_share_data.py: ignore some errors which do NOT belong to pjdfstest

---

qemu/tests/cfg/uefishell.cfg

For windows guest, no need to winutils iso in the case, so set cdroms to null string.
ID: 2134607

uefishell.check_network: disable winutils iso for windows guest

---

qemu/tests/change_media.py

It may not keep locked after change media in different guest. 
It needs to set lock on explictly then check the lock status.
ID:2122509

change_media:fix lock checking issue

---

qemu/tests/cfg/hv_check_cpu_utilization.cfg

We can not change service config via sc comamnd for win11 currently, so use reg command instead.
ID: 2125132

hv_check_cpu_utilization: change stop service method for win11

---

qemu/tests/cfg/block_with_iommu.cfg

iommu is support since RHEL8
The limitation only affect on old version.
ID:2135707

block_with_iommu:enable verify_enabled since RHEL8

---

qemu/tests/cfg/migrate.cfg
qemu/tests/migration.py
qemu/tests/migration_with_file_transfer.py
qemu/tests/migration_with_netperf.py

After confirm with developer,ksmtuned package not a strong dependency for migration scenarios, so delete the check of ksmtuned for migration scenarios.
ID:2134053

migrate:Delete the check of ksmtuned for migration scenarios

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

The installation can not find the system disk
if no serial on multi-disks.
Adding serial for each disk to make sure installation may find the target disk.
ID:2125192

virtio_scsi_cdrom:add serial on disks

---

generic/tests/cfg/kdump.cfg
generic/tests/kdump.py
qemu/tests/kdump_with_stress.py

1. Setting crashkernel=1G-4G:192M,4G-64G:256M,64G-:512M for RHEL9 or later releases
2. Setting crashkernel=256M for RHEL8 (x86_64)
ID: 2127790
Signed-off-by: Ke MA <mama@redhat.com>

Update 'crashkernel=' in kdump.cfg for RHEL9

---

qemu/tests/cfg/virtio_scsi_cdrom.cfg

After testing, both s390 and aarch64 support this scenario,
So remove platform restrictions.
ID: 2137477

virtio_scsi_cdrom: Remove platform restrictions

---

generic/tests/cfg/trans_hugepage.cfg
generic/tests/trans_hugepage.py

1. the output of 'process.system_output' is a bytes-list object
for python3, and 're' cannot use a str pattern on a bytes-like object
2. '<' not supported between instances of 'float' and 'str'
3. Replace 'logging' with 'test.log'
4. Disable 'trans_hugepage.base' with aarch64 and s390x platform
5. For different products, the filename to show the largepages are
different, add optional filename list
depends on: https://github.com/avocado-framework/avocado-vt/pull/3335
id: 2032252

trans_hugepage: fix several TypeError

---

qemu/tests/cfg/cpu_info_check.cfg
qemu/tests/cpu_info_check.py

ID: 2130748
These deprecated cpu models aren't supported since qemu 7.0.

cpu_info_check:remove checking deprecated cpu models

---

qemu/tests/cfg/chardev_tls_encryption.cfg
qemu/tests/chardev_tls_encryption.py

ID: 2095105
OVMF has a different boot entry message from seabios, fix this. And change the cleaning steps since it is conflict with the information 'depends_pkgs=gnutls-utils'.

chardev_tls_encryption:update checkpoint of boot entry

---

generic/tests/cfg/nfs_corrupt.cfg
qemu/tests/cfg/create_large_img.cfg
qemu/tests/cfg/qemu_disk_img.cfg

nfs_corrupt: skip for nfs backend
create_large_img: skip for nfs backend
qemu_disk_img: skip commit sub cases for nfs backend
ID: 2139657

skip several cases for nfs backend

---

qemu/tests/cfg/hotplug_mem_repeat.cfg
qemu/tests/cfg/hotplug_mem_stress_ng.cfg

Increase mem_fixed and memory object size to 8GB for hotplug_mem_repeat and also hotplug_mem_stress_ng cases
ID: 2140019

hotplug_mem_repeat: increase mem_fixed value

---

qemu/tests/blockdev_snapshot_guest_agent.py
qemu/tests/blockdev_snapshot_reboot.py
qemu/tests/blockdev_snapshot_stop_cont.py
qemu/tests/blockdev_snapshot_stress.py

for test with nfs backend
When run test with system disk, with original case design, backing file's path that on nfs will be
replaced by the local path, which will cause rebasing to an not existed backing file, update code to correct it.
id:2139585

blockdev_snapshot_reboot:to get correct backing     for test with nfs backend

---

qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/virtio_fs_hotplug.py
qemu/tests/virtio_fs_multi_vms.py
qemu/tests/virtio_fs_set_capability.py
qemu/tests/virtio_fs_share_data.py

For driver test, if driver verifier is enabled, to get memory leak, it's better to disable or uninstall driver after driver test.
ID: 2138792

virtio_fs: add memory check steps with verifier enabled

---

qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

xfstest only run on two nfs backend.
ID: 2143865

virtio_fs: add limitation for xfstest on nfs

---

qemu/tests/block_check_memory_leak.py
qemu/tests/cfg/block_check_memory_leak.cfg

There is no memoey leak in recent testing.
So change the threahold to 0.
ID:2138099

block_check_memory_leak:change threshold to 0

---

qemu/tests/balloon_boot_in_pause.py
qemu/tests/balloon_check.py
qemu/tests/balloon_hotplug.py
qemu/tests/balloon_memhp.py
qemu/tests/balloon_minimum.py
qemu/tests/balloon_sc_interrogate.py
qemu/tests/balloon_service.py
qemu/tests/balloon_stress.py
qemu/tests/cfg/balloon_boot_in_pause.cfg
qemu/tests/cfg/balloon_check.cfg
qemu/tests/cfg/balloon_hotplug.cfg
qemu/tests/cfg/balloon_illegal.cfg
qemu/tests/cfg/balloon_in_use.cfg
qemu/tests/cfg/balloon_memhp.cfg
qemu/tests/cfg/balloon_minimum.cfg
qemu/tests/cfg/balloon_service.cfg
qemu/tests/cfg/balloon_stress.cfg
qemu/tests/cfg/driver_load_stress.cfg

For windows balloon driver test, if driver verifier is enabled, to get memory leak, it's better to disable or uninstall driver after driver test.
ID: 2139570

balloon: add memory check steps with verifier enabled

---

qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/rng_host_guest_read.cfg
qemu/tests/cfg/rng_hotplug.cfg
qemu/tests/cfg/rng_read_longtime.cfg
qemu/tests/cfg/viorng_in_use.cfg
qemu/tests/rng_bat.py
qemu/tests/rng_host_guest_read.py
qemu/tests/rng_hotplug.py

For driver test, if driver verifier is enabled, to get memory leak, it's better to disable or uninstall driver after driver test.
ID:2113798

viorng: Add memory leak check steps with verifier enabled

---

qemu/tests/boot_nbdimage_with_qsd.py
qemu/tests/cfg/boot_nbdimage_with_qsd.cfg

1.Prepare an installed OS image via converting
2.Export the OS image via QSD plus unix
3.Start VM from the exported image
ID: 2143881

boot_nbdimage_with_qsd: new case

---

qemu/tests/cfg/block_discard.cfg

Sometimes it will fail to mkpart just after mklabel, it says that: "Partition(s) 1 on /dev/sdb have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use. As a result, the old partition(s) will remain in use. You should reboot now before making further changes."
Wait a little time can fix this problem.
Test Result:
```
(1/4) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.aarch64.io-github-autotest-qemu.block_discard.xfs.unmap.arm64-pci: STARTED                                                                              
(1/4) Host_RHEL.m8.u8.product_rhel.qcow2.virtio_scsi.up.virtio_net.Guest.RHEL.8.8.0.aarch64.io-github-autotest-qemu.block_discard.xfs.unmap.arm64-pci: PASS (81.48 s) …
```

block_diskcard: add sleep time between mklabel and mkpart

---

qemu/tests/qemu_img_lock_reject_boot.py

Sometimes the host needs to prepare some daemons such as swtpm to provide resources to qemu instances, however vm2.make_create_command will only generate qemu command lines, so the command lines will definitely terminate if the qemu process requires daemons.
ID: 2145090

qemu_img_lock_reject_boot: Launch the second instance using vm2.create

---

provider/ansible.py
qemu/tests/cfg/ansible_test.cfg
qemu/tests/cfg/nested_block_resize.cfg

Provide optional custom dnf repo containing ansible. This change is relevant for system like RHEL 8.5 and older.
**Note:** This change depends on https://github.com/avocado-framework/avocado/pull/5527.
ID: 2143263

ansible: update provider with optional custom dnf repository

---

qemu/tests/cfg/blockdev_mirror_with_ignore.cfg

For passthrough device, extension to 2G is not
enough for mirror completion, which will still
cause block_job_io_error. So extend lv to 2.5G
then tests under all scenarios can be met.
id:2151096

blockdev_mirror_with_ignore:extend lv to 2.5G

---

provider/virtio_mem_utils.py
qemu/tests/cfg/virtio_mem_numa_basic.cfg
qemu/tests/virtio_mem_numa_basic.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/3510
virtio_mem_numa_basic: new auto case for basic numa test with two virtio-mem devices.
Creates a new case that boots up a guest with two numa nodes and two virtio-mem devices, it resizes several times the virtio-mem devices and checks its sizes.
ID: 2121669

virtio_mem_numa_basic: new auto case for basic numa test with two virtio-mem devices.

---

qemu/tests/cfg/block_during_io.cfg

The case purpose is to test shutdown or reboot guest during IO, Sometimes iozone stress test already completed before run the shutdown or reboot, so the case will error.
ID: 2085384

block_during_io: modify 'iozone' value to ensure the stress alive

---

qemu/tests/cfg/boot_nic_with_iommu.cfg

Boot nic with iommu_platform=on based on virtio iommu device
ID:2148335

boot_nic_with_iommu:Add one case to support viommu device

---

qemu/tests/cfg/nested_block_resize.cfg
qemu/tests/cfg/nested_block_resize_l1.cfg
qemu/tests/nested_block_resize_l1.py

The disk drive is unpredictalbe in latest RHEL.
It should get the right disk by serial instead
of using fixed sdb.
ID:2154787

nested_block_resize:fix hardcode disk drive

---

qemu/tests/block_hotplug_scsi_hba.py
qemu/tests/block_resize_unplug.py
qemu/tests/cfg/block_hotplug_scsi_hba.cfg
qemu/tests/cfg/block_resize_unplug.cfg
qemu/tests/cfg/fio_windows.cfg
qemu/tests/fio_windows.py

Select 3 cases to add memory-leak check steps:
1) fio_windows
2) block_resize_unplug
3) block_hotplug_scsi_hba
ID: 2128921

Add memory leak check for vioscsi IO/block_resize/hotplug tests

---

qemu/tests/virtio_mem_numa_basic.py

virtio_mem_numa_basic: changes docstring test description
There is a typo at the beginning of the case docstring that it needs to be updated to the correct case functionality
ID: 2153689

virtio_mem_numa_basic: changes docstring test description

---

qemu/tests/cfg/sve_suite.cfg
qemu/tests/sve_guest_suite.py
qemu/tests/sve_host_suite.py

Use the upstream git repo for testing is not stable, use the src.rpm for sve testing, the version is as same as the system.
ID: 2153676

sve_suite: Use kernel src.rpm for get_reg_list and sve_stress test

---

qemu/tests/cfg/chardev_tls_encryption.cfg

Chardev: Add tls expected msg with RHEL9 on s390x
ID: 2152902

Add tls expected msg with RHEL9 on s390x

---

qemu/tests/cfg/trim_support_test.cfg
qemu/tests/trim_support_test.py

Including 3 cases:
1. trim_support_test.with_discard_granularity.4K
2. trim_support_test.with_discard_granularity.256K
3. trim_support_test.with_discard_granularity.32M
id: 2137732

Add 3 new cases for trim with discard_granularity

---

qemu/tests/cfg/memhp_threads.cfg
qemu/tests/memhp_threads.py

Some old version rhel8 hosts will create a thread when adding one memory-backend-file default, but the thread creation is not due to the setting of the qemu source code.
We can see that before qemu7.1 on rhel9, adding a memory-backend-file default will not create one thread.
This was fixed after qemu7.1, anyway, Our test point is that after 7.1, the default value of the thread is equal to the number of smps, so as to achieve performance improvement.
So remove pre-7.1 default checks.
ID: 2152530

memhp_threads: Update check point for prealloc-threads default

---

qemu/tests/win_virtio_driver_update_by_installer.py

For some guests, need to restart os after updating drivers. And after os rebooted, need to start virtiofs service.
ID: 2156859

installer: start virtiofs after reboot guest

---

qemu/tests/cfg/block_with_iommu.cfg

As Iommu does not support for windows on AMD host.
Change this case only run on Intel CPU.
id: 2155736

Limit block_with_iommu test for windows on Intel CPU only

---

qemu/tests/cfg/boot_nic_with_iommu.cfg
qemu/tests/cfg/hotplug_unplug_nic_with_viommu.cfg
qemu/tests/cfg/migrate_nic_with_iommu.cfg

Change "clone_master" to "image_snapshot". The reason is that when limited the qemu version, the case needs to be canceled when the current qemu version does not meet the conditions, but the parameter "clone_master" has not completed the backup image before the case cancel, so the original image is deleted, resulting in an error
ID:2160312

Change "clone_master" to "image_snapshot"

---

qemu/tests/cfg/hotplug_mem_migration.cfg
qemu/tests/hotplug_mem_migration.py

Add memory and migration cross-test scenarios,
This scenario simulates the migration of hot-inserted memory after use, and then unplugs it after the migration is complete.
ID: 2152804

hotplug_mem_migration: Add memory and migration cross-test

---

provider/in_place_upgrade_base.py
qemu/tests/in_place_upgrade_legacy.py

ID:2160644
a.there' no related leapp version in the code, and while we need to debug issues, it's hassle so we need such a function to recorder it.
b.we need to know which version has been used.

Add related leapp veriosn & grubby version for debugging in the future

---

provider/win_driver_utils.py

In driver uninstallation test, it's needed to remove the repeated one when attaching more than one same devices to a guest.
ID: 2165314

win_driver_utils: remove the repeated inf file

---

qemu/tests/watchdog.py

Watchdog: switch -watchdog to -device since -watchdog is deprecated.
ID: 2155430

Add capability for watchdog since -watchdog is deprecated

---

qemu/tests/cfg/hotplug_virtio_mem.cfg
qemu/tests/hotplug_virtio_mem.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/3593
Creates a new auto case that boots up a guest and
hotplugs a memory object and a virtio-mem device
resizes the device and check the size is correct.
ID: 2127829

hotplug_virtio_mem: new virtio_mem hotplug auto case

---

generic/tests/cfg/iometer_windows.cfg
generic/tests/iometer_windows.py
qemu/tests/block_during_io.py
qemu/tests/block_hotplug_in_pause.py
qemu/tests/cfg/block_during_io.cfg
qemu/tests/cfg/block_hotplug_in_pause.cfg
qemu/tests/cfg/migration_with_block.cfg
qemu/tests/cfg/trim_support_test.cfg
qemu/tests/cfg/virtio_storage_in_use.cfg
qemu/tests/driver_in_use.py
qemu/tests/migration_with_block.py
qemu/tests/trim_support_test.py

For driver test, if driver verifier is enabled, to get memory leak, it's better to disable or uninstall driver after driver test.
ID:2154890

viostor: Add memory leak check steps with verifier enabled

---

qemu/tests/cfg/numa_hmat.cfg

numa_hmat: updates case initiator option
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3605
According to the qemu-7.2 rebase the initiator
value is not mandatory anymore fot the -numa node
option. Updates the case to provide only the
initiator to the -numa hmat-lb option when qemu version is higher than 7.2
ID: 2158423

numa_hmat: updates case initiator option

---

qemu/tests/cfg/x86_cpu_protection_key.cfg

ID: 2169083
Script 'x86_cpu_protection_key' only supports EPYC-Milan or newer cpu model.

x86_cpu_protection_key:Add unsupported 'EPYC-IBPB'

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_negative.py

nvdimm_readonly: updates nvdimm_readonly unarmed subcases
Changes for unarmed readonly variants the structure because the negative case should be the unarmed_off one, also updates the error message including the backslashes and changes the if condition since the search method was not working.
ID: 2169373

nvdimm_readonly: updates nvdimm_readonly unarmed subcases

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 2171277
AMD supports 'la57' on Genoa now.

x86_cpu_flags:extend cpu vendor for 'la57' test

---

qemu/tests/blockdev_mirror_cancel_ready_job_with_ioerror.py
qemu/tests/cfg/blockdev_mirror_cancel_ready_job_with_ioerror.cfg

Cancel a ready mirror job with ioerror
id:2170366

blockdev_mirror_cancel_ready_job_with_ioerror:Cancel a ready-ioerror job

---

qemu/tests/cfg/hotplug_mem_migration.cfg
qemu/tests/hotplug_mem_migration.py

The memory used by the guest is not equal for each numa. 
In order to equalize the pressure on each numa.
Update the pressure size with dynamic grabbing.
ID: 2172056

hotplug_mem_migration:Update the pressure size with dynamic grabbing

---

qemu/tests/x86_cpu_L3_cache.py

ID: 2170807
limit 'vcpu_maxcpus' pc-q35-rhel7.3.0 machine type when testing it on large cpus(>=256) host.

x86_cpu_L3_cache:limit 'vcpu_maxcpus' for old machine type

---

qemu/tests/cfg/blockdev_mirror_firewall.cfg

Omit driver deprecated warning in host_dmesg.log
id:2173502

blockdev_mirror_firewall:omit host dmesg check

---

qemu/tests/cdrom_block_size_check.py
qemu/tests/cfg/cdrom_block_size_check.cfg

It supports force parameter in blockdev-change-medium since qemu 7.1. 
Update the case to support it.
ID:2143876

Support blockdev-change-medium force parameter

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

1. Add new guest agent command 'guest-get-cpustats' to get guest CPU statistics, we can know the guest workload and how busy the CPU is.
2. Check number of cpus as well.
ID: 2166558

qemu_guest_agent: Add new api 'guest-get-cpustats'

---

provider/virtio_fs_utils.py
provider/win_driver_installer_test.py
qemu/tests/virtio_fs_multi_users_access.py
qemu/tests/virtio_fs_share_data.py
qemu/tests/win_virtio_driver_install_by_installer.py
qemu/tests/win_virtio_driver_installer_repair.py
qemu/tests/win_virtio_driver_update_by_installer.py

virtio_fs_utils: migrate the related virtio functions
from win_driver_installer_test.py to virtio_fs_utils.py
ID: 2152054

virtio_fs_utils: migrate the related virtio functions

---

generic/tests/cfg/lvm.cfg

The lvm relevant cases include LV creation, io, and clean sub-cases. 
The creation case uses serial on disk, but the other sub-cases 
do not use same serial on disk, it is invalid usage if LV needs to rescan disks.
It results in the lvm can not find LV.
ID:2069578

lvm:fix lvremove /dev/vg_kvm_test/lv_kvm_test failed issue

---

qemu/tests/block_multifunction_scale.py

Add separate 'in' item for both condition
ID:2168474

block_multifunction_scale:fix syntax error for 'or'

---

qemu/tests/cfg/qmp_event_notification.cfg
qemu/tests/qmp_event_notification.py

1.Fix connection method of watchdog device in Q35
2.Remove '-watchdog' option and use '-device' instead
ID: 2155958

qmp_event_notification: fix watchdog cases issue

---

provider/virtio_fs_utils.py
qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/cfg/virtio_fs_winfsp_test.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/virtio_fs_set_capability.py
qemu/tests/virtio_fs_share_data.py

1.For virtiofs service test, it's better to clear the virtiofs service at the end. For virtiofs device hotplug/unplug test, deleting virtiofs service will fail after unplugging the virtiofs device, so use the image backend method for it.
2. Do some code update when using functions in provided unit
1.Update parameters as creating/deleting virtiofs
service is using function unit that implemented
in provider/win_driver_installer_test.py instead.
2.Use stop virtiofs service instead of delete service
when creating multi virtiofs service
ID: 2156433, 2169907

virtio_fs:  virtiofs code update/add after including functions in provided unit

---

qemu/tests/cfg/numa_opts.cfg
qemu/tests/numa_maxnodes.py
qemu/tests/numa_opts.py

According to a product bug, multi-numa guests are
at risk of crashing unexpectedly, so add related checks.
ID: 2174338

numa_opts: Add serial log check point

---

qemu/tests/cfg/secure_img.cfg

SE: re-write zipl.config file to avoid the 'default' param will make this test failed
ID: 2168885

Re-write zipl file for secure guest

---

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg

qemu/tests/cfg/qemu_guest_agent_hotplug.cfg: change original
qemu-cli to json format "-device '{"id": "virtio_serial_pci0",
"driver": "virtio-serial-pci", "bus": "pcie-root-port-1", "addr": "0x0"}'"
ID: 2145141

qemu_guest_agent: json format change affect one command line

---

qemu/tests/cfg/boot_nic_with_iommu.cfg

According to product bug 2156876, QE changed the parameter to "device-iotlb=false" for rhel 7.9 guest.
ID:2179868

Change the parameter to "device-iotlb=false" for rhel 7.9 guest

---

qemu/tests/qmp_basic.py

After qemu-kvm-5.1, migrate_set_speed is deprecated
and replaced by migrate-set-parameters
ID: 2035434

qmp_basic: fix CommandNotFound

---

qemu/tests/boot_with_different_vectors.py

Change the match string, because after changing from raw format to json format,the exception error messages caught by automation different.So directly replace the matching condition with its error output without any escaping
ID:2178525

boot_with_different_vectors: Changed the match string

---

generic/tests/cfg/lvm.cfg
generic/tests/ioquit.py

1. The process is interrupted by forced killing.
There is no time delay before checking the image file.
Maybe there are processes still using the image file.
2. Remove the backup system image file setting.
The backup operation is not necessary for testing.
The image file may be restored by an unexpected image
file if other cases generate a backup file in advance.
ID:2169902,2176367

ioquit:fix adding timeout after killing process

---

qemu/tests/cfg/qmp_command.cfg

Supported 'query-stats' and 'query-stats-schema' command in the new version(qemu-kvm-7.1),old version not supported it.
ID: 2181141

qmp_command: fix 'query-stats' and 'query-stats-schema' version issue

---

qemu/tests/cfg/uefi_boot_from_device.cfg

Attach scsi-hd and scsi-cd to the same virtio-scsi-pci without bootindex, only one is listed in boot menu, the change in behavior was caused by a scsi bugfix. So attach scsi-cd to a new virtio-scsi-pci, and then the cdrom is listed in boot menu.
ID: 2180729

uefi_boot_from_device: attach scsi-cd to a new virtio-scsi-pci

---

qemu/tests/cfg/ovmf_check_efi.cfg

From the new edk2 build in rhel9.2, the string is "EDK II edk2***" instead of "EFI Development Kit***", so update the check string.
ID: 2181065

ovmf_check_efi: update efi string for windows guest

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

1. check the default value of smbios version
2. boot a vm with smbios-entry-point-type=32/64 and check smbios version, bios version, bios release date. make sure the bios release dates are equal between bios version and bios release date.
ID: 2181709

uefishell.check_smbios: add support for smbios-entry-point-type

---

qemu/tests/arm_gic.py
qemu/tests/cfg/arm_gic.cfg

QEMU can define vgic version for guest, this test case gives a value of gic-version, after the guest is starts, we should check the version in the guest and compare it with the qemu command line.
ID: 2176742

arm_gic: Check if guest GIC version can match the value in command line

---

qemu/tests/cfg/virtio_fs_security_label.cfg
qemu/tests/virtio_fs_share_data.py

ID: 2172739
For some file in virtiofs who has no xattr, when getting the xattr, virtiofs should not output any error info.

virtio_fs: test the empty list of xattr on virtiofs

---

qemu/tests/cfg/migrate_nic_with_iommu.cfg

image_snapshot doesn't support migrate scenario, so changed to another backup method. Also add support for windows guest minimal mem and windows guest path.
ID:2182744

migrate_nic_with_iommu:image_snapshot doesn't support migrate scenario

---

qemu/tests/cfg/uefi_pkg.cfg
qemu/tests/uefi_pkg.py

1. the number of meta_files is different in rhel8 and rhel9, update them
2. for amdsev and inteltdx json files, check that the 'mode' is 'stateless'
ID: 2183604

uefi_pkg.check_descriptor_meta_files: update the checkpoints

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

nvdimm_nvml: fix dependent packages typo and include cmake for x86_64
Fix the typo 'depends_pks' and include the installation of the epel-release inside the guest as well as cmake for x86_64.
ID: 2178166

nvdimm_nvml: fix dependent packages typo and include cmake for x86_64

---

qemu/tests/cfg/chardev_acpi.cfg

ID: 2183442
This device is deprecated since qemu 6.0, and removed
since qemu8.0.

chardev_acpi: limit qemu version for deprecated device 'tty'

---

qemu/tests/cfg/chardev_tls_encryption.cfg

ID: 2184088
RHEL9 has a different policy to connect TLS, which will show the different message.

x86:chardev_tls_encryption:limit host for gnutls' version

---

qemu/tests/cfg/qemu_img_check_fragmentation.cfg

filefrag is not supported on nfs, so add this
limitation for this case
id:2187880

qemu_img_check_fragmentation:add limitation for nfs

---

qemu/tests/cfg/qemu_img_extent_size_hint.cfg

This case only supported on localfs, so set the
limitation
id:2187879

qemu_img_extent_size_hint:only supported on localfs

---

qemu/tests/cfg/guest_iommu_test.cfg

Because VIRTIO_F_IOMMU_PLATFORM was supported by neither legacy nor transitional device, adding limiting condition accordingly.
ID: 2188192

guest_iommu_test: set disable_legacy and disable_modern to virtio device

---

qemu/tests/cfg/virt_firmware_basic_test.cfg
qemu/tests/virt_firmware_basic_test.py

1. If package python3-virt-firmware-tests has been installed, run the scripts under "/usr/share/python-virt-firmware/tests". Otherwise, run the scripts in virt-firmware repo.
2. peutils has been dropped from version 1.6, and it has been removed from python3-virt-firmware-tests. But it still in virt-firmware repo, so adding "test-pe.sh" to blacklist when testing with the repo accordingly.
ID: 2187097

virt_firmware_basic_test: update the test steps

---

qemu/tests/cfg/virtio_mem_numa_basic.cfg
qemu/tests/virtio_mem_numa_basic.py

virtio_mem_reboot: new virtio_mem reboot auto case
Creates a new auto case that boots up a guest, resizes several times the virtio-mem device, reboots the guest and checks if the size is correct.
ID: 2182968

virtio_mem_reboot: new virtio_mem reboot auto case

---

provider/sgx.py

Qmp section_size deprecated. Verify qmp epc size by calculating total epc size in sections instead
ID: 2188914
Signed-off-by: Zixi Chen zixchen@redhat.com

Update qmp epc size verification functions

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add new guest agent command 'guest-get-diskstats' to get guest disk statistics for Linux guests. This can be useful for getting io flow or handling IO fault, no need to enter guests.
ID: 2166559

qemu_guest_agent: Add new api 'guest-get-diskstats'

---

qemu/tests/cfg/uefi_check_log_info.cfg

boot_option.splash_time*: it was supported from rhel8.3, add the constraints

---

qemu/tests/cfg/smt_test.cfg

ID: 2189869
Opteron_G3 is deprecated on RHEL9 and RHEL9 guest can't boot up with it, so remove it.

smt_test: limit guest version for 'Opteron_G3'

---

qemu/tests/enospc.py

The wrong bytes-like object is required, not 'str' result in the clean operation is broken.
ID:2182994

enospc:fix resource clean issue

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm_negative.py

nvdimm_readonly: updates unarmed_off error message and limits vm memory 
Updates unarmed_off subcase error message and applies vm memory limit
to be the same as the nvdimm device. Also changes back to the regex
search for the error messages.
ID: 2178025

nvdimm_readonly: updates unarmed_off error message and limits vm memory

---

qemu/tests/cfg/dump_guest_core.cfg

ID:2188907
1.backup the file before the test and restore it after the test
2.make the pre_command modify the config file as expected

dump_guest_core: backup config file and modify pre_command

---

qemu/tests/cfg/bitmaps_merge_with_nospace.cfg

Add backend limitation to only localfs
id:2193331

bitmaps_merge_with_nospace:limit to localfs

---

qemu/tests/cfg/virtio_mem_numa_basic.cfg
qemu/tests/virtio_mem_numa_basic.py

virtio_mem_migration: new virtio_mem migration auto case
Adapts existing numa virtio_mem auto case to cover a new one
that boots up a guest in source and destinations hosts,
migrates from src to dst, finally resizes the virtio-mem
devices and check the size is correct.
ID: 2184289

virtio_mem_migration: new virtio_mem migration auto case

---

qemu/tests/numa_memdev_options.py

numa_memdev_options: align auto case with the numa_maps format output
Since qemu8 the memory preferred policy accepts a set of numa nodes.
Updates the numa_maps query to be compatible with this new 'many'
preferred policy and the previous supported one.
ID: 2189892

numa_memdev_options: align auto case with the numa_maps format output

---

qemu/tests/cfg/iommu_pcie_pci_bridge.cfg

Launch a guest with iommu, and all supported devices should insert into pcie-pci-bridge bus.
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3659
ID: 2185698

Boot guest with iommu and devices insert into pcie-pci-bridge

---

qemu/tests/cfg/nic_acpi_index.cfg

1. Since it had been support on downstream from qemu-kvm-8.0.0, so add support for it on the q35 device.
ID: 2203643

Add support for option "acpi-index" on q35 device

---

qemu/tests/cfg/multi_disk_random_hotplug.cfg
qemu/tests/multi_disk_random_hotplug.py

The previous mechanism attached 200 disks to the respective controller.One disk allocates one controller. It does not match real usage.
The new mechanism asks for attaching 200 disks under one controller. It reduces the number of disks to 64 for the case one disk to allocate one controller.
ID:2186098

multi_disk_random_hotplug: change disks attaching mechanism

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

ID: 2188874
1. rhel8 guest kernel not suppor '-o posix_acl', so remove rhel8 guest.
2. for virtiofsd on rhel9, --no-killpriv-v2 is set to a default one, so no need to add it additionally.
3. generic/070 generic/650 need to work with ' --inode-file-handles=prefer' for nfs backend, so add them to blacklist in common tests.

virtio_fs: some updates on xfstests

---

qemu/tests/cfg/qemu_guest_agent.cfg

Since BLACKLIST_RPC has been replaced with BLOCK_RPCS after rebasing qemu to 7.2, change relevant code in automation script.
ID: 2165442
Signed-off-by: demeng demeng@redhat.com

qemu_guest_agent: BLACKLIST_RPC has to replaced with BLOCK_RPCS

---

qemu/tests/cfg/qemu_guest_agent.cfg

Add param 'discard_granularity=33554432' to scsi-hd 
for qga command "guest-fstrim"
ID: 2207829

qemu_guest_agent: Add param 'discard_granularity' to scsi image

---

qemu/tests/cfg/migrate_nic_with_iommu.cfg
qemu/tests/cfg/nic_hotplug.cfg

1.According to Bug 2156876 Comment 12 to disable option "dev-iotlb" for rhel 7.9 guest.
ID:2203756

For rhel 7.9 guest disable option "dev-iotlb"

---

qemu/tests/cfg/qemu_guest_agent.cfg

QGA: limit RHEL and qemu version for check_get_cpustats
ID: 2178927

limit test version of check_get_cpustatus

---

qemu/tests/cfg/netperf_udp_perf.cfg

GCC 10 use -fno-common as defaults, so add CFLAGS = -fcommon to make
Signed-off-by: Wenli Quan wquan@redhat.com
id:1938657

netperf_udp_perf: add CFLAGS = -fcommon to a make

---

generic/tests/cfg/jumbo.cfg

1.In the past we confused with the minimum datagram size that host must
be prepared to accept. 68 bytes is a minimum without further
fragmentation instead of must be able to receive a datagram.
ID:2208095

Change the minimum mtu size from 68 to 576

---

qemu/tests/qemu_guest_agent.py

QGA: From RHEL.9.3, br_netfilter is not loaded by default, so there will be a message information in serial, there will be conflict when checking the bridge info by using serial.
ID: 2188549

Modify serial session to session for gagent_check_get_interfaces

---

qemu/tests/cfg/x86_cpu_flags.cfg

ID: 2211798
The developer thinks this is not one valid test senario, and the related bug has been closed as WONTFIX, so remove it.

x86_cpu_flags:remove the invalid test scenario

---

generic/tests/cfg/boot_vm_in_hugepage.cfg
qemu/tests/cfg/hugepage_specify_node.cfg
qemu/tests/hugepage_specify_node.py

Currently, hugepage_specify_node can only be tested 
with the host's default huge page size.
Add test scenarios so that users can specify
the huge page size they want to test.
ID: 2178867

hugepage_specify_node:add set specify hugepage test

---

provider/win_driver_installer_test.py

Dump-guest-memory will raise a warning when VM cpu>32, it is expected behavior.
ID:2211274

win_driver_installer_test:fix a bug in fwcfg_test

---

generic/tests/trans_hugepage_swapping.py

trans_hugepage_swapping: removes vm create and updates count value
Removes vm create invocation to avoid a not-needed second start
of the guest that will use the same os image leading the case
to fail. Also updates the memory value for 'count', setting it to MemFree
in order to avoid an out of memory, when swap size is not enough.
ID: 2207558

trans_hugepage_swapping: removes vm create

---

qemu/tests/cfg/x86_cpu_model.cfg

ID: 2203027
QEMU8.0 support new cpu model 'SapphireRapids' and alias of cpu model 'SapphireRapids-v1'.

x86_cpu_model:add new cpu model 'SapphireRapids'

---

generic/tests/nicdriver_unload.py

By default, timeout of session.cmd_output_safe is 60, when `random.randint(10, 60)` returns 60s, cmd_output_safe may time out, so the timeout value should base on the `random.randint`.
ID: 2213379

nicdriver_unload: `cmd_output_safe` timeout based on `random.randint`

---

qemu/tests/cfg/qemu_img_lock.cfg
qemu/tests/qemu_img_lock_reject_boot.py

If `reject_boot_same_img_twice` variant is used there may be timing issue between time of writing of the lock message into the log file and the check for presence of the error lock message.
1) This PR introduces timeout to avoid this problem. Observed timing issue is roughly 200 milliseconds, so the default value of timeout set to 5 seconds should suffice any possible scenario. 
2) PR also adds `ignore_status=True` for `process.run` method, so misleading exception is not raised in case error message is not found and correct logic to handle this situation is used.
ID: 2208479

qemu_img_lock_reject_boot: avoid timing issues

---

qemu/tests/blockdev_snapshot_chains.py

In original design, miss this scenario: we define an image format for base image that is different from the --imageformat we defined in kar cmdline. In this scenario, when we do some rebase for snapshot images, we will use an incorrect imageformat for the base image, which will lead to "can't find baking image" error when start guest with snapshot images.
id:2213432

blockdev_snapshot_chains:update the method to get base format

---

qemu/tests/cfg/hotplug_mem_stress_ng.cfg

hotplug_mem_stress_ng: updates stress-ng repository source
Updates stress-ng repository to the github source, as the one from ubuntu seems to be no longer available.
ID: 2215785

hotplug_mem_stress_ng: updates stress-ng repository source

---

qemu/tests/cfg/virtio_fs_supp_group_transfer.cfg
qemu/tests/virtio_fs_supp_group_transfer.py

ID: 2172408
Signed-off-by: Houqi (Nick) Zuo <hzuo@redhat.com>

virtio_fs_supp_group_transfer: add a new test case

---

qemu/tests/cfg/numa_negative.cfg

numa_negative.threads_test: includes test_negative_thread cfg param
Include the test_negative_thread configuration param to avoid
setting the number of vcpu_threads to 1 in qemu_vm avocado-vt.
ID: 2217797

numa_negative.threads_test: includes test_negative_thread cfg param

---

qemu/tests/cfg/block_detect_zeroes.cfg

Avoid the case name being the same as the top variant.
ID:2219519

block_detect_zeroes:fix case name

---

qemu/tests/block_transfer_parameters_check.py
qemu/tests/cfg/block_transfer_parameters_check.cfg

Add block transfer parameters check test case

---

qemu/tests/cfg/virtio_fs_group_permission_access.cfg
qemu/tests/virtio_fs_group_permission_access.py

virtio_fs_group_permission_access: add a new test case

---

provider/in_place_upgrade_base.py
qemu/tests/in_place_upgrade.py

IPU: adjust steps for getting rhsm pool id while doing IPU with rhsm

---

qemu/tests/in_place_upgrade_legacy.py

In_place_upgrade_7to8:remove get data step for rhel7torhel8

---

qemu/deps/nested_hyperv/hyperv_env.ps1
qemu/deps/nested_hyperv/hyperv_run.ps1
qemu/deps/nested_hyperv/hyperv_sets.ps1
qemu/tests/cfg/nested_hyperv_on_kvm.cfg
qemu/tests/nested_hyperv_on_kvm.py

Signed-off-by: lixuemin2016 <xuli@redhat.com>

add basic nested hyperv on kvm test case

---

qemu/tests/virtio_fs_share_data.py

The re-instantiation of the class is theoretically not required. 
Use the same instantiation for setup and cleanup.
ID: 2208415

virtio_fs:correct nfs cleanup usage

---

qemu/tests/cfg/qemu_guest_agent.cfg

QGA: limit RHEL and qemu version for check_get_diskstats
ID: 2214946

limit test version of check_get_diskstatus

---

qemu/tests/cfg/dump_guest_core.cfg
qemu/tests/dump_guest_core.py

ID:2217847
On ppc64le, the rhel9 guest is supported on rhel8 host, need to remove those steps, which try to open file via host's kernel related packages because they're not matched

Dump:update steps for dump test for rhel9 guest on rhel8 host

---

qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Due to the characteristics of the product,
generic/568 is not applicable to the arm platform. 
So remove it.
ID: 2222151

virtio_fs:remove xfstest + nfs generic/568 on aarch64

---

qemu/tests/cfg/secure_execution.cfg
qemu/tests/secure_execution.py

Secure_execution: add test cases for both positive and negative to check
if SE guest could get 247 for maximum vCPU and the error message is
expected when it get 248 vCPUs
ID: 2209269

Add test cases to check maximum vCPUs with SE guest

---

qemu/tests/blockdev_commit_firewall.py
qemu/tests/cfg/blockdev_commit_firewall.cfg

Remove nbd image in clean_images() to keep an clean
test env
id:2216428

blockdev_commit_firewall:remove nbd image after test

---

qemu/tests/cfg/virtio_mode.cfg
qemu/tests/virtio_mode.py

virtio_mode: updates PCI patterns according to the numerical ID
Updates the case logic, checking the numerical ID of the PCI devices
instead of the full name, that could be updated without notice.
In order to support 0.9 and 1.0 virtio devices, the pattern now
contains both IDs.
ID: 2222179

virtio_mode: updates PCI patterns according to the numerical ID

---

qemu/tests/cfg/multi_disk_random_hotplug.cfg

There is no scsi bus when boot OS with virtio_blk. 
It needs to adding scsi bus before hotplug scsi_hd disk.
ID:2203001

multi_disk_random_hotplug:fix scsi bus miss issue

---

qemu/deps/block_device/libblkio_release_test.sh
qemu/tests/block_libblkio_release.py
qemu/tests/cfg/block_libblkio_release.cfg

It will verify the source code of
libblkio is working and test the main
driver virtio-blk-vhost-vdpa
ID:2222155

Add libblkio release test

---

qemu/tests/cfg/nmi_bsod_catch.cfg

windbg install path is different between x64 and i386, so update the configuration file to fix the error.
ID:2218864

nmi_bsod_catch: fix a bug on win10.i386

---

qemu/tests/cfg/device_bit_check.cfg
qemu/tests/device_bit_check.py

Updates the case logic using numerical ID as
test point due to name will be changed without
notice. In order to support 0.9 and 1.0 virtio
devices, the pattern now contains both IDs.
The ids of device may refer to
https://github.com/vcrhonek/hwdata/blob/master/pci.ids#L24039-L24058
ID:2217301

device_bit_check:fix pci search pattern

---

qemu/tests/cfg/qsd_blockdev_check.cfg

Explicitly declare the image format.
Avoid mismatches with default value.
ID:2210617

qsd_blockdev_check:fix qcow2 format support

---

qemu/tests/cfg/hotplug_mem_negative.cfg

Update ipa limit search criteria
ID:2229107

hotplug_mem_negative:Update ipa limit search criteria

---

qemu/deps/win_serial/VirtIoChannel_guest_recieve.py

Fixup inspekt checking failures in the latest python 3.9 job 
Use isinstance() for comparing types
Signed-off-by: Misbah Anjum N <misanjum@linux.vnet.ibm.com>

Fix inspekt checking failures for Python 3.9

---

qemu/tests/cfg/boot_from_virtiofs.cfg

Different arch use different console, need to update kernel_params on different arch.
ID: 2215182
Signed-off-by: Sibo Wang siwang@redhat.com

boot_from_virtiofs: Update console for different arch

---

qemu/tests/ctrl_vlan.py

Virtual_network: since there's output in console and infulence the test result,
use the safe way to get the cmd output
ID: 2229911

Update the way to get cmd_output

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/single_driver_install.cfg
qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/cfg/virtio_fs_multi_users_access.cfg
qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/cfg/virtio_fs_security_label.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/cfg/virtio_fs_winfsp_test.cfg
qemu/tests/cfg/win_sigverif.cfg
qemu/tests/cfg/win_virtio_driver_install_from_update.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

ID: 2211641
To make the test more flexible, use global variable
to instead of local variable for guest memory size.

virtio_fs: use global variable to define guest  memory size

---

qemu/tests/virtio_serial_hotplug_port_pci.py

Because the hotplug logic did not show up the correct place,
cause this kind of problem. Change the strategy of hotplugging pci
ID: 1114

virtio_port_hotplug.hotplug_port_pci: No free matching bus error

---

qemu/tests/live_backup_add_bitmap.py

`system_shutdown` will use qmp command to shut down the guest, but when guest is still booting, sometimes it may ignore the `POWERDOWN` event, this causes the guest failed to down. To safely shut down the guest, send a shell command by guest itself would be better.
ID: 2229869

live_backup_add_bitmap: Replace system_shutdown with graceful_shutdown

---

qemu/tests/cfg/dump_guest_core.cfg
qemu/tests/dump_guest_core.py

As there is a conflict between the param and the function, rename check_vmcore_file to check_vmcore.
ID: 2229116
Signed-off-by: Wenkang Ji <wji@redhat.com>

dump_guest_core: Update the params name to fix conflict

---

provider/win_driver_utils.py

ID: 2230246
When running some tests with a memory leak, sometimes it will fail after enabling the driver,
it's better to make sure the driver is really in
running status and then do the next testing.

win_driver_utils: check driver status after enable/install drivers

---

qemu/tests/cfg/fio_perf.cfg

ID: 2217203
From RHEL8.8, virtiofsd support allow_direct_io option.

fio_perf: add allow_direct_io option for RHEL8.8 and later

---

qemu/tests/cfg/block_libblkio_release.cfg

skip aarch64 and s390x in this case.
ID:2230227

libblkio_release_test: Ignore the case from aarch64 and s390x

---

qemu/tests/cfg/block_hotplug_check.cfg
qemu/tests/pci_hotplug_check.py

Updates the case logic using numerical ID, as test point due to name will be changed without notice. In order to support 0.9 and 1.0 virtio devices, the pattern now contains both IDs.
ID: 2230552
Signed-off-by: Sibo Wang siwang@redhat.com

block_hotplug_check:Update pci search pattern

---

qemu/tests/cfg/qsd_blockdev_check.cfg
qemu/tests/cfg/qsd_export_vhub_check.cfg
qemu/tests/cfg/qsd_object_check.cfg
qemu/tests/cfg/qsd_pidfile_check.cfg
qemu/tests/cfg/qsd_qmp_cmd_check.cfg

Disable luks format test for qsd cases:
qsd_blockdev_check,qsd_export_vhub_check,
qsd_object_check,qsd_pidfile_check,qsd_qmp_cmd_check
ID:2208501,2208500,2208502,2208503,2208497

Disable luks format test for qsd relevant cases

---

qemu/tests/virtio_fs_share_data.py

ID: 2230244
For windows guest, case insensitive should also works with windows app, such as md5sum.

virtio_fs: use md5sum cmd to check case insensitive

---

qemu/tests/cfg/hotplug_memory_repeat.cfg
qemu/tests/hotplug_mem_repeat.py

For the arm platform, there are two smallest mem block sizes.
Section size must be at least 128MB for 4K and 16k base page size config.
Section size must be at least 512MB for 64K base
Update the block size mem acquisition method by the current
guest base page size.
ID: 2229699

hotplug_mem_repeat:Update size_mem acquisition method

---

generic/tests/cfg/vlan.cfg
generic/tests/vlan.py
qemu/tests/cfg/ctrl_vlan.cfg
qemu/tests/ctrl_vlan.py

As the result of Win10+ guest will not support the netsh netkvm command, so use powershell to replace it.
ID:1231

Set vlan id on Windows guest using powershell

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Upstream changes the code to match a regular expression,  so we need to update the generic_blacklist format in virtio_fs_share_data and virtio_fs_share_data_multi_backend.
refer to commit: https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/commit/?id=6d63f23987a629b4f7dd6e57e5b67ba37a3b742e
ID：2237222
Signed-off-by: Sibo Wang siwang@redhat.com

Update generic blacklist format

---

qemu/tests/cfg/virtual_nic.cfg

According the test result, DummyCMD.exe command has no longer support on the windows guest, so use the tools fsutil that come with Windows
ID:1322

Change the command that creates files in Windows guests

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Due to generic/451 writes a file directly, add it into blacklist in cache=always scenario
ID: 2231253
Signed-off-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

Add generic/451 to blacklist in cache=always scenario for xfstest

---

generic/tests/vlan.py

QE sorry for not noticing that linux guest does not require this parameter, so sent a new patch to fix this regression issue.
ID:1364

Fix regression issue introduced by 9a707f0

---

qemu/tests/win_virtio_driver_installer_uninstall.py

ID: 2233424
Eventhough driver was uninstalled by installer, the return for driverquery cmd still get correct return. Therefore, it's better to check the driver status by checking if it has inf file.

win_driver_install_uninstall: update uninstalled check method

---

qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg

Virtio_fs: since we could set up memory-backend without numa/hugepage, remove workaround for virtio_fs ralated test cases on s390x
ID: 2213759

Updated virtio-fs test cases on s390x

---

qemu/tests/cdrom.py

Test tray close/open should use tray-relevant
commands directly instead of
depending on auto auto-close feature. Due to this
feature is not always supported.
ID:2229667

cdrom:fix tray close behavior

---

qemu/tests/cfg/check_cvq_event.cfg
qemu/tests/check_cvq_event.py

Add a new case to check if the QEMU is able to intercepting CVQ with SVQ, and can send a NIC_RX_FILTER_CHANGED event normally.
ID:1340

Check if QEMU is able to check CVQ by issuing rx filter event

---

qemu/tests/cfg/numa_prealloc_threads.cfg
qemu/tests/numa_prealloc_threads.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/3756
numa_prealloc_threads: boot guest with thread-context and cpu-affinity
Creates a new auto case that boots up a guest with a thread-context
object with a cpu-affinity configured. Verify the cpu-affinity is
correct and cannot be changed with sandbox enabled.
ID: 2224513

numa_prealloc_threads: boot guest with thread-context and cpu-affinity

---

qemu/tests/cfg/vdpa_pxe_boot.cfg
qemu/tests/vdpa_pxe_boot.py

This scenario from a product bug, we only need to check the guest if can works well when pxe booting with vDPA nic.
ID:1342

PXE booting test with vDPA nic

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Command 'netsh' was not usable for more and more windows version, so use 'wmic' to replace it.
ID: 1216

qemu_guest_agent: use command wmic replace netsh

---

generic/tests/nicdriver_unload.py

Firstly, changed the sleep time's location and range, 1~5 seconds is enough from the feature owner's perspective. And it don't need to execute sleep inside guest,since serial dirty log will tigger automation errors,it is enough to add it during code execution.Secondly, the case check point is guest nic can recover traffic after unload/load nic driver,so delete the down and up interface via ifconfig command.
ID:1426

nicdriver_unload:Rewrite the testing process

---

qemu/tests/cfg/vdpa_ipv6_connect_testing.cfg
qemu/tests/transfer_file_over_ipv6.py

Add a new case to support vdpa ipv6 connect testing,since the vdpa nic can not got an available ipv6 address at the current stage.Therefore I used the stable net id and random guest it to consist of a ipv6 address.
ID:1347

vDPA IPv6 connect testing

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Some tests of xfstest not support mmap with cache=none.
ID: 1443

Add some tests to blacklist in cache=none scenario for xfstest

---

qemu/tests/cfg/hv_tlbflush.cfg

When detach hv_tlbflush, also need detach hv_tlbflush_ext as well.
Since hv_tlbflush_ext depends on hv_tlflush.
ID: 1397
Signed-off-by: Peixiu <phou@redhat.com>

Fix the hv_tlbflush_ext dependency hv_tlbflush issue

---

qemu/tests/multi_nics_verify.py

Because of the default wait time is 240 seconds but sometimes rebooting will take long time, which will trigger login timeout expired errors, so extend this time to reduce the reproduced rate.
ID:1424

extend time to wait for login to succeed after rebooting

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

Since in write-back cache mode writes go to
cache only, limited to cached situations.
ID: 1423

virtio_fs:Update writeback filter conditions

---

qemu/tests/cfg/hotplug_memory_repeat.cfg

We hit unaligned hotplug range issue, on rhel8.
In older versions of the kernel it requires a larger address space. 
So update arm hotplug mem block size.
ID: 1454

hotplug_memory_repeat:Update arm hotplug mem block size

---

qemu/tests/cfg/enospc.cfg
qemu/tests/enospc.py

It uses a hard code disk drive letter,
The IO causes data corruption sometimes due
to disk order is unexpected.
ID:1447

enospc:fix hard code disk drive letter

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

there is debug output of running qemu-ga.exe as isa-serial. have to send a 'ent after start qemu-ga.exe so that program can catch the correct output to determin whether case is well.
ID: 1439	

qemu_guest_agent: adjust new output of using isa-serial

---

qemu/tests/cfg/block_detect_zeroes.cfg

It only uses discard=unmap in current testing.
Adding discard=ignore to expand the test scope.
ID:1331

Adding discard=ignore in block_detect_zeroes testing

---

qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_update_by_installer.py

Driver installer support restore network configuration after upgrade driver, so add a check point for it.
ID: 1386

Installer test: add network static configuration test

---

qemu/tests/cfg/in_place_upgrade.cfg
qemu/tests/cfg/in_place_upgrade_legacy.cfg
qemu/tests/in_place_upgrade.py
qemu/tests/in_place_upgrade_legacy.py

Leapp: add device_cio_free.service check after guest finish upgrading,
reference to Bug 2032953 - s390x: leapp post-upgrade doesn't enable
"device_cio_free.service" unit, which is required on Z
ID: 2231264

Add device_cio_free.service check after guest finish upgrading

---

qemu/tests/cfg/hotplug_mem_migration.cfg

Enable dirty ring test on x86_64 and aarch64
ID: 1474

hotplug_mem_migration:enable dirty ring test

---

qemu/tests/cfg/netperf_stress_test.cfg
qemu/tests/netperf_stress.py

netperf_stress: limit this test to smp <= 32 
reset to 32 when the netperf server's smp is larger than 32.
(guest will get half of the total number of vcpus of the host)
ID: 1377
Signed-off-by: Wenkang Ji wji@redhat.com

netperf_stress: limit this test to smp <= 32

---

qemu/tests/cfg/boot_from_virtiofs.cfg

Currently, in avocado-vt, it will check parameter
firmware_path and images, if these 2 paremeters are not none, then add firmware related qemu command line.
So add a disk to fix current bug in tp-qemu
ID:1450

boot_from_virtiofs: add a disk to workaround ovmf fd generation defect

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

1. the latest change is to add two new sebools instead of using `setenforce 0`. those are two specific selinux boolean values.
2. add the checkpoint for checking user root.
ID: 1127

qga: adjust new sebools to 'gagent_ssh_public_key_injection'

---

qemu/tests/cfg/multi_disk.cfg

THe /dev/sg* not only sg devices but also other devices in host. e.g. /dev/sg0  /dev/sgx_enclave  /dev/sgx_provision  /dev/sgx_vepc It should filter out sg devices only.
ID：1483

multi_disk:fix vm creation command failed

---

qemu/tests/cfg/unplug_block_during_io_reboot.cfg

During IO stress test (dd cmd), the waiting time is too long to check the status of stress, so shrink the waiting time from 30s to 10s.
ID:1531
Signed-off-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

unplug_block_during_io_reboot: Shrink the waiting time when stress test

---

qemu/tests/cfg/block_with_share_rw.cfg

THe /dev/sg* not only sg devices but also other devices in host. e.g. /dev/sg0  /dev/sgx_enclave  /dev/sgx_provision  /dev/sgx_vepc It should filter out sg devices only.
ID:1484

block_with_share_rw:fix vm creation command failed

---

qemu/tests/cfg/block_performance_test.cfg

It consumes too much memory resulting in VM boot
failing if there are too many CPUs in the VM.
The test point of this case is irrelevant to the CPU. limit the CPU number and increase memory usage
avoid to VM boot failing out of memory.
ID:1518

block_performance_test:fix resource usage

---

generic/tests/cfg/pxe_boot.cfg

Without bootindex in the nic command line, the bios will use the default boot entries for pxe booting, but if the pxe entry is not the first entry, then the guest will directly boot into the OS.
ID: 1475

fix(virtual-network): Use bootindex instead of boot order

---

qemu/tests/cfg/watchdog.cfg
qemu/tests/watchdog.py

The Q35 machine type chipset comes with unconditional support for a 'TCO' watchdog
ID: 1462

watchdog.cfg: support for a 'TCO' watchdog

---

qemu/tests/cfg/numa.cfg
qemu/tests/numa_consistency.py
qemu/tests/numa_stress.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/3792
numa_consistency: updates case to numa node memory binding
In order to do a proper memory allocation, this case is updated,
to bind the qemu-kvm process to the NUMA node with more free
memory. After that, a memory allocation process is started for
every node inside the vm and it's checked the memory has increased
in the binded host NUMA node.
ID: 1398

numa_consistency: updates case to numa node memory binding

---

generic/tests/cfg/pxe_boot.cfg

Based on the developer comment forbidden PXE tests, since igb is not supported yet in BIOS.
ID: 1544

Forbidden pxe_boot test for igb nic

---

qemu/tests/cfg/numa_prealloc_handling.cfg
qemu/tests/numa_prealloc_handling.py

numa_prealloc_handling: Basic preallocation handling
Creates a new case that measures the time that needs QEMU
to preallocate the memory with and without thread-context.
ID: 1502

numa_prealloc_handling: Basic preallocation handling

---

generic/tests/cfg/pxe_boot.cfg

No need cdroms in the case, so set cdroms to null string.
ID: 1570

pxe_boot: disable cdroms in the test

---

provider/virtio_fs_utils.py
qemu/tests/cfg/virtio_fs_subtest_during_io.cfg
qemu/tests/virtio_fs_subtest_during_io.py

stop_con_vm_during_virtiofs: add a new testcase

---

qemu/tests/bridge_qinq.py

Since there is commit fixed the packet size check and made it more strict about the packet size,based on this commit QEMU handled the ethernet FCS packets which is 4-byte long, so the maximum size should be subtracted 4.This surfaced a problem in the test case that the guest sends a packet larger than 1522 bytes without setting the LPE flag.A QinQ packet has a 22-byte header, the default MTU in VLAN is 1500, and an ethernet FCS is 4-byte long as I described earlier so the maximum packet size will be 22 + 1500 + 4 = 1526, which is 4-byte larger than 1522 bytes.So the fix is make the outer VLAN MTU greater to let the driver set the LPE flag.
ID: 1556

Configure outer VLAN MTU to 1504 for e1000e device on qemu-8.1

---

generic/tests/dd_test.py

dd_test:login again to avoid previous session expired

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Currently, VSS DLL can only report an error as a response to the VSS commands. 
This is significantly limiting the ability to debug the VSS DLL.
So this case involved exe program 'Deviewconsole.exe' to check the log info.
ID: 1240

qemu-guest-agent: Add new test case for checking VSS DLL

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Compare symbolic link information in the Linux host and
guest to check if they are consistent.
ID: 1564

virtio_fs:compare symbolic link info in host and guest

---

qemu/tests/cfg/bigfile_transfer_over_ipv6.cfg
qemu/tests/transfer_file_over_ipv6.py

Since from rhel9,ipv6 link local's scp syntax has been changed. So QE sent a MR to fix this problem.
ID: 1530

Change the ipv6 link local syntax for rhel9

---

qemu/tests/cfg/dump_guest_core.cfg
qemu/tests/dump_guest_core.py

Increase timeout duration to prevent issues when the desired condition
is not fulfilled within the given time frame.
ID: 1343
Signed-off-by: Wenkang Ji [wji@redhat.com](mailto:wji@redhat.com)

dump_guest_core: Handle timeout condition in wait_for function

---

qemu/tests/cfg/virtio_fs_support_win_fs.cfg
qemu/tests/virtio_fs_support_win_fs.py

virtiofs_supp_for_fs: add a new test case

---

qemu/tests/cfg/multi_disk.cfg
qemu/tests/multi_disk.py

Because the names of disks in different host environments are different, we need to dynamically modify the 'indirect_image_blacklist'. Check disks before and after scsi_debug is created, and update the 'indirect_image_blacklist' based on newly added disks.
ID: 1361
Signed-off-by: Sibo Wang [siwang@redhat.com](mailto:siwang@redhat.com)

multi_disk.virtio_scsi.passthrough: Dynamically update blacklist

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Simulate the scenario where direct IO and buffered IO are interleaved. 
When the buffered IO and direct IO sizes are different, 
product issues are more likely to occur.
ID: 1560

virtio_fs: stress test add different bs size

---

qemu/tests/cfg/virtio_fs_map_uid_gid.cfg
qemu/tests/virtio_fs_map_uid_gid.py

When running virtiofsd as non-root,
map a range of UIDs from host to virtiofsd user namespace.
ID: 1490

virtio_fs: map a range of UIDs/GIDs from host to namespace

---

qemu/tests/cfg/nic_acpi_index.cfg
qemu/tests/cfg/nic_hotplug.cfg

Based on the current framework, the guest source image will be removed if continue to used the old way to backup image when the test case be cancel due to the qemu version. Therefore changed to the current way.
ID:1696

Change the way of backup image

---

qemu/tests/cfg/virt_firmware_check_phys_bits.cfg
qemu/tests/virt_firmware_check_phys_bits.py

The memory encryption bit is 5 on Milan and it's 6 on Genoa, so get it dynamically instead of hard-coding.
ID: 1722

virt_firmware_check_phys_bits: get memory encryption bits dynamically

---

qemu/tests/cfg/numa_opts.cfg

numa_opts: increase memory size for 128 nodes variant
When booting a VM with 128 NUMA nodes, ensure this one
has at least 128M per node for the all RHEL versions.
Also disables this case for RHEL 9.2
ID: 1589

numa_opts: increase memory size for 128 nodes variant

---

qemu/tests/cfg/virt_firmware_check_phys_bits.cfg
qemu/tests/virt_firmware_check_phys_bits.py

enable dynamic mmio window on seabios from rhel9.4, so add support for seabios.
ID: 1755

virt_firmware_check_phys_bits: add support for seabios

---

qemu/tests/cfg/hugepage_mem_stress.cfg
qemu/tests/hugepage_mem_stress.py

hugepage_mem_stress: includes verify_guest_dmesg
This commit includes verify_guest_dmesg
as cfg param to avoid any possible failure.
ID: 1760

hugepage_mem_stress: includes verify_guest_dmesg

---

generic/tests/cfg/trans_hugepage.cfg

trans_hugepage.base: enable transparent_hugepages before test
Enables THPs before starting the test to avoid any possible
failure in case it had been disabled before.
ID: 1757

trans_hugepage.base: enable transparent_hugepages before test

---

provider/win_driver_installer_test.py
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_update_by_installer.py

Define balloon test object together with execution. And in the driver
function loop, move balloon test to the top to avoid possible conflicts.
ID: 1727

win_virtio_driver_installer: update balloon test

---

qemu/tests/qemu_guest_agent.py

The old logic of choosing vcpu to offline is hard code. 
change it to get the proper vcpu number.
ID: 1749

qemu_guest_agent: adjust new logic for case "check_set_vcpus"

---

qemu/tests/cfg/virtio_fs_share_data.cfg

When cache=None condition, fio test takes more time.
ID: 1751

virtio_fs: extend fio test time when cache is set to None

---

qemu/tests/cfg/sve_suite.cfg

from kernel commit 17da79e009c376523ab977a351a2a69bad8e847b, the get-reg-list self test is moved from 'aarch64' to parent directory, so fix the issue to execute it.
ID: 1729

fix(sve): get-reg-list test is move to parent directory

---

qemu/tests/cfg/uefishell.cfg

The default version of smbios is 3.0 from RHEL-9.4, so update it.
ID: 1862

uefishell.check_smbios: update the default version of smbios

---

qemu/tests/virtio_fs_share_data.py

Currently,folder_link's value will be reset, it will
introduce an error,so update the parameter's name to
fix the error.
ID: 1848

virtio_fs: fix the symbolic path on host

---

qemu/tests/cfg/numa_node_affinity.cfg
qemu/tests/numa_node_affinity.py

numa_node_affinity: creates new node-affinity test case
Creates a new case that tests the node-affinity property.
For it, boots up a guest with a valid node set, checks
the cpu-affinity status and finally verifies that the
property is not readable.
ID: 1789

numa_node_affinity: creates new node-affinity test case

---

generic/tests/cfg/trans_hugepage.cfg
generic/tests/trans_hugepage_defrag.py

Depends on https://github.com/autotest/tp-qemu/pull/3933
trans_hugepage.defrag: re-design test case
Changes test case functionality in order to make use
of the thp_fragment tool, this way the defragmentation
could be properly tested. Keeps the original comparison
of THPs allocated w/wo defrag enabled.
ID: 1419

trans_hugepage.defrag: re-design test case

---

provider/cpu_utils.py
qemu/tests/cpu_device_hotplug_maximum.py
qemu/tests/cpu_device_hotpluggable.py
qemu/tests/cpu_topology_test.py

Until QEMU 8.1 there was a different behaviour for thread count in case of Windows guests. It represented number of threads per single core, not the total number of threads available for all cores in socket. Therefore we disable check for older QEMU versions and adjust for newer versions.
ID: 1539

cpu_utils: adjust thread count for Windows guests

---

generic/tests/cfg/unattended_install.cfg
qemu/tests/cfg/single_driver_install.cfg

1.unattended_install..multi_disk_install: don't backup the test disk
2.single_dirver_install: for viostor and vioscsi, remove the test image stg1 with name 'storage' after test finish
ID: 1852, 1854

Do not backup and remove test image after test finish

---

qemu/tests/cfg/rng_bat.cfg

fix Mandatory parameter 'devcon_path'
is missing, the root cause is that
Mix spaces and tabs before 'devcon_path'.
ID: 1860

rng_bat.cfg: fix Mandatory parameter missing issue

---

qemu/tests/boot_cpu_model.py

Since commit d384d23f71 in Avocado-VT, the CPU utilities have been moved to virttest/cpu.py.
This updates the location of these utility functions so that the test will work properly.

qemu/tests/boot_cpu_model.py: update to use virttest/cpu.py

---

qemu/tests/nic_bonding.py

In a serial session, since the kernel often prints debugging messages. The safe model will send carriage returns and is more robust than the previous mode. Reduce the probability of failure.
ID:1889

nic_bonding:Change the session model to avoid dirty messages output

---

qemu/tests/cfg/migration_virtio_mem_ignore_shared.cfg
qemu/tests/migration_virtio_mem_ignore_shared.py

migration_virtio_mem_ignore_shared: creates new test case
Creates new case to test virtio-mem device migration with
x-ignore-shared capability enabled. It starts both guests,
source and destination ones, then puts some stress in the
first one during the migration process. Finally, does the
migration and checks that, only a little amount of memory
has been migrated because of the capability and the virtio-mem
device works as expected.
ID: 1334

migration_virtio_mem_ignore_shared: creates new test case

---

qemu/tests/cfg/balloon_in_use.cfg

Sometimes, balloon memory from a little value to a large one, it will take a bit longer time.
ID: 1885

balloon_in_use: extend balloon memory timeout

---

provider/vdpa_sim_utils.py
qemu/tests/block_vhost_vdpa_test.py
qemu/tests/vdpa_sim_blk_test.py

vdpa_sim_utils.py: add module for VDPA net device interface
vdpa_sim_utils.py:
1. repalce filename from vdpa_sim_blk_utils to vdpa_sim_utils
2. update the VDPA block interfaces
3. add Class VhostVdpaNetSimulator
block_vhost_vdpa_test.py: point to new VhostVdpaBlkSimulatorTest
vdpa_sim_blk_test.py: point to new VhostVdpaBlkSimulatorTest
ID:1929

vdpa_sim_utils.py: add module for VDPA net device interface.

---

qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_installer_uninstall.py

installer: check warning message when uninstall driver by msi

---

generic/tests/iozone_windows.py
multi_host_migration/tests/migration_multi_host_with_file_transfer.py
qemu/tests/virtio_console.py

There are a few threading methods been deprecated since Python3.10, let's replace them according to the guide.
Reference: https://docs.python.org/3/whatsnew/3.10.html#deprecated
ID: 1791

Deprecate methods from threading module

---

qemu/tests/cfg/balloon_check.cfg

As guest memory was ballooned to a very small value, it leads to the guest couldn't boot up in a short period.
Therefore, it's better to extend the timeout of os booting up.
ID: 1975

balloon_check: extent vm login timeout after evict memory

---

qemu/tests/iperf_test.py

Changed this script statistics's format due to the latest driver has not support the old format. And after discussion with developer, QE only need focus on the later version is enough, so remove the old test code.
ID:1993

rss_iperf_test: change the statistics's format

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

the name of qemu-ga-win has been changed to mingw-qemu-ga-win, so the logic of getting specific version of package should be adjusted as well.
ID: 1229

qemu_guest_agent: adjust change for the version name of mingw-qga

---

qemu/tests/cfg/multi_disk_wild_hotplug.cfg

It can not find boot disk if exist multiple scsi disks. It need to specify the boot index explicitly.
ID:2006

multi_disk_wild_hotplug:specify the boot index explicitly

---

qemu/tests/win_virtio_driver_update_by_installer.py

Driver installer supports restoring DNS configurations after driver upgrade, so add a DNS checkpoint here. The previous static IP configuration test was #3860
ID: 1561

Installer test: add static DNS configuration test

---

qemu/tests/thin_write_in_qemu_img_commit.py

disk_format: Add '"compressed": False' since the behavior has been
changed start from qemu.8.2.0
ID: 1950

Updated dumped image info since it changed start from qemu.8.2.0

---

qemu/tests/ksm_ksmtuned.py

ksm_ksmtuned: gives more time for ksm to start
After checking the timings, the case failed because
ksmtuned needs some more time in order to start ksm
after reaching the threshold.
ID: 1932

ksm_ksmtuned: gives more time for ksm to start

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

nvdimm_nvml: adds environment variable to guest
For the success of the integration tests from of the PMDK
project, is it needed to export the PMEMOBJ_CONF variable
following the suggestion of the repository maintainers.
ID: 2051

nvdimm_nvml: adds environment variable to guest

---

provider/storage_benchmark.py

The old default fio point to fixed 3.1 , it is too old result in output has gap with linux fio.
ID:2042

storage_benchmark:fix windows default fio to latest

---

qemu/tests/cfg/pvpanic_event_check.cfg
qemu/tests/pvpanic_event_check.py

This patch is primarily needed to add time for waiting until the service has finished. In addition, it replaces a simpler command for checking the service's status.
ID: 1341

pvpanic_event_check: add time to prevent failure

---

provider/storage_benchmark.py
qemu/tests/fio_windows.py

The original judge condition does not so accurate, change it more accurate here.
ID: 1865

fio_windows: Update new check method for fio install

---

qemu/tests/qemu_guest_agent.py

Qemu_Guest_Agent: limit to restorecon in the /mnt dir
ID: 1949
Signed-off-by: bmarcynk [bmarcynk@redhat.com]

QGA: limit to restorecon in the /mnt dir

---

provider/input_event_proxy.py
qemu/tests/cfg/cdrom_test.cfg
qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/ioeventfd.cfg
qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/vioser_in_use.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_port_hotplug.cfg
qemu/tests/cfg/virtio_serial_file_transfer.cfg
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

Python2.7 is EOL, so update the python version to 3.12 in Windows VM, and update our testing configuration accordingly
ID:1878

Update python_bin in our windows testing

---

generic/tests/cfg/pktgen_perf.cfg
generic/tests/pktgen_perf.py
provider/pktgen_utils.py
provider/vdpa_sim_utils.py

pktgen: add support for two vdpa test cases in pktgen
1. Test pktgen on a VM with vdpa simulator and vhost-vdpa as the backend
2. Test pktgen on a host with vdpa simulator and virtio-vdpa as the backend
vdpa_sim_utils.py: add Class VirtioVdpaNetSimulatorTest
1. correct cmd in the add_dev function of VhostVdpaNetSimulatorTest
2. add Class VirtioVdpaNetSimulatorTest
ID: 2040, 2047
Signed-off-by: Wenli Quan [wquan@redhat.com]

pktgen: add support for two vdpa test cases in pktgen

---

qemu/tests/cfg/nmi_bsod_catch.cfg

Guest min memory has to be 4096.0 for win2025.
ID: 2113

nmi_bsod_catch: change win2025 min memory to 4096

---

qemu/tests/cfg/image_commit_bypass_host_cache.cfg
qemu/tests/cfg/image_compare_bypass_host_cache.cfg
qemu/tests/cfg/image_convert_bypass_host_cache.cfg
qemu/tests/cfg/image_rebase_bypass_host_cache.cfg

Add rhel10 host in the conf files for openat system call
ID: 2221

bypass cache cases: the system call remains as openat in rhel10

---

generic/tests/jumbo.py

After QE debugging found the Windows 2025 needs to re-identify the nic configuration after changing the MTU, so the original waiting time is a bit short to cause testing errors, so it was extended.
ID:2222

jumbo:extend the time to wait for the MTU to be ok after MTU changed

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/single_driver_install.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/qemu_guest_agent_update.py
qemu/tests/single_driver_install.py

Virtio-win drivers behavior are changed because of INF isolation, So change the pnputil cmd to deletes a driver package from the
driver store.
ID: 2219

virtio_win_driver: update pnputil cmd to remove drivers

---

provider/win_driver_installer_test.py
provider/win_driver_utils.py
qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/qemu_guest_agent.py
qemu/tests/win_virtio_driver_install_by_installer.py
qemu/tests/win_virtio_driver_installer_repair.py
qemu/tests/win_virtio_driver_installer_uninstall.py
qemu/tests/win_virtio_driver_update_by_installer.py

From virtio-win-1.9.37 later, installer work behavior has some change, it will pop up restart button at the end.
So there are following task list.
update autoit script for install/uninstall/update/repair in WIN-UTIL. update tp-qemu to remove restart action after use installer.
ID: 2031

virtio-win-installer: some update of installer tests

---

qemu/tests/hello_world.py

The bytes and string can not auto-convert in
python3. It needs to add decode() to get the string.
ID:2249

hello_world:fix bytes string compares error

---

qemu/tests/block_transfer_parameters_check.py

The cmd "sg_inq --page bl" output value is HEX in RHEL10. It needs to consider the conversion of number systems.
ID:2264

block_transfer_parameters_check:fix type convert error

---

qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/single_driver_install.cfg
qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/cfg/virtio_fs_group_permission_access.cfg
qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/cfg/virtio_fs_memory_backend.cfg
qemu/tests/cfg/virtio_fs_multi_users_access.cfg
qemu/tests/cfg/virtio_fs_multi_vms.cfg
qemu/tests/cfg/virtio_fs_readonly.cfg
qemu/tests/cfg/virtio_fs_sandbox.cfg
qemu/tests/cfg/virtio_fs_security_label.cfg
qemu/tests/cfg/virtio_fs_set_capability.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/cfg/virtio_fs_supp_group_transfer.cfg
qemu/tests/cfg/virtio_fs_support_win_fs.cfg
qemu/tests/cfg/virtio_fs_winfsp_test.cfg
qemu/tests/cfg/win_sigverif.cfg
qemu/tests/cfg/win_virtio_driver_install_from_update.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

For Win10 i386 guest, the max memory size is 4G, so set it in the specific cases which use memory backend way to start VM.
ID: 1915

virtio_fs: limit memory size for some Windows guest

---

provider/thp_fragment_tool.py

Depends on https://github.com/autotest/tp-qemu/pull/3987
thp_fragment_tool: creates external provider
Creates an external provider for the thp_fragment tool,
this way, the tool, can be now easily invoked from different
scripts avoiding duplicated code.
ID: 2087

thp_fragment_tool: creates external provider

---

generic/tests/cfg/trans_hugepage.cfg
generic/tests/trans_hugepage_defrag.py

Depends on https://github.com/autotest/tp-qemu/pull/3987, https://github.com/autotest/tp-qemu/pull/3988
trans_hugepage.defrag: updates case to make use of the new tool
Updates the test case to use the thp_fragment_tool, now included
as an external provider to avoid code duplication. Also applies
the black code formatter.
ID: 2090

trans_hugepage.defrag: updates case to make use of the new tool

---

generic/tests/cfg/trans_hugepage.cfg
generic/tests/trans_hugepage_relocated.py

Depends on https://github.com/autotest/tp-qemu/pull/3987, https://github.com/autotest/tp-qemu/pull/3988
trans_hugepage.relocated: fix existing issues
Fixes existing issues with the params and variables casting.
Removes the redhat prefix from cfg values. For memory
fragmentation, uses the thp_fragment tool, now invoked
from an external provider.
ID: 2037

trans_hugepage.relocated: fix existing issues

---

qemu/tests/cfg/mmu_basic.cfg

ppc64le:compatible mode is not supported for rhel9 guest
ID: 2269
Signed-off-by: Miriam Deng mdeng@redhat.com

ppc64le:compatible mode is not supported for rhel9 guest

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

We add this for security reasons.  From QEMU 8.1, the guest agent supports the allow rpcs list. Maybe will be better to start using it.
ID: 1442

qemu_guest_agent: adjust '--allow-rpcs' as new default option

---

qemu/tests/cfg/pktgen_burst_test.cfg

Add a new case to test network function under pktgen burst mode to check if it will hit tx timeout issues.
ID:2250

pktgen burst mode test

---

qemu/tests/cfg/multi_vms_with_stress.cfg
qemu/tests/multi_vms_with_stress.py

For max vCPU, 8 pCPUs allows 2 VMs with 8vCPUs
but not 1 VM with 16vCPUs
ID: 2062

multi_vms_with_stress: Add max vcpu scenario

---

qemu/tests/qemu_guest_agent_update.py

For vioser, they need system reboot after
removing drivers with new pnputil cmd
"pnputil /delete-driver %s /uninstall /force"
ID: 2353

qemu_guest_agent_update: system reboot needed after remove drivers

---

provider/win_driver_installer_test.py

This patch primarily adds a 'dmp file removed' step in the fwcfg part. We need it because it will completely fill the disk during the acceptance test.
ID: 2084

fwcfg: add the 'dmp file removed' step at the test case end

---

qemu/tests/hv_avic.py

Original timeout is 60, it isn't enough for yum install cpuid. There are many files extract, enlarge it to 300.
ID: 2343

hv_avic: Add timeout=300 for "yum -y install cpuid"

---

qemu/tests/nic_teaming.py

After discussion with developer who think in this case the lost ratio from 0% ~ 100% are all correct, so QE decided to remove ovs test case.
ID:2351

Forbidden ovs tests in nic_teaming case

---

qemu/tests/cfg/virtio_mem_dynamic_memslots.cfg
qemu/tests/virtio_mem_dynamic_memslots.py

Depnds on https://github.com/avocado-framework/avocado-vt/pull/3892
virtio-mem test with dynamic-memslots=on/off
New case to test the dynamic memslot creation
for virtio-mem devices.
ID: 2253

virtio-mem test with dynamic-memslots=on/off

---

qemu/tests/cfg/numa_prealloc_threads.cfg
qemu/tests/numa_node_affinity.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/3856
thread_context: adds support for multiple thread contexts
According to the new changes in the avocado-vt framework,
updating thread_context related test cases to support this
new behavior. Applies the black code formatter.
ID: 2097

thread_context: adds support for multiple thread contexts

---

qemu/tests/virtio_fs_group_permission_access.py
qemu/tests/virtio_fs_host_owner_win.py

Sometimes when add a new user, it failed when the group
existed. In this situation, add the new user to the group.
ID: 2224

virtio_fs: add user to the group when it exists

---

provider/win_driver_utils.py
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_installer_repair.py

It's not a valid case to uninstall some drivers and then repair them by installer.
The correct way is removeing virtio-win msi and then repair it by installer.
ID: 2024

virtio_win_installer: update installer repair function

---

qemu/tests/cfg/migrate.cfg
qemu/tests/migration_with_file_transfer.py

1.Setup "spawn=allow",due to under the deny mode which has conflict with migrate exec test.
2.Re-write exec migrate tests, becuase of it was not check the real test point, it should be checked the gzip mode instead of nc mode.
ID:2339

Resolve the conflict between migration fork test and "spawn=deny"

---

requirements-ci.txt

We are no ready for enabling this new check [1] since we have seen hundreds of errors been detected. So let us firstly restrict pylint to an old version and make a regular fix via another patch.
Reference:
[1] https://pylint.readthedocs.io/en/v3.2.0/whatsnew/3/3.2/index.html#new-checks
ID: 2387

ci: bypass pylint issue

---

qemu/tests/cfg/blockdev_mirror_forbidden_actions.cfg

Error msg for resizing disks during mirror changed since qemu9.0, update the error msg to compate with both old and new qemu version
id:2293

blockdev_mirror_forbidden_actions:error msg update

---

qemu/tests/cfg/blockdev_commit_forbidden_actions.cfg

Error msg for resizing during commit changed since qemu9.0, update the error msg to compatible with both old and new qemu version
id: 2295

blockdev_commit_forbidden_actions:update resize err msg

---

qemu/tests/cfg/blockdev_stream_forbidden_actions.cfg

Error msg for resizing disks during mirror changed since qemu9.0, update it to compatible with both old and new qemu versions.
id: 2292

blockdev_stream_forbidden_actions:update resize err msg

---

qemu/tests/cfg/virtio_serial_file_transfer.cfg

Chardev: replace spawn=deny to allow in this specific test scenario,
cause deny is blocking guest from accessment
ID: 2357

Change "spawn" from "deny" to "allow" for authority of accessment

---

qemu/tests/cfg/emulate_vf_shutdown.cfg

Due to the emulate sriov function only support on igb device, so let's limit it on igb, it will be update when there is another nic type can support emulate sriov function.
ID:2400

emulate_vf_shutdown: only test on igb

---

qemu/tests/cfg/pktgen_burst_test.cfg

For this case we only test it with multi queues, so limit it on the virtio_net.
ID:2399

pktgen_burst_test: only test virtio_net

---

qemu/tests/cfg/virtio_fsd_check_info.cfg

Virtio_fs: Limit virtio_fsd_check_info only run on RHEL8, cause start
from virtiofsd version info not include qemu version anymore
ID: 1501

 Limit virtio_fsd_check_info test scenario

---

qemu/tests/cfg/nic_teaming.cfg

This module has been deprecated start rhel.9.0,it is supported since rhel7.So limit it only run on RHEL7 and RHEL8.
ID:2431

nic_teaming: Limit only run on RHEL7 and RHEL8

---

qemu/tests/cfg/set_link.cfg
qemu/tests/check_nic_link_status.py

Add a new case to test the set link status before guest startup and check the nic status after guest startup.
ID:2248

Set link status before guest startup and check its status after startup

---

qemu/tests/qemu_guest_agent.py

module 'packaging' has ModuleNotFoundError risk
on RHEL8 or other platform. Optimise the import
method to avoid program break
ID: 2419

qemu_guest_agent.py: optimise module importing

---

qemu/tests/block_detect_zeroes.py

The block info output for luks image is not same as qcow2 or raw. Using human monitor command "info block" then query the filename to address node name.
ID:2372

block_detect_zeroes:fix support luks format

---

qemu/tests/cfg/virtio_mem_dynamic_memslots_with_migration.cfg
qemu/tests/virtio_mem_dynamic_memslots_with_migration.py

Depends on: https://github.com/autotest/tp-qemu/pull/4034
virtio_mem_dynamic_memslots_with_migration: creates new test case
Creates new test case that boots up a VM including a virtio-mem device,
then resizes it and then performs live migration. Finally, checks the
virtio-mem size remains the same as before migration and validates
the number of memslots is the expected one.
ID: 2370

virtio_mem_dynamic_memslots_with_migration: creates new test case

---

qemu/tests/cfg/blockdev_snapshot_install.cfg

Installer tag changed in RHEL10, so need to define the new installer tag for RHEL10
id:2439

blockdev_snapshot_install: install tag for RHEL1O

---

qemu/tests/cfg/blockdev_stream_install.cfg

blockdev_stream_install: install tag for RHEL10
Install tag changed in RHEL1O, so re-set an installer
tag for RHEL10
id:2440

blockdev_stream_install: install tag for RHEL10

---

qemu/tests/cfg/blockdev_commit_install.cfg

blockdev_commit_install:install tag for RHEL10
Install tag changed in RHEL10, re-set it.
id: 2441

blockdev_commit_install:install tag for RHEL10

---

qemu/tests/cfg/blockdev_mirror_install.cfg

blockdev_mirror_install: install tag for RHEL10
Install tag changed in RHEL10, so re-set it.
id: 2442

blockdev_mirror_install: install tag for RHEL10

---

qemu/tests/cfg/virtio_fs_hotplug.cfg
qemu/tests/virtio_fs_hotplug.py

virtio_fs: update bus to 'virtual-css' and remove mutl memory backend
on s390x
ID: 2382

Fix the wrong bus usage and remove multi mem-backend on s390x

---

provider/virtio_fs_utils.py
qemu/tests/cfg/driver_load_stress.cfg
qemu/tests/cfg/virtio_fs_memory_backend.cfg
qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg
qemu/tests/cfg/virtio_fs_winfsp_test.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg
qemu/tests/virtio_fs_share_data.py

When running stress test on windows vm, there'll
be a large debug log created which will occupy the whole c: volume.
Therefore, disable it before starting stress test.
ID: 1837

virtio_fs: disable debug log for stress test

---

qemu/tests/uefi_check_resolution.py

because sometimes the vm may login time out with the default value, set the timeout parameter for reboot method
ID: 2486

uefi_check_resolution: set the timeout parameter for reboot method

---

qemu/tests/bridge_qinq.py

Enable safe mode to run check tcpdump result cmd to avoide print debug or dirty output that make to timeout.
ID:2517

bridge_qinq: Enable safe mode to run check tcpdump result cmd

---

provider/win_driver_utils.py

Currently all installer test cases will
copy msi and installer related files, actually
there is no need to copy msi if there is no specific requirement.
So that, add condition in this utils.
ID: 2415

win_driver_utils:add condition to copy msi files

---

qemu/tests/win_virtio_driver_installer_repair.py
qemu/tests/win_virtio_driver_installer_uninstall.py

As the installer behavior was changed from 1.9.38, while warning check case just require to check warning status during install all drivers by msi and it doesn't mean to finish the whole installation action.
So, it's better to seperate the two uninstall ways in the script.
fix viofs_basic_io_test argument error
ID: 2385, 2407

virtio_win_installer: update warining check case via msi

---

qemu/tests/virt_firmware_check_phys_bits.py

Add support for handling VMStartError when start a vm with invalid phys-bits
ID: 2542

virt_firmware_check_phys_bits: add error handling VMStartError

---

qemu/tests/cfg/hotplug_unplug_nic_with_viommu.cfg
qemu/tests/cfg/multi_nics_hotplug.cfg
qemu/tests/cfg/multi_nics_stress.cfg
qemu/tests/cfg/nic_acpi_index.cfg
qemu/tests/cfg/nic_bonding.cfg
qemu/tests/cfg/nic_hotplug.cfg
qemu/tests/nic_acpi_index.py
qemu/tests/nic_bonding.py
qemu/tests/nic_hotplug.py

Due to dhcp-client has been replaced with dhcpcd in the future, so modified these cases to switch to dhcpcd command for the newer guest.
ID:2528

Switch to dhcpcd command for the newer guest

---

qemu/tests/cfg/seabios_strict.cfg

3. rhel8 will continue to support sgabios, but starting with 8.6 libvirt uses "-machine graphics=off" so rhel-8 testing should be switched over too.
ID: 2566

seabios_strict: disable sga device from rhel8.6 and the later version

---

qemu/tests/cfg/boot_from_device.cfg

3. rhel8 will continue to support sgabios, but starting with 8.6 libvirt uses "-machine graphics=off" so rhel-8 testing should be switched over too.
ID: 2566

boot_from_device: disable sga device from rhel8.6

---

qemu/tests/cfg/seabios_order_once.cfg

3. rhel8 will continue to support sgabios, but starting with 8.6 libvirt uses "-machine graphics=off" so rhel-8 testing should be switched over too.
ID: 2566

seabios_order_once: disable sga device from rhel8.6

---

provider/hostdev/__init__.py
provider/hostdev/dev_setup.py
provider/hostdev/utils.py
qemu/tests/cfg/vfio_net_boot.cfg
qemu/tests/vfio_net_boot.py

provider: Add the hostdev module to set up host devices for testing.
1. hostdev: PF/VF instance to manage host device
2. hostdev.dev_setup: Wrapper to configure host devices, so test cases
can use the decorator to set up the environment
3. hostdev.utils: Utilities during the hostdev test life cycle
vfio_net_boot: Basic test case to test host NIC passthrough
- This set of test cases is to test host NIC passthrough in to the guest.
Passthrough some NICs to vm, and then login via ssh, then ping external
IP address from guest.
ID: 1403

vfio_net_boot: Basic test case to test host NIC passthrough

---

qemu/tests/cfg/multi_nics_verify.cfg
qemu/tests/multi_nics_verify.py

The keyfile format will be the default usage since rhel9,and rhel10 has not support configure file, so sent a patch to resolve this problem.
ID:2497

Switch to create keyfile instead of configure file since rhel9

---

qemu/tests/cfg/virtio_fs_memory_leak_check.cfg
qemu/tests/virtio_fs_memory_leak_check.py

Iotest on virtiofs might cause memory leak, it's
necesary to check it.
Currently, it only supports windows guest.
ID: 2360, 2434

virtio_fs: new case of memory leak check on virtiofs

---

qemu/tests/cfg/qemu_nobody.cfg

Since 'elevateprivileges=deny' in the sandbox conflicts with runas,
set the value of this parameter to allow from the perspective of qemu-kvm
ID: 2494

qemu_nobody: set 'elevateprivileges=allow' 

---

qemu/tests/cfg/nvdimm.cfg

nvdimm: disable pmem=on test cases
Following the deprecation of the pmem feature in the incoming
release, exclude the hosts on the respective test cases.
ID: 2580

nvdimm: disable pmem=on test cases

---

qemu/tests/cfg/edk2_stability_test.cfg
qemu/tests/edk2_stability_test.py

Sometimes stability issue occurs when edk2 is loading, 
but this has nothing to do with loading the kernel. 
Design a new test scenario only to check the process from edk2 to the boot kernel.
Skip the subsequent processes of kernel startup.
ID: 2378

edk2_stability_test:Add edk2 stability test

---

qemu/tests/cfg/virtio_fs_multi_users_access.cfg

virtio_fs: correct the usage of virtio_fs to only use memory-backend-file
on s390x
ID: 1503

Update the usage of virtio_fs on s390x

---

qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/cfg/win_sigverif.cfg

Support viomem driver in win_sigverify and virtio_driver_sign_check test cases.
ID: 1984, 1985

viomem: support viomem driver for win driver case

---

qemu/tests/cfg/qemu_guest_agent.cfg

optimize the matching conditions for case
'qemu_guest_agent.virtio_serial.check_powerdown'.
To prevent the test from being interrupted by
filtering out error messages that are not
qga services.
ID: 2594

qemu_guest_agent: optimize the matching conditions

---

qemu/tests/hotplug_virtio_mem.py

hotplug_virtio_mem: forbid virtio_mem unplug for QEMU < 8.1.0
The unplug support for virtio_mem was introduced in RHEL 9.4
with QEMU 8.1, corrects the test to only do this action when
the proper QEMU is used. Also applies the black code formatter.
ID: 2626

hotplug_virtio_mem: forbid virtio_mem unplug for QEMU < 8.1.0

---

qemu/tests/cfg/netperf_udp_perf.cfg

bypass compilation with -Wno-implicit-function-declaration
More information reference [1]
[1] avocado-framework/avocado-vt#3930
id: 2633

netperf_udp_perf: Update CFLAGS in netperf setup command

---

qemu/tests/cfg/single_driver_install.cfg

Install viomem driver in a preinstalled windows guest.
ID: 1974

single_driver_install: install viomem driver

---

qemu/tests/block_resize.py
qemu/tests/cfg/block_resize.cfg

1.The guest does not always deploy sgdisk first.
It need to check sgdisk cmd in advance.
2.It should not use hardcode sdb as data disk
ID:2572,2571

block_resize:fix miss sgdisk and disk hardcode 

---

generic/tests/cfg/pktgen_perf.cfg
generic/tests/pktgen_perf.py

The default parameter 'use_va' of module 'vdpa_sim' was changed from False to True. When 'use_va' is True, it only works with shared memory enabled
More information : RHEL-12125
id: 2640

pktgen_perf: add 'vm_mem_share = yes' for case vhost_sim_test_vm

---

qemu/tests/cfg/block_hotplug_with_cpu_hotplug.cfg

WinNext means inside preview version of Win11.
This case not support it as well.
ID: 2657
Signed-off-by: menli menli@redhat.com

block_hotplug_with_cpu_hotplug: remove WinNext

---

provider/block_devices_plug.py

This ensure that a device would be removed from the DevContainer before its parent(s) been removed.
ID: 2408

block_devices_plug: fix unplug issue

---

qemu/tests/cfg/nvdimm.cfg
qemu/tests/nvdimm.py

nvdimm: removes epel dependecies and use DOC=n flag with make
As the documents compilation can be skipped using 'DOC=n' flag,
the pandoc package is no longer needed and in the same way is
the EPEL repository. Changes the approach to first call make
with the DOC=n flag, then build the tests with make test and
run the RUNTESTS.sh script to execute the tests.
ID: 2569

nvdimm: removes epel dependecies and use DOC=n flag with make

---

qemu/tests/cfg/ovs_host_vlan.cfg
qemu/tests/ovs_host_vlan.py

1.Extend the ping timeout due to sometimes it will take more time when sometimes host has low machine resource.
2.Add a workaround to bypass the netperf compile issues, the root cause is gcc's implicit function declarations are treated as errors from 14.0.
ID:2642

Fix ping timeout short and netperf compile issue

---

qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_installer_uninstall.py

The warning check https://github.com/autotest/tp-qemu/pull/3867 is no longer needed. Removing sub-testcase.
ID: 2544

installer: remove the by_msi sub-testcase

---

qemu/tests/cfg/virtio_console.cfg

ID: 2495
VM won't boot up with error "Operation not permitted" with "spawn=deny".

chardev: set "spawn=allow" for specific case

---

qemu/tests/blockdev_stream_cor_base.py
qemu/tests/blockdev_stream_subchain.py

blockdev_stream_cor_base:adapt case to raw elimination
Backing changes for case blockdev_stream_cor_base and blockdev_stream_subchain when "raw format elimination" applied, so update the cases to adapt to it.
id: 2681

blockdev_stream_cor_base:adapt case to raw elimination

---

qemu/tests/blockdev_mirror_stress.py
qemu/tests/cfg/blockdev_mirror_stress.cfg

When running stress test as a thread, we usually hit resource lock issue, so some processes hang there even though test has finished and vm quit successfully,this will block all the tests in a loop.
id:2784

blockdev_mirror_stress:not run stress test as a thread

---

qemu/tests/blockdev_inc_backup_modify_backing_bitmaps.py

Original case can only support local backend,
extend it to support all supported backends.
id:2777

blockdev_*backing*:adapt case to all backends

---

qemu/tests/cfg/iperf_test.cfg

Netkvm: Add a case for iperf with very short packets length
ID: 2403                                                                       

Netkvm: Add a case for iperf with very short packets length

---

provider/win_driver_utils.py
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg

Since virtio-win 1.9.41 version, there is no restart requirement when install and uninstall the installer, while repair still has.
ID: 2785

virtio_win_installer: update the installer script

---

qemu/tests/cfg/virtio_fs_host_owner_win.cfg

Echo cmd sometimes cause timeout issue in automation, and the main test point isn't create files in this case, so using dd cmd to instead of echo cmd.
ID: 1752

virtio_fs: use dd cmd to create file

---

qemu/tests/blockdev_commit_backing_mask_off.py
qemu/tests/cfg/blockdev_commit_backing_mask_off.cfg

When doing block commit with backing_mask_protocol false, the backing raw image format can't be identified as a raw image but the backend image protocol, like nbd, file, iscsi and so on.
id:2807

blockdev_commit_backing_mask_off:commit backing mask off

---

qemu/tests/blockdev_stream_backing_mask_off.py
qemu/tests/cfg/blockdev_stream_backing_mask_off.cfg

When doing block stream with backing_mask_protocol false, the backing raw image format can't be identified as a raw image but the backend image protocol, like nbd, file, iscsi and so on.
id: 2805

blockdev_stream_backing_mask_off: test backing_mask_off

---

qemu/tests/cfg/throttle_operation_test.cfg
qemu/tests/cfg/throttle_parameter_test.cfg
qemu/tests/throttle_operation_test.py
qemu/tests/throttle_parameter_test.py

The disk serial number in the latest Linux guest can 
not be displayed in time. Adding some time delay
after booting.
ID:2793

Fix disk serial issue for throttle relevant test

---

qemu/tests/blockdev_commit_backing_mask_on.py
qemu/tests/cfg/blockdev_commit_backing_mask_on.cfg

When doing commit with backing_mask_protocol on,
the backing raw image format can be identified
correctly as "raw" for "raw format blockdev
elimination".
id:2808

blockdev_commit_backing_mask_on:test backing_mask on

---

qemu/tests/cfg/ovmf_check_efi.cfg

Due to the deletion of sgdisk in the latest linux, change sgdisk to parted in this case
ID: 2880

ovmf_check_efi: change sgdisk to parted

---

qemu/tests/cfg/virtio_mem_hugetlb_migration.cfg
qemu/tests/virtio_mem_hugetlb_migration.py

virtio_mem_hugetlb_migration: adds new test case
Creates a new test case for performing a live migration
of a VM with a virtio-mem device that consumes hugepages
ID: 2653

virtio_mem_hugetlb_migration: adds new test case

---

provider/ansible.py
qemu/tests/ansible_test.py
qemu/tests/ansible_with_responsive_migration.py
qemu/tests/cfg/ansible_test.cfg
qemu/tests/cfg/nested_block_resize.cfg
qemu/tests/cfg/nested_vsock_con_sockets.cfg
qemu/tests/nested_block_resize.py
qemu/tests/nested_vsock_con_sockets.py

The default connection plugin for ansible is ssh, but when using password with ssh plugin, the sshpass is required. To support flexible connection, make the connection plugin is customizable.
ID: 2651

rfe: Support custom ansible connection plugin

---

qemu/tests/cfg/blockdev_commit_firewall.cfg

Expected host dmesg changed for nft_compat,
so update it.
id: 1917

blockdev_commit_firewall:update the expected host dmsg

---

qemu/tests/blockdev_stream_backing_mask_on.py
qemu/tests/cfg/blockdev_stream_backing_mask_on.cfg

When doing stream with backing_mask_protocol on,
the backing raw image format can be identified
correctly as "raw" for "raw format blockdev
elimination".
id:2806

blockdev_stream_backing_mask_on: backing_mask_protocol on

---

generic/tests/stress_boot.py

stress_boot: Fixed the issue of unequal number of vCPUs when booting vm

---

qemu/tests/cfg/uefi_boot_from_device.cfg

include the following 4 cases:
uefi_boot_from_device.UEFI_PXEv4
uefi_boot_from_device.UEFI_PXEv6
uefi_boot_from_device.UEFI_HTTPv4
uefi_boot_from_device.UEFI_HTTPv6
ID: 2883

uefi_boot_from_device: add support for network boot

---

qemu/tests/cfg/edk2_check_mor.cfg
qemu/tests/edk2_check_mor.py

check mor enabled under secure mode
ID: 2895

edk2_check_mor: add a new case

---

qemu/tests/cfg/rh_kselftests_vm.cfg
qemu/tests/rh_kselftests_vm.py

rh_kselftests_vm: kernel selftests execution in guest
Creates a new test case that executes the kernel selftests
inside the VM through the RPM that has been previously downloaded
and installed. Could be expanded with more tests in the future.
ID: 2637

rh_kselftests_vm: kernel selftests execution in guest

---

qemu/tests/cfg/passt_stability_tests.cfg
qemu/tests/passt_stability_tests.py

Add a new case to support passt stability tests.
ID:2445

passt stability tests

---

qemu/tests/cfg/hotplug_virtio_mem.cfg
qemu/tests/hotplug_virtio_mem.py

hotplug_virtio_mem: updates unplug error message
From QEMU 9.1 onwards the error message displayed when the
virtio-mem device is tried to be unplugged while it still has
some memory plugged has been updated. Adding support for
both messages based on the version.
ID: 128

hotplug_virtio_mem: updates unplug error message

---

qemu/tests/hv_kvm_unit_test.py

Set the workaround of hv_kvm_unit_test about lm=off
Remove the lm=off flag form hv_kvm_unit_test test
ID: 1897

Update the hv_kvm_unit_test to suitable Win10-32

---

qemu/deps/block_device/libblkio_release_test.sh

There are multi packages for libblkio since version 1.5.
ID:2860

libblkio_release_test:fix untar error

---

qemu/tests/qemu_guest_agent.py

The fsfreeze commands are already written to report an error if vss_init() fails. Reporting a more specific error message is more helpful than a generic "command is disabled" message
ID: 2868

qemu_guest_agent: Report message changed for api qga-freeze

---

qemu/tests/win_virtio_driver_installer_uninstall.py

After run the installer uninstallation function, better to wait a moment to check whether drivers were totally uninstalled,because it would take some time to clear the drivers info in some os.
ID: 2855

installer_uninstall: wait a moment to check drivers

---

qemu/tests/cfg/qemu_guest_agent.cfg

Installation of installer would quit because virtio-net was uninstalled and re-installed in the process which cause the session was lost, and then autoit process would quit. Then using other network type instead of virtio-net would work.
ID: 2811

qemu_guest_agent: fix installer installation failed issue

---

qemu/tests/cfg/in_place_upgrade.cfg
qemu/tests/in_place_upgrade.py

ID:2634
Provide installing particular packages for leapp tool

IPU:add stream installation way for leapp tool

---

qemu/tests/cfg/numa_prealloc_threads.cfg

numa_prealloc_threads: sets smp to 1, avoiding boot up timeouts
Sets smp to 1 and vcpu_max to 2 (not needed to change the vcpu_sockets)
this way the VM can boot up in a feasible time, four times faster than
before facing the timeout issues.
ID: 2978

numa_prealloc_threads: sets smp to 1, avoiding boot up timeouts

---

qemu/tests/cfg/passt_transfer_tests.cfg
qemu/tests/passt_transfer_tests.py

Add a new case to support passt file transfer test via tcp/udp
ID:2853

passt file transfer tests via tcp/udp

---

generic/tests/cfg/emulate_vf_jumbo.cfg
generic/tests/cfg/mac_change.cfg
generic/tests/jumbo.py
generic/tests/mac_change.py

Due to dhclient command has been deleted on rhel 10, so using dhcpcd command to replace it

Use dhcpcd command on rhel 10

---

provider/in_place_upgrade_base.py
qemu/tests/cfg/in_place_upgrade.cfg

ID:2901
IPU:rmmod unsupported modules before doing in place upgrade from RHEL8 to RHEL9

IPU:rmmod unsupported modules before doing in place upgrade

---

qemu/tests/cfg/numa_opts.cfg

numa_opts: increase the mem required for 128 nodes
The current 16G of memory assigned to this case are not enough,
increasing the memory to 64G, even this will limit the testing
possibilities, it's not realistic testing son many nodes with
so few memory.
ID: 2974

numa_opts: increase the mem required for 128 nodes

---

qemu/tests/single_driver_install.py

Installing the netkvm driver on an existing network interface caused session handling issues, leading to test failures. This patch changes the session handling from SSH to the serial session by replacing vm.wait_for_login() with vm.wait_for_serial_login(). It also adds a ping test to verify network connectivity after the driver installation.
ID: 1382

Netkvm: Fix session handling issue during netkvm driver installation

---

qemu/tests/cfg/vfio_net_boot.cfg

iommufd-backed VFIO, for example:
-object iommufd,id=iommufd0
-device vfio-pci,host=01:00.0,iommufd=iommufd0
Multiple pcie device can use the same iommufd.

Add iommufd case for vfio_net_boot

---

qemu/tests/block_with_iommu.py
qemu/tests/cfg/block_with_iommu.cfg

block_with_iommu: expands the test case functionality
Expands the test case functionality, doing a simple i/o
operation after checking the guest has boot up
successfully and finally reboot the VM in all the cases.
ID: 2991

block_with_iommu: expands the test case functionality

---

provider/virt_storage/storage_volume.py

When setting image_aio to native, cache.direct:on
is required.
id: 2919

storage_volume: set direct=on for image_aio=native

---

qemu/tests/cfg/rh_kselftests_vm.cfg

rh_kselftests_vm.mm: makes shared machine memory
Implementing a suggestion where it would be better
using shared memory with memory-backend-file.
ID: 3004

rh_kselftests_vm.mm: makes shared machine memory

---

qemu/tests/cfg/hotplug_mem_simple.cfg

hotplug_mem_simple: increase VM memory and max memory
Updates the VM memory from 2G to 4G so the test could
work with Windows guests too. Also updates maxmem to 8G.
ID: 3010

hotplug_mem_simple: increase VM memory and max memory

---

qemu/tests/qmp_basic.py

The return result of the memsave command
has changed from qemu-kvm-9.1
ID: 2902

qmp_basic: fix the return results of the memsave command

---

qemu/tests/uefi_pkg.py

add support for inteltdx with secure boot when checking descriptor meta files
ID: 3030

uefi_pkg: add support for checking inteltdx with secure boot

---

qemu/tests/cpu_device_hotpluggable.py

CPU: ignore ruff policy for the funtiona of sub_migrate
ID: 3002

Based on test case design, ignore ruff policy

---

qemu/tests/cfg/vm_poisoned_migration_prevention.cfg
qemu/tests/vm_poisoned_migration_prevention.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/4022
vm_poisoned_migration_prevention: adds new test case
Creates a new test case that checks the migration prevention
when there's poisoned memory.
ID: 2982

vm_poisoned_migration_prevention: adds new test case

---

deps/input_event/input_event_win.py
provider/input_event_proxy.py
qemu/tests/kvm_unit_test.py
qemu/tests/performance.py
qemu/tests/qemu_io_blkdebug.py
qemu/tests/usb_common.py

Removed the python2 dependant modules as they are out of support now!
Signed-off-by: Kowshik Jois B S <kowsjois@linux.ibm.com>

Removed python2 imports

---

provider/win_driver_utils.py

For viostor and vioscsi, they need system reboot
after removing drivers with new pnputil cmd
"pnputil /delete-driver %s /uninstall /force"
ID: 3023

win_driver_utils: system reboot is needed after remove drivers

---

qemu/tests/cfg/single_driver_install.cfg
qemu/tests/cfg/virtio_driver_sign_check.cfg
qemu/tests/cfg/win_sigverif.cfg

virtio-mem is not supported on 32-bit system,
so remove virtio-mem test from i386.
ID: 2886

virtio-mem is not supported on 32-bit system

---

qemu/tests/cfg/win_virtio_driver_install_from_update.cfg

Add viomem support to test driver install
from windows update server.
ID: 2504

win_virtio_driver_install_from_update: Add viomem support

---

qemu/tests/multi_nics_verify.py

This command will let all the nic device obtain ip address which cuased guest ip route conflict to let guest hang a moment and failed to got the command execution status. Based on test steps the guest will reboot after create networkmanager connection file which can got same result,therefore delete this line.
ID:3014

delete reload configuration command

---

qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/rng_host_guest_read.cfg
qemu/tests/cfg/rng_hotplug.cfg
qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/cfg/rng_read_longtime.cfg
qemu/tests/cfg/rng_stress.cfg
qemu/tests/cfg/viorng_in_use.cfg

RNG: for guest report driver added exception for RHEL.7 and RHEL.8 on s390x in cases
"rng_bat", "rng_stress", "rng_hotplug", "viorng_in_use", "rng_host_guest_read", "rng_read_longtime" and "rng_maxbytes_period" 
ID: 2669

RNG: guest report driver add exception for RHEL.7,RHEL.8

---

qemu/tests/cfg/block_with_iommu.cfg

For currently we use the wrong limit parameter in the cfg. So we can not filter case on the intel machine. Update to the right parameter.
ID: 3144

block_with_iommu.cfg: limit iommu case for windows on Intel CPU only

---

qemu/tests/cfg/migrate.cfg
qemu/tests/migration_with_file_transfer.py

Delete between_vhost_novhost case name because it isn't a support scenario on libvirt level.
ID:3127

Delete case name because it isn't a support scenario

---

qemu/tests/cfg/in_place_upgrade.cfg
qemu/tests/in_place_upgrade.py

Support in place upgrade test from RHEL9 to RHEL10
ID:2857

IPU: support in place upgrade from RHEL9 to RHEL10

---

qemu/tests/cfg/win_virtio_driver_install_from_update.cfg
qemu/tests/win_virtio_driver_install_from_update.py

For currently win11 and win2025 always fail with
windows update case, the root case is that:
For INF isolation all win11 drivers are moved to DriverStore (C:\WINDOWS\system32\DriverStore\FileRepository).
Each installation creates a new directory in
the DriverStore folder depending on the driver hash. While for win10 drivers, there are no change.
So change the method to check whether the driver was installed. After the test, all guests work normally.
ID: 1726

Update the method to check driver was installed

---

provider/win_dump_utils.py
qemu/tests/cfg/fwcfg.cfg
qemu/tests/cfg/fwcfg_enable.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

The issue with WinDbg not being found was caused by incorrect WMIC queries.
ID: 1770

fwcfg: fix wmic query to ensure windbg installation for fwcfg cases

---

qemu/tests/cfg/cpu_topology_test.cfg

ID: 2526
Exclude the CPU topology details test for Windows VM, will cover the basic test for Windows vm

exclude windows vm for details test

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_supp_group_transfer.cfg

Use the new variable `fs_log_level` to set log levels in test cases. 
ID: 2796

Use fs_log_level to set log levels in test cases

---

qemu/tests/cfg/enable_scatter_windows.cfg
qemu/tests/enable_scatter_windows.py

Replace tshark.exe with WinDump.exe for capturing network traffic. This resolves the issue where enabling netkvm driver TxLSO results in no packet length >= 1514 after file transfer, identified as a Wireshark problem.
ID: 2395

Netkvm: use WinDump for capture and Wireshark for analysis

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add public ssh-key injection support for windows. Linux had been supported already.
ID: 2587
Signed-off-by: Dehan Meng [demeng@redhat.com](mailto:demeng@redhat.com)

qemu_guest_agent: Add ssh-key injection support for windows

---

qemu/tests/cfg/netkvm_params_check.cfg
qemu/tests/netkvm_params_check.py

Configure the driver with TX capacity of 64 (instead of default of 1024) and check in the driver logs that the driver limit the SG (scatter-gather) area " Limit m_SGTableCapacity by 64"
ID: 2402

NetKVM: Add a case for checking the keyword in the driver logs

---

qemu/tests/cfg/x86_cpu_flags.cfg
qemu/tests/x86_cpu_test_dies.py

ID: 3015
When TGLX rewrote the x86/topology code upstream a change was made to Intel die_id numbering. Previously the die_id was unique per package. After the change the die_id is unique per system.

x86: fix die parameter check

---

qemu/tests/cfg/pvpanic_event_check.cfg
qemu/tests/pvpanic_event_check.py

We have a new capability: normal shutdown requests through pvpanic. See https://gitlab.com/qemu-project/qemu/-/blob/master/docs/specs/pvpanic.rst?ref_type=heads and the patchset https://lore.kernel.org/qemu-devel/202 40208-pvpanic-shutdown-v6-0-965580ac057b@t-8ch.de/
ID: 2898

dump: add 7("111") when reading pvpanic device capability

---

qemu/tests/cfg/s390x_cpu_model.cfg

CPU_model: since z196 is deprecated start from 10, remove it
ID: 2646

Remove un-supported CPU model on s390x

---

qemu/tests/cfg/blockdev_mirror_firewall.cfg

Update expected_host_dmesg value to skip unmaintained driver detection in host_dmesg
id:3219

blockdev_mirror_firewall:skip unmaintained driver detection

---

qemu/tests/stress_kernel_compile.py

Change progress type to bar because
invalid progress type 'none' in qemu-kvm-9.1
ID: 2900

Fix download failure about wget type

---

qemu/deps/sev-snp/regular_attestation_workflow.sh
qemu/tests/cfg/sev_basic_config.cfg
qemu/tests/cfg/snp_basic_config.cfg
qemu/tests/snp_basic_config.py

snp_basic_config: Add snp basic config test case

---

qemu/tests/cfg/block_boot_multi_disks.cfg

to avoid the issue of tpm log file being full
ID: 3298

block_boot_multi_disks: only adding bootindex to the system image

---

qemu/tests/block_hotplug_with_max_map_count.py
qemu/tests/cfg/block_hotplug_with_max_map_count.cfg

block_hotplug_with_max_map_count: creates new test case
Creates new test case that boots up a VM with a small max_map_count,
then hotplugs 15 disks and checks the VM status.
ID: 3130

block_hotplug_with_max_map_count: creates new test case

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

covered the following scenarios in the case:
1. cpu without rdrand, with fallback rng and with one or two serial port
2. cpu without rdrand, with virtio-rng and with one or two serial port
3. cpu with rdrand, without virtio-rng and with one or two serial port
4. cpu with rdrand, with virtio-rng and with one or two serial port
ID: 3328

uefishell.check_net_boot_entry: adds new test case

---

qemu/tests/cfg/virtio_fs_subtest_during_io.cfg

The timeout variable name is fs_io_timeout but nog io_timeout in virtio_fs_utiles.py
ID: 3267

virtio_fs_subtest_during_io: fix timeout issue

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/virtio_fs_share_data.py

Reboot vm by system_reset during virtiofs is working
ID: 3129

Virtiofs: Reboot vm during virtiofs is working

---

qemu/tests/balloon_check.py

When balloon memory to a big value, it means balloon deflation, in guest the in use memory would be reduced;
while balloon memory to a small value, it means balloon inflation, in guest the in use memory would be increased.
So the calculation method should be updated.
ID: 1316

balloon_check: fix the inconsistent comparison

---

qemu/tests/cfg/virtio_fs_share_data_hugepage.cfg

change cache argument of virtiofsd from',cache=' to ' --cache=' and update the cache mode 'none' to 'never' to match with the latest production behavior.
ID:2917
Signed-off-by: Junyao Zhao junzhao@redhat.com

virtio_fs_share_data_hugepage: correct cache argument

---

qemu/tests/block_hotplug_with_max_map_count.py

The original type is 'types' resulting in can not
set vm.max_map_count as expected.
ID:3391

block_hotplug_with_max_map_count:fix the type of vm.max_map_count

---

qemu/tests/rh_kselftests_vm.py

rh_kselftests_vm.mm: updates the pattern based on the guest OS version
The output of the selftests changes, for RHEL 8 versions, it
seems to not contain hastags '#' at the beggining of each line.
Opportunistically, increase the RPM download timeout.
ID: 3352

rh_kselftests_vm.mm: updates the pattern based on the guest OS version

---

qemu/tests/cfg/virtio_fs_dynamic_memslots.cfg
qemu/tests/virtio_fs_dynamic_memslots.py

Add test case support >=509 memslots
ID: 3024

Virtiofs: Add test case support >=509 memslots

---

qemu/tests/cfg/virtio_fs_share_data.cfg
qemu/tests/cfg/virtio_fs_share_data_multi_backend.cfg

virtio_fs_share_data_multi_backend: Adapt the extra options to all the hosts
Update the condition from Host_RHEL.m9 to !Host_RHEL.m8 to let other hosts like rhel10 and later on can run the related cases
ID: 3363

virtio_fs_share_data: Adapt the extra options to all the hosts

---

provider/virtio_fs_utils.py
qemu/tests/virtio_fs_share_data.py

For windows guest, need to wait a moment for the volume active.
ID: 1863

virtio_fs: wait a moment for the shared volume active

---

generic/tests/cfg/nfs_corrupt.cfg

The account of time to wait the VM to get paused in rhel10 hosts is about 40 minutes.
ID: 3341

nfs_corrupt: Adapt the pause timeout for rhel10 hosts

---

qemu/tests/cpu_info_check.py
qemu/tests/thin_write_in_qemu_img_commit.py

`_get_qemu_version` was removed from `virttest.env_process` in https://github.com/avocado-framework/avocado-vt/pull/4039/commits/fe5614d78ce74395544d6c2834573e0e6f25eb5e
There were a bunch of test cases that were using the private function, and so affected by this removal, such as the one being fixed in https://github.com/autotest/tp-qemu/pull/4249
This path updates the other test cases so they call the public (and still available) function from virttest instead.
ID: 3313

Avoid  calling env_process._get_qemu_version from test cases

---

qemu/tests/uefi_pkg.py

the description of amd-sev-snp has been updated, no mapping mode, so add checks for it
ID: 3349

uefi_pkg: modify the judgment criteria to adapt to the new update

---

qemu/tests/cfg/hugepage_reset.cfg
qemu/tests/hugepage_reset.py

hugepage_reset: fix memory comparison
The comparison between the memory needed by the test
and the free memory from each node was incorrect.
Keep the HugePageConfig setup() function to
properly set the calculated hugepages on the right node.
Adds an informative comment in the cfg about setting
1G hugepages at boot time.
ID: 3254

hugepage_reset: fix memory comparison

---

qemu/tests/vioser_in_use.py
qemu/tests/virtio_serial_hotplug_port_pci.py

Avoid case calling case, so add corresponding functions
ID: 2995
Signed-off-by: Dehan Meng [demeng@redhat.com](mailto:demeng@redhat.com)

vioser: Supplement the correct function

---

qemu/tests/cfg/virtio_fs_nfs_migration_handler.cfg
qemu/tests/virtio_fs_nfs_migration_handler.py

Testing --migration-verify-handles and --migration-confirm-paths over NFS
ID: 2971

virtio_fs_nfs_migration_handler: Migration test with handler

---

qemu/tests/cfg/virtio_fs_localfs_migration.cfg
qemu/tests/virtio_fs_localfs_migration.py

virtio_fs_localfs_migration: Migrate localfs with different cache modes

---

qemu/tests/cfg/virtio_fs_migration_on_error.cfg
qemu/tests/virtio_fs_migration_on_error.py

virtio_fs_migration_on_error: Migration test with migration-on-error

---

qemu/tests/cfg/uefishell.cfg
qemu/tests/uefishell.py

smbios 3.0 uses "auto" type for entry point by default from rhel-9.4. 
"pc-q35-rhel9.4.0" or newer machine type(s) set SMBIOS entry point automatically depending on the configuration.
If VM uses VCPUs with less than 510, a 32-bit SMBIOS entry-point will be generated. Otherwise, QEMU will transparently switch to 64-bit SMBIOS entry-point.
ID: 3350

uefishell.check_smbios: add support for auto type of entry point

---

qemu/tests/cfg/rh_kselftests_vm.cfg
qemu/tests/rh_kselftests_vm.py

rh_kselftests_vm: adds check for brewkoji package
In case the brewkoji is not installed in the guest,
which is necessary for the test to succeed, tries to
install it or cancel the case.
ID: 3371

rh_kselftests_vm: adds check for brewkoji package

---

provider/storage_benchmark.py
qemu/tests/cfg/virtio_fs_nfs_migration.cfg
qemu/tests/virtio_fs_nfs_migration.py

The following testing matrix is covered:
cache mode:
auto, never, always, metadata
writeback:
enabled and disabled
allow-direct-io
enabled and disabled
file-handles
mandatory and never
ID: 2966

virtio_fs_nfs_migration: Virtiofs migration testing over NFS

---

qemu/tests/balloon_stress.py

cmd_output_safe() use serial session, while in this case, it need a common session.
ID: 3377

balloon_stress: update cmd_output_safe() with cmd_output()

---

qemu/tests/cfg/rng_bat.cfg
qemu/tests/cfg/rng_host_guest_read.cfg
qemu/tests/cfg/rng_hotplug.cfg
qemu/tests/cfg/rng_maxbytes_period.cfg
qemu/tests/cfg/rng_read_longtime.cfg
qemu/tests/cfg/rng_stress.cfg
qemu/tests/cfg/viorng_in_use.cfg

update_rng: Update rng device for all platform if needed

---

qemu/tests/cfg/blockdev_full_backup.cfg
qemu/tests/cfg/blockdev_full_mirror.cfg

600s is not enough for the block job to reach
ready status when the target image is created
on the 512 disk, so extend the time to 900s to
allow block job to get finished.
id: 3470

backup_utils: set block jobs timeout to 900s

---

qemu/tests/blockdev_inc_backup_after_commit.py
qemu/tests/blockdev_inc_backup_inc_success.py
qemu/tests/blockdev_inc_backup_with_guest_agent.py
qemu/tests/blockdev_inc_backup_with_migration.py
qemu/tests/blockdev_inc_backup_xpt_bitmap.py

remove data-file format when starting vm with
backup images
id:3400

blockdev_inc_backup_inc_success:remove data-file

---

qemu/tests/differential_backup.py

Zram0 device exist under image mode test env,
so filter it out during initiating data disk
image.
id:3427

differential_backup:filter out zram0 device

---

provider/virt_storage/virt_target.py

"/root/avocado-vt/*" is used as root dir of
the tests, but for an image mode test env,
the /root path links to /var/roothome, if we
still search the target image with imagename
"/root/avocado-vt/$filename", it will cause
"file not exist" error.
id:3426

virt_target:create target with real path

---

provider/blockdev_live_backup_base.py

Backup image was created as non data-file image, so we can't start it with data-file format. Now remove the data-file format when starting vm with backup image.
id:3399

blockdev_live_backup_base:remove data_file for backup image

---

qemu/tests/blockdev_inc_backup_test.py

Backup image is not created as data-file, so we can't start it with data-file format. Remove the enable_data _file params before starting the clone VM.
id:3394

blockdev_inc_backup_*:remove data-file for backup image

---

provider/blockdev_backup_base.py

Won't support data-file for backup image at present, will support it later if needed.
id:3390

blockdev_backup_base:skip data-file for backup image

---

qemu/tests/blockdev_inc_backup_pull_mode_test.py
qemu/tests/blockdev_inc_backup_pull_mode_vm_down.py
qemu/tests/blockdev_inc_backup_pull_mode_vm_reboot.py

Don't support data-file for backup image, so remove the parameter before creating the backup full/incremental images.
id:3384

blockdev_inc_backup_pull_*:Remove data-file for backup image

---

qemu/tests/cfg/blockdev_commit_auto_readonly.cfg

Snapshot image size set to 20G, but under some situation, we start VM with system image size not equal to 20G, so when we do the snapshot/commit with a snapshot image that smaller that system image size, the case will fail with "no ipv4 address" issue. So correct it to let the snapshot image size follow the default system image size.
id:3484

blockdev_commit_auto_readonly:not set size for snapshot image

---

qemu/tests/cfg/blockdev_full_backup.cfg

timeout set for dst_cluster_size_512, but not
set to backup_options, so no timeout get in
backup_utils.py when doing the backup jobs which
will cause it use the timeout default value 600s.
id:3486

blockdev_full_backup:add timeout in backup_options

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py

netperf: implements dynamic NUMA binding
The test was taking the last NUMA node to
bind the VM's memory. In some systems the last
NUMA node could have no memory and/or CPUs
assigned, updates the test to take the first
valid node.
ID: 3321

netperf: implements dynamic NUMA binding

---

qemu/tests/block_with_iommu.py
qemu/tests/cfg/block_with_iommu.cfg

1. Using the clone image as os image avoids breaking the original image file.
2. Force killing VM after test avoids the underlying issue and VM recover operation.
3. Support iommu test for virtio-blk device
4. Add debug information
ID:3452,3454,3448

block_with_iommu: improve test case

---

qemu/tests/cfg/viorng_in_use.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

win_virtio_driver_update_test: remove double quote
This is a minor fix, I guess the double quote is harmless
but still not correct. Opportunistically removes also a
single double quote from viorng_in_use.
ID: 3473

win_virtio_driver_update_test: remove double quote

---

provider/disk_utils.py

disk_utils: new functions provider
Creates a new file containing a set of functions
useful for managing disks and filesystems in guest
environments
ID: 3118

disk_utils: new functions provider

---

qemu/tests/block_disk_not_default_options.py
qemu/tests/cfg/block_disk_not_default_options.cfg

Depends on https://github.com/autotest/tp-qemu/pull/4219
block_disk_not_default_options: creates new test case
Creates a new test case that boots up a VM with a disk
configured with non-common options such as packed or
page-per-vq. Unplug the disk and hotplugs it again.
Signed-off-by: Mario Casquero <mcasquer@redhat.com>
ID: 3007

block_disk_not_default_options: creates new test case

---

qemu/tests/cfg/fwcfg.cfg
qemu/tests/cfg/fwcfg_enable.cfg
qemu/tests/cfg/win_virtio_driver_update_test.cfg

Currently, this command can not get available disk in bootc host, besides that, this command also not setup the output's units, it will get a wrong number if the command execute in a large system( disk size > 1T).So update the command to fix above errors
ID:3461

fwcfg: update command to make it more accurate and general

---

generic/tests/cfg/iozone_windows.cfg

The remaining disk size of the C drive decreases
as the VM memory increases for win11. so if we start the vm on a big memory host, no enough space to do iozone on C drive. Adjust the memory for win11 to
4G, then the case will run normally.
ID: 3389

iozone_windows: fix iozone error for win11

---

qemu/tests/vdpa_dpdk.py

Before, querying PPS statistics twice in quick succession caused the second query to return underestimated values. Adding a 2 second delay ensures that the reported PPS is more accurate.
id: 3481

vdpa_dpdk: Add delay between queries for accurate pps stats

---

qemu/tests/cfg/check_block_size.cfg

"Timeout elapsed while waiting for install to finish" error for this case as no enough disk space. So extend the image size to 25G, then test it, the case run
normally.
ID: 3805

check_block_size: fix "Timeout elapsed while waiting for install" error

---

qemu/tests/cfg/dump_guest_core.cfg

Previously, older versions of gdb did not require specifying the /usr/libexec/qemu-kvm parameter. Now, newer versions require it to avoid errors. This patch updates the configuration accordingly.
ID: 1849
Signed-off-by: Wenkang Ji <wji@redhat.com>

dump_guest_core: fix gdb command

---

qemu/tests/cfg/netkvm_buffer_shortage.cfg
qemu/tests/netkvm_buffer_shortage.py

Under various conditions, when the host-to-device packet rate is high, we lose packets in QEMU due to a lack of guest-allocated buffers. Look also at https://github.com/virtio-win/kvm-guest-drivers-windows/issues/1012
ID: 2405

netkvm: Add a case for packet loss when slowly reusing memory buffers

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py
provider/vdpa_utils.py
qemu/tests/cfg/vdpa_dpdk.cfg
qemu/tests/vdpa_dpdk.py

This patch introduces an OVSHandler class and supporting functions:
- check ovs status and retrieve bridge/port information
- handle vdpa device integration with ovs
- add flow rules to ovs bridge
- provide flexible bridge and port info for vm
- add vdpa_dpdk case usage: add flows rules to ovs
- add netperf case usage: add flows rules to ovs and get vdpa ovs
port info
id:3441

Add vdpa_utils.py

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

I have to run qga test frequently, so it's necessary to add a piece of logic to install the specific package of qga from url.
ID: 1847

qemu_guest_agent: Add logic to get specific rpm from url

---

qemu/tests/cfg/qemu_guest_agent.cfg
qemu/tests/qemu_guest_agent.py

Add new api 'guest-network-get-route' to support qga query route info of Guest.
ID: 2588

qemu_guest_agent: Add new api support 'guest-network-get-route'

---

qemu/tests/balloon_check.py
qemu/tests/cfg/balloon_check.cfg

Virtio-balloon: since there's a product issue on OCP, enlarge the sleep
time on s390x to cover this. Also, since top cannot show unit when res
memory is lower than 1G, switch the command to "ps", also adding call 
trace check for call trace error
ID: 3701

Enlarge the sleep time when free-page-reporting is enabled

---

qemu/tests/cfg/mlock_on_fault.cfg
qemu/tests/mlock_on_fault.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/4125
mlock_on_fault: creates a new test case
New mlock case for testing the new 'on-fault' option
which its main benefit is a smaller memory usage
compared to 'on' option. In the logic values from
both options are compared and finally checked that
RSS remains equal or higher so no swap out is produced.
ID: 3807

mlock_on_fault: creates a new test case

---

generic/tests/cfg/netperf.cfg
generic/tests/netperf.py

Fix minor issues in Windows guest tests between host and VM
1. Initialize client_pub_ip as None for safe variable use
2. Changed server_mtu_cmd to use "set interface" instead of "set subinterface" for correct ipv4 interface configuratio
3. Add client_physical_nic check to avoid errors if not set
id: 3891, 3892, 3893

netperf: Windows small fix for host-vm tests

---

qemu/tests/cfg/vdpa_sim_blk_test.cfg

The latest XFS require the filesystem size
greater than 300M.
Change XFS to EXT4 to avoid this issue.
ID:2533

vdpa_sim_blk_test:fix XFS issue

---

qemu/tests/cfg/block_vhost_vdpa_test.cfg

The latest XFS require the filesystem size
greater than 300M.
Change XFS to EXT4 to avoid this issue.
ID:2875

block_vhost_vdpa_tes:fix XFS issue

---

qemu/tests/cfg/secure_execution.cfg
qemu/tests/cfg/secure_img.cfg

Secure exectuion: remove hardcode of device number for secure execution related cases on s390x, cause we are adding device number by default, reference to https://github.com/avocado-framework/avocado-vt/pull/4010
ID: 3491
Signed-off-by: bfu <bfu@redhat.com>

Remove device number hardcode for secure execution on s390x

---

qemu/tests/cfg/ksm_base.cfg

1.query_cmd = "cat /sys/kernel/mm/ksm/pages_sharing" is
changed to /proc/QEMU_PID/ksm_merging_pages
2.This ensures the correct  check path to the corresponding QEMU process
to ensure the stable operation of the test cases.
3.In the KAR repo the query_cmd will be modified as mentioned for below file
internal_cfg/host-os-setting.cfg
Signed-off-by: meshetty <meshetty@redhat.com>
ID: 3868

[ksm_base]: change the path for query command

---

qemu/tests/block_check_memory_leak.py
qemu/tests/cfg/block_check_memory_leak.cfg

Support overflow checking
ID:3495

block_check_memory_leak:add overflow test

---

qemu/tests/cfg/block_during_io.cfg
qemu/tests/cfg/virtio_storage_in_use.cfg

The remaining disk size of the C drive decreases
as the VM memory increases for win11. so if we start the vm on a big memory host, no enough space to do iozone on C drive. Adjust the memory for win11 to
4G, then the case will run normally.
ID: 4100

block_during_io.cfg: fix iozone error on system disk

---

qemu/tests/cfg/virtio_fs_migration_kill_daemon.cfg
qemu/tests/virtio_fs_migration_kill_daemon.py

1. Kill the virtiofsd process during the migration process
2. Check that the VM is still running but the mount dir is not accessable.
ID: 3260

virtio_fs_migration_kill_daemon: new case

---

qemu/tests/cfg/thin_provision_guest_fstrim.cfg

The latest LINUX guest xfs must be larger than 300MB. 
Increase the scsi_debug memory size to meet the requirement.
ID:3460

thin_provision_guest_fstrim:fix scsi_debug memory size is small

---

qemu/tests/cfg/block_iothread_test.cfg

Support iothread_vq_mapping feature for virtio-scsi-pci.
ID:3949

block_iothread_test:iothread_vq_mapping support for virtio-scsi-pci

---

provider/win_driver_installer_test.py
qemu/tests/cfg/win_virtio_driver_install_by_installer.cfg
qemu/tests/win_virtio_driver_installer_uninstall.py
qemu/tests/win_virtio_driver_update_by_installer.py

Add supoport to test viomem related from
the installer.
ID: 3171, 3191, 3192, 3193, 3194

win_virtio_driver_install_by_installer: support viomem test

---

generic/tests/nfs_corrupt.py

The is_mounted search should look for the mount information with the mount destination.
ID:4241

nfs_corrupt:fix findmnt default src issue

---

qemu/tests/cfg/uefi_check_resolution.cfg
qemu/tests/uefi_check_resolution.py

Failed to change resolution due to newly added BootManagerMenuApp, pressing ESC in the splash screen enter the BootManagerMenuApp instead of firmware configuration app on the latest system, so need to update the value of parameter enter_change_preferred in test case.
ID: 4209

uefi_check_resolution: add support for BootManagerMenuApp

---

qemu/tests/cfg/uefi_disable_firmware_config.cfg
qemu/tests/uefi_disable_firmware_config.py

A new EDK2 test case to verify the functionality of disabling firmware configuration application via QEMU's -fw_cfg option. When disabled, users cannot access firmware setup interface to modify boot settings.
The test will:
- Verify boot device visibility in BootManagerMenuApp
- Validate expected behavior when toggling enable/disable states
ID: 4211

uefi_disable_firmware_config: creates a new test case

---

qemu/tests/cfg/device_option_check.cfg

The --page 0x83 is not expected in latest Linux.
Using --page di or -i directly to get the
device identification.
ID:3925

device_option_check:fix sq_inq paremeter error
